[VAS] Story #10341: leaves navigation with only results
ProgrammeVitam/vitam-ui pull request #1001
Opened 2022-10-05 16:13 UTC by laedanrex

## Description
Bloc "Position de rattachement" de la navigation - afficher seulement les nœud ayant des résultats

## Type de changement:
* Nouveau Code

## Documentation:

## Tests:
manuel
environnement
TU

## Migration:

## Checklist:

[x] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

VAS (Vitam Accessible en Service)

2022-10-10 14:04 UTC, oussamasic requested changes

2022-10-10 14:04 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.handler.spec.ts
> +import { FilingHoldingSchemeNode } from 'ui-frontend-common';
tu peux ajouter le texte du copyright

2022-10-10 14:04 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.handler.spec.ts
> +  fit('foundNodeAndSetCheck with invalid id is false', () => {
tu peux enlever le focus sur ces tests

2022-10-10 14:04 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.handler.ts
> +        // pas son enfant
commentaire à supprimer

2022-10-10 14:04 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.component.spec.ts
> +  it('should create', () => {
tests à compléter ou à supprimer

2022-10-10 14:04 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.component.spec.ts
> +import { LeavesTreeComponent } from './leaves-tree.component';
Il manque le texte du copyright

2022-10-12 08:26 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
> +      tap(() => {
On peut supprimer l'opérateur `tap()`

2022-10-12 08:28 UTC, depysk approved these changes

2022-10-13 13:55 UTC, oussamasic approved these changes

2022-10-14 13:16 UTC, merged