Delete using collect context call for DSL creator
ProgrammeVitam/vitam-ui pull request #1008
Opened 2022-10-12 13:17 UTC by GhrabSaifEddine

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2022-10-13 14:45 UTC, oussamasic commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/MetadataSearchCriteriaUtils.java
> +                        final Query queryForExistedObjects = VitamQueryHelper
- A tester, si cette modification ne casse pas la recherche dans archive-search.
- Vérifier aussi les TUs coté archive-search.

2022-10-31 10:51 UTC, oussamasic approved these changes

2022-10-31 11:12 UTC, oussamasic requested changes

2022-10-31 11:12 UTC, oussamasic commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/MetadataSearchCriteriaUtils.java
> +                            .buildSubQueryByOperator(ArchiveSearchConsts.ARCHIVE_UNIT_OBJECTS, value,
il y a des TUs cassés sur archive-search

2022-10-31 11:13 UTC, oussamasic requested changes
il y a des TUs à corriger sur archive-search

2022-10-31 11:54 UTC, mohatizaoui approved these changes

2022-10-31 13:47 UTC, oussamasic approved these changes

2022-11-02 09:09 UTC, GhrabSaifEddine commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/MetadataSearchCriteriaUtils.java
> +                        final Query queryForExistedObjects = VitamQueryHelper
Pipeline de build : https://jenkins.dev.programmevitam.fr/jenkins/blue/organizations/jenkins/vitamui-build/detail/clean_collect_context_call/3/pipeline/

2022-11-02 10:27 UTC, merged