story #10369 list transactions
ProgrammeVitam/vitam-ui pull request #1065
Opened 2022-10-28 08:21 UTC by mohatizaoui

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2022-10-31 09:37 UTC, oussamasic requested changes

2022-10-31 09:37 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/transactions/transaction-list/transaction-list.component.html
> +      <div *ngIf="infiniteScrollDisabled && transactionService.canLoadMore && !pending; then loadMore"></div>-->
To delete

2022-10-31 09:37 UTC, oussamasic commented on api/api-collect/collect-external-client/src/main/java/fr/gouv/vitamui/collect/external/client/CollectTransactionExternalRestClient.java
> +
on peux chercher des UAs avec le projectId ?
normalement c'est avec l'id d'une transaction

2022-10-31 09:37 UTC, oussamasic commented on api/api-collect/collect-external-client/src/main/java/fr/gouv/vitamui/collect/external/client/CollectTransactionExternalRestClient.java
> +    public CollectTransactionDto getTransactionById(ExternalHttpContext context, String projectId) {
```suggestion
    public CollectTransactionDto getTransactionById(ExternalHttpContext context, String transactionId) {
```

2022-10-31 09:37 UTC, oussamasic commented on api/api-collect/collect-internal-client/src/main/java/fr/gouv/vitamui/collect/internal/client/CollectTransactionInternalRestClient.java
> +    public ArchiveUnitsDto searchCollectProjectArchiveUnits(InternalHttpContext context, String projectId,
```suggestion
    public ArchiveUnitsDto searchCollectUnitsByTransactionId(InternalHttpContext context, String transactionId,
```

2022-10-31 09:37 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/ProjectInternalController.java
> +
Il manque les sanitycheck sur les différents paramètres avant le debug

2022-10-31 09:37 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/ProjectInternalService.java
> +         */
To delete

2022-10-31 09:37 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/ProjectInternalService.java
> +            return new PaginatedValuesDto<>(collectTransactionDtos, 1, MAX_RESULTS, false);
Est-ce qu'il y a une contrainte pour limiter le nombre des résultats retournés à 10000 ?

2022-10-31 09:37 UTC, oussamasic commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/collect/CollectService.java
> +        LOGGER.debug("projectId : {}", transactionId);
```suggestion
        LOGGER.debug("transactionId : {}", transactionId);
```

2022-10-31 09:37 UTC, oussamasic commented on deployment/scripts/mongod/6.rc.0/13_update_collecte_profiles_to_add_abort_reopen_transaction_role.js.j2
> +print("START 11_update_collecte_profiles_to_add_abort_reopen_transaction_role.js");
```suggestion
print("START 13_update_collecte_profiles_to_add_abort_reopen_transaction_role.js");
```

2022-10-31 09:37 UTC, oussamasic commented on deployment/scripts/mongod/6.rc.0/14_update_collecte_contexts_to_add_abort_reopen_transaction_role.js.j2
> +print("START 12_update_collecte_contexts_to_add_abort_reopen_transaction_role.js");
```suggestion
print("START 14_update_collecte_contexts_to_add_abort_reopen_transaction_role.js");
```

2022-10-31 09:37 UTC, oussamasic commented on ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/ProjectController.java
> +        SanityChecker.sanitizeCriteria(criteria);
un sanity à ajouter aussi sur projectId.

2022-10-31 09:37 UTC, oussamasic commented on api/api-collect/collect-external-client/src/main/java/fr/gouv/vitamui/collect/external/client/CollectTransactionExternalRestClient.java
> +
LOGGER inutile, à supprimer

2022-10-31 09:37 UTC, oussamasic commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectExternalController.java
> +        SanityChecker.sanitizeCriteria(direction);
un autre sanitize à ajouter sur le projectId

2022-10-31 09:37 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/ProjectInternalController.java
> +    @GetMapping(params = {"page", "size"}, value = "/{id}" + TRANSACTIONS)
tu peux utiliser CommonConstants.PATH_ID au lieu de "/{id}"

2022-10-31 09:37 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/TransactionInternalController.java
> +        ParameterChecker.checkParameter("The Identifier is a mandatory parameter: ", id);
à mettre dans une constante : "The Identifier is a mandatory parameter: "

2022-10-31 09:37 UTC, oussamasic commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/collect/CollectService.java
> +     * get all created projects from Vitam
```suggestion
     * get all created transactions from Vitam
```

2022-10-31 09:37 UTC, oussamasic commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/collect/CollectService.java
> +     * @return
```suggestion
     * @param vitamContext
      * @param projectId
     * @return
```

2022-10-31 09:37 UTC, oussamasic commented on ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/TransactionController.java
> +        SanityChecker.checkSecureParameter(transactionId);
ligne en double (meme chose que la ligne 144) à supprimer

2022-10-31 09:37 UTC, oussamasic commented on ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/TransactionController.java
> +        SanityChecker.checkSecureParameter(transactionId);
ligne en double, à supprimer

2022-10-31 09:37 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
> +      this.fetchUserAccessContractFromExternalParameters();
pourquoi on récupère le contrat d'accès dans Collect ? Normalement on a pas besoin du contrat d'accès dans ce module

2022-10-31 09:37 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
> +    this.accessContractSub?.unsubscribe();
problème de formatage ?

2022-10-31 09:37 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/collect-routing.module.ts
> +    path: 'transactions/:id',
```suggestion
    path: ':projectId/transactions',
```

2022-10-31 09:37 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/collect-routing.module.ts
> +    path: 'archive-search-collect/:id/:transactionId',
```suggestion
    path: 'collect-units/:projectId/:transactionId',
```

2022-10-31 09:37 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-list/project-list.component.ts
> +    this.router.navigate(['collect/transactions', project.id], {queryParams: {projectName: project.messageIdentifier}});
à mettre à jour, après la modification des path dans le routing file

2022-10-31 09:37 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/transactions/transaction-list/transaction-list.component.html
> +         <div *ngIf="infiniteScrollDisabled && transactionService.canLoadMore && !pending; then loadMore"></div>-->
to delete

2022-10-31 09:37 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/transactions/transaction-list/transaction-list.component.spec.ts
> +  it('should create', () => {
à compléter avec d'autres tests

2022-10-31 09:37 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/transactions/transaction-list/transaction-list.component.spec.ts
> +import { ComponentFixture, TestBed } from '@angular/core/testing';
ajoute le texte du copyright

2022-10-31 09:37 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/transactions/transaction-list/transaction-list.component.ts
> +import {Component, OnInit} from '@angular/core';
il manque le texte du copyright

2022-10-31 09:37 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/transactions/transaction-resolver.service.ts
> +/*
texte à modifier, c'est l'ancien texte du copyright

2022-10-31 09:37 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/transactions/transactions.component.ts
> +
pourquoi ce composant ? on fait presque rien dans ce composant juste l'affichage de l'entete et après le composant transactionsList, je pense qu'on peux utiliser juste le composant listTransactions

2022-10-31 09:37 UTC, oussamasic commented
Il manque des TUs sur les deux partie Java et Angular.

2022-10-31 11:40 UTC, mohatizaoui commented on ui/ui-frontend/projects/collect/src/app/collect/transactions/transactions.component.ts
> +
il y aura après la recherche transaction avec le filtre etc

2022-11-04 11:04 UTC, oussamasic approved these changes

2022-11-04 11:04 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-list/project-list.component.ts
> +    this.router.navigate(['collect/transactions', project.id], {queryParams: {projectName: project.messageIdentifier}});
après discussion, à faire dans une pr de clean code

2022-11-04 12:47 UTC, anasstsdi approved these changes

2022-11-14 08:30 UTC, merged