story#10388 : update collect api
ProgrammeVitam/vitam-ui pull request #1068
Opened 2022-10-28 16:40 UTC by anasstsdi

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2022-10-31 10:43 UTC, oussamasic requested changes

2022-10-31 10:43 UTC, oussamasic commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectExternalController.java
> +    @Secured(ServicesData.ROLE_CREATE_PROJECTS)
un nouveau rôle à ajouter, par exemple ROLE_CREATE_TRANSACTION

2022-10-31 10:43 UTC, oussamasic commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectExternalController.java
> +        SanityChecker.sanitizeCriteria(collectTransactionDto);
un sanity check à ajouter sur l'id aussi

2022-10-31 10:43 UTC, oussamasic commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectExternalController.java
> +    @GetMapping(CommonConstants.PATH_ID  + "/transactions")
Il manque la sécurisation de l'API

2022-10-31 10:43 UTC, oussamasic commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/TransactionExternalController.java
> +    @Secured(ServicesData.ROLE_UPDATE_PROJECTS)
rôle à modifier, avec un autre rôle par exemple : ROLE_UPDATE_TRANSACTION

2022-10-31 10:43 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/ProjectInternalController.java
> +        SanityChecker.sanitizeCriteria(collectTransactionDto);
il manque un sanity check sur l'id

2022-10-31 10:43 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/ProjectInternalController.java
> +    @GetMapping(CommonConstants.PATH_ID  + "/transactions")
c'est le même url qu'on aussi pour la liste des transactions d'un projet avec le même verbe

2022-10-31 10:43 UTC, oussamasic commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectExternalController.java
> +    @GetMapping(CommonConstants.PATH_ID  + "/transactions")
c'est le même url qu'on aussi pour la liste des transactions d'un projet avec le même verbe

2022-10-31 10:43 UTC, oussamasic commented on api/api-collect/collect-external-client/src/main/java/fr/gouv/vitamui/collect/external/client/CollectExternalRestClient.java
> +    public CollectTransactionDto getLastTransactionForProjectId(String id, ExternalHttpContext context) {
un point d'attention sur l'url, c'est même qu'on utilise pour la récupération de la liste des transaction

2022-10-31 10:43 UTC, oussamasic commented on api/api-collect/collect-internal-client/src/main/java/fr/gouv/vitamui/collect/internal/client/CollectInternalRestClient.java
> +            UriComponentsBuilder.fromHttpUrl(getUrl() + CommonConstants.PATH_ID + "/transactions" );
url à modifier

2022-10-31 10:43 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/converters/TransactionConverter.java
> +    public static CollectTransactionDto toVitamUiDto(TransactionDto collectTransactionDto) {
pour les converters tu peux utiliser la méthode copyProperties de BeanUtils

2022-10-31 10:43 UTC, oussamasic commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/collect/CollectService.java
> +     * @return
```suggestion
     * @param vitamContext
     * @param transactionDto
     * @param projectId
     * @return
```

2022-10-31 10:43 UTC, oussamasic commented on ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/ProjectController.java
> +        SanityChecker.sanitizeCriteria(collectTransactionDto);
il manque un sanity check sur l'id

2022-10-31 10:43 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/core/api/project-api.service.ts
> +  }
url à revoir

2022-10-31 10:43 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/transactions.service.ts
> +export class TransactionsService {
Il y aura des conflits à résoudre avec la PR de Mohamed

2022-11-03 13:28 UTC, anasstsdi commented on ui/ui-frontend/projects/collect/src/app/collect/projects/transactions.service.ts
> +export class TransactionsService {
On va le resoudre pas le choix

2022-11-03 17:01 UTC, oussamasic approved these changes

2022-11-09 14:30 UTC, bbenaissa requested changes

2022-11-09 14:30 UTC, bbenaissa commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/ProjectInternalService.java
> +            LOGGER.error(((RequestResponseOK) requestResponse).getFirstResult().toString());
Le log.error est mal placé

2022-11-09 14:30 UTC, bbenaissa commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/ProjectInternalService.java
> +            List<CollectTransactionDto> collectTransactionDtos = TransactionConverter.toVitamuiDtos(transactionDtos);
Est ce qu'il y a une vérification sur le tableau, étant donné qu'on accède par index juste après?

2022-11-09 14:30 UTC, bbenaissa commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/collect/CollectService.java
> +        LOGGER.debug("transactionid : {}", transactionId);
Peut etre un texte de log plus claire ?

2022-11-09 14:30 UTC, bbenaissa commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/collect/CollectService.java
> +        LOGGER.debug("projectId : {}", projectId);
Peut etre un texte de log plus claire ?

2022-11-09 14:30 UTC, bbenaissa commented on deployment/scripts/mongod/6.rc.0/31_update_collecte_profiles_to_add_transaction_roles.js.j2
> +          {"name": "ROLE_CREATE_TRANSACTIONS"},
Pas d'ajout du role ROLE_SEND_TRANSACTIONS ?

2022-11-09 14:30 UTC, bbenaissa commented on deployment/scripts/mongod/6.rc.0/32_update_collecte_contexts_to_add_transaction_roles.js.j2
> +            "ROLE_CREATE_TRANSACTIONS",
Pas d'ajout du role ROLE_SEND_TRANSACTIONS ?

2022-11-09 14:58 UTC, bbenaissa approved these changes

2022-11-09 15:22 UTC, merged