item#10454 Naviguer dans l'arborescence des unités d'archives standard
ProgrammeVitam/vitam-ui pull request #1073
Opened 2022-11-07 09:44 UTC by GhrabSaifEddine

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2022-11-10 09:56 UTC, oussamasic requested changes

2022-11-10 09:56 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/services/archive-shared-data.service.ts
> +
to delete

2022-11-10 09:56 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/services/archive-shared-data.service.ts
> +  // private rattachementUnitIds = new BehaviorSubject<Map<string,Unit>>(new Map());
to delete

2022-11-10 09:56 UTC, oussamasic commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/UpdateOperationDto.java
> +    private String systemId;
systemId c'est une nouvelle info envoyé par Vitam ?

2022-11-10 09:56 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/filing-holding-scheme.component.ts
> +      category: "FIELDS",
```suggestion
      category: SearchCriteriaTypeEnum.FIELDS,
```

2022-11-10 09:56 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/leaves-tree/leaves-tree.component.scss
> +@import '~ui-frontend-common/sass/variables/colors';
tu peux supprimer les commentaires ajoutés dans ce fichier

2022-11-10 09:56 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/models/utils.ts
> +export class Pair {
```suggestion
export interface Pair {
```

2022-11-10 09:56 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/models/utils.ts
> +export class VitamInternalFields {
```suggestion
export enum VitamInternalFields {
```

2022-11-10 13:25 UTC, GhrabSaifEddine commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/UpdateOperationDto.java
> +    private String systemId;
nn elle est ancienne, c'est une propriété SEDA

2022-11-10 13:34 UTC, GhrabSaifEddine commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/models/utils.ts
> +export class Pair {
Pourquoi ?

2022-11-10 13:38 UTC, GhrabSaifEddine commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/leaves-tree/leaves-tree.component.scss
> +@import '~ui-frontend-common/sass/variables/colors';
ça fait rien de les garder, c'est plutôt mieux pour la doc du dev

2022-11-14 08:59 UTC, mohatizaoui approved these changes

2022-11-14 09:46 UTC, oussamasic approved these changes

2022-11-14 15:25 UTC, merged