[VAS] Bug/vas-10222: Fix computing facets on big results count
ProgrammeVitam/vitam-ui pull request #1078
Opened 2022-11-07 17:23 UTC by bbenaissa

## Description

l'objectif de cette PR est de gérer correctement le comportement de calcul des facettes lorsque nous avons un nombre important de résultats > 10000 

## Contributeur

VAS (Vitam Accessible en Service)

2022-11-08 11:10 UTC, laedanrex approved these changes

2022-11-08 11:12 UTC, laedanrex commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-appraisal-rules-facets/search-appraisal-rules-facets.component.ts
> +      archiveUnitWithRules = this.handleWaitingToRecalculateRulesFacets();
peut etre inliné

2022-11-08 14:10 UTC, oussamasic requested changes

2022-11-08 14:10 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/models/operation/facet-details.interface.ts
> +  totalResults: any;
c'est mieux de laisser le type number

2022-11-09 17:03 UTC, oussamasic approved these changes

2022-11-09 17:06 UTC, merged