item#10623 Ajout des tests sur collect
ProgrammeVitam/vitam-ui pull request #1110
Opened 2022-11-24 16:09 UTC by GhrabSaifEddine

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2022-11-28 14:33 UTC, anasstsdi approved these changes

2022-11-28 15:41 UTC, mascoun approved these changes

2022-11-28 16:59 UTC, oussamasic commented
- Des conflits à corriger avant le merge 
- Texte du copyright à changer

2022-11-28 17:00 UTC, oussamasic requested changes

2022-11-28 17:00 UTC, oussamasic commented on api/api-collect/collect-internal-client/pom.xml
> +        </dependency>
elle sert à quoi cette lib ?

2022-11-28 17:00 UTC, oussamasic commented on api/api-collect/collect-internal-client/src/main/java/fr/gouv/vitamui/collect/internal/client/CollectInternalRestClient.java
> +    private static final String LAST_TRANSACTION = "/last-transaction";
à ajouter dans CommonConstants (pour éviter la déclaration de la mm constante dans plusieurs classe java)

2022-11-28 17:00 UTC, oussamasic commented on api/api-collect/collect-internal/pom.xml
> +        </dependency>
idem

2022-11-29 09:24 UTC, GhrabSaifEddine commented on api/api-collect/collect-internal/pom.xml
> +        </dependency>
?

2022-11-29 10:08 UTC, GhrabSaifEddine commented on api/api-collect/collect-internal-client/pom.xml
> +        </dependency>
auto remplissage des POJO ( tu peux checker son utilisation dans les tests unitaires )

2022-11-29 15:25 UTC, oussamasic approved these changes

2022-11-30 16:42 UTC, merged