[WIP] Story/Vas-10780: update technical docs
ProgrammeVitam/vitam-ui pull request #1133
Opened 2022-12-05 17:09 UTC by bbenaissa

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2023-01-13 15:11 UTC, oussamasic commented on docs/DAT/docs/dat_vitamui/architecture/mdd.md
> +applicationName dans un groupe.
formatage à vérifier

2023-01-13 15:11 UTC, oussamasic commented on docs/DAT/docs/dat_vitamui/architecture/services_externes.md
> +
à compléter

2023-01-13 15:11 UTC, oussamasic commented on docs/DAT/docs/dat_vitamui/architecture/services_internes.md
> +L'utililisation du protocole HTTPS permet de chiffrer les tokens et les informations sensibles qui sont transportées
```suggestion
L’utilisation du protocole HTTPS permet de chiffrer les tokens et les informations sensibles qui sont transportées
```

2023-01-13 15:11 UTC, oussamasic commented on docs/DAT/docs/dat_vitamui/architecture/services_internes.md
> +### Service collect-internal
à compléter

2023-01-13 15:11 UTC, oussamasic commented on docs/DAT/docs/dat_vitamui/architecture/external_param_profile.md
> +paramétrage externe (ExternalParameters).
à mettre dans la même ligne

2023-03-09 02:59 UTC, TDevillechabrolle commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx One – Scan Summary & Details** – [213c8899\-4503\-483c\-90bb\-886ea97dc99d](https://eu.ast.checkmarx.net/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/scans?id=213c8899-4503-483c-90bb-886ea97dc99d&branch=feature%2Fvas-10780-update-technical-documentation)

### Fixed Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/213c8899-4503-483c-90bb-886ea97dc99d/sast/description/117/9884244256835554923)|/api/api\-collect/collect\-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/SearchCriteriaHistoryExternalController\.java: [94](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas-10780-update-technical-documentation//api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/SearchCriteriaHistoryExternalController.java#L94)|[Attack Vector](https://eu.ast.checkmarx.net/results/213c8899-4503-483c-90bb-886ea97dc99d/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=NgTPTAdsAtXJYQrIh%2FdhTG%2BKwWQ%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/213c8899-4503-483c-90bb-886ea97dc99d/sast/description/117/9884244256835554923)|/api/api\-referential/referential\-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OntologyExternalController\.java: [162](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas-10780-update-technical-documentation//api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OntologyExternalController.java#L162)|[Attack Vector](https://eu.ast.checkmarx.net/results/213c8899-4503-483c-90bb-886ea97dc99d/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=kG2y%2F0W4xwv73nC2OQS7Tpu8qI4%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/213c8899-4503-483c-90bb-886ea97dc99d/sast/description/117/9884244256835554923)|/api/api\-archive\-search/archive\-search\-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/rest/SearchCriteriaHistoryExternalController\.java: [108](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas-10780-update-technical-documentation//api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/rest/SearchCriteriaHistoryExternalController.java#L108)|[Attack Vector](https://eu.ast.checkmarx.net/results/213c8899-4503-483c-90bb-886ea97dc99d/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=a9h97LWkI0ranFd%2F6mFFJPrZT5g%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/213c8899-4503-483c-90bb-886ea97dc99d/sast/description/117/9884244256835554923)|/ui/ui\-archive\-search/src/main/java/fr/gouv/vitamui/archives/search/rest/SearchCriteriaHistoryController\.java: [106](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas-10780-update-technical-documentation//ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/rest/SearchCriteriaHistoryController.java#L106)|[Attack Vector](https://eu.ast.checkmarx.net/results/213c8899-4503-483c-90bb-886ea97dc99d/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=k5iT7tuIIzXaGX8LJLf5%2FBJuWP4%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/213c8899-4503-483c-90bb-886ea97dc99d/sast/description/117/9884244256835554923)|/api/api\-iam/iam\-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/SubrogationExternalController\.java: [189](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas-10780-update-technical-documentation//api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/SubrogationExternalController.java#L189)|[Attack Vector](https://eu.ast.checkmarx.net/results/213c8899-4503-483c-90bb-886ea97dc99d/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=C2vpG1%2FCVaAhfz35A%2Flth62Xx7M%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/213c8899-4503-483c-90bb-886ea97dc99d/sast/description/117/9884244256835554923)|/ui/ui\-referential/src/main/java/fr/gouv/vitamui/referential/rest/OntologyController\.java: [191](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas-10780-update-technical-documentation//ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/OntologyController.java#L191)|[Attack Vector](https://eu.ast.checkmarx.net/results/213c8899-4503-483c-90bb-886ea97dc99d/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=rL2vtg8SghIJKIS6AdBG01uL1jM%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/213c8899-4503-483c-90bb-886ea97dc99d/sast/description/117/9884244256835554923)|/ui/ui\-referential/src/main/java/fr/gouv/vitamui/referential/rest/SecurityProfileController\.java: [190](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas-10780-update-technical-documentation//ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/SecurityProfileController.java#L190)|[Attack Vector](https://eu.ast.checkmarx.net/results/213c8899-4503-483c-90bb-886ea97dc99d/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=qaxdL39S%2BWl1l7gNopt0eUYe%2Bto%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/213c8899-4503-483c-90bb-886ea97dc99d/sast/description/117/9884244256835554923)|/api/api\-referential/referential\-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/SecurityProfileExternalController\.java: [160](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas-10780-update-technical-documentation//api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/SecurityProfileExternalController.java#L160)|[Attack Vector](https://eu.ast.checkmarx.net/results/213c8899-4503-483c-90bb-886ea97dc99d/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=WRUyvm8AvQWK9JDnAg9EQ5jm4ZY%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/213c8899-4503-483c-90bb-886ea97dc99d/sast/description/117/9884244256835554923)|/ui/ui\-collect/src/main/java/fr/gouv/vitamui/collect/rest/ProjectArchiveUnitController\.java: [106](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas-10780-update-technical-documentation//ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/ProjectArchiveUnitController.java#L106)|[Attack Vector](https://eu.ast.checkmarx.net/results/213c8899-4503-483c-90bb-886ea97dc99d/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=1%2Fva0ss8lCBoH%2FisyFx7zdf5aDE%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.chec [...]

2023-03-30 16:35 UTC, GiooDev requested changes
Pas mal de sauts de lignes inutiles et quelques fautes à revoir.

Uniformiser le nommage des fichiers par exemple en utilisant_que_des_underscores :)

2023-03-30 16:35 UTC, GiooDev commented on docs/fr/architacture-generale.odp
Quitte à déplacer le fichier, autant le renommer correctement :)

architecture au lieu de architacture
Et utiliser des _ au lieu des tirets pour uniformisation avec les autres fichiers.

2023-03-30 16:35 UTC, GiooDev commented on docs/fr/architecture/Installation-poste-de-dev.md
utiliser des _ au lieu des tirets pour uniformisation avec les autres fichiers.

2023-03-30 16:35 UTC, GiooDev commented on docs/fr/architecture/Regles-de-codage.md
utiliser des _ au lieu des tirets pour uniformisation avec les autres fichiers.

2023-03-30 16:35 UTC, GiooDev commented on docs/fr/architecture/images/securisationProd.png
utiliser des _ au lieu des tirets pour uniformisation avec les autres fichiers.

2023-03-30 16:35 UTC, GiooDev commented on docs/fr/exploitation/sections/pré-installation.md
> +chemain: `/vitamui/conf/iam-internal/customer-init.yml`
Saut de ligne inutile ici et erreur sur chemain au lieu de chemin

2023-03-30 16:35 UTC, GiooDev commented on docs/fr/exploitation/sections/pré-installation.md
> +organisation créée grâce à `users`:
saut de ligne inutile

2023-03-30 16:35 UTC, GiooDev commented on docs/fr/exploitation/sections/pré-installation.md
> +  renseigner
saut de ligne inutile

2023-03-30 16:35 UTC, GiooDev commented on docs/fr/exploitation/sections/pré-installation.md
> +  utilisateur.
saut de ligne inutile

2023-04-05 15:08 UTC, GiooDev requested changes

2023-04-05 15:08 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +    | -------------- | ----- | ------- | ------- |
Décallage inutile pour tous les tableaux

2023-04-05 15:08 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +du système. Il ne peut pas par exemple créer une nouvelle organisation, si ce rôle ne lui pas été donné à l'origine.
Beaucoup de sauts de lignes inutiles dans tout ce document.

2023-04-05 15:08 UTC, GiooDev commented on docs/fr/architecture/sections/implementation.md
> +   qu’il souhaite appeler
idem dans ce document

2023-04-05 15:08 UTC, GiooDev commented on docs/fr/installation/metadata.yaml
> +    - Le programme Vitam
Remplacer par: Programme Vitam

2023-04-05 15:21 UTC, oussamasic requested changes

2023-04-05 15:21 UTC, oussamasic commented on docs/fr/architecture/sections/architecture.md
> +dans le cadre d'un processus d'authentification mutuel (Machine To Machine/M2M). Dans la solution VITAMUI, les
attention au formatage au niveau du fichier.
beaucoup de retour à la ligne

2023-04-05 15:21 UTC, oussamasic commented on docs/fr/architecture/sections/architecture.md
> +            - ROLE_GET_ACCESS_CONTRACTS
on aura pas besoin d'ajouter une petite explication pour chaque rôle en question.

2023-04-05 15:21 UTC, oussamasic commented on docs/fr/architecture/sections/architecture.md
> +ne sera pas récupérée dans VitamUI). C'est recommandé d'ajouter aussi les ontologies dans la base de données de Vitam.
```suggestion
Il est nécessaire de déposer un fichier JSON dans **deployment/environments/ontology/** avec le nom : **external_ontology_fields.json** (c'est obligatoire d'avoir un fichier avec ce nom sinon la nouvelle liste des ontologies ne sera pas récupérée dans VitamUI). C'est recommandé d'ajouter aussi les ontologies dans la base de données de Vitam.
```

2023-04-05 15:42 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +            - ROLE_GET_ACCESS_CONTRACTS
Je suis d'accord, ce n'est pas ce qui était initialement demandé je pense, si c'est pour dupliquer le contenu du fichier `customer-init.yml`, ça sert à rien et ça sera contreproductif car il faudra maintenir à jour les 2 endroits.

Dans ce cas là, autant documenter l'existence de ce fichier pour plus de détails.

2023-04-05 15:46 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +ne sera pas récupérée dans VitamUI). C'est recommandé d'ajouter aussi les ontologies dans la base de données de Vitam.
Il est nécessaire de déposer le fichier d'ontology au format JSON sous `environments/ontology/` avec le nom: `external_ontology_fields.json`.

Le fichier doit obligatoirement être nommé ainsi afin qu'il puisse être récupéré dans VitamUI. Il est aussi recommandé d'ajouter ces ontologies dans la base de données de Vitam.

2023-04-06 09:50 UTC, bbenaissa commented on docs/fr/architecture/sections/architecture.md
> +            - ROLE_GET_ACCESS_CONTRACTS
le customer-init ne contient pas l'ensemble des roles, il y a des roles qui sont crées par le code

2023-04-06 16:35 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +            - ROLE_GET_ACCESS_CONTRACTS
Ok. On pourra prévoir une refacte de cette partie pour que ce soit un peu plus digeste à l'occasion :)

2023-04-14 09:44 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +    | ------------------------ | ------------------- | -------------------------- | ------------------- |
Décalage non nécessaire sur les tableaux suivants

2023-04-14 09:54 UTC, GiooDev commented on docs/fr/architecture/sections/implementation.md
> +les fichiers unit systemd, les fichiers de configurations, les scripts d'installation RPM executes.
Saut de ligne inutile

2023-04-14 09:54 UTC, GiooDev commented on docs/fr/architecture/sections/implementation.md
> +(fichier **vitamui/cots/vitamui-consul/pom.xml**). Ce nom de version sera transmis en parametre du makefile qui telechargera le binaire consul dans la bonne version
ici aussi

2023-04-14 09:54 UTC, GiooDev commented on docs/fr/architecture/sections/implementation.md
> +(fichier **vitamui/cots/vitamui-logstash/pom.xml**). Ce nom de version sera transmis en parametre du Makefile qui telechargera l'archive de source logstash correspondant a la version choisie.
ici aussi

2023-04-14 09:54 UTC, GiooDev commented on docs/fr/architecture/sections/implementation.md
> +contiendra:
et là

2023-04-14 09:55 UTC, GiooDev commented on docs/fr/exploitation/sections/pré_installation.md
> +dans `deployment/environnement/group_vars/all/vitamui_vars.yml`.
Saut de ligne en trop

2023-04-14 09:55 UTC, GiooDev commented on docs/fr/exploitation/sections/pré_installation.md
> +supérieur.
et là aussi

2023-04-14 09:57 UTC, GiooDev commented on docs/fr/exploitation/sections/pré_installation.md
> +* profiles: Liste des profiles dont les applications seront accessibles via ce profil. Le champ "name" des profils est à renseigner Enfin, il est également possible de renseigner des utilisateurs qui
Saut de ligne manquant ici !

2023-04-14 10:38 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +Le service externe a pour responsabilité de sécuriser les accès en effectuant les différentes étapes de vérifications des droits (générale, tenant, rôles, groupes, etc.) et de déterminer les droits r
un espace de trop ! :D

2023-04-14 10:39 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +.
Saut de ligne en trop

2023-04-14 10:39 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +* expiration de session par délai d'inactivité : la session expire si aucune action n'est faite (par l'utilisateur) au   bout du délai d'inactivité (session Token)
espace de trop

2023-04-14 10:39 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +entités.
ici aussi

2023-04-14 12:26 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +  POST /pastis-api/profile: Create Archival Profile
Pourquoi pas des * pour chacune des lignes comme sur les autres chapitres ?

2023-04-14 12:26 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +GET /pastis-api/archival-profile: Get entity
Idem ici, * pour chaque ligne

2023-04-14 12:27 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +Au niveau de chaque application on a la possibilité d'avoir plusieurs profils, pour distinguer entre les utilisateurs qui ont droits à certaines fonctionnalitées et d'autres qui n'ont pas les droits.
Enlever le <br/> ici

2023-04-14 12:28 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +- Example pour afficher un composant pour les users qui ont le role ROLE_SEARCH_WITH_RULES <br/>
Exemple au lieu de Example et <br/> a retirer

2023-04-14 12:29 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +  `<ng-template [vitamuiCommonHasRole]="dataToSearchWithRules">`
Mettre un bloc de code plutôt que des lignes de codes

```
```html
.../...
```
```

2023-04-14 12:29 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +`dataToSearchWithRules = {
Idem ici, bloc de code

2023-04-14 12:31 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +* Les journaux constituent un élément central de cette sécurité systémique Utilisation des journaux vitam NF Z42-013
Il manque un . pour séparer les 2 éléments de la phrase non ?

2023-04-14 12:31 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +      pour finir la transaction.
Saut de ligne en trop

2023-04-14 12:31 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +* Un appel REST => Une ou plusieurs opération métier => ensemble d’events => le premier sera l'événement primaire ( Primary) et les suivants secondaires (Secondary)
espace inutile dans la parenthèse.

2023-04-14 12:31 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +    | --------------------- | ------ | ---------------------- | ----------- |
espaces inutiles

2023-04-14 12:31 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +Le contexte applicatif permet d’attribuer à une application cliente selon son certificat X509 transmis lors de la
saut de ligne inutile

2023-04-14 14:29 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +* DELETE /collect-api/projects/{id}: * DELETE project
Des * en trop dans la description du point d'API.

2023-04-14 14:32 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +  ``` html
attention, je pense pas qu'il faut pas mettre un espace entre ``` et html

2023-04-14 14:32 UTC, GiooDev commented on docs/fr/architecture/sections/architecture.md
> +``` js
idem, pas d'espace

2023-04-14 14:34 UTC, GiooDev commented on docs/fr/architecture/sections/implementation.md
> +  VITAM : <http://www.programmevitam.fr/ressources/DocCourante/html/installation/annexes/10-overview_certificats.html>
sauts de ligne en trop

2023-04-14 14:34 UTC, GiooDev commented on docs/fr/architecture/sections/implementation.md
> +  fournis par la PKI, un certificat sera généré pour s'interfacer avec Vitam.
saut de ligne en trop

2023-04-14 14:35 UTC, GiooDev commented on docs/fr/architecture/sections/implementation.md
> +adresse : <http://www.programmevitam.fr/ressources/DocCourante/html/archi/securite/20-certificates.html>
saut de ligne en trop

2023-04-14 15:01 UTC, merged