[VAS] Bug #10698: PASTIS errors on pua update
ProgrammeVitam/vitam-ui pull request #1137
Opened 2022-12-08 09:48 UTC by laedanrex

## Description
Message d'erreur lors de la mise à jour d'un PUA utilisé par une AU

## Type de changement:

* Nouveau Code

* Correction

* Refactorisation de code

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[x] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

2022-12-08 14:57 UTC, oussamasic requested changes

2022-12-08 14:57 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.ts
> +      this.profileService.checkPuaProfile(archivalProfileUnit).subscribe(
à ajouter dans un subscribe puis le détruire dans le ngOndestroy.

2022-12-08 14:57 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.ts
> +      this.profileService.checkPaProfile(profile).subscribe(
idem

2022-12-08 14:57 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
> +                .subscribe(retrievedData => {
à ajouter dans un subscribe, après le détruire

2022-12-08 14:57 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
> +                      console.log('error!!rattachement')
tu peux supprimer ce console

2022-12-08 14:57 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
> +    // router.navigate ??
comment to delete

2022-12-08 14:57 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
> +                          this.displaySnackBar(vitamUIException);
on aura pas 2 bandeau qui s'affiche en bas en cas d'erreur ? 
le premier de l'intercepteur et le 2eme de la méthode displaySnackBar

2022-12-08 14:57 UTC, oussamasic commented on commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/converter/VitamUIErrorConverter.java
> +                exception = new InternalServerException(source.getMessage(), source.getError(), source.getArgs());
cela n'a pas d'impact sur les TUs dans commons-rest ?

2022-12-09 09:20 UTC, laedanrex commented on commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/converter/VitamUIErrorConverter.java
> +                exception = new InternalServerException(source.getMessage(), source.getError(), source.getArgs());
nop

2022-12-09 16:38 UTC, oussamasic approved these changes

2022-12-09 16:57 UTC, bbenaissa commented
Je pense qu'il y  pas mal de remarques sur les logs depuis la PR original qu'on aurait pu les corriger ou améliorer

2022-12-09 16:57 UTC, bbenaissa approved these changes

2022-12-13 09:42 UTC, merged