WIP : disable action buttons in file formats App for consultation profile
ProgrammeVitam/vitam-ui pull request #1143
Opened 2022-12-15 16:31 UTC by soukami

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2022-12-22 10:14 UTC, oussamasic requested changes

2022-12-22 10:14 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/file-format/file-format-preview/file-format-information-tab/file-format-information-tab.component.ts
> +    this.hasUpdatetRole = this.securityService.hasRole(ApplicationId.FILE_FORMATS_APP, this.tenantId, Role.ROLE_UPDATE_FILE_FORMATS);
```suggestion
    this.route.params.subscribe((params) => {
      if (params.tenantIdentifier) {
            this.hasUpdatetRole = this.securityService.hasRole(ApplicationId.FILE_FORMATS_APP,parseInt(params.tenantIdentifier);, Role.ROLE_UPDATE_FILE_FORMATS);
      }
    });
  }
```

2022-12-22 10:14 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/file-format/file-format-preview/file-format-information-tab/file-format-information-tab.component.ts
> +    private fileFormatService: FileFormatService,
à vérifier coté TU, s'ils passent toujours

2022-12-22 15:59 UTC, soukami commented on ui/ui-frontend/projects/referential/src/app/file-format/file-format-preview/file-format-information-tab/file-format-information-tab.component.ts
> +    this.hasUpdatetRole = this.securityService.hasRole(ApplicationId.FILE_FORMATS_APP, this.tenantId, Role.ROLE_UPDATE_FILE_FORMATS);
done

2022-12-22 15:59 UTC, soukami commented on ui/ui-frontend/projects/referential/src/app/file-format/file-format-preview/file-format-information-tab/file-format-information-tab.component.ts
> +    private fileFormatService: FileFormatService,
pas d'impact à priori

2023-01-09 10:53 UTC, oussamasic approved these changes

2023-01-09 11:08 UTC, laedanrex commented on ui/ui-frontend/projects/referential/src/app/file-format/file-format.component.ts
> +    this.route.params.subscribe((params) => {
tu peux unsubscribe ca dans un onDestroy ?

2023-01-09 13:57 UTC, bbenaissa requested changes

2023-01-09 13:57 UTC, bbenaissa commented on ui/ui-frontend/projects/referential/src/app/file-format/file-format.component.ts
> +    this.route.params.subscribe((params) => {
+1

2023-01-10 13:34 UTC, laedanrex approved these changes

2023-01-12 10:30 UTC, merged