fix pour packager l'executable pastis standalone
ProgrammeVitam/vitam-ui pull request #1144
Opened 2022-12-20 13:21 UTC by baptiste-Cines

## Description

modifications mineurs pour corriger le packaging de l'executable pastis

## Type de changement:

*Indiquer le ou les types de changements*

* Correction

## Documentation:

*Indiquer la documentation mise à jour*

La procédure pour packager pastis standalone et indiquée dans api/api-pastis/pastis-standalone/README.md

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

CINES

2022-12-22 10:51 UTC, laedanrex commented on api/api-pastis/pastis-standalone/src/main/resources/standalone/theme.service.ts
> +    return of(null);
Salut, mieux vaut remplacer par EMPTY

2022-12-22 10:51 UTC, oussamasic requested changes

2022-12-22 10:51 UTC, oussamasic commented on api/api-pastis/pastis-standalone/src/main/resources/standalone/package.json
> +    "@ngx-translate/core": "13.0.0",
pourquoi figer la version ?

2022-12-22 10:51 UTC, oussamasic commented on api/api-pastis/pastis-standalone/README.md
> -        ./run.sh
pourquoi ?
à compléter je pense avec tout ce qu'il faut pour démarrer pastis en mode standalone.

2022-12-22 10:53 UTC, oussamasic requested changes

2022-12-22 10:53 UTC, oussamasic commented on api/api-pastis/pastis-standalone/src/main/resources/standalone/package.json
> +    "@ngx-translate/http-loader": "6.0.0",
idem ?

2022-12-22 10:56 UTC, laedanrex commented on api/api-pastis/pastis-standalone/README.md
> -        ./run.sh
salut, oui si ce readme est a jour il me semble pertinent

2022-12-22 13:54 UTC, baptiste-Cines commented on api/api-pastis/pastis-standalone/src/main/resources/standalone/theme.service.ts
> +    return of(null);
corrigé

2022-12-22 13:54 UTC, baptiste-Cines commented on api/api-pastis/pastis-standalone/src/main/resources/standalone/package.json
> +    "@ngx-translate/core": "13.0.0",
corrigé

2022-12-22 13:54 UTC, baptiste-Cines commented on api/api-pastis/pastis-standalone/README.md
> -        ./run.sh
corrigé fichier supprimé par erreur

2022-12-22 13:54 UTC, baptiste-Cines commented on api/api-pastis/pastis-standalone/src/main/resources/standalone/package.json
> +    "@ngx-translate/http-loader": "6.0.0",
corrigé

2022-12-22 16:52 UTC, oussamasic requested changes

2022-12-22 16:52 UTC, oussamasic commented on api/api-pastis/pastis-standalone/src/main/resources/standalone/theme.service.ts
> +    return EMPTY;
il sert à quoi cette méthode ? 
elle retourne toujours EMPTY

2023-01-02 08:14 UTC, baptiste-Cines commented on api/api-pastis/pastis-standalone/src/main/resources/standalone/theme.service.ts
> +    return EMPTY;
la méthode sert uniquement à pouvoir builder ui-frontend-common avec le profil standalone

2023-01-02 09:48 UTC, oussamasic approved these changes

2023-01-05 16:56 UTC, laedanrex approved these changes

2023-01-05 17:11 UTC, merged