story/vas-9880 add profil consult for ingest contract
ProgrammeVitam/vitam-ui pull request #1148
Opened 2022-12-22 08:59 UTC by mohatizaoui

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2022-12-22 10:29 UTC, oussamasic requested changes

2022-12-22 10:29 UTC, oussamasic commented on deployment/scripts/mongod/6.rc.0/35_add_consult_ingest_contract_profil.js.j2
> +// Create new profile CONSULTATION for RULES_APP
```suggestion
// Create new profile CONSULTATION for INGEST_APP
```

2022-12-22 10:29 UTC, oussamasic commented
Les TUs front passent toujours en succès après les modifications ?

2022-12-22 13:56 UTC, oussamasic approved these changes

2023-01-02 09:25 UTC, anasstsdi approved these changes

2023-01-02 09:29 UTC, bbenaissa approved these changes

2023-01-09 09:11 UTC, merged