[VAS] Story #10829: clean code
ProgrammeVitam/vitam-ui pull request #1158
Opened 2023-01-05 11:02 UTC by laedanrex

remove or rework some code

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[x] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

2023-01-10 11:13 UTC, oussamasic approved these changes

2023-01-10 13:13 UTC, bbenaissa approved these changes

2023-01-11 17:26 UTC, GiooDev requested changes

2023-01-11 17:26 UTC, GiooDev commented on ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/service/ArchivesSearchService.java
> +                                                         ExternalHttpContext context) {
C'est quoi tous ces espaces ?

2023-01-11 17:26 UTC, GiooDev commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/ResultsDto.java
> + * <p>
Ça sert à quoi les `<p>` ici ?

2023-01-11 18:09 UTC, oussamasic commented on ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/service/ArchivesSearchService.java
> +                                                         ExternalHttpContext context) {
problème de formatage

2023-01-12 09:24 UTC, merged