WIP : [VAS] Story #10840: add objects metadata on archive search unit detail
ProgrammeVitam/vitam-ui pull request #1160
Opened 2023-01-06 15:52 UTC by laedanrex

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2023-01-19 10:41 UTC, oussamasic commented
Il manque la partie Back pour cette évolution.
l'API pour récupérer les  ObjectMetadatasByUnitId d'une unité archivistique.

2023-01-30 08:51 UTC, laedanrex commented
> Il manque la partie Back pour cette évolution. l'API pour récupérer les ObjectMetadatas d'une unité archivistique.

j'arrive à afficher ce qu'il faut, il ne m'a pas semblé qu'il y avait besoin de modif back 

ca serait quoi ?

2023-01-30 15:53 UTC, oussamasic requested changes

2023-01-30 15:53 UTC, oussamasic commented on ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/rest/ArchivesSearchController.java
> +                                                           @QueryParam("contractId") String contractId) throws PreconditionFailedException,
le code style de Vitam est bien appliqué ?

2023-01-30 15:53 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
> +  -->
To delete

2023-01-30 15:53 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
> +        // this.updateStarted = false;
To delete

2023-01-30 15:53 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
> +        <label>{{ 'Identifiant du groupe d\'objets techniques' | translate }}</label>
traduction à faire, changer le texte avec sa clé dans le fichier i18n

2023-01-30 15:53 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
> +        <label>{{ 'Date de création' | translate }}</label>
idem

2023-01-30 15:53 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
> +        <label>{{ 'Date de dernière modification' | translate }}</label>
idem

2023-01-30 15:53 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
> +      <!-- class="separate-div" class="separator" class="vitamui-separator" -->
to delete

2023-01-30 15:53 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
> +      <!-- class="separate-div" class="separator" class="vitamui-separator" -->
idem

2023-01-30 15:53 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.scss
> + */
texte à supprimer

2023-01-30 15:53 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.spec.ts
> + */
à compléter avec des TUs,

2023-01-30 16:54 UTC, laedanrex commented on ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/rest/ArchivesSearchController.java
> +                                                           @QueryParam("contractId") String contractId) throws PreconditionFailedException,
j'ai plus le fichier

2023-01-30 17:31 UTC, bbenaissa requested changes

2023-01-30 17:31 UTC, bbenaissa commented on ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/service/ArchivesSearchService.java
> +        if (isNotBlank(qualifier) && nonNull(version)) {
pourquoi combiner les 2 conditions?

2023-01-30 17:31 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
> +        <label>{{ 'Identifiant du groupe d\'objets techniques' | translate }}</label>
traduction

2023-01-30 17:31 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
> +        <label>{{ 'Date de création' | translate }}</label>
+1

2023-01-30 17:31 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
> +        <label>{{ 'Date de dernière modification' | translate }}</label>
+1

2023-01-30 17:31 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
> +     *ngFor="let versionWithQualifier of versionsWithQualifiersOrdered; let index = index; let isFirst = first; let isOdd = odd;">
isFirst & isOdd non utilisés

2023-01-30 17:31 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
> +              (click)="onClicDownloadObject($event, versionWithQualifier)">
onClicDownloadObject ==> onClickDownloadObject

2023-01-30 17:31 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
> +      <div class="line object-size">{{ versionWithQualifier.Size  | bytes }}</div>
l'attribut est bien Size ?

2023-01-30 17:31 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.spec.ts
> + */
+1

2023-01-30 17:35 UTC, bbenaissa commented
Une remarque globale sur le fichier html principal, est ce qu'il n'y a pas de risque que des champs soient nuls par exemple FileInfo,

2023-01-31 09:21 UTC, laedanrex commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
> +      <div class="line object-size">{{ versionWithQualifier.Size  | bytes }}</div>
oui

2023-01-31 09:22 UTC, laedanrex commented on ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/service/ArchivesSearchService.java
> +        if (isNotBlank(qualifier) && nonNull(version)) {
l'un ne va pas sans l'autre

2023-01-31 15:18 UTC, oussamasic approved these changes

2023-02-01 14:42 UTC, bbenaissa approved these changes

2023-02-01 15:07 UTC, merged