WIP : story 9854 partitioning access to ingest
ProgrammeVitam/vitam-ui pull request #1183
Opened 2023-01-26 16:38 UTC by soukami

## Description

L'objectif est de donner la possibilité de cloisonner la consultation de l'APP Dépôt et suivi des versements aux versements propres à un service producteur, ou à une sélection de services producteurs,

2023-02-02 14:07 UTC, bbenaissa requested changes

2023-02-02 14:07 UTC, bbenaissa commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestExternalParametersdService.java
> +                    throw new IllegalArgumentException( "external parameter of bulk access contract contains wrong integer value " + parameterAccessContract.getValue() + ", it will not be used ");
Dans cette partie, à priori tu as besoin que tu contrat d'accès (string) et pas de thresholds

2023-02-02 14:07 UTC, bbenaissa commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestExternalParametersdService.java
> +                    throw new IllegalArgumentException( "external parameter of bulk access contract contains wrong integer value " + parameterAccessContract.getValue() + ", it will not be used ");
Il n'y a pas de NumberFormatException

2023-02-02 14:07 UTC, bbenaissa commented on api/api-ingest/ingest-commons/src/main/java/fr/gouv/vitamui/ingest/common/dsl/VitamQueryHelper.java
> +                        }
ça serait pas mieux pour une meilleure visibilité de le les mettre ensemble: 

                   case OB_ID_IN:
                    case TRANSFERRING_AGENCY:
                    case ARCHIVAL_AGENCY:
                    case ORIGINATING_AGENCY:
                    case ID:
                    case COMMENT:
                        if (entry.getValue() instanceof ArrayList) {
                            final List<String> stringsValues = (ArrayList) entry.getValue();
                            for (String elt : stringsValues) {
                                queryOr.add(eq(searchKey, elt));
                            }
                            haveOrParameters = true;
                        } else {
                            if (entry.getValue() instanceof String) {
                                final String searchValue = (String) entry.getValue();
                                queryOr.add(eq(searchKey, searchValue));
                                haveOrParameters = true;
                            }
                        }
                        break;

2023-02-02 14:07 UTC, bbenaissa commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/config/ApiIngestInternalServerConfig.java
> +import fr.gouv.vitamui.commons.vitam.api.administration.AccessContractService;
Imports non utilisés

2023-02-02 14:07 UTC, bbenaissa commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/AccessContractInternalService.java
> +    private LogbookService logbookService;
Non utilisé

2023-02-02 14:07 UTC, bbenaissa commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/AccessContractInternalService.java
> +    public AccessContractDto getOne(VitamContext vitamContext, String identifier) {
C'est pas mieux de le convertir en retour de Optional<AccessContractDto>

2023-02-02 14:07 UTC, bbenaissa commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestExternalParametersdService.java
> +public class IngestExternalParametersdService extends AbstractResourceClientService<ArchiveUnitDto, ArchiveUnitDto> {
Nom de classe à corriger IngestExternalParameters**d**Service

2023-02-02 14:07 UTC, bbenaissa commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/AccessContractInternalService.java
> +import fr.gouv.vitam.common.model.administration.AccessContractModel;
Imports non utilisés

2023-02-02 14:07 UTC, bbenaissa commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestInternalService.java
> +                if (!everyOriginatingAgency) {
Proposition: 
  if (!everyOriginatingAgency) {
        vitamCriteria.put(ORIGINATING_AGENCY, originatingAgencies.stream().collect(Collectors.toList()));
    }

2023-02-07 13:08 UTC, soukami commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestExternalParametersdService.java
> +                    throw new IllegalArgumentException( "external parameter of bulk access contract contains wrong integer value " + parameterAccessContract.getValue() + ", it will not be used ");
done

2023-02-07 13:54 UTC, bbenaissa approved these changes

2023-02-09 14:09 UTC, oussamasic requested changes

2023-02-09 14:09 UTC, oussamasic commented on api/api-ingest/ingest-commons/src/main/java/fr/gouv/vitamui/ingest/common/dto/ArchiveUnitDto.java
> +public class ArchiveUnitDto extends IdDto implements Serializable {
attention : tu as déjà un attribut `id` dans la classe `ArchiveUnitDto`, pas besoin d'hériter `IdDto`

2023-02-09 14:09 UTC, oussamasic commented on api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/client/AbstractResourceClientService.java
> +            message + ": tenantIdentifier " + tenantIdentifier + " is not allowed");
bcp de formatage dans ce fichier, le code Style de Vitam est bien ajouté ou non ?

2023-02-09 14:09 UTC, oussamasic commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/AccessContractInternalService.java
> +            if (accessContractResponseDto.getResults().size() == 0) {
```suggestion
            if (CollectionUtils.isEmpty(accessContractResponseDto.getResults())) {
```

2023-02-09 14:09 UTC, oussamasic commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestExternalParametersService.java
> +        if (myExternalParameter != null && !CollectionUtils.isEmpty(myExternalParameter.getParameters())) {
```suggestion
        if (myExternalParameter != null && CollectionUtils.isNotEmpty(myExternalParameter.getParameters())) {
```

2023-02-09 14:09 UTC, oussamasic commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestExternalParametersService.java
> +        LOGGER.error("myExternalParameter: {}", myExternalParameter);
debug/info au lieu de error

2023-02-09 14:45 UTC, oussamasic approved these changes

2023-02-09 17:36 UTC, merged