[VAS] Story #10898: XXE vulnerability in pastis app
ProgrammeVitam/vitam-ui pull request #1197
Opened 2023-02-03 09:37 UTC by laedanrex

## Description

*Description des modifications*

Problème de configuration pouvant mener à une XXE (V13)

## Type de changement:

*Indiquer le ou les types de changements*

* Nouveau Code

* Refactorisation de code

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

2023-02-03 11:12 UTC, oussamasic approved these changes

2023-02-06 10:59 UTC, bbenaissa requested changes

2023-02-06 10:59 UTC, bbenaissa commented on api/api-pastis/pastis-external/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
> +        xmlReader.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
Est ce que l'accès à cette URL ne pose pas de pb dans les envs qui n'ont pas accès à internet?

2023-02-06 17:00 UTC, laedanrex commented on api/api-pastis/pastis-external/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
> +        xmlReader.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
c'est des flags, je pense pas que ca se connecte a internet

2023-02-06 17:03 UTC, laedanrex commented on api/api-pastis/pastis-external/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
> +        xmlReader.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
j'ai add un test

2023-02-06 21:17 UTC, bbenaissa approved these changes

2023-02-07 09:05 UTC, oussamasic commented on api/api-pastis/pastis-external/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
> +        xmlReader.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
en local ça marchera bien.
Pour bien vérifier je pense il faut qu'on teste sur NUBO qui bloque les les connexions internet.

2023-02-07 09:52 UTC, merged