Feature/vas item 10511 add more ontologies
ProgrammeVitam/vitam-ui pull request #1206
Opened 2023-02-08 14:19 UTC by oussamasic

L'objectif de cette PR est de traiter l'US 10511

2023-02-23 16:41 UTC, GiooDev requested changes

2023-02-23 16:41 UTC, GiooDev commented on deployment/roles/vitamui/tasks/archive-search-internal.yml
> +    ONTOLOGIES_LIST: "{{lookup('file', '{{ inventory_dir }}/ontologies/ontologies_field.json') }}"
Il sert à quoi le fact ici ? il ne semble utilisé nulle part

2023-02-23 16:41 UTC, GiooDev commented on deployment/roles/vitamui/tasks/collect-internal.yml
> +    ONTOLOGIES_LIST: "{{lookup('file', '{{ inventory_dir }}/ontologies/ontologies_field.json') }}"
Il sert à quoi le fact ici ? il ne semble utilisé nulle part

2023-02-23 16:41 UTC, GiooDev commented on deployment/environments/group_vars/all/vitamui_vars.yml
> +    ontologies_file_path: "{{ vitamui_defaults.folder.root_path | default('/vitamui') }}/conf/"
Pourquoi définir cette variable ici ? est-ce que l'on peut vraiment changer le path de destination du fichier qui sera déployé ?

2023-02-23 16:41 UTC, GiooDev commented on deployment/environments/group_vars/all/vitamui_vars.yml
> +    ontologies_file_path: "{{ vitamui_defaults.folder.root_path | default('/vitamui') }}/conf/"
Pourquoi définir cette variable ici ? est-ce que l'on peut vraiment changer le path de destination du fichier qui sera déployé ?

2023-02-23 16:41 UTC, GiooDev commented on deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
> +ontologies_file_path: {{ vitamui_struct.ontologies_file_path }}{{ vitamui_struct.vitamui_component }}/
Le mettre sous `{{ vitamui_folder_conf }}`

Quel pourrait-être l'intéret de modifier le chemin de ce fichier ?

Est-ce normal de cibler le répertoire et pas le fichier en question ? Est-ce qu'il pourrait y avoir plusieurs fichiers ontologies ?

2023-02-23 16:41 UTC, GiooDev commented on deployment/roles/vitamui/templates/collect-internal/application.yml.j2
> +ontologies_file_path: {{ vitamui_struct.ontologies_file_path }}{{ vitamui_struct.vitamui_component }}/
Le mettre sous `{{ vitamui_folder_conf }}`

Quel pourrait-être l'intéret de modifier le chemin de ce fichier ?

Est-ce normal de cibler le répertoire et pas le fichier en question ? Est-ce qu'il pourrait y avoir plusieurs fichiers ontologies ?

2023-02-23 16:41 UTC, GiooDev commented on deployment/roles/vitamui/tasks/collect-internal.yml
> +    dest: "{{ vitamui_struct.ontologies_file_path }}/{{ vitamui_struct.vitamui_component }}"
Le mettre sous `dest: "{{ vitamui_folder_conf }}"`

2023-02-23 16:41 UTC, GiooDev commented on docs/DAT/docs/dat_vitamui/exploitation/gestion_ontologies.md
> +Ensuite s'il y a un besoin d'ajouter des nouvelles ontologies, il suffit juste de modifier les fichier directement au niveau des machines
Sans oublier de le sauvegarder sous `environments/ontologies/ontologies_field.json` pour réapplication future.

D'ailleurs il est toujours déconseillé de modifier directement sur les machines des fichiers qui seront écrasés par ansible. Toujours préférer l'application des mises à jour par ansible.

2023-02-23 16:41 UTC, GiooDev commented on docs/DAT/docs/dat_vitamui/exploitation/gestion_ontologies.md
> +```
Spécifier le type de bloc-code ` ```json `

2023-02-23 16:41 UTC, GiooDev commented on docs/DAT/docs/dat_vitamui/exploitation/gestion_ontologies.md
> +## Les ontologies dans VitamUI
Pas mal de fautes d'orthographe et de saut de ligne en milieu de phrases à revoir.

2023-02-23 16:41 UTC, GiooDev commented on commons/commons-api/src/test/resources/ontologies/ontologies_field.json
> +[
Attention, ça ressemble à un exemple, si ce n'est pas légitime que ce soit appliqué tel quel chez tous les partenaires le suffixer d'un .example

Car sinon, en l'état ça sera appliqué de facto ainsi chez tout le monde.

2023-02-27 18:00 UTC, oussamasic commented on deployment/roles/vitamui/tasks/archive-search-internal.yml
> +    ONTOLOGIES_LIST: "{{lookup('file', '{{ inventory_dir }}/ontologies/ontologies_field.json') }}"
supprimé

2023-02-27 18:01 UTC, oussamasic commented on commons/commons-api/src/test/resources/ontologies/ontologies_field.json
> +[
c'est un fichier pour les tests unitaires

2023-02-27 18:29 UTC, GiooDev commented on commons/commons-api/src/test/resources/ontologies/ontologies_field.json
> +[
On a un repo en interne pour surcharger des fichiers de tests/intégration.
En l'état si c'est livré comme ça, ce sera appliqué tel quel chez tous les utilisateurs de VitamUI. Quels sont les impacts d'ajouter ça par défaut sur les installations ?

2023-02-28 10:57 UTC, oussamasic commented on deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
> +ontologies_file_path: {{ vitamui_struct.ontologies_file_path }}{{ vitamui_struct.vitamui_component }}/
oui, le nom du fichier est spécifié dans le code Java

2023-02-28 20:57 UTC, GiooDev requested changes

2023-02-28 20:57 UTC, GiooDev commented on deployment/roles/vitamui/tasks/archive-search-internal.yml
> +- name: Check if ontologies file exist
On pourrait faire un playbook à la racine du role vitamui/tasks/copy_ontologies.yml pour éviter de dupliquer le code et juste importer ces tasks ici ?

2023-03-01 14:11 UTC, bbenaissa requested changes

2023-03-01 14:11 UTC, bbenaissa commented on api/api-archive-search/archive-search-external-client/src/main/java/fr/gouv/vitamui/archives/search/external/client/ArchiveSearchExternalRestClient.java
> +    public  List<OntologyDto> getOntologiesList(ExternalHttpContext context) {
c'est mieux de spécifier: getExternalOntologiesList ou getAdditionalOntologiesList ou getExtraOntologiesList ou autre nom pour spécifier qu'ils s'agissent d'ontologies externes

2023-03-01 14:11 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/resources/application-dev.yml
> +# ontologies file path
ça sera mieux en prod que ça soit dans le repertoire data pré-créé

2023-03-01 14:11 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/resources/application-dev.yml
> +# ontologies file path
est ce que tu spécifies ici le dosier qui peut contenir plusieurs fichiers ou avec un nom bien défini?

2023-03-01 14:11 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/resources/application-dev.yml
> +# ontologies file path
idem: external ou ***

2023-03-01 14:11 UTC, bbenaissa commented on api/api-collect/collect-internal/src/main/resources/application-dev.yml
> +ontologies_file_path: "src/main/resources/ontologies/"
idem

2023-03-01 14:11 UTC, bbenaissa commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/CommonConstants.java
> +    public static final String ONTOLOGIES_LIST = "/ontologies";
idem pour external

2023-03-01 14:11 UTC, bbenaissa commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/OntologyServiceReader.java
> +    private static final String ONTOLOGY_FILE_NAME ="ontologies_field.json";
ça sera mieux de rentre le fichier configurable y compris le chemin

2023-03-01 14:11 UTC, bbenaissa commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/OntologyServiceReader.java
> +    public static List<OntologyDto> readOntologiesFromFile(Integer tenantId, String ontologiesFilePath)
pourquoi le mettre en static?

2023-03-01 14:11 UTC, bbenaissa commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/OntologyServiceReader.java
> +    public static List<OntologyDto> readOntologiesFromFile(Integer tenantId, String ontologiesFilePath)
On peut le mettre comme un parametre pour eviter de le créer à chaque fois

2023-03-01 14:11 UTC, bbenaissa commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/OntologyServiceReader.java
> +        ObjectMapper objectMapper = new ObjectMapper();
mettre ObjectMapper comme attribute

2023-03-01 14:11 UTC, bbenaissa commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/OntologyServiceReader.java
> +        return ontologyDtoList.stream().filter(ontologyDto -> ontologyDto.getTenantId().contains(1) ||
Mettre le 1 comme constante pour que ça soit bien visible et claire pour la lacture

2023-03-01 14:11 UTC, bbenaissa commented on deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
> +ontologies_file_path: {{ vitamui_folder_data }}/external_ontologies_field.json
Idem pour le nom du fichier

2023-03-01 14:11 UTC, bbenaissa commented on deployment/roles/vitamui/templates/collect-internal/application.yml.j2
> +ontologies_file_path: {{ vitamui_folder_data }}/external_ontologies_field.json
idem

2023-03-01 14:11 UTC, bbenaissa commented on ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/rest/ArchivesSearchController.java
> +    @GetMapping(CommonConstants.ONTOLOGIES_LIST)
le endpoint aussi (external **)

2023-03-01 16:47 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/main/resources/application-dev.yml
> +# ontologies file path
le path complet vers le fichier (chemin avec le nom du fichier)

2023-03-01 17:02 UTC, oussamasic commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/OntologyServiceReader.java
> +        ObjectMapper objectMapper = new ObjectMapper();
Done

2023-03-01 17:58 UTC, GiooDev requested changes

2023-03-01 17:58 UTC, GiooDev commented on deployment/environments/ontologies/ontologies_field.json
> +[
Fichier à supprimer.

2023-03-01 17:58 UTC, GiooDev commented on deployment/roles/vitamui/tasks/copy_ontologies.yml
> +  local_action: stat path={{ inventory_dir }}/ontologies/external_ontologies_field.json
Juste pour comprendre le nommage de ce fichier, C'est UN champ de plusieurs ontologies externes ?
Ou alors fields devrait aussi être au pluriel ?

Après échange avec Marion, cela devrait être external_ontology_fields.json

Car ce sont des champs (fields) d'un vocabulaire (ontology) externe (external).

2023-03-01 17:58 UTC, GiooDev commented on deployment/roles/vitamui/tasks/collect-internal.yml
> +- import_tasks: copy_ontologies.yml
Est-ce qu'il y a besoin de restart le service suite à la copie de ce fichier ?

2023-03-01 21:29 UTC, GiooDev requested changes

2023-03-01 21:29 UTC, GiooDev commented on deployment/roles/vitamui/tasks/archive-search-internal.yml
> +- include: copy_ontologies.yml
Ça marchait pas le import_tasks ?

Y'a des exemples avec include_tasks et import_tasks ici: https://github.com/ProgrammeVitam/vitam/blob/d9e23d619926b194961b9368cde024edf2a8b0a1/deployment/ansible-vitam/roles/vitam/tasks/main.yml#L356

2023-03-02 09:43 UTC, oussamasic commented on deployment/roles/vitamui/tasks/archive-search-internal.yml
> +- include: copy_ontologies.yml
avec import tasks : L'importation de rôles les ajoute de manière statique à un playbook  et vue que dans ma task j'ai des variables dynamique, c'est pour ça j'ai utilisé includes (import dynamique)

2023-03-02 09:43 UTC, oussamasic commented on deployment/roles/vitamui/tasks/collect-internal.yml
> +- import_tasks: copy_ontologies.yml
non, pas besoin

2023-03-02 09:49 UTC, bbenaissa requested changes

2023-03-02 09:49 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/test/resources/application.yml
> +ontologies_file_path: "src/main/resources/ontologies/external_ontologies_field.json"
je préfère que tu références plutot un fichier dans les resources des tests

2023-03-02 15:23 UTC, TDevillechabrolle commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx One – Scan Summary & Details** – [4865b11a\-3eca\-4462\-a106\-71c555141f07](https://eu.ast.checkmarx.net/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/scans?id=4865b11a-3eca-4462-a106-71c555141f07&branch=feature%2Fvas_item_10511_add_more_ontologies)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/4865b11a-3eca-4462-a106-71c555141f07/sast/description/117/9884244256835554923)|/api/api\-security/security\-internal/src/main/java/fr/gouv/vitamui/security/server/rest/CertificateCrudController\.java: [118](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas_item_10511_add_more_ontologies//api/api-security/security-internal/src/main/java/fr/gouv/vitamui/security/server/rest/CertificateCrudController.java#L118)|[Attack Vector](https://eu.ast.checkmarx.net/results/4865b11a-3eca-4462-a106-71c555141f07/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=lq4sI136k7xCW7q15qwEKkVuk7w%3D&redirect=true)

2023-03-02 17:06 UTC, GiooDev requested changes

2023-03-02 17:06 UTC, GiooDev commented on docs/DAT/docs/dat_vitamui/exploitation/gestion_ontologies.md
> +Ensuite, s'il y a un besoin d'ajouter des nouvelles ontologies, il suffit juste de modifier le fichier directement au niveau des machines. Sinon changer le fichier **environments/ontologies/external_
Typo, le répertoire est encore nommé ici ontologies au lieu de ontology/

2023-03-02 17:09 UTC, GiooDev requested changes

2023-03-02 17:09 UTC, GiooDev commented on docs/DAT/docs/dat_vitamui/exploitation/gestion_ontologies.md
> +- **_TenantId_** : La liste des tenants dont on pourra utiliser l'ontologie (liste des entiers)
Peut-être préciser que si le tenant 1 est mis, il s'applique à l'ensemble des tenants ?

2023-03-02 17:09 UTC, GiooDev commented on docs/DAT/docs/dat_vitamui/exploitation/gestion_ontologies.md
> +    "TenantId" : [1,2,3,4]
Retirer le tenant 1 de l'exemple ici car la définition des autres tenants ne sert à rien si avec le 1, ça s'applique déjà à tous.

2023-03-02 17:14 UTC, bbenaissa approved these changes

2023-03-02 19:40 UTC, GiooDev approved these changes

2023-03-03 09:17 UTC, GiooDev requested changes

2023-03-03 09:17 UTC, GiooDev commented on docs/DAT/docs/dat_vitamui/exploitation/gestion_ontologies.md
> +- **_TenantId_** : La liste des tenants dont on pourra utiliser l'ontologie (liste des entiers), si le tenant **1** est parmi la liste des entiers donc l'ontologie en question sera visible sur l'ense
En fait cette valeur est une liste de tenants.

Est-ce qu'il ne faudrait pas la mettre au pluriel aussi ? Car là, ça laisse penser que c'est une valeur unique.

Côté vitam on a:  `vitam_tenant_ids` ou `tenants`

Est-ce qu'on renomme `TenantIds` ? ou `TenantsList` ? 

Perso je verrai bien `TenantIds`, qu'en penses-tu ?

2023-03-03 09:23 UTC, oussamasic commented on docs/DAT/docs/dat_vitamui/exploitation/gestion_ontologies.md
> +- **_TenantId_** : La liste des tenants dont on pourra utiliser l'ontologie (liste des entiers), si le tenant **1** est parmi la liste des entiers donc l'ontologie en question sera visible sur l'ense
oui, on peux mettre tenantIds c'est plus propre

2023-03-03 11:16 UTC, GiooDev requested changes

2023-03-03 11:16 UTC, GiooDev commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/TransactionArchiveUnitInternalService.java
> +     * @param tenantId : tenant identifier
Ici c'est pas tenantIds ?

2023-03-03 11:31 UTC, merged