update collect architecture &rename collect service in consul
ProgrammeVitam/vitam-ui pull request #1207
Opened 2023-02-09 08:16 UTC by bbenaissa

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2023-02-10 16:01 UTC, oussamasic requested changes

2023-02-10 16:01 UTC, oussamasic commented on README.md
> +  into `api/api-(iam|referential)/(iam|referential)-internal/src/main/config/dev-vitam/`
archive-search et ingest aussi.
Sans oublier la modification du pom de chaque module en question.

2023-02-10 16:01 UTC, oussamasic commented
un squash à faire avant le merge.

2023-02-22 17:50 UTC, GiooDev requested changes

2023-02-22 17:50 UTC, GiooDev commented on README.md
> +    -
C'était mieux avant ici :p

2023-02-22 17:50 UTC, GiooDev commented on README.md
> +* Si une version d'ansible à été installée via `apt-get install`, il est nécessaire de la
Idem, sauts de ligne non nécessaires.

2023-02-22 17:50 UTC, GiooDev commented on README.md
> +- Copy files: `collect-external-client.conf`,`access-external-client.conf`, `ingest-external-client.conf`
Idem, plusieurs sauts de ligne qui cassent la mise en page

2023-02-22 17:50 UTC, GiooDev commented on README.md
> +  your `hosts` (`/etc/hosts`) file
again

2023-02-27 20:43 UTC, GiooDev commented
Attention, si on renomme tous les services, il faudra bien documenter voir faire un script de migration pour nettoyer les anciens éléments non nécessaires. De plus cela imposera une régénération totale des tous les certificats and co.
Je comprends bien l'objectif derrière mais attention à en maîtriser les impacts avec la proximité de l'échéance de la release

2023-02-28 16:28 UTC, GiooDev approved these changes

2023-03-01 09:49 UTC, oussamasic approved these changes

2023-03-01 10:33 UTC, merged