[VAS] 10842 update project with transaction
ProgrammeVitam/vitam-ui pull request #1211
Opened 2023-02-15 07:44 UTC by mohatizaoui

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2023-02-16 09:31 UTC, laedanrex commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
> +  <form [formGroup]="form" class="vitamui-sidepanel-body">
ca a ete vu avec po / ui la transformation de cette vue en formulaire ?

2023-02-16 09:41 UTC, laedanrex commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
> +  encapsulation: ViewEncapsulation.None,
ca va pas s'appliquer à tout ? 
tu ne préfère pas passer pas :host en css ?

2023-02-16 09:43 UTC, laedanrex commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
> +  legalStatusList: any[] = [];
si tu peux les typer , le premier ca devrait passer Array<string> je pense

2023-02-16 13:15 UTC, oussamasic requested changes

2023-02-16 13:15 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
> +      ces modifications
à traduire

2023-02-16 13:15 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
> +  acquisitionInformationsList: any[] = [];
évite l'utilisation du type any

2023-02-16 13:15 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
> +                                    class="col-8 px-0 mr-4" [value]="">
**value** : c'est le messageIdentifier à recuperer

2023-02-16 13:15 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
> +
pour les les composants : vitamui-common-input il manque je pense l'entrée value à mettre pour afficher une valeur à l'utilisateur

2023-02-16 13:15 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
> +      Action sur un projet de versement
à traduire

2023-02-16 13:15 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
> +    console.log(this.form.value);
to delete

2023-02-16 13:15 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
> +    this.updateStarted = false;
TU à ajouter et à corriger les autres

2023-02-16 13:15 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/models/collect/project.ts
> +  archiveProfile: string;
avec cette modification du modèle, il faut vérifier les TU dans collect.

2023-02-16 16:09 UTC, laedanrex commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
> +                                    class="col-8 px-0 mr-4" [value]="">
wo il a l'oeil

2023-02-17 09:12 UTC, bbenaissa requested changes

2023-02-17 09:12 UTC, bbenaissa commented on ui/ui-frontend-common/src/app/modules/models/collect/project.ts
> +  archiveProfile: string;
+1 :
S'il s'agit de champs juste pour l'app recherche, tu peux les mettre optionnels

2023-02-17 09:12 UTC, bbenaissa commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
> +      Action sur un projet de versement
:+1:

2023-02-17 09:12 UTC, bbenaissa commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
> +      ces modifications
:+1:

2023-02-17 09:12 UTC, bbenaissa commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
> +        <mat-button-toggle value="OUI">
Il s'agit de la valeur à envoyer au back? OUI/NON?

2023-02-17 09:12 UTC, bbenaissa commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.scss
>  .spinnerClass {
Je sais que c'est pas ton code, on ne peut pas le mettre un peu plus haut, s'il s'agit du meme style dans d'autres composants/modules

2023-02-17 09:12 UTC, bbenaissa commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.scss
> +.dialog-action {
à revoir le css si on n'a pas de style commun avant

2023-02-17 09:12 UTC, bbenaissa commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
> +    const updateProjectOperation$ = this.projectService.updateProject(projectToUpdate);
Je n'arrive pas à comprendre le process?!!

2023-02-17 09:32 UTC, oussamasic commented
remarque sur le processus d'update des transactions : 
vu qu'on pas une API coté back qui prends un id du projet et fait la MAJ des transactions du projet en question.
Pour des raison de performances, je pense que c'est mieux de faire un seul appel du front vers le back e vitamui, après on recupere la liste des transactions et on lance l'update pour chaque transaction.
Avec le processus ajouté dans cette PR : on est obligé pour chaque update de passer par l'ensemble des couches de VitamUI avant d'appeler Vitam (ca prends un peu du temps)

2023-02-17 09:40 UTC, mohatizaoui commented
> remarque sur le processus d'update des transactions : vu qu'on pas une API coté back qui prends un id du projet et fait la MAJ des transactions du projet en question. Pour des raison de performances, je pense que c'est mieux de faire un seul appel du front vers le back e vitamui, après on recupere la liste des transactions et on lance l'update pour chaque transaction. Avec le processus ajouté dans cette PR : on est obligé pour chaque update de passer par l'ensemble des couches de VitamUI avant d'appeler Vitam (ca prends un peu du temps)

2023-02-17 09:40 UTC, closed without merging

2023-02-20 07:45 UTC, mohatizaoui commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
> +        <mat-button-toggle value="OUI">
il s'agit juste une option  pour savoir est ce qu'il faut fair un appel au update transaction ou non