WIP
ProgrammeVitam/vitam-ui pull request #1215
Opened 2023-02-17 16:12 UTC by laedanrex

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2023-03-02 16:47 UTC, TDevillechabrolle commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx One – Scan Summary & Details** – [84b39904\-a9f0\-4750\-b59e\-f02c912f3ed6](https://eu.ast.checkmarx.net/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/scans?id=84b39904-a9f0-4750-b59e-f02c912f3ed6&branch=vas-10679-collect-project-workflow)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/84b39904-a9f0-4750-b59e-f02c912f3ed6/sast/description/117/9884244256835554923)|/api/api\-security/security\-internal/src/main/java/fr/gouv/vitamui/security/server/rest/CertificateCrudController\.java: [118](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-10679-collect-project-workflow//api/api-security/security-internal/src/main/java/fr/gouv/vitamui/security/server/rest/CertificateCrudController.java#L118)|[Attack Vector](https://eu.ast.checkmarx.net/results/84b39904-a9f0-4750-b59e-f02c912f3ed6/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=lq4sI136k7xCW7q15qwEKkVuk7w%3D&redirect=true)

2023-03-03 09:33 UTC, mohatizaoui commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.spec.ts
> -  it('should update project without transactions', waitForAsync(() => {
Il faut pas supprimer ces tests

2023-03-03 09:33 UTC, mohatizaoui commented on ui/ui-frontend/projects/vitamui-library/src/lib/api/search-unit-api.service.ts
> +    const searchResponseMock: SearchResponse = {
Il faut enlever le mock

2023-03-03 09:33 UTC, mohatizaoui commented on ui/ui-frontend/projects/vitamui-library/src/lib/components/filing-plan/filing-plan.service.ts
> +export function oneIncludedNodeRequired(): ValidatorFn {
il faut le mettre dans le service et si on commun essayes de le mettre dans un service en commun

2023-03-03 09:57 UTC, laedanrex commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.spec.ts
> -  it('should update project without transactions', waitForAsync(() => {
y a plus d'update

2023-03-03 10:01 UTC, laedanrex commented on ui/ui-frontend/projects/vitamui-library/src/lib/components/filing-plan/filing-plan.service.ts
> +export function oneIncludedNodeRequired(): ValidatorFn {
c'est deja le cas :  vitamui-library

2023-03-03 10:13 UTC, oussamasic requested changes

2023-03-03 10:13 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/ProjectInternalService.java
> +            ProjectDto projectDto = ProjectConverter.toProjectDto(collectProjectDto);
toVitamProjectDto

2023-03-03 10:13 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/ProjectInternalService.java
> +            List<CollectProjectDto> collectProjectDtos = ProjectConverter.toCollectProjectDtos(projectDtos);
toVitamuiCollectProjectDto

2023-03-03 10:13 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/ProjectInternalService.java
> +            ProjectDto projectDto = ProjectConverter.toProjectDto(collectProjectDto);
c'est mieux de changer les noms des deux fonctions utilisées pour la conversion  : 
- toVitamuiCollectDto
- toVitamProjectDto

2023-03-03 10:13 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/converters/ProjectConverter.java
> +    public static ProjectDto toProjectDto(CollectProjectDto collectProjectDto) {
idem

2023-03-03 10:13 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/converters/ProjectConverter.java
> +            return null;
on retourne pas une liste vide ?

2023-03-03 10:13 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/converters/ProjectConverter.java
> +            return null;
on retourne pas une liste vide ?

2023-03-03 10:13 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/converters/ProjectConverter.java
> +        return collectMetadataUnitUpDtos.stream().map(ProjectConverter::toMetadataUnitUp).collect(Collectors.toList());
si collectMetadataUnitUpDtos est vide ?

2023-03-03 10:13 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/converters/ProjectConverter.java
> +        return metadataUnitUps.stream().map(ProjectConverter::toCollectMetadataUnitUpDto).collect(Collectors.toList());
si metadataUnitUps est vide ?

2023-03-03 10:13 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project-step-helper.ts
> +  // FLOW_RULES = 'FLOW_RULES',
to delete

2023-03-03 10:13 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project-step-helper.ts
> +export enum WorkflowStep {
to delete

2023-03-03 10:13 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.html
> +                                      style="font-size: 14px; font-weight: 700; color: var(--vitamui-primary)"
à mettre dans le fichier .css

2023-03-03 10:13 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.html
> +                                        style="font-size: 14px; font-weight: 700; color: var(--vitamui-primary)"
idem : à mettre dans le fichier .css

2023-03-03 10:13 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.html
> +                            <mat-option *ngFor="let ontology of this.ontologies"
```suggestion
                            <mat-option *ngFor="let ontology of ontologies"
```

2023-03-03 10:13 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.scss
> +    //background-color: var(--vitamui-grey-100);
to delete

2023-03-03 10:13 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.spec.ts
> -  it('should have the right values', () => {
pourquoi t'as supprimé ces tests ?

2023-03-03 10:13 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
> +      // id: null,
to delete

2023-03-03 10:13 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
> +    console.log('formToProject: ' + JSON.stringify(project))
to delete

2023-03-03 10:13 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
> +    const sefzefd: Array<MetadataUnitUp> = this.rulesParams.controls.map((ruleParamControl: FormControl) => {
change le nom de la constante

2023-03-03 10:13 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
> +    console.log(JSON.stringify(sefzefd))
console à supprimer

2023-03-03 10:13 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
> +    console.log('validateAndCreateManual:');
to delete

2023-03-03 10:13 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
> +    console.log(JSON.stringify(project))
idem

2023-03-03 10:13 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.spec.ts
> -  it('should update project without transactions', waitForAsync(() => {
pourquoi t'as supprimé ça ?

2023-03-03 10:13 UTC, oussamasic commented on ui/ui-frontend/projects/vitamui-library/src/lib/api/search-unit-api.service.ts
> +  getFilingPlan(_?: HttpHeaders): Observable<SearchResponse> {
Mock à supprimer après le merge de la partie back

2023-03-03 10:13 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/converters/ProjectConverter.java
> +    public static CollectMetadataUnitUpDto toCollectMetadataUnitUpDto(MetadataUnitUp metadataUnitUp) {
des TUs à ajouter pour tester les différentes méthodes de conversion ajoutées.

2023-03-03 10:13 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project-step-helper.ts
> +export class CreateProjectStepHelper {
tu peux créer directement une interface pour les deux enum ou lieu d'un service

2023-03-03 10:16 UTC, mohatizaoui commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.spec.ts
> -  it('should update project without transactions', waitForAsync(() => {
No cela s'agit la nouvelle fonctionnalité concernant Modification d'un projet de versement

2023-03-03 10:23 UTC, laedanrex commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.spec.ts
> -  it('should update project without transactions', waitForAsync(() => {
y a plus d'update

2023-03-03 10:23 UTC, laedanrex commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.spec.ts
> -  it('should update project without transactions', waitForAsync(() => {
code mort ☠️

2023-03-03 10:23 UTC, laedanrex commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.spec.ts
> -  it('should update project without transactions', waitForAsync(() => {
code mort ☠️

2023-03-03 10:29 UTC, laedanrex commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/converters/ProjectConverter.java
> +            return null;
ca renvoit null si c'est null 
une liste vide si c'est une liste vide

2023-03-03 10:33 UTC, laedanrex commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.spec.ts
> -  it('should have the right values', () => {
mapProjectInternalFields supprimé
code mort ☠️

2023-03-03 10:42 UTC, laedanrex commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/ProjectInternalService.java
> +            ProjectDto projectDto = ProjectConverter.toProjectDto(collectProjectDto);
ouai certe, je ne suis pas convaincu mais ok, fait

2023-03-03 10:44 UTC, oussamasic requested changes

2023-03-03 10:44 UTC, oussamasic commented on ui/ui-frontend/projects/vitamui-library/src/lib/models/search-response.interface.ts
> +  $context: {
il faut pas utiliser les modèles de vitamui-library

2023-03-03 10:44 UTC, oussamasic commented on ui/ui-frontend/projects/vitamui-library/src/lib/components/vitamui-radio-group/vitamui-radio-group.component.ts
> +    console.log('onInit, primary = ' + this.primary);
to delete

2023-03-03 10:44 UTC, oussamasic commented on ui/ui-frontend/projects/vitamui-library/src/lib/components/filing-plan/filing-plan.service.ts
> +export function oneIncludedNodeRequired(): ValidatorFn {
il faut éviter l'utilisation de vitamui-library

2023-03-03 13:51 UTC, oussamasic requested changes

2023-03-03 13:51 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
> +    console.log('projectForm: ' + JSON.stringify(this.projectForm.value));
to delete

2023-03-03 15:07 UTC, laedanrex commented on ui/ui-frontend/projects/vitamui-library/src/lib/components/filing-plan/filing-plan.service.ts
> +export function oneIncludedNodeRequired(): ValidatorFn {
oui mais c'est utilisé par ce component qui est entierement dans vitamui-library

2023-03-03 15:28 UTC, mohatizaoui commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.spec.ts
> -  it('should update project without transactions', waitForAsync(() => {
non cela  update Transaction et update projet sont utilisé dans l'us 10842
et ce test concerne le même us

2023-03-03 15:44 UTC, oussamasic approved these changes

2023-03-03 15:57 UTC, oussamasic requested changes

2023-03-03 15:57 UTC, oussamasic commented on ui/ui-frontend/projects/vitamui-library/src/lib/components/vitamui-radio-group/vitamui-radio-group.component.ts
> +    console.log('onInit, primary = ' + this.primary);
console à supprimer

2023-03-03 15:57 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.spec.ts
> -  it('should update project with transactions', waitForAsync(() => {
ce test concerne la nouvelle fonctionnalité d'update d'un projet, il faut pas le supprimer

2023-03-03 15:57 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.spec.ts
> -    it('should have 10 buttons ', () => {
est-ce qu'on peut juste corriger le test au lieu de le supprimer

2023-03-03 15:57 UTC, oussamasic approved these changes

2023-03-03 16:10 UTC, mohatizaoui commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.spec.ts
> -  it('should update project without transactions', waitForAsync(() => {
bon je vais approuver mais il faut le corriger après

2023-03-03 16:10 UTC, mohatizaoui approved these changes

2023-03-06 07:57 UTC, bbenaissa approved these changes

2023-03-06 11:17 UTC, laedanrex commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.spec.ts
> -    it('should have 10 buttons ', () => {
c'est pas un test à forte valeur: il regarde le nombre de balise button dans la modale toute entière
donc oui y a 12 boutons "suivant"

2023-03-06 11:19 UTC, laedanrex commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.spec.ts
> -  it('should update project without transactions', waitForAsync(() => {
ok remis

2023-03-06 15:28 UTC, merged