update library version mongo-express to fix build
ProgrammeVitam/vitam-ui pull request #1228
Opened 2023-02-21 17:33 UTC by bbenaissa

## Description

L'objectif de cette PR est fixer la version de la librairie de mongo-express pour corriger le pb de build.
## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

2023-02-22 13:25 UTC, oussamasic approved these changes

2023-02-22 18:28 UTC, GiooDev requested changes

2023-02-22 18:28 UTC, GiooDev commented on cots/vitamui-mongo-express/Makefile
> +VERSION             := 5.0.14
En 6.rc nous sommes en 5.0.13

2023-02-23 14:14 UTC, GiooDev requested changes

2023-02-23 14:14 UTC, GiooDev commented on cots/vitamui-mongo-express/package-lock.json
> +  "version": "5.0.14",
pas ici :)

2023-02-23 14:20 UTC, GiooDev approved these changes

2023-02-23 16:46 UTC, merged