story #10997 : PUA data persists in context and remains visible in the PA workflow
ProgrammeVitam/vitam-ui pull request #1236
Opened 2023-02-24 15:59 UTC by mhameg

## Description

Afficher les metadonées sur la partie PA defaçon standard.
Garder le comportement de certaines metadonnées inchangé.

## Type de changement:

* Correction

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

2023-02-24 16:22 UTC, oussamasic approved these changes

2023-02-27 08:07 UTC, mohatizaoui approved these changes

2023-02-27 09:05 UTC, oussamasic requested changes

2023-02-27 09:05 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.ts
> +    if (PA_MANDATORY_ENUM_FIELDS.includes(element.nomDuChamp)){
tu peux ajouter un ou 2 TU sur la méthode : getMetadataInputType

2023-02-28 17:29 UTC, mhameg commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.ts
> +    if (PA_MANDATORY_ENUM_FIELDS.includes(element.nomDuChamp)){
j'ai ajouté quelques test unitaire pour tester les differents cas de fugure

2023-03-01 10:02 UTC, oussamasic approved these changes

2023-03-01 13:10 UTC, merged