Story 10660 Generalization of blocking / unblocking rules inheritance
ProgrammeVitam/vitam-ui pull request #1238
Opened 2023-02-27 16:01 UTC by soukami

## Description

Suite à la mise en place de la fonctionnalité de blocage / déblocage d'une règle sur une règle de DUA , l'objectif de cette US est de généraliser cette action à l'ensemble des règles modifiables sur VITAM UI (DUC, Communicabilité, Diffusion et Réutilisation).

2023-02-28 07:27 UTC, bbenaissa approved these changes

2023-02-28 14:46 UTC, oussamasic approved these changes

2023-02-28 15:07 UTC, bbenaissa requested changes

2023-02-28 15:07 UTC, bbenaissa commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/MetadataSearchCriteriaUtils.java
> +        switch (category.name()) {
Je crois qu'on a des constantes avec ces valeurs que tu peux utiliser

2023-03-01 10:29 UTC, soukami commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/MetadataSearchCriteriaUtils.java
> +        switch (category.name()) {
done

2023-03-01 14:12 UTC, bbenaissa approved these changes

2023-03-02 13:57 UTC, merged