Feature/10996 disable additional props for non extensible seda nodes
ProgrammeVitam/vitam-ui pull request #1251
Opened 2023-03-07 14:49 UTC by Regzox

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2023-03-07 15:49 UTC, TDevillechabrolle commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx One – Scan Summary & Details** – [c08e0cf9\-bc12\-4261\-a22d\-8c78b5de27b8](https://eu.ast.checkmarx.net/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/scans?id=c08e0cf9-bc12-4261-a22d-8c78b5de27b8&branch=feature%2F10996-disable-additional-props-for-non-extensible-seda-nodes)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Client_DOM_Open_Redirect](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/c08e0cf9-bc12-4261-a22d-8c78b5de27b8/sast/description/601/11100132039797172543)|/ui/ui\-frontend/projects/pastis/src/app/shared/pastis\-popup\-option/pastis\-popup\-option\.component\.ts: [115](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/10996-disable-additional-props-for-non-extensible-seda-nodes//ui/ui-frontend/projects/pastis/src/app/shared/pastis-popup-option/pastis-popup-option.component.ts#L115)|[Attack Vector](https://eu.ast.checkmarx.net/results/c08e0cf9-bc12-4261-a22d-8c78b5de27b8/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=NMZzI7SmEq4L%2FciSrUoqbCMbbIA%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/c08e0cf9-bc12-4261-a22d-8c78b5de27b8/sast/description/117/9884244256835554923)|/api/api\-pastis/pastis\-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/controller/PastisController\.java: [92](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/10996-disable-additional-props-for-non-extensible-seda-nodes//api/api-pastis/pastis-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/controller/PastisController.java#L92)|[Attack Vector](https://eu.ast.checkmarx.net/results/c08e0cf9-bc12-4261-a22d-8c78b5de27b8/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=GHqYzmYMJgBQWP8MpScKNBx8X5s%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/c08e0cf9-bc12-4261-a22d-8c78b5de27b8/sast/description/117/9884244256835554923)|/api/api\-pastis/pastis\-external/src/main/java/fr/gouv/vitamui/pastis/server/rest/PastisController\.java: [80](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/10996-disable-additional-props-for-non-extensible-seda-nodes//api/api-pastis/pastis-external/src/main/java/fr/gouv/vitamui/pastis/server/rest/PastisController.java#L80)|[Attack Vector](https://eu.ast.checkmarx.net/results/c08e0cf9-bc12-4261-a22d-8c78b5de27b8/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=N6N5TqcfoUv0%2FlmbNXMZARwXOGY%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/c08e0cf9-bc12-4261-a22d-8c78b5de27b8/sast/description/117/9884244256835554923)|/api/api\-pastis/pastis\-external/src/main/java/fr/gouv/vitamui/pastis/server/rest/PastisController\.java: [124](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/10996-disable-additional-props-for-non-extensible-seda-nodes//api/api-pastis/pastis-external/src/main/java/fr/gouv/vitamui/pastis/server/rest/PastisController.java#L124)|[Attack Vector](https://eu.ast.checkmarx.net/results/c08e0cf9-bc12-4261-a22d-8c78b5de27b8/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=f3b3Do6IWXZhD%2FpUNifNa3RvetU%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/c08e0cf9-bc12-4261-a22d-8c78b5de27b8/sast/description/117/9884244256835554923)|/api/api\-pastis/pastis\-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/controller/PastisController\.java: [159](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/10996-disable-additional-props-for-non-extensible-seda-nodes//api/api-pastis/pastis-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/controller/PastisController.java#L159)|[Attack Vector](https://eu.ast.checkmarx.net/results/c08e0cf9-bc12-4261-a22d-8c78b5de27b8/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=KOGSJwmnQvTF407i%2BmiJITDRhxs%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/c08e0cf9-bc12-4261-a22d-8c78b5de27b8/sast/description/117/9884244256835554923)|/api/api\-pastis/pastis\-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/controller/PastisController\.java: [145](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/10996-disable-additional-props-for-non-extensible-seda-nodes//api/api-pastis/pastis-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/controller/PastisController.java#L145)|[Attack Vector](https://eu.ast.checkmarx.net/results/c08e0cf9-bc12-4261-a22d-8c78b5de27b8/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=qyMOjQBFjXoL%2BZu5WOB6nhqgqQc%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/c08e0cf9-bc12-4261-a22d-8c78b5de27b8/sast/description/117/9884244256835554923)|/api/api\-pastis/pastis\-external/src/main/java/fr/gouv/vitamui/pastis/server/rest/PastisController\.java: [109](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/10996-disable-additional-props-for-non-extensible-seda-nodes//api/api-pastis/pastis-external/src/main/java/fr/gouv/vitamui/pastis/server/rest/PastisController.java#L109)|[Attack Vector](https://eu.ast.checkmarx.net/results/c08e0cf9-bc12-4261-a22d-8c78b5de27b8/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=OsxN8PP3AImopXPQpz8F1%2F4p610%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/c08e0cf9-bc12-4261-a22d-8c78b5de27b8/sast/description/117/9884244256835554923)|/api/api\-pastis/pastis\-external/src/main/java/fr/gouv/vitamui/pastis/server/rest/PastisController\.java: [124](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/10996-disable-additional-props-for-non-extensible-seda-nodes//api/api-pastis/pastis-external/src/main/java/fr/gouv/vitamui/pastis/server/rest/PastisController.java#L124)|[Attack Vector](https://eu.ast.checkmarx.net/results/c08e0cf9-bc12-4261-a22d-8c78b5de27b8/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=6Iru3L%2FoKIRfa%2BJByNCqD%2B0TSwU%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/c08e0cf9-bc12-4261-a22d-8c78b5de27b8/sast/description/117/9884244256835554923)|/api/api\-pastis/pastis\-external/src/main/java/fr/gouv/vitamui/pastis/server/rest/PastisController\.java: [125](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/10996-disable-additional-props-for-non-extensible-seda-nodes//api/api-pastis/pastis-external/src/main/java/fr/gouv/vitamui/pastis/server/rest/PastisController.java#L125)|[Attack Vector](https://eu.ast.checkmarx.net/results/c08e0cf9-bc12-4261-a22d-8c78b5de27b8/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=GEKXNPRB2OUGHWhUmEWrloYhmrA%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8 [...]

2023-03-08 14:41 UTC, oussamasic requested changes

2023-03-08 14:41 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
> +                  // console.log('  result.mode === \'PA\'')
commentaire à supprimer

2023-03-08 14:41 UTC, oussamasic commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/profiles/Notice.java
> +    @JsonProperty("identifier")
une remarque globale : est-ce que le code style de Vitam est bien appliqué ? 
parce que je vois beaucoup de formatage

2023-03-08 14:41 UTC, oussamasic commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/model/DataType.java
> +    //id("id"),
to delete

2023-03-08 14:41 UTC, oussamasic commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/JsonFromPua.java
> +/*
texte du copyright n'est pas bon

2023-03-08 14:41 UTC, oussamasic commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/PuaPastisValidator.java
> +            LOGGER.debug(e.getMessage());
```suggestion
            LOGGER.error(e.getMessage());
```

2023-03-08 14:41 UTC, oussamasic commented on api/api-pastis/pastis-external/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
> +            LOGGER.info("Control schema generated: {}", controlSchema);
debug ?

2023-03-08 14:41 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/core/services/seda.service.spec.ts
> +import { TestBed } from '@angular/core/testing';
il manque le texte du copyright

2023-03-08 14:41 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/models/pua.model.ts
> +interface AchivalUnitProfileDefinition {
il manque le texte du copyright

2023-03-08 14:41 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.html
> +          style="text-transform: uppercase"
style à mettre dans le fichier css du composant

2023-03-08 14:41 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.html
> +                matTooltip="La cardinalité n'est pas conforme aux specifications du SEDA 2.1"
possible d'ajouter le message du tooltip dans les deux fichiers i18n pour qu'il soit traduit

2023-03-08 14:41 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.html
> +                  style="border-top-color: #e0e0e0"
idem : à mettre dans le fichier css

2023-03-08 14:41 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.html
> +                  style="border-top-color: #e0e0e0"
idem

2023-03-08 14:41 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.html
> +                    style="margin-right: 16px; vertical-align: middle; color: #757575; font-size: 1.77em"
idem

2023-03-08 14:41 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.html
> +                <mat-divider *ngIf="element.canEnableAdditionalPropertiesEdition" style="border-top-color: #e0e0e0"> </mat-divider>
idem pour le style

2023-03-08 14:41 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.html
> +                      style="font-size: 1.5em"
idem

2023-03-08 14:41 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.html
> +                  <mat-icon style="color: #757575"><i class="vitamui-icon vitamui-icon-ic24-PUA"></i></mat-icon>
idem

2023-03-08 14:41 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.html
> +        {{ clickedNode.name }} {{ 'PROFILE.EDIT_PROFILE.FILE_TREE_METADATA.MESSAGE_METADONNEE_SANS_FILLES.PARTIEDEUX' | translate }}
dans ce fichier html, il y a plusieurs style css ajoutés directement dans le code html de la page, ca sera mieux de les ajouter dans le fichier css du composant en question

2023-03-08 14:41 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.ts
> +    console.log('The answer for arrays control was ', popUpAnswer);
console à supprimer

2023-03-08 14:41 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree/file-tree.component.html
> +                  <i class="vitamui-icon vitamui-icon-add" style="color: var(--vitamui-primary)"></i>
style dans le fichier css

2023-03-08 14:41 UTC, oussamasic commented
un squash des commits à faire avant le merge

2023-03-08 15:12 UTC, Regzox commented on ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
> +                  // console.log('  result.mode === \'PA\'')
Tous les console.log commentés ont été supprimés.

2023-03-08 15:16 UTC, Regzox commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/JsonFromPua.java
> +/*
C'est un fichier CINES à l'origine.

2023-03-08 15:18 UTC, Regzox commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/model/DataType.java
> +    //id("id"),
fixed

2023-03-08 15:22 UTC, Regzox commented on api/api-pastis/pastis-external/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
> +            LOGGER.info("Control schema generated: {}", controlSchema);
:+1:

2023-03-08 16:38 UTC, Regzox commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.ts
> +    console.log('The answer for arrays control was ', popUpAnswer);
j'ai viré les console.log de pastis

2023-03-08 16:40 UTC, Regzox commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/profiles/Notice.java
> +    @JsonProperty("identifier")
à priori oui, j'ai beaucoup reformaté pour virer des espaces et placer des final afin de mieux visualiser les constantes et les variables.

2023-03-08 17:05 UTC, Regzox commented on ui/ui-frontend/projects/pastis/src/app/core/services/seda.service.spec.ts
> +import { TestBed } from '@angular/core/testing';
fait

2023-03-08 17:06 UTC, Regzox commented on ui/ui-frontend/projects/pastis/src/app/models/pua.model.ts
> +interface AchivalUnitProfileDefinition {
Pas mon fichier à l'origine

2023-03-08 18:11 UTC, Regzox commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.html
> +                matTooltip="La cardinalité n'est pas conforme aux specifications du SEDA 2.1"
fait

2023-03-13 11:04 UTC, oussamasic requested changes

2023-03-13 11:04 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/shared/pastis-dialog/pastis-dialog-confirm/pastis-dialog-confirm.component.ts
> +    this.popUpService.popUpDataBeforeClose.subscribe((data) => {
à ajouter dans une subscription et à détruire après dans le ngOndestroy pour libérer la mémoire

2023-03-13 11:04 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/shared/pastis-popup-metadata-language/pastis-popup-metadata-language.component.ts
> +    this.metadataLanguageService.sedaLanguage.subscribe((value: boolean) => {
à ajouter dans une subscription et à détruire après dans le ngOndestroy pour libérer la mémoire

2023-03-13 11:04 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-preview.component.ts
> +      this.profileService.getProfile(inputProfile).subscribe((retrievedData) => {
à ajouter dans une subscription et à détruire après dans le ngOndestroy pour libérer la mémoire

2023-03-13 11:04 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-preview.component.ts
> +        this.profileService.uploadFile(this.fileNode, profileResponse.notice, inputProfile.type).subscribe((data) => {
idem

2023-03-13 11:04 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.ts
> +        this.profileService.checkPuaProfile(archivalProfileUnit).subscribe((response: boolean) => {
à ajouter dans une subscription et à détruire après dans le ngOndestroy pour libérer la mémoire

2023-03-13 11:04 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.ts
> +        this.profileService.checkPaProfile(profile).subscribe((response: boolean) => {
idem

2023-03-13 11:04 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
> +                            this.profileService.updateProfilePua(this.archivalProfileUnit).subscribe(
idem

2023-03-13 11:04 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
> +        this.profileService.uploadFile(this.data, notice, this.profileService.profileMode).subscribe((retrievedData) => {
idem

2023-03-13 11:04 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
> +        this.profileService.uploadFile(this.data, this.profileDescription, this.profileService.profileMode).subscribe((retrievedData) => {
idem

2023-03-24 16:03 UTC, GiooDev commented
Descoper de l'IT 116, PR trop conséquente à faire passer à la fin de l'IT.

2024-05-31 14:15 UTC, closed without merging