[VAS]-11255: retrieve mgt rules for collect unit
ProgrammeVitam/vitam-ui pull request #1281
Opened 2023-03-22 16:53 UTC by bbenaissa

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2023-03-22 17:52 UTC, TDevillechabrolle commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx One – Scan Summary & Details** – [c6e13a1e\-3cb1\-4623\-bd6d\-ed26dd045440](https://eu.ast.checkmarx.net/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/scans?id=c6e13a1e-3cb1-4623-bd6d-ed26dd045440&branch=feature%2Fvas-11255-retrieve-mgt-rules-for-collect-units)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Privacy_Violation](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/c6e13a1e-3cb1-4623-bd6d-ed26dd045440/sast/description/359/12956636075206043460)|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService\.java: [110](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas-11255-retrieve-mgt-rules-for-collect-units//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService.java#L110)|[Attack Vector](https://eu.ast.checkmarx.net/results/c6e13a1e-3cb1-4623-bd6d-ed26dd045440/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=YOttuugejtALHlyj5g0e4BVjW%2Bk%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[SSRF](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/c6e13a1e-3cb1-4623-bd6d-ed26dd045440/sast/description/918/15179929566605030594)|/ui/ui\-collect/src/main/java/fr/gouv/vitamui/collect/rest/TransactionController\.java: [232](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas-11255-retrieve-mgt-rules-for-collect-units//ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/TransactionController.java#L232)|[Attack Vector](https://eu.ast.checkmarx.net/results/c6e13a1e-3cb1-4623-bd6d-ed26dd045440/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=%2FCeR1PTXyy8tsXxOtE60ny1NUAc%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Unchecked_Input_for_Loop_Condition](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/c6e13a1e-3cb1-4623-bd6d-ed26dd045440/sast/description/606/10402229133361412662)|/ui/ui\-collect/src/main/java/fr/gouv/vitamui/collect/rest/TransactionController\.java: [267](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas-11255-retrieve-mgt-rules-for-collect-units//ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/TransactionController.java#L267)|[Attack Vector](https://eu.ast.checkmarx.net/results/c6e13a1e-3cb1-4623-bd6d-ed26dd045440/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=bGZ%2FLDGkVs4fbUWI7R2FzuOk%2B5g%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Unchecked_Input_for_Loop_Condition](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/c6e13a1e-3cb1-4623-bd6d-ed26dd045440/sast/description/606/10402229133361412662)|/api/api\-collect/collect\-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/TransactionArchiveUnitInternalController\.java: [170](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas-11255-retrieve-mgt-rules-for-collect-units//api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/TransactionArchiveUnitInternalController.java#L170)|[Attack Vector](https://eu.ast.checkmarx.net/results/c6e13a1e-3cb1-4623-bd6d-ed26dd045440/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=0BJCcuh0uaZgRG96xnoHc2M9vq4%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Unchecked_Input_for_Loop_Condition](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/c6e13a1e-3cb1-4623-bd6d-ed26dd045440/sast/description/606/10402229133361412662)|/api/api\-collect/collect\-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/TransactionArchiveUnitExternalController\.java: [147](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas-11255-retrieve-mgt-rules-for-collect-units//api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/TransactionArchiveUnitExternalController.java#L147)|[Attack Vector](https://eu.ast.checkmarx.net/results/c6e13a1e-3cb1-4623-bd6d-ed26dd045440/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=eEiXOc3qWgG9NQfLedWtMGwKuLQ%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Unchecked_Input_for_Loop_Condition](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/c6e13a1e-3cb1-4623-bd6d-ed26dd045440/sast/description/606/10402229133361412662)|/ui/ui\-collect/src/main/java/fr/gouv/vitamui/collect/rest/TransactionController\.java: [131](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas-11255-retrieve-mgt-rules-for-collect-units//ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/TransactionController.java#L131)|[Attack Vector](https://eu.ast.checkmarx.net/results/c6e13a1e-3cb1-4623-bd6d-ed26dd045440/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=MMQQKUhbE95KjCOG4r9Q%2BQ3%2F5Yk%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/c6e13a1e-3cb1-4623-bd6d-ed26dd045440/sast/description/117/9884244256835554923)|/api/api\-collect/collect\-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/TransactionArchiveUnitInternalController\.java: [170](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas-11255-retrieve-mgt-rules-for-collect-units//api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/TransactionArchiveUnitInternalController.java#L170)|[Attack Vector](https://eu.ast.checkmarx.net/results/c6e13a1e-3cb1-4623-bd6d-ed26dd045440/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=L7Cl%2FkZmhnSWp5vGsyUk0dPLuUk%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/c6e13a1e-3cb1-4623-bd6d-ed26dd045440/sast/description/117/9884244256835554923)|/ui/ui\-collect/src/main/java/fr/gouv/vitamui/collect/rest/TransactionController\.java: [233](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas-11255-retrieve-mgt-rules-for-collect-units//ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/TransactionController.java#L233)|[Attack Vector](https://eu.ast.checkmarx.net/results/c6e13a1e-3cb1-4623-bd6d-ed26dd045440/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=XKSc7IxpcU0yry%2FgFRbmCETRLjU%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/c6e13a1e-3cb1-4623-bd6d-ed26dd045440/sast/description/117/9884244256835554923)|/ui/ui\-collect/src/main/java/fr/gouv/vitamui/collect/rest/TransactionController\.java: [233](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas-11255-retrieve-mgt-rules-for-collect-units//ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/TransactionController.java#L233)|[Attack Vector](https://eu.ast.checkmarx.net/results/c6e13a1e-3cb1-4623-bd6d-ed26dd045440/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=zd4oQfOZR%2FmpvC2S5PRYYKQAlAk%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/c6e13a1e-3cb1-4623-bd6d-ed26dd045440/sast/descripti [...]

2023-03-23 18:32 UTC, oussamasic requested changes

2023-03-23 18:32 UTC, oussamasic commented on api/api-archive-search/archive-search-commons/src/test/java/fr/gouv/vitamui/archives/search/common/RulesUpdateCommonServiceTest.java
> + *  * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2015-2023)
un nouveau copyright ?

2023-03-23 18:32 UTC, oussamasic commented on api/api-collect/collect-external-client/src/main/java/fr/gouv/vitamui/collect/external/client/CollectTransactionExternalRestClient.java
> +                    fr.gouv.vitamui.archives.search.common.rest.RestApi.UNIT_WITH_INHERITED_RULES,
constante à ajouter dans les imports

2023-03-23 18:32 UTC, oussamasic commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/TransactionArchiveUnitExternalController.java
> +        throws InvalidParseOperationException, PreconditionFailedException {
il manque le check sanity du transactionId

2023-03-23 18:32 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/TransactionArchiveUnitInternalController.java
> +        SanityChecker.checkSecureParameter(accessContractId);
il manque le check sanity du transactionId

2023-03-23 18:32 UTC, oussamasic commented on ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/TransactionController.java
> +        SanityChecker.sanitizeCriteria(searchQuery);
il manque le check sanity du transactionId

2023-03-23 18:32 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-details-tab.component.ts
> +    console.log(archiveUnit)
console to delete

2023-03-24 09:09 UTC, mohatizaoui commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-collect.service.ts
> +    headers = headers.append('X-Access-Contract-Id', accessContract);
il faut vérifier si transaction id est null  car on peut avoir un projet sans transactions

2023-03-24 09:09 UTC, mohatizaoui commented on ui/ui-frontend/projects/collect/src/app/collect/core/api/transaction-api.service.ts
> +  selectUnitWithInheritedRules(tranasctionId: string, criteriaDto: SearchCriteriaDto, headers?: HttpHeaders): Observable<Unit> {
idem

2023-03-24 09:14 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-collect.service.ts
> +    headers = headers.append('X-Access-Contract-Id', accessContract);
il est toujours non null, vu que l'appel est lancé sur une unité archivistique (d'une transaction)

2023-03-24 09:23 UTC, bbenaissa commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-collect.service.ts
> +    headers = headers.append('X-Access-Contract-Id', accessContract);
Controle ajouté avant l'appel du service

2023-03-24 09:23 UTC, bbenaissa commented on ui/ui-frontend/projects/collect/src/app/collect/core/api/transaction-api.service.ts
> +  selectUnitWithInheritedRules(tranasctionId: string, criteriaDto: SearchCriteriaDto, headers?: HttpHeaders): Observable<Unit> {
Controle ajouté avant l'appel du service

2023-03-24 09:29 UTC, mohatizaoui approved these changes

2023-03-24 10:03 UTC, oussamasic requested changes

2023-03-24 10:03 UTC, oussamasic commented on ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/TransactionController.java
> +        SanityChecker.sanitizeCriteria(transactionId);
il faut utiliser plutôt la méthode `checkSecureParameters` à la place de `sanitizeCriteria` pour les paramètres de type String

2023-03-24 10:03 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/TransactionArchiveUnitInternalController.java
> +        SanityChecker.checkSecureParameter(accessContractId);
il manque le check sanity du transactionId

2023-03-24 10:06 UTC, bbenaissa commented on ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/TransactionController.java
> +        SanityChecker.sanitizeCriteria(transactionId);
+1

2023-03-24 10:10 UTC, bbenaissa commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/TransactionArchiveUnitInternalController.java
> +        SanityChecker.checkSecureParameter(accessContractId);
corrigé

2023-03-24 10:10 UTC, bbenaissa commented on ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/TransactionController.java
> +        SanityChecker.sanitizeCriteria(transactionId);
corrigé

2023-03-24 10:10 UTC, bbenaissa commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/TransactionArchiveUnitInternalController.java
> +        SanityChecker.checkSecureParameter(accessContractId);
corrigé

2023-03-24 10:50 UTC, oussamasic approved these changes

2023-03-24 11:14 UTC, merged