[WIP] Bug/vas 10897 manage acccess contracts errors
ProgrammeVitam/vitam-ui pull request #1306
Opened 2023-04-06 10:13 UTC by bbenaissa

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2023-04-06 11:16 UTC, TDevillechabrolle commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx One – Scan Summary & Details** – [923278a1\-8f99\-414a\-9785\-6a3e35dae06c](https://eu.ast.checkmarx.net/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/scans?id=923278a1-8f99-414a-9785-6a3e35dae06c&branch=bug%2Fvas-10897-manage-acccess-contracts-errors)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[Reflected_XSS_All_Clients](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/923278a1-8f99-414a-9785-6a3e35dae06c/sast/description/79/8481125285487743346)|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService\.java: [118](https://github.com/ProgrammeVitam/vitam-ui/blob/bug/vas-10897-manage-acccess-contracts-errors//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService.java#L118)|[Attack Vector](https://eu.ast.checkmarx.net/results/923278a1-8f99-414a-9785-6a3e35dae06c/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=LGRK8BxOnQNIIyelMbEhRBta%2FEs%3D&redirect=true)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[Reflected_XSS_All_Clients](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/923278a1-8f99-414a-9785-6a3e35dae06c/sast/description/79/8481125285487743346)|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService\.java: [118](https://github.com/ProgrammeVitam/vitam-ui/blob/bug/vas-10897-manage-acccess-contracts-errors//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService.java#L118)|[Attack Vector](https://eu.ast.checkmarx.net/results/923278a1-8f99-414a-9785-6a3e35dae06c/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=wh2w%2BvXofsesvNk61aAVytsZ0s8%3D&redirect=true)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[Reflected_XSS_All_Clients](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/923278a1-8f99-414a-9785-6a3e35dae06c/sast/description/79/8481125285487743346)|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService\.java: [118](https://github.com/ProgrammeVitam/vitam-ui/blob/bug/vas-10897-manage-acccess-contracts-errors//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService.java#L118)|[Attack Vector](https://eu.ast.checkmarx.net/results/923278a1-8f99-414a-9785-6a3e35dae06c/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=ifHMf%2BHfxJHLyjhL%2F9Um17WObu8%3D&redirect=true)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[Reflected_XSS_All_Clients](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/923278a1-8f99-414a-9785-6a3e35dae06c/sast/description/79/8481125285487743346)|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService\.java: [118](https://github.com/ProgrammeVitam/vitam-ui/blob/bug/vas-10897-manage-acccess-contracts-errors//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService.java#L118)|[Attack Vector](https://eu.ast.checkmarx.net/results/923278a1-8f99-414a-9785-6a3e35dae06c/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=fWIVn0etqgvIXoVem6ou5jIr8R8%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Cleartext_Submission_of_Sensitive_Information](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/923278a1-8f99-414a-9785-6a3e35dae06c/sast/description/319/5872693300309307288)|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService\.java: [110](https://github.com/ProgrammeVitam/vitam-ui/blob/bug/vas-10897-manage-acccess-contracts-errors//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService.java#L110)|[Attack Vector](https://eu.ast.checkmarx.net/results/923278a1-8f99-414a-9785-6a3e35dae06c/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=UbtGEERXXQMdQwbbyOJ72jqmiDc%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Cleartext_Submission_of_Sensitive_Information](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/923278a1-8f99-414a-9785-6a3e35dae06c/sast/description/319/5872693300309307288)|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService\.java: [118](https://github.com/ProgrammeVitam/vitam-ui/blob/bug/vas-10897-manage-acccess-contracts-errors//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService.java#L118)|[Attack Vector](https://eu.ast.checkmarx.net/results/923278a1-8f99-414a-9785-6a3e35dae06c/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=in9DRKKaNEcGozlqM7rtX%2F8M5NE%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Cleartext_Submission_of_Sensitive_Information](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/923278a1-8f99-414a-9785-6a3e35dae06c/sast/description/319/5872693300309307288)|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService\.java: [110](https://github.com/ProgrammeVitam/vitam-ui/blob/bug/vas-10897-manage-acccess-contracts-errors//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService.java#L110)|[Attack Vector](https://eu.ast.checkmarx.net/results/923278a1-8f99-414a-9785-6a3e35dae06c/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=eU%2F3YL6kTZtqcE5%2FhvH0cRifbCE%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Cleartext_Submission_of_Sensitive_Information](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/923278a1-8f99-414a-9785-6a3e35dae06c/sast/description/319/5872693300309307288)|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService\.java: [118](https://github.com/ProgrammeVitam/vitam-ui/blob/bug/vas-10897-manage-acccess-contracts-errors//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService.java#L118)|[Attack Vector](https://eu.ast.checkmarx.net/results/923278a1-8f99-414a-9785-6a3e35dae06c/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=w%2FXBQpmp1a5fRgQ4QSrZX5TxEcs%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Cleartext_Submission_of_Sensitive_Information](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/923278a1-8f99-414a-9785-6a3e35dae06c/sast/description/319/5872693300309307288)|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService\.java: [110](https://github.com/ProgrammeVitam/vitam-ui/blob/bug/vas-10897-manage-acccess-contracts-errors//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService.java#L110)|[Attack Vector](https://eu.ast.checkmarx.net/results/923278a1-8f99-414a-9785-6a3e35dae06c/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=6tTzz2aIUN25uDryOErU2EurVLM%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Cleartext_Submission_of_Sensitive_Information](https://eu.ast.checkmarx.net/results/ [...]

2023-04-12 07:28 UTC, laedanrex approved these changes

2023-04-12 09:56 UTC, oussamasic requested changes

2023-04-12 09:56 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ExternalParametersServiceTest.java
> + *  * successive licensors have only limited liability.
un mauvais copyright

2023-04-12 09:56 UTC, oussamasic commented on api/api-collect/collect-internal/src/test/java/fr/gouv/vitamui/collect/internal/server/service/ExternalParametersServiceTest.java
> + *  * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2015-2023)
idem

2023-04-12 14:46 UTC, soukami approved these changes

2023-04-19 18:09 UTC, oussamasic approved these changes

2023-04-20 07:32 UTC, merged