Feature/trv/gateway
ProgrammeVitam/vitam-ui pull request #1309
Opened 2023-04-11 07:45 UTC by pyXelians

Cette  PR contient l'ajout de la gateway afin de simplifier l'architecture de l'application. 

## Type de changement

-  Code et/ou Configuration : Correction, évolution

## Tests

Suite au build un rapport de test est généré avec les vulnérabilités. 

## Migration

 Quels sont les opérations supplémentaires à faire lors d’une migration de VITAM ? 
 De quel version à quel version s’appliquent ces modifications ?

## Checklist

 [ * ] Les tests unitaires nouveaux et existants passent avec succès localement.
 [ * ] Toutes les dépendances ont été mergées en priorité

## Contributeur

Xelians

2023-04-11 08:46 UTC, TDevillechabrolle commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx One – Scan Summary & Details** – [06978b6e\-5d37\-4d1d\-832b\-39c822064f73](https://eu.ast.checkmarx.net/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/scans?id=06978b6e-5d37-4d1d-832b-39c822064f73&branch=feature%2Ftrv%2Fgateway)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Absolute_Path_Traversal](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/06978b6e-5d37-4d1d-832b-39c822064f73/sast/description/36/4635938147065118004)|/ui/ui\-pastis/src/main/java/fr/gouv/vitamui/pastis/rest/ProfileController\.java: [245](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/trv/gateway//ui/ui-pastis/src/main/java/fr/gouv/vitamui/pastis/rest/ProfileController.java#L245)|[Attack Vector](https://eu.ast.checkmarx.net/results/06978b6e-5d37-4d1d-832b-39c822064f73/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=iL7YifXLZYYBHbSO5zcfYfBYo%2Fg%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Absolute_Path_Traversal](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/06978b6e-5d37-4d1d-832b-39c822064f73/sast/description/36/4635938147065118004)|/ui/ui\-referential/src/main/java/fr/gouv/vitamui/referential/rest/RuleController\.java: [219](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/trv/gateway//ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/RuleController.java#L219)|[Attack Vector](https://eu.ast.checkmarx.net/results/06978b6e-5d37-4d1d-832b-39c822064f73/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=ZSoZL5YPw9kPWwGsVBtAsGW1rDc%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Absolute_Path_Traversal](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/06978b6e-5d37-4d1d-832b-39c822064f73/sast/description/36/4635938147065118004)|/ui/ui\-commons/src/main/java/fr/gouv/vitamui/ui/commons/rest/RuleController\.java: [211](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/trv/gateway//ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/rest/RuleController.java#L211)|[Attack Vector](https://eu.ast.checkmarx.net/results/06978b6e-5d37-4d1d-832b-39c822064f73/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=igJY0J4ofeprOvPEq%2FfBRmpusSs%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Absolute_Path_Traversal](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/06978b6e-5d37-4d1d-832b-39c822064f73/sast/description/36/4635938147065118004)|/ui/ui\-pastis/src/main/java/fr/gouv/vitamui/pastis/rest/ArchivalProfileUnitController\.java: [211](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/trv/gateway//ui/ui-pastis/src/main/java/fr/gouv/vitamui/pastis/rest/ArchivalProfileUnitController.java#L211)|[Attack Vector](https://eu.ast.checkmarx.net/results/06978b6e-5d37-4d1d-832b-39c822064f73/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=%2BxxS9puwnfxt9hU%2Bkgyl9gekxgM%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Absolute_Path_Traversal](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/06978b6e-5d37-4d1d-832b-39c822064f73/sast/description/36/4635938147065118004)|/ui/ui\-pastis/src/main/java/fr/gouv/vitamui/pastis/rest/PastisController\.java: [99](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/trv/gateway//ui/ui-pastis/src/main/java/fr/gouv/vitamui/pastis/rest/PastisController.java#L99)|[Attack Vector](https://eu.ast.checkmarx.net/results/06978b6e-5d37-4d1d-832b-39c822064f73/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=oxiWxtwwatfDexyWfhHZyhiTdMo%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Absolute_Path_Traversal](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/06978b6e-5d37-4d1d-832b-39c822064f73/sast/description/36/4635938147065118004)|/ui/ui\-referential/src/main/java/fr/gouv/vitamui/referential/rest/FileFormatController\.java: [244](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/trv/gateway//ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/FileFormatController.java#L244)|[Attack Vector](https://eu.ast.checkmarx.net/results/06978b6e-5d37-4d1d-832b-39c822064f73/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=gsjxzC67OnYVcXrLWagKda6Mnqk%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Absolute_Path_Traversal](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/06978b6e-5d37-4d1d-832b-39c822064f73/sast/description/36/4635938147065118004)|/ui/ui\-referential/src/main/java/fr/gouv/vitamui/referential/rest/AgencyController\.java: [214](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/trv/gateway//ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/AgencyController.java#L214)|[Attack Vector](https://eu.ast.checkmarx.net/results/06978b6e-5d37-4d1d-832b-39c822064f73/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=%2FHGOYjyZj0oMTJu5tvsz7cVkgL8%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Absolute_Path_Traversal](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/06978b6e-5d37-4d1d-832b-39c822064f73/sast/description/36/4635938147065118004)|/api/api\-referential/referential\-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ProfileExternalController\.java: [210](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/trv/gateway//api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ProfileExternalController.java#L210)|[Attack Vector](https://eu.ast.checkmarx.net/results/06978b6e-5d37-4d1d-832b-39c822064f73/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=DGPAB5TfiSUq46aduC2ePGpL0mk%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Absolute_Path_Traversal](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/06978b6e-5d37-4d1d-832b-39c822064f73/sast/description/36/4635938147065118004)|/ui/ui\-referential/src/main/java/fr/gouv/vitamui/referential/rest/OntologyController\.java: [206](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/trv/gateway//ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/OntologyController.java#L206)|[Attack Vector](https://eu.ast.checkmarx.net/results/06978b6e-5d37-4d1d-832b-39c822064f73/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=otI8CVmlRH2IfKRPwWqb1nqsBvE%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Cleartext_Submission_of_Sensitive_Information](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/06978b6e-5d37-4d1d-832b-39c822064f73/sast/description/319/5872693300309307288)|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/ExternalSecurityService\.java: [133](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/trv/gateway//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/ExternalSecurityService.java#L133)|[Attack Vector](https://eu.ast.checkmarx.net/results/06978b6e-5d37-4d1d-832b-39c822064f73/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=Ee5AebGkUwY%2Fe2H36vre0ua7v2U%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/4 [...]

2023-04-11 13:33 UTC, GiooDev requested changes

2023-04-11 13:33 UTC, GiooDev commented on deployment/environments/group_vars/all/vitamui_vars.yml
> +  doc_tenant: 9
Ça correspond à quoi ce doc_tenant ?

2023-04-11 13:33 UTC, GiooDev commented on dev-deployment/environments/hosts
> +hosts_vitamui_api_gateway
Il faudrait mettre à jour le fichier d'inventaire d'exemple: `deployment/environments/hosts-ui.example`

2023-04-17 08:58 UTC, anasstsdi commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchRulesInternalService.java
> +     * @param rulesIdentifiers
@param ruleType

2023-04-17 08:58 UTC, anasstsdi commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchRulesInternalService.java
> +    public ArchiveUnit fillOriginatingAgencyName(ResultsDto originResponse,
je vois pas d'usage de cette methode

2023-04-17 08:58 UTC, anasstsdi commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchRulesInternalService.java
> +    public List<FileRulesModel> findRulesByIdentifiers(VitamContext vitamContext, Set<String> rulesIdentifiers,
je vois pas d'usage de cette methode

2023-04-17 08:58 UTC, anasstsdi commented on api/api-gateway/src/main/resources/application-dev.yml
> +          uri: https://localhost:8083  # URL IAM EXTERNAL
il faut appeler le service par son nom enregisté sur Consule. on crée une dependence forte en l'appelant avec son adresse IP

2023-04-17 08:58 UTC, anasstsdi commented on api/api-referential/referential-internal/src/main/config/access-external-client.conf
> +serverHost: dev.xelians-dev.fr
un oublie, faut changer l'adresse

2023-04-19 09:43 UTC, pyXelians commented on deployment/environments/group_vars/all/vitamui_vars.yml
> +  doc_tenant: 9
c'est une variable que nous avons ajoutée pour éviter de mettre en dure la valeur du tenant identifier. Elle était historiquement a 9, nous avons gardé le même comportement en donnant la possibilité de le surcharger plus facilement.

2023-04-19 09:52 UTC, pyXelians commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchRulesInternalService.java
> +     * @param rulesIdentifiers
Nous n'intervenons sur ces modules -> ça doit être un loupé au niveau du merge. Je vais reset avec le contenu de votre branche.

2023-04-19 09:52 UTC, pyXelians commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchRulesInternalService.java
> +    public ArchiveUnit fillOriginatingAgencyName(ResultsDto originResponse,
Nous n'intervenons sur ces modules -> ça doit être un loupé au niveau du merge. Je vais reset avec le contenu de votre branche.

2023-04-19 09:53 UTC, pyXelians commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchRulesInternalService.java
> +    public List<FileRulesModel> findRulesByIdentifiers(VitamContext vitamContext, Set<String> rulesIdentifiers,
Nous n'intervenons sur ces modules -> ça doit être un loupé au niveau du merge. Je vais reset avec le contenu de votre branche.

2023-04-19 09:54 UTC, pyXelians commented on api/api-gateway/src/main/resources/application-dev.yml
> +          uri: https://localhost:8083  # URL IAM EXTERNAL
Ce fichier de configuration est utilisé pour la partie développement sur les postes de devs; il sera surchargé par vos soins lors du déploiement. (en local sur les postes de devs nous n'utilisons pas consul)

2023-04-19 09:57 UTC, pyXelians commented on api/api-referential/referential-internal/src/main/config/access-external-client.conf
> +serverHost: dev.xelians-dev.fr
c'est corrigé

2023-04-20 08:39 UTC, oussamasic requested changes
Remarques générales : 
- à vérifier si le code style de VitamUI est bien appliqué ou non.
- Texte du copyright à mettre à jour.
- Texte du copyright à ajouter dans les nouveaux fichiers .ts
- La suppression des modules ui-identity, ui-portal et ui-referential est prévu pour quand ?

2023-04-20 08:39 UTC, oussamasic commented on api/api-gateway/src/main/java/fr/gouv/vitamui/gateway/ApiGatewayServerApplication.java
> +package fr.gouv.vitamui.gateway;
il manque le texte du copyright

2023-04-20 08:39 UTC, oussamasic commented on api/api-gateway/src/main/java/fr/gouv/vitamui/gateway/config/NettyServerCustomizer.java
> +package fr.gouv.vitamui.gateway.config;
il manque le texte du copyright

2023-04-20 08:39 UTC, oussamasic commented on api/api-gateway/src/main/java/fr/gouv/vitamui/gateway/filters/X509CertificateFilter.java
> +package fr.gouv.vitamui.gateway.filters;
idem

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/domain/dto/ProviderPatchType.java
> +/**
ancien texte du copyright, à mettre à jour

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/ApplicationExternalController.java
> +        //RestUtils.checkCriteria(criteria);
commentaire à supprimer

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/ApplicationExternalController.java
> +        LOGGER.debug("isApplicationExternalIdentifierEnabled");
un check sanity à ajouter sur l'identifer avant le log

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/CustomerExternalController.java
> -        SanityChecker.checkSecureParameter(id);
pourquoi tu as supprimé ça ?

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/ApplicationExternalController.java
> +    @GetMapping("/filtered")
à mettre dans dans CommonConstants, c'est plus propre

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/ExternalParamProfileExternalController.java
> +        //RestUtils.checkCriteria(criteria);
to delete

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/ExternalParamProfileExternalController.java
> +        LOGGER.debug("get logbook for external parameter profile with id :{}", id);
pour des raisons de sécurité il faut mettre le log après le check sanity,

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/GroupExternalController.java
> +        LOGGER.debug("get logbook for group with id :{}", id);
pour des raisons de sécurité il faut mettre le log après le check sanity (après la ligne 179).

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/IdentityProviderExternalController.java
> +        final Resource resource = identityProviderCrudService.getMetadataProviderByProviderId(id, ProviderEmbeddedOptions.IDPMETADATA, IamUtils.buildOptionalEmbedded(ProviderEmbeddedOptions.IDPMETADA
un check sanity sur l'id à ajouter

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/IdentityProviderExternalController.java
> +        final Resource resource = identityProviderCrudService.getMetadataProviderByProviderId(id, ProviderEmbeddedOptions.SPMETADATA, IamUtils.buildOptionalEmbedded(ProviderEmbeddedOptions.SPMETADATA
un check sanity sur l'id à ajouter

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/IdentityProviderExternalController.java
> +
proposition : 
une seule API au lieu de ces deux, en ajoutant un QueryParam  metadataType qui va permettre de savoir le type de metadata qu'on souhaite récupérer

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/OwnerExternalController.java
> +        LOGGER.debug("get logbook for owner with id :{}", id);
logger à supprimer

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/SecurityController.java
> +package fr.gouv.vitamui.iam.external.server.rest;
il manque le texte du copyright

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/TenantExternalController.java
> -        SanityChecker.checkSecureParameter(id);
il faut pas supprimer cette ligne

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/UserExternalController.java
> -        SanityChecker.checkSecureParameter(id);
il faut pas supprimer ces deux lignes du sanitizing

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/service/ApplicationService.java
> +/**
mauvais texte du copyright

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/service/UserExternalService.java
> +import com.fasterxml.jackson.core.JsonProcessingException;
le code style de VitamUI est bien appliqué ?

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/service/InitCustomerService.java
> +        for (final Profile p : filteredProfiles) {
c'est pas vrai, on a des applications avec plus d'un seul profil (2, 3 profils pour la même application).

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/domain/AlertAnalytics.java
> +package fr.gouv.vitamui.iam.internal.server.user.domain;
il manque texte du copyright

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/converter/UserConverter.java
> +                alertAnalyticsDto.setId(alert.getId());
```suggestion
                BeanUtils.copyProperties(alert, alertAnalyticsDto);
```

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/rest/CustomerCrudControllerTest.java
> +
des imports inutiles je pense

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/RequestAttributeX509CertificateExtractor.java
> +package fr.gouv.vitamui.iam.security.filter;
copyright

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/RequestAttributeX509CertificateExtractor.java
> +
```suggestion
    private static final VitamUILogger LOGGER = VitamUILoggerFactory.getInstance(RequestAttributeX509CertificateExtractor.class);

```

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/RequestHeaderX509CertificateExtractor.java
> +    private static final Log LOGGER = LogFactory.getLog(RequestHeaderX509CertificateExtractor.class);
```suggestion
    private static final VitamUILogger LOGGER = VitamUILoggerFactory.getInstance(RequestHeaderX509CertificateExtractor.class);
    
```

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/RequestHeaderX509CertificateExtractor.java
> +package fr.gouv.vitamui.iam.security.filter;
copyright

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/TokenExtractor.java
> +package fr.gouv.vitamui.iam.security.filter;
copyright

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/X509CertificateExtractor.java
> +package fr.gouv.vitamui.iam.security.filter;
idem

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-security/src/test/java/fr/gouv/vitamui/iam/security/filter/TokenExtractorTest.java
> +package fr.gouv.vitamui.iam.security.filter;
idem

2023-04-20 08:39 UTC, oussamasic commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OntologyExternalController.java
> +        LOGGER.debug("get logbook for ontology with id :{}", id);
to delete, code dupliqué

2023-04-20 08:39 UTC, oussamasic commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OntologyExternalController.java
> +
```
        SanityChecker.isValidFileName(file.getOriginalFilename());
        SafeFileChecker.checkSafeFilePath(file.getOriginalFilename());
```
à ajouter avant le log

2023-04-20 08:39 UTC, oussamasic commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OperationExternalController.java
> +        LOGGER.debug("get logbook for audit with id :{}", id);
log to delete

2023-04-20 08:39 UTC, oussamasic commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/RuleExternalController.java
> +import fr.gouv.vitamui.referential.common.dto.RuleDto;
pourquoi tout ces imports ?

2023-04-20 08:39 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchRulesInternalService.java
> +    public ArchiveUnit fillOriginatingAgencyName(ResultsDto originResponse,
méthode inutile, to delete

2023-04-20 08:39 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchRulesInternalService.java
> +    public List<FileRulesModel> findRulesByIdentifiers(VitamContext vitamContext, Set<String> rulesIdentifiers,
méthode inutile, to delete

2023-04-20 08:39 UTC, oussamasic commented on api/api-gateway/src/main/java/fr/gouv/vitamui/gateway/filters/X509CertificateFilter.java
> +    private static final Logger logger = LoggerFactory.getLogger(X509CertificateFilter.class);
```suggestion
    private static final VitamUILogger LOGGER = VitamUILoggerFactory.getInstance(X509CertificateFilter.class);

```

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/IdentityProviderExternalController.java
> +    // FXME MDI - Ignore with Failed to execute goal 'convertSwagger2markup': Type of parameter 'keystore' must not be blank
FIXME ?

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/IdentityProviderExternalController.java
> +    @ApiIgnore // FXME MDI - Ignore with Failed to execute goal 'convertSwagger2markup': Type of parameter 'provider' must not be blank
FIXME ?

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/service/UserExternalService.java
> +                throw new ForbiddenException(String.format("Unable to patch analytics for user with id: %s", partialDto.get(USER_ID_ATTRIBUTE)));
c'est plutôt `UnAuthorizedException` au lieu de ForbiddenException

2023-04-20 08:39 UTC, oussamasic commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/UserInfoInternalController.java
> +
pourquoi tout ces imports ?

2023-04-20 08:39 UTC, oussamasic commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamAgencyService.java
> +        fr.gouv.vitamui.commons.vitam.api.dto.LogbookOperationsResponseDto lastImportOperation = VitamRestUtils.responseMapping(lastImportOperationResponse.toJsonNode(), LogbookOperationsResponseDto.
```suggestion
         LogbookOperationsResponseDto lastImportOperation = VitamRestUtils.responseMapping(lastImportOperationResponse.toJsonNode(), LogbookOperationsResponseDto.class);
```

2023-04-20 08:39 UTC, oussamasic commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/SecurityProfileExternalService.java
> +import java.util.*;
problème de formatage ?

2023-04-20 08:39 UTC, oussamasic commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/SecurityProfileExternalService.java
> +import java.util.*;
problème de formatage ?

2023-04-20 08:39 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/config/collect-client.conf
> +serverHost: dev.xelians-dev.fr
pas besoin de commiter ces 3 fichiers de configuration

2023-04-20 08:39 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/config/ingest-external-client.conf
> +serverHost: dev.xelians-dev.fr
3 fichiers de conf inutiles coté VitamUI

2023-04-20 08:39 UTC, oussamasic commented on cas/cas-server/src/main/config/cas-server-application-dev.yml
> +    #trust-store-password: changeme
to delete

2023-04-20 08:39 UTC, oussamasic commented on cas/cas-server/src/main/config/cas-server-application-dev.yml
> +#vitamui.authn.x509.defaultDomain: 'domain.com'
to delete

2023-04-20 08:39 UTC, oussamasic commented on cas/cas-server/src/main/config/cas-server-application-dev.yml
> +cas.authn.oauth.access-token.crypto.signing.key: j8AZtUo6i4BI2n3bu2Elr9d3aIOL35vec0AjUBubP6rgj5arKWB9lRcWq9bjxGIwoAbFv-1MRmiScXlIIX0BGg
est-ce que c'est normal de partager ces clés (meme si cela ne concerne que la partie dev) ?

2023-04-20 08:39 UTC, oussamasic commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/config/WebConfig.java
> +/**
copyright to update

2023-04-20 08:39 UTC, oussamasic commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/util/CustomCasBanner.java
> +/**
idem

2023-04-20 08:39 UTC, oussamasic commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/web/CustomCorsProcessor.java
> +package fr.gouv.vitamui.cas.web;
copyright qui manque

2023-04-20 08:39 UTC, oussamasic commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/web/CustomOidcCasClientRedirectActionBuilder.java
> +package fr.gouv.vitamui.cas.web;
idem : il manque le text du copyright

2023-04-20 08:39 UTC, oussamasic commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/webflow/CustomCasDelegatingWebflowEventResolver.java
> +package fr.gouv.vitamui.cas.webflow;
idem : il manque le text du copyright

2023-04-20 08:39 UTC, oussamasic commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/webflow/actions/I18NSendPasswordResetInstructionsAction.java
> +        //
to delete

2023-04-20 08:39 UTC, oussamasic commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/webflow/resolver/CustomCasDelegatingWebflowEventResolver.java
> +package fr.gouv.vitamui.cas.webflow.resolver;
copyright

2023-04-20 08:39 UTC, oussamasic commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/webflow/resolver/CustomCasDelegatingWebflowEventResolver.java
> +        //
les commentaires à supprimer

2023-04-20 08:39 UTC, oussamasic commented on cas/cas-server/src/main/java/org/apereo/cas/config/CasFiltersConfiguration.java
> +package org.apereo.cas.config;
copyright

2023-04-20 08:39 UTC, oussamasic commented on cas/cas-server/src/main/java/org/apereo/cas/configuration/model/support/sms/SmsModeProperties.java
> +package org.apereo.cas.configuration.model.support.sms;
copyright

2023-04-20 08:39 UTC, oussamasic commented on cas/cas-server/src/main/java/org/apereo/cas/mfa/simple/web/flow/CasSimpleMultifactorSendTokenAction.java
> +package org.apereo.cas.mfa.simple.web.flow;
copyright

2023-04-20 08:39 UTC, oussamasic commented on cas/cas-server/src/main/java/org/apereo/cas/oidc/web/controllers/token/CustomOidcRevocationEndpointController.java
> +package org.apereo.cas.oidc.web.controllers.token;
copyright

2023-04-20 08:39 UTC, oussamasic commented on cas/cas-server/src/main/java/org/apereo/cas/ticket/accesstoken/OAuth20DefaultAccessTokenFactory.java
> +package org.apereo.cas.ticket.accesstoken;
idem

2023-04-20 08:39 UTC, oussamasic commented on cas/cas-server/src/main/java/org/apereo/cas/ticket/accesstoken/OAuth20DefaultAccessTokenFactory.java
> +package org.apereo.cas.ticket.accesstoken;
idem

2023-04-20 08:39 UTC, oussamasic commented on cas/cas-server/src/main/java/org/apereo/cas/support/sms/SmsModeSmsSender.java
> +package org.apereo.cas.support.sms;
idem

2023-04-20 08:39 UTC, oussamasic commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/AlertAnalyticsDto.java
> +package fr.gouv.vitamui.commons.api.domain;
idem

2023-04-20 08:39 UTC, oussamasic commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/AlertAnalyticsDto.java
> +public class AlertAnalyticsDto implements Serializable {
C'est quoi l'utilité de ce nouveau Dto.

2023-04-20 08:39 UTC, oussamasic commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/AlertAnalyticsDto.java
> +@Setter
```suggestion
@Data
```

2023-04-20 08:39 UTC, oussamasic commented on commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/BasePaginatingAndSortingRestClient.java
> + * with identifier.
pas besoin de faire le retour à la ligne

2023-04-20 08:39 UTC, oussamasic commented on commons/commons-utils/src/main/java/fr/gouv/vitamui/commons/utils/SecurePathUtils.java
> +package fr.gouv.vitamui.commons.utils;
copyright

2023-04-20 08:39 UTC, oussamasic commented on commons/commons-utils/src/main/java/fr/gouv/vitamui/commons/utils/SecurePathUtils.java
> +        //return FilenameUtils.concat(trustedBasePath, trustedFilename);
to delete

2023-04-20 08:39 UTC, oussamasic commented on commons/commons-utils/src/main/java/fr/gouv/vitamui/commons/utils/SecureZipUtils.java
> +/**
mauvais texte du copyright

2023-04-20 08:39 UTC, oussamasic commented on commons/commons-utils/src/test/java/fr/gouv/vitamui/commons/utils/SecureZipUtilsTest.java
> +package fr.gouv.vitamui.commons.utils;
idem

2023-04-20 08:39 UTC, oussamasic commented on deployment/roles/vitamui/files/customer-init.yml
> +
après cette modification, il faut prévoir un script mongo, pour mettre à jour les profils de l'app contrat d'entée au niveau de la BD en ajoutant ces 3 rôles.

2023-04-20 08:39 UTC, oussamasic commented on deployment/roles/vitamui/files/customer-init.yml
> +        - ROLE_GET_EXTERNAL_PARAMS
après cette modification, il faut prévoir un script mongo, pour mettre à jour les profils de l'app contrat d'accès au niveau de la BD en ajoutant ces 2 rôles

2023-04-20 08:39 UTC, oussamasic commented on deployment/scripts/mongod/1.0.0/04_cas_services_ref.js.j2
> +	"_class": "org.apereo.cas.services.CasRegisteredService",
un nouveau script d'update qu'il faut créer.
Lors d'une migration d'une version vers une autre version ce script ne sera pas rejoué vu qu'il est versionné

2023-04-20 08:39 UTC, oussamasic commented on deployment/scripts/mongod/1.0.0/101_iam_system_demo.js
> +db.tenants.update({"identifier": NumberInt({{ vitamui_platform_informations.proof_tenant }})},{"$set" : {"itemIngestContractIdentifier" : "IC-000005"}});
un nouveau script d'update qu'il faut créer.
Lors d'une migration d'une version vers une autre version ce script ne sera pas rejoué vu qu'il est versionné

2023-04-20 08:39 UTC, oussamasic commented on deployment/scripts/mongod/1.0.0/213_cas_services_ref.js.j2
> +   "_class": "org.apereo.cas.services.CasRegisteredService",
idem

2023-04-20 08:39 UTC, oussamasic commented on deployment/scripts/mongod/1.0.0/218_cas_services_archive_search_ref.js.j2
> +   "_class": "org.apereo.cas.services.CasRegisteredService",
idem

2023-04-20 08:39 UTC, oussamasic commented on deployment/scripts/mongod/1.0.0/209_cas_services_ref.js.j2
> +	"_class": "org.apereo.cas.services.CasRegisteredService",
idem

2023-04-20 08:39 UTC, oussamasic commented on deployment/scripts/mongod/2.0.0/01_remove_executed_scripts_from_changelog_versioning_ref.js
> +db.changelog.deleteMany({ checksum: { $in: scriptsChecksums } });
pourquoi cette suppression ? c'est quoi le bug ou la régression exactement ?

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/authentication/authentication-interceptor.ts
> +/*
mauvais texte du copyright

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/authentication/authentication.module.ts
> +    // tslint:disable-next-line: whitespace semicolon
il faut pas  désactiver les règles ts-lint

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/authentication/authentication.module.ts
> +    // tslint:disable-next-line: whitespace semicolon
il faut pas  désactiver les règles ts-lint

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/components/user-alerts/user-alerts-card/user-alerts-card.component.ts
> +import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
copyright

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/components/user-alerts/user-alerts-card/user-alerts-card.module.ts
> +import { CommonModule } from '@angular/common';
idem

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/components/user-alerts/user-alerts.service.ts
> +import { Injectable } from '@angular/core';
idem

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/components/vitamui-snack-bar/vitamui-snack-bar.interface.ts
> +/*
mauvais texte copyright

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend-common/src/assets/shared-i18n/fr.json
> +    "MASS_UPDATE_CHECK.FATAL": "Erreur technique lors de la Vérification des droits et des paramètres",
ces clés traduits ne sont pas utilisés coté VitamUI

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend-common/src/assets/shared-i18n/en.json
> +    "STP_COMPUTE_INHERITED_RULES.OK": "Compute applicable business rules calculation process successful",
ces clés traduites ne sont pas utilisés coté VitamUI

2023-04-20 08:39 UTC, oussamasic commented on api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/rest/ArchivesSearchExternalController.java
> -        throws InvalidParseOperationException, PreconditionFailedException {
à ne pas supprimer l'exception levée

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/app.component.spec.ts
> +// tslint:disable-next-line:component-selector
il faut pas désactiver la règle en question

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-informations-tab/archive-unit-rules-informations-tab.component.spec.ts
> +  // tslint:disable-next-line:directive-selector
il faut pas désactiver la règle en question

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/collect/package.json
> +  "version": "6.0-SNAPSHOT",
c'est version 7.0 : 
`7.0-SNAPSHOT`

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/package.json
> +  "version": "6.0-SNAPSHOT",
c'est version 7.0 : 
`7.0-SNAPSHOT`

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/models/utils.ts
> +  // tslint:disable-next-line:ban-types
à ne pas désactiver

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/demo/package.json
> +  "version": "6.0-SNAPSHOT",
c'est version 7.0 : 
`7.0-SNAPSHOT`

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/identity/package.json
> +  "version": "6.0-SNAPSHOT",
c'est version 7.0 : 
`7.0-SNAPSHOT`

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/package.json
> +  "version": "6.0-SNAPSHOT",
c'est version 7.0 : 
`7.0-SNAPSHOT`

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/pastis/package.json
> +  "version": "6.0-SNAPSHOT",
c'est version 7.0 : 
`7.0-SNAPSHOT`

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/portal/package.json
> +  "version": "6.0-SNAPSHOT",
c'est version 7.0 : 
`7.0-SNAPSHOT`

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/portal/src/assets/config-dev.json
> +  "PORTAL_URL": "https://dev.vitamui.com:4200",
il manque l'URL de Pastis, identity, collect

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/portal/src/assets/config-dev.json
> +  "PORTAL_MESSAGE": "Profitez d'un portail unique pour rechercher dans les archives de vos coffres, pour déposer des éléments en toute sécurité et pour imprimer des étiquettes en quelques clics.",
```suggestion
  "PORTAL_MESSAGE": "Pour gérer vos archives, profitez d'un portail d'applications proposé par le Programme Vitam et ses contributeurs",
```

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/identity/src/assets/config-dev.json
> +  "PORTAL_MESSAGE": "Profitez d'un portail unique pour rechercher dans les archives de vos coffres, pour déposer des éléments en toute sécurité et pour imprimer des étiquettes en quelques clics.",
```suggestion
  "PORTAL_MESSAGE": "Pour gérer vos archives, profitez d'un portail d'applications proposé par le Programme Vitam et ses contributeurs",
```

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/identity/src/assets/config-dev.json
> +  "ARCHIVES_SEARCH_URL": null,
c'est  https://dev.vitamui.com:4209/archive-search au lieu de null

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/identity/src/assets/config-dev.json
> +  "REFERENTIAL_URL": "https://dev.vitamui.com:4202",
il manque l'URL de collect, identity et pastis

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/referential/package.json
> +  "version": "6.0-SNAPSHOT",
```suggestion
  "version": "7.0-SNAPSHOT",
```

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/assets/config-dev.json
> +  "ARCHIVES_SEARCH_URL": null,
```suggestion
  "ARCHIVES_SEARCH_URL": "https://dev.vitamui.com:4209/archive-search",
```

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/assets/config-dev.json
> +  "PORTAL_MESSAGE": "Profitez d'un portail unique pour rechercher dans les archives de vos coffres, pour déposer des éléments en toute sécurité et pour imprimer des étiquettes en quelques clics.",
```suggestion
  "PORTAL_MESSAGE": "Pour gérer vos archives, profitez d'un portail d'applications proposé par le Programme Vitam et ses contributeurs.",
```

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/assets/config-dev.json
> +  "PORTAL_TITLE": "Portail des applications de l'archivage",
```suggestion
  "PORTAL_TITLE": "Portail des applications Vitam",
```

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/identity/src/assets/config-dev.json
> +  "PORTAL_TITLE": "Portail des applications de l'archivage",
```suggestion
  "PORTAL_TITLE": "Portail des applications Vitam",
```

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/portal/src/assets/config-dev.json
> +  "PORTAL_TITLE": "Portail des applications de l'archivage",
```suggestion
  "PORTAL_TITLE": "Portail des applications Vitam",
```

2023-04-20 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/vitamui-library/src/lib/models/access-contract.ts
> +import {AccessContract as IAccessContract} from 'ui-frontend-common';
fichier à supprimer, il faut utiliser AccessContract qu'on a dans ui-frontend-common

2023-04-20 08:39 UTC, oussamasic commented on api/api-gateway/pom.xml
> +        <version>6.0-SNAPSHOT</version>
```suggestion
        <version>7.0-SNAPSHOT</version>
```

2023-04-20 08:39 UTC, oussamasic commented on api/api-gateway/src/main/resources/application.yml
> +  client-certificate-header-name: x-ssl-cert
pour la partie spring.cloud.gateway est géré comment en production ?

2023-04-24 10:43 UTC, bbenaissa requested changes

2023-04-24 10:43 UTC, bbenaissa commented on api/api-archive-search/archive-search-external/pom.xml
> +        <dependency>
Est ce qu'on a besoin d'ajouter cette dépendence?

2023-04-24 10:43 UTC, bbenaissa commented on api/api-gateway/pom.xml
> +        <version>6.0-SNAPSHOT</version>
@oussamasic  ça sera mis à jour après le rebase

2023-04-24 10:43 UTC, bbenaissa commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/SecurityController.java
> +package fr.gouv.vitamui.iam.external.server.rest;
+1

2023-04-24 10:43 UTC, bbenaissa commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/TenantExternalController.java
> -        SanityChecker.checkSecureParameter(id);
Est ce qu'il y a une raison pour ça?

2023-04-24 10:43 UTC, bbenaissa commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/UserExternalController.java
> -        SanityChecker.checkSecureParameter(id);
+1

2023-04-24 10:43 UTC, bbenaissa commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/UserInfoExternalController.java
> +    @GetMapping(CommonConstants.PATH_LOGBOOK)
Est ce normal de changer ce endpoint?

2023-04-24 10:43 UTC, bbenaissa commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/service/InitCustomerService.java
> +        for (final Profile p : filteredProfiles) {
chaque application dispose d'un seul profile par défaut, par contre, on peut avoir des applications avec plusieurs profils, d'ailleurs on l'utilise dans notre coté

2023-04-24 10:43 UTC, bbenaissa commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/service/UserInternalService.java
>                  case "lastTenantIdentifier":
mettre la chaine en enum ou en à minima en const

2023-04-24 10:43 UTC, bbenaissa commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/service/UserInternalService.java
> +        Set<String> analyticsPatchAllowedFields = Set.of(APPLICATION_ID, "lastTenantIdentifier", "alerts", USER_ID_ATTRIBUTE);
on peut sortir ça hors la méthode

2023-04-24 10:43 UTC, bbenaissa commented on api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/RequestHeaderX509CertificateExtractor.java
> +            final CertificateFactory certificateFactory = CertificateFactory.getInstance("X.509");
je crois qu'il y a déjà une constante pour "X.509"

2023-04-24 10:43 UTC, bbenaissa commented on api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/ExternalAuthentificationService.java
>          if (userToken == null) {
est ce le check null est suffisant ou il faudra tester la chaine vide?

2023-04-24 10:43 UTC, bbenaissa commented on api/api-referential/referential-external/pom.xml
> +        <dependency>
pourquoi cette librairie?

2023-04-24 10:43 UTC, bbenaissa commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OperationExternalController.java
> +    public ObjectNode extractInfoFromTimestamp(final @RequestBody String timestamp) {
Est ce le bon endroit pour cet endpoint ? il y un role?

2023-04-24 10:43 UTC, bbenaissa commented on api/api-referential/referential-internal/src/main/config/access-external-client.conf
> +serverHost: dev.vitamui-dev.fr
ces fichiers on les commitent pas sinon, on change le host par celui de Vitam, puisque ça induit à l'erreur

2023-04-24 10:43 UTC, bbenaissa commented on api/api-referential/referential-internal/src/main/config/collect-client.conf
> +serverHost: dev.vitamui-dev.fr
Idem, ce fichier a changé de nom, il s'appelle collect-external-client.conf

2023-04-24 10:43 UTC, bbenaissa commented on api/api-referential/referential-internal/src/main/config/ingest-external-client.conf
> +serverHost: dev.vitamui-dev.fr
idem

2023-04-24 10:43 UTC, bbenaissa commented on cas/cas-server/pom.xml
> +            <version>2.11.0</version>
On peut mettre la version en common

2023-04-24 10:43 UTC, bbenaissa commented on cas/cas-server/pom.xml
> +            <version>1.6.5</version>
idem

2023-04-24 10:43 UTC, bbenaissa commented on cas/cas-server/pom.xml
> +            <version>1.1.1</version>
Idem

2023-04-24 10:43 UTC, bbenaissa commented on cas/cas-server/pom.xml
> +            <version>1.15</version>
Idem

2023-04-24 10:43 UTC, bbenaissa commented on cas/cas-server/pom.xml
> +            <version>5.11.2</version>
il y a plein ..

2023-04-24 10:43 UTC, bbenaissa commented on cas/cas-server/src/main/config/cas-server-application-dev.yml
> +cas.authn.oauth.access-token.crypto.signing.key: j8AZtUo6i4BI2n3bu2Elr9d3aIOL35vec0AjUBubP6rgj5arKWB9lRcWq9bjxGIwoAbFv-1MRmiScXlIIX0BGg
ça concerne que la partie dev, pour moi c'est pas un pb

2023-04-24 10:43 UTC, bbenaissa commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/web/CustomOidcCasClientRedirectActionBuilder.java
> +        val redirectionUrl = casServerLoginUrl + (casServerLoginUrl.contains("?") ? "&" : "?")
Un StringBuilder? pour une question de perf

2023-04-24 10:43 UTC, bbenaissa commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/webflow/actions/CheckMfaTokenAction.java
> +        } catch (InvalidTicketException e) {}
Est ce normal de ne pas traiter le catch?

2023-04-24 10:43 UTC, bbenaissa commented on cas/cas-server/src/main/java/org/apereo/cas/config/CasFiltersConfiguration.java
> +/**
ça pourrait être un TODO pour ne pas oublier ça

2023-04-24 10:43 UTC, bbenaissa commented on cas/cas-server/src/main/java/org/apereo/cas/mfa/simple/web/flow/CasSimpleMultifactorSendTokenAction.java
> + * To be removed when upgrading to CAS version >= 6.6.3.
Idem

2023-04-24 10:43 UTC, bbenaissa commented on cas/cas-server/src/main/java/org/apereo/cas/oidc/web/controllers/token/CustomOidcRevocationEndpointController.java
> +            Custom : Don't check clientId to allow revoke token to all services (SSO)
To check

2023-04-24 10:43 UTC, bbenaissa commented on cas/cas-server/src/main/resources/templates/login/casLoginView.html
> +        var providedUsername = /*[[${providedUsername}]]*/ "";
On peut supprimer ça

2023-04-24 10:43 UTC, bbenaissa commented on commons/commons-security/src/main/java/fr/gouv/vitamui/common/security/SanityChecker.java
> +                throw new ParseOperationException("Error with the parameter ");
A ajouter le param dans le message

2023-04-24 10:43 UTC, bbenaissa commented on commons/commons-security/src/main/java/fr/gouv/vitamui/common/security/SanityChecker.java
>              throw new PreconditionFailedException("the parameter is not valid");
Idem

2023-04-24 10:43 UTC, bbenaissa commented on deployment/environments/group_vars/all/vitamui_vars.yml
> +  doc_tenant: 9
ça peut poser problème dans notre cas et chez d'autres clients, puisqu'on commence la generation des tenants à partir de 2

2023-04-24 10:43 UTC, bbenaissa commented on deployment/roles/init_app_bdd/templates/referential/01_referential.js.j2
>      { "_id" :  NumberInt(4) },
ça pose problème lors de la montée de version, puisque les scripts ont été déja joués

2023-04-24 10:43 UTC, bbenaissa commented on deployment/roles/init_archive_search_app_bdd/templates/archive-search/01_archive-search.js.j2
>          "$set" : {
ça pose problème lors de la montée de version, puisque les scripts ont été déja joués

2023-04-24 10:43 UTC, bbenaissa commented on deployment/roles/init_ingest_app_bdd/templates/ingest/01_ingest.js.j2
> +            "_class": "org.apereo.cas.services.CasRegisteredService",
ça pose problème lors de la montée de version, puisque les scripts ont été déja joués

2023-04-24 10:43 UTC, bbenaissa commented on deployment/roles/vitamui/files/customer-init.yml
> +
+1 (pour les montée de version aussi)

2023-04-24 10:43 UTC, bbenaissa commented on deployment/scripts/mongod/1.0.0/04_cas_services_ref.js.j2
> +	"_class": "org.apereo.cas.services.CasRegisteredService",
+1

2023-04-24 10:43 UTC, bbenaissa commented on deployment/scripts/mongod/1.0.0/101_iam_system_demo.js
> +db.tenants.update({"identifier": NumberInt({{ vitamui_platform_informations.proof_tenant }})},{"$set" : {"itemIngestContractIdentifier" : "IC-000005"}});
+1

2023-04-24 10:43 UTC, bbenaissa commented on deployment/scripts/mongod/1.0.0/209_cas_services_ref.js.j2
> +	"_class": "org.apereo.cas.services.CasRegisteredService",
+1

2023-04-24 10:43 UTC, bbenaissa commented on deployment/scripts/mongod/1.0.0/218_cas_services_archive_search_ref.js.j2
> +   "_class": "org.apereo.cas.services.CasRegisteredService",
Question de montée de version, le script ne sera pas executé, ça fonctionne en cas d'une install from scratch

> Le fichier a été revert puisqu''il y avait un autre fichier qui contenait déjà un update la dessus

2023-04-24 10:43 UTC, bbenaissa commented on deployment/scripts/mongod/2.0.0/015_RABB_fix_missing_collection_ref.js
> +db = db.getSiblingDB('iam')
est ce qu'on a besoin de ce script?

2023-04-24 10:43 UTC, bbenaissa commented on deployment/scripts/mongod/6.rc.0/035_TRV_remove_tenant_2_and_profiles_and_profiles_groups_linkend_to_ref.js
> +print("START 035_TRV_remove_tenant_2_and_profiles_and_profiles_groups_linkend_to_ref.js");
ça risque de poser problème si un client dispose du tenant 2 comme un vrai tenant, on supprime ces données

2023-04-24 10:43 UTC, bbenaissa commented on tools/swagger/Dockerfile.template
> +LABEL maintainer="Xelians DevOps"
Changer le maintainer :)

2023-04-24 10:43 UTC, bbenaissa commented on ui/ui-frontend-common/icomoon-selection.json
> -{"IcoMoonType":"selection","icons":[{"icon":{"paths":["M154.834 184.594v811.967c0 14.966 12.473 27.438 27.44 27.438h643.588c14.966 0 27.438-12.472 27.438-27.438v-811.967h72.34c14.966 0 27.438-12.473
Est ce que la génération des nouvelles icones a été faite en suivant la procédure pour éviter la suppression des anciennes icones?

2023-04-28 08:08 UTC, pyXelians commented on api/api-archive-search/archive-search-external/pom.xml
> +        <dependency>
Oui elle est nécessaire

2023-04-28 08:19 UTC, pyXelians commented on api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/rest/ArchivesSearchExternalController.java
> -        throws InvalidParseOperationException, PreconditionFailedException {
je ne vois pas l'intérêt de les garder ? elles finiront par être catcher par le controllerAdvice

2023-04-28 08:19 UTC, pyXelians commented on api/api-gateway/pom.xml
> +        <version>6.0-SNAPSHOT</version>
lors du rebase ça sera pris en compte du coup

2023-04-28 08:26 UTC, pyXelians commented on api/api-gateway/src/main/java/fr/gouv/vitamui/gateway/ApiGatewayServerApplication.java
> +package fr.gouv.vitamui.gateway;
Done

2023-04-28 08:27 UTC, pyXelians commented on api/api-gateway/src/main/java/fr/gouv/vitamui/gateway/config/NettyServerCustomizer.java
> +package fr.gouv.vitamui.gateway.config;
Done

2023-04-28 08:27 UTC, pyXelians commented on api/api-gateway/src/main/java/fr/gouv/vitamui/gateway/filters/X509CertificateFilter.java
> +package fr.gouv.vitamui.gateway.filters;
Done

2023-04-28 08:55 UTC, pyXelians commented on api/api-gateway/src/main/java/fr/gouv/vitamui/gateway/filters/X509CertificateFilter.java
> +    private static final Logger logger = LoggerFactory.getLogger(X509CertificateFilter.class);
Done

2023-04-28 08:57 UTC, pyXelians commented on api/api-gateway/src/main/resources/application.yml
> +  client-certificate-header-name: x-ssl-cert
peux-tu préciser ta question ?

2023-04-28 08:59 UTC, pyXelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/domain/dto/ProviderPatchType.java
> +/**
Done

2023-04-28 09:00 UTC, pyXelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/ApplicationExternalController.java
> +        //RestUtils.checkCriteria(criteria);
Done

2023-04-28 09:02 UTC, pyXelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/ApplicationExternalController.java
> +    @GetMapping("/filtered")
La cible c'est de n'avoir qu'une seul couche, la pertinence d'avoir une constante qui n'est utilisé qu'a un seul endroit me semble moins vrai aujourd'hui

2023-04-28 09:05 UTC, pyXelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/ApplicationExternalController.java
> +        LOGGER.debug("isApplicationExternalIdentifierEnabled");
Done

2023-04-28 09:06 UTC, pyXelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/CustomerExternalController.java
> -        SanityChecker.checkSecureParameter(id);
La signature de la méthode a été changé pour être rétrocompatible entre la couche ui et external.

2023-04-28 09:07 UTC, pyXelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/ExternalParamProfileExternalController.java
> +        //RestUtils.checkCriteria(criteria);
Done

2023-04-28 09:08 UTC, pyXelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/ExternalParamProfileExternalController.java
> +        LOGGER.debug("get logbook for external parameter profile with id :{}", id);
Done

2023-04-28 09:09 UTC, pyXelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/GroupExternalController.java
> +        LOGGER.debug("get logbook for group with id :{}", id);
Done

2023-04-28 09:10 UTC, pyXelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/IdentityProviderExternalController.java
> +        final Resource resource = identityProviderCrudService.getMetadataProviderByProviderId(id, ProviderEmbeddedOptions.IDPMETADATA, IamUtils.buildOptionalEmbedded(ProviderEmbeddedOptions.IDPMETADA
Done

2023-04-28 09:11 UTC, pyXelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/IdentityProviderExternalController.java
> +        final Resource resource = identityProviderCrudService.getMetadataProviderByProviderId(id, ProviderEmbeddedOptions.SPMETADATA, IamUtils.buildOptionalEmbedded(ProviderEmbeddedOptions.SPMETADATA
Done

2023-04-28 09:13 UTC, pyXelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/IdentityProviderExternalController.java
> +
çela nécessitait des modifications côté front -> ça pourra être fait dans un deuxième temps

2023-04-28 09:14 UTC, pyXelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/IdentityProviderExternalController.java
> +    // FXME MDI - Ignore with Failed to execute goal 'convertSwagger2markup': Type of parameter 'keystore' must not be blank
Done

2023-04-28 09:19 UTC, pyXelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/IdentityProviderExternalController.java
> +    @ApiIgnore // FXME MDI - Ignore with Failed to execute goal 'convertSwagger2markup': Type of parameter 'provider' must not be blank
Il faut bien comprendre que nous avons déplacé du code existant provenant du module UI pour le déporter dans la couche external. Nous n'avons pas pu faire le nettoyage de tout l'existant c'est pourquoi certaines choses comme ici sont un reliquat des modules UI. Le refactoring de l'existant n'était pas inclus dans ce chantier.  De plus la fusion des couches external et internal pourrait impliqué une suppression du code et donc de l'énergie dépensé pour rien.

2023-04-28 09:20 UTC, pyXelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/OwnerExternalController.java
> +        LOGGER.debug("get logbook for owner with id :{}", id);
Done

2023-04-28 09:21 UTC, pyXelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/SecurityController.java
> +package fr.gouv.vitamui.iam.external.server.rest;
Done

2023-04-28 09:23 UTC, pyXelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/TenantExternalController.java
> -        SanityChecker.checkSecureParameter(id);
Done

2023-04-28 09:24 UTC, pyXelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/UserExternalController.java
> -        SanityChecker.checkSecureParameter(id);
Done

2023-04-28 09:25 UTC, pyXelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/UserInfoExternalController.java
> +    @GetMapping(CommonConstants.PATH_LOGBOOK)
A priori oui -> ça a été fait dans le but de rendre retrocompatibles les couches entre elles

2023-04-28 09:26 UTC, pyXelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/service/ApplicationService.java
> +/**
Done

2023-04-28 09:29 UTC, pyXelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/service/UserExternalService.java
> +                throw new ForbiddenException(String.format("Unable to patch analytics for user with id: %s", partialDto.get(USER_ID_ATTRIBUTE)));
Done

2023-04-28 09:33 UTC, pyXelians commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/service/InitCustomerService.java
> +        for (final Profile p : filteredProfiles) {
Pour le même tenant ?

2023-04-28 09:35 UTC, pyXelians commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/converter/UserConverter.java
> +                alertAnalyticsDto.setId(alert.getId());
Done

2023-04-28 09:36 UTC, pyXelians commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/domain/AlertAnalytics.java
> +package fr.gouv.vitamui.iam.internal.server.user.domain;
Done

2023-04-28 09:39 UTC, pyXelians commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/service/UserInternalService.java
>                  case "lastTenantIdentifier":
Ce code est déjà présent ->  ce que nous avons ajouter c'est les alerts sur le même modèle que lastTenantIdentifier

2023-04-28 09:40 UTC, pyXelians commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/service/UserInternalService.java
> +        Set<String> analyticsPatchAllowedFields = Set.of(APPLICATION_ID, "lastTenantIdentifier", "alerts", USER_ID_ATTRIBUTE);
pourquoi tu veux le sortir ?

2023-04-28 09:41 UTC, pyXelians commented on api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/rest/CustomerCrudControllerTest.java
> +
Done

2023-04-28 09:42 UTC, pyXelians commented on api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/RequestAttributeX509CertificateExtractor.java
> +package fr.gouv.vitamui.iam.security.filter;
Done

2023-04-28 09:43 UTC, pyXelians commented on api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/RequestAttributeX509CertificateExtractor.java
> +
Done

2023-04-28 09:44 UTC, pyXelians commented on api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/RequestHeaderX509CertificateExtractor.java
> +package fr.gouv.vitamui.iam.security.filter;
Done

2023-04-28 09:44 UTC, pyXelians commented on api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/RequestHeaderX509CertificateExtractor.java
> +    private static final Log LOGGER = LogFactory.getLog(RequestHeaderX509CertificateExtractor.class);
Done

2023-04-28 09:47 UTC, pyXelians commented on api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/RequestHeaderX509CertificateExtractor.java
> +            final CertificateFactory certificateFactory = CertificateFactory.getInstance("X.509");
laquelle ?

2023-04-28 09:47 UTC, pyXelians commented on api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/TokenExtractor.java
> +package fr.gouv.vitamui.iam.security.filter;
Done

2023-04-28 09:48 UTC, pyXelians commented on api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/X509CertificateExtractor.java
> +package fr.gouv.vitamui.iam.security.filter;
Done

2023-04-28 09:49 UTC, oussamasic commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/service/InitCustomerService.java
> +        for (final Profile p : filteredProfiles) {
@pyXelians : oui pour chaque tenant on a cette option, actuellement on a des applications avec plusieurs profils.

2023-04-28 09:50 UTC, pyXelians commented on api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/ExternalAuthentificationService.java
>          if (userToken == null) {
Done

2023-04-28 09:50 UTC, pyXelians commented on api/api-iam/iam-security/src/test/java/fr/gouv/vitamui/iam/security/filter/TokenExtractorTest.java
> +package fr.gouv.vitamui.iam.security.filter;
Done

2023-04-28 09:51 UTC, pyXelians commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamAgencyService.java
> +        fr.gouv.vitamui.commons.vitam.api.dto.LogbookOperationsResponseDto lastImportOperation = VitamRestUtils.responseMapping(lastImportOperationResponse.toJsonNode(), LogbookOperationsResponseDto.
Done

2023-04-28 09:59 UTC, pyXelians commented on deployment/environments/group_vars/all/vitamui_vars.yml
> +  doc_tenant: 9
Dans ce cas libre à vous de la surcharger ?

2023-04-28 10:00 UTC, pyXelians commented on dev-deployment/environments/hosts
> +hosts_vitamui_api_gateway
on ne maintient pas cette partie, vous pouvez le mettre à jours de votre côté

2023-04-28 10:01 UTC, pyXelians commented on ui/ui-frontend/projects/identity/src/assets/config-dev.json
> +  "PORTAL_TITLE": "Portail des applications de l'archivage",
Done

2023-04-28 11:44 UTC, pyXelians commented
> Remarques générales :
> 
> * à vérifier si le code style de VitamUI est bien appliqué ou non.
> * Texte du copyright à mettre à jour.
> * Texte du copyright à ajouter dans les nouveaux fichiers .ts
> * La suppression des modules ui-identity, ui-portal et ui-referential est prévu pour quand ?

La suppression des modules Ui sera faites uniquement lorsque vous serez prêt -> donc lorsque vous aurez mis à jours votre partie déploiement etc

2023-05-26 13:44 UTC, GiooDev commented on deployment/environments/group_vars/all/vitamui_vars.yml
> +  doc_tenant: 9
Cette variable est utilisée pour quels composants applicatifs ? Car je ne la trouve nulle part dans aucun de nos composants.

Si cette variable ne fait pas parti des composants de VitamUI, nous n'avons pas à l'ajouter dans la liste des paramètres de configuration généraux.
De votre côté, vous pouvez lui ajouter une valeur par default (au template jinja par exemple) et la surcharger si nécessaire lors de l'exécution.

2023-05-26 14:23 UTC, GiooDev requested changes

2023-05-26 14:23 UTC, GiooDev commented on deployment/roles/init_ingest_app_bdd/templates/ingest/01_ingest.js.j2
> +            "_class": "org.apereo.cas.services.CasRegisteredService",
Ça semble pouvoir être exécuté à chaque déploiement. Car l'action demandée est un `db.services.update` donc cela devrait bien mettre à jour le document avec le $set fourni.

Par contre, le rôle suivant `deployment/roles/init_ingest_app_bdd/` ne semble appelé par aucun playbook.

-> Donc soit le rôle est inutile et donc il faut le supprimer, soit il nous manque les modifications adéquates au niveau des playbooks pour l'exécution de ce rôle ?

Donc au delà de la mise à jour à tester, comment est chargé ce service ?

:warning: Et Attention car l'update prend en filtre le même `{ "_id" : NumberInt(4) },` que les précédents ? Est-ce normal ? Car à chaque passage d'un rôle à l'autre on va modifier le même services.

2023-05-26 14:23 UTC, GiooDev commented on deployment/roles/init_archive_search_app_bdd/templates/archive-search/01_archive-search.js.j2
>          "$set" : {
Ça semble pouvoir être exécuté à chaque déploiement. Car l'action demandée est un `db.services.update` donc cela devrait bien mettre à jour le document avec le $set fourni.

Par contre, le rôle suivant `deployment/roles/init_archive_search_app_bdd/` ne semble appelé par aucun playbook.

-> Donc soit le rôle est inutile et donc il faut le supprimer, soit il nous manque les modifications adéquates au niveau des playbooks pour l'exécution de ce rôle ?

Donc au delà de la mise à jour à tester, comment est chargé ce service ?

:warning: Et Attention car l'update prend en filtre le même `{ "_id" : NumberInt(4) },` que les précédents ? Est-ce normal ? Car à chaque passage d'un rôle à l'autre on va modifier le même services.

2023-05-26 14:23 UTC, GiooDev commented on deployment/roles/init_app_bdd/templates/referential/01_referential.js.j2
>      { "_id" :  NumberInt(4) },
Ça semble pouvoir être exécuté à chaque déploiement. Car l'action demandée est un `db.services.update` donc cela devrait bien mettre à jour le document avec le $set fourni.

Par contre, le rôle `deployment/roles/init_app_bdd/` qui est censé exécuter ces templates semble commenté de tous les playbooks qui l'appellent. Donc ça semble ainsi jamais exécuté ni mis à jour.

```
$ grep -r init_app_bdd deployment/
deployment/ansible-vitamui/mongo_update_scripts.yml:    - init_app_bdd

$ grep -r mongo_update_scripts deployment/
deployment/ansible-vitamui/vitamui_pastis.yml:#- import_playbook: mongo_update_scripts.yml
deployment/ansible-vitamui/vitamui_referential.yml:#- import_playbook: mongo_update_scripts.yml
deployment/ansible-vitamui/vitamui_collect.yml:#- import_playbook: mongo_update_scripts.yml
deployment/ansible-vitamui/vitamui_archive_search.yml:#- import_playbook: mongo_update_scripts.yml
deployment/ansible-vitamui/vitamui_ingest.yml:#- import_playbook: mongo_update_scripts.yml
```

-> Donc soit le rôle est inutile et donc il faut le supprimer, soit il nous manque les modifications adéquates au niveau des playbooks pour l'exécution de ce rôle ?

Donc au delà de la mise à jour à tester, comment est chargé ce service ?

:warning: Et Attention car l'update prend en filtre le même `{ "_id" : NumberInt(4) },` que les précédents ? Est-ce normal ? Car à chaque passage d'un rôle à l'autre on va modifier le même services.

2023-05-26 14:23 UTC, GiooDev commented on deployment/environments/group_vars/all/vitamui_vars.yml
> +  doc_tenant: 9
Ok la modification provient du script mongo : `deployment/scripts/mongod/1.0.0/101_iam_system_demo.js`
https://github.com/ProgrammeVitam/vitam-ui/pull/1309/files#diff-4de6bd60e59c0d4aa8d145134d0823590dadd9a955123ab19617cc5a7e03a619R84

L'exécution des scripts _demo semblent exclus via la variable du fichier `deployment/environments/group_vars/all/mongodb_vars.yml`
```
    excluded_scripts: # List of regexs allowing to determine which scripts will be excluded.
        - ".*_dev.js.*"
        - ".*_demo.js.*"
```

Hors, dans la configuration dev du fichier `tools/docker/mongo/mongo_vars_dev.yml`, cette liste est vide donc les scripts seront exécutés.
Cette variable correspond donc à une variable de dev et non de prod à fournir dans ce fichier de config.

2023-05-26 14:23 UTC, GiooDev commented on deployment/roles/init_archive_search_app_bdd/templates/archive-search/01_archive-search.js.j2
>          "$set" : {
Ok j'ai trouvé, le service est initialement chargé avec le script mongo: `deployment/scripts/mongod/1.0.0/218_cas_services_archive_search_ref.js.j2` qui contient l'id: `"_id" : NumberInt(6),`

2023-05-26 14:23 UTC, GiooDev commented on deployment/roles/init_app_bdd/templates/referential/01_referential.js.j2
>      { "_id" :  NumberInt(4) },
Ok j'ai trouvé, le script est initialement chargé avec le script mongo: `deployment/scripts/mongod/1.0.0/209_cas_services_ref.js.j2` qui contient l'id: `"_id" : NumberInt(4),`

2023-05-26 14:23 UTC, GiooDev commented on deployment/roles/init_ingest_app_bdd/templates/ingest/01_ingest.js.j2
> +            "_class": "org.apereo.cas.services.CasRegisteredService",
Ok j'ai trouvé, le script est initialement chargé avec le script mongo: `deployment/scripts/mongod/1.0.0/213_cas_services_ref.js.j2` qui contient l'id: `"_id" : NumberInt(5),`

2023-06-08 14:48 UTC, pyXelians commented on deployment/environments/group_vars/all/vitamui_vars.yml
> +  doc_tenant: 9
Vu avec Benaissa, nous avons finalement supprimer la variable pour éviter tout problème de votre côté

2023-06-08 15:06 UTC, pyXelians commented on ui/ui-frontend-common/icomoon-selection.json
> -{"IcoMoonType":"selection","icons":[{"icon":{"paths":["M154.834 184.594v811.967c0 14.966 12.473 27.438 27.44 27.438h643.588c14.966 0 27.438-12.472 27.438-27.438v-811.967h72.34c14.966 0 27.438-12.473
Je ne suis pas sûre de ça dans le doute, je revert le fichier -> vous pourrez ensuite ajouter les icônes au besoin

2023-06-08 15:34 UTC, pyXelians commented on deployment/scripts/mongod/6.rc.0/035_TRV_remove_tenant_2_and_profiles_and_profiles_groups_linkend_to_ref.js
> +print("START 035_TRV_remove_tenant_2_and_profiles_and_profiles_groups_linkend_to_ref.js");
En effet je supprime ce fichier -> il était nécessaire de notre côté mais pas du votre

2023-06-08 15:42 UTC, pyXelians commented on deployment/scripts/mongod/2.0.0/015_RABB_fix_missing_collection_ref.js
> +db = db.getSiblingDB('iam')
Nous avions créé ce script car il arrivait parfois que la collection ne se créée pas correctement. Je peux le supprimer si tu veux ?

2023-06-08 15:47 UTC, bbenaissa requested changes

2023-06-08 15:47 UTC, bbenaissa commented on api/api-iam/iam-internal/pom.xml
> +            <version>${spring.version}</version>
Mettre la vension dans le fichier parent

2023-06-08 15:47 UTC, bbenaissa commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OntologyExternalController.java
> +        LOGGER.debug("get logbook for ontology with id :{}", id);
+1

2023-06-08 15:47 UTC, bbenaissa commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OntologyExternalController.java
> +
+1

2023-06-08 15:47 UTC, bbenaissa commented on deployment/environments/group_vars/all/vitamui_vars.yml
> +  doc_tenant: 9
après échange, cette configuration pourrai être supprimée

2023-06-08 15:47 UTC, bbenaissa commented on deployment/scripts/mongod/2.0.0/015_RABB_fix_missing_collection_ref.js
> +db = db.getSiblingDB('iam')
Idem que le message d'avant

2023-06-08 15:47 UTC, bbenaissa commented on deployment/scripts/mongod/6.rc.0/035_TRV_remove_tenant_2_and_profiles_and_profiles_groups_linkend_to_ref.js
> +print("START 035_TRV_remove_tenant_2_and_profiles_and_profiles_groups_linkend_to_ref.js");
après échange, cette modification pourrai être rollbackée

2023-06-08 15:47 UTC, bbenaissa commented on ui/ui-frontend-common/icomoon-selection.json
> -{"IcoMoonType":"selection","icons":[{"icon":{"paths":["M154.834 184.594v811.967c0 14.966 12.473 27.438 27.44 27.438h643.588c14.966 0 27.438-12.472 27.438-27.438v-811.967h72.34c14.966 0 27.438-12.473
après échange, à checker

2023-09-23 16:28 UTC, bbenaissa commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/service/InitCustomerService.java
> +        // Cannot have 2 profiles on the same application name for the same tenant
Attention: à ajouter dans le customer init, un commentaire pour trier les profils, pour avoir celui qui a plus de droits en premier, sinon,on aura pour le groupe admin des profils restreints

2023-11-07 16:02 UTC, bbenaissa approved these changes

2023-11-15 12:13 UTC, Regzox approved these changes

2023-11-15 12:52 UTC, merged