[VAS] 11330 : change erreor message
ProgrammeVitam/vitam-ui pull request #1319
Opened 2023-04-24 18:37 UTC by oussamasic

2023-04-24 19:31 UTC, TDevillechabrolle commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx One – Scan Summary & Details** – [80714232\-6e98\-43a7\-a930\-b41f4f5b3d5b](https://eu.ast.checkmarx.net/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/scans?id=80714232-6e98-43a7-a930-b41f4f5b3d5b&branch=feature%2Fvas_item_11330_update_error_message)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[Reflected_XSS_All_Clients](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/80714232-6e98-43a7-a930-b41f4f5b3d5b/sast/description/79/8481125285487743346)|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService\.java: [118](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas_item_11330_update_error_message//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService.java#L118)|[Attack Vector](https://eu.ast.checkmarx.net/results/80714232-6e98-43a7-a930-b41f4f5b3d5b/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=R%2BP5eOmZ%2FVQfi6771PDRcc%2FaoL0%3D&redirect=true)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[Reflected_XSS_All_Clients](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/80714232-6e98-43a7-a930-b41f4f5b3d5b/sast/description/79/8481125285487743346)|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService\.java: [118](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas_item_11330_update_error_message//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService.java#L118)|[Attack Vector](https://eu.ast.checkmarx.net/results/80714232-6e98-43a7-a930-b41f4f5b3d5b/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=p40hv7fxdkALrPRuJhxA6%2Bd0Mb4%3D&redirect=true)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[Reflected_XSS_All_Clients](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/80714232-6e98-43a7-a930-b41f4f5b3d5b/sast/description/79/8481125285487743346)|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService\.java: [118](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas_item_11330_update_error_message//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService.java#L118)|[Attack Vector](https://eu.ast.checkmarx.net/results/80714232-6e98-43a7-a930-b41f4f5b3d5b/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=84dCb8zBd4KVCoujm%2BjYBeqXKpo%3D&redirect=true)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[Reflected_XSS_All_Clients](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/80714232-6e98-43a7-a930-b41f4f5b3d5b/sast/description/79/8481125285487743346)|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService\.java: [118](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas_item_11330_update_error_message//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService.java#L118)|[Attack Vector](https://eu.ast.checkmarx.net/results/80714232-6e98-43a7-a930-b41f4f5b3d5b/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=X%2B3dOi4X7Bx9LgDbk8%2B5uupd3oY%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Cleartext_Submission_of_Sensitive_Information](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/80714232-6e98-43a7-a930-b41f4f5b3d5b/sast/description/319/5872693300309307288)|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService\.java: [110](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas_item_11330_update_error_message//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService.java#L110)|[Attack Vector](https://eu.ast.checkmarx.net/results/80714232-6e98-43a7-a930-b41f4f5b3d5b/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=Ky2n0k3HQmoWVyHaECThgy2rn9o%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Cleartext_Submission_of_Sensitive_Information](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/80714232-6e98-43a7-a930-b41f4f5b3d5b/sast/description/319/5872693300309307288)|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService\.java: [118](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas_item_11330_update_error_message//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService.java#L118)|[Attack Vector](https://eu.ast.checkmarx.net/results/80714232-6e98-43a7-a930-b41f4f5b3d5b/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=Jp72lhkoJMvgOWvcNYPOkbEbpEk%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Cleartext_Submission_of_Sensitive_Information](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/80714232-6e98-43a7-a930-b41f4f5b3d5b/sast/description/319/5872693300309307288)|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService\.java: [110](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas_item_11330_update_error_message//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService.java#L110)|[Attack Vector](https://eu.ast.checkmarx.net/results/80714232-6e98-43a7-a930-b41f4f5b3d5b/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=Y1Uuvjv4kMHtAyOVHRUZ7%2BMA8Vw%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Cleartext_Submission_of_Sensitive_Information](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/80714232-6e98-43a7-a930-b41f4f5b3d5b/sast/description/319/5872693300309307288)|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService\.java: [118](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas_item_11330_update_error_message//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService.java#L118)|[Attack Vector](https://eu.ast.checkmarx.net/results/80714232-6e98-43a7-a930-b41f4f5b3d5b/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=3vU7P71RFA6dC6sXVwSF%2FkNCJxA%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Cleartext_Submission_of_Sensitive_Information](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/80714232-6e98-43a7-a930-b41f4f5b3d5b/sast/description/319/5872693300309307288)|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService\.java: [110](https://github.com/ProgrammeVitam/vitam-ui/blob/feature/vas_item_11330_update_error_message//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService.java#L110)|[Attack Vector](https://eu.ast.checkmarx.net/results/80714232-6e98-43a7-a930-b41f4f5b3d5b/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=6XEq%2Baw%2BIL7ZDT8H%2Bc4YW8tJ3pw%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Cleartext_Submission_of_Sensitive_Information](https://eu.ast.checkmarx.net/results/78091106-f13 [...]

2023-04-25 09:56 UTC, GiooDev requested changes

2023-04-25 09:56 UTC, GiooDev commented on ui/ui-frontend-common/src/assets/shared-i18n/fr.json
> +      "HTTP_STATUS_CODE_BAD_REQUEST": "Requête invalide : L'objet ajouté est invalide et non propre merci de le corriger",
il manque une virgule après le propre,

Et que signifie la notion de propre pour l'objet ?

2023-04-25 10:04 UTC, oussamasic commented on ui/ui-frontend-common/src/assets/shared-i18n/fr.json
> +      "HTTP_STATUS_CODE_BAD_REQUEST": "Requête invalide : L'objet ajouté est invalide et non propre merci de le corriger",
corrigé,
non propre c'est à dire qu'il contient des caractères invalides (comme un code html, xml....)

2023-04-25 12:03 UTC, laedanrex approved these changes

2023-04-26 08:06 UTC, bbenaissa approved these changes

2023-04-26 08:55 UTC, merged