Story 11472: Fix profile creation for management contract app.
ProgrammeVitam/vitam-ui pull request #1336
Opened 2023-05-16 08:07 UTC by GiooDev

## Description

During upgrade, the management contract profile is not properly created.

## Type de changement:

* Ansiblerie
* Correction

## Contributeur

* VAS (Vitam Accessible en Service)

2023-05-16 09:08 UTC, TDevillechabrolle commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx One – Scan Summary & Details** – [46c7c267\-027c\-4622\-acc2\-0fc829c5a427](https://eu.ast.checkmarx.net/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/scans?id=46c7c267-027c-4622-acc2-0fc829c5a427&branch=story_11472_fix_profile_mngt_contract)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2016-10707](https://devhub.checkmarx.com/cve-details/CVE-2016-10707)|Maven\-org\.webjars:jquery\-1\.12\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/reports/46c7c267-027c-4622-acc2-0fc829c5a427/vulnerabilities/CVE-2016-10707%3AMaven-org.webjars%3Ajquery-1.12.0/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2021-43466](https://devhub.checkmarx.com/cve-details/CVE-2021-43466)|Maven\-org\.thymeleaf:thymeleaf\-spring5\-3\.0\.12\.RELEASE|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/reports/46c7c267-027c-4622-acc2-0fc829c5a427/vulnerabilities/CVE-2021-43466%3AMaven-org.thymeleaf%3Athymeleaf-spring5-3.0.12.RELEASE/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2007-2379](https://devhub.checkmarx.com/cve-details/CVE-2007-2379)|Maven\-org\.webjars:jquery\-1\.12\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/reports/46c7c267-027c-4622-acc2-0fc829c5a427/vulnerabilities/CVE-2007-2379%3AMaven-org.webjars%3Ajquery-1.12.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2015-9251](https://devhub.checkmarx.com/cve-details/CVE-2015-9251)|Maven\-org\.webjars:jquery\-1\.12\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/reports/46c7c267-027c-4622-acc2-0fc829c5a427/vulnerabilities/CVE-2015-9251%3AMaven-org.webjars%3Ajquery-1.12.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2019-11358](https://devhub.checkmarx.com/cve-details/CVE-2019-11358)|Maven\-org\.webjars:jquery\-1\.12\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/reports/46c7c267-027c-4622-acc2-0fc829c5a427/vulnerabilities/CVE-2019-11358%3AMaven-org.webjars%3Ajquery-1.12.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2020-11022](https://devhub.checkmarx.com/cve-details/CVE-2020-11022)|Maven\-org\.webjars:jquery\-1\.12\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/reports/46c7c267-027c-4622-acc2-0fc829c5a427/vulnerabilities/CVE-2020-11022%3AMaven-org.webjars%3Ajquery-1.12.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2020-11023](https://devhub.checkmarx.com/cve-details/CVE-2020-11023)|Maven\-org\.webjars:jquery\-1\.12\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/reports/46c7c267-027c-4622-acc2-0fc829c5a427/vulnerabilities/CVE-2020-11023%3AMaven-org.webjars%3Ajquery-1.12.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2021-41182](https://devhub.checkmarx.com/cve-details/CVE-2021-41182)|Maven\-org\.webjars:jquery\-ui\-1\.12\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/reports/46c7c267-027c-4622-acc2-0fc829c5a427/vulnerabilities/CVE-2021-41182%3AMaven-org.webjars%3Ajquery-ui-1.12.1/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2021-41183](https://devhub.checkmarx.com/cve-details/CVE-2021-41183)|Maven\-org\.webjars:jquery\-ui\-1\.12\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/reports/46c7c267-027c-4622-acc2-0fc829c5a427/vulnerabilities/CVE-2021-41183%3AMaven-org.webjars%3Ajquery-ui-1.12.1/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2021-41184](https://devhub.checkmarx.com/cve-details/CVE-2021-41184)|Maven\-org\.webjars:jquery\-ui\-1\.12\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/reports/46c7c267-027c-4622-acc2-0fc829c5a427/vulnerabilities/CVE-2021-41184%3AMaven-org.webjars%3Ajquery-ui-1.12.1/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Filtering_Sensitive_Logs](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/46c7c267-027c-4622-acc2-0fc829c5a427/sast/description/532/12553559161661395516)|/deployment/lib/mitogen\-0\.2\.9/mitogen/core\.py: [3300](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11472_fix_profile_mngt_contract//deployment/lib/mitogen-0.2.9/mitogen/core.py#L3300)|[Attack Vector](https://eu.ast.checkmarx.net/results/46c7c267-027c-4622-acc2-0fc829c5a427/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=vqMtwgcxzxowZMboxk%2BwjEpeX0I%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Filtering_Sensitive_Logs](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/46c7c267-027c-4622-acc2-0fc829c5a427/sast/description/532/12553559161661395516)|/deployment/lib/mitogen\-0\.2\.9/mitogen/core\.py: [3300](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11472_fix_profile_mngt_contract//deployment/lib/mitogen-0.2.9/mitogen/core.py#L3300)|[Attack Vector](https://eu.ast.checkmarx.net/results/46c7c267-027c-4622-acc2-0fc829c5a427/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=B66NhW1rmW%2Flt67Ae%2B0%2F8LHG7Hw%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Filtering_Sensitive_Logs](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/46c7c267-027c-4622-acc2-0fc829c5a427/sast/description/532/12553559161661395516)|/deployment/lib/mitogen\-0\.2\.9/mitogen/core\.py: [3286](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11472_fix_profile_mngt_contract//deployment/lib/mitogen-0.2.9/mitogen/core.py#L3286)|[Attack Vector](https://eu.ast.checkmarx.net/results/46c7c267-027c-4622-acc2-0fc829c5a427/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=evuHOHuTgeM9zsPxZCrCEjq0qmo%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Filtering_Sensitive_Logs](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/46c7c267-027c-4622-acc2-0fc829c5a427/sast/description/532/12553559161661395516)|/deployment/lib/mitogen\-0\.2\.9/mitogen/core\.py: [809](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11472_fix_profile_mngt_contract//deployment/lib/mitogen-0.2.9/mitogen/core.py#L809)|[Attack Vector](https://eu.ast.checkmarx.net/results/46c7c267-027c-4622-acc2-0fc829c5a427/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=H7VM%2Bmw9b26L4Ft2W1gmtMktkSc%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Filtering_Sensitive_Logs](https://eu.ast.checkmarx.net/ [...]

2023-05-16 13:51 UTC, laedanrex approved these changes

2023-05-19 09:29 UTC, bbenaissa commented
Attention, il y a un souci avec ce script:

- Ce script concerne la version V6, alors que develop est sur la version V7, il y a deux corrections à faire:
  - 1: créer un répertoire V7: et dedans on crée un script qui permet de mettre à jour les données existantes, puisque le script dans une installation V7 est censé être executé, et il ne le sera pas de nouveau, c'est pour ça, il faudra un script de mise à jour (un script de correction). Quand on est sur la même version, pas de souci, on peut se permettre de changer le script existant, mais sur des version differentes, ça fonctionne pas.
  - 2: pour le master 6.x: on peut créer une PR de bugfix en modifiant le même fichier.

2023-05-19 09:29 UTC, bbenaissa requested changes

2023-05-19 09:29 UTC, bbenaissa commented on deployment/scripts/mongod/v6.0/21_create_profile_MANAGEMENT_CONTRACT_APP.js.j2
> +        "_id" : "PROFIL_" + tenant.identifier + "-MANAGEMENT_CONTRACT_APP-ADMIN",
J'ai ajouté un commentaire globale pour ma remarque

2023-05-22 07:34 UTC, GiooDev commented on deployment/scripts/mongod/v6.0/21_create_profile_MANAGEMENT_CONTRACT_APP.js.j2
> +        "_id" : "PROFIL_" + tenant.identifier + "-MANAGEMENT_CONTRACT_APP-ADMIN",
C'est un profil ajouté en V6, donc la correction doit se faire dans le répertoire V6 pour que le cherry-pick soit pris en compte jusqu'à la branche de mise en oeuvre de ce profil.

Point à confirmer en fonction de la décision de relivraison: Pour la migration des données, 2 possibilités, soit oui il faut un nouveau script car pour les installations actuelles en 6.0 il ne sera pas réappliqué. Soit on considère que la 6.0 ne sera pas officiellement releasée (au vu des bugs identifiés) et auquel cas, on peut relivrer ce script puisqu'il ne sera pas censé être joué sur une production et il sera donc releasé correctement avec la 6.1.

2023-06-20 10:11 UTC, GiooDev commented on deployment/scripts/mongod/v6.0/21_create_profile_MANAGEMENT_CONTRACT_APP.js.j2
> +        "_id" : "PROFIL_" + tenant.identifier + "-MANAGEMENT_CONTRACT_APP-ADMIN",
Vu qu'on a prévu de relivrer la V6, ce script peut être ainsi corrigé en l'état pour relivraison officielle.

2023-06-20 10:12 UTC, GiooDev commented
À CP jusqu'à V6.

2023-06-20 12:05 UTC, bbenaissa approved these changes

2023-06-20 15:51 UTC, merged