Story 10410: update labels, css and layouts for external params app
ProgrammeVitam/vitam-ui pull request #1365
Opened 2023-06-07 16:33 UTC by mhameg

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2023-06-07 17:33 UTC, TDevillechabrolle commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx One – Scan Summary & Details** – [4c049e05\-3789\-452b\-bd7f\-898937cd80cc](https://eu.ast.checkmarx.net/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/scans?id=4c049e05-3789-452b-bd7f-898937cd80cc&branch=story_10410_fix_external_param_app_layouts)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2016-10735](https://devhub.checkmarx.com/cve-details/CVE-2016-10735)|Npm\-bootstrap\-3\.3\.6|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/reports/4c049e05-3789-452b-bd7f-898937cd80cc/vulnerabilities/CVE-2016-10735%3ANpm-bootstrap-3.3.6/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2018-14040](https://devhub.checkmarx.com/cve-details/CVE-2018-14040)|Npm\-bootstrap\-3\.3\.6|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/reports/4c049e05-3789-452b-bd7f-898937cd80cc/vulnerabilities/CVE-2018-14040%3ANpm-bootstrap-3.3.6/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2018-14042](https://devhub.checkmarx.com/cve-details/CVE-2018-14042)|Npm\-bootstrap\-3\.3\.6|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/reports/4c049e05-3789-452b-bd7f-898937cd80cc/vulnerabilities/CVE-2018-14042%3ANpm-bootstrap-3.3.6/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2018-20676](https://devhub.checkmarx.com/cve-details/CVE-2018-20676)|Npm\-bootstrap\-3\.3\.6|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/reports/4c049e05-3789-452b-bd7f-898937cd80cc/vulnerabilities/CVE-2018-20676%3ANpm-bootstrap-3.3.6/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2018-20677](https://devhub.checkmarx.com/cve-details/CVE-2018-20677)|Npm\-bootstrap\-3\.3\.6|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/reports/4c049e05-3789-452b-bd7f-898937cd80cc/vulnerabilities/CVE-2018-20677%3ANpm-bootstrap-3.3.6/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2019-8331](https://devhub.checkmarx.com/cve-details/CVE-2019-8331)|Npm\-bootstrap\-3\.3\.6|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/78091106-f137-4b7b-8b68-77ee0f4d3433/reports/4c049e05-3789-452b-bd7f-898937cd80cc/vulnerabilities/CVE-2019-8331%3ANpm-bootstrap-3.3.6/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Unchecked_Input_for_Loop_Condition](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/4c049e05-3789-452b-bd7f-898937cd80cc/sast/description/606/10402229133361412662)|/api/api\-referential/referential\-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/UnitInternalController\.java: [115](https://github.com/ProgrammeVitam/vitam-ui/blob/story_10410_fix_external_param_app_layouts//api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/UnitInternalController.java#L115)|[Attack Vector](https://eu.ast.checkmarx.net/results/4c049e05-3789-452b-bd7f-898937cd80cc/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=V7GIDLLf76k6qBVaOjw6KMcayRc%3D&redirect=true)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Unchecked_Input_for_Loop_Condition](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/4c049e05-3789-452b-bd7f-898937cd80cc/sast/description/606/10402229133361412662)|/api/api\-referential/referential\-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/UnitInternalController\.java: [103](https://github.com/ProgrammeVitam/vitam-ui/blob/story_10410_fix_external_param_app_layouts//api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/UnitInternalController.java#L103)|[Attack Vector](https://eu.ast.checkmarx.net/results/4c049e05-3789-452b-bd7f-898937cd80cc/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=avLC3F%2BEpXNV%2FkH%2FV%2BeQNrAk5HI%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/4c049e05-3789-452b-bd7f-898937cd80cc/sast/description/117/9884244256835554923)|/api/api\-referential/referential\-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/UnitInternalController\.java: [126](https://github.com/ProgrammeVitam/vitam-ui/blob/story_10410_fix_external_param_app_layouts//api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/UnitInternalController.java#L126)|[Attack Vector](https://eu.ast.checkmarx.net/results/4c049e05-3789-452b-bd7f-898937cd80cc/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=vQ58g5AW5QRwD%2FHXaVwK1eRjhzI%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/4c049e05-3789-452b-bd7f-898937cd80cc/sast/description/117/9884244256835554923)|/api/api\-referential/referential\-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/UnitInternalController\.java: [126](https://github.com/ProgrammeVitam/vitam-ui/blob/story_10410_fix_external_param_app_layouts//api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/UnitInternalController.java#L126)|[Attack Vector](https://eu.ast.checkmarx.net/results/4c049e05-3789-452b-bd7f-898937cd80cc/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=8%2F%2Fuy2CHPPVJWJr8zu%2FsIZAX%2Fs8%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/4c049e05-3789-452b-bd7f-898937cd80cc/sast/description/117/9884244256835554923)|/api/api\-referential/referential\-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/UnitInternalController\.java: [126](https://github.com/ProgrammeVitam/vitam-ui/blob/story_10410_fix_external_param_app_layouts//api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/UnitInternalController.java#L126)|[Attack Vector](https://eu.ast.checkmarx.net/results/4c049e05-3789-452b-bd7f-898937cd80cc/78091106-f137-4b7b-8b68-77ee0f4d3433/sast?result-id=gTDct1cmh7TESJvcFZ92l1b%2FHWQ%3D&redirect=true)
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/78091106-f137-4b7b-8b68-77ee0f4d3433/4c049e05-3789-452b-bd7f-898937cd80cc/sast/description/117/9884244256835554923)|/api/api\-referential/referential\-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/UnitInternalController\.java: [115](https://github.com/ProgrammeVitam/vitam-ui/blob/story_10410_fix_external_param_app_layouts//api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/UnitInternalController.java#L115)|[Attack Vector](https://eu.ast.che [...]

2023-06-19 19:33 UTC, bbenaissa requested changes

2023-06-19 19:33 UTC, bbenaissa commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalService.java
> +                //auditOptions.setQuery(null);
à supprimer si on n'a pas besoin

2023-06-19 19:33 UTC, bbenaissa commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalService.java
>              if ("AUDIT_FILE_CONSISTENCY".equals(auditOptions.getAuditActions())) {
On peut les convertir en enum

2023-06-19 19:33 UTC, bbenaissa commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/service/ExternalParametersService.java
> +    public Optional<Long> retrieveProfilThresholds() {
retrieveProfileThreshold

2023-06-19 19:33 UTC, bbenaissa commented on ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-create/external-param-profile-create.component.css
> +.header-title {
On n'a pas une classe CSS commune pour ce title?

2023-06-19 19:33 UTC, bbenaissa commented on ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-detail/thresholds-tab/thresholds-tab.component.css
> +.icon-information {
pareil pour le style

2023-06-22 14:21 UTC, mhameg commented on ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-detail/thresholds-tab/thresholds-tab.component.css
> +.icon-information {
j'ai repris de la css qui a été fait pour un autre wizard, 
il n'y a pas de style pré-définie sur le wizard dont je me suis inspiré

2023-06-22 14:21 UTC, mhameg commented on ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-create/external-param-profile-create.component.css
> +.header-title {
j'ai repris de la css qui a été fait pour un autre wizard,
il n'y a pas de style pré-définie sur le wizard dont je me suis inspiré

2023-06-22 15:40 UTC, mhameg commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalService.java
> +                //auditOptions.setQuery(null);
ok c'est fait

2023-07-05 10:19 UTC, laedanrex approved these changes

2023-07-05 12:28 UTC, laedanrex commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/service/ExternalParametersService.java
> +        if (myExternalParameter != null && !org.springframework.util.CollectionUtils.isEmpty(myExternalParameter.getParameters())) {
y a import org.apache.commons.collections4.CollectionUtils;   tu peux utiliser le isEmpty de cette collection (elle est bien plus complète que celle de spring)

au passage tu peux inverser les if et mettre des return pour éviter les cascade ?

2023-07-05 15:57 UTC, mhameg commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/service/ExternalParametersService.java
> +        if (myExternalParameter != null && !org.springframework.util.CollectionUtils.isEmpty(myExternalParameter.getParameters())) {
done

2023-07-06 12:19 UTC, Regzox approved these changes

2023-07-06 12:23 UTC, merged