Story-11459: Add java options for stopping services on OutOfMemoryError
ProgrammeVitam/vitam-ui pull request #1434
Opened 2023-08-02 10:00 UTC by bbenaissa

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2023-08-03 10:11 UTC, GiooDev requested changes

2023-08-03 10:11 UTC, GiooDev commented on deployment/roles/vitamui/templates/java_opts.j2
> +JAVA_OPTS="{{ vitamui_struct.jvm_opts.gc | default(gc_opts) }} {{ vitamui_struct.jvm_opts.memory | default(memory_opts) }} {{ vitamui_struct.jvm_opts.java | default(java_opts) }} -Djava.security.prop
Y'a une grosse typo ici...

2023-08-03 15:52 UTC, mascoun approved these changes

2023-08-03 15:56 UTC, GiooDev approved these changes

2023-08-10 14:10 UTC, laedanrex approved these changes

2023-09-07 15:22 UTC, merged