Vas 11586 contrat entree
ProgrammeVitam/vitam-ui pull request #1447
Opened 2023-08-29 14:40 UTC by laedanrex

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2023-08-29 15:42 UTC, TDevillechabrolle commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx One – Scan Summary & Details** – [059b8715\-4993\-4452\-b436\-d7db49fa3b6d](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=059b8715-4993-4452-b436-d7db49fa3b6d&branch=vas-11586-contrat-entree)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2022-26592](https://devhub.checkmarx.com/cve-details/CVE-2022-26592)|Npm\-node\-sass\-4\.14\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/059b8715-4993-4452-b436-d7db49fa3b6d/vulnerabilities/CVE-2022-26592%3ANpm-node-sass-4.14.1/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2023-41080](https://devhub.checkmarx.com/cve-details/CVE-2023-41080)|Maven\-org\.apache\.tomcat\.embed:tomcat\-embed\-core\-9\.0\.63|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/059b8715-4993-4452-b436-d7db49fa3b6d/vulnerabilities/CVE-2023-41080%3AMaven-org.apache.tomcat.embed%3Atomcat-embed-core-9.0.63/vulnerabilityDetails)

### Fixed Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Missing User Instruction|/Dockerfile: [10](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11586-contrat-entree//tools/docker/centos/Dockerfile#L10)|A user should be specified in the dockerfile, otherwise the image will run as root
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Missing User Instruction|/Dockerfile: [10](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11586-contrat-entree//tools/docker/vitamui-base/Dockerfile#L10)|A user should be specified in the dockerfile, otherwise the image will run as root
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Missing User Instruction|/Dockerfile: [11](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11586-contrat-entree//tools/docker/vitamui/Dockerfile#L11)|A user should be specified in the dockerfile, otherwise the image will run as root
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Missing User Instruction|/Dockerfile: [10](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11586-contrat-entree//tools/docker/vitamui-osbase/Dockerfile#L10)|A user should be specified in the dockerfile, otherwise the image will run as root
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|No New Privileges Not Set|/vitam\-recette\.yml: [17](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11586-contrat-entree//tools/docker/vitam/vitam-recette.yml#L17)|Ensuring the process does not gain any new privileges lessens the risk associated with many operations.
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|No New Privileges Not Set|/vitam\-recette\.yml: [54](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11586-contrat-entree//tools/docker/vitam/vitam-recette.yml#L54)|Ensuring the process does not gain any new privileges lessens the risk associated with many operations.
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|No New Privileges Not Set|/vitam\-dev\.yml: [19](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11586-contrat-entree//tools/docker/vitam/vitam-dev.yml#L19)|Ensuring the process does not gain any new privileges lessens the risk associated with many operations.
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|No New Privileges Not Set|/docker\-compose\.yml: [10](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11586-contrat-entree//tools/docker/vitamui-osbase/docker-compose.yml#L10)|Ensuring the process does not gain any new privileges lessens the risk associated with many operations.
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\.yml: [95](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11586-contrat-entree//ui/ui-identity/src/test/resources/application.yml#L95)|Query to find passwords and secrets in infrastructure code.
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [22](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11586-contrat-entree//ui/ui-collect/src/main/resources/application-dev.yml#L22)|Query to find passwords and secrets in infrastructure code.
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-integration\.yml: [66](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11586-contrat-entree//integration-tests/src/test/resources/application-integration.yml#L66)|Query to find passwords and secrets in infrastructure code.
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [19](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11586-contrat-entree//ui/ui-portal/src/main/resources/application-dev.yml#L19)|Query to find passwords and secrets in infrastructure code.
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\.yml: [28](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11586-contrat-entree//ui/ui-identity/src/test/resources/application.yml#L28)|Query to find passwords and secrets in infrastructure code.
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [90](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11586-contrat-entree//integration-tests/src/test/resources/application-dev.yml#L90)|Query to find passwords and secrets in infrastructure code.
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [73](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11586-contrat-entree//ui/ui-ingest/src/main/resources/application-dev.yml#L73)|Query to find passwords and secrets in infrastructure code.
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-recette\.yml: [52](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11586-contrat-entree//ui/ui-archive-search/src/main/resources/application-recette.yml#L52)|Query to find passwords and secrets in infrastructure code.
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\.yml: [76](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11586-contrat-entree//ui/ui-pastis/src/test/resources/application.yml#L76)|Query to find passwords and secrets in infrastructure code.
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [71](https://github.com/Programm [...]

2023-09-05 09:41 UTC, Regzox approved these changes

2023-09-07 15:07 UTC, bbenaissa requested changes

2023-09-07 15:07 UTC, bbenaissa commented on ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
> +                   matTooltip="Autoriser tout les formats d'objets binaires existant dans le référentiel des formats"></i>
traduction du tooltip

2023-09-07 15:07 UTC, bbenaissa commented on ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
> +                 matTooltip="Choisir les formats binaires que vous souhaitez autoriser"></i>
traduction du tooltip

2023-09-07 15:07 UTC, bbenaissa commented on ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
> +                   matTooltip="Autoriser les formats d'objets binaires non référencés dans le référentiel des formats"></i>
traduction du tooltip

2023-09-07 15:07 UTC, bbenaissa commented on ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
> +                  Autoriser les formats non identifiés
traduction du tooltip

2023-09-07 15:07 UTC, bbenaissa commented on ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
> +                   matTooltip="Usage(s) autorisé(s) dans le cas de l’ajout d’un objet binaire à un groupe d’objets techniques existant"></i>
traduction du tooltip

2023-09-07 15:07 UTC, bbenaissa commented on ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
> +                >Calcul des héritages de règles et d'indexation des échéances
traduction du tooltip

2023-09-07 15:08 UTC, bbenaissa commented
à traduire les textes tooltips

2023-09-07 15:09 UTC, bbenaissa approved these changes

2023-09-07 15:29 UTC, laedanrex commented on ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
> +                   matTooltip="Autoriser tout les formats d'objets binaires existant dans le référentiel des formats"></i>
vu on passera les trad plus tard

2023-09-07 15:50 UTC, merged