feat: add pastis standalone pipeline
ProgrammeVitam/vitam-ui pull request #1457
Opened 2023-09-06 10:19 UTC by Regzox

2023-09-06 13:29 UTC, vitam-devops commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx One – Scan Summary & Details** – [7c72ce34\-c8a4\-4989\-87c5\-2b25d8946c05](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=7c72ce34-c8a4-4989-87c5-2b25d8946c05&branch=feature%2Fpipeline_pastis_standalone)

### Fixed Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2015-4852](https://devhub.checkmarx.com/cve-details/CVE-2015-4852)|Maven\-commons\-collections:commons\-collections\-3\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/7c72ce34-c8a4-4989-87c5-2b25d8946c05/vulnerabilities/CVE-2015-4852%3AMaven-commons-collections%3Acommons-collections-3.2.1/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2015-7501](https://devhub.checkmarx.com/cve-details/CVE-2015-7501)|Maven\-commons\-collections:commons\-collections\-3\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/7c72ce34-c8a4-4989-87c5-2b25d8946c05/vulnerabilities/CVE-2015-7501%3AMaven-commons-collections%3Acommons-collections-3.2.1/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2016-1000027](https://devhub.checkmarx.com/cve-details/CVE-2016-1000027)|Maven\-org\.springframework:spring\-webmvc\-5\.3\.20|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/7c72ce34-c8a4-4989-87c5-2b25d8946c05/vulnerabilities/CVE-2016-1000027%3AMaven-org.springframework%3Aspring-webmvc-5.3.20/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2016-1000027](https://devhub.checkmarx.com/cve-details/CVE-2016-1000027)|Maven\-org\.springframework:spring\-webmvc\-5\.3\.13|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/7c72ce34-c8a4-4989-87c5-2b25d8946c05/vulnerabilities/CVE-2016-1000027%3AMaven-org.springframework%3Aspring-webmvc-5.3.13/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2016-1000027](https://devhub.checkmarx.com/cve-details/CVE-2016-1000027)|Maven\-org\.springframework:spring\-web\-5\.3\.20|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/7c72ce34-c8a4-4989-87c5-2b25d8946c05/vulnerabilities/CVE-2016-1000027%3AMaven-org.springframework%3Aspring-web-5.3.20/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2016-10707](https://devhub.checkmarx.com/cve-details/CVE-2016-10707)|Npm\-jquery\-2\.2\.4|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/7c72ce34-c8a4-4989-87c5-2b25d8946c05/vulnerabilities/CVE-2016-10707%3ANpm-jquery-2.2.4/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2016-10707](https://devhub.checkmarx.com/cve-details/CVE-2016-10707)|Maven\-org\.webjars:jquery\-1\.12\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/7c72ce34-c8a4-4989-87c5-2b25d8946c05/vulnerabilities/CVE-2016-10707%3AMaven-org.webjars%3Ajquery-1.12.0/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2017-12963](https://devhub.checkmarx.com/cve-details/CVE-2017-12963)|Npm\-node\-sass\-4\.14\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/7c72ce34-c8a4-4989-87c5-2b25d8946c05/vulnerabilities/CVE-2017-12963%3ANpm-node-sass-4.14.1/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2017-12964](https://devhub.checkmarx.com/cve-details/CVE-2017-12964)|Npm\-node\-sass\-4\.14\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/7c72ce34-c8a4-4989-87c5-2b25d8946c05/vulnerabilities/CVE-2017-12964%3ANpm-node-sass-4.14.1/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2017-18640](https://devhub.checkmarx.com/cve-details/CVE-2017-18640)|Maven\-org\.yaml:snakeyaml\-1\.19|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/7c72ce34-c8a4-4989-87c5-2b25d8946c05/vulnerabilities/CVE-2017-18640%3AMaven-org.yaml%3Asnakeyaml-1.19/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2017-7957](https://devhub.checkmarx.com/cve-details/CVE-2017-7957)|Maven\-com\.thoughtworks\.xstream:xstream\-1\.4\.9|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/7c72ce34-c8a4-4989-87c5-2b25d8946c05/vulnerabilities/CVE-2017-7957%3AMaven-com.thoughtworks.xstream%3Axstream-1.4.9/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2017-9096](https://devhub.checkmarx.com/cve-details/CVE-2017-9096)|Maven\-com\.lowagie:itext\-2\.1\.7|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/7c72ce34-c8a4-4989-87c5-2b25d8946c05/vulnerabilities/CVE-2017-9096%3AMaven-com.lowagie%3Aitext-2.1.7/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2018-11499](https://devhub.checkmarx.com/cve-details/CVE-2018-11499)|Npm\-node\-sass\-4\.14\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/7c72ce34-c8a4-4989-87c5-2b25d8946c05/vulnerabilities/CVE-2018-11499%3ANpm-node-sass-4.14.1/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2018-11694](https://devhub.checkmarx.com/cve-details/CVE-2018-11694)|Npm\-node\-sass\-4\.14\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/7c72ce34-c8a4-4989-87c5-2b25d8946c05/vulnerabilities/CVE-2018-11694%3ANpm-node-sass-4.14.1/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2018-11697](https://devhub.checkmarx.com/cve-details/CVE-2018-11697)|Npm\-node\-sass\-4\.14\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/7c72ce34-c8a4-4989-87c5-2b25d8946c05/vulnerabilities/CVE-2018-11697%3ANpm-node-sass-4.14.1/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2018-19827](https://devhub.checkmarx.com/cve-details/CVE-2018-19827)|Npm\-node\-sass\-4\.14\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/7c72ce34-c8a4-4989-87c5-2b25d8946c05/vulnerabilities/CVE-2018-19827%3ANpm-node-sass-4.14.1/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2019-10172](https://devhub.checkmarx.com/cve-details/CVE-2019-10172)|Maven\-org\.codeh [...]

2023-09-07 09:22 UTC, bbenaissa requested changes

2023-09-07 09:22 UTC, bbenaissa commented on Jenkinsfile
> +        stage('Build PASTIS standalone') {
Je préfère qu'on ajoute une step conditionnée au lie d'une step systématique

2023-09-11 09:13 UTC, bbenaissa approved these changes

2023-09-27 09:51 UTC, laedanrex approved these changes

2023-11-13 09:38 UTC, merged