Story 11789: Fix parameterized audit threshold
ProgrammeVitam/vitam-ui pull request #1495
Opened 2023-09-28 11:01 UTC by mhameg

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2023-09-28 11:58 UTC, vitam-devops commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx One – Scan Summary & Details** – [0845283f\-60da\-40bf\-b592\-d8a7560f3506](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=0845283f-60da-40bf-b592-d8a7560f3506&branch=story_11789_fix_parameterized_audit_threshold)

### Fixed Issues
Severity|Issue|Source File / Package
---|---|---
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Missing User Instruction|/Dockerfile: [10](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11789_fix_parameterized_audit_threshold//tools/docker/centos/Dockerfile#L10)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Missing User Instruction|/Dockerfile: [10](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11789_fix_parameterized_audit_threshold//tools/docker/vitamui-osbase/Dockerfile#L10)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Missing User Instruction|/Dockerfile: [10](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11789_fix_parameterized_audit_threshold//tools/docker/vitamui-base/Dockerfile#L10)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Missing User Instruction|/Dockerfile: [11](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11789_fix_parameterized_audit_threshold//tools/docker/vitamui/Dockerfile#L11)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|No New Privileges Not Set|/docker\-compose\.yml: [10](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11789_fix_parameterized_audit_threshold//tools/docker/vitamui-osbase/docker-compose.yml#L10)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|No New Privileges Not Set|/vitam\-recette\.yml: [54](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11789_fix_parameterized_audit_threshold//tools/docker/vitam/vitam-recette.yml#L54)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|No New Privileges Not Set|/vitam\-recette\.yml: [17](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11789_fix_parameterized_audit_threshold//tools/docker/vitam/vitam-recette.yml#L17)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|No New Privileges Not Set|/vitam\-dev\.yml: [19](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11789_fix_parameterized_audit_threshold//tools/docker/vitam/vitam-dev.yml#L19)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [71](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11789_fix_parameterized_audit_threshold//ui/ui-collect/src/main/resources/application-dev.yml#L71)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [23](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11789_fix_parameterized_audit_threshold//ui/ui-ingest/src/main/resources/application-dev.yml#L23)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [82](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11789_fix_parameterized_audit_threshold//ui/ui-referential/src/main/resources/application-dev.yml#L82)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [68](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11789_fix_parameterized_audit_threshold//ui/ui-pastis/src/main/resources/application-dev.yml#L68)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\.yml: [74](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11789_fix_parameterized_audit_threshold//ui/ui-identity/src/test/resources/application.yml#L74)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [12](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11789_fix_parameterized_audit_threshold//integration-tests/src/test/resources/application-dev.yml#L12)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [77](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11789_fix_parameterized_audit_threshold//ui/ui-ingest/src/main/resources/application-dev.yml#L77)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [100](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11789_fix_parameterized_audit_threshold//ui/ui-identity/src/main/resources/application-dev.yml#L100)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [71](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11789_fix_parameterized_audit_threshold//integration-tests/src/test/resources/application-dev.yml#L71)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [119](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11789_fix_parameterized_audit_threshold//api/api-iam/iam-internal/src/main/resources/application-dev.yml#L119)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-integration\.yml: [66](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11789_fix_parameterized_audit_threshold//integration-tests/src/test/resources/application-integration.yml#L66)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [32](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11789_fix_parameterized_audit_threshold//api/api-collect/collect-external/src/main/resources/application-dev.yml#L32)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-recette\.yml: [96](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11789_fix_parameterized_audit_threshold//ui/ui-ingest/src/main/resources/application-recette.yml#L96)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [22](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11789_fix_parameterized_audit_threshold//ui/ui-archive-search/src/main/resources/application-dev.yml#L22)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [24](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11789_fix_parameterized_audit_threshold//ui/ui-referential/src/main/resources/application-dev.yml#L24)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676 [...]

2023-09-28 14:04 UTC, bbenaissa requested changes

2023-09-28 14:04 UTC, bbenaissa commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalService.java
> +                auditOptions.setQuery(multiQuery.getFinalSelect());
il manque le changement du type d'audit en dsl

2023-09-28 14:27 UTC, mhameg commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalService.java
> +                auditOptions.setQuery(multiQuery.getFinalSelect());
done

2023-09-28 14:42 UTC, mohatizaoui approved these changes

2023-09-28 14:42 UTC, mohatizaoui commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalService.java
> +                    if (("originatingagency").equals(auditOptions.getAuditType())) {
mettre cela dans une constante

2023-09-28 14:44 UTC, mohatizaoui commented
Si possible ajouter un test  qui vérifie la requete dsl envoyé (pas bloquant)

2023-09-28 15:20 UTC, Regzox approved these changes

2023-09-28 16:06 UTC, lgheribi requested changes

2023-09-28 16:06 UTC, lgheribi commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalService.java
> +                    }
```
            } else if ("dsl".equals(options.getAuditType())) {
                <Récupérer la query>
            } else {
                throw ...
            }
```

2023-09-29 10:59 UTC, mhameg commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalService.java
> +                    }
done

2023-09-29 10:59 UTC, mhameg commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalService.java
> +                    if (("originatingagency").equals(auditOptions.getAuditType())) {
done

2023-09-29 11:57 UTC, Regzox approved these changes

2023-09-29 11:57 UTC, Regzox commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalServiceTest.java
Elles servent à quoi les ressources de test ?

2023-09-29 12:06 UTC, mhameg commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalServiceTest.java
initalement c'etait pour y mettre des requetes dsl en json et les tester, j'ai oublié de les supprimer au dernier commit

2023-09-29 12:17 UTC, merged