[VAS] bug 11726: add role ROLE_GET_AUDITS
ProgrammeVitam/vitam-ui pull request #1505
Opened 2023-10-02 07:56 UTC by laedanrex

## Description

l'accès aux données de l'APP Audits est dépendant de la présence de l'APP Opérations de sécurisation

## Type de changement:

* Nouveau Code

## Tests:

manuel

## Contributeur

VAS (Vitam Accessible en Service)

2023-10-02 08:41 UTC, Regzox approved these changes

2023-10-02 08:59 UTC, vitam-devops commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx One – Scan Summary & Details** – [31026024\-42fa\-42ce\-ac78\-af65a51a7667](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=31026024-42fa-42ce-ac78-af65a51a7667&branch=vas-11726-add-role-get-audit)

### Fixed Issues
Severity|Issue|Source File / Package
---|---|---
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Missing User Instruction|/Dockerfile: [11](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//tools/docker/vitamui/Dockerfile#L11)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Missing User Instruction|/Dockerfile: [10](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//tools/docker/vitamui-osbase/Dockerfile#L10)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Missing User Instruction|/Dockerfile: [10](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//tools/docker/centos/Dockerfile#L10)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Missing User Instruction|/Dockerfile: [10](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//tools/docker/vitamui-base/Dockerfile#L10)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|No New Privileges Not Set|/vitam\-recette\.yml: [54](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//tools/docker/vitam/vitam-recette.yml#L54)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|No New Privileges Not Set|/vitam\-recette\.yml: [17](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//tools/docker/vitam/vitam-recette.yml#L17)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|No New Privileges Not Set|/vitam\-dev\.yml: [19](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//tools/docker/vitam/vitam-dev.yml#L19)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|No New Privileges Not Set|/docker\-compose\.yml: [10](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//tools/docker/vitamui-osbase/docker-compose.yml#L10)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\.yml: [77](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//ui/ui-pastis/src/test/resources/application.yml#L77)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [46](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//api/api-pastis/pastis-external/src/main/resources/application-dev.yml#L46)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [40](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//ui/ui-pastis/src/main/resources/application-dev.yml#L40)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [100](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//ui/ui-identity/src/main/resources/application-dev.yml#L100)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/cas\-server\-application\-recette\.yml: [178](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//cas/cas-server/src/main/config/cas-server-application-recette.yml#L178)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [66](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//ui/ui-referential/src/main/resources/application-dev.yml#L66)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\.yml: [81](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//ui/ui-portal/src/test/resources/application.yml#L81)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\.yml: [53](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//ui/ui-archive-search/src/test/resources/application.yml#L53)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\.yml: [42](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//ui/ui-pastis/src/test/resources/application.yml#L42)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/cas\-server\-application\-dev\.yml: [45](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//cas/cas-server/src/main/config/cas-server-application-dev.yml#L45)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [101](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//api/api-iam/iam-internal/src/main/resources/application-dev.yml#L101)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\.yml: [42](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//ui/ui-referential/src/test/resources/application.yml#L42)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-recette\.yml: [22](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//ui/ui-collect/src/main/resources/application-recette.yml#L22)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [115](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//api/api-iam/iam-internal/src/main/resources/application-dev.yml#L115)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [30](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//api/api-iam/iam-external/src/main/resources/application-dev.yml#L30)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-recette\.yml: [21](https://github.com/ProgrammeVitam/vitam-ui/blob/vas-11726-add-role-get-audit//ui/ui-ingest/src/main/resources/application-recette.yml#L21)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\.yml [...]

2023-10-02 10:08 UTC, bbenaissa commented
La solution est à ajouter le role GET_OPERATIONS dans le profil associé à l'app AUDIT

2023-10-02 10:08 UTC, bbenaissa requested changes

2023-10-02 10:08 UTC, bbenaissa commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OperationExternalController.java
> +    @Secured({ServicesData.ROLE_GET_AUDITS, ServicesData.ROLE_GET_OPERATIONS})
C'est pas bon, il faudra sécuriser un endpoint par un seul role

2023-10-03 12:42 UTC, bbenaissa approved these changes

2023-10-03 13:43 UTC, merged