Story 11821: fix audit dsl request projection attribute
ProgrammeVitam/vitam-ui pull request #1511
Opened 2023-10-06 13:55 UTC by mhameg

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2023-10-06 14:04 UTC, bbenaissa requested changes

2023-10-06 14:04 UTC, bbenaissa commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalServiceTest.java
> +    String jsonDslQuery ="{\n" +
c'est plus propre de mettre la query dans une ressource

2023-10-06 14:04 UTC, bbenaissa commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalService.java
> +                && (auditOptions.getQuery().findValue(DSL_QUERY_PROJECTION) == null)){
la condition (auditOptions.getQuery().findValue(DSL_QUERY_PROJECTION) == null) est tjrs true, puisque tu  l'as déjà supprimé juste avant

2023-10-06 14:04 UTC, bbenaissa commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalServiceTest.java
> +    final private String AUDIT_FILE_RECTIFICATION = "AUDIT_FILE_RECTIFICATION";
Tu peux enlever les constantes non utilisées

2023-10-06 14:23 UTC, mhameg commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalServiceTest.java
> +    final private String AUDIT_FILE_RECTIFICATION = "AUDIT_FILE_RECTIFICATION";
pris en compte

2023-10-06 14:23 UTC, mhameg commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalService.java
> +                && (auditOptions.getQuery().findValue(DSL_QUERY_PROJECTION) == null)){
merci, pas vu
pris en compte

2023-10-06 14:26 UTC, mhameg commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalServiceTest.java
> +    String jsonDslQuery ="{\n" +
pris en compte

2023-10-06 14:48 UTC, bbenaissa approved these changes

2023-10-06 14:52 UTC, vitam-devops commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx One – Scan Summary & Details** – [7a8e81ae\-f66a\-437f\-8182\-ac2a3b739d79](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=7a8e81ae-f66a-437f-8182-ac2a3b739d79&branch=story_11821_fix_audit_dsl_query_projection)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2021-23372](https://devhub.checkmarx.com/cve-details/CVE-2021-23372)|Npm\-mongo\-express\-1\.0\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/7a8e81ae-f66a-437f-8182-ac2a3b739d79/vulnerabilities/CVE-2021-23372%3ANpm-mongo-express-1.0.0/vulnerabilityDetails)

### Fixed Issues
Severity|Issue|Source File / Package
---|---|---
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Missing User Instruction|/Dockerfile: [10](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11821_fix_audit_dsl_query_projection//tools/docker/vitamui-base/Dockerfile#L10)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Missing User Instruction|/Dockerfile: [10](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11821_fix_audit_dsl_query_projection//tools/docker/centos/Dockerfile#L10)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Missing User Instruction|/Dockerfile: [11](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11821_fix_audit_dsl_query_projection//tools/docker/vitamui/Dockerfile#L11)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Missing User Instruction|/Dockerfile: [10](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11821_fix_audit_dsl_query_projection//tools/docker/vitamui-osbase/Dockerfile#L10)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|No New Privileges Not Set|/vitam\-recette\.yml: [17](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11821_fix_audit_dsl_query_projection//tools/docker/vitam/vitam-recette.yml#L17)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|No New Privileges Not Set|/vitam\-dev\.yml: [19](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11821_fix_audit_dsl_query_projection//tools/docker/vitam/vitam-dev.yml#L19)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|No New Privileges Not Set|/vitam\-recette\.yml: [54](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11821_fix_audit_dsl_query_projection//tools/docker/vitam/vitam-recette.yml#L54)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|No New Privileges Not Set|/docker\-compose\.yml: [10](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11821_fix_audit_dsl_query_projection//tools/docker/vitamui-osbase/docker-compose.yml#L10)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [32](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11821_fix_audit_dsl_query_projection//api/api-archive-search/archive-search-external/src/main/resources/application-dev.yml#L32)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [19](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11821_fix_audit_dsl_query_projection//ui/ui-portal/src/main/resources/application-dev.yml#L19)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\.yml: [28](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11821_fix_audit_dsl_query_projection//ui/ui-identity/src/test/resources/application.yml#L28)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [101](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11821_fix_audit_dsl_query_projection//api/api-iam/iam-internal/src/main/resources/application-dev.yml#L101)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/cas\-server\-application\-dev\.yml: [14](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11821_fix_audit_dsl_query_projection//cas/cas-server/src/main/config/cas-server-application-dev.yml#L14)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\.yml: [31](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11821_fix_audit_dsl_query_projection//ui/ui-archive-search/src/test/resources/application.yml#L31)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [91](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11821_fix_audit_dsl_query_projection//ui/ui-archive-search/src/main/resources/application-dev.yml#L91)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [56](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11821_fix_audit_dsl_query_projection//ui/ui-pastis/src/main/resources/application-dev.yml#L56)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [62](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11821_fix_audit_dsl_query_projection//ui/ui-referential/src/main/resources/application-dev.yml#L62)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\.yml: [81](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11821_fix_audit_dsl_query_projection//ui/ui-portal/src/test/resources/application.yml#L81)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [78](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11821_fix_audit_dsl_query_projection//ui/ui-referential/src/main/resources/application-dev.yml#L78)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [80](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11821_fix_audit_dsl_query_projection//ui/ui-portal/src/main/resources/application-dev.yml#L80)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-dev\.yml: [52](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11821_fix_audit_dsl_query_projection//ui/ui-pastis/src/main/resources/application-dev.yml#L52)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Password|/application\-recette\.yml: [22](https://github.com/ProgrammeVitam/vitam-ui/blob/story_11821_fix_audit_dsl_query_projection//ui/ui-ingest/src/main/resources/application-r [...]

2023-10-09 08:04 UTC, Regzox approved these changes

2023-10-09 08:24 UTC, merged