Fix/display metadata
ProgrammeVitam/vitam-ui pull request #1561
Opened 2023-12-01 09:42 UTC by Regzox

## Description

Fixes sur les MD

2023-12-01 09:43 UTC, bbenaissa approved these changes

2023-12-01 10:25 UTC, vitam-devops commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx One – Scan Summary & Details** – [822be1d1\-a130\-40f7\-a17f\-86f10e60c877](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=822be1d1-a130-40f7-a17f-86f10e60c877&branch=fix%2Fdisplay_metadata)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2023-6378](https://devhub.checkmarx.com/cve-details/CVE-2023-6378)|Maven\-ch\.qos\.logback:logback\-core\-1\.2\.9|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/822be1d1-a130-40f7-a17f-86f10e60c877/vulnerabilities/CVE-2023-6378%3AMaven-ch.qos.logback%3Alogback-core-1.2.9/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2023-6378](https://devhub.checkmarx.com/cve-details/CVE-2023-6378)|Maven\-ch\.qos\.logback:logback\-classic\-1\.2\.9|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/822be1d1-a130-40f7-a17f-86f10e60c877/vulnerabilities/CVE-2023-6378%3AMaven-ch.qos.logback%3Alogback-classic-1.2.9/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[Cx5b5cdd9c-b61e](https://devhub.checkmarx.com/cve-details/Cx5b5cdd9c-b61e)|Maven\-org\.owasp\.esapi:esapi\-2\.2\.3\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/822be1d1-a130-40f7-a17f-86f10e60c877/vulnerabilities/Cx5b5cdd9c-b61e%3AMaven-org.owasp.esapi%3Aesapi-2.2.3.1/vulnerabilityDetails)

2023-12-01 16:21 UTC, bbenaissa requested changes

2023-12-01 16:21 UTC, bbenaissa commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/ResultsDto.java
> +        System.out.println("Setting additional property - Key: " + key + ", Value: " + value);
System.out.println

2023-12-01 17:11 UTC, lgheribi approved these changes

2023-12-01 17:11 UTC, ghost commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/schema/SchemaModelToExtendedOntologyDtoConverter.java
> +            .setRootPaths(null)
unsued?

2023-12-01 17:11 UTC, ghost commented on ui/ui-frontend-common/src/app/modules/object-viewer/components/group/group.component.html
> +          <span class="object-name">{{ displayObject.displayRule.ui.label || displayObject.path | translate }}</span>
Pas de traduction

2023-12-01 17:11 UTC, ghost commented on ui/ui-frontend-common/src/app/modules/object-viewer/models/schema-element.model.ts
> +  readonly TenantIds?: string[];
Revoir ça plus tard

2023-12-01 17:11 UTC, ghost commented on ui/ui-frontend-common/src/app/modules/object-viewer/services/display-rule-helper.service.ts
> +    const p1 = path1 ? path1.replace(/\[\d+\]/gm, '') : path1;
commentaire "toto[0].tata[1] ==> toto.tata"

2023-12-01 17:11 UTC, ghost commented on ui/ui-frontend-common/src/app/modules/object-viewer/services/ontology-to-display-rule.service.ts
> +        Path: ontology.ApiPath || ontology.Path,
Path vs ApiPath

2023-12-01 17:11 UTC, ghost commented on ui/ui-frontend-common/src/app/modules/object-viewer/services/ontology-to-display-rule.service.ts
> +  public computeApiPaths(ontologies: SchemaElement[]): { ontology: SchemaElement; ApiPath: string }[] {
To delete?

2023-12-01 17:11 UTC, ghost commented on ui/ui-frontend-common/src/app/modules/object-viewer/services/ontology-strategy-display-object.service.ts
> +import { OntologyToDisplayRuleService } from './ontology-to-display-rule.service';
Schema?

2023-12-01 17:11 UTC, ghost commented on ui/ui-frontend-common/src/app/modules/object-viewer/services/ontology-strategy-display-object.service.ts
> +      const schemaElement2 = schemaTemplate.find((se) => se.Path.replace(/\[\d+\]/gm, '') === schemaElement1.Path.replace(/\[\d+\]/gm, ''));
Commentaire "toto[0].tata[1] -> toto.tata"

Plus tard : penser à utiliser un nommage différent pour indiquer un path de data json de type "toto[0].tata[1]" vs un path de schema type "toto.tata"

2023-12-01 17:11 UTC, ghost commented on ui/ui-frontend-common/src/app/modules/object-viewer/services/ontology-strategy-display-object.service.ts
> +    const isDescriptive = !ui.Path.startsWith('#');
Racourcis à revoir?

2023-12-01 17:11 UTC, lgheribi commented on ui/ui-frontend-common/src/app/modules/object-viewer/services/ontology-strategy-display-object.service.ts
> +    const shouldDisplay = (isDescriptive || belongsToTemplate) && isConsistent && (belongsToOntologies || isVirtual || belongsToTemplate);
Un petit commentaire pour expliquer tout ça :)

2023-12-01 20:54 UTC, Regzox commented on ui/ui-frontend-common/src/app/modules/object-viewer/services/ontology-strategy-display-object.service.ts
> +      const schemaElement2 = schemaTemplate.find((se) => se.Path.replace(/\[\d+\]/gm, '') === schemaElement1.Path.replace(/\[\d+\]/gm, ''));
j'ai mis dans une fonction dédiée

2023-12-04 08:38 UTC, Regzox commented on ui/ui-frontend-common/src/app/modules/object-viewer/services/display-rule-helper.service.ts
> +    const p1 = path1 ? path1.replace(/\[\d+\]/gm, '') : path1;
J'ai ajouté une fonction pour faire ce traitement à plusieurs endroits

2023-12-04 08:40 UTC, Regzox commented on ui/ui-frontend-common/src/app/modules/object-viewer/services/ontology-strategy-display-object.service.ts
> +    const isDescriptive = !ui.Path.startsWith('#');
J'ai split la methode en deux pour cacher les valeurs non consistantes et pour cacher les mauvaise catégories

2023-12-04 08:40 UTC, Regzox commented on ui/ui-frontend-common/src/app/modules/object-viewer/services/ontology-strategy-display-object.service.ts
> +    const shouldDisplay = (isDescriptive || belongsToTemplate) && isConsistent && (belongsToOntologies || isVirtual || belongsToTemplate);
J'ai split la methode en deux pour cacher les valeurs non consistantes et pour cacher les mauvaise catégories

2023-12-04 08:43 UTC, Regzox commented on ui/ui-frontend-common/src/app/modules/object-viewer/models/schema-element.model.ts
> +  readonly TenantIds?: string[];
A voir dans une phase de clean code, ne sachant pas avec certitude si j'aurais pas besoin d'un élément on peut laisser comme ça pour l'instant.

2023-12-04 09:42 UTC, bbenaissa approved these changes

2023-12-04 10:32 UTC, merged