Story 11876
ProgrammeVitam/vitam-ui pull request #1564
Opened 2023-12-04 09:37 UTC by marob

## Description

Paramétrer la version du SEDA et la sélection d'usages d'objets d'un export DIP et d'une demande de transfert

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2023-12-04 10:19 UTC, vitam-devops commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx One – Scan Summary & Details** – [9cacec92\-36a5\-4cbe\-93a9\-b2d85d679ac1](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=9cacec92-36a5-4cbe-93a9-b2d85d679ac1&branch=story_11876_parameter-SEDA-version-and-object-usage-selection-for-DIP-and-transfer)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2019-15599](https://devhub.checkmarx.com/cve-details/CVE-2019-15599)|Npm\-tree\-kill\-1\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9cacec92-36a5-4cbe-93a9-b2d85d679ac1/vulnerabilities/CVE-2019-15599%3ANpm-tree-kill-1.2.1/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-28502](https://devhub.checkmarx.com/cve-details/CVE-2020-28502)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9cacec92-36a5-4cbe-93a9-b2d85d679ac1/vulnerabilities/CVE-2020-28502%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-36048](https://devhub.checkmarx.com/cve-details/CVE-2020-36048)|Npm\-engine\.io\-3\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9cacec92-36a5-4cbe-93a9-b2d85d679ac1/vulnerabilities/CVE-2020-36048%3ANpm-engine.io-3.2.1/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-36049](https://devhub.checkmarx.com/cve-details/CVE-2020-36049)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9cacec92-36a5-4cbe-93a9-b2d85d679ac1/vulnerabilities/CVE-2020-36049%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-7660](https://devhub.checkmarx.com/cve-details/CVE-2020-7660)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9cacec92-36a5-4cbe-93a9-b2d85d679ac1/vulnerabilities/CVE-2020-7660%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-7788](https://devhub.checkmarx.com/cve-details/CVE-2020-7788)|Npm\-ini\-1\.3\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9cacec92-36a5-4cbe-93a9-b2d85d679ac1/vulnerabilities/CVE-2020-7788%3ANpm-ini-1.3.5/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2021-31597](https://devhub.checkmarx.com/cve-details/CVE-2021-31597)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9cacec92-36a5-4cbe-93a9-b2d85d679ac1/vulnerabilities/CVE-2021-31597%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2022-2421](https://devhub.checkmarx.com/cve-details/CVE-2022-2421)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9cacec92-36a5-4cbe-93a9-b2d85d679ac1/vulnerabilities/CVE-2022-2421%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2023-32695](https://devhub.checkmarx.com/cve-details/CVE-2023-32695)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9cacec92-36a5-4cbe-93a9-b2d85d679ac1/vulnerabilities/CVE-2023-32695%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2019-16769](https://devhub.checkmarx.com/cve-details/CVE-2019-16769)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9cacec92-36a5-4cbe-93a9-b2d85d679ac1/vulnerabilities/CVE-2019-16769%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-6\.10\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9cacec92-36a5-4cbe-93a9-b2d85d679ac1/vulnerabilities/CVE-2020-15366%3ANpm-ajv-6.10.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-5\.5\.2|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9cacec92-36a5-4cbe-93a9-b2d85d679ac1/vulnerabilities/CVE-2020-15366%3ANpm-ajv-5.5.2/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2020-28481](https://devhub.checkmarx.com/cve-details/CVE-2020-28481)|Npm\-socket\.io\-2\.1\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9cacec92-36a5-4cbe-93a9-b2d85d679ac1/vulnerabilities/CVE-2020-28481%3ANpm-socket.io-2.1.1/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2020-7693](https://devhub.checkmarx.com/cve-details/CVE-2020-7693)|Npm\-sockjs\-0\.3\.19|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9cacec92-36a5-4cbe-93a9-b2d85d679ac1/vulnerabilities/CVE-2020-7693%3ANpm-sockjs-0.3.19/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2021-23364](https://devhub.checkmarx.com/cve-details/CVE-2021-23364)|Npm\-browserslist\-4\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9cacec92-36a5-4cbe-93a9-b2d85d679ac1/vulnerabilities/CVE-2021-23364%3ANpm-browserslist-4.5.5/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2021-23495](https://devhub.checkmarx.com/cve-details/CVE-2021-23495)|Npm\-karma\-4\.1\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9cacec92-36a5-4cbe-93a9-b2d85d679ac1/vulnerabilities/CVE-2021-23495%3ANpm-karma-4.1.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2022-0437](https://devhub.checkmarx.com/cve-details/CVE-2022-0437)|Npm\-karma\-4\.1\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9cacec92-36a5-4cbe-93a9-b2d85d679ac1/vulnerabilities/CVE-2022-0437%3ANpm-karma-4.1.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed [...]

2023-12-07 15:48 UTC, GiooDev commented
Message de commit en anglais plz et un # pour l'id de la story :)

2023-12-08 13:12 UTC, Regzox approved these changes

2023-12-08 13:12 UTC, Regzox commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/dip-request-create/dip-request-create.component.ts
> +import {Component, Inject, OnDestroy, OnInit} from '@angular/core';
Les imports avec ou sans espaces dans les curly braces ?

2023-12-11 09:25 UTC, bbenaissa requested changes

2023-12-11 09:25 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/dip-request-create/dip-request-create.component.scss
> +.text-title {
Est ce qu'il n'y a pas de refacto du css possible?

2023-12-11 09:25 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/dip-request-create/dip-request-create.component.ts
> +                this.logger.error('Error message :', error);
Dans le cas d'erreur, on affiche la popup d'erreur?

2023-12-11 09:25 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/models/dip.interface.ts
> +type DIPSedaVersion = '2.2' | '2.3';
on a que ces deux versions? on n'a pas le 2.1.?

2023-12-11 09:54 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/dip-request-create/dip-request-create.component.ts
> +import {Component, Inject, OnDestroy, OnInit} from '@angular/core';
@Regzox Bonne question. Le linter ne semble pas s'en préoccuper (d'ailleurs, des erreurs de lint existent dans le code du projet... on ne run pas le linter dans Jenkins ? On ne bloque pas le merge ?).
Par ailleurs, il ne semble pas y avoir de prettier (on l'évoque vaguement dans un README, mais il ne semble pas être utilisé).
Enfin, je ne comprends pas combien d'espaces on doit utiliser pour l'indentation (mon IDE semble perdu également).

2023-12-11 09:55 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/dip-request-create/dip-request-create.component.scss
> +.text-title {
@bbenaissa Alors, dans l'idéal, tout ce CSS devrait être global à Vitam, mais ça n'a pas été mis en place. Du coup, à part faire un refactoring global de tout le code pour se baser sur un truc propre, je ne vois pas trop comment faire.

2023-12-11 09:57 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/dip-request-create/dip-request-create.component.ts
> +                this.logger.error('Error message :', error);
Je n'ai pas changé ce comportement et ce n'est pas décrit dans l'US.

2023-12-11 10:14 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/models/dip.interface.ts
> +type DIPSedaVersion = '2.2' | '2.3';
@bbenaissa Bien vu, en plus dans l'interface on propose 2.1 et 2.2, donc je vais changer à `'2.1' | '2.2'`. Bon, après c'est du typage pas très utile parce que pas vérifié par rapport à l'input de l'utilisateur, mais c'est vrai que c'est pas cohérent.

2023-12-11 10:20 UTC, bbenaissa approved these changes

2023-12-11 13:38 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/dip-request-create/dip-request-create.component.ts
> +import {Component, Inject, OnDestroy, OnInit} from '@angular/core';
Du coup, j'ai mis en place Prettier et on a des espaces maintenant.

2023-12-11 13:44 UTC, Regzox approved these changes

2023-12-11 13:47 UTC, bbenaissa approved these changes

2023-12-11 15:56 UTC, merged