Story #11960: Build VitamUI's components in containers and add the associated deployment mode
ProgrammeVitam/vitam-ui pull request #1569
Opened 2023-12-07 10:37 UTC by achoubiemohamed

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2023-12-07 10:54 UTC, GiooDev requested changes

2023-12-07 10:54 UTC, GiooDev commented on Jenkinsfile.containers
> +                // Scan all vuln levels
Si on doit itérer unitairement sur tous les composants, ça serait mieux de faire une liste, d'ailleurs si on rajoute de nouveaux composants il ne faudra pas oublier de les lister ici.

2023-12-07 10:54 UTC, GiooDev commented on ui/ui-archive-search/pom.xml
> +				<groupId>com.google.cloud.tools</groupId>
Indentation à revoir sur plusieurs fichiers ;)

2023-12-07 11:21 UTC, vitam-devops commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx One – Scan Summary & Details** – [113281b5\-feff\-44dd\-8ec4\-df9ef96f8bda](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=113281b5-feff-44dd-8ec4-df9ef96f8bda&branch=story_11960_build_vitam_containers)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2019-15599](https://devhub.checkmarx.com/cve-details/CVE-2019-15599)|Npm\-tree\-kill\-1\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/113281b5-feff-44dd-8ec4-df9ef96f8bda/vulnerabilities/CVE-2019-15599%3ANpm-tree-kill-1.2.1/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-28502](https://devhub.checkmarx.com/cve-details/CVE-2020-28502)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/113281b5-feff-44dd-8ec4-df9ef96f8bda/vulnerabilities/CVE-2020-28502%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-36048](https://devhub.checkmarx.com/cve-details/CVE-2020-36048)|Npm\-engine\.io\-3\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/113281b5-feff-44dd-8ec4-df9ef96f8bda/vulnerabilities/CVE-2020-36048%3ANpm-engine.io-3.2.1/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-36049](https://devhub.checkmarx.com/cve-details/CVE-2020-36049)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/113281b5-feff-44dd-8ec4-df9ef96f8bda/vulnerabilities/CVE-2020-36049%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-7660](https://devhub.checkmarx.com/cve-details/CVE-2020-7660)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/113281b5-feff-44dd-8ec4-df9ef96f8bda/vulnerabilities/CVE-2020-7660%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-7788](https://devhub.checkmarx.com/cve-details/CVE-2020-7788)|Npm\-ini\-1\.3\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/113281b5-feff-44dd-8ec4-df9ef96f8bda/vulnerabilities/CVE-2020-7788%3ANpm-ini-1.3.5/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2021-31597](https://devhub.checkmarx.com/cve-details/CVE-2021-31597)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/113281b5-feff-44dd-8ec4-df9ef96f8bda/vulnerabilities/CVE-2021-31597%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2022-2421](https://devhub.checkmarx.com/cve-details/CVE-2022-2421)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/113281b5-feff-44dd-8ec4-df9ef96f8bda/vulnerabilities/CVE-2022-2421%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2023-32695](https://devhub.checkmarx.com/cve-details/CVE-2023-32695)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/113281b5-feff-44dd-8ec4-df9ef96f8bda/vulnerabilities/CVE-2023-32695%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2023-46589](https://devhub.checkmarx.com/cve-details/CVE-2023-46589)|Maven\-org\.apache\.tomcat\.embed:tomcat\-embed\-core\-9\.0\.63|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/113281b5-feff-44dd-8ec4-df9ef96f8bda/vulnerabilities/CVE-2023-46589%3AMaven-org.apache.tomcat.embed%3Atomcat-embed-core-9.0.63/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2019-16769](https://devhub.checkmarx.com/cve-details/CVE-2019-16769)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/113281b5-feff-44dd-8ec4-df9ef96f8bda/vulnerabilities/CVE-2019-16769%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-6\.10\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/113281b5-feff-44dd-8ec4-df9ef96f8bda/vulnerabilities/CVE-2020-15366%3ANpm-ajv-6.10.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-5\.5\.2|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/113281b5-feff-44dd-8ec4-df9ef96f8bda/vulnerabilities/CVE-2020-15366%3ANpm-ajv-5.5.2/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2020-28481](https://devhub.checkmarx.com/cve-details/CVE-2020-28481)|Npm\-socket\.io\-2\.1\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/113281b5-feff-44dd-8ec4-df9ef96f8bda/vulnerabilities/CVE-2020-28481%3ANpm-socket.io-2.1.1/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2020-7693](https://devhub.checkmarx.com/cve-details/CVE-2020-7693)|Npm\-sockjs\-0\.3\.19|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/113281b5-feff-44dd-8ec4-df9ef96f8bda/vulnerabilities/CVE-2020-7693%3ANpm-sockjs-0.3.19/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2021-23364](https://devhub.checkmarx.com/cve-details/CVE-2021-23364)|Npm\-browserslist\-4\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/113281b5-feff-44dd-8ec4-df9ef96f8bda/vulnerabilities/CVE-2021-23364%3ANpm-browserslist-4.5.5/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2021-23495](https://devhub.checkmarx.com/cve-details/CVE-2021-23495)|Npm\-karma\-4\.1\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/113281b5-feff-44dd-8ec4-df9ef96f8bda/vulnerabilities/CVE-2021-23495%3ANpm-karma-4.1.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.co [...]

2023-12-07 11:22 UTC, GiooDev commented
Revoir le message de commit as l'id et en anglais plz :)

2024-04-05 13:05 UTC, GiooDev commented on deployment/roles/consul/tasks/main.yml
>      mode: "{{ vitamui_defaults.folder.conf_permission | default('0440') }}"
`mode: "{{ '0777' if install_mode == 'container' else vitamui_defaults.folder.folder_permission | default('0440') }}"`

Plutôt que de dupliquer toute la task

2024-04-05 13:06 UTC, GiooDev commented on deployment/roles/consul/templates/consul.json.j2
> -  "enable_syslog": true,
À revérifier, j'ai l'impression qu'en le retirant ça n'a pas l'effet escompté.

Il faudrait check sur /var/log/messages si on a encore les logs consul qui remontent.

2024-04-05 13:09 UTC, GiooDev commented on deployment/roles/consul/templates/vitam-container-consul.service.j2
> +ExecStartPre=-/usr/bin/docker pull {{ container_repository }}/vitam-external/hashicorp/consul:1.18.0
Utiliser la variable `consul_version` (revoir pour la mettre en forme car dans le package on a besoin d'un -1 qu'on peut traiter dans la variable `consul_package`

cf. `deployment/roles/consul/vars/main.yml`

2024-04-05 13:11 UTC, GiooDev commented on deployment/roles/mongo/handlers/main.yml
> +    daemon_reload: yes
Pourquoi avoir déplacé la task de reload de consul ?

2024-04-05 13:12 UTC, GiooDev commented on deployment/roles/mongo/tasks/main.yml
> +    mode: "0777"
Idem éviter de dupliquer toute la task ici.

2024-04-05 13:12 UTC, GiooDev commented on deployment/roles/mongo/templates/mongod.conf.j2
> -  path: {{ vitamui_defaults.folder.root_path | default('/vitamui') }}/log/mongod/mongod.log
Attention, pourquoi retirer le path d'écriture des logs pour mongo ?

2024-04-05 13:13 UTC, GiooDev commented on deployment/roles/mongo/templates/vitamui-container-mongo.service.j2
> +ExecStartPre=-/usr/bin/docker pull {{ container_repository }}/vitam-external/mongodb/mongodb-community-server:7.0.5-ubuntu2204
Mettre à jour 7.0.7

2024-04-05 13:14 UTC, GiooDev commented on deployment/roles/normalize/tasks/vitamui.yml
> +  ansible.builtin.user:
Attention, `ansible.builtin` ne fonctionne pas avec les versions précédentes de ansible. Préférer juste `user:`

2024-04-05 13:18 UTC, GiooDev commented on deployment/roles/vitamui/tasks/main.yml
> +    dest: "{{ systemd_directory }}/vitamui-{{ vitamui_struct.vitamui_component }}.service"
Tu peux virer les 2 tasks précédentes de set_facts si tu mets cette ligne à la place:
`dest: "{{ '/lib/systemd/system' if ansible_os_family == 'Debian' else '/usr/lib/systemd/system' }}/vitamui-{{ vitamui_struct.vitamui_component }}.service"`

2024-04-05 13:21 UTC, GiooDev commented on deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
> +        service-name: vitamui-{{ vitamui_struct.vitamui_component }}
Ça change quoi au niveau du comportement de consul en cas de multi-instanciation ?

2024-04-05 13:23 UTC, GiooDev commented on Jenkinsfile.containers
> + //           cleanWs()
Ne pas oublier de réactiver le cleanWs()

2024-04-05 13:29 UTC, GiooDev requested changes

2024-04-05 13:29 UTC, GiooDev commented on deployment/roles/docker/README.md
> +Role Name
Fichier à retirer

2024-04-05 13:29 UTC, GiooDev commented on deployment/roles/docker/tasks/main.yml
> +  when: install_mode == "container"
Faire un block pour la condition `when: install_mode == "container"` plutôt que de duplique sur chacune des tasks la même condition

2024-04-05 13:29 UTC, GiooDev commented on deployment/ansible-vitamui/pre_install.yml
> +    - docker
Rajouter un conditionnel à l'exécution de ce rôle. Déjà en partie traité sinon à l'aide du block demandé sur la task/main.yml du rôle docker mais ça permet de protéger au niveau de l'appel du rôle directement (notamment si on souhaite utiliser ce rôle en dehors du mode container par exemple).

`- { role: docker, when: install_mode | default('legacy') == "container" }`

2024-04-05 13:29 UTC, GiooDev commented on deployment/roles/consul/tasks/main.yml
> +  when: install_mode != "container"
Attention, de façon générale, qu'est ce qui se passe si je ne set pas cette valeur ?

Par défaut que peut-elle contenir ? ex. `legacy` (par défaut) ou `container`

2024-04-09 07:07 UTC, bbenaissa commented on api/api-archive-search/archive-search-external/pom.xml
> +				 <image>pic-prod-nexus.vitam-factory:9080/vitamui/archive-search-external</image>
Il s'agit de lien interne?

2024-04-09 07:07 UTC, bbenaissa commented on api/api-archive-search/archive-search-external/pom.xml
> +				 <image>pic-prod-nexus.vitam-factory:9080/vitamui/archive-search-external</image>
On peut le rendre parametrable

2024-04-18 14:33 UTC, GiooDev commented on deployment/roles/docker/tasks/main.yml
> +  when: install_mode == "container"
Vérifier si les modifications apportées au rôle côté back vitam sont bien prise en compte pour le rôle ici.

2024-04-18 14:35 UTC, GiooDev commented on deployment/roles/mongo/templates/vitamui-container-mongo.service.j2
> +        {{ container_repository.registry_url }}/vitam-external/mongodb/mongodb-community-server:7.0.7-ubuntu2204 \
Attention, version 7.0.8 maintenant

2024-04-21 10:05 UTC, GiooDev requested changes

2024-04-21 10:05 UTC, GiooDev commented on deployment/roles/mongo/templates/vitamui-container-mongo.service.j2
> +ExecStart=/usr/bin/docker run --rm --net=host --name vitamui-mongod --user 1004:1004 \
À revérifier sur différentes installation pour s'assurer que l'uid:gid est bien celui attendu.

2024-04-22 12:21 UTC, achoubiemohamed commented on deployment/ansible-vitamui/pre_install.yml
> +    - docker
done

2024-04-22 12:55 UTC, GiooDev requested changes

2024-04-22 12:55 UTC, GiooDev commented on deployment/roles/consul/templates/vitam-container-consul.service.j2
> +        --memory=1536m \
Limiter à 1024m comme sur le back.

2024-04-22 12:55 UTC, GiooDev commented on deployment/roles/consul/handlers/main.yml
> +    state: reloaded
Lors d'une installation initiale, est-ce que ça passe pour le premier start ?

Ce n'est pas iso avec le rôle côté back.

2024-04-22 12:56 UTC, achoubiemohamed commented on deployment/roles/consul/handlers/main.yml
> +    state: reloaded
ça passe

2024-04-22 15:19 UTC, GiooDev commented on Jenkinsfile.containers
> +        stage('Set scanner preriquities') {
preriquities ?

2024-04-22 15:29 UTC, GiooDev requested changes

2024-04-22 15:29 UTC, GiooDev commented on deployment/roles/normalize/tasks/vitamui.yml
> +- name: Create the user vitamui
Déjà fait par le rôle `users` lors de l'exécution du playbook `deployment/ansible-vitamui/pre_install.yml`

À retirer.

2024-04-22 15:29 UTC, GiooDev commented on deployment/roles/normalize/tasks/vitamui.yml
> +- name: Create the user vitam
Pourquoi on a besoin de créer le user vitam ici ?

2024-04-22 15:29 UTC, GiooDev commented on deployment/roles/vitamui/templates/pastis-external/application.yml.j2
> +        service-name: vitamui-{{ vitamui_struct.vitamui_component }}
Renommer `serviceName` pour aligner avec le camel case des autres param (instanceId par exemple).

2024-04-22 15:29 UTC, GiooDev commented on deployment/roles/vitamui/templates/vitamui-container-componentid.service.j2
> +                              -e "JAVA_TOOL_OPTIONS=-Xlog:gc*,gc+age=trace,safepoint:file=/vitamui/log/{{ vitamui_struct.vitamui_component }}/gc.log:utctime,pid,tags:filecount=32,filesize=64m -XX:Max
Reprendre les paramètres par défaut (comme sur le back) pour la définition des gc & autres paramètres.

`jvm_opts.memory`, `jvm_opts.gc` & `jvm_opts.java` tel que définit dans `deployment/roles/vitamui/defaults/main.yml`

2024-04-22 15:34 UTC, GiooDev requested changes

2024-04-22 15:34 UTC, GiooDev commented on deployment/roles/mongo/tasks/main.yml
> +<<<<<<< HEAD
Attention conflit de rebase à cleaner.

2024-04-22 15:34 UTC, GiooDev commented on deployment/roles/mongo/tasks/main.yml
> +<<<<<<< HEAD
Ici aussi, conflit de rebase à nettoyer.

2024-04-22 15:35 UTC, achoubiemohamed commented on deployment/roles/vitamui/templates/pastis-external/application.yml.j2
> +        service-name: vitamui-{{ vitamui_struct.vitamui_component }}
je ne sais pas si serviceName est le bon paramètre Spring

2024-04-22 15:38 UTC, GiooDev commented on Jenkinsfile.containers
> +        stage('Set scanner preriquisities') {
Presque :p `prerequisites`

2024-04-22 15:39 UTC, GiooDev requested changes

2024-04-22 15:39 UTC, GiooDev commented on Jenkinsfile.containers
> +                    sh 'mvn  --settings .ci/settings.xml install -Djib.skip=false  -DskipTests=true --show-version --batch-mode --errors -fn -DinstallAtEnd=true -DdeployAtEnd=true package -Pvitam   -
Attention, la commande mvn a évoluée aussi, on ne build plus vitamui-nginx, mongod (et bientôt logstash).

2024-04-22 15:40 UTC, GiooDev commented on deployment/roles/vitamui/templates/pastis-external/application.yml.j2
> +        service-name: vitamui-{{ vitamui_struct.vitamui_component }}
Normalement si: https://cloud.spring.io/spring-cloud-consul/reference/html/

C'est très bizarre spring, ils gèrent 2 types de convention de variables.

2024-04-22 15:45 UTC, achoubiemohamed commented on Jenkinsfile.containers
> +                    sh 'mvn  --settings .ci/settings.xml install -Djib.skip=false  -DskipTests=true --show-version --batch-mode --errors -fn -DinstallAtEnd=true -DdeployAtEnd=true package -Pvitam   -
c'est le cas dans la commande avec le !

2024-04-22 15:54 UTC, GiooDev commented on Jenkinsfile.containers
> +                    sh 'mvn  --settings .ci/settings.xml install -Djib.skip=false  -DskipTests=true --show-version --batch-mode --errors -fn -DinstallAtEnd=true -DdeployAtEnd=true package -Pvitam   -
Oui mais je veux dire que ça peut totalement être retiré puisque ça n'existera plus, au moins pour nginx et mongod.
Une fois ta PR mergée je prendrai en compte la modif pour logstash dans mon autre PR.

2024-04-24 12:27 UTC, merged