Story 11868 api gateway ansible rework
ProgrammeVitam/vitam-ui pull request #1594
Opened 2023-12-14 09:15 UTC by Ro3034

## Description

*Description des modifications*

Ajout du déploiement de la gateway et des ui en mode gateway avec un mode activable/désactivable.

## Type de changement:

*Indiquer le ou les types de changements*
Ansiblerie 
PKI
Scripts mongodb 

* Build

* PKI
Rajout de l'extension serveur et de la génération des pem dans un cas supplémentaire.

* Ansiblerie
Rajout des roles asset_copy, nginx_webapp et ajout de variables et code pour activer/désactiver 
l'installation des ui en mode legacy ou gateway. Modification des templates pour avoir les 2 modes.

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2023-12-14 10:02 UTC, vitam-devops commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx One – Scan Summary & Details** – [3bba5fea\-97d1\-4e94\-b051\-20e1146b81ca](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=3bba5fea-97d1-4e94-b051-20e1146b81ca&branch=story_11868_api_gateway_ansible_rework)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2019-15599](https://devhub.checkmarx.com/cve-details/CVE-2019-15599)|Npm\-tree\-kill\-1\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3bba5fea-97d1-4e94-b051-20e1146b81ca/vulnerabilities/CVE-2019-15599%3ANpm-tree-kill-1.2.1/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-28502](https://devhub.checkmarx.com/cve-details/CVE-2020-28502)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3bba5fea-97d1-4e94-b051-20e1146b81ca/vulnerabilities/CVE-2020-28502%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-36048](https://devhub.checkmarx.com/cve-details/CVE-2020-36048)|Npm\-engine\.io\-3\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3bba5fea-97d1-4e94-b051-20e1146b81ca/vulnerabilities/CVE-2020-36048%3ANpm-engine.io-3.2.1/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-36049](https://devhub.checkmarx.com/cve-details/CVE-2020-36049)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3bba5fea-97d1-4e94-b051-20e1146b81ca/vulnerabilities/CVE-2020-36049%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-7660](https://devhub.checkmarx.com/cve-details/CVE-2020-7660)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3bba5fea-97d1-4e94-b051-20e1146b81ca/vulnerabilities/CVE-2020-7660%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-7788](https://devhub.checkmarx.com/cve-details/CVE-2020-7788)|Npm\-ini\-1\.3\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3bba5fea-97d1-4e94-b051-20e1146b81ca/vulnerabilities/CVE-2020-7788%3ANpm-ini-1.3.5/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2021-31597](https://devhub.checkmarx.com/cve-details/CVE-2021-31597)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3bba5fea-97d1-4e94-b051-20e1146b81ca/vulnerabilities/CVE-2021-31597%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2022-2421](https://devhub.checkmarx.com/cve-details/CVE-2022-2421)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3bba5fea-97d1-4e94-b051-20e1146b81ca/vulnerabilities/CVE-2022-2421%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2023-32695](https://devhub.checkmarx.com/cve-details/CVE-2023-32695)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3bba5fea-97d1-4e94-b051-20e1146b81ca/vulnerabilities/CVE-2023-32695%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2019-16769](https://devhub.checkmarx.com/cve-details/CVE-2019-16769)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3bba5fea-97d1-4e94-b051-20e1146b81ca/vulnerabilities/CVE-2019-16769%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-6\.10\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3bba5fea-97d1-4e94-b051-20e1146b81ca/vulnerabilities/CVE-2020-15366%3ANpm-ajv-6.10.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-5\.5\.2|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3bba5fea-97d1-4e94-b051-20e1146b81ca/vulnerabilities/CVE-2020-15366%3ANpm-ajv-5.5.2/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2020-28481](https://devhub.checkmarx.com/cve-details/CVE-2020-28481)|Npm\-socket\.io\-2\.1\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3bba5fea-97d1-4e94-b051-20e1146b81ca/vulnerabilities/CVE-2020-28481%3ANpm-socket.io-2.1.1/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2020-7693](https://devhub.checkmarx.com/cve-details/CVE-2020-7693)|Npm\-sockjs\-0\.3\.19|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3bba5fea-97d1-4e94-b051-20e1146b81ca/vulnerabilities/CVE-2020-7693%3ANpm-sockjs-0.3.19/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2021-23364](https://devhub.checkmarx.com/cve-details/CVE-2021-23364)|Npm\-browserslist\-4\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3bba5fea-97d1-4e94-b051-20e1146b81ca/vulnerabilities/CVE-2021-23364%3ANpm-browserslist-4.5.5/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2021-23495](https://devhub.checkmarx.com/cve-details/CVE-2021-23495)|Npm\-karma\-4\.1\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3bba5fea-97d1-4e94-b051-20e1146b81ca/vulnerabilities/CVE-2021-23495%3ANpm-karma-4.1.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2022-0437](https://devhub.checkmarx.com/cve-details/CVE-2022-0437)|Npm\-karma\-4\.1\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3bba5fea-97d1-4e94-b051-20e1146b81ca/vulnerabilities/CVE-2022-0437%3ANpm-karma-4.1.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2022-21704](ht [...]

2023-12-14 10:43 UTC, GiooDev requested changes

2023-12-14 10:43 UTC, GiooDev commented on deployment/roles/assets_copy/files/instance-operator-logo.png
Mettre à jour les assets avec ceux du role sous vitamui/

2023-12-14 10:43 UTC, GiooDev commented on deployment/roles/nginx_webapp/templates/frontend/identity-admin/vhost.conf.j2
> +    proxy_pass {{ 'https' if vitamui.api_gateway.server_secure | bool else 'http' }}://API-GATEWAY;
Mettre un default(true)

2023-12-14 10:43 UTC, GiooDev commented on deployment/roles/vitamui/templates/iam-external/application.yml.j2
> +    client-certificate-header-name: {{ vitamui.api_gateway.client_certificate_header_name }}
Rajouter un ` | default('x-ssl-cert')`

2023-12-14 10:43 UTC, GiooDev commented on deployment/roles/nginx_webapp/templates/frontend/identity-admin/vhost.conf.j2
> +    add_header Cache-Control "{{ vitamui.identity_admin.resources_header_cache_control}}";
Mettre un `default('max-age=1800, must-revalidate')`

2023-12-14 10:43 UTC, GiooDev commented on deployment/roles/nginx_webapp/templates/frontend/portal/config.json.j2
> +    {%- if vitamui.portal.has_tenant_list is defined %}
```
    "hasTenantList": {{ "true" if vitamui.portal.has_tenant_list | default(false) | bool == true else "false" }},
    "hasLangSelection": {{ "true" if vitamui.portal.has_lang_selection | default(false) | bool == true else "false" }},
    "hasSiteSelection" : {{ "true" if vitamui.portal.has_site_selection | default(true) | bool == true else "false" }}
```

2023-12-14 10:43 UTC, GiooDev commented on deployment/environments/group_vars/all/vitamui_vars.yml
> +    portal_logo: "logo_PORTAL.png"
Retirer et définir par défaut.

2023-12-14 10:43 UTC, GiooDev commented on deployment/environments/group_vars/all/vitamui_vars.yml
> +    external_url:
Pas utilisé ?

2023-12-14 10:43 UTC, GiooDev commented on deployment/environments/group_vars/all/vitamui_vars.yml
> +portal:
À retirer.

Définit sous: `vitamui_platform_informations.portal_message` & `vitamui_platform_informations.portal_title`

2023-12-14 10:43 UTC, GiooDev commented on deployment/roles/nginx_webapp/templates/frontend/identity-admin/config.json.j2
> +  "PORTAL_MESSAGE": "{{ portal.message }}",
Remplacer `vitamui_platform_informations.portal_message`

2023-12-14 10:43 UTC, GiooDev commented on deployment/roles/nginx_webapp/templates/frontend/identity/config.json.j2
> +  "PORTAL_TITLE": "{{ portal.title }}",
Remplacer `vitamui_platform_informations.portal_title`

2023-12-14 10:43 UTC, GiooDev commented on deployment/environments/group_vars/all/frontend.yml
> +app_certificates:
Pas utile, définir par déduction le certificat adapté au service associé.

cf. pki vitam ?

2023-12-14 10:43 UTC, GiooDev commented on deployment/environments/group_vars/all/frontend.yml
> +frontend_ssl_global_certificate_enabled: true
À retirer.

2023-12-14 10:43 UTC, GiooDev commented on deployment/ansible-vitamui/app_api_gateway.yml
> +    frontend_application_version: "7.1.0-SNAPSHOT" #"{{ app_version }}"
Passer une vitamui_struct: comme sur vitam

2023-12-14 10:43 UTC, GiooDev commented on deployment/roles/nginx_webapp/templates/frontend/identity-admin/config.json.j2
> +{
Voir pour mutualiser le fichier de config pour toutes les UI et gérer quelques conditionnels en fonction du besoin pour éviter trop de duplication de code.

Passer une vitamui_struct: comme sur vitam pour définir les paramètres nécessaires.

2023-12-14 10:43 UTC, GiooDev commented on deployment/roles/nginx_webapp/templates/frontend/identity-admin/vhost.conf.j2
> +server {
Voir pour mutualiser le fichier de config pour toutes les UI et gérer quelques conditionnels en fonction du besoin pour éviter trop de duplication de code.

Passer une vitamui_struct: comme sur vitam pour définir les paramètres nécessaires.

2023-12-14 10:43 UTC, GiooDev commented on deployment/roles/reverse/defaults/main.yml
> +nginx_ssl_conf: "/etc/nginx/ssl"
Quid en cas de migration d'une instance déjà en prod ?

2023-12-14 10:43 UTC, GiooDev commented on deployment/roles/reverse/templates/nginx/conf.d/upstream.j2
> +
Saut de ligne en trop, voir si le - est nécessaire ? Rajouter sinon le `#jinja2: lstrip_blocks: True`

2023-12-14 10:43 UTC, GiooDev commented on deployment/roles/assets_copy/README.md
> +Role Name
Role assets non nécessaire, les assets sont livrés par le rôle vitamui/ pour les composants de type ui.

Voir si nécessaire de refacto cette partie sinon; notamment dans le cas où des partenaires souhaiteraient mettre leurs propres assets (sous environments/)

2023-12-14 11:03 UTC, Ro3034 commented on deployment/roles/assets_copy/README.md
> +Role Name
Copie des assets corrects réalisés dans le rôle "asset_copy".

Une fois toutes les UI migrées sur le format gateway, on enlèvera la gestion des assets du rôle "vitamui" pour utiliser le rôle "asset_copy" uniquement.

2023-12-14 17:44 UTC, GiooDev requested changes

2023-12-14 17:44 UTC, GiooDev commented on deployment/roles/nginx_webapp/templates/frontend/config.json.j2
> +  {% if vitamui_struct.vitamui_component == "ui-identity" and vitam.enabled is defined %}
Ça correspond à quoi `vitam.enabled` ?

2023-12-14 17:44 UTC, GiooDev commented on deployment/roles/nginx_webapp/templates/frontend/config.json.j2
> +  {% if vitamui_struct.vitamui_component == "ui-portal" and vitamui.portal.has_tenant_list is defined or vitamui.portal.has_lang_selection is defined or vitamui.portal.has_site_selection is defined %
Est-ce que ça pose problème d'afficher le bloc sans toutes les conditions has_tenant_list, has_lang_selection & co ?

Si non, l'afficher par défaut pour la config de ui-portal pour simplifier ce if :)

2023-12-14 17:44 UTC, GiooDev commented on deployment/roles/nginx_webapp/templates/frontend/config.json.j2
> +  "REFERENTIAL_URL": "{{ vitamui.referential.base_url }}",
On a besoin de la REFERENTIAL_URL pour toutes les apps frontend ?

2023-12-14 17:44 UTC, GiooDev commented on deployment/roles/nginx_webapp/templates/frontend/vhost.conf.j2
> +    add_header Cache-Control "{{ vitamui.identity.resources_header_cache_control | default('max-age=1800, must-revalidate')}}";
`vitamui_struct` ici plutôt que `vitamui.identity`

2023-12-14 17:44 UTC, GiooDev commented on deployment/scripts/mongod/1.0.0/05_security.populate_certificates_ref.js.j2
> +{{ process('{{ pki_dir }}/client-external/clients/ui-identity-admin/ui-identity-admin.pem', 'ui_admin_identity_context', 'hosts_ui_identity_admin') }}
Attention, prévoir un script de migration si on conserve ce nouveau chemin pour les certificats déjà existant en base ou alors documenter dans la DMV (ou automatiser) le cleanup dans la base changelog des scripts qui nécessitent d'être rejoués.

2023-12-14 17:54 UTC, Ro3034 commented on deployment/roles/nginx_webapp/templates/frontend/config.json.j2
> +  "REFERENTIAL_URL": "{{ vitamui.referential.base_url }}",
La même pour tout le monde.

2023-12-15 17:41 UTC, Ro3034 commented on deployment/roles/nginx_webapp/templates/frontend/config.json.j2
> +  {% if vitamui_struct.vitamui_component == "ui-identity" and vitam.enabled is defined %}
Cela ne sert plus.

2023-12-15 17:44 UTC, Ro3034 commented on deployment/roles/nginx_webapp/templates/frontend/config.json.j2
> +  {% if vitamui_struct.vitamui_component == "ui-portal" and vitamui.portal.has_tenant_list is defined or vitamui.portal.has_lang_selection is defined or vitamui.portal.has_site_selection is defined %
Logiquement non. On prends les valeurs. Pas besoin de faire la longue liste de if du coup.

2023-12-16 12:46 UTC, Ro3034 commented on deployment/roles/reverse/defaults/main.yml
> +nginx_ssl_conf: "/etc/nginx/ssl"
Le dossier a été remis comme avant.

2023-12-17 20:17 UTC, Ro3034 commented on deployment/scripts/mongod/1.0.0/05_security.populate_certificates_ref.js.j2
> +{{ process('{{ pki_dir }}/client-external/clients/ui-identity-admin/ui-identity-admin.pem', 'ui_admin_identity_context', 'hosts_ui_identity_admin') }}
Suite au changement d'extension dans la génération des certificats cette modification n'est plus nécessaire. On peut rester sur l'ancien code du script. Par contre, il faudra effectivement une procédure de montée de version car les certificats sont différents malgré tout.

2023-12-17 20:39 UTC, GiooDev requested changes

2023-12-17 20:39 UTC, GiooDev commented on deployment/environments/group_vars/all/vitamui_vars.yml
> +    base_url: "https://{{ vitam_reverse_external_dns }}/identity"
Est-ce que les base_url sont réellement personnalisables puisque dans la configuration du vhost du nginx les locations sont en dur ?

2023-12-17 20:39 UTC, GiooDev commented on deployment/roles/assets_copy/tasks/main.yml
> +  become: true
become pas nécessaire ici puisqu'on exécute déjà via root l'exécution de la commande ansible-playbook non ?

2023-12-18 15:17 UTC, Ro3034 commented on deployment/environments/group_vars/all/vitamui_vars.yml
> +    base_url: "https://{{ vitam_reverse_external_dns }}/identity"
Mis par default. Nécessaire pour la gateway.

2023-12-19 15:33 UTC, GiooDev requested changes

2023-12-19 15:33 UTC, GiooDev commented on deployment/scripts/mongod/v7.1/003_TRV-399_enable_oidc_code_grant_type_on_portal_service_ref.js.j2
> +  clientId: "portal",
On peut peut-être conserver la possibilité de surcharger cette valeur comme avant ?

```
clientId: "{{ vitamui.portal.clientId | default('portal') }}",
name: "{{ vitamui.portal.name | default('Portal Application') }}",
```

2023-12-19 16:08 UTC, GiooDev requested changes

2023-12-19 16:08 UTC, GiooDev commented on deployment/roles/nginx_webapp/templates/frontend/config.json.j2
> +  "REFERENTIAL_URL": "{{ vitamui.referential.base_url }}",
`"REFERENTIAL_URL": "{{ vitamui.referential.base_url | default(url_prefix+'/referential') }}",`

2023-12-20 10:17 UTC, GiooDev commented on deployment/environments/group_vars/all/vitamui_vars.yml
> +    #base_url: "https://{{ vitam_reverse_external_dns }}/ingest"
Supprimer les base_url de ce fichier de variables.

2023-12-20 10:24 UTC, GiooDev commented on deployment/environments/vitamui_extra_vars.yml
> +opentracing.enable: false
Attention, parfois le hashmerge ne fonctionne pas bien avec les variables présentés ainsi.

D'ailleurs, pour toutes les autres variables on met enabled et pas enable. Préciser aussi dans les fichiers de config une variable par défaut en cas de non set de la variable.

Mieux vaut préciser la variable en 2 lignes tel que:
```yml
opentracing:
  enabled: false
```

2023-12-20 10:33 UTC, bbenaissa requested changes

2023-12-20 10:33 UTC, bbenaissa commented on deployment/scripts/mongod/v7.1/003_TRV-399_enable_oidc_code_grant_type_on_portal_service_ref.js.j2
> +db.services.deleteOne({ "_id": NumberInt(1) });
Je propose d'utiliser plutot par name ou Id au lieu de la séquence, et un update au lieu de delete puis insert?

2023-12-20 10:33 UTC, bbenaissa commented on deployment/scripts/mongod/v7.1/004_TRV-400_enable_oidc_code_grant_type_on_identity_service_ref.js.j2
> +db.services.deleteOne({ "_id": NumberInt(2) });
Idem

2023-12-20 14:07 UTC, Ro3034 commented on deployment/scripts/mongod/v7.1/003_TRV-399_enable_oidc_code_grant_type_on_portal_service_ref.js.j2
> +db.services.deleteOne({ "_id": NumberInt(1) });
L'update avait été testé mais ça ne fonctionnait pas car la structure insérée avant n'était pas identique à cet insert ici.

2023-12-20 14:08 UTC, Ro3034 commented on deployment/scripts/mongod/v7.1/003_TRV-399_enable_oidc_code_grant_type_on_portal_service_ref.js.j2
> +db.services.deleteOne({ "_id": NumberInt(1) });
On est bien sur l'id. Je n'ai pas compris.

2023-12-20 14:08 UTC, Ro3034 commented on deployment/scripts/mongod/v7.1/004_TRV-400_enable_oidc_code_grant_type_on_identity_service_ref.js.j2
> +db.services.deleteOne({ "_id": NumberInt(2) });
idem voir avant.

2023-12-21 13:01 UTC, GiooDev commented on tools/packaging/Makefile-fronts
> +USER            := vitamui
Pourquoi pas mettre $(USER) ici ?

2023-12-21 13:23 UTC, GiooDev commented on deployment/scripts/mongod/v7.1/003_TRV-399_enable_oidc_code_grant_type_on_portal_service_ref.js.j2
> +db.services.deleteOne({ "_id": NumberInt(1) });
Oui je ne comprend pas le problème. Fonctionner par l'id me semble le plus pertinent tel que c'est fait car dans les scripts qui font l'enregistrement de ces services on a déjà mis l'id en dur.

2023-12-21 14:36 UTC, GiooDev commented on api/api-gateway/src/main/resources/application-dev.yml
> +             # /referential-api/fileFormat/**, doesn't exist
À supprimer.

2023-12-21 14:46 UTC, GiooDev commented on deployment/environments/group_vars/all/vitamui_vars.yml
> -      vitamui_platform_name: VITAM-UI
Attention, cette variable semble utilisée dans cas-server; elle a aussi été retirée dans la config. Quelle est la valeur qui sera ainsi settée par défaut ? Pourquoi n'est-elle plus personnalisable ?

2023-12-21 17:07 UTC, GiooDev approved these changes

2023-12-21 17:08 UTC, GiooDev commented
Ne pas oublier de `Squash and merge` plz !

Merci pour le super boulot :)

2023-12-22 13:20 UTC, merged