Feature/migration archive search to api gateway
ProgrammeVitam/vitam-ui pull request #1609
Opened 2024-01-12 08:37 UTC by bbenaissa

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2024-01-12 09:10 UTC, vitam-devops commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx One – Scan Summary & Details** – [66fa7080\-8617\-49c8\-9f23\-82f4869e6312](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=66fa7080-8617-49c8-9f23-82f4869e6312&branch=feature%2Fmigration-archive-search-to-api-gateway)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2019-15599](https://devhub.checkmarx.com/cve-details/CVE-2019-15599)|Npm\-tree\-kill\-1\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/66fa7080-8617-49c8-9f23-82f4869e6312/vulnerabilities/CVE-2019-15599%3ANpm-tree-kill-1.2.1/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-28502](https://devhub.checkmarx.com/cve-details/CVE-2020-28502)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/66fa7080-8617-49c8-9f23-82f4869e6312/vulnerabilities/CVE-2020-28502%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-36048](https://devhub.checkmarx.com/cve-details/CVE-2020-36048)|Npm\-engine\.io\-3\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/66fa7080-8617-49c8-9f23-82f4869e6312/vulnerabilities/CVE-2020-36048%3ANpm-engine.io-3.2.1/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-36049](https://devhub.checkmarx.com/cve-details/CVE-2020-36049)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/66fa7080-8617-49c8-9f23-82f4869e6312/vulnerabilities/CVE-2020-36049%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-7660](https://devhub.checkmarx.com/cve-details/CVE-2020-7660)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/66fa7080-8617-49c8-9f23-82f4869e6312/vulnerabilities/CVE-2020-7660%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-7788](https://devhub.checkmarx.com/cve-details/CVE-2020-7788)|Npm\-ini\-1\.3\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/66fa7080-8617-49c8-9f23-82f4869e6312/vulnerabilities/CVE-2020-7788%3ANpm-ini-1.3.5/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2021-31597](https://devhub.checkmarx.com/cve-details/CVE-2021-31597)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/66fa7080-8617-49c8-9f23-82f4869e6312/vulnerabilities/CVE-2021-31597%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2022-2421](https://devhub.checkmarx.com/cve-details/CVE-2022-2421)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/66fa7080-8617-49c8-9f23-82f4869e6312/vulnerabilities/CVE-2022-2421%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2023-32695](https://devhub.checkmarx.com/cve-details/CVE-2023-32695)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/66fa7080-8617-49c8-9f23-82f4869e6312/vulnerabilities/CVE-2023-32695%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2019-16769](https://devhub.checkmarx.com/cve-details/CVE-2019-16769)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/66fa7080-8617-49c8-9f23-82f4869e6312/vulnerabilities/CVE-2019-16769%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-6\.10\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/66fa7080-8617-49c8-9f23-82f4869e6312/vulnerabilities/CVE-2020-15366%3ANpm-ajv-6.10.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-5\.5\.2|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/66fa7080-8617-49c8-9f23-82f4869e6312/vulnerabilities/CVE-2020-15366%3ANpm-ajv-5.5.2/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2020-28481](https://devhub.checkmarx.com/cve-details/CVE-2020-28481)|Npm\-socket\.io\-2\.1\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/66fa7080-8617-49c8-9f23-82f4869e6312/vulnerabilities/CVE-2020-28481%3ANpm-socket.io-2.1.1/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2020-7693](https://devhub.checkmarx.com/cve-details/CVE-2020-7693)|Npm\-sockjs\-0\.3\.19|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/66fa7080-8617-49c8-9f23-82f4869e6312/vulnerabilities/CVE-2020-7693%3ANpm-sockjs-0.3.19/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2021-23364](https://devhub.checkmarx.com/cve-details/CVE-2021-23364)|Npm\-browserslist\-4\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/66fa7080-8617-49c8-9f23-82f4869e6312/vulnerabilities/CVE-2021-23364%3ANpm-browserslist-4.5.5/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2021-23495](https://devhub.checkmarx.com/cve-details/CVE-2021-23495)|Npm\-karma\-4\.1\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/66fa7080-8617-49c8-9f23-82f4869e6312/vulnerabilities/CVE-2021-23495%3ANpm-karma-4.1.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2022-0437](https://devhub.checkmarx.com/cve-details/CVE-2022-0437)|Npm\-karma\-4\.1\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/66fa7080-8617-49c8-9f23-82f4869e6312/vulnerabilities/CVE-2022-0437%3ANpm-karma-4.1.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-202 [...]

2024-01-12 14:11 UTC, GiooDev requested changes, later dismissed

2024-01-12 14:11 UTC, GiooDev commented on deployment/roles/vitamui/templates/api-gateway/application.yml.j2
> +          uri: https://localhost:8089  # URL ARCHIVE-SEARCH EXTERNAL
L'uri semble incorrecte, à remplacer par: `uri: {{ 'https' if vitamui.archive_search_external.secure | default(secure) | bool else 'http' }}://{{ vitamui.archive_search_external.host }}:{{ vitamui.archive_search_external.port_service }}`

2024-01-12 14:11 UTC, GiooDev commented on deployment/scripts/mongod/v7.1/039_enable_oidc_code_grant_type_on_archive_search_service_ref.js.j2
> +db.services.insertOne({
Attention, dans la MR de recharting du CEA, la méthode auto-incrémente les IDs.

Il y a donc un risque de conflit.
Reprendre la méthode dans la PR de recharting. Idem pour le serices.deleteOne juste au dessus.

2024-02-01 13:36 UTC, ebernard commented on deployment/scripts/mongod/v7.1/039_enable_oidc_code_grant_type_on_archive_search_service_ref.js.j2
> +db.services.insertOne({
Changé ci-dessus (lignes 7 à 17).

2024-02-01 17:32 UTC, marob submitted a review, later dismissed
Ce n'est qu'une review de surface sans rentrer dans les détails.

2024-02-01 17:32 UTC, marob commented on api/api-archive-search/archive-search-external/pom.xml
> +        </dependency>
Pourquoi utilise-t-on une version pour JDK 1.5+ qui est dépréciée et qui contient des vulnérabilités alors qu'il existe une version pour jdk 1.8+ ?

2024-02-01 17:32 UTC, marob commented on cas/cas-server/src/main/config/cas-server-application-dev.yml
> +cas.http-web-request.cors.allow-origins: [ "https://dev.vitamui.com:4200", "https://dev.vitamui.com:4201", "https://dev.vitamui.com:4202", "https://dev.vitamui.com:4209", "https://dev.vitamui.com:420
Étonnant qu'on n'ait pas les même ports entre localhost et dev.vitamui.com. Aussi, il serait préférable de conserver un ordre ascendant pour les ports aussi bien pour localhost que pour dev.vitamui.com (ici 4209 est avant 4208 pour dev.vitamui.com mais pas pour localhost)

2024-02-01 17:32 UTC, marob commented on deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
> +    {% else %}
If sans code ?

2024-02-01 17:32 UTC, marob commented on deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
> +    {% else %}
Mauvaise indentation ?

2024-02-01 17:32 UTC, marob commented on deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
> +{% endif %}
Mauvaise indentation ?

2024-02-01 17:32 UTC, marob commented on ui/ui-frontend/package.json
> +    "start:archive-search:gateway": "ng serve archive-search --proxy-config proxy.conf.js --disable-host-check --ssl --ssl-key $npm_package_pki_path/$npm_package_pki_asset.key --ssl-cert $npm_package
Ne pourrait-on pas factoriser le code de la ligne de commande ?

2024-02-02 17:56 UTC, ebernard commented on api/api-archive-search/archive-search-external/pom.xml
> +        </dependency>
il faudrait upgrader la dépendance pour tout le projet. Est-ce vraiment le sujet de l'US ?

2024-02-02 17:56 UTC, ebernard commented on deployment/roles/vitamui/templates/api-gateway/application.yml.j2
> +          uri: https://localhost:8089  # URL ARCHIVE-SEARCH EXTERNAL
Corrigé

2024-02-02 17:56 UTC, ebernard commented on cas/cas-server/src/main/config/cas-server-application-dev.yml
> +cas.http-web-request.cors.allow-origins: [ "https://dev.vitamui.com:4200", "https://dev.vitamui.com:4201", "https://dev.vitamui.com:4202", "https://dev.vitamui.com:4209", "https://dev.vitamui.com:420
Corrigé.

2024-02-02 17:56 UTC, ebernard commented on deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
> +    {% else %}
Corrigé.

2024-02-02 17:56 UTC, ebernard commented on deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
> +    {% else %}
Corrigé.

2024-02-02 17:56 UTC, ebernard commented on deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
> +{% endif %}
Corrigé. (désolé pour tous les commentaires séparés, je suis obligé de faire un par un car j'ai fait un rebase de develop et donc un force push et github ne retrouve plus ses petits)

2024-02-05 13:32 UTC, ebernard commented on ui/ui-frontend/package.json
> +    "start:archive-search:gateway": "ng serve archive-search --proxy-config proxy.conf.js --disable-host-check --ssl --ssl-key $npm_package_pki_path/$npm_package_pki_asset.key --ssl-cert $npm_package
Done pour celui-là et d'autres, mais il faudrait probablement aller plus loin dans la factorisation.

2024-02-05 13:36 UTC, marob commented on api/api-archive-search/archive-search-external/pom.xml
> +        </dependency>
En effet. Mais dans ce cas peut-être qu'il faudrait créer une US de dette ?

2024-02-05 13:39 UTC, ebernard commented on api/api-archive-search/archive-search-external/pom.xml
> +        </dependency>
Je pense que ça peut rentrer dans une US un peu plus générale de mise à jour des dépendances. On n'a pas déjà ça quelque part ?

2024-02-05 13:41 UTC, marob commented on ui/ui-frontend/package.json
> -    "start:referential:gateway": "ng serve referential --proxy-config proxy.conf.js --disable-host-check --ssl --ssl-key $npm_package_pki_path/$npm_package_pki_asset.key --ssl-cert $npm_package_pki_p
On a un `proxy.conf.json` ET un `proxy.conf.js` ?

2024-02-05 13:43 UTC, ebernard commented on ui/ui-frontend/package.json
> -    "start:referential:gateway": "ng serve referential --proxy-config proxy.conf.js --disable-host-check --ssl --ssl-key $npm_package_pki_path/$npm_package_pki_asset.key --ssl-cert $npm_package_pki_p
Oui. `proxy.conf.json` pour l'utilisation en mode classique, `proxy.conf.js` pour l'utilisation en mode api gateway.

2024-02-05 13:50 UTC, marob commented on ui/ui-frontend/package.json
> -    "start:referential:gateway": "ng serve referential --proxy-config proxy.conf.js --disable-host-check --ssl --ssl-key $npm_package_pki_path/$npm_package_pki_asset.key --ssl-cert $npm_package_pki_p
Hmm, dans ce cas, il faudrait peut-être renommer le `proxy.conf.js` en `proxy-gateway.conf.js` ou équivalent ?

2024-02-05 13:54 UTC, ebernard commented on ui/ui-frontend/package.json
> -    "start:referential:gateway": "ng serve referential --proxy-config proxy.conf.js --disable-host-check --ssl --ssl-key $npm_package_pki_path/$npm_package_pki_asset.key --ssl-cert $npm_package_pki_p
✅

2024-02-05 14:15 UTC, ebernard commented on api/api-archive-search/archive-search-external/pom.xml
> +        </dependency>
Voir ticket Tuleap numéro 12363

2024-02-06 16:59 UTC, Regzox commented on deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
>          type: JKS
Inversion de la condition pour éviter la répétition avec le truststore ?
```
{% if gateway.enabled | default(False) is sameas false %}
  keystore:
    key-path: {{ vitamui_folder_conf }}/keystore_{{ vitamui_struct.service_name | default(service_name) }}.jks
    key-password: {{ password_keystore }}
    type: JKS
{% endif %}
  truststore:
    key-path: {{ vitamui_folder_conf }}/truststore_{{ vitamui_certificate_type }}.jks
    key-password: {{ password_truststore }}
```

2024-02-06 16:59 UTC, Regzox commented on deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
>          key-password:  {{ password_truststore }}
idem

2024-02-06 16:59 UTC, Regzox commented on deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
>          key-password:  {{ password_truststore }}
idem

2024-02-06 16:59 UTC, Regzox commented on deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
>          key-password:  {{ password_truststore }}
idem

2024-02-07 08:31 UTC, ebernard commented on deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
>          type: JKS
Done.

2024-02-07 08:33 UTC, ebernard commented on deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
>          key-password:  {{ password_truststore }}
Done.

2024-02-07 08:33 UTC, ebernard commented on deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
>          key-password:  {{ password_truststore }}
Done.

2024-02-07 08:34 UTC, ebernard commented on deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
>          key-password:  {{ password_truststore }}
Done.

2024-02-07 10:47 UTC, bbenaissa commented on api/api-gateway/src/main/resources/application-dev.yml
> +              /referential-api/customers/**,
je ne pense pas qu'on a besoin de la route /referential-api/customers/**,

2024-02-07 10:47 UTC, bbenaissa commented on deployment/roles/vitamui/templates/api-gateway/application.yml.j2
> +              /archive-search-api/customers/**,
Pareil pour le /customers

2024-02-07 10:47 UTC, bbenaissa commented on deployment/roles/vitamui/templates/api-gateway/application.yml.j2
> +              /archive-search-api/customers/**,
/tenants j'ai un doute aussi

2024-02-07 10:47 UTC, bbenaissa commented on deployment/roles/vitamui/templates/api-gateway/application.yml.j2
> +              /referential-api/customers/**,
pareil

2024-02-07 14:00 UTC, laedanrex approved these changes

2024-02-08 08:27 UTC, ebernard commented on deployment/roles/vitamui/templates/api-gateway/application.yml.j2
> +              /archive-search-api/customers/**,
J'ai juste fait /customers.

2024-02-09 09:10 UTC, Regzox approved these changes

2024-02-09 09:19 UTC, ebernard approved these changes

2024-02-09 09:24 UTC, merged