Story 12159  add archive unit bulk update api
ProgrammeVitam/vitam-ui pull request #1618
Opened 2024-01-15 15:44 UTC by Regzox

Ajoute l'API de mise à jour de masse des métadonnées descriptives pour les unités d'archives.

2024-01-15 16:17 UTC, vitam-devops commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx One – Scan Summary & Details** – [76fc3ff6\-8528\-4a78\-aff4\-17082ddc544d](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=76fc3ff6-8528-4a78-aff4-17082ddc544d&branch=story_12159__add_archive_unit_bulk_update_api)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2019-15599](https://devhub.checkmarx.com/cve-details/CVE-2019-15599)|Npm\-tree\-kill\-1\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/76fc3ff6-8528-4a78-aff4-17082ddc544d/vulnerabilities/CVE-2019-15599%3ANpm-tree-kill-1.2.1/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-28502](https://devhub.checkmarx.com/cve-details/CVE-2020-28502)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/76fc3ff6-8528-4a78-aff4-17082ddc544d/vulnerabilities/CVE-2020-28502%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-36048](https://devhub.checkmarx.com/cve-details/CVE-2020-36048)|Npm\-engine\.io\-3\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/76fc3ff6-8528-4a78-aff4-17082ddc544d/vulnerabilities/CVE-2020-36048%3ANpm-engine.io-3.2.1/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-36049](https://devhub.checkmarx.com/cve-details/CVE-2020-36049)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/76fc3ff6-8528-4a78-aff4-17082ddc544d/vulnerabilities/CVE-2020-36049%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-7660](https://devhub.checkmarx.com/cve-details/CVE-2020-7660)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/76fc3ff6-8528-4a78-aff4-17082ddc544d/vulnerabilities/CVE-2020-7660%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2020-7788](https://devhub.checkmarx.com/cve-details/CVE-2020-7788)|Npm\-ini\-1\.3\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/76fc3ff6-8528-4a78-aff4-17082ddc544d/vulnerabilities/CVE-2020-7788%3ANpm-ini-1.3.5/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2021-31597](https://devhub.checkmarx.com/cve-details/CVE-2021-31597)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/76fc3ff6-8528-4a78-aff4-17082ddc544d/vulnerabilities/CVE-2021-31597%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2022-2421](https://devhub.checkmarx.com/cve-details/CVE-2022-2421)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/76fc3ff6-8528-4a78-aff4-17082ddc544d/vulnerabilities/CVE-2022-2421%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2023-32695](https://devhub.checkmarx.com/cve-details/CVE-2023-32695)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/76fc3ff6-8528-4a78-aff4-17082ddc544d/vulnerabilities/CVE-2023-32695%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2019-16769](https://devhub.checkmarx.com/cve-details/CVE-2019-16769)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/76fc3ff6-8528-4a78-aff4-17082ddc544d/vulnerabilities/CVE-2019-16769%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-6\.10\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/76fc3ff6-8528-4a78-aff4-17082ddc544d/vulnerabilities/CVE-2020-15366%3ANpm-ajv-6.10.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-5\.5\.2|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/76fc3ff6-8528-4a78-aff4-17082ddc544d/vulnerabilities/CVE-2020-15366%3ANpm-ajv-5.5.2/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2020-28481](https://devhub.checkmarx.com/cve-details/CVE-2020-28481)|Npm\-socket\.io\-2\.1\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/76fc3ff6-8528-4a78-aff4-17082ddc544d/vulnerabilities/CVE-2020-28481%3ANpm-socket.io-2.1.1/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2020-7693](https://devhub.checkmarx.com/cve-details/CVE-2020-7693)|Npm\-sockjs\-0\.3\.19|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/76fc3ff6-8528-4a78-aff4-17082ddc544d/vulnerabilities/CVE-2020-7693%3ANpm-sockjs-0.3.19/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2021-23364](https://devhub.checkmarx.com/cve-details/CVE-2021-23364)|Npm\-browserslist\-4\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/76fc3ff6-8528-4a78-aff4-17082ddc544d/vulnerabilities/CVE-2021-23364%3ANpm-browserslist-4.5.5/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2021-23495](https://devhub.checkmarx.com/cve-details/CVE-2021-23495)|Npm\-karma\-4\.1\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/76fc3ff6-8528-4a78-aff4-17082ddc544d/vulnerabilities/CVE-2021-23495%3ANpm-karma-4.1.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2022-0437](https://devhub.checkmarx.com/cve-details/CVE-2022-0437)|Npm\-karma\-4\.1\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/76fc3ff6-8528-4a78-aff4-17082ddc544d/vulnerabilities/CVE-2022-0437%3ANpm-karma-4.1.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2022-21 [...]

2024-01-24 10:29 UTC, marob requested changes

2024-01-24 10:29 UTC, marob commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/converter/JsonPatchDtoToUpdateMultiQueryConverter.java
> +    }
La bonne pratique est plutôt l'injection par constructeur

2024-01-24 10:29 UTC, marob commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/converter/JsonPatchToSetActionConverter.java
> +            })
Pourrait être remplacé par :
```suggestion
.filter(patchCommand -> Arrays.asList(PatchOperation.ADD, PatchOperation.REPLACE).contains(patchCommand.getOp()))
```

2024-01-24 10:29 UTC, marob commented on api/api-archive-search/archive-search-external-client/src/main/java/fr/gouv/vitamui/archives/search/external/client/ArchiveUnitClientImpl.java
> +        log.info(uri.toString());
Supprimer ?

2024-01-24 10:29 UTC, marob commented on api/api-archive-search/archive-search-internal-client/src/main/java/fr/gouv/archive/internal/client/ArchiveUnitClientImpl.java
> +        log.info(uri.toString());
Supprimer ?

2024-01-24 10:29 UTC, marob commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/config/ConverterConfig.java
> +@ComponentScan("fr.gouv.vitamui.archives.search.common.dto.converter")
Pourquoi est-il nécessaire d'indiquer quels composants scanner ?

2024-01-24 10:40 UTC, Regzox commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/config/ConverterConfig.java
> +@ComponentScan("fr.gouv.vitamui.archives.search.common.dto.converter")
Les services que je veux instancier sont dans le module common et dans un package différent du module en cours...

Soit j'utilise le scan, soit j'écris du bloatcode avec 1k @Bean à chaque fois.

2024-01-24 10:52 UTC, Regzox commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/converter/JsonPatchToSetActionConverter.java
> +            })
J'ai remplacé par l'équivalence List.of

2024-01-24 14:32 UTC, marob commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/config/ConverterConfig.java
> +@ComponentScan("fr.gouv.vitamui.archives.search.common.dto.converter")
OK, je posais la question parcequ'on n'a fait ça nulle part pour le moment.

2024-01-26 09:51 UTC, marob approved these changes

2024-02-01 14:34 UTC, laedanrex approved these changes

2024-02-01 14:59 UTC, bbenaissa requested changes

2024-02-01 14:59 UTC, bbenaissa commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/converter/JsonPatchDtoToUpdateMultiQueryConverter.java
> +        } catch (InvalidCreateOperationException e) {
tu ne catches pas l'exception?

2024-02-01 14:59 UTC, bbenaissa commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/converter/JsonPatchToSetActionConverter.java
> +                log.error("{}", e);
Idem

2024-02-01 14:59 UTC, bbenaissa commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/converter/JsonPatchToUnsetActionConverter.java
> +            log.error("{}", e);
Idem

2024-02-01 14:59 UTC, bbenaissa commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/converter/UpdateArchiveUnitDtoToUpdateMultiQueryConverter.java
> +            log.error("{}", e);
idem

2024-02-01 14:59 UTC, bbenaissa commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/model/PatchOperation.java
> +@Getter
pas besoin de l'annotation?

2024-02-01 14:59 UTC, bbenaissa commented on api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService.java
que du restructuration d'imports,?

2024-02-01 14:59 UTC, bbenaissa commented on api/api-referential/referential-external-client/src/main/java/fr/gouv/vitamui/referential/external/client/UnitExternalRestClient.java
> +        } catch (JsonProcessingException e) {
est ce la bonne exception?

2024-02-02 10:54 UTC, Regzox commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/converter/JsonPatchDtoToUpdateMultiQueryConverter.java
> +        } catch (InvalidCreateOperationException e) {
J'ai ajouté des RuntimeException si jamais le parsing n'est pas possible càd jsonPatch sans commandes.

2024-02-02 10:54 UTC, Regzox commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/converter/JsonPatchToSetActionConverter.java
> +                log.error("{}", e);
J'ai ajouté des RuntimeException si jamais le parsing n'est pas possible càd jsonPatch sans commandes.

2024-02-02 10:54 UTC, Regzox commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/converter/JsonPatchToUnsetActionConverter.java
> +            log.error("{}", e);
J'ai ajouté des RuntimeException si jamais le parsing n'est pas possible càd jsonPatch sans commandes.

2024-02-02 10:54 UTC, Regzox commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/converter/UpdateArchiveUnitDtoToUpdateMultiQueryConverter.java
> +            log.error("{}", e);
J'ai ajouté des RuntimeException si jamais le parsing n'est pas possible càd jsonPatch sans commandes.

2024-02-02 10:56 UTC, Regzox commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/model/PatchOperation.java
> +@Getter
Retiré

2024-02-02 11:00 UTC, Regzox commented on api/api-referential/referential-external-client/src/main/java/fr/gouv/vitamui/referential/external/client/UnitExternalRestClient.java
> +        } catch (JsonProcessingException e) {
J'ai pas touché le code ici... C'est un effet de reformattage.

2024-02-02 11:22 UTC, Regzox commented on api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService.java
j'ai viré toutes les modifs de code style. Faudra faire un gros lint fix sur les éléments java un jour.

2024-02-02 14:27 UTC, bbenaissa approved these changes

2024-02-06 10:23 UTC, merged