Bugs #11893 fix(management-contract): forms states and layouts
ProgrammeVitam/vitam-ui pull request #1626
Opened 2024-01-23 14:57 UTC by Regzox

## Description

Corrige de multiple bugs en rapport avec les contrats de gestion.

2024-01-23 15:31 UTC, vitam-devops commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [a7406b72\-c3ed\-45e0\-a945\-ffa79df9e28a](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=a7406b72-c3ed-45e0-a945-ffa79df9e28a&branch=bugs_11893__create_management_contract)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2019-15599](https://devhub.checkmarx.com/cve-details/CVE-2019-15599)|Npm\-tree\-kill\-1\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a7406b72-c3ed-45e0-a945-ffa79df9e28a/vulnerabilities/CVE-2019-15599%3ANpm-tree-kill-1.2.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-28502](https://devhub.checkmarx.com/cve-details/CVE-2020-28502)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a7406b72-c3ed-45e0-a945-ffa79df9e28a/vulnerabilities/CVE-2020-28502%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-36048](https://devhub.checkmarx.com/cve-details/CVE-2020-36048)|Npm\-engine\.io\-3\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a7406b72-c3ed-45e0-a945-ffa79df9e28a/vulnerabilities/CVE-2020-36048%3ANpm-engine.io-3.2.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-36049](https://devhub.checkmarx.com/cve-details/CVE-2020-36049)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a7406b72-c3ed-45e0-a945-ffa79df9e28a/vulnerabilities/CVE-2020-36049%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-7660](https://devhub.checkmarx.com/cve-details/CVE-2020-7660)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a7406b72-c3ed-45e0-a945-ffa79df9e28a/vulnerabilities/CVE-2020-7660%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-7788](https://devhub.checkmarx.com/cve-details/CVE-2020-7788)|Npm\-ini\-1\.3\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a7406b72-c3ed-45e0-a945-ffa79df9e28a/vulnerabilities/CVE-2020-7788%3ANpm-ini-1.3.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2021-31597](https://devhub.checkmarx.com/cve-details/CVE-2021-31597)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a7406b72-c3ed-45e0-a945-ffa79df9e28a/vulnerabilities/CVE-2021-31597%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2022-2421](https://devhub.checkmarx.com/cve-details/CVE-2022-2421)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a7406b72-c3ed-45e0-a945-ffa79df9e28a/vulnerabilities/CVE-2022-2421%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2023-32695](https://devhub.checkmarx.com/cve-details/CVE-2023-32695)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a7406b72-c3ed-45e0-a945-ffa79df9e28a/vulnerabilities/CVE-2023-32695%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2019-16769](https://devhub.checkmarx.com/cve-details/CVE-2019-16769)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a7406b72-c3ed-45e0-a945-ffa79df9e28a/vulnerabilities/CVE-2019-16769%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-6\.10\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a7406b72-c3ed-45e0-a945-ffa79df9e28a/vulnerabilities/CVE-2020-15366%3ANpm-ajv-6.10.0/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-5\.5\.2|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a7406b72-c3ed-45e0-a945-ffa79df9e28a/vulnerabilities/CVE-2020-15366%3ANpm-ajv-5.5.2/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-28481](https://devhub.checkmarx.com/cve-details/CVE-2020-28481)|Npm\-socket\.io\-2\.1\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a7406b72-c3ed-45e0-a945-ffa79df9e28a/vulnerabilities/CVE-2020-28481%3ANpm-socket.io-2.1.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-7693](https://devhub.checkmarx.com/cve-details/CVE-2020-7693)|Npm\-sockjs\-0\.3\.19|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a7406b72-c3ed-45e0-a945-ffa79df9e28a/vulnerabilities/CVE-2020-7693%3ANpm-sockjs-0.3.19/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2021-23364](https://devhub.checkmarx.com/cve-details/CVE-2021-23364)|Npm\-browserslist\-4\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a7406b72-c3ed-45e0-a945-ffa79df9e28a/vulnerabilities/CVE-2021-23364%3ANpm-browserslist-4.5.5/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2021-23495](https://devhub.checkmarx.com/cve-details/CVE-2021-23495)|Npm\-karma\-4\.1\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a7406b72-c3ed-45e0-a945-ffa79df9e28a/vulnerabilities/CVE-2021-23495%3ANpm-karma-4.1.0/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2022-0437](https://devhub.checkmarx.com/cve-details/CVE-2022-0437)|Npm\-karma\-4\.1\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a7406b72-c3ed-45e0-a945-ffa79df9e28a/vulnerabilities/CVE-2022-0437%3ANpm-karma-4.1.0/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2022-21704](https://devhub.checkmarx.com/cve-details/CVE-2022-21704)|Npm\-log4js\-4\.5\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a7406b72-c3ed-45e0-a945-ffa79df9e28a/vulnerabilities/CVE-2022-21704%3ANpm-log4js-4.5.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2022-41940](https://devhub.checkmarx.com/cve-details/CVE-2022-41940)|Npm\-engine\.io\-3\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a7406b72-c3ed-45e0-a945-ffa79df9e28a/vulnerabilities/CVE-2022-41940%3ANpm-engine.io-3.2.1/vulnerabilityDetails)

### Fixed Issues
Severity|Issue|Source File / Package
---|---|---
![H [...]

2024-01-24 17:33 UTC, marob commented
@Regzox Le bouton "Retour" ne respecte pas le design du Figma

2024-01-24 18:07 UTC, marob commented
@Regzox Le découpage en persistent-identifier-policies-form me semble douteux :
- utilisation de `*ngFor` sur `getPersistentIdentifiers().controls` alors qu'il n 'y a qu'un élément dans la liste ?
- `[form]="persistentIdentifier"` : persistentIdentifier ne semble pas être du bon type
- on ne comprends pas quels sont les champs du form

2024-01-24 18:08 UTC, marob requested changes
Je n'ai pas eu le temps de faire une review exhaustive.

2024-01-24 18:08 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.scss
> +    color: var(--vitamui-primary);
Le (i) devrait être bleu et non violet d'après le Figma

2024-01-24 18:08 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/components/persistent-identifier-policies-form/persistent-identifier-policies-form.component.html
> +    <div class="r-header row dark-background" [ngClass]="{ opened: objectUsagePoliciesToggle }" (click)="toggle($event)">
La classe "opened" semble être activée dès la sélection de ARK comme type d'identifiant

2024-01-24 18:08 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/components/persistent-identifier-policies-form/persistent-identifier-policies-form.component.html
> +        <h5 class="primary title">Positionnement des identifiants</h5>
Il manque l'i18n

2024-01-24 18:08 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/components/persistent-identifier-policies-form/persistent-identifier-policies-form.component.html
> +          placeholder="{{ 'CONTRACT_MANAGEMENT.FORM_UPDATE.NAMING_AUTORITY' | translate }}"
AUTORITY -> AUTHORITY

2024-01-24 18:08 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/components/persistent-identifier-policies-form/persistent-identifier-policies-form.component.html
> +          placeholder="{{ 'CONTRACT_MANAGEMENT.FORM_UPDATE.NAMING_AUTORITY' | translate }}"
Si on focus ce champ, il passe en error et je ne trouve pas de moyen de ne pas avoir d'erreur (quelle est l'erreur ?)

2024-01-25 10:16 UTC, Regzox commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/components/persistent-identifier-policies-form/persistent-identifier-policies-form.component.html
> +          placeholder="{{ 'CONTRACT_MANAGEMENT.FORM_UPDATE.NAMING_AUTORITY' | translate }}"
J'ai ajouté l'erreur au composant.

2024-01-25 10:17 UTC, Regzox commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/components/persistent-identifier-policies-form/persistent-identifier-policies-form.component.html
> +    <div class="r-header row dark-background" [ngClass]="{ opened: objectUsagePoliciesToggle }" (click)="toggle($event)">
J'ai set à false par défaut et je synchronise l'attribut avec la valeur du formulaire dans ngChange.

2024-01-25 10:19 UTC, bbenaissa requested changes

2024-01-25 10:19 UTC, bbenaissa commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.ts
> +      status: [true],
status est de type String ?

2024-01-25 10:19 UTC, bbenaissa commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.ts
> +  getPersistentIdentifiers(): FormArray {
Je pense que le nom est mal choisi, puisqu'on ne parle pas de list d'identifiants mais une liste d'usages

2024-01-26 10:35 UTC, Regzox commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.scss
> +    color: var(--vitamui-primary);
Il me semble qu'il y a une inversion des couleurs pirmaire et secondaire sur vitam en dev.
C'est un sujet qu'il faudra traiter de manière générale plus tard.

2024-01-26 10:49 UTC, marob requested changes
Il y a des erreurs TSLint

2024-01-26 10:49 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.html
> +                minlength="5"
Aucun message d'erreur affiché si la taille min n'est pas respectée

2024-01-26 10:49 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/management-contract/components/create-persistent-identifier-policy-form/create-persistent-identifier-policy-form.component.html
> +        <h5 class="primary title">{{ 'CONTRACT_MANAGEMENT.FORM_UPDATE.POSITIONING_TITLE' | translate }}</h5>
D'après l'US, ce champ semble être obligatoire. Or il est possible de soumettre le formulaire sans cocher aucune des cases :

> "Positionnement des identifiants" (obligatoire)

2024-01-26 10:49 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-preview/management-contract-information-tab/management-contract-information-tab.component.ts
> +      }),
Si l'on ne change que le nom du contrat ou sa description, la date d'activation ou désactivation est mise à jour avec la date courante ?

2024-01-26 10:49 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.ts
> +  getpersistentIdentifierPolicies(): FormArray {
```suggestion
  getPersistentIdentifierPolicies(): FormArray {
```

2024-01-26 10:49 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-preview/management-contract-identification-tab/management-contract-identification-tab.component.ts
> +  getpersistentIdentifierPolicies(): FormArray {
```suggestion
  getPersistentIdentifierPolicies(): FormArray {
```

2024-01-26 13:46 UTC, Regzox commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.html
> +                minlength="5"
En effet, il semblerait qu'une contrainte sur le formulaire existe bien.

Par contre, plusieurs éléments perturbants:
* Le composant vitam-common-input ne semble rien n'avoir à faire de minlength (pas pris en charge dans l'impl)
* Le formulaire de création contient cette contrainte unique, pas la modification et le système ne rejète pas la un update du name plus petite que la contrainte initiale (je doute de la pertinence de la contrainte surtout pour les noms des contrats)

Sinon, j'ai migré les contraintes dans du composant input sur le form et ajouté des messages pour ces erreurs de validation.

2024-01-26 14:01 UTC, Regzox commented on ui/ui-frontend/projects/referential/src/app/management-contract/components/create-persistent-identifier-policy-form/create-persistent-identifier-policy-form.component.html
> +        <h5 class="primary title">{{ 'CONTRACT_MANAGEMENT.FORM_UPDATE.POSITIONING_TITLE' | translate }}</h5>
En effet, si cette contrainte n'est pas possitionnée on a une règle de gestion qui ne fait rien... Bien vu.

2024-01-26 15:04 UTC, Regzox commented on ui/ui-frontend/projects/referential/src/app/management-contract/components/create-persistent-identifier-policy-form/create-persistent-identifier-policy-form.component.html
> +        <h5 class="primary title">{{ 'CONTRACT_MANAGEMENT.FORM_UPDATE.POSITIONING_TITLE' | translate }}</h5>
J'ai ajouté un validateur avec message pour garantir cette contrainte sur les formulaires.

Après, sur le formulaire d'update cela permettait de rendre inopérante une persistentIdentifierPolicy sans la supprimer de la liste des règles.

2024-01-26 15:21 UTC, Regzox commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-preview/management-contract-information-tab/management-contract-information-tab.component.ts
> +      }),
Initialement oui, le diff est fait pour pouvoir sélectionner les champs qui ont changé de valeur.

Mais la conversion de status string -> boolean n'était pas bien gérée donc il y avait un changement de détecté à chaque fois donc un update de dates.

2024-01-26 15:32 UTC, bbenaissa approved these changes

2024-01-26 15:32 UTC, bbenaissa commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.ts
> +      managementContract.activationDate = timestamp;
Check the time zone issue

2024-01-26 16:03 UTC, marob requested changes

2024-01-26 16:03 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.html
> -                required
Actuellement, il faut garder le required dans le template sinon on n'a plus l'`*` dans l'UI...

2024-01-26 16:03 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.html
> -                required
Actuellement, il faut garder le required dans le template sinon on n'a plus l'`*` dans l'UI...

2024-01-26 16:11 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/management-contract/components/create-persistent-identifier-policy-form/create-persistent-identifier-policy-form.component.html
> +        <h5 class="primary title">{{ 'CONTRACT_MANAGEMENT.FORM_UPDATE.POSITIONING_TITLE' | translate }}</h5>
Ça semble OK sur la popin de création, mais en modification dans la sidenav, si le formulaire est KO avec le choix "ARK" (pas de positionnement choisi ou autorité KO) puis qu'on passe en "Aucun", il n'est pas possible de soumettre le formulaire. Les erreurs des éléments "cachés" sont prises en compte pour déterminer si le formulaire peut être soumis ou non.

2024-01-26 16:15 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-preview/management-contract-information-tab/management-contract-information-tab.component.ts
> +      }),
Je ne suis pas certain de bien comprendre. C'est donc normal que lorsqu'on modifie le nom du contrat ou sa description, le payload de la requête de path contiennent également une nouvelle date d'activation/désactivation qui corresponde à Date.now() ?

2024-01-29 11:28 UTC, Regzox commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-preview/management-contract-information-tab/management-contract-information-tab.component.ts
> +      }),
Je ne pense pas, si le status ne change pas, pas de recalcul de dates... La manière de faire n'est pas clean à mon avis, car on laisse que la possibilité de toggle le state à l'utilisateur... La gestion des dates devrait se faire en backend si le user n'influe pas dirrectement dessus.

Pour l'instant on laisse comme ça. J'ai cette fois normalement effectivement empéché des nouvelles dates si le toggle n'a pas changé d'état.

2024-01-29 16:27 UTC, marob commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/ManagementDto.java
> +    private Boolean needAuthorization;
A quoi sert cet attribut ?

2024-01-29 16:32 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/management-contract/components/create-persistent-identifier-policy-form/create-persistent-identifier-policy-form.component.html
> +        <h5 class="primary title">{{ 'CONTRACT_MANAGEMENT.FORM_UPDATE.POSITIONING_TITLE' | translate }}</h5>
@Regzox Il me semble que ce bug est toujours présent.

2024-01-30 15:29 UTC, Regzox commented on ui/ui-frontend/projects/referential/src/app/management-contract/components/create-persistent-identifier-policy-form/create-persistent-identifier-policy-form.component.html
> +        <h5 class="primary title">{{ 'CONTRACT_MANAGEMENT.FORM_UPDATE.POSITIONING_TITLE' | translate }}</h5>
En effet, vu avec les PO, dans tous les pour passer de ARK vers Aucun on a pas les API qui nous permettent de faire ça.
On y ajoutera cette tâche de correction du formulaire d'update quand on ajoutera la possibilité des remove PATCH sur les management contracts.

2024-01-30 15:54 UTC, Regzox commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.ts
> +      managementContract.activationDate = timestamp;
Je ne sais pas, c'est une refacto d'un comportement déjà existant...

2024-01-30 15:54 UTC, Regzox commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.ts
> +      managementContract.activationDate = timestamp;
2024-01-30T15:48:38.188Z

2024-01-30 15:54 UTC, bbenaissa approved these changes

2024-01-30 16:10 UTC, marob approved these changes

2024-02-01 14:43 UTC, Regzox commented on ui/ui-frontend/projects/referential/src/app/management-contract/components/create-persistent-identifier-policy-form/create-persistent-identifier-policy-form.component.html
> +        <h5 class="primary title">{{ 'CONTRACT_MANAGEMENT.FORM_UPDATE.POSITIONING_TITLE' | translate }}</h5>
Du coup, un peu de révision a été demandé.
J'ai externalisé la gestion du choice et ajouté un message comme quoi la feature aucun n'est pas disponible en update (update sur l'API nécessaire).

2024-02-05 16:05 UTC, merged