fix(archive-search): find units by persistent identifier test
ProgrammeVitam/vitam-ui pull request #1630
Opened 2024-01-29 14:01 UTC by Regzox

2024-01-29 14:35 UTC, vitam-devops commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [dbc43cd5\-4bdb\-4b31\-8e24\-18e0b8daf082](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=dbc43cd5-4bdb-4b31-8e24-18e0b8daf082&branch=hotfix%2Fpersistent-id)

### Fixed Issues
Severity|Issue|Source File / Package
---|---|---
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2024-22233](https://devhub.checkmarx.com/cve-details/CVE-2024-22233)|Maven\-org\.springframework:spring\-core\-5\.3\.22
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2024-22233](https://devhub.checkmarx.com/cve-details/CVE-2024-22233)|Maven\-org\.springframework:spring\-core\-5\.3\.21
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2024-22233](https://devhub.checkmarx.com/cve-details/CVE-2024-22233)|Maven\-org\.springframework:spring\-core\-5\.3\.20
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2024-22233](https://devhub.checkmarx.com/cve-details/CVE-2024-22233)|Maven\-org\.springframework:spring\-core\-5\.3\.19
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2024-22233](https://devhub.checkmarx.com/cve-details/CVE-2024-22233)|Maven\-org\.springframework:spring\-core\-5\.3\.18
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2024-22233](https://devhub.checkmarx.com/cve-details/CVE-2024-22233)|Maven\-org\.springframework:spring\-core\-5\.3\.11
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2024-22233](https://devhub.checkmarx.com/cve-details/CVE-2024-22233)|Maven\-org\.springframework:spring\-core\-5\.2\.9\.RELEASE

2024-01-29 17:24 UTC, marob requested changes

2024-01-29 17:24 UTC, marob commented on api/api-archive-search/archive-search-external-client/src/test/java/fr/gouv/vitamui/archives/search/external/client/ArchiveSearchExternalRestClientTest.java
> +        verify(restTemplate).exchange(eq(uri), eq(HttpMethod.GET), any(HttpEntity.class), eq(PersistentIdentifierResponseDto.class));
Est-ce lié au fix ?

2024-01-29 17:24 UTC, marob commented on api/api-archive-search/archive-search-internal-client/src/test/java/fr/gouv/archive/internal/client/ArchiveInternalRestClientTest.java
> +        verify(restTemplate).exchange(eq(uri), eq(HttpMethod.GET), any(HttpEntity.class), eq(PersistentIdentifierResponseDto.class));
Est-ce lié au fix ?

2024-01-29 17:24 UTC, marob commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/ManagementDto.java
> +    private Boolean needAuthorization;
A quoi sert cet attribut ?

2024-01-29 17:24 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.spec.ts
> +  //   };
Supprimer le code commenté

2024-01-29 17:24 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.spec.ts
> +  //   component.projectForm.patchValue(form);
Supprimer le code commenté

2024-01-29 17:24 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.spec.ts
> +  //   component.validateAndCreateProject();
Supprimer le code commenté

2024-01-29 17:24 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.spec.ts
> +  // });
Supprimer le code commenté

2024-01-29 17:24 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.spec.ts
> +  // });
Supprimer le code commenté

2024-01-30 11:26 UTC, marob approved these changes

2024-01-30 13:39 UTC, bbenaissa approved these changes

2024-01-30 13:42 UTC, merged