Story #11964: Migrate Collect to API Gateway
ProgrammeVitam/vitam-ui pull request #1651
Opened 2024-02-14 15:38 UTC by ebernard

2024-02-16 15:29 UTC, bbenaissa commented on cas/cas-server/pom.xml
>              <plugin>
pourquoi ce changement? il y a une raison particulière?

2024-02-16 15:32 UTC, ebernard commented on cas/cas-server/pom.xml
>              <plugin>
En gros c'est une mise à jour du plugin libsass-maven-plugin car cette vieille version ne fonctionne pas sous Mac. La nouvelle version fonctionne correctement. Je l'ai mis dans un commit à part, si ça ne va pas je l'enlève de la PR.

2024-02-16 15:51 UTC, bbenaissa approved these changes

2024-02-19 12:42 UTC, marob requested changes

2024-02-19 12:42 UTC, marob commented on ui/ui-frontend/package.json
> +    "copy-scss:vitamui-library": "mkdir -p dist/ && cp -a ./projects/vitamui-library/src/sass ./dist/",
Le commit indique "Replace cp-cli with cpy-cli", mais cpy-cli n'est pas utilisé.

2024-02-19 12:42 UTC, marob commented on api/api-gateway/src/main/resources/application-dev.yml
> +              /pastis-api/profile,
Est-ce normal d'avoir du Pastis dans une MR collecte ?

2024-02-19 12:42 UTC, marob commented on api/api-gateway/src/main/resources/application-dev.yml
> +            - RewritePath=/pastis-api/profile,/referential/v1/profile
Est-ce normal d'avoir du Pastis dans une MR collecte ?

2024-02-19 12:42 UTC, marob commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectObjectGroupExternalController.java
> +        final @RequestParam(value = "version", required = false) Integer version)
Veut-on vraiment rendre ces paramètre non obligatoires ?

2024-02-19 12:42 UTC, marob commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectObjectGroupExternalController.java
> +        SanityChecker.checkSecureParameter(objectId);
Avant on vérifiait l'id (de l'unit), maintenant l'objectId (du GOT). Normal ?

2024-02-19 12:42 UTC, marob commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectObjectGroupExternalController.java
> -        ParameterChecker.checkParameter(MANDATORY_VERSION, version);
Les constantes n'ont pas été supprimées

2024-02-19 12:42 UTC, marob commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/TransactionArchiveUnitExternalController.java
> +    public VitamUIArchiveUnitResponseDto searchArchiveUnits(final @PathVariable("transactionId") String transactionId,
Import correspondant non supprimé

2024-02-19 12:42 UTC, marob commented on api/api-collect/collect-external/src/test/java/fr/gouv/vitamui/collect/external/server/rest/ProjectArchiveUnitExternalControllerTest.java
> +        VitamUIArchiveUnitResponseDto expectedResponse = new VitamUIArchiveUnitResponseDto();
Import non supprimé

2024-02-19 12:42 UTC, marob commented on api/api-collect/collect-external-client/src/main/java/fr/gouv/vitamui/collect/external/client/SearchCriteriaHistoryExternalRestClient.java
> +        final UriComponentsBuilder uriBuilder = UriComponentsBuilder.fromHttpUrl(getUrl());
Import non supprimé

2024-02-19 12:42 UTC, marob commented on deployment/roles/vitamui/templates/api-gateway/application.yml.j2
> +              /pastis-api/profile/**,
Est-ce normal d'avoir du Pastis ?

2024-02-19 12:44 UTC, ebernard commented on ui/ui-frontend/package.json
> +    "copy-scss:vitamui-library": "mkdir -p dist/ && cp -a ./projects/vitamui-library/src/sass ./dist/",
Oui, j'avais fait ça initialement, mais on a décidé que ça servait à rien et je n'ai pas changé le message de commit. Je fais ça.

2024-02-19 12:45 UTC, ebernard commented on api/api-gateway/src/main/resources/application-dev.yml
> +              /pastis-api/profile,
Ce sont des trucs qui ne fonctionnaient pas correctement et que j'ai corrigé au passage.

2024-02-19 12:45 UTC, ebernard commented on api/api-gateway/src/main/resources/application-dev.yml
> +            - RewritePath=/pastis-api/profile,/referential/v1/profile
Idem

2024-02-19 12:46 UTC, ebernard commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectObjectGroupExternalController.java
> +        final @RequestParam(value = "version", required = false) Integer version)
C'est fait comme ça côté ui-collect. J'ai dû bouger la logique à cet endroit.

2024-02-19 12:50 UTC, ebernard commented on deployment/roles/vitamui/templates/api-gateway/application.yml.j2
> +              /pastis-api/profile/**,
Idem

2024-02-19 12:54 UTC, ebernard commented on ui/ui-frontend/package.json
> +    "copy-scss:vitamui-library": "mkdir -p dist/ && cp -a ./projects/vitamui-library/src/sass ./dist/",
Message de commit changé.

2024-02-19 12:56 UTC, ebernard commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectObjectGroupExternalController.java
> +        SanityChecker.checkSecureParameter(objectId);
J'ai ajouté le check sur id aussi.

2024-02-19 14:00 UTC, marob commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectObjectGroupExternalController.java
> +        final @RequestParam(value = "version", required = false) Integer version)
J'ai quand même l'impression qu'il y a un micmac entre `id` et `objectId`. Je ne vois pas la même chose côté archive search (il n'y a qu'un seul id et pas 2).

2024-02-19 15:15 UTC, ebernard commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectObjectGroupExternalController.java
> +        final @RequestParam(value = "version", required = false) Integer version)
Je n'ai fait que reprendre le code, mais en effet il y a quelque chose qui cloche (clochait ?).

Côté Archive Search on ne fait que passer l'unit id, qui est utilisé pour un appel à findObjectById et pour télécharger le binaire.
Côté collect, l'object Id sert uniquement pour l'appel à findObjectById pour obtenir les infos du GOT à partir de son id.

A priori les deux findObjectById ne sont pas les mêmes...

Je suis d'accord que ce n'est pas cohérent, mais j'ai repris la fonctionnalité telle quelle...

2024-02-19 15:17 UTC, marob commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectObjectGroupExternalController.java
> +        final @RequestParam(value = "version", required = false) Integer version)
@bbenaissa Help ? :smile:

2024-02-20 15:11 UTC, ebernard commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectObjectGroupExternalController.java
> +        final @RequestParam(value = "version", required = false) Integer version)
Suite à la conversation d'hier, je resolve la discussion...

2024-02-20 15:12 UTC, merged