Story 12069  update archive unit descriptive metadata
ProgrammeVitam/vitam-ui pull request #1655
Opened 2024-02-23 16:56 UTC by Regzox

## Description

Ajout formulaire de mise à jour dynamique pour la mise à jour d'unité d'archive.

2024-02-23 17:31 UTC, vitam-devops commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [303ae57c\-8fc9\-4563\-8eb7\-61d88faa2feb](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=303ae57c-8fc9-4563-8eb7-61d88faa2feb&branch=story_12069__update_archive_unit_descriptive_metadata)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2019-15599](https://devhub.checkmarx.com/cve-details/CVE-2019-15599)|Npm\-tree\-kill\-1\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/303ae57c-8fc9-4563-8eb7-61d88faa2feb/vulnerabilities/CVE-2019-15599%3ANpm-tree-kill-1.2.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-28502](https://devhub.checkmarx.com/cve-details/CVE-2020-28502)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/303ae57c-8fc9-4563-8eb7-61d88faa2feb/vulnerabilities/CVE-2020-28502%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-36048](https://devhub.checkmarx.com/cve-details/CVE-2020-36048)|Npm\-engine\.io\-3\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/303ae57c-8fc9-4563-8eb7-61d88faa2feb/vulnerabilities/CVE-2020-36048%3ANpm-engine.io-3.2.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-36049](https://devhub.checkmarx.com/cve-details/CVE-2020-36049)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/303ae57c-8fc9-4563-8eb7-61d88faa2feb/vulnerabilities/CVE-2020-36049%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-7660](https://devhub.checkmarx.com/cve-details/CVE-2020-7660)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/303ae57c-8fc9-4563-8eb7-61d88faa2feb/vulnerabilities/CVE-2020-7660%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-7788](https://devhub.checkmarx.com/cve-details/CVE-2020-7788)|Npm\-ini\-1\.3\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/303ae57c-8fc9-4563-8eb7-61d88faa2feb/vulnerabilities/CVE-2020-7788%3ANpm-ini-1.3.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2021-31597](https://devhub.checkmarx.com/cve-details/CVE-2021-31597)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/303ae57c-8fc9-4563-8eb7-61d88faa2feb/vulnerabilities/CVE-2021-31597%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2022-2421](https://devhub.checkmarx.com/cve-details/CVE-2022-2421)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/303ae57c-8fc9-4563-8eb7-61d88faa2feb/vulnerabilities/CVE-2022-2421%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2023-32695](https://devhub.checkmarx.com/cve-details/CVE-2023-32695)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/303ae57c-8fc9-4563-8eb7-61d88faa2feb/vulnerabilities/CVE-2023-32695%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2023-45860](https://devhub.checkmarx.com/cve-details/CVE-2023-45860)|Maven\-com\.hazelcast:hazelcast\-5\.1\.3|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/303ae57c-8fc9-4563-8eb7-61d88faa2feb/vulnerabilities/CVE-2023-45860%3AMaven-com.hazelcast%3Ahazelcast-5.1.3/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2023-45860](https://devhub.checkmarx.com/cve-details/CVE-2023-45860)|Maven\-com\.hazelcast:hazelcast\-sql\-5\.1\.3|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/303ae57c-8fc9-4563-8eb7-61d88faa2feb/vulnerabilities/CVE-2023-45860%3AMaven-com.hazelcast%3Ahazelcast-sql-5.1.3/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2019-16769](https://devhub.checkmarx.com/cve-details/CVE-2019-16769)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/303ae57c-8fc9-4563-8eb7-61d88faa2feb/vulnerabilities/CVE-2019-16769%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-6\.10\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/303ae57c-8fc9-4563-8eb7-61d88faa2feb/vulnerabilities/CVE-2020-15366%3ANpm-ajv-6.10.0/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-5\.5\.2|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/303ae57c-8fc9-4563-8eb7-61d88faa2feb/vulnerabilities/CVE-2020-15366%3ANpm-ajv-5.5.2/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-28481](https://devhub.checkmarx.com/cve-details/CVE-2020-28481)|Npm\-socket\.io\-2\.1\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/303ae57c-8fc9-4563-8eb7-61d88faa2feb/vulnerabilities/CVE-2020-28481%3ANpm-socket.io-2.1.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-7693](https://devhub.checkmarx.com/cve-details/CVE-2020-7693)|Npm\-sockjs\-0\.3\.19|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/303ae57c-8fc9-4563-8eb7-61d88faa2feb/vulnerabilities/CVE-2020-7693%3ANpm-sockjs-0.3.19/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2021-23364](https://devhub.checkmarx.com/cve-details/CVE-2021-23364)|Npm\-browserslist\-4\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/303ae57c-8fc9-4563-8eb7-61d88faa2feb/vulnerabilities/CVE-2021-23364%3ANpm-browserslist-4.5.5/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2021-23495](https://devhub.checkmarx.com/cve-details/CVE-2021-23495)|Npm\-karma\-4\.1\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/303ae57c-8fc9-4563-8eb7-61d88faa2feb/vulnerabilities/CVE-2021-23495%3ANpm-karma-4.1.0/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2022-0437](https://devhub.checkmarx.com/cve-details/CVE-2022-0437)|Npm\-karma\-4\.1\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/303ae57c-8fc9-4563-8eb7-61d88faa2feb/vulnerabilities/CVE-2022-0437%3ANpm-karma-4.1.0/v [...]

2024-03-04 09:51 UTC, marob commented
Le texte devrait être "Modifier les métadonnées descriptives"

![image](https://github.com/ProgrammeVitam/vitam-ui/assets/3486231/4f774101-9d96-4bee-b159-b39e9753a393)

2024-03-04 09:58 UTC, marob commented
Est-ce normal d'avoir un tooltip avec du JSON au rollover des titres ?

![image](https://github.com/ProgrammeVitam/vitam-ui/assets/3486231/195d6886-5692-4662-a6f1-449fb9140c8e)

2024-03-04 10:05 UTC, marob commented
Problème d'espaces sur le bandeau sticky

![image](https://github.com/ProgrammeVitam/vitam-ui/assets/3486231/4354bf94-f46b-44c6-b556-008ff1f576db)

2024-03-04 10:09 UTC, marob commented
Il manque le "Services producteurs liés à l’unité archivistique" qui est présent en mode consultation.
Aussi, ces champs devraient être non modifiables et grisés (ce n'est pas le cas).
Il y a également une inconsistance sur le nommage des champs entre l'US/Figma et l'application Vitam UI.

![image](https://github.com/ProgrammeVitam/vitam-ui/assets/3486231/e22e5095-d3cd-4dcb-a2a8-7e9703f98eb8)

2024-03-04 10:11 UTC, marob commented
Le "Niveau de description", présent en consultation, est manquant.

![image](https://github.com/ProgrammeVitam/vitam-ui/assets/3486231/dcc92086-46a6-4479-a0ff-fe405be93679)

2024-03-04 10:19 UTC, marob commented
- je ne trouve pas de bloc "PersistentIdentifier"
- le bouton "+" devrait être un "..." vertical avec choix et ne correspond pas au Figma (couleur, design, ...)
- le gris utilisé pour les composant vides devrait être différent du gris des composants non vides et repliés

![image](https://github.com/ProgrammeVitam/vitam-ui/assets/3486231/3aefdbec-4709-4f70-a90e-36c16450c03a)

2024-03-04 10:43 UTC, marob commented
Lorsqu'aucune modification n'a été effectuée, le bouton enregistrer, bien que non cliquable, semble l'être. Son style n'est pas cohérent. Par ailleurs, le bouton annuler ne devrait pas ouvrir de popin si aucune modification n'a été effectuée.
![image](https://github.com/ProgrammeVitam/vitam-ui/assets/3486231/75c9bd3a-574c-4ad3-b59a-9b6f12ca3563)

Lorsqu'une modification a été effectuée, le bouton enregistrer est bien cliquable, mais son style n'est pas cohérent.
![image](https://github.com/ProgrammeVitam/vitam-ui/assets/3486231/2d21ecde-d49e-42f6-a764-36fffb87aeea)

Lorsque les modifications sont enregistrées, l’onglet Description ne repasse pas en mode affichage.

2024-03-04 10:48 UTC, marob commented
La popin de confirmation d'une annulation de modification n'est pas déclenchée dans les cas suivants :
- clic sur un autre onglet
- clic sur la croix permettant de fermer le panneau latéral
- clic n'importe où ailleurs que dans le panneau latéral

À noter qu'une fois la popin fermée (confirmation d'annulation ou enregistrement), l'action initiale doit être déclenchée (aller sur l'onglet/fermer le panneau/charger une autre Unit/...)

2024-03-04 16:55 UTC, marob requested changes

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/archive/components/archive-unit-editor/components/editor-banner/editor-banner.component.ts
> +  @Input() title: string = 'MODE EDITION (MODIFICATION ET COMPLETION) - VERSION 2.2 SEDA';
Ne devrait-on pas utiliser de l'i18n ? Aussi, il manque un accent aigu sur "COMPLÉTION"

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.html
> +  [ngStyle]="{ display: !editMode ? 'block' : 'none' }"
Pourquoi utiliser display block/none plutôt qu'un if/else ?

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.html
> +    <button (click)="onSave()" [disabled]="editObject?.control?.pristine" class="btn primary save">
Pas le bon style ?

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.ts
> +    this.subscriptions.add(
Ne pas afficher la popin dans le cas pristine

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.scss
> +}
On n'a pas de bouton correspondant dans le Design System ?

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.ts
> +  tenantId: number;
Le tenantId peut être privé. On peut également le retirer des attributs de classe je pense. On doit pouvoir extraire le tenantId via ActivatedRouteSnapshot directement dans handleUpdateSuccess

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/archive/components/archive-unit-editor/components/editor-banner/editor-banner.component.ts
> +  @Input() title: string = 'MODE EDITION (MODIFICATION ET COMPLETION) - VERSION 2.2 SEDA';
```suggestion
  @Input() title: string = 'MODE EDITION (MODIFICATION ET COMPLÉTION) - VERSION 2.2 SEDA';
```
Et il manque l'i18n

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/archive/components/archive-unit-editor/components/editor-banner/editor-banner.component.scss
> +}
On ne devrait pas avoir besoin d'utiliser ce style. Il faudrait pouvoir utiliser les classes "text caption bold white short-spaced" (mais white et short-spaced n'existent pas) et ne garder que l'align-items & left

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/archive/components/archive-unit-editor/archive-unit-editor.component.ts
> +export class ArchiveUnitEditorComponent implements OnInit, OnChanges, OnDestroy {
Fichier spec vide => à supprimer ou écrire une spec ?

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/archive/components/archive-unit-editor/archive-unit-editor.component.ts
> +  @Input() template: DisplayRule[] = [
À mettre en commun avec archive-unit-viewer.component.ts

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/archive/components/archive-unit-editor/archive-unit-editor.service.ts
> +  template$ = this.template.asObservable();
```suggestion
  editObject$ = this.editObject.asObservable();
```

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/archive/components/archive-unit-editor/archive-unit-editor.service.ts
> +              'SubmissionAgency.OrganizationDescriptiveMetadata', // FIXME: What should we do with free extension points
Doit-on garder ces FIXME ?

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/archive/components/archive-unit-editor/archive-unit-editor.service.ts
> +      this.logger.info(this, `EditObject with path '${editObject.path}' havn't DisplayRule`);
```suggestion
      this.logger.info(this, `EditObject with path '${editObject.path}' have no DisplayRule`);
```

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/archive/components/archive-unit-editor/archive-unit-editor.service.ts
> +  private collaspeAll(editObject: EditObject): void {
```suggestion
  private collapseAll(editObject: EditObject): void {
```

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/archive/components/archive-unit-editor/archive-unit-editor.service.ts
> +  private uncollapse(path: string, editObject: EditObject): void {
```suggestion
  private expand(path: string, editObject: EditObject): void {
```

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/archive/components/archive-unit-editor/archive-unit-editor.service.ts
> +        label: 'Autres métadonnées',
i18n

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/components/group-editor/group-editor.component.scss
> +:host {
Dupliqué de group.component.scss (qui a changé dans ma MR).
Il faudrait mutualiser et s'assurer qu'on diverge pas entre les 2 MR.

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/components/list-editor/list-editor.component.scss
> +:host {
Dupliqué de list.component.scss (qui a changé dans ma MR).
Il faudrait mutualiser et s'assurer qu'on diverge pas entre les 2 MR.

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/components/group-editor/group-editor.component.ts
> +  template: `
Je ne suis pas fan des templates dans le code. D'autant moins quand ils font plus de quelques lignes (et qu'on a un template quasi identique dans group.component.html, ce qui rend difficile la comparaison (TS vs. HTML))

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/components/list-editor/list-editor.component.ts
> +  template: `
Je ne suis pas fan des templates dans le code. D'autant moins quand ils font plus de quelques lignes (et qu'on a un template quasi identique dans list.component.html, ce qui rend difficile la comparaison (TS vs. HTML))

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/components/primitive-editor/primitive-editor.component.ts
> +  template: `
Je ne suis pas fan des templates dans le code. D'autant moins quand ils font plus de quelques lignes

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/components/group-editor/group-editor.component.ts
> +        matTooltipClass="vitamui-tooltip"
```suggestion
```

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/components/group-editor/group-editor.component.ts
> +  }
```suggestion
```

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/components/group-editor/group-editor.component.ts
> +    <ng-container *ngIf="editObject">
Il faudra utiliser l'accordéon de ma PR

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/components/list-editor/list-editor.component.ts
> +    <ng-container *ngIf="editObject && editObject.kind !== 'primitive-array'">
Il faudra utiliser le vitamui-common-data de ma PR

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/services/edit-object.service.ts
> +    // if (data && Object.keys(data).length === 0) return { ...baseEditObject, children };
```suggestion
```

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/services/edit-object.service.spec.ts
> +      const ouput = service.createaTemplateSchema(template, schema);
```suggestion
      const output = service.createaTemplateSchema(template, schema);
```
À corriger sur toutes les occurrences de `ouput`

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/services/form.service.ts
> +}
Code mort

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/services/form.service.ts
> +   * Tranform an object into a FormGroup.
```suggestion
   * Transform an object into a FormGroup.
```

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/services/form.service.spec.ts
> +      });
Ne peut-on pas réutiliser `complexObject` dans la comparaison ?

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/services/schema.service.spec.ts
> +      inject([MockSchemaService, PathService], (schemaService: MockSchemaService, pathService: PathService) => {
```suggestion
      inject([MockSchemaService, PathService], (schemaService: MockSchemaService) => {
```

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/services/schema.service.spec.ts
> +      inject([MockSchemaService, PathService], (schemaService: MockSchemaService, pathService: PathService) => {
```suggestion
      inject([MockSchemaService, PathService], (schemaService: MockSchemaService) => {
```

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/services/schema.service.ts
> +    return element.Cardinality.includes('MANY') || element.Cardinality.includes('MORE'); // FIXME: Real API seems return ZERO_OR_MORE instant ONE or MANY...
FIXME ?

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-viewer/services/schema-strategy-display-object.service.ts
> +    console.log({ displayObject });
À supprimer ?

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.html
> +    <br />
```suggestion
```

2024-03-04 16:55 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.html
> +    <br />
```suggestion
```

2024-03-05 10:19 UTC, laedanrex commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.html
> +  [ngStyle]="{ display: !editMode ? 'block' : 'none' }"
ca évite le recalcul du dom - ca permet un affichage plus rapide

2024-03-05 13:20 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.html
> +  [ngStyle]="{ display: !editMode ? 'block' : 'none' }"
Je ne suis pas convaincu. Là on bascule de l'un à l'autre si on affiche le mode édition/consultation, donc en fonction d'une action utilisateur (on n'est pas dans le cas d'un calcul qu'il faudrait faire très régulièrement).
Si on ne fait que consulter les données, on doit donc générer le mode édition pour rien. Le bilan ne me semble pas positif.
Bref, ça me convient de garder ce code, mais ça ne me semble pas être la bonne pratique d'avoir du DOM généré et caché par CSS.

2024-03-05 15:20 UTC, laedanrex commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.html
> +  [ngStyle]="{ display: !editMode ? 'block' : 'none' }"
moi je suis convaincu : ca depend des cas - si la condition varie souvent vaut mieu ca - si elle ne varie pas vaut mieu ngIf

2024-03-05 16:32 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.html
> +  [ngStyle]="{ display: !editMode ? 'block' : 'none' }"
Ben, on est d'accord, donc il vaut mieux ngIf. On en revient donc à ma remarque initiale.

2024-03-05 17:03 UTC, laedanrex approved these changes

2024-03-08 17:31 UTC, Regzox commented on ui/ui-frontend-common/src/app/modules/archive/components/archive-unit-editor/archive-unit-editor.service.ts
> +              'SubmissionAgency.OrganizationDescriptiveMetadata', // FIXME: What should we do with free extension points
C'est des cas particuliers, il vaut mieux garder cette information tant qu'on à pas déterminer une manière de les gérer (pour l'instant j'ai  volontairement choisi de les ignorer)

2024-03-08 17:31 UTC, Regzox commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.html
> +    <button (click)="onSave()" [disabled]="editObject?.control?.pristine" class="btn primary save">
a harmoniser avec le contenu de https://github.com/ProgrammeVitam/vitam-ui/pull/1304

2024-03-08 17:31 UTC, Regzox commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.scss
> +}
a harmoniser avec le contenu de https://github.com/ProgrammeVitam/vitam-ui/pull/1304

2024-03-08 17:58 UTC, marob approved these changes

2024-03-12 10:01 UTC, merged