Story #12111: display persistent id in object information
ProgrammeVitam/vitam-ui pull request #1658
Opened 2024-02-27 12:06 UTC by ebernard

2024-02-27 12:40 UTC, vitam-devops commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [18d92b8e\-9259\-4e29\-8573\-fd9f38f811c4](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=18d92b8e-9259-4e29-8573-fd9f38f811c4&branch=story_12111__display_ark_id)
### No New Or Fixed Issues Found

2024-02-28 09:57 UTC, marob requested changes

2024-02-28 09:57 UTC, marob commented on ui/ui-frontend-common/src/assets/shared-i18n/fr.json
> +        "PERSISTENTIDENTIFIERCONTENT": "Identifiant"
Il y a effectivement des clé d'i18n qui ont ce format, mais j'aurais plutôt utilisé un séparateur `_` (upper snake case)

2024-02-28 09:57 UTC, marob commented on ui/ui-frontend-common/src/assets/shared-i18n/fr.json
> +        "PERSISTENTIDENTIFIER": "IDENTIFIANT PÉRENNE",
J'aurai fait la mise en majuscule via CSS plutôt que dans l'i18n.

2024-02-28 09:57 UTC, marob commented on ui/ui-frontend/package-lock.json
Étonnant que le package-lock change alors que le package.json n'a pas changé.

2024-02-28 09:57 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
> +    <div *ngIf="versionWithQualifier.PersistentIdentifier" class="object-details-group PERSISTENTIDENTIFIER">
Je ne comprends pas trop l'intérêt de la classe `PERSISTENTIDENTIFIER`

2024-02-28 10:00 UTC, ebernard commented on ui/ui-frontend-common/src/assets/shared-i18n/fr.json
> +        "PERSISTENTIDENTIFIER": "IDENTIFIANT PÉRENNE",
Je me suis posé la même question, mais de ce que j'ai vu actuellement, c'est fait comme partout ailleurs.

2024-02-28 10:03 UTC, ebernard commented on ui/ui-frontend/package-lock.json
Le checksum de ui-frontend-common change. Quant au reste, je ne sais pas, j'ai juste fait un npm install. Je peux enlever le package-lock de la PR.

2024-02-28 10:03 UTC, ebernard commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
> +    <div *ngIf="versionWithQualifier.PersistentIdentifier" class="object-details-group PERSISTENTIDENTIFIER">
C'est fait comme ça à d'autres endroits du fichier, mais en effet ça ne sert à rien.

2024-02-28 10:16 UTC, marob commented on ui/ui-frontend/package-lock.json
S'il a été regénéré avec la bonne version de node/npm, ça me va, on peut le garder dans la PR

2024-02-28 13:16 UTC, ebernard commented on ui/ui-frontend-common/src/assets/shared-i18n/fr.json
> +        "PERSISTENTIDENTIFIERCONTENT": "Identifiant"
Done

2024-02-28 13:17 UTC, ebernard commented on ui/ui-frontend-common/src/assets/shared-i18n/fr.json
> +        "PERSISTENTIDENTIFIER": "IDENTIFIANT PÉRENNE",
Done

2024-02-28 13:17 UTC, ebernard commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
> +    <div *ngIf="versionWithQualifier.PersistentIdentifier" class="object-details-group PERSISTENTIDENTIFIER">
Je l'ai viré.

2024-02-28 13:17 UTC, ebernard commented on ui/ui-frontend/package-lock.json
J'ai enlevé le package-lock de la PR.

2024-02-28 13:34 UTC, marob approved these changes

2024-03-04 11:16 UTC, bbenaissa commented on ui/ui-frontend-common/src/assets/shared-i18n/fr.json
> +        "PERSISTENT_IDENTIFIER": "Identifiant pérenne",
En fait, le texte devrait êtres identifiants pérennes, le nom en singulier dans les variables et les balises provient de la balise XML du Seda

2024-03-04 11:16 UTC, bbenaissa commented on ui/ui-frontend-common/src/assets/shared-i18n/en.json
> +        "USAGE_VERSION": "Usage version",
idem

2024-03-04 11:18 UTC, ebernard commented on ui/ui-frontend-common/src/assets/shared-i18n/fr.json
> +        "PERSISTENT_IDENTIFIER": "Identifiant pérenne",
ok. J'avais juste mis comme dans le figma, mais je change ça.

2024-03-04 11:21 UTC, ebernard commented on ui/ui-frontend-common/src/assets/shared-i18n/en.json
> +        "USAGE_VERSION": "Usage version",
Corrigé (ton commentaire n'était pas sur la bonne ligne).

2024-03-04 13:07 UTC, bbenaissa approved these changes

2024-03-04 13:28 UTC, merged