Story #12151 feat(metadata): handle object array metadata form
ProgrammeVitam/vitam-ui pull request #1665
Opened 2024-03-04 15:29 UTC by Regzox

## Description
 
Ajoute la gestion des listes d'objet conformément à l'UX souhaité.

2024-03-08 09:51 UTC, laedanrex approved these changes

2024-03-08 18:11 UTC, marob reviewed
L'ordre des métadonnées englobantes n'est pas le même en consultation et en modification.
Par exemple, en consultation, Agent apparaît avant Destinataire et en modification dans le sens inverse.

> @Regzox En effet, j'ai un algo qui change entre le mode consultation et le mode edition en raison de la gestion des champs à initiliser plus drivé par le schema que la donnée.    
> Je pense qu'il faudra harmoniser la manière de trier les éléments plus tard.

2024-03-08 18:17 UTC, marob commented
Le CA 02 (pop-in de confirmation de suppression de balise englobante non vide) n'est pas implémenté.

2024-03-08 18:20 UTC, marob commented
CA 01 :
> Les métadonnées englobantes ne comprenant pas de métadonnée déjà renseignée s'affichent en bas du bloc

Les métadonnées englobantes vides et non vides sont "mélangées" entre elles : les vides ne sont pas à la fin.
Bon, après, on peut questionner le bien fondé de cette demande parce qu'il se passe quoi quand on commence à renseigner une métadonnées englobante vide ? Elle se déplace vers le haut pour retrouver sa place ?

2024-03-08 18:39 UTC, marob requested changes

2024-03-08 18:39 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/components/group-editor/group-editor.component.scss
> +}
Il faudrait plutôt utiliser une classe `btn btn-circle outline outline-secondary small` pour avoir la bonne taille de 30px (et le mode outline). D'ailleurs la taille est ici de 35px, ce qui ne correspond pas au Figma.
![image](https://github.com/ProgrammeVitam/vitam-ui/assets/3486231/9f4fcdf0-f490-4522-8ab3-32f03bada0f6)

2024-03-08 18:39 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/services/edit-object.service.ts
> +          label: 'Ajouter un nouveau bloc de métadonnées',
i18n

2024-03-08 18:39 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/services/edit-object.service.ts
> +              label: 'Supprimer le bloc de métadonnées',
i18n

2024-03-08 18:39 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/services/edit-object.service.ts
> +          label: 'Supprimer le bloc de métadonnées',
i18n

2024-03-08 18:39 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/services/edit-object.service.ts
> +            label: 'Supprimer le bloc de métadonnées',
i18n

2024-03-08 18:39 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/services/edit-object.service.ts
> +            },
Réutiliser le code ligne 48 ?

2024-03-08 18:39 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/services/edit-object.service.ts
>          };
Mettre en commun avec le code ligne 48 ?

2024-03-11 14:09 UTC, marob requested changes

2024-03-11 14:09 UTC, marob commented on ui/ui-frontend-common/src/app/modules/components/vitamui-menu-button/vitamui-menu-button.component.ts
> +  }
Ce n'est pas plus simple de passer par le template directement ? Je n'ai jamais vu de Renderer2.

2024-03-11 14:09 UTC, marob commented on ui/ui-frontend-common/src/app/modules/components/vitamui-menu-button/vitamui-menu-button.component.ts
> +    if (this.outlineSecondary) this.renderer.addClass(this.menuButton.nativeElement, 'outline-secondary');
`outline-secondary` ne fait pas doublon avec les classes `outline secondary` qui sont déjà présentes ?

2024-03-11 14:09 UTC, marob commented on ui/ui-frontend-common/src/assets/shared-i18n/en.json
> +          "FAILURE": ""
Pas de message ?

2024-03-11 14:09 UTC, marob commented on ui/ui-frontend-common/src/assets/shared-i18n/fr.json
> +          "FAILURE": ""
Pas de message ?

2024-03-11 14:50 UTC, Regzox commented on ui/ui-frontend-common/src/app/modules/components/vitamui-menu-button/vitamui-menu-button.component.ts
> +    if (this.outlineSecondary) this.renderer.addClass(this.menuButton.nativeElement, 'outline-secondary');
Ca fait pas la même chose en tout cas. J'ai soit l'un si défini soit les autres et plus les 3.

2024-03-11 16:47 UTC, marob approved these changes

2024-03-11 16:47 UTC, marob commented on ui/ui-frontend-common/src/app/modules/components/vitamui-menu-button/vitamui-menu-button.component.html
> +  #menuButton
Inutilisé

2024-03-11 16:47 UTC, marob commented on ui/ui-frontend-common/src/app/modules/components/vitamui-menu-button/vitamui-menu-button.component.html
> +  class="btn"
```suggestion
[ngClass]="{
    'outline-secondary': outlineSecondary,
    'btn-circle': this.icon && !this.label,
    hidden: trigger.menuOpen
  }"
  [disabled]="disabled"
  aria-label="more menu"
  [class]="menuButtonSize"
  class="btn secondary"
```

2024-03-11 18:47 UTC, marob requested changes

2024-03-11 18:47 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/components/list-editor/list-editor.component.html
> +</ng-container>
Pourquoi ne plus utiliser l'accordéon ?

2024-03-11 19:19 UTC, Regzox commented on ui/ui-frontend-common/src/app/modules/object-editor/components/list-editor/list-editor.component.html
> +</ng-container>
Il n'était pas adapté en l'état à ce qui est fait ici.
Il faut faire une grosse refacto dessus sinon.

2024-03-12 09:59 UTC, marob approved these changes

2024-03-12 10:01 UTC, merged