Bug #12447: avoid null enum convertion
ProgrammeVitam/vitam-ui pull request #1710
Opened 2024-03-25 10:57 UTC by laedanrex

## Description

[BUG][Affichage MD] les métadonnées externes ne s'affichent pas

## Type de changement:

* Nouveau Code

## Tests:

manuel

TU

## Contributeur

VAS (Vitam Accessible en Service)

2024-03-25 11:32 UTC, vitam-devops commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [9616d024\-a182\-42cc\-9d3c\-65c6322019cc](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=9616d024-a182-42cc-9d3c-65c6322019cc&branch=12447-schema-error)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/9616d024-a182-42cc-9d3c-65c6322019cc/sast/description/117/9884244256835554923)|/api/api\-pastis/pastis\-external/src/main/java/fr/gouv/vitamui/pastis/server/rest/PastisController\.java: [150](https://github.com/ProgrammeVitam/vitam-ui/blob/12447-schema-error//api/api-pastis/pastis-external/src/main/java/fr/gouv/vitamui/pastis/server/rest/PastisController.java#L150)|[Attack Vector](https://eu.ast.checkmarx.net/results/9616d024-a182-42cc-9d3c-65c6322019cc/3f06ff53-d733-40ac-a6fb-49e415cb793f/sast?result-id=K4jQN6x6B9KluR46U2WfF2%2BTHnM%3D&redirect=true)

### Fixed Issues
Severity|Issue|Source File / Package
---|---|---
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|[Log_Forging](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/9616d024-a182-42cc-9d3c-65c6322019cc/sast/description/117/9884244256835554923)|/api/api\-pastis/pastis\-external/src/main/java/fr/gouv/vitamui/pastis/server/rest/PastisController\.java: [150](https://github.com/ProgrammeVitam/vitam-ui/blob/12447-schema-error//api/api-pastis/pastis-external/src/main/java/fr/gouv/vitamui/pastis/server/rest/PastisController.java#L150)

2024-03-25 13:00 UTC, ebernard approved these changes

2024-03-25 13:11 UTC, marob requested changes
Ce n'est pas lié à https://gitlab.dev.programmevitam.fr/vitam/vitam/-/merge_requests/9985 ?
Il me semble qu'on devrait systématiquement avoir une `Collection` et que la cas `null` ne devrait pas exister.

2024-03-25 15:07 UTC, laedanrex commented
> Ce n'est pas lié à https://gitlab.dev.programmevitam.fr/vitam/vitam/-/merge_requests/9985 ? Il me semble qu'on devrait systématiquement avoir une `Collection` et que la cas `null` ne devrait pas exister.

Si très certainement.      
et ca fait tout planter.

2024-03-25 15:31 UTC, Regzox approved these changes

2024-03-25 15:39 UTC, marob commented
> > Ce n'est pas lié à https://gitlab.dev.programmevitam.fr/vitam/vitam/-/merge_requests/9985 ? Il me semble qu'on devrait systématiquement avoir une `Collection` et que la cas `null` ne devrait pas exister.
> 
> Si très certainement. et ca fait tout planter.

Mais alors, doit-on garder cette MR ?

2024-03-26 09:41 UTC, marob approved these changes

2024-03-26 11:02 UTC, merged