Bugs #12595: fix non working removal of default search filters
ProgrammeVitam/vitam-ui pull request #1711
Opened 2024-03-25 11:41 UTC by ebernard

Correction d'une régression sur la suppression des filtres de recherche entre 7.0 et 7.1.

2024-03-25 12:16 UTC, vitam-devops commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [c0ffda96\-8097\-45c8\-b4ae\-db804d0968d7](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=c0ffda96-8097-45c8-b4ae-db804d0968d7&branch=fix_12595_archive_unit_with_or_without_objets_filter)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|[Use_Of_Hardcoded_Password](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/c0ffda96-8097-45c8-b4ae-db804d0968d7/sast/description/259/2783517675732844652)|/ui/ui\-frontend/proxy\-gateway\-next\.conf\.js: [20](https://github.com/ProgrammeVitam/vitam-ui/blob/fix_12595_archive_unit_with_or_without_objets_filter//ui/ui-frontend/proxy-gateway-next.conf.js#L20)|[Attack Vector](https://eu.ast.checkmarx.net/results/c0ffda96-8097-45c8-b4ae-db804d0968d7/3f06ff53-d733-40ac-a6fb-49e415cb793f/sast?result-id=1Q00YZpDFULE2lbUJGhyB%2BRbgA4%3D&redirect=true)

2024-03-25 13:04 UTC, laedanrex approved these changes

2024-03-25 14:25 UTC, marob requested changes

2024-03-25 14:25 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> -    }
Cela casse plusieurs choses :
- l'id pérenne en query param (`PersistentIdentifier.PersistentIdentifierContent=...`) n'est plus supprimé lorsqu'on retire le critère
- cela ne remet plus automatiquement les critères archives avec ou sans objet lorsqu'on supprime le critère sur id pérenne (ou n'importe quel critère lorsque c'est le dernier). Cela-dit, ce comportement n'a jamais été spécifié il me semble, donc ce n'est pas forcément un problème si on a une "régression" dessus

2024-03-26 10:07 UTC, ebernard commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> -    }
J'ai remis le `resetParam`. En revanche, je laisse la suppression des lignes 490 à 492. Avec ça le comportement est le même que sur la 7.0 (testable sur https://int70x-ui.env.programmevitam.fr/archive-search/archive-search/tenant/1).

2024-03-27 10:05 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> -    }
@ebernard Mais du coup, on ne peut plus supprimer juste "Archive avec objets" ou "Archive sans objets".

2024-03-27 16:26 UTC, ebernard commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> -    }
Au temps pour moi. Je viens de changer pour que le `resetParams` ne concerne que le paramètre `PersistentIdentifier.PersistentIdentifierContent` (comme avant, quoi).

2024-04-02 11:40 UTC, marob approved these changes

2024-04-02 12:00 UTC, merged