bug #12572: fix http save criteria
ProgrammeVitam/vitam-ui pull request #1712
Opened 2024-03-25 13:02 UTC by mohatizaoui

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2024-03-25 13:05 UTC, ebernard commented on package-lock.json
À enlever ?

2024-03-25 13:08 UTC, laedanrex approved these changes

2024-03-25 13:39 UTC, ebernard approved these changes

2024-03-25 13:42 UTC, vitam-devops commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [5622cd6a\-6b99\-4624\-a4a2\-2d091082f0be](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=5622cd6a-6b99-4624-a4a2-2d091082f0be&branch=BUG_12572_save_search)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2024-24549](https://devhub.checkmarx.com/cve-details/CVE-2024-24549)|Maven\-org\.apache\.tomcat\.embed:tomcat\-embed\-core\-9\.0\.75|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/5622cd6a-6b99-4624-a4a2-2d091082f0be/vulnerabilities/CVE-2024-24549%3AMaven-org.apache.tomcat.embed%3Atomcat-embed-core-9.0.75/vulnerabilityDetails)
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|[Use_Of_Hardcoded_Password](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/5622cd6a-6b99-4624-a4a2-2d091082f0be/sast/description/259/2783517675732844652)|/ui/ui\-frontend/proxy\-gateway\-next\.conf\.js: [20](https://github.com/ProgrammeVitam/vitam-ui/blob/BUG_12572_save_search//ui/ui-frontend/proxy-gateway-next.conf.js#L20)|[Attack Vector](https://eu.ast.checkmarx.net/results/5622cd6a-6b99-4624-a4a2-2d091082f0be/3f06ff53-d733-40ac-a6fb-49e415cb793f/sast?result-id=1Q00YZpDFULE2lbUJGhyB%2BRbgA4%3D&redirect=true)

2024-03-25 14:41 UTC, marob requested changes

2024-03-25 14:41 UTC, marob commented on ui/ui-frontend/package-lock.json
Il n'y a pas de raison que le package-lock change. À revert.

2024-03-25 14:41 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-saver/search-criteria-saver.service.ts
> +    return this.archiveService.saveSearchCriteriaHistory(searchCriteriaHistory);
Je ne comprends pas pourquoi on utilise pas directement ArchiveApiService. Et je comprends encore moins pourquoi en l'utilisant directement ça ne fonctionne pas...
D'ailleurs, on avait le même code dans Collecte et ça fonctionne bien. Maintenant, on se retrouve avec des différences entre archive-search et Collecte.

2024-03-26 02:19 UTC, mohatizaoui commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-saver/search-criteria-saver.service.ts
> +    return this.archiveService.saveSearchCriteriaHistory(searchCriteriaHistory);
en fait il y a un problème dans http intercptor 
après le merge de api gateway l'interceptor authentificator-interceptor ne se déclenche pas 
je pense que suite à la redefinition de provide de component 
je pense qu'il faut faire pareil au niveau de collect

2024-03-26 13:05 UTC, marob approved these changes

2024-03-26 13:08 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-saver/search-criteria-saver.service.ts
> +    return this.archiveService.saveSearchCriteriaHistory(searchCriteriaHistory);
Il faut créer un ticket de dette technique pour nettoyer le code :
- supprimer httpClient du constructeur de SearchService
- supprimer les services déclarés dans les providers lorsqu'ils sont déjà `providedIn: 'root'`
- ajouter `providedIn: 'root'` aux services qui ne l'ont pas (sauf exceptions ?) et les supprimer des providers

2024-03-26 16:04 UTC, merged