Bugs #12601: fix transfer acknowledgment
ProgrammeVitam/vitam-ui pull request #1714
Opened 2024-03-25 15:28 UTC by ebernard

## Description

Fix transfer acknoledgement. Expected parameter name for file name was converted from "fileName" to "X-Original-Filename" in ui-archive-search.

## Type de changement:

* Correction

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

manuel

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2024-03-25 16:06 UTC, vitam-devops commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [74b7cf9c\-d96f\-4263\-87b8\-ec009c682fb8](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=74b7cf9c-d96f-4263-87b8-ec009c682fb8&branch=fix_12601_transfer_acknowledgment)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2024-24549](https://devhub.checkmarx.com/cve-details/CVE-2024-24549)|Maven\-org\.apache\.tomcat\.embed:tomcat\-embed\-core\-9\.0\.75|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/74b7cf9c-d96f-4263-87b8-ec009c682fb8/vulnerabilities/CVE-2024-24549%3AMaven-org.apache.tomcat.embed%3Atomcat-embed-core-9.0.75/vulnerabilityDetails)
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|[Use_Of_Hardcoded_Password](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/74b7cf9c-d96f-4263-87b8-ec009c682fb8/sast/description/259/2783517675732844652)|/ui/ui\-frontend/proxy\-gateway\-next\.conf\.js: [20](https://github.com/ProgrammeVitam/vitam-ui/blob/fix_12601_transfer_acknowledgment//ui/ui-frontend/proxy-gateway-next.conf.js#L20)|[Attack Vector](https://eu.ast.checkmarx.net/results/74b7cf9c-d96f-4263-87b8-ec009c682fb8/3f06ff53-d733-40ac-a6fb-49e415cb793f/sast?result-id=1Q00YZpDFULE2lbUJGhyB%2BRbgA4%3D&redirect=true)

2024-03-25 16:13 UTC, Regzox approved these changes

2024-03-25 16:33 UTC, marob requested changes

2024-03-25 16:33 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
À corriger également sur Collecte (archive-collect.service.ts) et Ingest (ingest-api.service.ts)

2024-03-25 16:39 UTC, ebernard commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
À ma connaissance, la fonctionnalité n'est disponible que dans archive-search ("Acquitter un transfert d'archives").

2024-03-25 16:47 UTC, laedanrex approved these changes

2024-03-25 16:51 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
On a le même problème de `X-Original-Filename` attendu et `filename` envoyé.
Si tu cherche `'fileName', fileName` dans le code, tu trouveras toutes les occurrences. Et dans chacun des cas, c'est ui-* qui faisait la "traduction" en `X-Original-Filename` via le *-external-client correspondant

2024-03-25 17:03 UTC, ebernard commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
Ok. Mais dans ce cas, il faut peut-être plutôt créer d'autres tickets non ?

Sinon :
- pour Ingest, c'est déjà fait dans 382b75e53058d3559f796eab0fb9cc1d3536f045
- pour Collect, merge request séparée à venir pour changer `ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-collect.service.ts` ligne 296

2024-03-25 17:25 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
Dans Ingest, j'ai toujours `headers = headers.set('fileName', fileName);` sur develop. Pour moi c'est KO.

En effet, il faut voir s'il faut traiter dans un autre ticket ou non. S'il existe déjà des tickets correspondants à ces bugs, on peut traiter dans d'autres MRs. Sinon, le plus simple est peut-être de faire une correction "préventive" en fixant toutes les erreurs similaires dans cette MR.

2024-03-25 17:27 UTC, ebernard commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
Regarde deux lignes au-dessus :-)

2024-03-25 17:29 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
Ah, effectivement, y'a les 2, mais pourquoi garder les 2 ?
Ce n'est pas homogène avec ta PR qui remplace `fileName` par `X-Original-Filename`. Donc soit il faut adopter la même technique en gardant les 2 (je ne suis pas fan), soit il faudrait supprimer le header `fileName`.

2024-03-26 14:51 UTC, ebernard commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
- Ingest : traité dans https://github.com/ProgrammeVitam/vitam-ui/pull/1719
- Collect : finalement aucun ticket ne sera créé, mais c'est corrigé dans https://github.com/ProgrammeVitam/vitam-ui/pull/1720

2024-03-27 09:37 UTC, marob approved these changes

2024-03-27 09:41 UTC, merged