Story #12443: Update merge_index for VitamUI #1713
ProgrammeVitam/vitam-ui pull request #1725
Opened 2024-03-27 10:06 UTC by bouayad123

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2024-03-27 10:19 UTC, GiooDev requested changes

2024-03-27 10:19 UTC, GiooDev commented on deployment/roles/merge_index_apache/templates/proxy_pass.conf.j2
> +    {% for host in groups['hosts_vitamui'] %}
Plutôt itérer sur le group `hosts_browse`

Reprendre l'exemple sous: `deployment/roles/reverse/templates/apache/httpd_config`

```j2
# /vitamui subdir browser
{% for host in groups['hosts_browse'] %}
    ProxyPass /nodes/{{host}}/browse http://{{ hostvars[host]['ip_admin'] }}/browse {{reverse_connection_params}}
    ProxyPassReverse /nodes/{{host}}/browse http://{{ hostvars[host]['ip_admin'] }}/browse

    ProxyPass /browse{{loop.index}} http://{{ hostvars[host]['ip_admin'] }}/browse {{reverse_connection_params}}
    ProxyPassReverse /browse{{loop.index}} http://{{ hostvars[host]['ip_admin'] }}/browse
{% endfor %}
```

2024-03-27 10:19 UTC, GiooDev commented on deployment/roles/merge_index_apache/templates/proxy_pass.conf.j2
> +    {% for host in groups['hosts_vitamui_mongod'] %}
Rajouter aussi le conditionnel sur le contenu de la variable: `mongo_express_enabled=true`

Reprendre l'exemple sous: `deployment/roles/reverse/templates/apache/httpd_config`

```j2
{% for host in groups['hosts_vitamui_mongod'] %}
{% if hostvars[host]['mongo_express_enabled'] | default(false) | bool == true %}
    # MONGO-EXPRESS
    ProxyPass {{ mongo_express.baseuri }} http://{{ hostvars[host]['ip_admin'] }}:{{ mongo_express.port | default('8081') }}{{ mongo_express.baseuri }} {{ reverse_connection_params }}
    ProxyPassReverse {{ mongo_express.baseuri }} http://{{ hostvars[host]['ip_admin'] }}:{{ mongo_express.port | default('8081') }}{{ mongo_express.baseuri }}
{% endif %}
{% endfor %}
```

2024-03-27 11:03 UTC, vitam-devops commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [81f71a71\-35ae\-4270\-a28d\-bf1d49f23572](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=81f71a71-35ae-4270-a28d-bf1d49f23572&branch=story_12443_update_merge_index-fix)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[SSRF](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/81f71a71-35ae-4270-a28d-bf1d49f23572/sast/description/918/15179929566605030594)|/api/api\-iam/iam\-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/CasInternalController\.java: [196](https://github.com/ProgrammeVitam/vitam-ui/blob/story_12443_update_merge_index-fix//api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/CasInternalController.java#L196)|[Attack Vector](https://eu.ast.checkmarx.net/results/81f71a71-35ae-4270-a28d-bf1d49f23572/3f06ff53-d733-40ac-a6fb-49e415cb793f/sast?result-id=CAmJXnwIMrNb9m3FG2FNIJBcWyQ%3D&redirect=true)

2024-03-27 13:04 UTC, GiooDev requested changes

2024-03-27 13:04 UTC, GiooDev commented on deployment/roles/merge_index_apache/tasks/main.yml
> +    path: "/etc/httpd/conf.d/zz_{{ vitam_site_name }}.conf"
```yml
- name: Set apache settings for CentOS
  set_fact:
    apache_service: "httpd"
    apache_conf_dir: "conf.d"
  when: ansible_os_family == "RedHat"

- name: Set apache settings for Debian
  set_fact:
    apache_service: "apache2"
    apache_conf_dir: "sites-available"
  when: ansible_os_family == "Debian"
```

`path: "/etc/{{ apache_service }}/{{ apache_conf_dir }}/zz_{{ vitam_site_name }}.conf"`

2024-03-27 13:04 UTC, GiooDev commented on deployment/roles/merge_index_apache/templates/proxy_pass.conf.j2
> +    ProxyPass /nodes/{{ host }}/browse http://{{ hostvars[host]['ip_admin'] }}/browse/  {{ reverse_connection_short_params }}
Retirer `reverse_connection_short_params`

2024-03-27 13:04 UTC, GiooDev commented on deployment/roles/merge_index_apache/templates/proxy_pass.conf.j2
> +{% if mongo_express_enabled | default(false) | bool == true %}
Ligne à retirer.

2024-04-02 13:00 UTC, GiooDev approved these changes

2024-04-03 14:17 UTC, laedanrex approved these changes

2024-04-03 16:02 UTC, Regzox approved these changes

2024-04-03 16:17 UTC, merged