refactor(vitamui-library): fix usage, set prefix and rationalize validators
ProgrammeVitam/vitam-ui pull request #1726
Opened 2024-03-27 15:22 UTC by Regzox

## Description

* Corrige les mauvaises utilisations de vitamui-library
* Met en place le prefix `vitamui-library` pour les imports
* Met en commun le validateur de format d'id de règles de gestion

2024-03-27 16:00 UTC, vitam-devops commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [9d4ee416\-78ca\-45f9\-9e5e\-0652e025c7b8](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=9d4ee416-78ca-45f9-9e5e-0652e025c7b8&branch=story_11852__refactor_vitamui_library_usage)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2019-15599](https://devhub.checkmarx.com/cve-details/CVE-2019-15599)|Npm\-tree\-kill\-1\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9d4ee416-78ca-45f9-9e5e-0652e025c7b8/vulnerabilities/CVE-2019-15599%3ANpm-tree-kill-1.2.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-28502](https://devhub.checkmarx.com/cve-details/CVE-2020-28502)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9d4ee416-78ca-45f9-9e5e-0652e025c7b8/vulnerabilities/CVE-2020-28502%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-36048](https://devhub.checkmarx.com/cve-details/CVE-2020-36048)|Npm\-engine\.io\-3\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9d4ee416-78ca-45f9-9e5e-0652e025c7b8/vulnerabilities/CVE-2020-36048%3ANpm-engine.io-3.2.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-36049](https://devhub.checkmarx.com/cve-details/CVE-2020-36049)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9d4ee416-78ca-45f9-9e5e-0652e025c7b8/vulnerabilities/CVE-2020-36049%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-7660](https://devhub.checkmarx.com/cve-details/CVE-2020-7660)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9d4ee416-78ca-45f9-9e5e-0652e025c7b8/vulnerabilities/CVE-2020-7660%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-7788](https://devhub.checkmarx.com/cve-details/CVE-2020-7788)|Npm\-ini\-1\.3\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9d4ee416-78ca-45f9-9e5e-0652e025c7b8/vulnerabilities/CVE-2020-7788%3ANpm-ini-1.3.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2021-31597](https://devhub.checkmarx.com/cve-details/CVE-2021-31597)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9d4ee416-78ca-45f9-9e5e-0652e025c7b8/vulnerabilities/CVE-2021-31597%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2022-2421](https://devhub.checkmarx.com/cve-details/CVE-2022-2421)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9d4ee416-78ca-45f9-9e5e-0652e025c7b8/vulnerabilities/CVE-2022-2421%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2023-32695](https://devhub.checkmarx.com/cve-details/CVE-2023-32695)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9d4ee416-78ca-45f9-9e5e-0652e025c7b8/vulnerabilities/CVE-2023-32695%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2019-16769](https://devhub.checkmarx.com/cve-details/CVE-2019-16769)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9d4ee416-78ca-45f9-9e5e-0652e025c7b8/vulnerabilities/CVE-2019-16769%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-6\.10\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9d4ee416-78ca-45f9-9e5e-0652e025c7b8/vulnerabilities/CVE-2020-15366%3ANpm-ajv-6.10.0/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-5\.5\.2|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9d4ee416-78ca-45f9-9e5e-0652e025c7b8/vulnerabilities/CVE-2020-15366%3ANpm-ajv-5.5.2/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-28481](https://devhub.checkmarx.com/cve-details/CVE-2020-28481)|Npm\-socket\.io\-2\.1\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9d4ee416-78ca-45f9-9e5e-0652e025c7b8/vulnerabilities/CVE-2020-28481%3ANpm-socket.io-2.1.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-7693](https://devhub.checkmarx.com/cve-details/CVE-2020-7693)|Npm\-sockjs\-0\.3\.19|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9d4ee416-78ca-45f9-9e5e-0652e025c7b8/vulnerabilities/CVE-2020-7693%3ANpm-sockjs-0.3.19/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2021-23364](https://devhub.checkmarx.com/cve-details/CVE-2021-23364)|Npm\-browserslist\-4\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9d4ee416-78ca-45f9-9e5e-0652e025c7b8/vulnerabilities/CVE-2021-23364%3ANpm-browserslist-4.5.5/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2021-23495](https://devhub.checkmarx.com/cve-details/CVE-2021-23495)|Npm\-karma\-4\.1\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9d4ee416-78ca-45f9-9e5e-0652e025c7b8/vulnerabilities/CVE-2021-23495%3ANpm-karma-4.1.0/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2022-0437](https://devhub.checkmarx.com/cve-details/CVE-2022-0437)|Npm\-karma\-4\.1\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9d4ee416-78ca-45f9-9e5e-0652e025c7b8/vulnerabilities/CVE-2022-0437%3ANpm-karma-4.1.0/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2022-21704](https://devhub.checkmarx.com/cve-details/CVE-2022-21704)|Npm\-log4js\-4\.5\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9d4ee416-78ca-45f9-9e5e-0652e025c7b8/vulnerabilities/CVE-2022-21704%3ANpm-log4js-4.5.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2022-41940](https://devhub.checkmarx.com/cve-details/CVE-2022-41940)|Npm\-engine\.io\-3\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/9d4ee416-78ca-45f9-9e5e-0652e025c7b8/vulnerabilities/CVE-2022-41940%3ANpm-engine.io-3.2.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Med [...]

2024-03-27 16:04 UTC, ebernard approved these changes

2024-03-27 16:29 UTC, laedanrex approved these changes

2024-03-29 10:14 UTC, marob requested changes

2024-03-29 10:14 UTC, marob commented on ui/ui-frontend/package.json
> +    "build:allModules": "npm run build:vitamui-library && npm run build:portal &&  npm run build:identity  && npm run build:referential && npm run build:archive-search && npm run build:pastis && npm
J'ai un FIX dans une autre MR pour paralléliser ces builds. Aussi, j'ai ajouté le build de vitamui-library avant le build de tous les modules côté maven dans le pom.xml.
Il me semble que ça va rentrer en conflit.

2024-03-29 10:26 UTC, marob requested changes

2024-03-29 10:26 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/agency/agency-list/agency-list.component.spec.ts
> -/*
Suppression de la license ?

2024-03-29 10:26 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/add-management-rules/add-management-rules.component.ts
> +import { Subscription, merge } from 'rxjs';
On a un soucis sur l'ordre des imports. Y'a beaucoup de diff qui concerne un changement d'ordre. Il faudrait voir pour standardiser ça, via un plugin Prettier ?

2024-03-29 13:09 UTC, Regzox commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/add-management-rules/add-management-rules.component.ts
> +import { Subscription, merge } from 'rxjs';
Il y a une configuration VSCode qui doit utiliser le tslint pour fix les fichiers.

D'ailleurs j'avais tenté de faire des coups de `ng lint --fix` et `npm run prettier` en local mais beaucoup trop de modifications sur le code existant et quelques régles contradictoires entre tslint et prettier.

Dans tous les cas c'est un sujet qu'on risque de gérer lors de la montée de version angular. Il y a pas mal de dépréciation à gérer.

2024-03-29 13:10 UTC, Regzox commented on ui/ui-frontend/projects/referential/src/app/agency/agency-list/agency-list.component.spec.ts
> -/*
Yes, c'est des tests qui passaient pas, j'ai régénéré un nouveau fichier spec... Je corrige.

2024-03-29 13:15 UTC, Regzox commented on ui/ui-frontend/package.json
> +    "build:allModules": "npm run build:vitamui-library && npm run build:portal &&  npm run build:identity  && npm run build:referential && npm run build:archive-search && npm run build:pastis && npm
C'est possible, mais comme j'ai corrigé toutes les utilisations cross-projet de la lib, j'ai dû ajouter ça pour faire passer les builds correctement.

Je pense qu'on va prendre ta méthode car ici, c'est provisoire et je trouve ça pas terrible de ne pas lancer un build général du projet. Par contre, je ne sais pas si un build général contruit les projets dans le bon ordre de dépendance.

2024-03-29 14:19 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/add-management-rules/add-management-rules.component.ts
> +import { Subscription, merge } from 'rxjs';
Oui, peut-être qu'ESLint permettra de trier les imports. Attendons de voir une fois qu'on a monté de version Angular et mis en place ESLint du coup.

2024-03-29 14:20 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/agency/agency-list/agency-list.component.spec.ts
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2022)
Ce n'est plus la même date, c'est normal ?

2024-03-29 14:21 UTC, marob commented on ui/ui-frontend/package.json
> +    "build:allModules": "npm run build:vitamui-library && npm run build:portal &&  npm run build:identity  && npm run build:referential && npm run build:archive-search && npm run build:pastis && npm
OK. Il y a un ordre de dépendance entre les projets ?

2024-04-02 12:39 UTC, Regzox commented on ui/ui-frontend/package.json
> +    "build:allModules": "npm run build:vitamui-library && npm run build:portal &&  npm run build:identity  && npm run build:referential && npm run build:archive-search && npm run build:pastis && npm
vitamui-library puis le reste à priori.

2024-04-02 12:46 UTC, Regzox commented on ui/ui-frontend/projects/referential/src/app/agency/agency-list/agency-list.component.spec.ts
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2022)
J'ai recréer le fichier... La licence que j'ai est 2022. Je sais pas si c'est astucieux de mettre cette information comme ça. Dans tous les cas, il y a masse de fichier qui n'ont pas la dernière version de licence.

Tu peux passer le inherit du pom principal à true et constater les dégats du license:check

2024-04-02 13:00 UTC, marob commented on ui/ui-frontend/package.json
> +    "build:allModules": "npm run build:vitamui-library && npm run build:portal &&  npm run build:identity  && npm run build:referential && npm run build:archive-search && npm run build:pastis && npm
À supprimer pour éviter le double build (maven fait déjà un build de la library)

2024-04-02 13:02 UTC, marob approved these changes

2024-04-02 13:54 UTC, Regzox commented on ui/ui-frontend/package.json
> +    "build:allModules": "npm run build:vitamui-library && npm run build:portal &&  npm run build:identity  && npm run build:referential && npm run build:archive-search && npm run build:pastis && npm
:+1:

2024-04-04 10:02 UTC, merged