Story #12273: Migration to API Gateway
ProgrammeVitam/vitam-ui pull request #1729
Opened 2024-03-28 16:27 UTC by Ro3034

## Description

*Description des modifications*

Ajout du rôle de migration de la gateway et conditions sur la gateway enlevées dans les configurations des services, dans les scripts de base de données et dans l'ansiblerie.

## Type de changement:
Ansiblerie / scripts de base de données

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*
Installation d'un Vitam v701 et Vitamui701. Montée de version Vitam vers v71. Montée de version vitamui v71 (pre step: on joue le playbook de migration gateway).

manuel

environnement
BU

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2024-03-28 17:03 UTC, vitam-devops commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [557e71fb\-163c\-4a74\-8256\-3592154c12c1](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=557e71fb-163c-4a74-8256-3592154c12c1&branch=story_12273_migration_gtw)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2019-15599](https://devhub.checkmarx.com/cve-details/CVE-2019-15599)|Npm\-tree\-kill\-1\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/557e71fb-163c-4a74-8256-3592154c12c1/vulnerabilities/CVE-2019-15599%3ANpm-tree-kill-1.2.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-28502](https://devhub.checkmarx.com/cve-details/CVE-2020-28502)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/557e71fb-163c-4a74-8256-3592154c12c1/vulnerabilities/CVE-2020-28502%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-36048](https://devhub.checkmarx.com/cve-details/CVE-2020-36048)|Npm\-engine\.io\-3\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/557e71fb-163c-4a74-8256-3592154c12c1/vulnerabilities/CVE-2020-36048%3ANpm-engine.io-3.2.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-36049](https://devhub.checkmarx.com/cve-details/CVE-2020-36049)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/557e71fb-163c-4a74-8256-3592154c12c1/vulnerabilities/CVE-2020-36049%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-7660](https://devhub.checkmarx.com/cve-details/CVE-2020-7660)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/557e71fb-163c-4a74-8256-3592154c12c1/vulnerabilities/CVE-2020-7660%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-7788](https://devhub.checkmarx.com/cve-details/CVE-2020-7788)|Npm\-ini\-1\.3\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/557e71fb-163c-4a74-8256-3592154c12c1/vulnerabilities/CVE-2020-7788%3ANpm-ini-1.3.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2021-31597](https://devhub.checkmarx.com/cve-details/CVE-2021-31597)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/557e71fb-163c-4a74-8256-3592154c12c1/vulnerabilities/CVE-2021-31597%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2022-2421](https://devhub.checkmarx.com/cve-details/CVE-2022-2421)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/557e71fb-163c-4a74-8256-3592154c12c1/vulnerabilities/CVE-2022-2421%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2023-28857](https://devhub.checkmarx.com/cve-details/CVE-2023-28857)|Maven\-org\.apereo\.cas:cas\-server\-support\-x509\-core\-6\.6\.4|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/557e71fb-163c-4a74-8256-3592154c12c1/vulnerabilities/CVE-2023-28857%3AMaven-org.apereo.cas%3Acas-server-support-x509-core-6.6.4/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2023-6481](https://devhub.checkmarx.com/cve-details/CVE-2023-6481)|Maven\-ch\.qos\.logback:logback\-core\-1\.2\.9|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/557e71fb-163c-4a74-8256-3592154c12c1/vulnerabilities/CVE-2023-6481%3AMaven-ch.qos.logback%3Alogback-core-1.2.9/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2019-16769](https://devhub.checkmarx.com/cve-details/CVE-2019-16769)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/557e71fb-163c-4a74-8256-3592154c12c1/vulnerabilities/CVE-2019-16769%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-6\.10\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/557e71fb-163c-4a74-8256-3592154c12c1/vulnerabilities/CVE-2020-15366%3ANpm-ajv-6.10.0/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-5\.5\.2|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/557e71fb-163c-4a74-8256-3592154c12c1/vulnerabilities/CVE-2020-15366%3ANpm-ajv-5.5.2/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-28481](https://devhub.checkmarx.com/cve-details/CVE-2020-28481)|Npm\-socket\.io\-2\.1\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/557e71fb-163c-4a74-8256-3592154c12c1/vulnerabilities/CVE-2020-28481%3ANpm-socket.io-2.1.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-7693](https://devhub.checkmarx.com/cve-details/CVE-2020-7693)|Npm\-sockjs\-0\.3\.19|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/557e71fb-163c-4a74-8256-3592154c12c1/vulnerabilities/CVE-2020-7693%3ANpm-sockjs-0.3.19/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2021-23364](https://devhub.checkmarx.com/cve-details/CVE-2021-23364)|Npm\-browserslist\-4\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/557e71fb-163c-4a74-8256-3592154c12c1/vulnerabilities/CVE-2021-23364%3ANpm-browserslist-4.5.5/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2022-21704](https://devhub.checkmarx.com/cve-details/CVE-2022-21704)|Npm\-log4js\-4\.5\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/557e71fb-163c-4a74-8256-3592154c12c1/vulnerabilities/CVE-2022-21704%3ANpm-log4js-4.5.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2022-41940](https://devhub.checkmarx.com/cve-details/CVE-2022-41940)|Npm\-engine\.io\-3\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/557e71fb-163c-4a74-8256-3592154c12c1/vulnerabilities/CVE-2022-41940%3ANpm-engine.io-3.2.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2024-29041](https://devhub.checkmarx.com/cve-details/CVE-2024-29041)|Npm\-express\-4\.18\.2|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/557e71fb-163c-4a74-8256-3592154c12c1/vulnerabilities/CVE-2024-29041%3ANpm-e [...]

2024-03-28 17:12 UTC, GiooDev requested changes

2024-03-28 17:12 UTC, GiooDev commented on deployment/ansible-vitamui-migration/migration_gateway.yml
> +      shell: yum-complete-transaction --cleanup-only
Attention à la gestion sous Debian

2024-03-28 17:12 UTC, GiooDev commented on deployment/ansible-vitamui-migration/migration_gateway.yml
> +      when: inventory_hostname is in groups['hosts_vitamui_reverseproxy']
Pourquoi ce when ? Tu es déjà dans le group hosts_vitamui_reverseproxy vu tu es en train d'appliquer les tasks sur ces hosts.

2024-03-28 21:41 UTC, GiooDev commented
Il manque aussi la MAJ de la DMV avec l'exécution de la mise à jour des certificats ainsi que l'exécution du playbook fourni.

2024-03-29 10:17 UTC, GiooDev commented on deployment/scripts/mongod/v7.1/003_TRV-399_enable_oidc_code_grant_type_on_portal_service_ref.js.j2
Petite question à analyser pour l'ensemble de ces scripts.

Est-ce qu'il serait envisageable de supprimer les anciens scripts qui font l'insert initial de ces services puisqu'on les delete dans ce script ?

Ainsi, lors d'une installation initiale, on s'évite de jouer tous les scripts initiaux pour rien et on conserve malgré tout le delete ici en cas de migration d'une précédente release.

2024-04-02 21:01 UTC, GiooDev commented on deployment/scripts/mongod/v7.1/003_TRV-399_enable_oidc_code_grant_type_on_portal_service_ref.js.j2
J'ai poussé un commit pour modifier ça. À tester lors d'un déploiement from scratch.

2024-04-05 15:34 UTC, Regzox approved these changes

2024-04-05 15:37 UTC, ebernard approved these changes
Ok pour moi, mais devra être complété par une autre PR pour supprimer le code inutile côté dev (virer les ui-*, supprimer les modes de lancement n'utilisant pas l'apigw, virer les conditions s'il en reste encore, etc.)

2024-04-05 15:52 UTC, GiooDev commented
> Ok pour moi, mais devra être complété par une autre PR pour supprimer le code inutile côté dev (virer les ui-*, supprimer les modes de lancement n'utilisant pas l'apigw, virer les conditions s'il en reste encore, etc.)

Tout à fait d'accord. Là c'est une PR 'OPS' pour la migration mais il faut prévoir la fin du cleanup côté dev.

2024-04-05 16:12 UTC, merged

2024-04-05 16:42 UTC, bbenaissa commented
On avait prévu de créer une US de cleanup coté dev sur cette partie.

2024-04-05 21:28 UTC, GiooDev commented
> On avait prévu de créer une US de cleanup coté dev sur cette partie.

Je l'ai créée (story 12674) pour l'avoir en visibilité :)