Add different indexes, add enabled capacity, add mongodb dissect
ProgrammeVitam/vitam-ui pull request #1735
Opened 2024-04-03 14:44 UTC by Ro3034

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie
Ajout et correction dans l'ansiblerie, partie filebeat.

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2024-04-03 14:59 UTC, vitam-devops commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [e7a88013\-6d97\-450f\-8a73\-dd2cd7c2cd35](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=e7a88013-6d97-450f-8a73-dd2cd7c2cd35&branch=story_12517_fix_improve_filebeat)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2019-15599](https://devhub.checkmarx.com/cve-details/CVE-2019-15599)|Npm\-tree\-kill\-1\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/e7a88013-6d97-450f-8a73-dd2cd7c2cd35/vulnerabilities/CVE-2019-15599%3ANpm-tree-kill-1.2.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-28502](https://devhub.checkmarx.com/cve-details/CVE-2020-28502)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/e7a88013-6d97-450f-8a73-dd2cd7c2cd35/vulnerabilities/CVE-2020-28502%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-36048](https://devhub.checkmarx.com/cve-details/CVE-2020-36048)|Npm\-engine\.io\-3\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/e7a88013-6d97-450f-8a73-dd2cd7c2cd35/vulnerabilities/CVE-2020-36048%3ANpm-engine.io-3.2.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-36049](https://devhub.checkmarx.com/cve-details/CVE-2020-36049)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/e7a88013-6d97-450f-8a73-dd2cd7c2cd35/vulnerabilities/CVE-2020-36049%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-7660](https://devhub.checkmarx.com/cve-details/CVE-2020-7660)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/e7a88013-6d97-450f-8a73-dd2cd7c2cd35/vulnerabilities/CVE-2020-7660%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-7788](https://devhub.checkmarx.com/cve-details/CVE-2020-7788)|Npm\-ini\-1\.3\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/e7a88013-6d97-450f-8a73-dd2cd7c2cd35/vulnerabilities/CVE-2020-7788%3ANpm-ini-1.3.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2021-31597](https://devhub.checkmarx.com/cve-details/CVE-2021-31597)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/e7a88013-6d97-450f-8a73-dd2cd7c2cd35/vulnerabilities/CVE-2021-31597%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2022-2421](https://devhub.checkmarx.com/cve-details/CVE-2022-2421)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/e7a88013-6d97-450f-8a73-dd2cd7c2cd35/vulnerabilities/CVE-2022-2421%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2019-16769](https://devhub.checkmarx.com/cve-details/CVE-2019-16769)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/e7a88013-6d97-450f-8a73-dd2cd7c2cd35/vulnerabilities/CVE-2019-16769%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-6\.10\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/e7a88013-6d97-450f-8a73-dd2cd7c2cd35/vulnerabilities/CVE-2020-15366%3ANpm-ajv-6.10.0/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-5\.5\.2|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/e7a88013-6d97-450f-8a73-dd2cd7c2cd35/vulnerabilities/CVE-2020-15366%3ANpm-ajv-5.5.2/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-28481](https://devhub.checkmarx.com/cve-details/CVE-2020-28481)|Npm\-socket\.io\-2\.1\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/e7a88013-6d97-450f-8a73-dd2cd7c2cd35/vulnerabilities/CVE-2020-28481%3ANpm-socket.io-2.1.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-7693](https://devhub.checkmarx.com/cve-details/CVE-2020-7693)|Npm\-sockjs\-0\.3\.19|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/e7a88013-6d97-450f-8a73-dd2cd7c2cd35/vulnerabilities/CVE-2020-7693%3ANpm-sockjs-0.3.19/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2021-23364](https://devhub.checkmarx.com/cve-details/CVE-2021-23364)|Npm\-browserslist\-4\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/e7a88013-6d97-450f-8a73-dd2cd7c2cd35/vulnerabilities/CVE-2021-23364%3ANpm-browserslist-4.5.5/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2022-21704](https://devhub.checkmarx.com/cve-details/CVE-2022-21704)|Npm\-log4js\-4\.5\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/e7a88013-6d97-450f-8a73-dd2cd7c2cd35/vulnerabilities/CVE-2022-21704%3ANpm-log4js-4.5.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2022-41940](https://devhub.checkmarx.com/cve-details/CVE-2022-41940)|Npm\-engine\.io\-3\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/e7a88013-6d97-450f-8a73-dd2cd7c2cd35/vulnerabilities/CVE-2022-41940%3ANpm-engine.io-3.2.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[Cx366abb53-9fde](https://devhub.checkmarx.com/cve-details/Cx366abb53-9fde)|Npm\-es5\-ext\-0\.10\.62|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/e7a88013-6d97-450f-8a73-dd2cd7c2cd35/vulnerabilities/Cx366abb53-9fde%3ANpm-es5-ext-0.10.62/vulnerabilityDetails)
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|Logging of Sensitive Data|/ansible\.cfg: [2](https://github.com/ProgrammeVitam/vitam-ui/blob/story_12517_fix_improve_filebeat//deployment/pki/scripts/lib/ansible.cfg#L2)|To keep sensitive values out of logs, tasks that expose them need to be marked defining 'no_log' and setting to True
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|Logging of Sensitive Data|/ansible\.cfg: [1](https://github.com/ProgrammeVitam/vitam-ui/blob/story_12517_fix_improve_filebeat//deployment/ansible.cfg#L1)|To keep sensitive values out of logs, tasks that expose them need to be marked defining 'no_log' and setting to True
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|Logging of Sensitive Data|/ansible\.cfg: [2](https://github.com/ProgrammeVitam/vitam-ui/blo [...]

2024-04-03 15:34 UTC, GiooDev commented on deployment/roles/filebeat/templates/inputs/vitamui_services.yml.j2
> +  enabled: {{ {'vitamui-iam-internal': filebeat.services.vitamui-iam-internal.enable_access,
Attention, dans ansible les variables ne doivent pas contenir de -

Renommer `vitamui-ingest-internal` en `vitamui_ingest_internal`

2024-04-09 09:03 UTC, GiooDev requested changes

2024-04-09 09:03 UTC, GiooDev commented on deployment/ansible-vitamui/filebeat.yml
> +    - filebeat
Pourquoi retirer le conditionnel ici ? On doit encore pouvoir choisir entre rsyslog et filebeat.

2024-04-09 09:03 UTC, GiooDev commented on deployment/roles/filebeat/tasks/add_modules.yml
> +  when:
Pas besoin de ce saut de ligne ici.

2024-04-09 09:05 UTC, GiooDev commented on deployment/ansible-vitamui/filebeat.yml
> +    - filebeat
Géré dans le rôle directement, permet notamment d'exécuter le uninstall.

2024-04-22 09:03 UTC, GiooDev approved these changes

2024-04-23 11:39 UTC, Ro3034 commented on deployment/roles/filebeat/defaults/main.yml
> +  keepfiles: 30
est ce qu'on mettrait pas une variable en + et une valeur par défaut à 30 ?

2024-04-23 12:09 UTC, GiooDev commented on deployment/roles/filebeat/defaults/main.yml
> +  keepfiles: 30
C'est ce que je pensais aussi mais c'est déjà une variable dans les defaults donc facilement surchargeable.

Donc en fait la variable existe déjà implicitement ;)

2024-04-23 23:06 UTC, merged