Bugs #12673: allow setting a date to null
ProgrammeVitam/vitam-ui pull request #1744
Opened 2024-04-08 16:20 UTC by ebernard

Modify the DatePickerComponent to allow setting a date to null (relevant change on line 53). Prettier on the rest.

2024-04-08 17:02 UTC, vitam-devops commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [745c8450\-02cc\-4d3b\-a38c\-ee9e7345846b](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=745c8450-02cc-4d3b-a38c-ee9e7345846b&branch=fix_12673_MD_date_removal)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2019-15599](https://devhub.checkmarx.com/cve-details/CVE-2019-15599)|Npm\-tree\-kill\-1\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/745c8450-02cc-4d3b-a38c-ee9e7345846b/vulnerabilities/CVE-2019-15599%3ANpm-tree-kill-1.2.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-28502](https://devhub.checkmarx.com/cve-details/CVE-2020-28502)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/745c8450-02cc-4d3b-a38c-ee9e7345846b/vulnerabilities/CVE-2020-28502%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-36048](https://devhub.checkmarx.com/cve-details/CVE-2020-36048)|Npm\-engine\.io\-3\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/745c8450-02cc-4d3b-a38c-ee9e7345846b/vulnerabilities/CVE-2020-36048%3ANpm-engine.io-3.2.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-36049](https://devhub.checkmarx.com/cve-details/CVE-2020-36049)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/745c8450-02cc-4d3b-a38c-ee9e7345846b/vulnerabilities/CVE-2020-36049%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-7660](https://devhub.checkmarx.com/cve-details/CVE-2020-7660)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/745c8450-02cc-4d3b-a38c-ee9e7345846b/vulnerabilities/CVE-2020-7660%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-7788](https://devhub.checkmarx.com/cve-details/CVE-2020-7788)|Npm\-ini\-1\.3\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/745c8450-02cc-4d3b-a38c-ee9e7345846b/vulnerabilities/CVE-2020-7788%3ANpm-ini-1.3.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2021-31597](https://devhub.checkmarx.com/cve-details/CVE-2021-31597)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/745c8450-02cc-4d3b-a38c-ee9e7345846b/vulnerabilities/CVE-2021-31597%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2022-2421](https://devhub.checkmarx.com/cve-details/CVE-2022-2421)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/745c8450-02cc-4d3b-a38c-ee9e7345846b/vulnerabilities/CVE-2022-2421%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2019-16769](https://devhub.checkmarx.com/cve-details/CVE-2019-16769)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/745c8450-02cc-4d3b-a38c-ee9e7345846b/vulnerabilities/CVE-2019-16769%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-6\.10\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/745c8450-02cc-4d3b-a38c-ee9e7345846b/vulnerabilities/CVE-2020-15366%3ANpm-ajv-6.10.0/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-5\.5\.2|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/745c8450-02cc-4d3b-a38c-ee9e7345846b/vulnerabilities/CVE-2020-15366%3ANpm-ajv-5.5.2/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-28481](https://devhub.checkmarx.com/cve-details/CVE-2020-28481)|Npm\-socket\.io\-2\.1\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/745c8450-02cc-4d3b-a38c-ee9e7345846b/vulnerabilities/CVE-2020-28481%3ANpm-socket.io-2.1.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-7693](https://devhub.checkmarx.com/cve-details/CVE-2020-7693)|Npm\-sockjs\-0\.3\.19|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/745c8450-02cc-4d3b-a38c-ee9e7345846b/vulnerabilities/CVE-2020-7693%3ANpm-sockjs-0.3.19/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2021-23364](https://devhub.checkmarx.com/cve-details/CVE-2021-23364)|Npm\-browserslist\-4\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/745c8450-02cc-4d3b-a38c-ee9e7345846b/vulnerabilities/CVE-2021-23364%3ANpm-browserslist-4.5.5/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2022-21704](https://devhub.checkmarx.com/cve-details/CVE-2022-21704)|Npm\-log4js\-4\.5\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/745c8450-02cc-4d3b-a38c-ee9e7345846b/vulnerabilities/CVE-2022-21704%3ANpm-log4js-4.5.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2022-41940](https://devhub.checkmarx.com/cve-details/CVE-2022-41940)|Npm\-engine\.io\-3\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/745c8450-02cc-4d3b-a38c-ee9e7345846b/vulnerabilities/CVE-2022-41940%3ANpm-engine.io-3.2.1/vulnerabilityDetails)
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|Logging of Sensitive Data|/ansible\.cfg: [2](https://github.com/ProgrammeVitam/vitam-ui/blob/fix_12673_MD_date_removal//tools/docker/mongo/ansible.cfg#L2)|To keep sensitive values out of logs, tasks that expose them need to be marked defining 'no_log' and setting to True
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|Logging of Sensitive Data|/ansible\.cfg: [1](https://github.com/ProgrammeVitam/vitam-ui/blob/fix_12673_MD_date_removal//deployment/ansible.cfg#L1)|To keep sensitive values out of logs, tasks that expose them need to be marked defining 'no_log' and setting to True
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|Logging of Sensitive Data|/ansible\.cfg: [2](https://github.com/ProgrammeVitam/vitam-ui/blob/fix_12673_MD_date_removal//deployment/pki/scripts/lib/ansible.cfg#L2)|To keep sensitive values out of logs, tasks that expose them need to be marked defining 'no_log' and setting to True

2024-04-09 07:52 UTC, Regzox approved these changes

2024-04-12 12:38 UTC, marob requested changes
Ne fonctionne pas.
En partant de :
![image](https://github.com/ProgrammeVitam/vitam-ui/assets/3486231/d208c862-bf44-4ee4-a2d3-9107d1eccf05)
Si j'appuie sur la touche <- (delete) avec le curseur tout à droite, j'obtiens :
![image](https://github.com/ProgrammeVitam/vitam-ui/assets/3486231/ad4d2941-4374-4992-bff1-acbbaebf4255)
Si j'appuie à nouveau sur <-, j'obtiens :
![image](https://github.com/ProgrammeVitam/vitam-ui/assets/3486231/ed1395ba-6627-4261-8bc5-21ff9579a7cf)

Par ailleurs, le composant datepicker : 
- n'est pas présent dans le starter-kit
- n'est pas exporté depuis frontend-common (et donc ne peut pas être réutilisé, y compris dans starter-kit)
- est en doublon avec le datepicker "natif" matDatepicker présenté dans le starter-kit

2024-04-15 07:20 UTC, ebernard commented
> Ne fonctionne pas. En partant de : ![image](https://private-user-images.githubusercontent.com/3486231/321983395-d208c862-bf44-4ee4-a2d3-9107d1eccf05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjUyNjUsIm5iZiI6MTcxMzE2NDk2NSwicGF0aCI6Ii8zNDg2MjMxLzMyMTk4MzM5NS1kMjA4Yzg2Mi1iZjQ0LTRlZTQtYTJkMy05MTA3ZDFlY2NmMDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTVUMDcwOTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmViNmU4NWVkNmQ0YjllZjk1MjMyNmYwMTdmYjQ3MmQxYjQwOTU0N2IxYzhkNWZhMGU2YjRhODFjOGVhNjE2ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4heKryd3FnKmrbDlb3tCDy-Hk_JLx91lPS5lyS3ab1A) Si j'appuie sur la touche <- (delete) avec le curseur tout à droite, j'obtiens : ![image](https://private-user-images.githubusercontent.com/3486231/321983573-ad4d2941-4374-4992-bff1-acbbaebf4255.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjUyNjUsIm5iZiI6MTcxMzE2NDk2NSwicGF0aCI6Ii8zNDg2MjMxLzMyMTk4MzU3My1hZDRkMjk0MS00Mzc0LTQ5OTItYmZmMS1hY2JiYWViZjQyNTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTVUMDcwOTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzQ1NWJmMjhjOTNhNTRlZTMxYjU4OTA3MDFjMGM4Mjk4ODE3MGY2OTMzNjY2MGFiOTBmYzkwMmZhODY5Y2NkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.h6R_b0e1A55fVyUIjJXhPCkF3c2QzVKP5T67QfS0quk) Si j'appuie à nouveau sur <-, j'obtiens : ![image](https://private-user-images.githubusercontent.com/3486231/321983657-ed1395ba-6627-4261-8bc5-21ff9579a7cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjUyNjUsIm5iZiI6MTcxMzE2NDk2NSwicGF0aCI6Ii8zNDg2MjMxLzMyMTk4MzY1Ny1lZDEzOTViYS02NjI3LTQyNjEtOGJjNS0yMWZmOTU3OWE3Y2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTVUMDcwOTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmUwNzc2MjRjN2RjZDVhYjMwYzI5Y2VkMmNhYzc1NWQ0MWNkMTNjNTdiYTJlYTUxZmUzZjk0ZmI5ZjcwMjM3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.u6qUXXEJ3TdcVxLQ6omestGYQUP-Xeq67Cnmi_e6M68)
> 
> Par ailleurs, le composant datepicker :
> 
> * n'est pas présent dans le starter-kit
> * n'est pas exporté depuis frontend-common (et donc ne peut pas être réutilisé, y compris dans starter-kit)
> * est en doublon avec le datepicker "natif" matDatepicker présenté dans le starter-kit

La solution présentée dans le ticket était de sélectionner le contenu du champ avec Ctrl-A et de supprimer tout. Ce cas est réglé par cette PR.

La vraie solution est bien de ne pas avoir deux implémentations du date picker, mais j'estime que l'on sort du cadre d'un correctif de bug, surtout si on prend en compte le fait que le matDatePicker envoie date et heure et qu'il pose des problèmes de fuseaux horaires.

Je te remercie pour l'export du composant et ajout dans starter-kit, je fusionne ton commit "WIP" avec le reste.

2024-04-23 15:24 UTC, ebernard commented
Problème à nouveau soulevé dans le ticket Tuleap 12737

2024-04-23 15:26 UTC, marob approved these changes

2024-04-23 15:29 UTC, ebernard commented
Ticket Tuleap créé pour remplacement du composant : 12766

2024-04-23 15:29 UTC, merged