bugs #12702 fix(archive-unit): fields order
ProgrammeVitam/vitam-ui pull request #1766
Opened 2024-04-15 14:58 UTC by Regzox

## Description

Corrige le classement des champs des unité d'archive en mode edition.

2024-04-15 15:14 UTC, vitam-devops commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [a83f0a09\-ea0c\-4325\-9070\-e56fd712f0a9](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=a83f0a09-ea0c-4325-9070-e56fd712f0a9&branch=bugs_12702)
### No New Or Fixed Issues Found

2024-04-15 15:32 UTC, bbenaissa requested changes

2024-04-15 15:32 UTC, bbenaissa commented on ui/ui-frontend-common/src/app/modules/archive/archive-unit-template.ts
> +export const ordenedFields: string[] = [
orderedFields ?

2024-04-15 15:32 UTC, bbenaissa commented on ui/ui-frontend-common/src/app/modules/archive/archive-unit-template.ts
> +export const ordenedFields: string[] = [
Tu ne peux pas l'externaliser hors du fichier du template, pour ne pas charger le doc

2024-04-16 08:04 UTC, laedanrex approved these changes

2024-04-16 08:20 UTC, Regzox commented on ui/ui-frontend-common/src/app/modules/archive/archive-unit-template.ts
> +export const ordenedFields: string[] = [
J'ai split le fichier.

2024-04-16 08:53 UTC, bbenaissa approved these changes

2024-04-16 13:37 UTC, merged