Story #12687: MD datetime display small
ProgrammeVitam/vitam-ui pull request #1810
Opened 2024-04-25 14:39 UTC by laedanrex

2024-04-25 14:55 UTC, vitam-devops commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [28ced19b\-51e0\-4a49\-8ac2\-39a3c7dc6c34](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=28ced19b-51e0-4a49-8ac2-39a3c7dc6c34&branch=12687-md-date-small-display)

### Fixed Issues
Severity|Issue|Source File / Package
---|---|---
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[Cx366abb53-9fde](https://devhub.checkmarx.com/cve-details/Cx366abb53-9fde)|Npm\-es5\-ext\-0\.10\.62

2024-04-26 16:29 UTC, Regzox approved these changes

2024-04-29 08:54 UTC, marob requested changes
90% des modifications sont du formatage. Ce serait bien de revert pour ne garder que le code réellement modifié.

2024-04-29 08:54 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-viewer/services/schema-element-to-display-rule.service.ts
> +    }
Pourquoi forcer la size pour un datetime ? Ne peut-on pas changer ça côté schéma ?

2024-04-29 10:31 UTC, laedanrex commented on ui/ui-frontend-common/src/app/modules/object-viewer/services/schema-element-to-display-rule.service.ts
> +    }
Je n'ai pas exploré cette option.     
Est-ce possible de mettre un default pour tous les datetime ?

2024-04-29 12:05 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-viewer/services/schema-element-to-display-rule.service.ts
> +    }
Pour moi, la taille dépends de ce qui a été défini au niveau de l'ontologie. Cette taille est "recopiée" dans le schéma, et on se base dessus côté front.
Y'a pas de taille par défaut à définir en fonction du type de champ. Si tous les datetime doivent être small, on passe toutes les dates à small dans l'ontologie.

2024-04-29 13:40 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-viewer/services/schema-element-to-display-rule.service.ts
> +    }
Finalement, le StringSize ne s'applique qu'aux String. Or, là on est sur une date, donc ce n'est pas pertinent.
À voir donc si on change la taille par défaut à small ou si on fait une exception pour les dates, sachant que dans les MD internes, toutes celles qui ont une taille et qui ne sont pas de typeDetail String sont small.

2024-04-29 13:42 UTC, marob approved these changes

2024-04-29 15:54 UTC, merged