Deploy starter kit
ProgrammeVitam/vitam-ui pull request #1839
Opened 2024-05-02 12:38 UTC by marob

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2024-05-02 12:53 UTC, vitam-devops commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [1b339184\-b2f7\-4656\-9dec\-7bf3edd3fbfd](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=1b339184-b2f7-4656-9dec-7bf3edd3fbfd&branch=deploy-starter-kit)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2024-31573](https://devhub.checkmarx.com/cve-details/CVE-2024-31573)|Maven\-org\.xmlunit:xmlunit\-core\-2\.8\.4|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/1b339184-b2f7-4656-9dec-7bf3edd3fbfd/vulnerabilities/CVE-2024-31573%3AMaven-org.xmlunit%3Axmlunit-core-2.8.4/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|Passwords And Secrets \- Generic Password|/vitamui\_vars\.yml: [241](https://github.com/ProgrammeVitam/vitam-ui/blob/deploy-starter-kit//deployment/environments/group_vars/all/vitamui_vars.yml#L241)|Query to find passwords and secrets in infrastructure code.

### Fixed Issues
Severity|Issue|Source File / Package
---|---|---
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|Passwords And Secrets \- Generic Password|/vitamui\_vars\.yml: [238](https://github.com/ProgrammeVitam/vitam-ui/blob/deploy-starter-kit//deployment/environments/group_vars/all/vitamui_vars.yml#L238)

2024-05-02 19:03 UTC, ebernard approved these changes
Le déploiement du module n'est pas désactivable, mais je ne sais pas si c'est une possibilité pour les autres modules, donc ok pour moi. Je me suis permis de pinguer les ops.

2024-05-03 08:15 UTC, marob commented
> Le déploiement du module n'est pas désactivable, mais je ne sais pas si c'est une possibilité pour les autres modules, donc ok pour moi. Je me suis permis de pinguer les ops.

Je pense effectivement qu'il faudrait pouvoir rendre le déploiement optionnel.
Mais il y a peut-être aussi quelques autres sujets à creuser :
- ne pas ajouter de host + port 8004 + ProxyPass + certificats => servir direct depuis le nginx ?
- renommer starter-kit par un nom plus clair, genre design-system

2024-05-03 13:03 UTC, ebernard commented
> * ne pas ajouter de host + port 8004 + ProxyPass + certificats => servir direct depuis le nginx ?

Je pense que les ops ne voudront pas forcément gérer un cas particulier. Ça sera de toute façon un service à faible traffic, donc pourquoi se donner cette peine ?

> * renommer starter-kit par un nom plus clair, genre design-system

Je plussoie.

2024-05-06 07:01 UTC, laedanrex commented on deployment/ansible-vitamui-exploitation/start_vitamui.yml
> +  tags: frontend_apps
On devrait peut-être mettre un `tag` ou un `when` afin de rendre paramétrable le démarrage de ce service, de même pour le déploiement ?

2024-05-06 07:01 UTC, laedanrex approved these changes

2024-05-06 15:36 UTC, marob commented
Déployé sur ga et zo.
Seul ga possède un `hosts_ui_design_system`, ce qui fait que le design system n'a été déployé que sur celui-ci.
![image](https://github.com/ProgrammeVitam/vitam-ui/assets/3486231/44a5f9e6-024e-4406-a3f8-aeed73822db5)

Par défaut, le design system n'est donc pas déployé (sauf si on ajoute un host group `hosts_ui_design_system`), ce qu'on devrait faire sur l'ensemble de nos envs bac à sable mais pas sur les environnements clients.

L'app starter-kit a été renommée design-system.

2024-05-06 15:37 UTC, marob commented on deployment/ansible-vitamui-exploitation/start_vitamui.yml
> +  tags: frontend_apps
J'utilise finalement le group `hosts_ui_design_system`. S'il n'est pas défini (ce qui devrait être le cas pour les clients, mais pas chez nous), les rôles correspondants ne s'exécutent pas.

2024-05-06 16:07 UTC, GiooDev requested changes

2024-05-06 16:07 UTC, GiooDev commented on deployment/ansible-vitamui/frontend_apps.yml
> +- hosts: hosts_ui_design_system
Pourquoi pas le conditionnel ici aussi ?

2024-05-06 16:07 UTC, GiooDev commented on deployment/environments/hosts-ui.example
> +# EDIT: Only if you want to deploy the design system
Rajouter la mention Optionnal

2024-05-07 08:06 UTC, ebernard approved these changes

2024-05-07 08:06 UTC, ebernard commented on deployment/ansible-vitamui-exploitation/start_vitamui.yml
> +  tags: frontend_apps
On a vu ça ensemble, donc ça me va :-)

2024-05-27 12:29 UTC, GiooDev requested changes

2024-05-27 12:29 UTC, GiooDev commented on deployment/environments/group_vars/all/vitamui_vars.yml
> +    port_service: 8004
Ptetre utiliser un autre port car en cas de déploiement mono-instance c'est déjà le port de functional-admin.

2024-05-28 09:20 UTC, GiooDev commented on deployment/environments/group_vars/all/vitamui_vars.yml
> +    port_service: 8004
On peut prendre le 9016 par exemple

2024-05-28 11:37 UTC, GiooDev requested changes

2024-05-28 11:37 UTC, GiooDev commented on ui/ui-design-system/pom.xml
> +        <version>7.1.0-SNAPSHOT</version>
Attention la version n'est plus à jour avec develop.

2024-05-29 09:42 UTC, GiooDev approved these changes
À voir pour se synchroniser avec la PR #1874 car il semble y avoir des modifications qui risquent de venir en conflit.

2024-05-29 14:01 UTC, merged