Bug 12809 authentication keys fixes & 12810 fixing display elements on password screen
ProgrammeVitam/vitam-ui pull request #1848
Opened 2024-05-13 08:22 UTC by hazco75

## Description

Bug 12809 authentication keys fixes
Bug 12810 fixing display elements on password screen

## Type de changement:

* Correction

## Documentation:

## Contributeur

VAS (Vitam Accessible en Service)

2024-05-13 08:34 UTC, marob requested changes

2024-05-13 08:34 UTC, marob commented on cas/cas-server/src/main/resources/templates/customerForm.html
> +      <button id="main-form-submit" class="Button" type="submit" form="main-form">SUIVANT</button>
Pas d'i18n ?

2024-05-13 08:34 UTC, marob commented on cas/cas-server/src/main/resources/templates/layout.html
> +        SUIVANT
Pas d'i18n ?

2024-05-13 08:34 UTC, marob commented on cas/cas-server/src/main/resources/overriden_messages_en.properties
> +cas.authentication.password.create=Create a new password.
```suggestion
cas.authentication.password.create=Create a new password
```

2024-05-13 08:34 UTC, marob commented on cas/cas-server/src/main/resources/overriden_messages.properties
> +cas.authentication.password.create=Créer un nouveau mot de passe
Sur la maquette, c'est avec un "z" :
```suggestion
cas.authentication.password.create=Créez un nouveau mot de passe
```

2024-05-13 08:34 UTC, marob commented on cas/cas-server/src/main/resources/overriden_messages_fr.properties
> +cas.authentication.password.create=Créer un nouveau mot de passe
Sur la maquette, c'est avec un "z" :
```suggestion
cas.authentication.password.create=Créez un nouveau mot de passe
```

2024-05-13 08:34 UTC, marob commented on cas/cas-server/src/main/resources/templates/passwordForm.html
>    </form>
Mauvaise indentation

2024-05-13 08:38 UTC, vitam-devops commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [5f62372a\-882e\-4391\-a336\-f7422df24abe](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=5f62372a-882e-4391-a336-f7422df24abe&branch=bug_12809_authentication_keys_fixes)
### No New Or Fixed Issues Found

2024-05-13 10:19 UTC, hazco75 commented on cas/cas-server/src/main/resources/templates/customerForm.html
> +      <button id="main-form-submit" class="Button" type="submit" form="main-form">SUIVANT</button>
Je ne trouve pas de fr.json dans cas-server

2024-05-13 10:19 UTC, hazco75 commented on cas/cas-server/src/main/resources/templates/layout.html
> +        SUIVANT
Idem

2024-05-13 13:05 UTC, hazco75 commented on cas/cas-server/src/main/resources/overriden_messages_en.properties
> +cas.authentication.password.create=Create a new password.
Modifié

2024-05-13 13:06 UTC, hazco75 commented on cas/cas-server/src/main/resources/overriden_messages.properties
> +cas.authentication.password.create=Créer un nouveau mot de passe
Modifié

2024-05-13 13:06 UTC, hazco75 commented on cas/cas-server/src/main/resources/overriden_messages_fr.properties
> +cas.authentication.password.create=Créer un nouveau mot de passe
Modifié

2024-05-13 13:06 UTC, hazco75 commented on cas/cas-server/src/main/resources/templates/passwordForm.html
>    </form>
Modifié

2024-05-13 14:25 UTC, Regzox commented on cas/cas-server/src/main/resources/templates/customerForm.html
> +      <button id="main-form-submit" class="Button" type="submit" form="main-form">SUIVANT</button>
Faut créer les messages manquant dans les fichiers .properties et mettre du th:text sur ton bouton.

2024-05-13 14:25 UTC, Regzox commented on cas/cas-server/src/main/resources/templates/passwordForm.html
> +  <a href="javascript:void(0)"
C'est plus basé sur le flag passwordManagementEnabled ?

2024-05-13 15:18 UTC, hazco75 commented on cas/cas-server/src/main/resources/templates/customerForm.html
> +      <button id="main-form-submit" class="Button" type="submit" form="main-form">SUIVANT</button>
C'est fait

2024-05-13 15:19 UTC, hazco75 commented on cas/cas-server/src/main/resources/templates/passwordForm.html
> +  <a href="javascript:void(0)"
J'ai juste changé la disposition des labels, je n'ai pas eu à modifier ce flag

2024-05-14 09:05 UTC, hazco75 commented on cas/cas-server/src/main/resources/templates/passwordForm.html
> +  <a href="javascript:void(0)"
J'ai fait la modif que tu m'as mentionné @Regzox

2024-05-14 13:49 UTC, marob approved these changes

2024-05-14 15:58 UTC, Regzox approved these changes

2024-05-14 16:14 UTC, merged