bug #12554 : Fixing buttons display bugs in confirm/save/delete dialogs
ProgrammeVitam/vitam-ui pull request #1863
Opened 2024-05-17 14:52 UTC by hazco75

## Description

(Reopened) Fixing buttons display bugs in confirm/save/delete dialogs

## Type de changement:

* Correction

## Contributeur

VAS (Vitam Accessible en Service)

2024-05-17 15:08 UTC, vitam-devops commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [84a43e2a\-9d2c\-4de3\-b600\-a3aa4f6a5d1c](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=84a43e2a-9d2c-4de3-b600-a3aa4f6a5d1c&branch=bug_12554_reopen_popups_displaying_bug)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2019-15599](https://devhub.checkmarx.com/cve-details/CVE-2019-15599)|Npm\-tree\-kill\-1\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/84a43e2a-9d2c-4de3-b600-a3aa4f6a5d1c/vulnerabilities/CVE-2019-15599%3ANpm-tree-kill-1.2.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-28502](https://devhub.checkmarx.com/cve-details/CVE-2020-28502)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/84a43e2a-9d2c-4de3-b600-a3aa4f6a5d1c/vulnerabilities/CVE-2020-28502%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-36048](https://devhub.checkmarx.com/cve-details/CVE-2020-36048)|Npm\-engine\.io\-3\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/84a43e2a-9d2c-4de3-b600-a3aa4f6a5d1c/vulnerabilities/CVE-2020-36048%3ANpm-engine.io-3.2.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-36049](https://devhub.checkmarx.com/cve-details/CVE-2020-36049)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/84a43e2a-9d2c-4de3-b600-a3aa4f6a5d1c/vulnerabilities/CVE-2020-36049%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-7660](https://devhub.checkmarx.com/cve-details/CVE-2020-7660)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/84a43e2a-9d2c-4de3-b600-a3aa4f6a5d1c/vulnerabilities/CVE-2020-7660%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-7788](https://devhub.checkmarx.com/cve-details/CVE-2020-7788)|Npm\-ini\-1\.3\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/84a43e2a-9d2c-4de3-b600-a3aa4f6a5d1c/vulnerabilities/CVE-2020-7788%3ANpm-ini-1.3.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2021-31597](https://devhub.checkmarx.com/cve-details/CVE-2021-31597)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/84a43e2a-9d2c-4de3-b600-a3aa4f6a5d1c/vulnerabilities/CVE-2021-31597%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2022-2421](https://devhub.checkmarx.com/cve-details/CVE-2022-2421)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/84a43e2a-9d2c-4de3-b600-a3aa4f6a5d1c/vulnerabilities/CVE-2022-2421%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[Reflected_XSS_All_Clients](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/84a43e2a-9d2c-4de3-b600-a3aa4f6a5d1c/sast/description/79/8481125285487743346)|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService\.java: [118](https://github.com/ProgrammeVitam/vitam-ui/blob/bug_12554_reopen_popups_displaying_bug//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/InternalSecurityService.java#L118)|[Attack Vector](https://eu.ast.checkmarx.net/results/84a43e2a-9d2c-4de3-b600-a3aa4f6a5d1c/3f06ff53-d733-40ac-a6fb-49e415cb793f/sast?result-id=YH79G9MaIP584zcSHWMomXHWDFY%3D&redirect=true)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[Absolute_Path_Traversal](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/84a43e2a-9d2c-4de3-b600-a3aa4f6a5d1c/sast/description/36/4635938147065118004)|/ui/ui\-referential/src/main/java/fr/gouv/vitamui/referential/rest/OntologyController\.java: [206](https://github.com/ProgrammeVitam/vitam-ui/blob/bug_12554_reopen_popups_displaying_bug//ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/OntologyController.java#L206)|[Attack Vector](https://eu.ast.checkmarx.net/results/84a43e2a-9d2c-4de3-b600-a3aa4f6a5d1c/3f06ff53-d733-40ac-a6fb-49e415cb793f/sast?result-id=Upz8IPjATgmcRS9B6wdlKgZ44eo%3D&redirect=true)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[Absolute_Path_Traversal](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/84a43e2a-9d2c-4de3-b600-a3aa4f6a5d1c/sast/description/36/4635938147065118004)|/ui/ui\-pastis/src/main/java/fr/gouv/vitamui/pastis/rest/ProfileController\.java: [245](https://github.com/ProgrammeVitam/vitam-ui/blob/bug_12554_reopen_popups_displaying_bug//ui/ui-pastis/src/main/java/fr/gouv/vitamui/pastis/rest/ProfileController.java#L245)|[Attack Vector](https://eu.ast.checkmarx.net/results/84a43e2a-9d2c-4de3-b600-a3aa4f6a5d1c/3f06ff53-d733-40ac-a6fb-49e415cb793f/sast?result-id=x1eCwLJcHgcsozlpqYzOJL10Ux8%3D&redirect=true)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[Absolute_Path_Traversal](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/84a43e2a-9d2c-4de3-b600-a3aa4f6a5d1c/sast/description/36/4635938147065118004)|/ui/ui\-pastis/src/main/java/fr/gouv/vitamui/pastis/rest/ArchivalProfileUnitController\.java: [211](https://github.com/ProgrammeVitam/vitam-ui/blob/bug_12554_reopen_popups_displaying_bug//ui/ui-pastis/src/main/java/fr/gouv/vitamui/pastis/rest/ArchivalProfileUnitController.java#L211)|[Attack Vector](https://eu.ast.checkmarx.net/results/84a43e2a-9d2c-4de3-b600-a3aa4f6a5d1c/3f06ff53-d733-40ac-a6fb-49e415cb793f/sast?result-id=Z2QuLwWz8qYb%2BDj6FI0cJVty15g%3D&redirect=true)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[Absolute_Path_Traversal](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/84a43e2a-9d2c-4de3-b600-a3aa4f6a5d1c/sast/description/36/4635938147065118004)|/ui/ui\-referential/src/main/java/fr/gouv/vitamui/referential/rest/FileFormatController\.java: [244](https://github.com/ProgrammeVitam/vitam-ui/blob/bug_12554_reopen_popups_displaying_bug//ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/FileFormatController.java#L244)|[Attack Vector](https://eu.ast.checkmarx.net/results/84a43e2a-9d2c-4de3-b600-a3aa4f6a5d1c/3f06ff53-d733-40ac-a6fb-49e415cb793f/sast?result-id=uyoD5VfQRPBrRSOMArgfTbFWYrE%3D&redirect=true)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[Absolute_Path_Traversal](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/84a43e2a-9d2c-4de3-b600-a3aa4f6a5d1c/sast/description/36/4635938147065118004)|/ui/ui\-referential/src/main/java/fr/gouv/vitamui/referential/rest/AgencyController\.java: [214](https://github.com/ProgrammeVitam/vitam-ui/blob/bug_12554_reopen_popups_displaying_bug//ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/AgencyController.java#L214)|[Attack Vector](https://eu.ast.checkmarx.net/results/84a43e2a-9d2c-4de3-b600-a3aa4f6a5d1c/3f06ff53-d733-40ac-a6fb-49e415cb793f/sast?result-id=5MM%2B8L58NtNO1BndouHFIeokMPI%3D&redirect=true)
![MEDIUM](https://cdn.ast.checkmarx.net/integr [...]

2024-05-21 08:30 UTC, marob requested changes

2024-05-21 08:30 UTC, marob commented on ui/ui-frontend-common/src/sass/_button.scss
> +    &:hover {
Non, il faut garder au focus sinon le style est KO quand on navigue au clavier (TAB)

2024-05-22 14:14 UTC, hazco75 commented on ui/ui-frontend-common/src/sass/_button.scss
> +    &:hover {
C'est corrigé. J'ai trouvé la solution pour le focus

2024-05-24 08:18 UTC, marob commented on ui/ui-frontend-common/src/app/modules/object-editor/components/group-editor/group-editor.component.ts
> +  private readonly dialogConfig: MatDialogConfig = { panelClass: 'vitamui-dialog', width: '800px', autoFocus: false };
@hazco75  C'est pour quoi le `autoFocus: false` ?

2024-05-24 08:30 UTC, hazco75 commented on ui/ui-frontend-common/src/app/modules/object-editor/components/group-editor/group-editor.component.ts
> +  private readonly dialogConfig: MatDialogConfig = { panelClass: 'vitamui-dialog', width: '800px', autoFocus: false };
Lorsque la popup s'ouvre, le focus est déjà activé sur le premier bouton, d'où le fait qu'il soit noir. J'utilise l'`autofocus : false` pour désactiver ce comportement

2024-05-24 10:59 UTC, marob approved these changes

2024-05-24 14:12 UTC, ebernard approved these changes

2024-05-24 15:42 UTC, merged