Angular upgrade
ProgrammeVitam/vitam-ui pull request #1892
Opened 2024-06-03 17:15 UTC by marob

## Description

*Description des modifications*

## Type de changement

*Indiquer le ou les types de changements*

* Build
* PKI
* Ansiblerie
* Nouveau Code
* Correction
* Refactorisation de code
* Autre

## Documentation

*Indiquer la documentation mise à jour*

* [ ] Quels sont les nouvelles documentations ?
* [ ] Quels sont les modifications existantes ?
* [ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

* manuel
* environnement
* TU

## Migration

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist

*Sélectionner les éléments de la checklist*

* [ ] Mon code suit le style de code de ce projet.
* [ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.
* [ ] J'ai fait les changements correspondant dans la documentation RAML.
* [ ] J'ai fait les changements correspondant dans la documentation Métier.
* [ ] J'ai fait les changements correspondant dans la documentation Technique.
* [ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.
* [ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.
* [ ] Les tests unitaires nouveaux et existants passent avec succès localement.
* [ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

* VAS (Vitam Accessible en Service)
* CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2024-06-03 17:29 UTC, vitam-devops commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [3de31a51\-df3d\-4993\-a344\-9e2e04351f92](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=3de31a51-df3d-4993-a344-9e2e04351f92&branch=angular-upgrade)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2019-15599](https://devhub.checkmarx.com/cve-details/CVE-2019-15599)|Npm\-tree\-kill\-1\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3de31a51-df3d-4993-a344-9e2e04351f92/vulnerabilities/CVE-2019-15599%3ANpm-tree-kill-1.2.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-28502](https://devhub.checkmarx.com/cve-details/CVE-2020-28502)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3de31a51-df3d-4993-a344-9e2e04351f92/vulnerabilities/CVE-2020-28502%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-36048](https://devhub.checkmarx.com/cve-details/CVE-2020-36048)|Npm\-engine\.io\-3\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3de31a51-df3d-4993-a344-9e2e04351f92/vulnerabilities/CVE-2020-36048%3ANpm-engine.io-3.2.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-36049](https://devhub.checkmarx.com/cve-details/CVE-2020-36049)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3de31a51-df3d-4993-a344-9e2e04351f92/vulnerabilities/CVE-2020-36049%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-7660](https://devhub.checkmarx.com/cve-details/CVE-2020-7660)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3de31a51-df3d-4993-a344-9e2e04351f92/vulnerabilities/CVE-2020-7660%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-7788](https://devhub.checkmarx.com/cve-details/CVE-2020-7788)|Npm\-ini\-1\.3\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3de31a51-df3d-4993-a344-9e2e04351f92/vulnerabilities/CVE-2020-7788%3ANpm-ini-1.3.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2021-31597](https://devhub.checkmarx.com/cve-details/CVE-2021-31597)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3de31a51-df3d-4993-a344-9e2e04351f92/vulnerabilities/CVE-2021-31597%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2022-2421](https://devhub.checkmarx.com/cve-details/CVE-2022-2421)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3de31a51-df3d-4993-a344-9e2e04351f92/vulnerabilities/CVE-2022-2421%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2023-45133](https://devhub.checkmarx.com/cve-details/CVE-2023-45133)|Npm\-babel\-traverse\-6\.26\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3de31a51-df3d-4993-a344-9e2e04351f92/vulnerabilities/CVE-2023-45133%3ANpm-babel-traverse-6.26.0/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2019-16769](https://devhub.checkmarx.com/cve-details/CVE-2019-16769)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3de31a51-df3d-4993-a344-9e2e04351f92/vulnerabilities/CVE-2019-16769%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-6\.10\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3de31a51-df3d-4993-a344-9e2e04351f92/vulnerabilities/CVE-2020-15366%3ANpm-ajv-6.10.0/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-5\.5\.2|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3de31a51-df3d-4993-a344-9e2e04351f92/vulnerabilities/CVE-2020-15366%3ANpm-ajv-5.5.2/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-28481](https://devhub.checkmarx.com/cve-details/CVE-2020-28481)|Npm\-socket\.io\-2\.1\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3de31a51-df3d-4993-a344-9e2e04351f92/vulnerabilities/CVE-2020-28481%3ANpm-socket.io-2.1.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-7693](https://devhub.checkmarx.com/cve-details/CVE-2020-7693)|Npm\-sockjs\-0\.3\.19|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3de31a51-df3d-4993-a344-9e2e04351f92/vulnerabilities/CVE-2020-7693%3ANpm-sockjs-0.3.19/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2021-23364](https://devhub.checkmarx.com/cve-details/CVE-2021-23364)|Npm\-browserslist\-4\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3de31a51-df3d-4993-a344-9e2e04351f92/vulnerabilities/CVE-2021-23364%3ANpm-browserslist-4.5.5/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2022-21704](https://devhub.checkmarx.com/cve-details/CVE-2022-21704)|Npm\-log4js\-4\.5\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3de31a51-df3d-4993-a344-9e2e04351f92/vulnerabilities/CVE-2022-21704%3ANpm-log4js-4.5.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2022-41940](https://devhub.checkmarx.com/cve-details/CVE-2022-41940)|Npm\-engine\.io\-3\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/3de31a51-df3d-4993-a344-9e2e04351f92/vulnerabilities/CVE-2022-41940%3ANpm-engine.io-3.2.1/vulnerabilityDetails)
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|Logging of Sensitive Data|/ansible\.cfg: [2](https://github.com/ProgrammeVitam/vitam-ui/blob/angular-upgrade//deployment/pki/scripts/lib/ansible.cfg# L2)|To keep sensitive values out of logs, tasks that expose them need to be marked defining 'no_log' and setting to True
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|Logging of Sensitive Data|/ansible\.cfg: [2](https://github.com/ProgrammeVitam/vitam-ui/blob/angular-upgrade//tools/docker/mongo/ansible.cfg# L2)|To keep sensitive values out of logs, tasks that expose them need to be marked defining 'no_log' and setting to True
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|Logging of Sensitive Data|/ansible\.cfg: [1](https://github.com/ProgrammeVitam/vitam-ui/blob/angular-upgrade//deployment/ansibl [...]

2024-06-06 08:24 UTC, Regzox approved these changes

2024-06-06 08:24 UTC, laedanrex approved these changes

2024-06-06 12:33 UTC, bbenaissa requested changes

2024-06-06 12:33 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/transfer-acknowledgment/transfer-acknowledgment.component.spec.ts
> +  it('should parseXmlToTransferDetails for valid XML', async () => {
ça n'a pas de relation avec la migration, ça serai mieux qu'on la sépare dans un autre commit

2024-06-06 12:33 UTC, bbenaissa commented on ui/ui-frontend/projects/ingest/src/sass/_material-theme.scss
> +    50: white,
Pourquoi ce changement?

2024-06-06 12:33 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/app-routing.module.ts
> +      relativeLinkResolution: 'legacy',
Est ce qu'on ne peut pas corriger l'url pour eviter le type legacy?

2024-06-06 13:29 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/transfer-acknowledgment/transfer-acknowledgment.component.spec.ts
> +  it('should parseXmlToTransferDetails for valid XML', async () => {
Si, la lib xml2js casse le build en Angular 12 et il faut donc utiliser une autre lib à la place. Pour garantir que je casse rien, je suis revenu sur Angular 11, j'ai ajouté un test avant de remplacer xml2js et puis j'ai remplacé par une autre lib et adapté le code et je suis repassé en Angular 12.

2024-06-06 13:31 UTC, marob commented on ui/ui-frontend/projects/ingest/src/sass/_material-theme.scss
> +    50: white,
Hmm, bonne question. C'est pas moi qui ait fait la modif, c'est le CLI Angular.

2024-06-06 13:31 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/app-routing.module.ts
> +      relativeLinkResolution: 'legacy',
Peut-être, c'est une modif auto par le CLI Angular.

2024-06-06 14:22 UTC, bbenaissa approved these changes

2024-06-06 14:49 UTC, merged