Bug #12685 : hide _sps field when having one value
ProgrammeVitam/vitam-ui pull request #1900
Opened 2024-06-13 08:27 UTC by IsmailHam87

## Description

*Description des modifications*

## Type de changement

*Indiquer le ou les types de changements*

* Build
* PKI
* Ansiblerie
* Nouveau Code
* Correction
* Refactorisation de code
* Autre

## Documentation

*Indiquer la documentation mise à jour*

* [ ] Quels sont les nouvelles documentations ?
* [ ] Quels sont les modifications existantes ?
* [ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

* manuel
* environnement
* TU

## Migration

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist

*Sélectionner les éléments de la checklist*

* [ ] Mon code suit le style de code de ce projet.
* [ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.
* [ ] J'ai fait les changements correspondant dans la documentation RAML.
* [ ] J'ai fait les changements correspondant dans la documentation Métier.
* [ ] J'ai fait les changements correspondant dans la documentation Technique.
* [ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.
* [ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.
* [ ] Les tests unitaires nouveaux et existants passent avec succès localement.
* [ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

* VAS (Vitam Accessible en Service)
* CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2024-06-13 08:50 UTC, vitam-devops commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [a3c97390\-5903\-40d8\-a35e\-3b0665946ad7](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=a3c97390-5903-40d8-a35e-3b0665946ad7&branch=bugs-%2312685-hide-_sps-field-with-one-value)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2019-15599](https://devhub.checkmarx.com/cve-details/CVE-2019-15599)|Npm\-tree\-kill\-1\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a3c97390-5903-40d8-a35e-3b0665946ad7/vulnerabilities/CVE-2019-15599%3ANpm-tree-kill-1.2.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-28502](https://devhub.checkmarx.com/cve-details/CVE-2020-28502)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a3c97390-5903-40d8-a35e-3b0665946ad7/vulnerabilities/CVE-2020-28502%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-36048](https://devhub.checkmarx.com/cve-details/CVE-2020-36048)|Npm\-engine\.io\-3\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a3c97390-5903-40d8-a35e-3b0665946ad7/vulnerabilities/CVE-2020-36048%3ANpm-engine.io-3.2.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-36049](https://devhub.checkmarx.com/cve-details/CVE-2020-36049)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a3c97390-5903-40d8-a35e-3b0665946ad7/vulnerabilities/CVE-2020-36049%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-7660](https://devhub.checkmarx.com/cve-details/CVE-2020-7660)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a3c97390-5903-40d8-a35e-3b0665946ad7/vulnerabilities/CVE-2020-7660%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2020-7788](https://devhub.checkmarx.com/cve-details/CVE-2020-7788)|Npm\-ini\-1\.3\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a3c97390-5903-40d8-a35e-3b0665946ad7/vulnerabilities/CVE-2020-7788%3ANpm-ini-1.3.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2021-31597](https://devhub.checkmarx.com/cve-details/CVE-2021-31597)|Npm\-xmlhttprequest\-ssl\-1\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a3c97390-5903-40d8-a35e-3b0665946ad7/vulnerabilities/CVE-2021-31597%3ANpm-xmlhttprequest-ssl-1.5.5/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2022-2421](https://devhub.checkmarx.com/cve-details/CVE-2022-2421)|Npm\-socket\.io\-parser\-3\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a3c97390-5903-40d8-a35e-3b0665946ad7/vulnerabilities/CVE-2022-2421%3ANpm-socket.io-parser-3.2.0/vulnerabilityDetails)
![HIGH](https://cdn.ast.checkmarx.net/integrations/severity/High.png)|[CVE-2023-45133](https://devhub.checkmarx.com/cve-details/CVE-2023-45133)|Npm\-babel\-traverse\-6\.26\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a3c97390-5903-40d8-a35e-3b0665946ad7/vulnerabilities/CVE-2023-45133%3ANpm-babel-traverse-6.26.0/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2019-16769](https://devhub.checkmarx.com/cve-details/CVE-2019-16769)|Npm\-serialize\-javascript\-1\.9\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a3c97390-5903-40d8-a35e-3b0665946ad7/vulnerabilities/CVE-2019-16769%3ANpm-serialize-javascript-1.9.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-6\.10\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a3c97390-5903-40d8-a35e-3b0665946ad7/vulnerabilities/CVE-2020-15366%3ANpm-ajv-6.10.0/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-15366](https://devhub.checkmarx.com/cve-details/CVE-2020-15366)|Npm\-ajv\-5\.5\.2|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a3c97390-5903-40d8-a35e-3b0665946ad7/vulnerabilities/CVE-2020-15366%3ANpm-ajv-5.5.2/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-28481](https://devhub.checkmarx.com/cve-details/CVE-2020-28481)|Npm\-socket\.io\-2\.1\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a3c97390-5903-40d8-a35e-3b0665946ad7/vulnerabilities/CVE-2020-28481%3ANpm-socket.io-2.1.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2020-7693](https://devhub.checkmarx.com/cve-details/CVE-2020-7693)|Npm\-sockjs\-0\.3\.19|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a3c97390-5903-40d8-a35e-3b0665946ad7/vulnerabilities/CVE-2020-7693%3ANpm-sockjs-0.3.19/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2021-23364](https://devhub.checkmarx.com/cve-details/CVE-2021-23364)|Npm\-browserslist\-4\.5\.5|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a3c97390-5903-40d8-a35e-3b0665946ad7/vulnerabilities/CVE-2021-23364%3ANpm-browserslist-4.5.5/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2022-21704](https://devhub.checkmarx.com/cve-details/CVE-2022-21704)|Npm\-log4js\-4\.5\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a3c97390-5903-40d8-a35e-3b0665946ad7/vulnerabilities/CVE-2022-21704%3ANpm-log4js-4.5.1/vulnerabilityDetails)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2022-41940](https://devhub.checkmarx.com/cve-details/CVE-2022-41940)|Npm\-engine\.io\-3\.2\.1|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/reports/a3c97390-5903-40d8-a35e-3b0665946ad7/vulnerabilities/CVE-2022-41940%3ANpm-engine.io-3.2.1/vulnerabilityDetails)
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|Logging of Sensitive Data|/ansible\.cfg: [2](https://github.com/ProgrammeVitam/vitam-ui/blob/bugs-#12685-hide-_sps-field-with-one-value//deployment/pki/scripts/lib/ansible.cfg# L2)|To keep sensitive values out of logs, tasks that expose them need to be marked defining 'no_log' and setting to True
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|Logging of Sensitive Data|/ansible\.cfg: [2](https://github.com/ProgrammeVitam/vitam-ui/blob/bugs-#12685-hide-_sps-field-with-one-value//tools/docker/mongo/ansible.cfg# L2)|To keep sensitive values out of logs, tasks that expose them need to be marked defining 'no_log' and setting to True
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|Logging of Sensitive Data|/ansible\.cfg: [1] [...]

2024-06-13 09:23 UTC, laedanrex commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/object-viewer/components/list/list.component.html
> +  [value]="displayObject.value.length === 1 ? '' : displayObject.value"
est ce qu'on veut la balise vide ?        
sinon on peut mettre displayObject.value.length > 1 dans le ngIf ?

2024-06-13 09:25 UTC, IsmailHam87 commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/object-viewer/components/list/list.component.html
> +  [value]="displayObject.value.length === 1 ? '' : displayObject.value"
ce que j'ai compris du bug c'est supprimer toute la balise dans le cas d'une seule valeur.

2024-06-13 10:02 UTC, Regzox requested changes

2024-06-13 10:02 UTC, Regzox commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/object-viewer/components/list/list.component.html
> +  [value]="displayObject.value.length === 1 ? '' : displayObject.value"
Je ne suis pas convaincu, j'ai l'impression qu'il va y avoir des effets de bords avec d'autres champs.

Idée de test => Tags avec un seul élément sera à priori flingué

2024-06-13 10:02 UTC, Regzox commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/object-viewer/components/list/list.component.html
> +  [value]="displayObject.value.length === 1 ? '' : displayObject.value"
Si c'est le cas, alors faut juste ajouter un filtre post traitement de l'arbre de displayObject pour hide le champ en question quand la condition est rencontrée (_sps && length === 1)

2024-06-13 13:42 UTC, IsmailHam87 commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/object-viewer/components/list/list.component.html
> +  [value]="displayObject.value.length === 1 ? '' : displayObject.value"
les modifications sont appliquées pour éviter les effets de bords.

2024-06-13 13:54 UTC, Regzox approved these changes

2024-06-14 12:38 UTC, laedanrex approved these changes

2024-06-14 13:13 UTC, merged

2024-06-17 08:53 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/archive-unit-edit-object.service.ts
> +    const hasOneValue = Boolean(displayObject.displayRule.ui.Path === '#originating_agencies' && displayObject.value.length === 1);
@IsmailHam87 Pourquoi mettre `Boolean(...)` ?

2024-06-17 08:53 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/archive-unit-edit-object.service.ts
> +    displayObject.children.forEach((child) => this.hideSpsFieldWithOneValue(child));
@IsmailHam87  A-t-on besoin de parcourir toute l'arborescence ?

2024-06-17 13:05 UTC, IsmailHam87 commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/archive-unit-edit-object.service.ts
> +    const hasOneValue = Boolean(displayObject.displayRule.ui.Path === '#originating_agencies' && displayObject.value.length === 1);
car dans le cas où il y a plusieurs valeurs, celles-ci devrait s'afficher.

2024-06-17 13:07 UTC, IsmailHam87 commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/archive-unit-edit-object.service.ts
> +    displayObject.children.forEach((child) => this.hideSpsFieldWithOneValue(child));
Oui car il faut éviter quelques effets de bords sur d'autres champs autre que _sps

2024-06-17 13:11 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/archive-unit-edit-object.service.ts
> +    const hasOneValue = Boolean(displayObject.displayRule.ui.Path === '#originating_agencies' && displayObject.value.length === 1);
Ce que je veux dire, c'est qu'on pourrait très bien écrire : `const hasOneValue = displayObject.displayRule.ui.Path === '#originating_agencies' && displayObject.value.length === 1;`

2024-06-17 13:13 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/archive-unit-edit-object.service.ts
> +    displayObject.children.forEach((child) => this.hideSpsFieldWithOneValue(child));
Il me semblait que le _sps était à la racine et qu'il n'était pas nécessaire d'avoir du code récursif. Mais bon, ça devrait marcher, c'est juste qu'on perds peut-être juste du temps à parcourir toute l'arborescence pour rien.

2024-06-17 13:18 UTC, IsmailHam87 commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/archive-unit-edit-object.service.ts
> +    const hasOneValue = Boolean(displayObject.displayRule.ui.Path === '#originating_agencies' && displayObject.value.length === 1);
ah d'accord, je peux l'adapter, est ce que c'est mieux côté perf ?

2024-06-17 13:37 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/archive-unit-edit-object.service.ts
> +    const hasOneValue = Boolean(displayObject.displayRule.ui.Path === '#originating_agencies' && displayObject.value.length === 1);
Si ça marche, on peut laisser je pense. Mais c'est surtout que j'ai jamais vu cette manière d'écrire le code et que ça ajoute du code pour rien. L'expression étant déjà un booléen, il n'y a pas de raison d'essayer de la convertir en booléen.

2024-06-17 13:44 UTC, IsmailHam87 commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/archive-unit-edit-object.service.ts
> +    const hasOneValue = Boolean(displayObject.displayRule.ui.Path === '#originating_agencies' && displayObject.value.length === 1);
c'est vrai j'ai pas fait attention qu'il fait juste le cast, je vais corriger..