Story 12306
ProgrammeVitam/vitam-ui pull request #1933
Opened 2024-07-05 14:29 UTC by Regzox

## Description

Update Java 17

2024-07-11 14:44 UTC, ebernard commented on commons/commons-test/src/test/java/fr/gouv/vitamui/commons/test/AbstractMongoTests.java
> +    public static final MongoDBContainer mongoDBContainer = new MongoDBContainer("mongo:7.0.11");
À sortir dans une propriété du yaml de config

2024-07-15 08:34 UTC, GiooDev requested changes

2024-07-15 08:34 UTC, GiooDev commented on Jenkinsfile
> +        label 'java11'
java11 ?

2024-07-15 09:52 UTC, Regzox commented on Jenkinsfile
> +        label 'java11'
https://progvitam.slack.com/archives/CE7HWCC0G/p1721034370093009?thread_ts=1721033552.997219&cid=CE7HWCC0G :wink:

2024-07-15 13:15 UTC, ebernard commented on api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/cas/service/CasServiceIntegrationTest.java
> +    @Disabled
Créer un ticket pour ne pas oublier de réactiver ces tests, lorsque c'est pertinent.

2024-07-15 13:15 UTC, ebernard commented on api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/customer/service/InitCustomerServiceIntegrationTest.java
> +    }
Pourquoi pas `extends AbstractMongoTests` ici ?

2024-07-15 13:15 UTC, ebernard commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/IngestContractServiceTest.java
> +            BadRequestException.class
Ce n'est pas le même type d'Exception qu'avant. C'était un bug dans le code précédent ?

2024-07-15 13:15 UTC, ebernard commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/VitamUIAccessContractServiceTest.java
> +        MockitoAnnotations.openMocks(VitamUIAccessContractServiceTest.class);
Pas nécessaire si tu utilises `@ExtendWith(MockitoExtension.class)`

2024-07-15 13:15 UTC, ebernard commented on commons/commons-test/src/test/java/fr/gouv/vitamui/commons/test/AbstractMongoTests.java
> +    private static final MongoDBContainer mongoDBContainer = new MongoDBContainer("mongo:7.0.8");
Je croyais que tu avais mis l'image `mongo:7.0.8` comme une propriété de l'application.yml ?

2024-07-15 13:15 UTC, ebernard commented on commons/commons-mongo/src/test/java/fr/gouv/vitamui/commons/mongo/Application.java
À quoi ça sert ?

2024-07-15 13:15 UTC, ebernard commented on commons/commons-rest/src/test/java/fr/gouv/vitamui/commons/rest/controller/RestExceptionHandlerTest.java
> +@RunWith(SpringRunner.class)
Convertir en JUnit 5 ? (@ExtendWith)

2024-07-15 13:15 UTC, ebernard commented on commons/commons-vitam/src/test/java/fr/gouv/vitamui/commons/vitam/api/util/VitamRestUtilsTest.java
> +    public static void setup() {}
Méthodes setup vides à supprimer.

2024-07-15 13:28 UTC, Regzox commented on api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/customer/service/InitCustomerServiceIntegrationTest.java
> +    }
Ce test est non indépendant. Si d'autres font des modifications sur la base de données, il tombe en KO car il compte les éléments d'un findAll.

Du coup, ici on instancie une db pour le test uniquement.

2024-07-15 13:31 UTC, ebernard commented on commons/commons-vitam/src/test/java/fr/gouv/vitamui/commons/vitam/api/util/VitamRestUtilsTest.java
> +    public static void setup() {}
Fait.

2024-07-15 13:31 UTC, Regzox commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/IngestContractServiceTest.java
> +            BadRequestException.class
Oui, j'ai eu ce test qui ne passait pas...

Le test décrit l'obtention d'une 400 alors que l'assert attendait du 500 initialement.

2024-07-15 13:32 UTC, ebernard commented on api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/customer/service/InitCustomerServiceIntegrationTest.java
> +    }
ok.

2024-07-15 13:32 UTC, ebernard commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/IngestContractServiceTest.java
> +            BadRequestException.class
ok.

2024-07-15 13:34 UTC, ebernard commented on api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/customer/service/InitCustomerServiceIntegrationTest.java
> +    }
Il faudrait quand même mettre la constante `mongo:7.0.8` ailleurs.

2024-07-15 13:36 UTC, Regzox commented on commons/commons-test/src/test/java/fr/gouv/vitamui/commons/test/AbstractMongoTests.java
> +    private static final MongoDBContainer mongoDBContainer = new MongoDBContainer("mongo:7.0.8");
J'ai pas réussi à le faire correctement. Je peux retenter l'expérience mais j'ai pas l'impression que ça soit une bonne chose que d'avoir du context spring boot et junit dans une classe abstraite. De plus, j'ai peur que ça n'implique d'ajouter un `mongo.version` dans plusieurs fichiers `application.yml`.

2024-07-15 13:38 UTC, ebernard commented on commons/commons-test/src/test/java/fr/gouv/vitamui/commons/test/AbstractMongoTests.java
> +    private static final MongoDBContainer mongoDBContainer = new MongoDBContainer("mongo:7.0.8");
Ok. On va botter en touche pour le moment. Peut être ajouter la tâche dans un ticket de dette technique ?

2024-07-15 13:51 UTC, Regzox commented on commons/commons-rest/src/test/java/fr/gouv/vitamui/commons/rest/controller/RestExceptionHandlerTest.java
> +@RunWith(SpringRunner.class)
C'est fait

2024-07-15 13:59 UTC, Regzox commented on commons/commons-mongo/src/test/java/fr/gouv/vitamui/commons/mongo/Application.java
C'est pas terrible mais j'ai ajouté ça pour être dans un contexte spring boot et chargé les @Repository de la partie `main`...

2024-07-15 14:05 UTC, ebernard commented on commons/commons-mongo/src/test/java/fr/gouv/vitamui/commons/mongo/Application.java
Ok.

2024-07-15 14:06 UTC, ebernard commented on api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/cas/service/CasServiceIntegrationTest.java
> +    @Disabled
Cf https://assistance.programmevitam.fr/plugins/tracker/?aid=13153

2024-07-15 14:06 UTC, ebernard commented on commons/commons-test/src/test/java/fr/gouv/vitamui/commons/test/AbstractMongoTests.java
> +    public static final MongoDBContainer mongoDBContainer = new MongoDBContainer("mongo:7.0.11");
Cf commentaire plus bas.

2024-07-15 14:07 UTC, ebernard approved these changes

2024-07-15 15:41 UTC, ebernard commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/VitamUIAccessContractServiceTest.java
> +        MockitoAnnotations.openMocks(VitamUIAccessContractServiceTest.class);
Voir le ticket Tuleap 13153

2024-07-15 15:50 UTC, ghost reviewed
Not sure why vitam-ui logger was removed. Too many updates, I am not sure why it was required

2024-07-16 07:52 UTC, laedanrex approved these changes

2024-07-16 11:22 UTC, lgheribi approved these changes

2024-07-16 11:22 UTC, ghost commented on api/api-archive-search/archive-search-internal/pom.xml
> +            <groupId>org.jetbrains</groupId>
Why?

2024-07-16 11:22 UTC, ghost commented on deployment/roles/normalize/tasks/check_java.yml
> +        - openjdk-11-jdk-headless
To be tested - probable conflict during upgrade when having col-localized components

2024-07-16 11:22 UTC, ghost commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/config/CustomerInitConfig.java
> +    private String filename;
Unused?

2024-07-16 11:22 UTC, ghost commented on lombok.config
> +lombok.log.flagUsage = warning
Si on remplace la couche VitamUILogger directement par slf4j, je suis pour la généralisation du lombok.

2024-07-16 11:22 UTC, ghost commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/identity/ServerIdentityConfiguration.java
> +public class ServerIdentityConfiguration {
Pas sûr de comprendre à quoi elle sert à présent.
Si inutilisée, faudrait la supprimer + les classes liées, ainsi que la conf `server-identity.*`

2024-07-16 11:22 UTC, ghost commented on pom.xml
> +                <version>1.19.8</version>
use property

2024-07-16 11:22 UTC, lgheribi commented on commons/commons-mongo/src/main/java/fr/gouv/vitamui/commons/mongo/codec/OffsetDateTimeCodecProvider.java
> +public class OffsetDateTimeCodecProvider implements CodecProvider {
Unused? same with `OffsetDateTimeCodec`

2024-07-16 12:05 UTC, lgheribi commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/identity/ServerIdentityConfiguration.java
> +public class ServerIdentityConfiguration {
Si le prefix de logs est vraiment utilisé, il faut mettre à jour la conf de logs ou autre solution.
Sinon, à supprimer.

2024-07-16 12:07 UTC, lgheribi commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/logbook/service/IamLogbookService.java
> +    @Transactional
Si c'était du bug, faut-il backporter?

2024-07-16 12:13 UTC, Regzox commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/logbook/service/IamLogbookService.java
> +    @Transactional
Dans les tests on entre dans du transactional à partir d'un certain moment et on passe à travers des méthodes non transactionnelles. Les tests plantaient sans ces modifications après upgrade java 17 + junit 5.

2024-07-16 12:15 UTC, Regzox commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/logbook/service/IamLogbookService.java
> +    @Transactional
Je ne pense pas qu'il faille backport, les tests semblent fonctionner dans les version précédentes.

2024-07-16 12:15 UTC, Regzox commented on commons/commons-mongo/src/main/java/fr/gouv/vitamui/commons/mongo/codec/OffsetDateTimeCodecProvider.java
> +public class OffsetDateTimeCodecProvider implements CodecProvider {
Oui, date du temps ou je tentais d'update flatdoodle. Je vais clean.

2024-07-16 12:20 UTC, Regzox commented on pom.xml
> +                <version>1.19.8</version>
done

2024-07-16 12:29 UTC, Regzox commented on api/api-archive-search/archive-search-internal/pom.xml
> +            <groupId>org.jetbrains</groupId>
fixed

2024-07-16 12:32 UTC, Regzox commented on deployment/roles/normalize/tasks/check_java.yml
> +        - openjdk-11-jdk-headless
Je suis d'accord, j'ai juste repris la logique qu'il y avait dans le rôle entre java 8 et java 11.

2024-07-16 12:34 UTC, Regzox commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/config/CustomerInitConfig.java
> +    private String filename;
Bien vu, j'avais ajouté ça pour logger la valeur car je ne comprenais pas de quel fichier de conf elle venait.

2024-07-16 12:39 UTC, Regzox commented on lombok.config
> +lombok.log.flagUsage = warning
Yes, c'est pas remplacé pour le coup, mais j'autorise l'usage sans warning.

2024-07-16 12:49 UTC, GiooDev commented on Jenkinsfile
> +        label 'java11'
Ok, on mettra ça à jour plus tard. On a une story en cours pour améliorer tout ça :)

2024-07-16 13:56 UTC, GiooDev approved these changes

2024-07-16 14:10 UTC, merged