story #13140 : new datepicker component for design system
ProgrammeVitam/vitam-ui pull request #1970
Opened 2024-08-01 08:22 UTC by hazco75

## Description

Nouveau composant datepicker pour l'instant destiné pour le design-system

## Type de changement

*Indiquer le ou les types de changements*

* Nouveau Code

## Contributeur

* VAS (Vitam Accessible en Service)

2024-08-01 09:22 UTC, Regzox approved these changes

2024-08-01 09:22 UTC, Regzox commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +  }
```
map: { [key: PickerType]: string } = {
  year: 'YYYY',
  month: 'MM/YYYY',
  day: 'DD/MM/YYYY'
}

get display() {

  return {
    dateInput: this.dateInput,
    monthYearLabel: 'MMM YYYY',
    dateA11yLabel: 'LL',
    monthYearA11yLabel: 'MMMM YYYY',
  };

  get dateInput() {
     return map[this.format];
  }
}
```

2024-08-01 09:22 UTC, Regzox commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +    if (this.pickerType === 'day') {
logger ou suppression

2024-08-01 09:22 UTC, Regzox commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +      this.date.setValue(year);
sert à quoi d'update l'ancienne date si on remplace par la nouvelle ?

2024-08-01 09:22 UTC, Regzox commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +      this.date.setValue(val);
idem

2024-08-01 09:22 UTC, Regzox commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +    }
Fonctionne pas avec les DD/MM/YYYY ?

2024-08-01 09:22 UTC, Regzox commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +  @Input() pickerType: 'year' | 'month' | 'day' = 'day';
type <PickerType | Picker>

2024-08-01 09:22 UTC, Regzox commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +    }
Doit être traduit ?

2024-08-01 09:22 UTC, Regzox commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.html
> +  <mat-hint>Format attendu : {{ dateInputLabelPattern }}</mat-hint>
Doit être traduit ?

2024-08-05 10:10 UTC, marob requested changes
Si le datepicker est disabled, on ne devrait pas pouvoir avoir de focus
![image](https://github.com/user-attachments/assets/02a4b0e9-620e-43b0-a65e-be67bbacbea6)

Il manque un effet "hover" sur la sélection des années/mois/jour
![image](https://github.com/user-attachments/assets/4bf71c66-df64-4cf1-926e-47226557e3f3)

Le composant ne gère pas le cas "required".

Si on saisit une valeur incorrecte, le label et la valeur s'affichent l'une sur l'autre (et aucune erreur ne s'affiche) :
![image](https://github.com/user-attachments/assets/4bbfbbbc-1120-4efd-90b3-e86eac2c97b8)

2024-08-05 10:10 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/theme.service.ts
> +      colors[key + '-500'] = '#9E9E9E';
Utile ?

2024-08-05 10:10 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/sass/mixins/_fonts.scss
> +  }
Utile ?

2024-08-05 10:10 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +    this.date = new FormControl(moment());
Pourquoi initialiser avec la date du jour ?

2024-08-05 10:10 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +    this.date = new FormControl(moment());
Ne pas utiliser moment

2024-08-05 10:10 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.html
> +  <i class="vitamui-icon vitamui-icon-calendar {{ disabled ? 'grey-500' : 'primary' }}" (click)="datepicker.open()"></i>
On peut appliquer le style "disabled" ou non en utilisant un @HostBinding sur le champ `disabled`

2024-08-05 10:10 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.html
> +    startView="multi-year"
On doit ouvrir le jour par défaut (le mois si on ne peut sélectionner que année/mois et l'année si on ne peut sélectionner que l'année)

2024-08-05 10:10 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.html
> +  <label #label> Date </label>
Il manque l'i18n.

2024-08-05 10:10 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.html
> +  <label #label> Date </label>
Quand on clique sur "Date", ça ne focus pas le champ.

2024-08-05 10:10 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.html
> +  <i class="vitamui-icon vitamui-icon-calendar {{ disabled ? 'grey-500' : 'primary' }}" (click)="datepicker.open()"></i>
Le hover devrait afficher un curseur "main"

2024-08-05 10:10 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.html
> +  />
Seul le centre du composant (l'input) ou le bouton sont cliquables. Les bords du composant ne sont pas cliquable. Ce n'est pas pratique.

2024-08-05 10:10 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +  @HostBinding('class.vitamui-focused') focused = false;
Le focus "décale" l'input d'1px, ce qui risque de casser le montage

2024-08-05 10:10 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +import moment, { default as _rollupMoment, Moment } from 'moment';
Moment c'est mal

2024-08-05 10:10 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +// const moment = _rollupMoment || _moment;
Supprimer

2024-08-05 10:10 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +  @Input() type = 'text';
Inutile

2024-08-05 10:10 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +  @Input() value: string;
À quoi sert la value ? Pourquoi une string et pas plutôt une Date ?

2024-08-05 10:10 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +    this.input.nativeElement.style.color = this.disabled ? '#616161' : '#212121';
Il ne faut pas manipuler le DOM à la main.

2024-08-05 10:10 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.scss
> +    0 0.6px 2px 0 rgba(33, 33, 33, 0.2) !important;
Il faudrait plutôt définir ça dans le style global, en remplacement des anciennes ".elevation-box"

2024-08-05 10:10 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.scss
> +}
Tous les nouveaux composants vont avoir un style similaire. Il faudrait peut-être le rendre global, voire créer un composant dédié

2024-08-05 10:10 UTC, marob commented on ui/ui-frontend/projects/design-system/src/app/components/inputs/inputs.component.html
> +    </div>
Ajouter plus de cas :
- sans/avec valeur initiale
- required ou non
- active
- error

2024-08-12 09:28 UTC, hazco75 commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +  }
Plus besoin finalement @marob @Regzox

2024-08-12 09:28 UTC, hazco75 commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +      this.date.setValue(year);
Corrigé

2024-08-12 09:28 UTC, hazco75 commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +      this.date.setValue(val);
Corrigé

2024-08-12 09:28 UTC, hazco75 commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +    }
C'est traduit

2024-08-12 09:29 UTC, hazco75 commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +  @Input() pickerType: 'year' | 'month' | 'day' = 'day';
Créé

2024-08-12 09:29 UTC, hazco75 commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.html
> +  <mat-hint>Format attendu : {{ dateInputLabelPattern }}</mat-hint>
C'est traduit

2024-08-12 09:48 UTC, marob requested changes
La date saisie n'est pas reflétée (saisie : 2021, en surbrillance : 2024)
![image](https://github.com/user-attachments/assets/55fcd4fe-6ed4-4a8a-aa60-d1f2c119e5f6)

Il est possible de basculer sur un écran de saisie de jour en cliquant sur l'année, même lorsque le datepicker est configuré pour saisir seulement une année ou année/mois
![image](https://github.com/user-attachments/assets/dc7d7a3a-cb48-42a2-93bb-3b8e56def03b)

En navigation au clavier, il n'y a pas de surbrillance des années/mois/jours sur lesquels on a le "focus".

Un clic sur le mat-hint ne devrait pas focus le champ.

Le curseur de la souris n'est pas le même en hover sur l'input et sur "Date" ou les bords du champ. Il faudrait que ce soit un `cursor: text` partout.

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.html
> +  </div>
Les erreurs ne devraient pas s'afficher si le champ n'est pas dirty.
Ce comportement devrait être centralisé et unifié pour tout type de champ de formulaire (un composant commun a été commencé [ici](https://github.com/ProgrammeVitam/vitam-ui/blob/715d03f1d6cf63139cc88171659fe1fb67c7b030/ui/ui-frontend/projects/vitamui-library/src/app/modules/components/form-error-display/form-error-display.component.ts))

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
> +    }
Dans [la MR de Daniel](https://github.com/ProgrammeVitam/vitam-ui/blob/715d03f1d6cf63139cc88171659fe1fb67c7b030/ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json#L5604), la clé est plutôt `ERRORS.XXX`. Par ailleurs, le message pour "required" n'est pas le même => à uniformiser.

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +  @Input() value: string;
Cette valeur découle directement de `this.date.value` => supprimer

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +  @HostBinding('class.vitamui-float') labelFloat = false;
Cette valeur découle directement de `this.date.value` => supprimer

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +  }
Trop peu précis : ça focus même quand on clique sur les mat-hint

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/design-system/src/app/components/inputs/inputs.component.html
> +    </div>
Il manque juste un cas "active"

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/design-system/src/app/components/inputs/inputs.component.html
> +        [pickerType]="'year'"
Tu peux l'écrire plus simplement (perso, je préfère)
```suggestion
        pickerType="year"
```

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/design-system/src/app/components/inputs/inputs.component.html
> +        [value]="'02/2022'"
L'input `value` ne devrait pas exister => à supprimer.
En plus, ce n'est pas la même valeur que celle du formControl...

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/design-system/src/app/components/inputs/inputs.component.html
> +        [value]="'2022'"
L'input `value` ne devrait pas exister => à supprimer.
En plus, ce n'est pas la même valeur que celle du formControl...

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/design-system/src/app/components/inputs/inputs.component.html
> +        [value]="'02/2022'"
L'input `value` ne devrait pas exister => à supprimer.
En plus, ce n'est pas la même valeur que celle du formControl...

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/design-system/src/app/components/inputs/inputs.component.html
> +        [value]="'2022'"
L'input `value` ne devrait pas exister => à supprimer.
En plus, ce n'est pas la même valeur que celle du formControl...

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.html
> +    style="visibility: hidden; position: absolute; pointer-events: none"
À mettre dans le SCSS

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +  onDateChange(date: Date) {
Renommer en `setDayMonthAndYear` ?

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.html
> +  </div>
Je pense qu'il faut aussi l'afficher si le form est invalide mais pristine.

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.scss
> +    color: rgba(193, 0, 0, 1);
```suggestion
    color: $red;
```

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +  private _disabled = false;
Inutile. Utiliser `this.date.disabled` à la place.

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +  @HostBinding('class.vitamui-focused') focused = false;
Il faut utiliser le CSS `:focus-within` plutôt que du JS.

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +  dateInputLabelPattern: string;
Inutile. Dans le template, utiliser:
```html
<mat-hint> {{ 'DATE.EXPECTED_FORMAT' | translate: { format: 'DATE.FORMAT.' + pickerType | translate } }} </mat-hint>
```

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +  dayMonthYearRegExp = new RegExp(
Pas lisible, non maintenable.

Je préférerai utiliser une fonction. Par exemple (basé sur une réponse ChatGPT) :
```typescript
this.date.addValidators((control) => {
        function isValidDate(dateString: string) {
          // Step 1: Split the string into components
          const parts = dateString.split('-');
          if (parts.length !== 3) {
            return false; // Invalid format
          }

          // Step 2: Convert to integers
          const year = parseInt(parts[0], 10);
          const month = parseInt(parts[1], 10) - 1; // Months are zero-based (0 = January, 11 = December)
          const day = parseInt(parts[2], 10);

          // Step 3: Create a Date object
          const date = new Date(year, month, day);

          // Step 4: Check for validity
          if (date.getFullYear() !== year || date.getMonth() !== month || date.getDate() !== day) {
            return false; // The date is not valid
          }

          return true; // The date is valid
        }
        return isValidDate(control.value) ? null : { pattern: true };
      });
```

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +    if (ngControl) {
Le cas `null` est-il possible ?

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +    this.labelFloat = !!this.value;
Supprimer

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +    });
Supprimer

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +      this.date.addValidators(Validators.pattern(this.dayMonthYearRegExp));
```suggestion
      this.date.addValidators((control) => {
        function isValidDate(dateString: string) {
          // Step 1: Split the string into components
          const parts = dateString.split('-');
          if (parts.length !== 3) {
            return false; // Invalid format
          }

          // Step 2: Convert to integers
          const year = parseInt(parts[0], 10);
          const month = parseInt(parts[1], 10) - 1; // Months are zero-based (0 = January, 11 = December)
          const day = parseInt(parts[2], 10);

          // Step 3: Create a Date object
          const date = new Date(year, month, day);

          // Step 4: Check for validity
          if (date.getFullYear() !== year || date.getMonth() !== month || date.getDate() !== day) {
            return false; // The date is not valid
          }

          return true; // The date is valid
        }
        return isValidDate(control.value) ? null : { pattern: true };
      });
```

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +    this.labelFloat = !!this.value;
Supprimer

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +    if (!this.disabled) {
```suggestion
    if (!this.date.disabled) {
```

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +      this.focused = true;
Supprimer

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +    this.focused = false;
Supprimer

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +  }
Supprimer

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +    this.labelFloat = !!this.value;
```suggestion
    this.date.setValue(this.value);
```

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +      this.onChange(this.datePipe.transform(date, 'yyyy-MM-dd'));
```suggestion
      this.date.setValue(this.datePipe.transform(date, 'yyyy-MM-dd'));
      this.onChange(this.date.value);
```

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +      this.onChange(this.datePipe.transform(year, 'yyyy'));
```suggestion
      this.date.setValue(this.datePipe.transform(year, 'yyyy'));
      this.onChange(this.date.value);
```

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
> +      this.onChange(this.datePipe.transform(monthAndYear, 'yyyy-MM'));
```suggestion
      this.date.setValue(this.datePipe.transform(monthAndYear, 'yyyy-MM'));
      this.onChange(this.date.value);
```

2024-08-12 09:48 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/sass/_table.scss
> -}
Attention aux effets de bord sur les autres composants/écrans

2024-08-13 09:57 UTC, marob approved these changes

2024-08-13 12:12 UTC, merged