Run prettier
ProgrammeVitam/vitam-ui pull request #1971
Opened 2024-08-01 09:49 UTC by laedanrex

run prettier....

2024-08-01 09:51 UTC, Regzox approved these changes

2024-08-01 12:40 UTC, bbenaissa approved these changes

2024-08-05 08:58 UTC, marob requested changes

2024-08-05 08:58 UTC, marob commented on .gitignore
> +.angular/
Ce n'est pas lié à prettier :thinking:

2024-08-05 08:58 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/update-unit-rules/update-unit-rules.component.html
Si j'exécute prettier sur l'ensemble du projet, il y a beaucoup d'autres fichiers qui sont modifiés. Pourquoi n'appliquer prettier que sur celui-là ?

2024-08-06 10:21 UTC, closed without merging