story #13281 feat(pastis): add seda version to editors
ProgrammeVitam/vitam-ui pull request #2005
Opened 2024-08-30 15:06 UTC by Regzox

## Description

Ajoute des chips pour afficher la version de SEDA dans pastis.

2024-09-03 14:32 UTC, marob requested changes
Cas KO :
1. créer un nouveau PUA seda 2.2
2. enregistrer dans le SAE
3. modifier le profil => il est en seda 2.1 (à la création, la version du seda n'est pas dans le payload de l'appel HTTP)

2024-09-03 14:32 UTC, marob commented on api/api-pastis/pastis-external/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
> +    public static final String DEFAULT_SEDA_VERSION = "v2.3";
```suggestion
    public static final String DEFAULT_SEDA_VERSION = "2.3";
```

2024-09-03 14:32 UTC, marob commented on api/api-pastis/pastis-external/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
> +                    : DEFAULT_SEDA_VERSION;
```suggestion
                final String sedaVersion = Optional.ofNullable(handler.getSedaVersion()).orElse(DEFAULT_SEDA_VERSION);
```

2024-09-03 14:32 UTC, marob commented on api/api-pastis/pastis-external/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
> +                    : ProfileVersion.fromVersionString(DEFAULT_SEDA_VERSION);
```suggestion
                final ProfileVersion profileVersion = Optional.ofNullable(profileResponse.getNotice()).map(Notice::getSedaVersion).orElse(ProfileVersion.fromVersionString(DEFAULT_SEDA_VERSION));
```

2024-09-03 14:32 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/chip/chip.module.ts
> +export class ChipModule {}
En faire un standalone component ?

2024-09-03 14:32 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/chip/chip.component.ts
> +export class ChipComponent {
Le [design system](https://www.figma.com/design/m5EfQ0suI0YGr8oqLih0NL/%2F%2FDesign-System-Vitam-UI-(v1-c%C3%B4t%C3%A9-Xelians)?node-id=17252-23705&node-type=FRAME&t=9SN0BXt2AEUSpHBZ-0) (obsolète car Xelians ?) permettait d'avoir plusieurs couleurs et gérer différents niveau de gras dans le texte à l'intérieur du composant.
A voir si on en a besoin ou si c'est un composant "provisoire".

2024-09-04 08:58 UTC, vitam-devops commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [ae34a2e2\-c154\-4cb8\-82dd\-c822fa2b55ae](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=ae34a2e2-c154-4cb8-82dd-c822fa2b55ae&branch=story_13281)
### No New Or Fixed Issues Found

2024-09-04 09:10 UTC, Regzox commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/chip/chip.component.ts
> +export class ChipComponent {
Pour l'instant pas de demandes particulières sur ce composant... On ajoutera les feature manquantes au moment où en aura l'usage.

2024-09-04 12:59 UTC, ebernard commented on ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
> +    return this.getAllProfilesVitam();
Les `return` ne servent à rien.

2024-09-04 12:59 UTC, ebernard approved these changes

2024-09-04 16:31 UTC, marob approved these changes

2024-09-05 07:44 UTC, merged