Story#12969: clean current collect and archive-search profiles and create new profiles
ProgrammeVitam/vitam-ui pull request #2006
Opened 2024-09-02 07:58 UTC by bbenaissa

## Description

L'objecif de cette PR est de nettoyer les profils des applications archive-search et collect, et de créer deux nouveaux profils dans l'application Collect.
 

## Contributeur

* VAS (Vitam Accessible en Service)

2024-09-04 09:25 UTC, GiooDev requested changes

2024-09-04 09:25 UTC, GiooDev commented on deployment/scripts/mongod/v8.0/005_create_new_collect_profiles_for_exist_customers.js.j2
> +        "_id": "PROFIL_" + tenant.identifier + "-COLLECT_APP-Archiviste-gestion-et-collecte",
Vérifier si c'est cohérent par rapport à la convention de nommage des autres profils. 

De mémoire, ça devait être du style:
`PROFIL_<TENANT>-<APP_NAME>-<PROFIL_NAME>`

Avec pour séparateurs des _ dans le nom de PROFIL_NAME et en anglais.
Mais à vérifier si c'est bien comme ça, pas facile de mon téléphone ;)

2024-09-04 13:25 UTC, Regzox approved these changes

2024-09-04 14:14 UTC, bbenaissa commented on deployment/scripts/mongod/v8.0/005_create_new_collect_profiles_for_exist_customers.js.j2
> +        "_id": "PROFIL_" + tenant.identifier + "-COLLECT_APP-Archiviste-gestion-et-collecte",
Effectivement, j'ai pris en compte les modifs

2024-09-06 15:12 UTC, laedanrex approved these changes

2024-09-07 17:21 UTC, GiooDev requested changes

2024-09-07 17:21 UTC, GiooDev commented on deployment/scripts/mongod/v8.0/005_create_new_collect_profiles_for_exist_customers.js.j2
> +        "_id": "PROFIL_" + tenant.identifier + "-COLLECT_APP-ARCHIVISTE-COLLECT-MANAGEMENT",
Le nom semble pas correspondre à ce qui a été fait par exemple ici : https://github.com/ProgrammeVitam/vitam-ui/blob/develop/deployment/scripts/mongod/v6.0/21_create_profile_MANAGEMENT_CONTRACT_APP.js.j2

`ARCHIVISTE_COLLECT_MANAGEMENT`

Mettre des _ pour la séparation du nom final après le app_name.

2024-09-07 18:17 UTC, bbenaissa commented on deployment/scripts/mongod/v8.0/005_create_new_collect_profiles_for_exist_customers.js.j2
> +        "_id": "PROFIL_" + tenant.identifier + "-COLLECT_APP-ARCHIVISTE-COLLECT-MANAGEMENT",
En fait ARCHIVISTE-COLLECT-MANAGEMENT est le nom du profil dans  l'application  COLLECT_APP

2024-09-07 18:20 UTC, bbenaissa commented on deployment/scripts/mongod/v8.0/005_create_new_collect_profiles_for_exist_customers.js.j2
> +        "_id": "PROFIL_" + tenant.identifier + "-COLLECT_APP-ARCHIVISTE-COLLECT-MANAGEMENT",
j'ai mis ARCHIVISTE_COLLECT_MANAGEMENT

2024-09-09 06:12 UTC, GiooDev approved these changes

2024-09-09 06:50 UTC, merged