Story# 13356: clean collect and archive search profiles
ProgrammeVitam/vitam-ui pull request #2032
Opened 2024-09-17 05:03 UTC by bbenaissa

## Description

l'objectif de cette PR est de corriger des roles manquants ou non exploités pour la gestion des profils archive-search et collect.

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

* VAS (Vitam Accessible en Service)

2024-09-17 09:09 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.ts
> +    this.checkDownloadPermissions();
`tenantIdentifier` n'est utile que pour `checkDownloadPermissions()` et on n'a pas de garantie que sa valeur est renseignée avant l'appel à `archiveService.hasArchiveSearchRole`. Il faudrait plutôt récupérer le `tenantIdentifier` dans `checkDownloadPermissions` (pas d'attribut de classe) et pipe avec l'appel au service `hasArchiveSearchRole` (pour garantir l'ordre d'exécution).

À faire aussi dans les autres fichiers modifiés.

2024-09-17 09:23 UTC, Regzox approved these changes

2024-09-17 09:54 UTC, GiooDev requested changes
Message de commit à revoir.

2024-09-24 09:16 UTC, marob approved these changes

2024-09-24 09:16 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.ts
> +    console.log(this.tenantSelectionService.getSelectedTenant());
Supprimer les logs

2024-09-24 09:16 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.ts
> +  tenantIdentifier: number;
On n'a pas besoin du `tenantIdentifier` en dehors de `checkDownloadPermissions()`. Il faudrait donc en faire une constante dans `checkDownloadPermissions()` (ou au moins un attribut privé)

2024-09-24 09:16 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.ts
> +  tenantIdentifier: number;
On n'a pas besoin du `tenantIdentifier` en dehors de `checkDownloadPermissions()`. Il faudrait donc en faire une constante dans `checkDownloadPermissions()` (ou au moins un attribut privé)

2024-09-24 09:16 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/collect-object-group-details-tab/collect-object-group-details-tab.component.ts
> +  tenantIdentifier: number;
On n'a pas besoin du `tenantIdentifier` en dehors de `checkDownloadPermissions()`. Il faudrait donc en faire une constante dans `checkDownloadPermissions()` (ou au moins un attribut privé)

2024-09-24 09:16 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.spec.ts
> +  });
Ce n'est pas suffisant ?
```suggestion
  const tenantSelectionServiceSpy = createSpyObj('TenantSelectionService', ['getSelectedTenant']);
```

2024-09-24 09:16 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/collect-object-group-details-tab/collect-object-group-details-tab.component.spec.ts
> +  });
Ce n'est pas suffisant ?
```suggestion
  const tenantSelectionServiceSpy = createSpyObj('TenantSelectionService', ['getSelectedTenant']);
```

2024-09-24 12:29 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.ts
> +  tenantIdentifier: number;
Je l'ai intégré dans la méthode

2024-09-24 12:29 UTC, bbenaissa commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/collect-object-group-details-tab/collect-object-group-details-tab.component.ts
> +  tenantIdentifier: number;
Je l'ai intégré dans la méthode

2024-09-24 12:30 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.spec.ts
> +  });
Il s'attend au champ identifier

2024-09-24 12:30 UTC, bbenaissa commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/collect-object-group-details-tab/collect-object-group-details-tab.component.spec.ts
> +  });
Il s'attend au champs identifier

2024-09-24 12:31 UTC, bbenaissa commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.ts
> +  tenantIdentifier: number;
Changé dans la méthode

2024-09-24 12:35 UTC, marob commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.spec.ts
> +  });
Ma remarque est qu'on a 2 fois l'objet: une fois dans le spy, une autre fois plus bas. Je voulais éviter la duplication.

2024-09-24 12:36 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/collect-object-group-details-tab/collect-object-group-details-tab.component.spec.ts
> +  });
Ma remarque est qu'on a 2 fois l'objet: une fois dans le spy, une autre fois plus bas. Je voulais éviter la duplication.

2024-09-24 12:45 UTC, bbenaissa commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/collect-object-group-details-tab/collect-object-group-details-tab.component.spec.ts
> +  });
je vois, corrigé

2024-09-24 13:36 UTC, GiooDev approved these changes

2024-09-24 13:39 UTC, merged