bug #13347 : modify user email with dash
ProgrammeVitam/vitam-ui pull request #2142
Opened 2024-10-15 20:09 UTC by IsmailHam87

fixes the dash and point that were considered the same when using equalsIgnoreCase

## Description

*Description des modifications*

## Type de changement

*Indiquer le ou les types de changements*

* Build
* PKI
* Ansiblerie
* Nouveau Code
* Correction
* Refactorisation de code
* Autre

## Documentation

*Indiquer la documentation mise à jour*

* [ ] Quels sont les nouvelles documentations ?
* [ ] Quels sont les modifications existantes ?
* [ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

* manuel
* environnement
* TU

## Migration

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist

*Sélectionner les éléments de la checklist*

* [ ] Mon code suit le style de code de ce projet.
* [ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.
* [ ] J'ai fait les changements correspondant dans la documentation RAML.
* [ ] J'ai fait les changements correspondant dans la documentation Métier.
* [ ] J'ai fait les changements correspondant dans la documentation Technique.
* [ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.
* [ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.
* [ ] Les tests unitaires nouveaux et existants passent avec succès localement.
* [ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

* VAS (Vitam Accessible en Service)
* CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2024-10-16 08:17 UTC, hazco75 approved these changes

2024-10-16 08:46 UTC, laedanrex commented on ui/ui-frontend/projects/identity/src/app/user/user.service.ts
> +    criterionArray.push({ key: 'email', value: email.toLowerCase(), operator: Operators.equals });
c'est etrange, rien a voir avec le titre     
et tu modifs la valeur ?

2024-10-16 09:16 UTC, IsmailHam87 commented on ui/ui-frontend/projects/identity/src/app/user/user.service.ts
> +    criterionArray.push({ key: 'email', value: email.toLowerCase(), operator: Operators.equals });
j'ai expliqué dans la description que le equalsIgnoreCase considère le "-" et le "." comme étant pareils dans l'email de l'utilsateur , ce qui génère le bug, d'où l'utilisation de equals à sa place.

2024-10-16 10:02 UTC, marob requested changes, later dismissed
En retirant l'ignore case, ça laisse la possibilité de créer une duplication d'une adresse mail existante en changeant la "case" d'un ou plusieurs caractères, ce qui crée un nouveau bug.
La correction est plutôt à trouver dans MongoUtils.getCriteria qui prends la `val` tel quel sans l'échapper => le `.` est interprété par la regex comme "tout caractère" au lieu d'un caractère `.` (on a une injection regex !).
Le pb de `.` vs `-` ne se pose pas en equals (vs. equalsIgnoreCase) parce que tant qu'on n'a pas de `*` dans la `val`, on n'utilise pas de regex dans la requête Mongo. Dans le equalsIgnoreCase, on utilise une regex dans tous les cas, et on interprète donc le `.` comme "tout caractère". À corriger donc (pour equals et equalsIgnoreCase) et créer un test.

2025-07-17 08:14 UTC, ebernard commented
> En retirant l'ignore case, ça laisse la possibilité de créer une duplication d'une adresse mail existante en changeant la "case" d'un ou plusieurs caractères, ce qui crée un nouveau bug. La correction est plutôt à trouver dans `MongoUtils.getCriteria` qui prends la `val` tel quel sans l'échapper => le `.` est interprété par la regex comme "tout caractère" au lieu d'un caractère `.` (on a une injection regex !). Le pb de `.` vs `-` ne se pose pas en equals (vs. equalsIgnoreCase) parce que tant qu'on n'a pas de `*` dans la `val`, on n'utilise pas de regex dans la requête Mongo. Dans le equalsIgnoreCase, on utilise une regex dans tous les cas, et on interprète donc le `.` comme "tout caractère". À corriger donc (pour equals et equalsIgnoreCase) et créer un test.

Changements faits.

2025-07-17 08:16 UTC, ebernard commented on ui/ui-frontend/projects/identity/src/app/user/user.service.ts
> +    criterionArray.push({ key: 'email', value: email.toLowerCase(), operator: Operators.equals });
Fait autrement.

2025-07-17 08:20 UTC, vitam-prg commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [481b75c5\-8219\-4248\-9517\-e5cb568d1bcd](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=481b75c5-8219-4248-9517-e5cb568d1bcd&branch=bug_13347_modify_user_email_with_dash)
<!--fix issues section--><details><summary><b>Fixed Issues (13)</b></summary>
Great job! The following issues were fixed in this Pull Request

Severity|Issue|Source File / Package
---|---|---
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|~~[Log_Forging](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/481b75c5-8219-4248-9517-e5cb568d1bcd/sast/description/117/9884244256835554923)~~|/api/api\-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController\.java: [101](https://github.com/ProgrammeVitam/vitam-ui/blob/bug_13347_modify_user_email_with_dash//api/api-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController.java#L101)
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|~~[Log_Forging](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/481b75c5-8219-4248-9517-e5cb568d1bcd/sast/description/117/9884244256835554923)~~|/api/api\-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController\.java: [101](https://github.com/ProgrammeVitam/vitam-ui/blob/bug_13347_modify_user_email_with_dash//api/api-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController.java#L101)
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|~~[Log_Forging](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/481b75c5-8219-4248-9517-e5cb568d1bcd/sast/description/117/9884244256835554923)~~|/api/api\-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController\.java: [114](https://github.com/ProgrammeVitam/vitam-ui/blob/bug_13347_modify_user_email_with_dash//api/api-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController.java#L114)
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|~~[Log_Forging](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/481b75c5-8219-4248-9517-e5cb568d1bcd/sast/description/117/9884244256835554923)~~|/api/api\-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController\.java: [72](https://github.com/ProgrammeVitam/vitam-ui/blob/bug_13347_modify_user_email_with_dash//api/api-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController.java#L72)
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|~~[Log_Forging](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/481b75c5-8219-4248-9517-e5cb568d1bcd/sast/description/117/9884244256835554923)~~|/api/api\-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController\.java: [100](https://github.com/ProgrammeVitam/vitam-ui/blob/bug_13347_modify_user_email_with_dash//api/api-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController.java#L100)
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|~~[Log_Forging](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/481b75c5-8219-4248-9517-e5cb568d1bcd/sast/description/117/9884244256835554923)~~|/api/api\-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController\.java: [114](https://github.com/ProgrammeVitam/vitam-ui/blob/bug_13347_modify_user_email_with_dash//api/api-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController.java#L114)
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|~~[Log_Forging](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/481b75c5-8219-4248-9517-e5cb568d1bcd/sast/description/117/9884244256835554923)~~|/api/api\-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController\.java: [100](https://github.com/ProgrammeVitam/vitam-ui/blob/bug_13347_modify_user_email_with_dash//api/api-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController.java#L100)
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|~~[Log_Forging](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/481b75c5-8219-4248-9517-e5cb568d1bcd/sast/description/117/9884244256835554923)~~|/api/api\-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController\.java: [101](https://github.com/ProgrammeVitam/vitam-ui/blob/bug_13347_modify_user_email_with_dash//api/api-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController.java#L101)
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|~~[Log_Forging](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/481b75c5-8219-4248-9517-e5cb568d1bcd/sast/description/117/9884244256835554923)~~|/api/api\-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController\.java: [72](https://github.com/ProgrammeVitam/vitam-ui/blob/bug_13347_modify_user_email_with_dash//api/api-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController.java#L72)
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|~~[Log_Forging](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/481b75c5-8219-4248-9517-e5cb568d1bcd/sast/description/117/9884244256835554923)~~|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/SecurityService\.java: [175](https://github.com/ProgrammeVitam/vitam-ui/blob/bug_13347_modify_user_email_with_dash//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/SecurityService.java#L175)
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|~~[Log_Forging](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/481b75c5-8219-4248-9517-e5cb568d1bcd/sast/description/117/9884244256835554923)~~|/api/api\-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController\.java: [73](https://github.com/ProgrammeVitam/vitam-ui/blob/bug_13347_modify_user_email_with_dash//api/api-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController.java#L73)
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|~~[Log_Forging](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/481b75c5-8219-4248-9517-e5cb568d1bcd/sast/description/117/9884244256835554923)~~|/api/api\-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController\.java: [115](https://github.com/ProgrammeVitam/vitam-ui/blob/bug_13347_modify_user_email_with_dash//api/api-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController.java#L115)
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|~~[Log_Forging](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/481b75c5-8219-4248-9517-e5cb568d1bcd/sast/description/117/9884244256835554923)~~|/api/api\-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController\.java: [101](https://github.com/ProgrammeVitam/vitam-ui/blob/bug_13347_modify_user_email_with_dash//api/api-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/CollectArchiveUnitController.java#L101)
</details>

<!--fix issues section-->

2025-07-17 09:01 UTC, ebernard approved these changes

2025-07-18 13:56 UTC, bbenaissa approved these changes

2025-07-18 13:57 UTC, merged