bug #13500 : wrong regex error messages
ProgrammeVitam/vitam-ui pull request #2144
Opened 2024-10-16 08:32 UTC by hazco75

## Description

When modifying AU, fixing error messages about datepicker field + provide datepicker component when predefined regex is chosen.

## Type de changement

* Correction

2024-10-16 08:43 UTC, ebernard commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/primitive-editor/primitive-editor.component.html
> +      [pickerType]="setPickerType(editObject)"
Pour ma part je l'aurais plutôt appelé `getPickerType` puisque c'est censé retourner une valeur.

2024-10-16 08:43 UTC, ebernard commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/object-viewer/services/schema-element-to-display-rule.service.ts
> +          console.log(schemaElement);
Enlever

2024-10-16 08:43 UTC, ebernard commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/object-viewer/services/schema-element-to-display-rule.service.ts
> +          if ((schemaElement as ProfiledSchemaElement).Control) {
Créer une variable pour `schemaElement as ProfiledSchemaElement` parce que c'est un peu lourdingue, non ?

2024-10-16 10:11 UTC, marob requested changes

2024-10-16 10:11 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/primitive-editor/primitive-editor.component.ts
> +      } else if (editObject.pattern === '^[0-9]{4}-[0-9]{2}-[0-9]{2}$') {
Utiliser une constante pour les regex (à factoriser avec les valeurs dans file-tree-metadata.component.ts)

2024-10-16 10:11 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/object-viewer/services/schema-element-to-display-rule.service.ts
> +              ['^[0-9]{4}-[0-9]{2}-[0-9]{2}$', '^[0-9]{4}$'].includes((schemaElement as ProfiledSchemaElement).Control.Value)
Idem, constante pour les regex

2024-10-16 10:11 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/sass/_form.scss
> +vitamui-common-input-error {
Mettre le style dans le composant vitamui-common-input-error

2024-10-16 16:41 UTC, marob requested changes

2024-10-16 16:41 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/dates.constants.ts
> +}
Il faut utiliser ces valeurs dans `file-tree-metadata.component.ts`

2024-10-16 16:41 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/vitamui-input/vitamui-input-error.component.scss
> +@import '../../../../../src/sass/variables/colors';
```suggestion
@import '../../../../sass/variables/colors';
```

2024-10-16 16:41 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/vitamui-input/vitamui-input-error.component.scss
> +}
```suggestion
@use '../../../../sass/base/typography';
@import '../../../../sass/variables/colors';

:host {
  @extend .text;
  @extend .caption;
  width: 100%;
  color: $red;
  display: flex;
  align-items: center;
  padding: 5px 0 0 0;

  i {
    @extend .text;
    @extend .caption;
    margin-right: 5px;
  }
}
```

2024-10-18 14:20 UTC, Regzox requested changes

2024-10-18 14:20 UTC, Regzox commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.ts
> +import { DatePatternConstants } from '../../../../../../vitamui-library/src/app/modules/dates.constants';
:warning: traversée de projets

2024-10-18 14:20 UTC, Regzox commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.ts
> +    { label: 'AAAA-MM', value: DatePatternConstants.YEAR_MONTH.toString() },
value: DatePatternConstants ?

2024-10-18 14:20 UTC, Regzox commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/primitive-editor/primitive-editor.component.ts
> +  }
Nécessaire le toString ?

2024-10-18 14:20 UTC, Regzox commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/object-viewer/services/schema-element-to-display-rule.service.ts
> +        }
C'est pas exclusif au champs `Version`

2024-10-21 09:11 UTC, Regzox approved these changes

2024-10-21 09:22 UTC, ebernard approved these changes

2024-10-21 12:46 UTC, hazco75 commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/dates.constants.ts
> +}
C'est fait @marob

2024-10-21 13:17 UTC, marob approved these changes

2024-10-21 13:43 UTC, merged