bug #13482: fix display fields
ProgrammeVitam/vitam-ui pull request #2151
Opened 2024-10-17 08:06 UTC by mohatizaoui

## Description

*Description des modifications*

## Type de changement

*Indiquer le ou les types de changements*

* Build
* PKI
* Ansiblerie
* Nouveau Code
* Correction
* Refactorisation de code
* Autre

## Documentation

*Indiquer la documentation mise à jour*

* [ ] Quels sont les nouvelles documentations ?
* [ ] Quels sont les modifications existantes ?
* [ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

* manuel
* environnement
* TU

## Migration

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist

*Sélectionner les éléments de la checklist*

* [ ] Mon code suit le style de code de ce projet.
* [ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.
* [ ] J'ai fait les changements correspondant dans la documentation RAML.
* [ ] J'ai fait les changements correspondant dans la documentation Métier.
* [ ] J'ai fait les changements correspondant dans la documentation Technique.
* [ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.
* [ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.
* [ ] Les tests unitaires nouveaux et existants passent avec succès localement.
* [ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

* VAS (Vitam Accessible en Service)
* CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2024-11-05 14:28 UTC, laedanrex commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/services/edit-object.service.ts
> +    }
il doit etre possible de simplifier je pense pour éviter les if imbriqués.       

if (editObject.cardinality !== 'ZERO' && editObject.virtual && editObject.children.every((ele) => ele.cardinality === 'ZERO')) {
  editObject.cardinality = 'ZERO';
} else if (editObject.cardinality !== 'ZERO' ) {
   return
}

(je n'ai pas essayé)

2024-11-05 14:28 UTC, laedanrex approved these changes

2024-11-06 15:02 UTC, marob requested changes
Il manque un test

2025-03-18 08:46 UTC, vitam-prg commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [e421c55a\-13d3\-4802\-a3bc\-15962a90ebda](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=e421c55a-13d3-4802-a3bc-15962a90ebda&branch=BUG_13482_FIX_DISPLAY_VIRTUAL_FIELDS)
<!--new issues section--><details><summary><b>New Issues (6)</b></summary>
Checkmarx found the following issues in this Pull Request

Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[Privacy_Violation](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/e421c55a-13d3-4802-a3bc-15962a90ebda/sast/description/359/12956636075206043460)|/api/api\-iam/iam\-client/src/main/java/fr/gouv/vitamui/iam/client/UserRestClient\.java: [100](https://github.com/ProgrammeVitam/vitam-ui/blob/BUG_13482_FIX_DISPLAY_VIRTUAL_FIELDS//api/api-iam/iam-client/src/main/java/fr/gouv/vitamui/iam/client/UserRestClient.java#L100)|<details><summary>details</summary>Method getMe at line 100 of /api/api\-iam/iam\-client/src/main/java/fr/gouv/vitamui/iam/client/UserRestClient\.java sends user information outside the\.\.\.</details>[Attack Vector](https://eu.ast.checkmarx.net/results/e421c55a-13d3-4802-a3bc-15962a90ebda/3f06ff53-d733-40ac-a6fb-49e415cb793f/sast?result-id=bF20IBOl55v65aK3Mvu%2F4nO0V4I%3D&redirect=true)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[Privacy_Violation](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/e421c55a-13d3-4802-a3bc-15962a90ebda/sast/description/359/12956636075206043460)|/api/api\-iam/iam\-client/src/main/java/fr/gouv/vitamui/iam/client/UserRestClient\.java: [100](https://github.com/ProgrammeVitam/vitam-ui/blob/BUG_13482_FIX_DISPLAY_VIRTUAL_FIELDS//api/api-iam/iam-client/src/main/java/fr/gouv/vitamui/iam/client/UserRestClient.java#L100)|<details><summary>details</summary>Method getMe at line 100 of /api/api\-iam/iam\-client/src/main/java/fr/gouv/vitamui/iam/client/UserRestClient\.java sends user information outside the\.\.\.</details>[Attack Vector](https://eu.ast.checkmarx.net/results/e421c55a-13d3-4802-a3bc-15962a90ebda/3f06ff53-d733-40ac-a6fb-49e415cb793f/sast?result-id=xryUFaQaBiBCronv6rLUaElLI7g%3D&redirect=true)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[Privacy_Violation](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/e421c55a-13d3-4802-a3bc-15962a90ebda/sast/description/359/12956636075206043460)|/api/api\-iam/iam\-client/src/main/java/fr/gouv/vitamui/iam/client/UserRestClient\.java: [100](https://github.com/ProgrammeVitam/vitam-ui/blob/BUG_13482_FIX_DISPLAY_VIRTUAL_FIELDS//api/api-iam/iam-client/src/main/java/fr/gouv/vitamui/iam/client/UserRestClient.java#L100)|<details><summary>details</summary>Method getMe at line 100 of /api/api\-iam/iam\-client/src/main/java/fr/gouv/vitamui/iam/client/UserRestClient\.java sends user information outside the\.\.\.</details>[Attack Vector](https://eu.ast.checkmarx.net/results/e421c55a-13d3-4802-a3bc-15962a90ebda/3f06ff53-d733-40ac-a6fb-49e415cb793f/sast?result-id=LxuLqZSln2fVpM8v0ocj%2F%2F5YeZU%3D&redirect=true)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[Privacy_Violation](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/e421c55a-13d3-4802-a3bc-15962a90ebda/sast/description/359/12956636075206043460)|/api/api\-iam/iam\-client/src/main/java/fr/gouv/vitamui/iam/client/UserRestClient\.java: [100](https://github.com/ProgrammeVitam/vitam-ui/blob/BUG_13482_FIX_DISPLAY_VIRTUAL_FIELDS//api/api-iam/iam-client/src/main/java/fr/gouv/vitamui/iam/client/UserRestClient.java#L100)|<details><summary>details</summary>Method getMe at line 100 of /api/api\-iam/iam\-client/src/main/java/fr/gouv/vitamui/iam/client/UserRestClient\.java sends user information outside the\.\.\.</details>[Attack Vector](https://eu.ast.checkmarx.net/results/e421c55a-13d3-4802-a3bc-15962a90ebda/3f06ff53-d733-40ac-a6fb-49e415cb793f/sast?result-id=z%2FOfXyTA%2Fjll96sM%2FIuOU89GQiY%3D&redirect=true)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[Privacy_Violation](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/e421c55a-13d3-4802-a3bc-15962a90ebda/sast/description/359/12956636075206043460)|/api/api\-iam/iam\-client/src/main/java/fr/gouv/vitamui/iam/client/UserRestClient\.java: [100](https://github.com/ProgrammeVitam/vitam-ui/blob/BUG_13482_FIX_DISPLAY_VIRTUAL_FIELDS//api/api-iam/iam-client/src/main/java/fr/gouv/vitamui/iam/client/UserRestClient.java#L100)|<details><summary>details</summary>Method getMe at line 100 of /api/api\-iam/iam\-client/src/main/java/fr/gouv/vitamui/iam/client/UserRestClient\.java sends user information outside the\.\.\.</details>[Attack Vector](https://eu.ast.checkmarx.net/results/e421c55a-13d3-4802-a3bc-15962a90ebda/3f06ff53-d733-40ac-a6fb-49e415cb793f/sast?result-id=2EW2sl%2Fn5QqG34mkR4wyxQAI388%3D&redirect=true)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[Privacy_Violation](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/e421c55a-13d3-4802-a3bc-15962a90ebda/sast/description/359/12956636075206043460)|/api/api\-iam/iam\-client/src/main/java/fr/gouv/vitamui/iam/client/UserRestClient\.java: [100](https://github.com/ProgrammeVitam/vitam-ui/blob/BUG_13482_FIX_DISPLAY_VIRTUAL_FIELDS//api/api-iam/iam-client/src/main/java/fr/gouv/vitamui/iam/client/UserRestClient.java#L100)|<details><summary>details</summary>Method getMe at line 100 of /api/api\-iam/iam\-client/src/main/java/fr/gouv/vitamui/iam/client/UserRestClient\.java sends user information outside the\.\.\.</details>[Attack Vector](https://eu.ast.checkmarx.net/results/e421c55a-13d3-4802-a3bc-15962a90ebda/3f06ff53-d733-40ac-a6fb-49e415cb793f/sast?result-id=POGdVD6DLMMV5UyIlfOPEH3XMU0%3D&redirect=true)

</details>

<!--new issues section--><!--fix issues section--><details><summary><b>Fixed Issues (231)</b></summary>
Great job! The following issues were fixed in this Pull Request

Severity|Issue|Source File / Package
---|---|---
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|~~[Privacy_Violation](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/e421c55a-13d3-4802-a3bc-15962a90ebda/sast/description/359/12956636075206043460)~~|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/SecurityService\.java: [175](https://github.com/ProgrammeVitam/vitam-ui/blob/BUG_13482_FIX_DISPLAY_VIRTUAL_FIELDS//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/SecurityService.java#L175)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|~~[Privacy_Violation](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/e421c55a-13d3-4802-a3bc-15962a90ebda/sast/description/359/12956636075206043460)~~|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/SecurityService\.java: [85](https://github.com/ProgrammeVitam/vitam-ui/blob/BUG_13482_FIX_DISPLAY_VIRTUAL_FIELDS//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/SecurityService.java#L85)
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|~~[Log_Forging](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/e421c55a-13d3-4802-a3bc-15962a90ebda/sast/description/117/9884244256835554923)~~|/api/api\-iam/iam\-security/src/main/java/fr/gouv/vitamui/iam/security/service/SecurityService\.java: [175](https://github.com/ProgrammeVitam/vitam-ui/blob/BUG_13482_FIX_DISPLAY_VIRTUAL_FIELDS//api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/SecurityService.java#L175)
![LOW](https://cdn.ast.checkmarx.net/integrations/severity/Low.png)|~~[Log_Forging](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb- [...]

2025-04-08 08:26 UTC, Pierre-TROCHET commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/services/edit-object.service.ts
> +    }
Hello Mohamed, ce if est identique et plus facile à comprendre je pense:

```
if (editObject.cardinality !== 'ZERO' && !(editObject.virtual && editObject.children.every(child => child.cardinality === 'ZERO'))) {
  return;
}
```

2025-04-08 13:12 UTC, Pierre-TROCHET approved these changes

2025-04-08 14:36 UTC, marob approved these changes

2025-04-08 14:36 UTC, merged