Bug #13592: add validators on owner forms
ProgrammeVitam/vitam-ui pull request #2161
Opened 2024-10-21 07:04 UTC by bbenaissa

## Description

Ajout de validateurs sur le code, company name et name dans le formulaire de gestion des owners pour prévenir une gestion d'erreur technique en back.

## Contributeur

* VAS (Vitam Accessible en Service)

2024-10-25 12:37 UTC, hazco75 approved these changes

2024-11-04 11:01 UTC, laedanrex approved these changes

2024-11-04 11:08 UTC, merged

2024-11-04 11:11 UTC, marob requested changes

2024-11-04 11:11 UTC, marob commented on ui/ui-frontend/projects/identity/src/app/customer/owner-form/owner-form.component.html
>    <vitamui-common-input class="col-6 pl-0" maxlength="20" required formControlName="code" [placeholder]="'CUSTOMER.OWNER.CODE' | translate">
Supprimer `maxlength="20"` si inutile (déjà spécifié en TS). Si utile (ça ne devrait pas), utiliser la constante `OWNER_CODE_MAX_LENGTH`.
Idem pour les autres occurrences.