Bug #13753: collect add files to project
ProgrammeVitam/vitam-ui pull request #2233
Opened 2024-11-14 10:01 UTC by laedanrex

WIP

2024-11-26 09:57 UTC, vitam-prg commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [b5a45df1\-c993\-49ba\-8577\-225cb218f363](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=b5a45df1-c993-49ba-8577-225cb218f363&branch=13753-collect-add-files)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2024-38828](https://devhub.checkmarx.com/cve-details/CVE-2024-38828)|Maven\-org\.springframework:spring\-webmvc\-5\.3\.27|[Vulnerable Package](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/b5a45df1-c993-49ba-8577-225cb218f363/sca?internalPath=%2Fpackages%2FMaven-org.springframework%3Aspring-webmvc-5.3.27%2FpackageDetailsGql)
![MEDIUM](https://cdn.ast.checkmarx.net/integrations/severity/Medium.png)|[CVE-2024-38828](https://devhub.checkmarx.com/cve-details/CVE-2024-38828)|Maven\-org\.springframework:spring\-webmvc\-5\.3\.22|[Vulnerable Package](https://eu.ast.checkmarx.net/results/3f06ff53-d733-40ac-a6fb-49e415cb793f/b5a45df1-c993-49ba-8577-225cb218f363/sca?internalPath=%2Fpackages%2FMaven-org.springframework%3Aspring-webmvc-5.3.22%2FpackageDetailsGql)

2024-11-26 10:55 UTC, marob commented
Typo dans le commentaire de commit "Sotry" -> "Story"

2024-11-26 10:58 UTC, marob commented
Build KO

2024-11-26 13:44 UTC, marob requested changes

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/add-units/add-units.component.ts
> +import { CollectUploadService } from '../../shared/collect-upload/collect-upload.service';
Supprimer

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/add-units/add-units.component.ts
> +    private translateService: TranslateService,
Supprimer

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/add-units/add-units.component.ts
> +    private snackBar: MatSnackBar,
Supprimer

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/add-units/add-units.component.ts
> +import { TranslateService } from '@ngx-translate/core';
Supprimer

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/add-units/add-units.component.ts
> +import { MatLegacySnackBar as MatSnackBar } from '@angular/material/legacy-snack-bar';
Supprimer

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/add-units/zip-file.ts
Supprimer les console.log

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-collect.service.ts
> +    console.log('ArchiveCollectService attachmentId = ' + attachmentId);
Supprimer

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/core/api/project-api.service.ts
Supprimer les console.log

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/vitamui-http-headers.enum.ts
> +//TODO: replace every usage
Pourquoi ne pas effectuer le remplacement maintenant ?

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-to-upload.ts
> +}
```suggestion
export interface ZipFileToUpload extends Omit<FileToUpload, 'dragged'>{
  uploadedSize: number;
  currentFile?: string;
  currentFileUploadedSize?: number;
}
```

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-to-upload.ts
Inutilisé ? => supprimer

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.ts
> +  /** only a directory can be chose */
```suggestion
  /** only a directory can be chosen */
```

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.ts
Supprimer les console.log

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.ts
>    protected files: File[] = [];
```suggestion
  private files: File[] = [];
```

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.html
> +  [enableFolderDragAndDrop]="true"
Toujours true ?

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.html
> +  <div class="vitamui-chip-list defaultFileList">
Il n'y a pas de classe `defaultFileList`
```suggestion
  <div class="vitamui-chip-list">
```

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.html
> +  <h4 (click)="openFileSelectorOSDialog()" class="text-center text primary link defaultContent">
Il n'y a pas de classe `defaultContent`

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.html
> +  <div *ngIf="extensions" class="text-center text primary defaultContent">
Il n'y a pas de classe `defaultContent`

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.html
> +  <div *ngIf="maxSizeInBytes" class="text-center text primary defaultContent">
Il n'y a pas de classe `defaultContent`

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/lib/components/filing-plan/filing-plan.component.ts
>        this.initCheckedNodes(this.selectedNodes, nodes);
Extraire dans une fonction pour éviter la duplication

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/shared/collect-upload/collect-upload.service.ts
> +  //private static X_TENANT_KEY = 'X-Tenant-Id';
?

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/shared/collect-upload/collect-upload.service.ts
> +    //headers = headers.set(CollectUploadService.X_TENANT_KEY, tenantIdentifier.toString());
Supprimer ?

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/shared/collect-upload/collect-upload.service.ts
> +    headers = headers.set(CollectUploadService.X_ATTACHEMENT_ID, 'alexandr');
"alexandr" ?

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-list/project-list.component.ts
> +    //this.updatedData.subscribe({ next: () => this.searchArchiveUnitsByProject(this.dataSource[0]) });
Supprimer ?

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
> +              {{ 'Ajouter des unités archivistiques' | translate }}
i18n

2024-11-26 13:44 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/add-units/zip-file.ts
> +  zipFileStatusSubject$: BehaviorSubject<ZipFileStatus> = new BehaviorSubject<ZipFileStatus>(null);
On ne fait qu'émettre dans ce subject et il n'est jamais souscrit => inutile => à supprimer

2024-11-26 14:03 UTC, laedanrex commented on ui/ui-frontend/projects/collect/src/app/collect/shared/collect-upload/collect-upload.service.ts
> +    headers = headers.set(CollectUploadService.X_ATTACHEMENT_ID, 'alexandr');
oui ?

2024-11-26 14:04 UTC, laedanrex commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/vitamui-http-headers.enum.ts
> +//TODO: replace every usage
j'attends le back

2024-11-26 14:13 UTC, laedanrex commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.ts
>    protected files: File[] = [];
c'est utilisé dans le template, ca marchera pas si je met private

2024-11-26 14:40 UTC, laedanrex commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.html
> +  <h4 (click)="openFileSelectorOSDialog()" class="text-center text primary link defaultContent">
oue j'avais un problème d'affichage, ca m'a aidé à debug

2024-11-26 14:42 UTC, laedanrex commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.html
> +  <div *ngIf="maxSizeInBytes" class="text-center text primary defaultContent">
le disque est rayé

2024-11-26 14:57 UTC, laedanrex commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/add-units/zip-file.ts
> +  zipFileStatusSubject$: BehaviorSubject<ZipFileStatus> = new BehaviorSubject<ZipFileStatus>(null);
alors,      
c'est une reprise de collectUpload - je l'ai divisé en service dédié.         
dans create-project, le subject est utilisé dans le component pour visualiser le progress, j'ai pas eu le temps d'en parler avec les PO.

2024-11-26 15:12 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.ts
>    protected files: File[] = [];
C'est displayFiles qui est utilisé maintenant. Il me semble que files n'est utilisé que dans le .ts

2024-11-27 09:01 UTC, laedanrex commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.ts
>    protected files: File[] = [];
a oui, bien vu

2024-12-13 10:15 UTC, laedanrex commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/add-units/zip-file.ts
> +  zipFileStatusSubject$: BehaviorSubject<ZipFileStatus> = new BehaviorSubject<ZipFileStatus>(null);
supprimé

2024-12-13 10:20 UTC, laedanrex commented on ui/ui-frontend/projects/vitamui-library/src/lib/components/filing-plan/filing-plan.component.ts
>        this.initCheckedNodes(this.selectedNodes, nodes);
j'ai mis un methode setNodes

2024-12-13 10:21 UTC, laedanrex commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.html
> +  [enableFolderDragAndDrop]="true"
il y a une variable directoryMode

2024-12-13 14:26 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/vitamui-http-headers.enum.ts
> +//TODO: replace every usage
Il reste des endroits où les headers sont utilisés "en dur" plutôt que de référencer cet enum

2024-12-13 14:30 UTC, bbenaissa approved these changes

2024-12-13 14:36 UTC, marob commented
Problème sur le n° d'étape
![image](https://github.com/user-attachments/assets/64514fdf-c899-47b8-88ef-af9df2319be6)

2024-12-13 14:53 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/add-units/add-units.component.ts
> +  public stepCount = 1;
```suggestion
  public stepCount = 2;
```

2024-12-13 14:53 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/add-units/add-units.component.ts
> +  @ViewChild('updateMetadataCSVFile', { static: false }) updateMetadataCSVFile: any;
Inutilisé

2024-12-13 14:53 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/add-units/add-units.component.html
> +        <!-- <i class="material-icons">keyboard_arrow_left</i> -->
Supprimer

2024-12-13 14:53 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
> +            <button mat-menu-item [disabled]="" (click)="openAddUnitsForm()">
`[disabled]=""` ? C'est jamais disabled ?

2024-12-13 14:53 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.module.ts
> +    CdkStepperModule,
Utile ?

2024-12-13 14:53 UTC, marob commented on ui/ui-frontend/projects/collect/src/app/collect/core/api/project-api.service.ts
> +    // return this.http.post<HttpEvent<any>>(`${this.apiUrl}/upload`, content, options);
Supprimer

2024-12-16 08:17 UTC, laedanrex commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
> +            <button mat-menu-item [disabled]="" (click)="openAddUnitsForm()">
yes, je l'ai retiré

2024-12-16 08:34 UTC, laedanrex commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.module.ts
> +    CdkStepperModule,
ajout auto, j'ai test le VitamUILibraryModule est utile au bon fonctionnement,      
j'ai retiré l'autre.

2024-12-16 09:34 UTC, Regzox commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
> +      dialogRef.afterClosed().subscribe((result) => {
subscribe() ?

2024-12-16 09:42 UTC, Regzox approved these changes

2024-12-16 09:48 UTC, marob approved these changes

2024-12-16 09:51 UTC, laedanrex commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/vitamui-http-headers.enum.ts
> +//TODO: replace every usage
j'ai commencé la reprise dans une pr clean code

2024-12-16 09:57 UTC, merged