Story #13836 feat(agencies): add advanced edition view for agency
ProgrammeVitam/vitam-ui pull request #2256
Opened 2024-11-22 16:55 UTC by Regzox

## Description

Ajoute la vue de modification avancée pour les services agent.

2024-11-25 17:24 UTC, vitam-prg commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [d1892238\-e266\-4476\-82c6\-42ba45866540](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=d1892238-e266-4476-82c6-42ba45866540&branch=story_13836)
### No New Or Fixed Issues Found

2024-11-28 10:41 UTC, marob requested changes
Problème de style :
- les "hints" sont en rouge (d'autres sont en gris)
- un "hint" caché sous un autre élément
![image](https://github.com/user-attachments/assets/44a25c84-96fd-4490-a51d-012f0918b70c)

2024-11-28 10:41 UTC, marob commented on ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
> +      "TITLE": "Référentiel des services agents",
Changer également en anglais ?

2024-11-28 10:41 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/agency/agency-preview/agency-preview.component.html
> +      [matTooltipShowDelay]="300"
Utiliser `vitamuiCommonToolTip`.
Toutes les tooltip utilisent `vitamuiCommonToolTip` dans la MR https://github.com/ProgrammeVitam/vitam-ui/pull/2236

2024-11-28 10:41 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/agency/agency.guard.ts
> +    console.error('No tenant selected');
Message incorrect si c'est agencyIdentifier qui est null

2024-11-28 10:41 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/agency/edit-agency/edit-agency.component.ts
> +    of(history?.state?.agency)
Je pense qu'il est préférable d'utiliser l'API Angular plutôt que l'API du navigateur : `this.router.getCurrentNavigation().extras.state.agency`

2024-11-28 10:41 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/agency/edit-agency/edit-agency.component.ts
> +      margin-top: 30px;
Utiliser .mt-5

2024-11-28 10:41 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/agency/edit-agency/edit-agency.component.ts
> +      padding-left: 112%;
Un peu magique. Est-ce qu'il est possible de faire mieux ? Ou au moins de mettre un commentaire et/ou de calculer les valeurs les unes par rapport aux autres ?
Aussi, à voir s'il y a un besoin de sticky (position: fixed)

2024-11-28 10:41 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/agency/edit-agency/edit-agency.component.html
> +    <vitamui-common-editor-banner title="" class="editor-banner">
title vide ?

2024-11-28 10:41 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/agency/edit-agency/edit-agency.component.html
> +    <vitamui-common-editor-banner title="" class="editor-banner">
On peut se passer de la classe `editor-banner` en ciblant le style sur `vitamui-common-editor-banner`

2024-11-28 10:41 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/components/archive-unit-editor/components/editor-banner/editor-banner.component.scss
> +  gap: 10px;
20px sur le figma => utiliser .hgap-4

2024-11-28 10:41 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/agency/view-agency/view-agency.component.ts
> +    of(history?.state?.agency)
Je pense qu'il est préférable d'utiliser l'API Angular plutôt que l'API du navigateur : `this.router.getCurrentNavigation().extras.state.agency`

2024-11-28 10:41 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/agency/agency.template.ts
> +      open: true,
Devrait être fermé par défaut (mais passer à false ne semble pas le fermer...)

2024-11-28 10:41 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/agency/edit-agency/edit-agency.component.ts
> +  breadcrumbData: BreadCrumbData[] = [{ identifier: ApplicationId.PORTAL_APP }, { identifier: ApplicationId.AGENCIES_APP }];
Le second élément du breadcrumb est, d'après l'US et le Figma "Créer et gérer des services agents" et non le nom de l'application. Est-ce normal ? Je ne sais pas, mais en tout cas ce n'est pas conforme.

2024-11-28 10:41 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/agency/view-agency/view-agency.component.ts
> +  breadcrumbData: BreadCrumbData[] = [{ identifier: ApplicationId.PORTAL_APP }, { identifier: ApplicationId.AGENCIES_APP }];
Le second élément du breadcrumb est, d'après l'US et le Figma "Créer et gérer des services agents" et non le nom de l'application. Est-ce normal ? Je ne sais pas, mais en tout cas ce n'est pas conforme.

2024-11-28 10:41 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/agency/agency.template.ts
> +  },
D'après le document excel en PJ de l'US, il manque un champ "description". Par ailleurs, il n'y a aucune cohérence entre ce document excel et les maquettes Figma (définitive ou en travaux)...

2024-11-28 10:41 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/object-viewer/services/display-rule-helper.service.ts
> +  public mergeDisplayRules(sourceRule: DisplayRule, targetRule: DisplayRule): DisplayRule {
Inutile ?

2024-11-28 10:42 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/agency/agency.schema.ts
> +      Comment: 'Limité à 50 caractères',
On ne peut pas gérer d'i18n ?

2024-12-02 09:50 UTC, laedanrex approved these changes

2024-12-02 12:11 UTC, Regzox commented on ui/ui-frontend/projects/referential/src/app/agency/agency.schema.ts
> +      Comment: 'Limité à 50 caractères',
Géré mais ça reste très moche.

2024-12-02 12:24 UTC, Regzox commented on ui/ui-frontend/projects/referential/src/app/agency/agency.template.ts
> +  },
Va être géré correctement dans https://github.com/ProgrammeVitam/vitam-ui/pull/2257

2024-12-02 18:37 UTC, Regzox commented on ui/ui-frontend/projects/referential/src/app/agency/edit-agency/edit-agency.component.ts
> +  breadcrumbData: BreadCrumbData[] = [{ identifier: ApplicationId.PORTAL_APP }, { identifier: ApplicationId.AGENCIES_APP }];
Validé en l'état avec un PO.

2024-12-02 18:37 UTC, Regzox commented on ui/ui-frontend/projects/referential/src/app/agency/view-agency/view-agency.component.ts
> +  breadcrumbData: BreadCrumbData[] = [{ identifier: ApplicationId.PORTAL_APP }, { identifier: ApplicationId.AGENCIES_APP }];
Validé en l'état avec un PO

2024-12-03 13:39 UTC, Regzox commented on ui/ui-frontend/projects/referential/src/app/agency/edit-agency/edit-agency.component.ts
> +      padding-left: 112%;
J'ai tenté, mais pas moyen... c'est systématiquement hors de la vue, je n'arrive pas régler la vue avec notre layout actuel.

2024-12-03 16:27 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/agency/edit-agency/edit-agency.component.ts
> +      padding-left: 112%;
As-tu eu la réponse concernant le sticky ?
Et aura-t-on systématiquement un alignement à gauche du bouton avec les éléments de la page ?
Ça me semble être un caprice de designer...

2024-12-03 16:27 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/components/archive-unit-editor/components/editor-banner/editor-banner.component.html
> +<div class="actions hgap-4" [ngClass]="{ only: !title }">
Je préfère `[class.only]="!title"`, mais les 2 sont OK.

2024-12-03 16:27 UTC, marob commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/vitamui-input/vitamui-textarea.component.scss
> +  height: $input-height;
Pourquoi ? On ne peut pas mettre `display: flex` ?

2024-12-03 16:40 UTC, Regzox commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/components/vitamui-input/vitamui-textarea.component.scss
> +  height: $input-height;
L'espace pour les messages repasse en dessous des autres éléments.

2024-12-04 12:36 UTC, marob approved these changes

2024-12-04 13:41 UTC, merged