13888 service agent
ProgrammeVitam/vitam-ui pull request #2257
Opened 2024-11-26 11:05 UTC by laedanrex

## Description

*Description des modifications*

## Type de changement

*Indiquer le ou les types de changements*

* Build
* PKI
* Ansiblerie
* Nouveau Code
* Correction
* Refactorisation de code
* Autre

## Documentation

*Indiquer la documentation mise à jour*

* [ ] Quels sont les nouvelles documentations ?
* [ ] Quels sont les modifications existantes ?
* [ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

* manuel
* environnement
* TU

## Migration

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist

*Sélectionner les éléments de la checklist*

* [ ] Mon code suit le style de code de ce projet.
* [ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.
* [ ] J'ai fait les changements correspondant dans la documentation RAML.
* [ ] J'ai fait les changements correspondant dans la documentation Métier.
* [ ] J'ai fait les changements correspondant dans la documentation Technique.
* [ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.
* [ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.
* [ ] Les tests unitaires nouveaux et existants passent avec succès localement.
* [ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

* VAS (Vitam Accessible en Service)
* CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2024-12-04 19:44 UTC, bbenaissa requested changes

2024-12-04 19:44 UTC, bbenaissa commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dto/AgencyCSVDto.java
> +    @JsonProperty("CreationDate")
CreationDate et UpdateDate sont des champs calculés par Vitam

2024-12-04 19:44 UTC, bbenaissa commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamAgencyService.java
> +        agencyToPatch.setCreationDate(fieldsToApply.getCreationDate());
Aussi les champs creationDate et UpdateDate

2024-12-04 19:44 UTC, bbenaissa commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamAgencyService.java
> +            final List<String> accessContractsIds = agenciesModels.stream().map(AgenciesModel::getIdentifier).toList();
A renommer la la variable, j'ai mis un peu de temps pour comprendre qu'il s'agit d'un souci de nommage

2024-12-04 19:44 UTC, bbenaissa commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamAgencyService.java
>              alreadyCreated = accessContractResponseDto
Idem

2024-12-06 11:33 UTC, ebernard commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamAgencyService.java
> +    private void patchFields(AgenciesModel agencyToPatch, AgenciesModel fieldsToApply) {
Utiliser `VitamUIUtils.copyProperties` ?

2024-12-06 11:33 UTC, ebernard commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamAgencyService.java
> +        String fileName = "Agencies.json";
Utiliser une constante et inline la variable dans la ligne 229 ?

2024-12-06 11:33 UTC, ebernard commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/utils/AgencyConverter.java
> +        return VitamUIUtils.copyProperties(Agency, new AgencyDto());
```suggestion
    public AgencyDto convertVitamToDto(final AgenciesModel agency) {
        return VitamUIUtils.copyProperties(agency, new AgencyDto());
```

2024-12-06 11:33 UTC, ebernard commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/utils/AgencyConverter.java
> +@UtilityClass
Ras le bol des méthodes statiques dans Vitam, je préfèrerais largement un `@Service` si possible (surtout qu'on utilise Spring sur Vitam UI)

2024-12-06 11:33 UTC, ebernard commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/config/ConverterConfig.java
> -
Laisser en service à mon avis.

2024-12-06 11:33 UTC, ebernard commented on ui/ui-frontend/projects/vitamui-library/src/app/modules/object-viewer/models/display-object.enum.ts
> +  DATE_DRIVEN = 'data-driven',
```suggestion
  DATA_DRIVEN = 'data-driven',
```

2024-12-06 14:17 UTC, laedanrex commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/utils/AgencyConverter.java
> +@UtilityClass
c'est un converteur, ca me parait mieu en static

2024-12-06 14:17 UTC, laedanrex commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/config/ConverterConfig.java
> -
c'est quoi l'avantage ?

2024-12-06 14:29 UTC, laedanrex commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamAgencyService.java
> +        String fileName = "Agencies.json";
quoi ?

2024-12-06 14:29 UTC, laedanrex commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamAgencyService.java
> +            final List<String> accessContractsIds = agenciesModels.stream().map(AgenciesModel::getIdentifier).toList();
ah ouai, ce sont des relicats, j'ai essayé d'en corrigé pas mal

2024-12-06 14:42 UTC, laedanrex commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamAgencyService.java
> +    private void patchFields(AgenciesModel agencyToPatch, AgenciesModel fieldsToApply) {
yes, je vais test

2024-12-06 16:37 UTC, ebernard commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamAgencyService.java
> +        String fileName = "Agencies.json";
La variable `fileName` a une valeur constante, autant utiliser une constante.

2024-12-06 16:37 UTC, ebernard commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/utils/AgencyConverter.java
> +@UtilityClass
L'avantage de ne pas le faire en static ici c'est de pouvoir le déclarer comme service Spring pour l'injection.

Dans l'absolu, j'aurais même préféré qu'on utilise MapStruct, mais chaque chose en son temps.

2024-12-06 16:37 UTC, ebernard commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/config/ConverterConfig.java
> -
Injection de dépendances. Dur de mocker une méthode statique.

2024-12-06 18:04 UTC, laedanrex commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamAgencyService.java
> +        String fileName = "Agencies.json";
a oui, refacto pas complete, c'est modifié

2024-12-06 18:13 UTC, laedanrex commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/config/ConverterConfig.java
> -
tu sites une des raisons pour lesquelles je l'ai mis en static

2024-12-09 13:49 UTC, bbenaissa approved these changes

2024-12-09 14:21 UTC, ebernard commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/config/ConverterConfig.java
> -
ça se discute... pour moi ce changement est une régression, mais bon, je ne vais pas faire mon ayatollah non plus.

2024-12-09 14:21 UTC, ebernard approved these changes

2024-12-09 14:31 UTC, merged