Story #13791: improve IntelliJ config
ProgrammeVitam/vitam-ui pull request #2258
Opened 2024-11-26 15:34 UTC by marob

## Description

* Externalisation de la configuration IntelliJ (laisse le choix au développeur de customiser sa configuration)
* Réécriture des configurations pour utiliser les configurations de type Spring, Angular, ...

## Type de changement

* Autre

## Checklist

*Sélectionner les éléments de la checklist*

* [ ] Mon code suit le style de code de ce projet.
* [ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.
* [ ] J'ai fait les changements correspondant dans la documentation RAML.
* [ ] J'ai fait les changements correspondant dans la documentation Métier.
* [ ] J'ai fait les changements correspondant dans la documentation Technique.
* [ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.
* [ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.
* [ ] Les tests unitaires nouveaux et existants passent avec succès localement.
* [ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

* VAS (Vitam Accessible en Service)

2024-11-26 15:51 UTC, ebernard commented on intellij-conf/.run/Spring/pastis standalone.run.xml
À virer ?

2024-11-26 15:52 UTC, ebernard approved these changes

2024-11-26 15:57 UTC, GiooDev requested changes

2024-11-26 15:57 UTC, GiooDev commented on intellij-conf/.run/Spring/API gateway.run.xml
> +<component name="ProjectRunConfigurationManager">
Le nommage des fichiers ne respecte aucune convention.
Certains ont des majuscules, d'autres pas.

Si il n'y a pas de besoin fonctionnel pour ce nommage, essayer de cleaner un peu tout ça avec une convention unifiée :)

2024-11-26 15:57 UTC, GiooDev commented on intellij-conf/.run/Multirun/Multirun_ archive-search.run.xml
> +<component name="ProjectRunConfigurationManager">
Dans le nom de ces fichiers sont préfixés par `Multirun_ `

Est-ce que l'espace sur ce prefixe est voulu ou pas ?

2024-11-26 15:57 UTC, GiooDev commented on intellij-conf/.run/Angular/Angular_ archive-search.run.xml
> +<component name="ProjectRunConfigurationManager">
Dans le nom de ces fichiers sont préfixés par `Angular_ `

Est-ce que l'espace sur ce prefixe est voulu ou pas ?

2024-11-26 16:16 UTC, marob commented on intellij-conf/.run/Spring/API gateway.run.xml
> +<component name="ProjectRunConfigurationManager">
C'est l'IDE qui nomme en fonction du nom visible dans l'interface. C'est moche, mais il vaut mieux se baser sur ce que l'IDE à généré plutôt que de vouloir rendre les noms de fichiers jolis ou bien rendre moins intelligible les noms affichés au développeur.

2024-11-26 16:16 UTC, marob commented on intellij-conf/.run/Angular/Angular_ archive-search.run.xml
> +<component name="ProjectRunConfigurationManager">
Oui, généré par l'IDE

2024-11-26 16:16 UTC, marob commented on intellij-conf/.run/Multirun/Multirun_ archive-search.run.xml
> +<component name="ProjectRunConfigurationManager">
Oui, généré par l'IDE

2024-11-26 16:24 UTC, GiooDev commented on intellij-conf/.run/Spring/API gateway.run.xml
> +<component name="ProjectRunConfigurationManager">
Ok compris :)

2024-11-26 16:42 UTC, bbenaissa approved these changes

2024-11-27 08:13 UTC, ebernard commented
@GiooDev tu attends encore des changements ?

2024-11-27 08:32 UTC, GiooDev approved these changes

2024-11-27 09:15 UTC, merged