Story #13901 feat(agencies): add create and update button in creation form
ProgrammeVitam/vitam-ui pull request #2259
Opened 2024-11-26 17:19 UTC by Regzox

## Description

* Ajout du bouton de création et redirection vers l'édition.

2024-11-28 10:58 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.ts
> -        this.isLoading = false;
Pourquoi ne pas arrêter le loader en cas d'erreur ?

2024-11-29 09:19 UTC, Regzox commented on ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.ts
> -        this.isLoading = false;
Un oubli, je voulais passer par du tap, finalize... Mais comme le composant est instancié à chaque ajout le problème de gestion d'état que j'ai voulu corriger ne se voit pas.

2024-11-30 10:07 UTC, vitam-prg commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [3fa5d38b\-5a0d\-4dae\-8a49\-6067735137ea](https://eu.ast.checkmarx.net/projects/3f06ff53-d733-40ac-a6fb-49e415cb793f/scans?id=3fa5d38b-5a0d-4dae-8a49-6067735137ea&branch=story_13901)
### No New Or Fixed Issues Found

2024-12-02 09:49 UTC, marob approved these changes

2024-12-02 09:51 UTC, marob requested changes

2024-12-02 09:51 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/agency/agency-preview/agency-preview.component.html
> +      [matTooltipShowDelay]="300"
Utiliser vitamuiCommonToolTip

2024-12-02 11:09 UTC, laedanrex approved these changes

2024-12-02 14:26 UTC, marob approved these changes

2024-12-04 13:51 UTC, merged