story #13833: import_paths_from_CSV_file_admin_tenant
ProgrammeVitam/vitam-ui pull request #2288
Opened 2024-12-06 08:22 UTC by gtaltou

## Description

*Description des modifications*

## Type de changement

*Indiquer le ou les types de changements*

* Build
* PKI
* Ansiblerie
* Nouveau Code
* Correction
* Refactorisation de code
* Autre

## Documentation

*Indiquer la documentation mise à jour*

* [ ] Quels sont les nouvelles documentations ?
* [ ] Quels sont les modifications existantes ?
* [ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

* manuel
* environnement
* TU

## Migration

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist

*Sélectionner les éléments de la checklist*

* [ ] Mon code suit le style de code de ce projet.
* [ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.
* [ ] J'ai fait les changements correspondant dans la documentation RAML.
* [ ] J'ai fait les changements correspondant dans la documentation Métier.
* [ ] J'ai fait les changements correspondant dans la documentation Technique.
* [ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.
* [ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.
* [ ] Les tests unitaires nouveaux et existants passent avec succès localement.
* [ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

* VAS (Vitam Accessible en Service)
* CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2024-12-06 09:06 UTC, GiooDev submitted a review, later dismissed

2024-12-06 09:06 UTC, GiooDev commented on deployment/scripts/mongod/v8.1/001_add_import_schema_role.js.j2
> +
Beaucoup


trop


de
sauts

de

lignes

:D

2024-12-06 09:06 UTC, GiooDev commented on ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
> +    "ONTOLOGY_FORMAT_JSON": "Le fichier d’import doit être au format json",
Les `’` ne semblent pas être les mêmes que ci-dessus: `'`

Voir pour unifier tout ça non ?

2024-12-06 09:06 UTC, GiooDev commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
> +
pourquoi ?

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dto/ImportSchemaDto.java
> +public class ImportSchemaDto extends IdDto implements Serializable {
Pas besoin d'étendre IdDto car on n'a pas de champ Id

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/ImportSchemaService.java
> +    List<SchemaInputModel> convertImputSchemaToModelOfCreation(final List<SchemaInputModel> schemaModels) {
Je ne comprends pas quel est le but de la méthode. Ça prend une liste de SchemaInputModel et ça retourne une liste de SchemaInputModel en copiant les champs ? Est-ce vraiment nécessaire ?

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/dto/ImportSchemaDtoTest.java
Ok pour le test, mais je ne suis pas convaincu qu'il soit vraiment pertinent.

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/ImportSchemaServiceTest.java
> +        MockitoAnnotations.openMocks(this);
C'est bon, mais je préfèrerais utiliser `@ExtendWith(MockitoExtension.class)` sur la classe.

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/ImportSchemaServiceTest.java
> +        VitamContext vitamContext = mock(VitamContext.class);
Tu as déjà `vitamContext` comme membre. Si tu as besoin d'avoir un mock propre peut être plutôt faire un reset dans le setUp ?

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/ImportSchemaServiceTest.java
> +    }
Ajouter la vérification du JSON généré ?

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/ImportSchemaServiceTest.java
> +        assertNotNull(byteArrayInputStream);
Peut être regroupé avec le précédent

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/ImportSchemaServiceTest.java
> +        List<SchemaInputModel> result = importSchemaService.convertImputSchemaToModelOfCreation(schemaModels);
Je ne suis toujours pas convaincu par l'utilité de la méthode. Et au passage, ça devrait être `convertInputSchemaToModelOfCreation` et non `convertImputSchemaToModelOfCreation`

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/SchemaExternalControllerTest.java
> +        schemaExternalService = mock(SchemaExternalService.class);
Ok mais tu aurais pu utiliser les annotations sur les membres :

```
@InjectMocks
private SchemaExternalController schemaExternalController;

@Mock
private SchemaExternalService schemaExternalService;

@Mock
private ExternalSecurityService externalSecurityService;
```

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/SchemaExternalControllerTest.java
> +        Mockito.when(schemaExternalService.importSchemas(any(), any(), any())).thenReturn(expectedResponse);
Utiliser un import static (`when`) au lieu de `Mockito.when` car ça alourdit la syntaxe.

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/SchemaExternalControllerTest.java
> +        MockMultipartFile validFile = new MockMultipartFile("file", "import_schema.csv", "text/csv", fileContent);
À vérifier, mais plutôt quelque chose comme ça :
```suggestion
        MultipartFile validFile = new MockMultipartFile("file", "import_schema.csv", "text/csv", getClass().getResourceAsStream("/data/import_schema.csv"));
```

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/SchemaExternalControllerTest.java
> +        assertEquals(expectedResponse, Jresponse);
Ça sera toujours vrai puisque tu as demandé à mockito que ça te retourne Jresponse.

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/SchemaExternalControllerTest.java
> +}
Il faudrait aussi tester avec un CSV non valide, non ?

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/service/SchemaExternalServiceTest.java
> +        MockitoAnnotations.openMocks(this);
Même remarque qu'avant.

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/SchemaExternalControllerTest.java
> +}
Ah, je viens de voir que le CSV de test n'est pas valide. Pourquoi ça ne remonte pas dans le test ?

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/schema/ImportSchemaConverter.java
> +        }
C'est pas déjà fait par le copyProperties juste au-dessus ?

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/schema/ImportSchemaConverter.java
> +        importSchema.setDescription(dto.getDescription());
Idem

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/schema/ImportSchemaConverter.java
> +        }
Même remarque

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/schema/ImportSchemaConverter.java
> +        dto.setDescription(schemaInputModel.getDescription());
Idem

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/schema/ImportSchemaConverter.java
> +    }
C'est utilisé ça ?

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/utils/ImportCSVUtils.java
> +    public static class ColumnDetails {
Pourquoi c'est nécessaire ici alors que ça n'avait pas posé de problème jusqu'à maintenant ?

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/schema/ImportSchemaCSVUtilsTest.java
> +        // Call buildImportSchemaColumns with 'false' to make the identifier not mandatory
Path est toujours obligatoire. Cette logique a été copié/collée depuis Ingest Contract, qui lui a bien un Id.

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/schema/ImportSchemaCSVUtilsTest.java
> +        );
Tu viens de tester le contraire dans la méthode au-dessus, je ne vois pas comment le test peut passer.

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/schema/ImportSchemaConverter.java
> +        importSchema.setObject(dto.isObject());
Pourquoi ça n'est pas setIsObject / getIsObject ? Ça va poser des problèmes sur le copyProperties.

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/schema/ImportSchemaConverterTest.java
> +        dto.setObject(true);
Tester quand il n'y a pas eu d'appel à setObject, pour vérifier que la valeur par défaut est bien false.

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/schema/ImportSchemaConverterTest.java
> +        assertEquals(SchemaCardinality.MANY, result.get(1).getCardinality());
Vérifier la valeur de IsObject

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/SchemaInternalServiceTest.java
> +        schemaInternalService = new SchemaInternalService(
Tu fais un `@InjectMocks` juste au-dessus, est-ce nécessaire ?

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/SchemaInternalServiceTest.java
> +        objectMapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
Tu peux le déclarer en static sur la classe.

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/SchemaInternalServiceTest.java
> +        objectMapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
Mais il sert à quoi en fait ?

2024-12-06 10:18 UTC, ebernard commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/SchemaInternalServiceTest.java
> +
Supprimer

2024-12-06 10:18 UTC, ebernard commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
> +
Inutile.

2024-12-06 10:18 UTC, ebernard commented on deployment/scripts/mongod/v8.1/001_add_import_schema_role.js.j2
> +db = db.getSiblingDB('iam')
Trop de sauts de ligne, comme le 

dit

Julien

2024-12-06 10:18 UTC, ebernard commented on ui/ui-frontend/projects/referential/src/app/core/api/referential-schema-api.service.spec.ts
C'est déjà testé dans `ui/ui-frontend/projects/referential/src/app/core/api/referential-import-api.service.spec.ts` et en plus tu n'utilises plus le service, normalement. À supprimer

2024-12-06 10:18 UTC, ebernard commented on ui/ui-frontend/projects/referential/src/app/core/api/referential-schema-api.service.ts
Ça n'est plus utilisé car tu utilises ReferentialImportApiService normalement, maintenant. À supprimer

2024-12-06 10:18 UTC, ebernard commented on ui/ui-frontend/projects/referential/src/app/ontology/ontology.component.ts
> +  }
Où est-ce utilisé ?

2024-12-06 10:18 UTC, ebernard commented on ui/ui-frontend/projects/referential/src/app/ontology/ontology.component.html
> -          <span>{{ 'ONTOLOGY.HOME.IMPORT' | translate }}</span>
Est-ce que la clé de traduction est encore utilisée, du coup ?

2024-12-06 10:20 UTC, ebernard commented
J'ajouterais juste que ça ne passe pas le linter (lancer `mvn spotless:apply`), tu as au moins un conflit, et les tests ne sont pas encore passés.

2024-12-06 10:41 UTC, ebernard commented
Plus déployer sur un bac à sable (on peut voir ça ensemble).

2024-12-06 11:05 UTC, bbenaissa requested changes

2024-12-06 11:05 UTC, bbenaissa commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/ImportSchemaService.java
> +    public RequestResponse<?> createImportSchema(
A renommber la méthode

2024-12-06 11:05 UTC, bbenaissa commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/ImportSchemaService.java
> +            LOGGER.info("Create Ingest Contract EvIdAppSession : {} ", vitamContext.getApplicationSessionId());
A corriger les logs (ce n'est pas du ingest contract), ça ne sert à rien à logger aussi le  EvIdAppSession

2024-12-06 11:05 UTC, bbenaissa commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/ImportSchemaService.java
> +    public RequestResponse<?> createImportSchema(
par exemple ImportUnitSchema

2024-12-06 11:05 UTC, bbenaissa commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/ImportSchemaService.java
> +        final ObjectMapper mapper = new ObjectMapper();
Tu peux mettre le mapper comme un param du service pour éviter de la créer à chaque appel

2024-12-06 11:05 UTC, bbenaissa commented on api/api-gateway/src/main/resources/application-dev.yml
> +              /referential-api/schemas/**,
cette partie concerne les schema unit, est ce que tu peux le renomer par soit : unit-schema ou schema/unit

2024-12-06 11:05 UTC, bbenaissa commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/config/ApiReferentialServerConfig.java
> +    @Bean
Je pense que tu as pas besoin de ce bean schemaInternalWebClient, à vérifier

2024-12-06 11:05 UTC, bbenaissa commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/config/ApiReferentialServerConfig.java
> +    @Bean
C'est une action en mode synchrone?

2024-12-06 11:05 UTC, bbenaissa commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/SchemaExternalController.java
> +    public JsonNode importSchemas(@RequestParam("file") MultipartFile file) {
renommer la méthode, et le endpoint (import-unit-schema ou import-schema/unit)

2024-12-06 11:05 UTC, bbenaissa commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/SchemaExternalControllerTest.java
> +}
Oui, à ajouter un cas KO stp

2024-12-06 11:05 UTC, bbenaissa commented on api/api-referential/referential-internal-client/src/main/java/fr/gouv/vitamui/referential/internal/client/ReferentialInternalWebClientFactory.java
> +    public SchemaInternalWebClient getSchemaInternalWebClient() {
Check si utile

2024-12-06 11:05 UTC, bbenaissa commented on api/api-referential/referential-internal-client/src/main/java/fr/gouv/vitamui/referential/internal/client/SchemaInternalWebClient.java
> +public class SchemaInternalWebClient extends BaseWebClient<InternalHttpContext> {
je pense que plutot à mettre dans SchemaInternalRestClient et supprimer le WebClient

2024-12-06 11:05 UTC, bbenaissa commented on api/api-referential/referential-internal-client/src/main/java/fr/gouv/vitamui/referential/internal/client/SchemaInternalWebClient.java
> +    public JsonNode importSchemas(InternalHttpContext context, String fileName, MultipartFile file) {
renommer la méthode aussi

2024-12-06 11:05 UTC, bbenaissa commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/CommonConstants.java
> +    public static final String IMPORT_SCHEMAS = "/import";
a renommer pour spécifier Schema + import + unit stp

2024-12-06 11:05 UTC, bbenaissa commented on deployment/roles/vitamui/templates/api-gateway/application.yml.j2
> +              /referential-api/schemas/**,
idem: renommage

2024-12-06 18:15 UTC, gtaltou commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/ImportSchemaService.java
> +    List<SchemaInputModel> convertImputSchemaToModelOfCreation(final List<SchemaInputModel> schemaModels) {
La méthode convertImputSchemaToModelOfCreation est supprimée, car elle n'ajoute effectivement  pas de valeur au traitement de sérialisation. Si des ajustements spécifiques sont nécessaires pour certains champs, cela pourrait être fait avant ou après la sérialisation, ou directement au niveau de la classe SchemaInputModel.

2024-12-06 18:34 UTC, gtaltou commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/dto/ImportSchemaDtoTest.java
Bien que ces tests ne soient pas toujours essentiels, Je pense qu'ils ne doivent pas être négligés  car ils couvrent plusieurs aspects fondamentaux d'une classe DTO :

La manipulation correcte des données via les getters et setters.
La sérialisation de l'objet en JSON pour l'échange de données.
La génération d'une chaîne de caractères informative via la méthode toString...parfois très utile lors du debogage

D'autres aspects potentiellement  importants, tels que la gestion des erreurs ou la validation des données sont couvert dans d'autres classes de tests.

2024-12-09 08:49 UTC, gtaltou commented on api/api-gateway/src/main/resources/application-dev.yml
> +              /referential-api/schemas/**,
Done... ce sera visible au prochain push d'ici la fin de la journée

2024-12-09 08:50 UTC, gtaltou commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dto/ImportSchemaDto.java
> +public class ImportSchemaDto extends IdDto implements Serializable {
Done... ce sera visible au prochain push d'ici la fin de la journée

2024-12-09 08:50 UTC, gtaltou commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/ImportSchemaService.java
> +    public RequestResponse<?> createImportSchema(
Done

2024-12-09 08:51 UTC, gtaltou commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/ImportSchemaService.java
> +            LOGGER.info("Create Ingest Contract EvIdAppSession : {} ", vitamContext.getApplicationSessionId());
Done

2024-12-09 08:51 UTC, gtaltou commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/ImportSchemaServiceTest.java
> +        MockitoAnnotations.openMocks(this);
Done

2024-12-09 08:51 UTC, gtaltou commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/ImportSchemaServiceTest.java
> +        VitamContext vitamContext = mock(VitamContext.class);
Done

2024-12-09 08:52 UTC, gtaltou commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/ImportSchemaServiceTest.java
> +    }
Done

2024-12-09 08:52 UTC, gtaltou commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/ImportSchemaServiceTest.java
> +        assertNotNull(byteArrayInputStream);
Done

2024-12-09 08:52 UTC, gtaltou commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/ImportSchemaServiceTest.java
> +        List<SchemaInputModel> result = importSchemaService.convertImputSchemaToModelOfCreation(schemaModels);
Done

2024-12-09 08:53 UTC, gtaltou commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/SchemaExternalController.java
> +    public JsonNode importSchemas(@RequestParam("file") MultipartFile file) {
Done

2024-12-09 09:12 UTC, gtaltou commented on ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
> +    "ONTOLOGY_FORMAT_JSON": "Le fichier d’import doit être au format json",
Done... ce sera visible au prochain push d'ici la fin de la journée

2024-12-09 09:15 UTC, gtaltou commented on ui/ui-frontend/projects/referential/src/app/ontology/ontology.component.ts
> +  }
Effectivement ce n'est pas utilisé pour l'instant... c'est viré !

2024-12-09 09:22 UTC, gtaltou commented on deployment/scripts/mongod/v8.1/001_add_import_schema_role.js.j2
> +
Done... ce sera visible au prochain push d'ici la fin de la journée

2024-12-09 09:22 UTC, gtaltou commented on deployment/scripts/mongod/v8.1/001_add_import_schema_role.js.j2
> +db = db.getSiblingDB('iam')
Done

2024-12-09 09:23 UTC, gtaltou commented on deployment/roles/vitamui/templates/api-gateway/application.yml.j2
> +              /referential-api/schemas/**,
Done

2024-12-09 10:07 UTC, gtaltou commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/SchemaExternalControllerTest.java
> +        MockMultipartFile validFile = new MockMultipartFile("file", "import_schema.csv", "text/csv", fileContent);
Done

2024-12-09 10:13 UTC, gtaltou commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/SchemaExternalControllerTest.java
> +        assertEquals(expectedResponse, Jresponse);
Done

2024-12-09 10:19 UTC, gtaltou commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/SchemaExternalControllerTest.java
> +}
Done

2024-12-09 10:47 UTC, gtaltou commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/service/SchemaExternalServiceTest.java
> +        MockitoAnnotations.openMocks(this);
Done

2024-12-09 11:11 UTC, gtaltou commented on api/api-referential/referential-internal-client/src/main/java/fr/gouv/vitamui/referential/internal/client/SchemaInternalWebClient.java
> +    public JsonNode importSchemas(InternalHttpContext context, String fileName, MultipartFile file) {
Done

2024-12-09 17:28 UTC, gtaltou commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/utils/ImportCSVUtils.java
> +    public static class ColumnDetails {
Done

2024-12-09 17:28 UTC, gtaltou commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/schema/ImportSchemaCSVUtilsTest.java
> +        // Call buildImportSchemaColumns with 'false' to make the identifier not mandatory
Done

2024-12-09 17:28 UTC, gtaltou commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/schema/ImportSchemaCSVUtilsTest.java
> +        );
Done

2024-12-09 17:31 UTC, gtaltou commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/SchemaInternalServiceTest.java
> +
Done

2024-12-09 17:31 UTC, gtaltou commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/CommonConstants.java
> +    public static final String IMPORT_SCHEMAS = "/import";
Done

2024-12-09 17:32 UTC, gtaltou commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
> +
Done

2024-12-09 17:32 UTC, gtaltou commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
> +
Done

2024-12-09 17:32 UTC, gtaltou commented on deployment/roles/vitamui/templates/api-gateway/application.yml.j2
> +              /referential-api/schemas/**,
Done

2024-12-09 17:33 UTC, gtaltou commented on ui/ui-frontend/projects/referential/src/app/core/api/referential-schema-api.service.ts
Done

2024-12-09 17:42 UTC, gtaltou commented on ui/ui-frontend/projects/referential/src/app/ontology/ontology.component.html
> -          <span>{{ 'ONTOLOGY.HOME.IMPORT' | translate }}</span>
Done

2024-12-09 17:51 UTC, gtaltou commented on ui/ui-frontend/projects/referential/src/app/core/api/referential-schema-api.service.spec.ts
Done

2024-12-10 08:40 UTC, ebernard commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/ImportSchemaServiceTest.java
> +        VitamContext vitamContext = mock(VitamContext.class);
Où ça ?

2024-12-10 08:40 UTC, ebernard commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/ImportSchemaServiceTest.java
> +    }
Où ça ?

2024-12-10 08:40 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/config/ApiReferentialServerConfig.java
> +    @Bean
> C'est une action en mode synchrone?

Oui

2024-12-10 08:40 UTC, ebernard commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/ImportSchemaServiceTest.java
> +        assertNotNull(byteArrayInputStream);
Où ça ?

2024-12-10 09:40 UTC, ebernard requested changes

2024-12-10 09:40 UTC, ebernard commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/SchemaExternalControllerTest.java
> +        byte[] fileContent = Files.readAllBytes(Paths.get(TEST_FILE_PATH));
Il vaut mieux aller chercher dans les resources (`getResourceAsStream`) plutôt que dans `src/test/resources/...`

2024-12-10 09:40 UTC, ebernard commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/SchemaExternalControllerTest.java
> +            TEST_FILE_NAME,
Le même fichier est utilisé pour le cas valide et pour le cas invalide ?

2024-12-10 09:40 UTC, ebernard commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/service/SchemaExternalServiceTest.java
> +    //private static final String TEST_FILE_PATH = "src/test/resources/data/import_schema.csv";
À enlever

2024-12-10 09:40 UTC, ebernard commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/service/SchemaExternalServiceTest.java
> +        internalHttpContext = mock(InternalHttpContext.class);
Pourquoi ne pas plutôt utiliser l'annotation `@Mock` ligne 32 ?

2024-12-10 09:40 UTC, ebernard commented on api/api-referential/referential-external/src/test/resources/data/import_schema_valid.csv
> +Path;Cardinality;IsObject;ShortName;Descriptionmmmmmmmmmmmmmmm
C'est voulu le mmmmmm ?

2024-12-10 09:40 UTC, ebernard commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/utils/ImportCSVUtils.java
> +    public static class ColumnDetails {
Où ça ?

2024-12-10 09:40 UTC, ebernard commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/SchemaInternalServiceTest.java
> +        objectMapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
Je vois que tu l'as supprimé.

2024-12-10 09:40 UTC, ebernard commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/CommonConstants.java
> +    public static final String IMPORT_UNIT_SCHEMAS = "/import-unit_schemas";
Pas d'underscore dans les URLs stp

2024-12-10 09:40 UTC, ebernard commented on ui/ui-frontend/projects/referential/src/app/ontology/ontology.component.html
> -          <span>{{ 'ONTOLOGY.HOME.IMPORT' | translate }}</span>
Vraiment ?

2024-12-10 09:40 UTC, ebernard commented on ui/ui-frontend/projects/referential/src/app/ontology/ontology.component.ts
> +  }
Vraiment ?

2024-12-10 09:46 UTC, gtaltou commented on api/api-referential/referential-internal-client/src/main/java/fr/gouv/vitamui/referential/internal/client/ReferentialInternalWebClientFactory.java
> +    public SchemaInternalWebClient getSchemaInternalWebClient() {
Cette partie reste inchangée dans l'optique de rester au plus proche de l'architecture actuelle

2024-12-10 09:47 UTC, gtaltou commented on api/api-referential/referential-internal-client/src/main/java/fr/gouv/vitamui/referential/internal/client/SchemaInternalWebClient.java
> +public class SchemaInternalWebClient extends BaseWebClient<InternalHttpContext> {
Cette partie reste inchangée dans l'optique de rester au plus proche de l'architecture actuelle

2024-12-10 10:13 UTC, gtaltou commented on api/api-referential/referential-external/src/test/resources/data/import_schema_valid.csv
> +Path;Cardinality;IsObject;ShortName;Descriptionmmmmmmmmmmmmmmm
C'est mon clavier qui m'a joué des tours... c'est viré !

2024-12-10 11:04 UTC, gtaltou commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/ImportSchemaServiceTest.java
> +        VitamContext vitamContext = mock(VitamContext.class);
Ce sera présent lors du prochain commit.

2024-12-10 11:53 UTC, gtaltou commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/ImportSchemaServiceTest.java
> +    }
Ce sera présent lors du prochain commit.

2024-12-10 13:31 UTC, gtaltou commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/CommonConstants.java
> +    public static final String IMPORT_UNIT_SCHEMAS = "/import-unit_schemas";
Dispo lors du prochain commit

2024-12-10 13:49 UTC, gtaltou commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/service/SchemaExternalServiceTest.java
> +        internalHttpContext = mock(InternalHttpContext.class);
Done...Dispo lors du prochain commit.

2024-12-10 14:06 UTC, gtaltou commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/SchemaExternalControllerTest.java
> +        schemaExternalService = mock(SchemaExternalService.class);
Done... dispo lors du prochain commit

2024-12-10 14:33 UTC, gtaltou commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/SchemaExternalControllerTest.java
> +        byte[] fileContent = Files.readAllBytes(Paths.get(TEST_FILE_PATH));
Done

2024-12-10 14:47 UTC, gtaltou commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/SchemaExternalControllerTest.java
> +            TEST_FILE_NAME,
Done

2024-12-10 14:50 UTC, gtaltou commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/SchemaExternalControllerTest.java
> +}
Dispo lors du prochain commit

2024-12-10 16:37 UTC, gtaltou commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/schema/ImportSchemaConverter.java
> +        }
copyProperties() ne gère pas les propriétés booléennes... à investiguer

2024-12-11 09:45 UTC, gtaltou commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/schema/ImportSchemaConverter.java
> +        importSchema.setObject(dto.isObject());
Souci résolu ... dispo lors du prochain commit.

2024-12-11 09:46 UTC, gtaltou commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/schema/ImportSchemaConverter.java
> +        importSchema.setDescription(dto.getDescription());
Souci résolu ... dispo lors du prochain commit.

2024-12-11 09:46 UTC, gtaltou commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/schema/ImportSchemaConverter.java
> +        }
Souci résolu ... dispo lors du prochain commit.

2024-12-11 09:47 UTC, gtaltou commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/schema/ImportSchemaConverter.java
> +        dto.setDescription(schemaInputModel.getDescription());
Souci résolu ... dispo lors du prochain commit.

2024-12-11 10:01 UTC, gtaltou commented on ui/ui-frontend/projects/referential/src/app/ontology/ontology.component.html
> -          <span>{{ 'ONTOLOGY.HOME.IMPORT' | translate }}</span>
Cette clé de traduction n'est plus utilisée.

2024-12-11 10:59 UTC, gtaltou commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/schema/ImportSchemaConverter.java
> +    }
Ce n'est pas utilisé... c'est viré !

2024-12-11 12:22 UTC, gtaltou commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/utils/ImportCSVUtils.java
> +    public static class ColumnDetails {
"protected" a été remis à sa place... c'était pour gérer certains tests qui ne fonctionnaient pas.

2024-12-11 12:39 UTC, gtaltou commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/schema/ImportSchemaConverterTest.java
> +        dto.setObject(true);
Done

2024-12-11 12:39 UTC, gtaltou commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/schema/ImportSchemaConverterTest.java
> +        assertEquals(SchemaCardinality.MANY, result.get(1).getCardinality());
Done

2024-12-12 10:13 UTC, ebernard commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/dto/ImportSchemaDtoTest.java
Ok  🤷

2024-12-12 10:28 UTC, ebernard commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/ImportSchemaServiceTest.java
> +    }
C'est où ?

2024-12-12 10:28 UTC, ebernard commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/SchemaExternalControllerTest.java
> +        schemaExternalService = mock(SchemaExternalService.class);
Ok.

2024-12-12 10:28 UTC, ebernard commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/SchemaExternalControllerTest.java
> +        MockMultipartFile validFile = new MockMultipartFile("file", "import_schema.csv", "text/csv", fileContent);
Ok

2024-12-12 10:28 UTC, ebernard commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/utils/ImportCSVUtils.java
> +    public static class ColumnDetails {
Ok.

2024-12-12 10:28 UTC, ebernard commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/schema/ImportSchemaConverterTest.java
> +        assertEquals(SchemaCardinality.MANY, result.get(1).getCardinality());
Ok.

2024-12-12 10:28 UTC, ebernard commented on ui/ui-frontend/projects/referential/src/app/ontology/ontology.component.ts
>  export class OntologyComponent extends SidenavPage<Ontology> {
implement OnInit (comme le gentil linter le suggère plus bas).

2024-12-12 10:28 UTC, ebernard commented on ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
>        "IMPORT": "Importer",
Normalement cette clé n'est plus utilisée. Vérifier et si c'est bien le cas, il faut la supprimer (idem dans en.json)

2024-12-12 10:28 UTC, ebernard commented on ui/ui-frontend/projects/referential/src/app/ontology/ontology.component.html
> -          <span>{{ 'ONTOLOGY.HOME.IMPORT' | translate }}</span>
Commentaire mis dans fr.json à la place.

2024-12-12 10:30 UTC, ebernard commented
J'ajouterais juste qu'apparemment ça ne builde pas.

2024-12-12 10:32 UTC, ebernard commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/ImportSchemaServiceTest.java
> +        VitamContext vitamContext = mock(VitamContext.class);
Pas encore vu.

2024-12-12 10:33 UTC, gtaltou commented on ui/ui-frontend/projects/referential/src/app/ontology/ontology.component.ts
> +  }
Utile pour la suite de L'US...

2024-12-12 10:37 UTC, ebernard commented on ui/ui-frontend/projects/referential/src/app/ontology/ontology.component.ts
> +  }
Je sais, on en a parlé hier, mais faut pas dire que c'est viré si ça ne l'est pas 😄

2024-12-12 11:41 UTC, gtaltou commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/ImportSchemaServiceTest.java
> +    }
@Test
    @DisplayName("Should generate valid JSON when serializing SchemaInputModel list")
    void testSerializeImportSchema_shouldGenerateValidJson() throws IOException {

2024-12-12 18:15 UTC, gtaltou commented on ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
>        "IMPORT": "Importer",
![IlsSontUtilisés](https://github.com/user-attachments/assets/d0638c3c-264c-441e-894b-fed00512b82c)
Je pense qu'ils sont utilisés

2024-12-13 13:40 UTC, ebernard commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/ImportSchemaServiceTest.java
> +    private Logger logger;
Pourquoi le logger est-il un mock ?

2024-12-13 13:40 UTC, ebernard commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/ImportSchemaServiceTest.java
> +        VitamContext vitamContext = mock(VitamContext.class);
Ok.

2024-12-13 13:41 UTC, ebernard commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/SchemaExternalControllerTest.java
> +        byte[] fileContent = Files.readAllBytes(Paths.get(TEST_FILE_PATH));
Ok.

2024-12-13 13:42 UTC, ebernard commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/SchemaExternalControllerTest.java
> +            TEST_FILE_NAME,
Ok.

2024-12-13 13:43 UTC, ebernard commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/service/SchemaExternalServiceTest.java
> +    //private static final String TEST_FILE_PATH = "src/test/resources/data/import_schema.csv";
ok

2024-12-13 13:44 UTC, ebernard commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/service/SchemaExternalServiceTest.java
> +        internalHttpContext = mock(InternalHttpContext.class);
Ok.

2024-12-13 13:46 UTC, ebernard commented on ui/ui-frontend/projects/referential/src/app/ontology/ontology.component.ts
>  export class OntologyComponent extends SidenavPage<Ontology> {
ok

2024-12-13 13:47 UTC, ebernard commented on ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
>        "IMPORT": "Importer",
La capture d'écran ne prouve rien.

Mais bon, admettons. C'est pas la fin du monde non plus.

2024-12-13 13:55 UTC, ebernard commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/SchemaExternalControllerTest.java
> +}
Ok.

2024-12-13 13:55 UTC, ebernard commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/schema/ImportSchemaConverterTest.java
> +        dto.setObject(true);
Ok (plus bas).

2024-12-13 14:36 UTC, bbenaissa commented on api/api-referential/referential-internal-client/src/main/java/fr/gouv/vitamui/referential/internal/client/SchemaInternalWebClient.java
> +public class SchemaInternalWebClient extends BaseWebClient<InternalHttpContext> {
En fait, on a 2 types de clients: *WebClient pour les appels de types Asynchrones, et *RestClient pour les services avec appels Synchrones

2024-12-13 19:52 UTC, bbenaissa commented
Il reste des remarques à prendre en compte en plus de celles d'Etienne, comme discuté, ça pourrai être pris en compte dans la prochaine PR sur le même sujet

2024-12-13 19:52 UTC, bbenaissa approved these changes

2024-12-13 20:15 UTC, ebernard commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/ImportSchemaServiceTest.java
> +    private Logger logger;
Sera à traiter ultérieurement s'il te plaît.

2024-12-13 20:15 UTC, ebernard approved these changes

2024-12-16 09:16 UTC, merged