Story 13053 fusion api referential
ProgrammeVitam/vitam-ui pull request #2290
Opened 2024-12-09 08:33 UTC by mohatizaoui

## Description

*Description des modifications*

## Type de changement

*Indiquer le ou les types de changements*

* Build
* PKI
* Ansiblerie
* Nouveau Code
* Correction
* Refactorisation de code
* Autre

## Documentation

*Indiquer la documentation mise à jour*

* [ ] Quels sont les nouvelles documentations ?
* [ ] Quels sont les modifications existantes ?
* [ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

* manuel
* environnement
* TU

## Migration

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist

*Sélectionner les éléments de la checklist*

* [ ] Mon code suit le style de code de ce projet.
* [ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.
* [ ] J'ai fait les changements correspondant dans la documentation RAML.
* [ ] J'ai fait les changements correspondant dans la documentation Métier.
* [ ] J'ai fait les changements correspondant dans la documentation Technique.
* [ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.
* [ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.
* [ ] Les tests unitaires nouveaux et existants passent avec succès localement.
* [ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

* VAS (Vitam Accessible en Service)
* CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2024-12-12 17:24 UTC, marob requested changes
Supprimer referential-internal, renommer referential-external en referential.

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/accesscontract/AccessContractInternalService.java
>      public AccessContractInternalService(
External

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/AccessContractExternalController.java
> +    private AccessContractInternalService accessContractExternalService;
External

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/AccessionRegisterExternalController.java
> +    private final AccessionRegisterInternalService accessionRegisterDetailExternalService;
accessionRegisterDetailExternalService -> accessionRegisterInternalService

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/accessionregister/AccessionRegisterInternalService.java
> +    private AccessionRegisterStatsDto buildStatisticData(
Méthode inutilisée

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/accessionregister/AccessionRegisterInternalService.java
> +    public List<AccessionRegisterSummaryDto> getAll(final Optional<String> criteria) {
Param criteria non utilisé

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/AgencyExternalController.java
> +    private AgencyInternalService agencyExternalService;
External -> Internal

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ArchivalProfileUnitExternalController.java
> +    private ArchivalProfileUnitInternalService archivalProfileUnitExternalService;
External -> Internal

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ArchivalProfileUnitExternalController.java
> +    //TODO methode note use A supprimer
Supprimer

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ContextExternalController.java
> +    private ContextInternalService contextExternalService;
External -> Internal

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/FileFormatExternalController.java
> +    private FileFormatInternalService fileFormatExternalService;
External -> Internal

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/IngestContractExternalController.java
> +    private IngestContractInternalService ingestContractExternalService;
External -> Internal

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/LogbookManagementOperationExternalController.java
> +    private final LogbookManagementOperationInternalService logbookManagementOperationExternalService;
External -> Internal

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ManagementContractExternalController.java
> +    private final ManagementContractInternalService managementContractExternalService;
External -> Internal

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ManagementContractExternalController.java
> +    public ManagementContractExternalController(ManagementContractInternalService managementContractExternalService) {
External -> Internal

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OntologyExternalController.java
> +    private OntologyInternalService ontologyExternalService;
External -> Internal

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OntologyExternalController.java
> +    public OntologyExternalController(OntologyInternalService ontologyExternalService) {
External -> Internal

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OperationExternalController.java
> +    private OperationInternalService operationExternalService;
External -> Internal

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ProfileExternalController.java
> +    private ProfileInternalService profileExternalService;
External -> Internal

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/RuleExternalController.java
> +    private RuleInternalService ruleExternalService;
External -> Internal

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/RuleExternalController.java
> +    public RuleExternalController(final RuleInternalService ruleExternalService) {
External -> Internal

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/SecurityProfileExternalController.java
> +    private SecurityProfileInternalService securityProfileExternalService;
External -> Internal

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/UnitExternalController.java
> +    private UnitInternalService unitExternalService;
External -> Internal

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/accesscontract/AccessContractInternalService.java
> +    public List<AccessContractDto> getAll(final Optional<String> criteria) {
Param criteria non utilisé

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/accesscontract/AccessContractInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/accesscontract/AccessContractInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/accesscontract/AccessContractInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/accesscontract/AccessContractInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/accesscontract/AccessContractInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/accesscontract/AccessContractInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/accesscontract/AccessContractInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/accesscontract/AccessContractInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/accessionregister/AccessRegisterStatsHelper.java
> +            .map(ardm -> ardm.getObjectSize().getIngested())
.map(AccessionRegisterDetailModel::getObjectSize)
.map(RegisterValueDetailModel::getIngested)

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/accessionregister/AccessRegisterStatsHelper.java
> +            .map(ardm -> ardm.getTotalObjects().getIngested())
.map(AccessionRegisterDetailModel::getTotalObjects)
.map(RegisterValueDetailModel::getIngested)

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/accessionregister/AccessRegisterStatsHelper.java
> +            .map(ardm -> ardm.getTotalUnits().getIngested())
.map(AccessionRegisterDetailModel::getTotalUnits)
.map(RegisterValueDetailModel::getIngested)

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/accessionregister/AccessRegisterStatsHelper.java
> +            .map(ardm -> ardm.getTotalObjectsGroups().getIngested())
.map(AccessionRegisterDetailModel::getTotalObjectsGroups)
.map(RegisterValueDetailModel::getIngested)

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyConverter.java
> +        final AgencyModelDto Agency = VitamUIUtils.copyProperties(dto, new AgencyModelDto());
return VitamUIUtils.copyProperties(dto, new AgencyModelDto());

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyConverter.java
> +        final AgencyDto dto = VitamUIUtils.copyProperties(Agency, new AgencyDto());
return VitamUIUtils.copyProperties(Agency, new AgencyDto());

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyInternalService.java
> +                return fr.gouv.vitamui.referential.common.utils.AgencyConverter.convertVitamToDto(
importer

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyInternalService.java
>              RequestResponse<?> requestResponse = vitamAgencyService.patchAgency(
Inutilisé

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/archivalprofileunit/ArchivalProfileUnitInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/archivalprofileunit/ArchivalProfileUnitInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/archivalprofileunit/ArchivalProfileUnitInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/archivalprofileunit/ArchivalProfileUnitInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/archivalprofileunit/ArchivalProfileUnitInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
Inutile si on throw systématiquement une exception

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/archivalprofileunit/ArchivalProfileUnitInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/archivalprofileunit/ArchivalProfileUnitInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/archivalprofileunit/ArchivalProfileUnitInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/archivalprofileunit/ArchivalProfileUnitInternalService.java
> +    private ExternalSecurityService externalSecurityService;
final (idem pour les autre) + supprimer logbookService

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/context/ContextInternalService.java
> +    private VitamContext buildVitamContext() {
Inutile, déjà implémenté par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/context/ContextInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/context/ContextInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/context/ContextInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/context/ContextInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/context/ContextInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/context/ContextInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/context/ContextInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/fileformat/FileFormatInternalService.java
> +    //TOTO A suppriemr
Supprimer ?

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/fileformat/FileFormatInternalService.java
> +    private VitamContext buildVitamContext() {
Inutile, déjà implémenté dans externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/fileformat/FileFormatInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/fileformat/FileFormatInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/fileformat/FileFormatInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/fileformat/FileFormatInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/fileformat/FileFormatInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/fileformat/FileFormatInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/fileformat/FileFormatInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/fileformat/FileFormatInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/fileformat/FileFormatInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/ingestcontract/IngestContractInternalService.java
> +    private VitamContext buildVitamContext() {
Inutile, déjà implémenté dans externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/ingestcontract/IngestContractInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/ingestcontract/IngestContractInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/ingestcontract/IngestContractInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/ingestcontract/IngestContractInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/ingestcontract/IngestContractInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/ingestcontract/IngestContractInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/ingestcontract/IngestContractInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/ingestcontract/IngestContractInternalService.java
> +        final VitamContext vitamContext = externalSecurityService.buildVitamContext(
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/ingestcontract/IngestContractInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/logbookmanagement/LogbookManagementOperationInternalService.java
> +    private VitamContext buildVitamContext() {
Inutile, déjà implémenté dans externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/logbookmanagement/LogbookManagementOperationInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/logbookmanagement/LogbookManagementOperationInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/logbookmanagement/LogbookManagementOperationInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/managementcontract/service/ManagementContractInternalService.java
> +    private VitamContext buildVitamContext() {
Inutile, déjà implémenté dans externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/managementcontract/service/ManagementContractInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/managementcontract/service/ManagementContractInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/managementcontract/service/ManagementContractInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/managementcontract/service/ManagementContractInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/managementcontract/service/ManagementContractInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/managementcontract/service/ManagementContractInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/managementcontract/service/ManagementContractInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/ontology/OntologyInternalService.java
> +    private VitamContext buildVitamContext() {
Inutile, déjà implémenté dans externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/ontology/OntologyInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/ontology/OntologyInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/ontology/OntologyInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/ontology/OntologyInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/ontology/OntologyInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/ontology/OntologyInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/ontology/OntologyInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/ontology/OntologyInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/ontology/OntologyInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/operation/OperationInternalService.java
> +    private ProbativeValueInternalService probativeValueInternalService;
Injecter par constructeur

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/operation/OperationInternalService.java
> +    private VitamContext buildVitamContext() {
Inutile, déjà implémenté dans externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/operation/OperationInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/operation/OperationInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/operation/OperationInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/operation/OperationInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/operation/OperationInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/operation/OperationInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/operation/OperationInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/operation/OperationInternalService.java
> +        VitamContext vitamContext = buildVitamContext();
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/operation/OperationInternalService.java
> +                TypeReference<HashMap<String, Object>> typRef = new TypeReference<HashMap<String, Object>>() {};
new TypeReference<>() {};

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/operation/OperationInternalService.java
> +    public fr.gouv.vitamui.commons.vitam.api.dto.LogbookOperationsResponseDto findHistoryById(String id) {
Importer fr.gouv.vitamui.commons.vitam.api.dto.LogbookOperationsResponseDto

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/AbstractService.java
> +        return externalSecurityService.buildVitamContext(externalSecurityService.getTenantIdentifier());
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/securityprofile/SecurityProfileInternalService.java
> +        LOGGER.debug("Creating Security Profile: {}", securityProfileDto);
Creating -> Patching

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/service/ExternalParametersService.java
> +    public VitamContext buildVitamContextFromExternalParam() {
Inutilisé

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/unit/UnitInternalService.java
> +    private ObjectMapper objectMapper;
final

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/unit/UnitInternalService.java
> +    public VitamUISearchResponseDto findUnitById(final String id) throws VitamClientException {
Retirer l'exception

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/unit/UnitInternalService.java
> +        final VitamContext vitamContext = buildVitamContext();
Inutile

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/ManagementContractExternalControllerTest.java
> +    private ManagementContractInternalService managementContractExternalService;
External -> Internal

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/OntologyExternalControllerTest.java
> +    private OntologyInternalService ontologyExternalService;
External -> Internal

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/test/resources/application.yml
> +    name: referential-external-application
referential-application ?

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/src/test/resources/application.yml
> +  host: xxx
xxx ?

2024-12-12 17:24 UTC, marob commented on api/api-referential/referential-external/pom.xml
> +        <!-- Export CSV -->
Doublon

2024-12-12 17:24 UTC, marob commented on api/api-pastis/pastis-external/src/main/java/fr/gouv/vitamui/pastis/server/config/ApiPastisServerConfig.java
> +    //TODO remove internal and external
TODO

2024-12-12 17:24 UTC, marob commented on api/api-pastis/pastis-external/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
> +        return externalSecurityService.buildVitamContext(externalSecurityService.getTenantIdentifier());
Remplacer par externalSecurityService.getVitamContext()

2024-12-12 17:24 UTC, marob commented on api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/client/AbstractExternalClientService.java
> +    //TODO remove internal and external
TODO

2024-12-12 17:24 UTC, marob commented on api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/client/AbstractExternalClientService.java
> +        // final String customerId = externalSecurityService.getUser().getCustomerId();
Code mort

2024-12-12 17:24 UTC, marob commented on deployment/roles/vitamui/templates/referential-external/application.yml.j2
Supprimer la partie "vitamui.referential_internal.secure" ?
Renommer "referential-external" en "referential" ?

2024-12-19 16:49 UTC, mohatizaoui commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/operation/OperationInternalService.java
> +    public fr.gouv.vitamui.commons.vitam.api.dto.LogbookOperationsResponseDto findHistoryById(String id) {
Il y a une classe pareil qui se nomme avec le même  nom

2024-12-20 00:15 UTC, closed without merging