CP V7.1 - Story #13791 cc: refresh dev certs
ProgrammeVitam/vitam-ui pull request #2294
Opened 2024-12-09 11:43 UTC by laedanrex

CHERRY-PICK

2024-12-09 13:56 UTC, marob approved these changes

2024-12-10 14:43 UTC, Regzox approved these changes

2024-12-10 17:29 UTC, GiooDev requested changes

2024-12-10 17:29 UTC, GiooDev commented on deployment/environments/hosts.local
> +hosts_vitamui_api_gateway
Pas d'api gateway en 7.0

2024-12-17 09:57 UTC, GiooDev commented
Commits à squash avant de merger plz.

Ou alors revoir les intitulés des commits si besoin de les conserver séparés.

2025-01-16 12:51 UTC, GiooDev commented
Maintenant que la 7.0.2 est sortie, cela nous laisse l'opportunité de merger cette PR au besoin.

PS: Commits à squash avant de merger plz. Ou alors revoir les intitulés des commits si besoin de les conserver séparés.

2025-09-03 16:11 UTC, marob commented
@GiooDev 7.0 n'est plus maintenu. On cloture ?

2025-09-12 14:57 UTC, closed without merging