bug #14026 : agents services creation forbid only whitespace
ProgrammeVitam/vitam-ui pull request #2299
Opened 2024-12-10 14:59 UTC by hazco75

## Description

When creating agent services, we must forbid whitespaces-only fields identifier and name

## Type de changement

* Correction

2024-12-10 17:31 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.validators.ts
> +  };
```suggestion
  onlyWhitespaces = Validators.pattern('^\s+$');
  };
```

2024-12-10 17:31 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.ts
> +        [Validators.required, this.agencyCreateValidators.onlyWhitespaces()],
```suggestion
      name: [null, [Validators.required, this.agencyCreateValidators.onlyWhitespaces], this.agencyCreateValidators.uniqueName()],
      identifier: [
        null,
        [Validators.required, this.agencyCreateValidators.onlyWhitespaces],
```

2024-12-10 17:31 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.spec.ts
> +      onlyWhitespaces: () => of(null),
```suggestion
      onlyWhitespaces: () => {},
```

2024-12-11 09:02 UTC, Regzox commented on ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.validators.ts
> +  };
C'est justement le inverse de cette regex ?

2024-12-11 09:02 UTC, Regzox commented on ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.validators.ts
> +  };
![image](https://github.com/user-attachments/assets/4656efb6-63d6-4b77-868e-eddf5c5cdadd)

Le deuxième cas doit passer non ?

2024-12-11 09:33 UTC, Regzox approved these changes

2024-12-11 10:08 UTC, hazco75 commented on ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.validators.ts
> +  };
Oui le deuxième cas doit passer, je vais modifier la méthode

2024-12-11 10:58 UTC, marob commented on ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.validators.ts
Ajouter un test

2024-12-11 13:24 UTC, laedanrex approved these changes

2024-12-11 13:26 UTC, marob requested changes
Merge bloqué en attendant un TU

2024-12-11 15:31 UTC, hazco75 commented on ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.validators.ts
Test ajouté @marob

2024-12-11 16:16 UTC, marob approved these changes

2024-12-11 16:59 UTC, merged