Story 13053 final fusion api
ProgrammeVitam/vitam-ui pull request #2310
Opened 2024-12-12 14:36 UTC by mohatizaoui

## Description

*Description des modifications*

## Type de changement

*Indiquer le ou les types de changements*

* Build
* PKI
* Ansiblerie
* Nouveau Code
* Correction
* Refactorisation de code
* Autre

## Documentation

*Indiquer la documentation mise à jour*

* [ ] Quels sont les nouvelles documentations ?
* [ ] Quels sont les modifications existantes ?
* [ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

* manuel
* environnement
* TU

## Migration

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist

*Sélectionner les éléments de la checklist*

* [ ] Mon code suit le style de code de ce projet.
* [ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.
* [ ] J'ai fait les changements correspondant dans la documentation RAML.
* [ ] J'ai fait les changements correspondant dans la documentation Métier.
* [ ] J'ai fait les changements correspondant dans la documentation Technique.
* [ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.
* [ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.
* [ ] Les tests unitaires nouveaux et existants passent avec succès localement.
* [ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

* VAS (Vitam Accessible en Service)
* CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2024-12-19 15:14 UTC, ebernard requested changes
Quasiment que des remarques sur l'organisation du code, mais rien de bien grave. Tu as fait un travail de Titan!

2024-12-19 15:14 UTC, ebernard commented on api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/client/AbstractExternalClientService.java
> +        // final String customerId = externalSecurityService.getUser().getCustomerId();
Supprimer les commentaires inutiles.

2024-12-19 15:14 UTC, ebernard commented on api/api-pastis/pastis-standalone/src/test/java/fr/gouv/vitamui/pastis/standalone/ProfileControllerTest.java
Pourquoi est-ce que c'est supprimé ?

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/pom.xml
> +            <artifactId>opencsv</artifactId>
dupliqué avec celui juste au-dessus

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ArchivalProfileUnitExternalController.java
> +    //TODO methode note use A supprimer
À supprimer, donc.

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ContextExternalController.java
> +        return contextExternalService.getAll();
Du coup `criteria` n'est pas utilisé ?

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/IngestContractExternalController.java
> +        return ingestContractExternalService.getAll();
`criteria` n'est pas utilisé ?

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ManagementContractExternalController.java
> +        return managementContractExternalService.getAll();
`criteria` n'est pas utilisé ?

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OntologyExternalController.java
> +        return ontologyExternalService.getAll();
Même remarque.

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/RuleExternalController.java
> +        return ruleExternalService.getAll();
Idem

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/UnitExternalController.java
> +    private UnitExtternalService unitExternalService;
```suggestion
    private UnitExternalService unitExternalService;
```

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/accesscontract/AccessContractExternalService.java
> +        return this.getAll(vitamContext);
`criteria` ? Je pense qu'il faudrait passer le paramètre quitte à l'ignorer dans le `getAll(VitamContext vitamContext, Optional<String> criteria)` (en mettant un commentaire).

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/accesscontract/AccessContractExternalService.java
> +        final Optional<DirectionDto> direction
Mettre les paramètres dans le même ordre que dans la méthode au-dessous.

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/accessionregister/AccessionRegisterExternalService.java
> +        final Optional<DirectionDto> direction
Avoir le même ordre dans les paramètres

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/accessionregister/AccessionRegisterExternalService.java
> +        return this.getAll(vitamContext);
Ajouter un commentaire comme quoi le `criteria` est ignoré.

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyConverter.java
> +        final AgencyDto dto = VitamUIUtils.copyProperties(Agency, new AgencyDto());
```suggestion
    public AgencyDto convertVitamToDto(final AgencyModelDto agency) {
        final AgencyDto dto = VitamUIUtils.copyProperties(agency, new AgencyDto());
```

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyExternalService.java
> +                return fr.gouv.vitamui.referential.common.utils.AgencyConverter.convertVitamToDto(
Le nom complet de la classe est-il nécessaire ici ? On ne pouvait pas faire un import ?

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyExternalService.java
> +    public AgencyDto getOne(String id) {
À bouger près de la définition de `getOne(VitamContext, String)`.

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyExternalService.java
> +        return this.getAll(vitamContext);
Commenter le fait que `criteria` n'est pas utilisé.

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyExternalService.java
> +            return fr.gouv.vitamui.referential.common.utils.AgencyConverter.convertVitamsToDtos(
Import ?

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyExternalService.java
> +        final List<AgencyDto> valuesDto = fr.gouv.vitamui.referential.common.utils.AgencyConverter.convertVitamsToDtos(
Idem : import ?

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyExternalService.java
> +        return this.getAllPaginated(page, size, orderBy, direction, vitamContext, criteria);
Avoir le même ordre pour les arguments entre les deux méthodes.

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyExternalService.java
> +                fr.gouv.vitamui.referential.common.utils.AgencyConverter.convertDtosToVitams(Arrays.asList(agencyDto)),
Import ?

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyExternalService.java
> +    public boolean check(AgencyDto agencyDto) {
À bouger près de la définition de `check(VitamContext, AgencyDto)`

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyExternalService.java
> +                fr.gouv.vitamui.referential.common.utils.AgencyConverter.convertDtoToVitam(agencyDto)
Import?

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyExternalService.java
> +            return fr.gouv.vitamui.referential.common.utils.AgencyConverter.convertVitamToDto(agencyModelDto);
Import?

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyExternalService.java
> +    public AgencyDto create(final AgencyDto agencyDto) {
À bouger près de create(VitamContext, AgencyDto)

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyExternalService.java
> +        AgenciesModel agencyModelDto = fr.gouv.vitamui.referential.common.utils.AgencyConverter.convertDtoToVitam(
Import?

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyExternalService.java
> +    public AgencyDto patch(final Map<String, Object> partialDto) {
À bouger

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/agency/AgencyExternalService.java
> +    public JsonNode importAgencies(String fileName, MultipartFile file) {
À bouger

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/archivalprofileunit/ArchivalProfileUnitExternalService.java
> +    public ArchivalProfileUnitDto getOne(final String identifier) {
À bouger près de la définition de `getOne(VitamContext, String)`.

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/archivalprofileunit/ArchivalProfileUnitExternalService.java
> +        return this.getAll(vitamContext, criteria);
À bouger

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/archivalprofileunit/ArchivalProfileUnitExternalService.java
> +        final Optional<DirectionDto> direction
Ordre des paramètres

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/archivalprofileunit/ArchivalProfileUnitExternalService.java
> +
```suggestion
    public ArchivalProfileUnitDto update(final ArchivalProfileUnitDto dto)
        throws AccessExternalClientException, InvalidParseOperationException {
        final VitamContext vitamContext = this.buildVitamContext();
        return this.update(dto, vitamContext);
    }

    public boolean checkExists(final String criteria) {
        final VitamContext vitamContext = this.buildVitamContext();
        // Implémentez la logique dans l'InternalService si nécessaire
        throw new UnsupportedOperationException("Method not implemented yet in InternalService");
    }

```

(bouger update près de l'autre implémentation).

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/archivalprofileunit/ArchivalProfileUnitExternalService.java
> +    public ResponseEntity<JsonNode> importArchivalUnitProfiles(String fileName, MultipartFile file) {
Si ce n'est plus `importProfile` alors renommer l'autre aussi.

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/context/ContextExternalService.java
> +    public PaginatedValuesDto<ContextDto> getAllPaginated(
À bouger près des implémentations respectives.

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/context/ContextExternalService.java
> +    }
Idem

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/fileformat/FileFormatExternalService.java
> +    //TOTO A suppriemr
Fais-le alors, Toto !

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/fileformat/FileFormatExternalService.java
> +    public FileFormatDto getOne(String identifier) {
Bouger près de chaque implementation respective (idem pour les suivants).

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/ingestcontract/IngestContractExternalService.java
> +    public IngestContractDto getOne(String identifier) {
Mêmes remarques (bouger) + pareil pour les méthodes suivantes.

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/ingestcontract/IngestContractExternalService.java
> +        Optional<DirectionDto> direction
Ordre des paramètres

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/logbookmanagement/LogbookManagementOperationExternalService.java
> +    public ProcessDetailDto searchOperationsDetails(ProcessQuery processQuery) {
Pareil ici aussi

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/ontology/OntologyExternalService.java
> +    public OntologyDto getOne(String identifier) {
Idem (bouger + ordre des paramètres).

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/operation/OperationExternalService.java
> +        return OperationConverter.convertVitamsToDtos(this.findAll(vitamContext, query).getResults());
getAll au dessus, findAll ici.

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/operation/OperationExternalService.java
> +        final Optional<DirectionDto> direction
Ordre des paramètres

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/operation/OperationExternalService.java
> +    public boolean runAudit(AuditCreateOptions auditOptions) {
Bouger

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/operation/OperationExternalService.java
> +    public fr.gouv.vitamui.commons.vitam.api.dto.LogbookOperationsResponseDto findHistoryById(String id) {
Importer fr.gouv.vitamui.commons.vitam.api.dto.LogbookOperationsResponseDto ?

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/operation/OperationExternalService.java
> +        JsonNode history = this.findHistoryByIdentifier(vitamContext, id);
findHistoryById + findHistoryByIdentifier

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/operation/OperationExternalService.java
> +                fr.gouv.vitamui.commons.vitam.api.dto.LogbookOperationsResponseDto.class
Import

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/profile/ProfileExternalService.java
> +    public List<ProfileDto> getAll(Optional<String> criteria) {
Bouger.

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/profile/ProfileExternalService.java
> +        final Optional<DirectionDto> direction
Ordre des paramètres ?

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/profile/ProfileExternalService.java
> +    public ProfileDto getOne(String id) {
Bouger + idem en dessous

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/rule/RuleExternalService.java
> +    public RuleDto getOne(String identifier) {
Bouger

2024-12-19 15:14 UTC, ebernard commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/securityprofile/SecurityProfileExternalService.java
> +    public SecurityProfileDto getOne(final String id) {
Bouger + ordre des paramètres.

2024-12-20 13:49 UTC, mohatizaoui commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ContextExternalController.java
> +        return contextExternalService.getAll();
non, c'est le paginated qui est utilisé dans criteria je l'ai laissé pour ne pas casser l'api

2024-12-20 13:49 UTC, mohatizaoui commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/IngestContractExternalController.java
> +        return ingestContractExternalService.getAll();
idem

2024-12-20 13:49 UTC, mohatizaoui commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ContextExternalController.java
> +        return contextExternalService.getAll();
non

2024-12-20 17:18 UTC, marob commented on deployment/roles/filebeat/tasks/add_inputs.yml
> +        vitamui_service_list: "{{ services_on_vm | intersect(vitamui_keys) | select('ne', 'referential_internal')   }}"
Pourquoi il y a besoin d'exclure "referential_internal" ? Il y en a toujours une trace quelque part ?

2024-12-20 17:18 UTC, marob commented on deployment/roles/filebeat/tasks/add_inputs.yml
> +        var: vitamui_keys
Retirer le debug ?

2024-12-20 17:18 UTC, marob commented on deployment/roles/vitamui/templates/referential-external/application.yml.j2
> +internal_ontology_file_path: {{ vitamui_folder_data }}/internal_ontology_fields.json
internal_ontology_file_path dupliqué

2024-12-20 17:18 UTC, marob commented on api/api-pastis/pastis-standalone/pom.xml
> +        </dependency>
Étonnant d'avoir besoin d'iam-security pour du standalone !
Est-ce que le téléchargement de profils fonctionne bien en standalone ?

2024-12-20 17:18 UTC, marob commented on api/api-referential/referential-external/src/main/config/access-external-client.conf
> +  - keyPath: /vitam/conf/certs/our-keystore-env-ga.p12
Je n'ai pas ce fichier. Il sort d'où ?
Idem pour ingest et collect.

2024-12-20 17:18 UTC, marob commented on api/api-referential/referential-external/src/main/config/access-external-client.conf
> +  - keyPath: /vitam/conf/certs/our-trust-store.jks
Je n'ai pas ce fichier. Il sort d'où ?
Idem pour ingest et collect.

2024-12-20 17:18 UTC, marob commented on api/api-referential/referential-external/src/test/resources/data/import_access_contracts_valid.csv
> +;Contrats d'accès Full accès 0;;;;;;;;;;;;;;
Étonnant que le précédent était valide avec juste "Name*" et "toto" ...

2024-12-20 20:57 UTC, bbenaissa commented on deployment/roles/filebeat/tasks/add_inputs.yml
> +        vitamui_service_list: "{{ services_on_vm | intersect(vitamui_keys) | select('ne', 'referential_internal')   }}"
il y a un process d'install de filebeat qui tombe en erreur si un service est absent. c'était une solution temporaire

2024-12-20 20:57 UTC, bbenaissa commented on deployment/roles/filebeat/tasks/add_inputs.yml
> +        var: vitamui_keys
il y a un process d'install de filebeat qui tombe en erreur si un service est absent. c'était une solution temporaire

2024-12-20 20:58 UTC, bbenaissa commented on deployment/roles/vitamui/templates/referential-external/application.yml.j2
> +internal_ontology_file_path: {{ vitamui_folder_data }}/internal_ontology_fields.json
supprimé

2024-12-20 20:58 UTC, bbenaissa commented on api/api-referential/referential-external/src/main/config/access-external-client.conf
> +  - keyPath: /vitam/conf/certs/our-trust-store.jks
fichier de conf local, supprimé

2024-12-23 09:42 UTC, bbenaissa commented
Il reste quelques remarques non bloquants à traiter post merge

2024-12-23 09:42 UTC, bbenaissa approved these changes

2024-12-23 09:52 UTC, GiooDev approved these changes
Approve ops part.

2024-12-23 09:55 UTC, merged