Story #13791 cc: use VitamuiHttpHeaders
ProgrammeVitam/vitam-ui pull request #2316
Opened 2024-12-16 10:05 UTC by laedanrex

## Description

use vitamui headers

2024-12-16 14:53 UTC, ebernard requested changes

2024-12-16 14:53 UTC, ebernard commented on ui/ui-frontend/projects/referential/src/app/agency/agency.service.ts
> +import { VitamuiHttpHeaders } from '../../../../vitamui-library/src/app/modules';
```suggestion
import { VitamuiHttpHeaders } from 'vitamui-library';
```

2024-12-16 14:53 UTC, ebernard commented on ui/ui-frontend/projects/referential/src/app/context/context.service.ts
> +import { VitamuiHttpHeaders } from '../../../../vitamui-library/src/app/modules';
```suggestion
import { VitamuiHttpHeaders } from 'vitamui-library';
```

2024-12-16 14:53 UTC, ebernard commented on ui/ui-frontend/projects/referential/src/app/file-format/file-format.service.ts
> +import { VitamuiHttpHeaders } from '../../../../vitamui-library/src/app/modules';
```suggestion
import { VitamuiHttpHeaders } from 'vitamui-library';
```

2024-12-16 14:53 UTC, ebernard commented on ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.ts
> +import { VitamuiHttpHeaders } from '../../../../../vitamui-library/src/app/modules';
```suggestion
import { VitamuiHttpHeaders } from 'vitamui-library';
```

2024-12-16 14:53 UTC, ebernard commented on ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-information-tab/ingest-contract-information-tab.component.ts
> +import { VitamuiHttpHeaders } from '../../../../../../vitamui-library/src/app/modules';
```suggestion
import { VitamuiHttpHeaders } from 'vitamui-library';
```

2024-12-16 14:53 UTC, ebernard commented on ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract.service.ts
> +import { VitamuiHttpHeaders } from '../../../../vitamui-library/src/app/modules';
```suggestion
import { VitamuiHttpHeaders } from 'vitamui-library';
```

2024-12-16 14:53 UTC, ebernard commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract.service.ts
> +import { VitamuiHttpHeaders } from '../../../../vitamui-library/src/app/modules';
```suggestion
import { VitamuiHttpHeaders } from 'vitamui-library';
```

2024-12-16 14:53 UTC, ebernard commented
Je sais que c'est en draft, c'est juste pour pas oublier.

2024-12-19 13:29 UTC, Regzox approved these changes

2024-12-20 12:28 UTC, ebernard approved these changes

2024-12-20 12:28 UTC, merged