[VAS] item 7095 : Export archive units into csv file
ProgrammeVitam/vitam-ui pull request #256
Opened 2021-04-19 08:57 UTC by bbenaissa

## Description
L'objectif de cette PR est de pouvoir exporter les résultats de recherche des unités archivistiques en CSV.

Les tests unitaires vont venir après, dans une autre PR. 

## Type de changement:
* Front
* Nouveau Code
* Correction

## Tests:
L'ensemble des tests unitaires coté JAVA ont été verifiés
Les nouveaux tests unitaires vont venir dans une autre PR.
Des tests manuels sont effectués sur VitamUI.

## Migration:
Pas de modification DB, pas de nouvelle APP, pas de migration.

## Checklist:
[X] Mon code suit le style de code de ce projet.
[X] J'ai commenté mon code, en particulier dans les classes et lesméthodes difficile à comprendre.
[X] Les tests unitaires nouveaux et existants passent avec succès localement.
[X] Toutes les dépendances ont été mergées en priorité

## Contributeur
Vitam Accessible en Service (VAS)

2021-04-19 14:34 UTC, oussamasic approved these changes

2021-04-21 09:33 UTC, CouzinieAtCines commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchAgenciesInternalService.java
> +            }
Quel est l’intérêt de catch pour logger et rethrow les même exceptions ?

2021-04-21 09:54 UTC, naji-cines reviewed
I agree

2021-04-21 11:18 UTC, CouzinieAtCines requested changes

2021-04-21 11:18 UTC, CouzinieAtCines commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
> +            throw new BadRequestException("Unable to find archive units with pagination", ioe);
Anti-pattern: CATCH LOG RETHROW
On se retrouve avec des fichiers de logs avec des doublons de logs.

Soit on catch et on log
Soit on catch et on rethrow (en encapsulant l'exception d'origine)
On ne log qu'au plus haut level.

2021-04-21 11:18 UTC, CouzinieAtCines commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
>              LOGGER.error("Can not get the archive unit {} ", e);
Anti-pattern: CATCH LOG RETHROW

2021-04-21 11:18 UTC, CouzinieAtCines commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
> +            LOGGER.error("Can't parse criteria as Vitam query" + e.getMessage());
Anti-pattern: CATCH LOG RETHROW

2021-04-21 11:18 UTC, CouzinieAtCines commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
> +            LOGGER.error("The archives units result found is greater than allowed {} ",
Inutile de log ici, vu que l'on throw une exception avec le même message sur la ligne d'après.

2021-04-21 11:18 UTC, CouzinieAtCines commented on docs/swagger/api-external/archive-search-external/index.html
> +<td class="tableblock halign-left valign-middle"><p class="tableblock">Identifiant technique du token gÃ©nÃ©rÃ© par le serveur CAS lors de l&#8217;authentification</p></td>
Quelques problème avec l'encodage des diacritiques ?

2021-04-21 11:18 UTC, CouzinieAtCines commented on docs/swagger/api-external/archive-search-external/index.html
> +<td class="tableblock halign-left valign-middle"><p class="tableblock">Non trouvÃ©e</p></td>
Problème encodage ?

2021-04-21 11:18 UTC, CouzinieAtCines commented on docs/swagger/api-external/archive-search-external/index.html
> +<td class="tableblock halign-left valign-middle"><p class="tableblock">Identifiant technique du token gÃ©nÃ©rÃ© par le serveur CAS lors de l&#8217;authentification</p></td>
Encodage

2021-04-21 11:18 UTC, CouzinieAtCines commented on docs/swagger/api-external/archive-search-external/index.html
> +<td class="tableblock halign-left valign-middle"><p class="tableblock">Non trouvÃ©e</p></td>
Encodage

2021-04-21 11:18 UTC, CouzinieAtCines commented on docs/swagger/api-external/archive-search-external/index.html
> +<td class="tableblock halign-left valign-middle"><p class="tableblock">Identifiant technique du token gÃ©nÃ©rÃ© par le serveur CAS lors de l&#8217;authentification</p></td>
Encodage

2021-04-21 11:18 UTC, CouzinieAtCines commented on docs/swagger/api-external/archive-search-external/index.html
> +<td class="tableblock halign-left valign-middle"><p class="tableblock">L&#8217;utilisateur ne possÃ¨de pas les droits pour effectuer cette opÃ©ration</p></td>
Encodage

2021-04-21 11:18 UTC, CouzinieAtCines commented on docs/swagger/api-external/archive-search-external/index.html
> +<td class="tableblock halign-left valign-middle"><p class="tableblock">Identifiant technique du token gÃ©nÃ©rÃ© par le serveur CAS lors de l&#8217;authentification</p></td>
Encodage

2021-04-21 11:18 UTC, CouzinieAtCines commented on docs/swagger/api-external/archive-search-external/index.html
> +<td class="tableblock halign-left valign-middle"><p class="tableblock">Non trouvÃ©e</p></td>
Encodage

2021-04-21 11:18 UTC, CouzinieAtCines commented on docs/swagger/api-external/archive-search-external/index.html
> +<td class="tableblock halign-left valign-middle"><p class="tableblock">Identifiant technique du token gÃ©nÃ©rÃ© par le serveur CAS lors de l&#8217;authentification</p></td>
Encodage

2021-04-21 11:18 UTC, CouzinieAtCines commented on docs/swagger/api-external/archive-search-external/index.html
> +<td class="tableblock halign-left valign-middle"><p class="tableblock">L&#8217;utilisateur ne possÃ¨de pas les droits pour effectuer cette opÃ©ration</p></td>
Encodage

2021-04-21 12:32 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
> +            throw new BadRequestException("Unable to find archive units with pagination", ioe);
Done

2021-04-21 12:33 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
>              LOGGER.error("Can not get the archive unit {} ", e);
Done

2021-04-21 12:33 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
> +            LOGGER.error("The archives units result found is greater than allowed {} ",
Done

2021-04-21 12:33 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
> +            LOGGER.error("Can't parse criteria as Vitam query" + e.getMessage());
Done

2021-04-21 12:34 UTC, bbenaissa commented on docs/swagger/api-external/archive-search-external/index.html
> +<td class="tableblock halign-left valign-middle"><p class="tableblock">Identifiant technique du token gÃ©nÃ©rÃ© par le serveur CAS lors de l&#8217;authentification</p></td>
Code généré automatiquement avec Swagger, à vérifier la config

2021-04-21 12:59 UTC, CouzinieAtCines commented on docs/swagger/api-external/archive-search-external/index.html
> +<td class="tableblock halign-left valign-middle"><p class="tableblock">Identifiant technique du token gÃ©nÃ©rÃ© par le serveur CAS lors de l&#8217;authentification</p></td>
Ok, vous comptez push ici ou ca sera sur une autre MR ?

2021-04-21 13:05 UTC, bbenaissa commented on docs/swagger/api-external/archive-search-external/index.html
> +<td class="tableblock halign-left valign-middle"><p class="tableblock">Identifiant technique du token gÃ©nÃ©rÃ© par le serveur CAS lors de l&#8217;authentification</p></td>
ça sera sur une autre PR

2021-04-21 13:15 UTC, CouzinieAtCines approved these changes

2021-04-21 13:40 UTC, merged