May add the ability to renew a previously created platform.. or not !
ProgrammeVitam/vitam-ui pull request #30
Opened 2020-04-29 15:00 UTC by croftophile

2020-05-01 10:20 UTC, benemart requested changes
Dans la collection applications (base iam), il faut inclure la créations des applications dans le bloc renew_platform pour éviter qu'elles soient dupliquées (_id random). J'ai eu le cas lors de mon déploiement

2020-05-01 10:20 UTC, benemart commented on deployment/roles/init_bdd/templates/iam/03_application_ref.js.j2
>  db.applications.insert({
Il faut que le bloc de création des applications soit aussi dans le renew, sinon les apps sont recrées avec un _id différent et apparaissent en double dans le portail

2020-05-04 07:23 UTC, benemart approved these changes

2020-05-07 09:52 UTC, TDevillechabrolle approved these changes

2020-05-07 09:53 UTC, merged