[VAS] item 7991 : Add Logbook Management Operation application
ProgrammeVitam/vitam-ui pull request #300
Opened 2021-05-21 18:54 UTC by oussamasic

## Description
Cette US à pour objectif la création d'une nouvelle application **Logbook Operations Management** et aussi l'affichage de la page d'accueil de l'APP "Gestion des opérations" avec :
- La visualisation du tableau de suivi des opérations en cours ou en pause.
- La possibilité de pouvoir filtrer par facette.
- 
## Type de changement:
* Ansiblerie
* Nouveau Code 
* Refactorisation de code
* 
## Documentation:

## Tests:
- Des tests unitaires en JAVA sont ajoutés.
- Des tests unitaires coté Angular sont ajoutés.
- Des tests fonctionnels sont effectués pour vérifier le fonctionnement de cette application.

## Migration:
- Des modifications au niveau de la DB, 
- Une nouvelle Application ajoutée, 
- pas de migration.

## Checklist:
[X] Mon code suit le style de code de ce projet.
[X] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.
[X] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.
[X] Les tests unitaires nouveaux et existants passent avec succès localement.

## Contributeur
Vitam Accessible en Service (VAS)

2021-06-08 12:42 UTC, JulienCouzinie requested changes

2021-06-08 12:42 UTC, JulienCouzinie commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/service/LogbookManagementOperationExternalServiceTest.java
> +        }).doesNotThrowAnyException();
Quel est l’intérêt cet cet assert ?
Le test échouera quoi qu'il arrive si une exception est levée. C'est le comportement par defaut de JUnit.

On peut aussi illustrer le comportement "pas d'exception" avec :
@Test(expected = Test.None.class )

2021-06-08 12:42 UTC, JulienCouzinie commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/LogbookManagementOperationInternalServiceTest.java
> +    }
Tous ces tests vérifient que le mock retourne le bon résultat.
Donc on ne teste rien en fait.

2021-06-08 12:42 UTC, JulienCouzinie commented on ui/ui-referential/src/test/java/fr/gouv/vitamui/referential/service/LogbookManagementOperationServiceTest.java
> +        Assert.assertNotNull(response);
Test du résultat du mock.
Test inutile.

2021-06-10 13:00 UTC, oussamasic commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/service/LogbookManagementOperationExternalServiceTest.java
> +        }).doesNotThrowAnyException();
L'objectif du assert ajouté est d'assurer que le le service en question renvoie bien une réponse de type ProcessDetailDto quand le paramètre de la méthode est bien correcte.

* Oui c'est faisable avec @Test(expected = Test.None.class ), mais c'est plus pratique avec @Test().

2021-06-10 13:14 UTC, oussamasic commented on ui/ui-referential/src/test/java/fr/gouv/vitamui/referential/service/LogbookManagementOperationServiceTest.java
> +        Assert.assertNotNull(response);
2eme test supprimé

2021-06-10 13:16 UTC, JulienCouzinie requested changes

2021-06-10 13:16 UTC, JulienCouzinie commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/service/LogbookManagementOperationExternalServiceTest.java
> +        }).doesNotThrowAnyException();
Si on voulait tester que le service renvoie bien une réponse de type ProcessDetailDto, il aurait fallu utiliser "instanceof".
Ce qui ne servirait à rien de toutes façons vu que le résultat est retourné par le mock et sera toujours un ProcessDetailDto.

Donc ce test inutile ou mal implémenté.

Et il n'y a pas besoin de faire de test pour savoir si une exception a été levée, car c'est le comportement par défaut de JUnit. Si il y a une exception, le test échouera, donc pas besoin du "assertThatCode ... doesNotThrowAnyException"

2021-06-10 13:25 UTC, oussamasic commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/LogbookManagementOperationInternalServiceTest.java
> +    }
On teste la réponse du mock dans des cas différents, c'est pour s'assurer que notre service revoie bien le bon résultat

2021-06-10 13:47 UTC, oussamasic commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/service/LogbookManagementOperationExternalServiceTest.java
> +        }).doesNotThrowAnyException();
C'est ok pour cette partie du test, le Assert est supprimé.
Les Assert non utiles sont supprimés (au niveau des 3 fichiers commentés)

2021-06-17 14:55 UTC, JulienCouzinie requested changes

2021-06-17 14:55 UTC, JulienCouzinie commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/service/LogbookManagementOperationExternalServiceTest.java
> +    }
Ce test n'en est pas un.
Il ne teste rien du tout.

Vous définissez le mock sur logbookManagementOperationInternalRestClient.listOperationsDetails puis vous ne testez pas.

C'est quoi le but ?

2021-06-17 14:55 UTC, JulienCouzinie commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/LogbookManagementOperationInternalServiceTest.java
> +    }
Je l'impression que vous n'avez pas compris le fonctionnement et/ou l'utilité des mock.

Ici vous faites un assertNull sur la fonction listOperationsDetails.
Que peux bien retourner cette fonction ?
Elle retourne le résultat de la fonction listOperationsDetails du service vitamOperationService.
Or vous avez déclaré un mock sur ce service (ligne 71). Mock qui renverra toujours null. 
null qui déclenchera un nullpointerexeption à la ligne 73 de LogbookManagementOperationInternalService.java.

De toutes façons je me demande bien comment ce test peux fonctionner sachant que vous utilisez les fonctions de mock de Easymock et déclarez votre test avec PowerMockRunner. Ces deux là n'ont rien à voir.

Chez moi il provoque une nullpointerexpection sur le mock de vitamOperationService. Je pense que c'est du au fait de déclarer le runner avec PowerMock et déclarer les mocks avec EasyMock. Ou alors, surement du au fait que vous n'avez pas passé le test en mode test avec la fonction replay.


Je pense il serait judicieux de rester sur Mockito comme sur la classe de test LogbookManagementOperationExternalServiceTest.java

De plus, mockito n'oblige pas à passer le test en mode 'test' avec la fonction replay.

2021-06-17 14:55 UTC, JulienCouzinie commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/LogbookManagementOperationInternalServiceTest.java
> +    }
Ce test fail parceque justement le code renvoi une npe.
Ceci à cause de la confusion EasyMock/Powermock.

De plus il n'apporte rien de plus au premier test qui en lui même est inutile.

2021-06-17 14:55 UTC, JulienCouzinie commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/LogbookManagementOperationInternalServiceTest.java
> +    }
Ce test ici ne fait absolument rien.

Vous définissez le mock avec la methode expect, puis passez en mode test avec la fonction replay.

Et puis rien.


Donc avec Easymock, la procédure c'est :

On défini un Mock, soit avec la méthode mock(), soit avec @mock
On défini ce que l'on veut que le mock renvoie avec expect() when()
On passe en mode de test avec la fonction replay()

puis on execute le code à tester.

2021-06-17 14:55 UTC, JulienCouzinie commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/LogbookManagementOperationInternalServiceTest.java
> +    }
Même remarque que précédemment.
Ce test ne fait rien du tout à part définir le mock.

2021-06-17 14:55 UTC, JulienCouzinie commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/LogbookManagementOperationInternalServiceTest.java
> +}
Encore un test qui vérifie que le mock fonctionne bien.

Vous définissez le retour du mock pour qu'il throw une VitamClientException, puis vous testez avec assertThatCode que le mock throws une VitamClientException

2021-06-22 11:53 UTC, JulienCouzinie requested changes

2021-06-22 11:53 UTC, JulienCouzinie commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/service/LogbookManagementOperationExternalServiceTest.java
> +    }
Je vous conseille de lire des articles sur les tests avec JUnit et Mockito car visiblement vous n'avez pas compris.

Une fois de plus (j'ai l'impression de me répéter mais bon, je suis patient ;) ), vous testez le résultat du mock. Donc vous ne testez rien !

Le mock, ça sert à simuler une partie du code qui ne serait pas fonctionnelle lors de l’exécution d'un test. Il y a plein de raisons qu'un code ne soit pas fonctionnel lors de l’exécution d'un test. La raison principale est que l'architecture n'est généralement pas déployée pour l’exécution des tests. Il va manquer les BDD, API externe, connexion au net, ...
Par exemple, on va faire un mock sur le service d’interrogation d'un base SQL, afin de simuler le résultat une requête SQL.
Ou on va faire un mock sur un client Rest, afin de simuler le résultat d'une requête sur une API.


Donc ici on a:
Vous définissez une variable 'reponse' de type ProcessDetailDto  à la ligne 67.
Vous définissez un mock sur la fonction listOperationsDetails, afin qu'elle renvoie votre variable 'reponse' aux lignes 68-69.
Vous executez la fonction listOperationsDetails et récupérez son résultat ligne 70.
Vous testez que le résultat est différent de nul, égal à la variable 'reponse', puis un test sur les operations lignes 72,73,74

donc vous testez que le résultat du mock que vous avez vous même défini, est bien égal à lui même ...

Votre code revient à faire ça:
`assertEquals(response, response);`


Honnêtement, il n'y a aucun test fonctionnel à réaliser sur ce service, il interroge une API et retourne le résultat sans effectuer de traitement.

Ici, il aurait juste été intéressant de tester que le service ne génère pas d'exception. 
En l'état actuel il n'en génèrera jamais, vu qu'il ne fais rien, mais peut-être qu'un jour quelqu'un va ajouter des contrôles sur le param ProcessQuery, et du coup là on aura des risques de NPE ou autres..


Du coup, pour tester cette fonction, j'aurais écrit juste ça:

`@Test()
    public void getListOperationsDetails_should_return_ok_when_vitamclient_ok()  {
        ProcessDetailDto response = new ProcessDetailDto();
        when(logbookManagementOperationInternalRestClient.listOperationsDetails(any(InternalHttpContext.class), any(ProcessQuery.class)))
            .thenReturn(response);
        logbookManagementOperationExternalService.listOperationsDetails(new ProcessQuery());
    }`


On défini un mock sur le client Rest.
On teste que service logbookManagementOperationExternalService.listOperationsDetails() s'execute sans exception.

2021-06-22 11:53 UTC, JulienCouzinie commented on ui/ui-frontend/projects/referential/src/assets/i18n/en.json
> +    "REFRESH": "Refrech",
```suggestion
    "REFRESH": "Refresh",
```

2021-06-22 11:53 UTC, JulienCouzinie commented on ui/ui-frontend/projects/referential/src/assets/i18n/en.json
> +    "ToolTip_Refresh": "Refrech the list of operations",
```suggestion
    "ToolTip_Refresh": "Refresh the list of operations",
```

2021-06-22 11:53 UTC, JulienCouzinie commented on ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
> +    "SEARCH" : "Rechercher par identdfiant d'opération",
Erreur de typo:

```suggestion
    "SEARCH" : "Rechercher par identifiant d'opération",
```

2021-06-22 11:53 UTC, JulienCouzinie commented on ui/ui-referential/src/test/java/fr/gouv/vitamui/referential/service/LogbookManagementOperationServiceTest.java
> +}
Même commentaire que fait précédemment, vous testez le mock que vous avez vous-même défini.
Test inutile.

2021-06-23 14:42 UTC, JulienCouzinie approved these changes

2021-06-23 16:56 UTC, bbenaissa approved these changes

2021-06-23 17:04 UTC, merged