[VAS] Item 8023 : Profil APP Paramétrages externes
ProgrammeVitam/vitam-ui pull request #315
Opened 2021-06-21 11:44 UTC by nabilm2i

## Description
Cette PR permet d'ajouter le socle d'une nouvelle application permettant de la création des profils de paramétrage externes et leur association avec les contrats d'accès.

L'application se nomme **Profil APP Paramétrages externes**

## Type de changement:
* Nouveau Code Front Back
* Scripts de déploiemnt

## Tests:
- Des tests unitaires coté Angular sont ajoutés.
- Des test unitaires et IT backend
- Scénarios Gherkin.
- Des tests fonctionnels sont effectués pour vérifier le fonctionnement de cette application.

## Migration:
- pas de migration.

## Checklist:
[X] Mon code suit le style de code de ce projet.
[X] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.
[X] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.
[X] Les tests unitaires nouveaux et existants passent avec succès localement.

## Contributeur
Vitam Accessible en Service (VAS)

2021-06-23 15:10 UTC, youcefxelians reviewed
Bonjour,
En plus de mes remarques, il faudra gérer les traductions avec ngx-translate.
Merci :)

2021-06-23 15:10 UTC, youcefxelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/AccessContractExternalController.java
> +@Api(tags = "accesscontracts", value = "Access contact", description = "Acess contract Management")
```suggestion
@Api(tags = "accesscontracts", value = "Access contact", description = "Access contract Management")
```

2021-06-23 15:10 UTC, youcefxelians commented on commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/accesscontract/AccessContractInternalRestClient.java
> +     * Find unit life cycle by id.
la javadoc correspond-t-elle à la méthode ?

2021-06-23 15:10 UTC, youcefxelians commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/common/domain/SequencesConstants.java
> +    public static final String EXTPARAM_IDENTIFIER = "externalParamIdentifier";
EXTERNAL_PARAM_IDENTIFIER, c'est plus lisible.

2021-06-23 15:10 UTC, youcefxelians commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/common/utils/ProfileSequenceGenerator.java
> +public class ProfileSequenceGenerator {
pourquoi vous avez crée un nouveau générateur ? pourquoi ne pas avoir utilisé le SequenceGeneratorService ?

2021-06-23 15:10 UTC, youcefxelians commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/common/builder/ProfileDtoBuilder.java
> +public enum ProfileDtoBuilder {
je ne vois pas pourquoi on utilise des enums pour faire des mappers. ce n'est pas le rôle des enums à ma connaissance.

2021-06-23 15:10 UTC, youcefxelians commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/AccessContractInternalController.java
> +//        LOGGER.debug("get all accessContract criteria={}", criteria);
décommenter ou supprimer svp.

2021-06-23 15:10 UTC, youcefxelians commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/ExternalParamProfileInternalController.java
> +        String criteriaValue = criteria.orElse(null);
Je ne vois pas l’intérêt d'utiliser des Optionals => dans tous les cas les arguments sans Optional, soit ils contiennent des valeurs soit Ils sont null et cela correspond au traitement que vous avez ajouté.
Le mieux, c'est de supprimer les Optionals.

2021-06-23 15:10 UTC, youcefxelians commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/ExternalParamProfileInternalController.java
> +@Setter
pas nécessaire ?

2021-06-23 15:10 UTC, youcefxelians commented on ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/service/ExternalParamProfileService.java
> +    public ExternalParamProfileDto create(final ExternalHttpContext c, final ExternalParamProfileDto dto) {
le mieux, c'est de remplacer c par context comme les autres

2021-06-23 15:10 UTC, youcefxelians commented on ui/ui-commons/src/test/java/fr/gouv/vitamui/ui/commons/service/AccessContractServiceTest.java
> +        assertEquals(all.size(), 5);
Il y a moyen d'ajouter des assertions sur le contenu ?

2021-06-23 15:10 UTC, youcefxelians commented on ui/ui-commons/src/test/java/fr/gouv/vitamui/ui/commons/service/ExternalParamProfileServiceTest.java
> +@RunWith(SpringRunner.class)
Mockito est suffisant si tu n'utilises pas Spring. ça évite de recharger le contexte Spring et c'est plus rapide.

2021-06-23 15:10 UTC, youcefxelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/ExternalParamProfileExternalController.java
> +@Setter
nécessaire ?

2021-06-23 15:10 UTC, youcefxelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/ExternalParamProfileExternalController.java
> +        return null;
ajouter éventuellement une exception pour dire que la méthode n'est pas implémentée ?

2021-06-23 15:10 UTC, youcefxelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/service/ExternalParamProfileExternalService.java
> +@Setter
nécessaire ?

2021-06-23 15:10 UTC, youcefxelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/service/ExternalParamProfileExternalService.java
> +    private void checkLogbookRight(final String id) {
cette méthode existe déjà dans ProfileExternalService par exemple. il est possible de la réutiliser ?

2021-06-23 15:10 UTC, youcefxelians commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/common/builder/ExternalParamDtoBuilder.java
> +public enum ExternalParamDtoBuilder {
Même remarque sur les enums

2021-06-23 15:10 UTC, youcefxelians commented on ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/rest/AccessContractController.java
> +@Produces("application/json")
ce n'est pas le fonctionnement par défaut ? tu pourrais utiliser les enums proposées par Spring
@RequestMapping(
            value = "${ui-prefix}/accesscontracts",
            consumes = MediaType.APPLICATION_JSON_VALUE,
            produces = MediaType.APPLICATION_JSON_VALUE
    )

2021-06-23 15:10 UTC, youcefxelians commented on ui/ui-frontend-common/src/app/modules/components/header/select-language/select-language.component.ts
> +        case ApplicationId.EXTERNAL_PARAM_PROFILE_APP_REF :
pourquoi ne pas conserver la même monoculture que l'existant ? _REF ?

2021-06-23 15:10 UTC, youcefxelians commented on ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-detail/information-tab/information-tab.component.spec.ts
> +  describe('DOM', () => {
à compléter ou supprimer svp

2021-06-23 15:10 UTC, youcefxelians commented on ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-detail/information-tab/information-tab.component.spec.ts
> +  describe('Component', () => {
pareil

2021-06-23 15:10 UTC, youcefxelians commented on ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile.validators.spec.ts
> +    /*const profileValidators = new ExternalParamProfileValidators(
à supprimer stp

2021-06-23 15:10 UTC, youcefxelians commented on ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile.validators.spec.ts
> +    /*const profileValidators = new ExternalParamProfileValidators(
à supprimer stp

2021-06-23 15:10 UTC, youcefxelians commented on ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile.validators.spec.ts
> +    // const profileValidators = new ExternalParamProfileValidators();
pareil

2021-06-23 15:10 UTC, youcefxelians commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/common/builder/ExternalParamProfileDtoBuilder.java
> +public enum ExternalParamProfileDtoBuilder {
je ne vois pas pourquoi on utilise des enums pour faire des mappers. ce n'est pas le rôle des enums à ma connaissance. je me trompe ?

2021-06-23 15:10 UTC, youcefxelians commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalparamprofile/converter/ExternalParamProfileConverter.java
> +    public static final String DATE_TIME = "DateTime";
y a t il une logique majuscule vs minuscule dans le contenu des constantes ?

2021-06-23 15:10 UTC, youcefxelians commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalparamprofile/converter/ExternalParamProfileConverter.java
> +@Setter
nécessaire ?

2021-06-23 15:10 UTC, youcefxelians commented on deployment/scripts/mongod/2.0.0/06_create_search_criteria_history.js.j2
> +db = db.getSiblingDB('{{ mongodb.archivesearch.db }}')
le nom de la bd n'est pas figé comme les autres ?

2021-06-23 15:10 UTC, youcefxelians commented on deployment/scripts/mongod/2.0.0/10_update_external_param_profile.js
> +    _id: "5c79022e7884583d1ebb6e5d0bc0121822684250a3fd2996fd93c04634363363",
cette id est auto généré ? il est le même pour tout le monde ? la communauté ?

2021-06-23 15:10 UTC, youcefxelians commented on ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-create/external-param-profile-create.component.html
> +<div class="header">
il faudra gérer la traduction avec ngx-translate dans tous le fichiers html

2021-06-23 15:39 UTC, depysk commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/common/builder/ProfileDtoBuilder.java
> +public enum ProfileDtoBuilder {
Il s'agit d'une manière de déclarer un singleton en java de manière thread safe. C'est aussi souvent utiliser pour construire des mappers (confère implémentation du framework MapStruct)

2021-06-23 16:08 UTC, depysk commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/common/utils/ProfileSequenceGenerator.java
> +public class ProfileSequenceGenerator {
Bien vu, effectivement on avait eu besoin à un moment donné de mutualiser la génération de la séquence dans une classe afin de la réutiliser à deux endroits différents mais finalement ce fut pas le cas et on a oublié de faire le rollback. Merci

2021-06-23 16:09 UTC, depysk commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/common/domain/SequencesConstants.java
> +    public static final String EXTPARAM_IDENTIFIER = "externalParamIdentifier";
Finalement constante supprimée car inutilisée. Merci

2021-06-23 16:13 UTC, depysk commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalparamprofile/converter/ExternalParamProfileConverter.java
> +    public static final String DATE_TIME = "DateTime";
Erreur de typos, c'est corrigé (tous mis en camelCase)

2021-06-23 16:14 UTC, depysk commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalparamprofile/converter/ExternalParamProfileConverter.java
> +@Setter
Un malheureux copie/coller. Merci

2021-06-23 16:25 UTC, depysk commented on deployment/scripts/mongod/2.0.0/06_create_search_criteria_history.js.j2
> +db = db.getSiblingDB('{{ mongodb.archivesearch.db }}')
Rien avoir avec cette US mais il s'agissait de faire du boyscout par rapport aux autres fichiers jinja (.j2). La valeur de cette variable est récupérée depuis le fichier deployment/environments/all/vault_mongodb.yml lors du déploiement de vitam-ui

2021-06-23 16:26 UTC, depysk commented on deployment/scripts/mongod/2.0.0/10_update_external_param_profile.js
> +    _id: "5c79022e7884583d1ebb6e5d0bc0121822684250a3fd2996fd93c04634363363",
Non, malheureusement il s'agit d'un id utilisé par tous pour mettre à jour le groupe de profil admin

2021-06-24 09:14 UTC, youcefxelians commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/common/builder/ProfileDtoBuilder.java
> +public enum ProfileDtoBuilder {
ce qui me gène c'est plus l'utilisation des Enums (je me dis ce n'est pas le rôle des enums). si tu as un lien à me donner pour la génération de mapper par Enum avec MapStruct, je suis preneur :)
MapStruct de mémoire utilise des interfaces et derrière une implémentation est générée.
Les mappers devraient être threadsafe car ils sont sans état.

2021-06-24 14:29 UTC, depysk commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/common/builder/ProfileDtoBuilder.java
> +public enum ProfileDtoBuilder {
Autant pour moi Youcef, effectivement tu as raison concernant MapStruct. Pour l'utilisation de l'Enum en tant que Singleton, celà provient du livre de Joshua Bloch dans son livre "Effective Java 2nd edition" dont tu peux trouver un extrait via ce lien (https://www.informit.com/articles/article.aspx?p=1216151&seqNum=3).

2021-06-25 13:31 UTC, depysk commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/ExternalParamProfileInternalController.java
> +        String criteriaValue = criteria.orElse(null);
Le fait est que le service appelant (AbstractPaginateService<T extends IdDto> extends AbstractCrudService<T> ) nous oblige à définir un API avec des optionals. Un chantier doit être mener sur tous les APIs afin de corriger celà. Pour éviter de reproduire ce schéma plus loin j'ai extrait les valeurs des optionals à ce niveau

2021-06-25 14:20 UTC, youcefxelians approved these changes

2021-06-25 14:49 UTC, oussamasic requested changes

2021-06-25 14:49 UTC, oussamasic commented on ui/ui-frontend/projects/identity/src/app/shared/vitamui-snack-bar/vitamui-snack-bar.component.html
> +    </ng-container>
Il manque la partie traduction

2021-06-25 14:49 UTC, oussamasic commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/common/builder/ExternalParamDtoBuilder.java
> +    }
A supprimer

2021-06-25 14:49 UTC, oussamasic commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/common/builder/ExternalParamProfileDtoBuilder.java
> +    }
A supprimer

2021-06-25 14:49 UTC, oussamasic commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/common/builder/ProfileDtoBuilder.java
> +    }
A supprimer

2021-06-25 14:49 UTC, oussamasic commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalparamprofile/dao/CriteriaQueryHelper.java
> +    }
A enlever

2021-06-25 15:44 UTC, oussamasic approved these changes

2021-06-28 15:00 UTC, merged