[VAS] Item-8359 : Ajout du paramètre du calcul des héritages de règle…
ProgrammeVitam/vitam-ui pull request #354
Opened 2021-07-08 15:26 UTC by depysk

## Description
Evolution du contrat d'entrée - Ajout du paramètre du calcul des héritages de règles et de l’indexation des échéances

## Checklist:
[x] Mon code suit le style de code de ce projet.
[x] Les tests unitaires nouveaux et existants passent avec succès localement.

## Contributeur
VAS

2021-07-09 10:11 UTC, bbenaissa requested changes

2021-07-09 10:11 UTC, bbenaissa commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractInternalService.java
> +            RequestResponse<?> requestResponse = ingestContractService.patchIngestContract(vitamContext, id, query);
Je n'ai pas compris le fonctionnement de cette partie.
En cas d'exception, on patch le contract? il y a une raison pour ça

2021-07-09 12:49 UTC, oussamasic approved these changes

2021-07-12 08:05 UTC, bbenaissa approved these changes

2021-07-12 08:10 UTC, merged