[XEL] Update dev spring config
ProgrammeVitam/vitam-ui pull request #359
Opened 2021-07-09 16:06 UTC by pyXelians

## Description

Cette PR contient des modifications ayant pour but de faciliter les développements et l'intégration de spring avec les IDE des devs. 

Elle permet de pouvoir utiliser nativement les fonctionnalités de débbugage de l'IDE ainsi que le lancement des modules sur les postes des devs. 

Note : il faudra potentiellement mettre à jours les runner des postes des devs s'ils en ont. 

Aucun impact sur l'existant.

## Type de changement
-  Technique : Amélioration du développement

## Checklist

 [X ] Mon code suit le style de code de ce projet.
 [X] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.
 [X] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.
 [X] Les tests unitaires nouveaux et existants passent avec succès localement.
 [X] Toutes les dépendances ont été mergées en priorité

## Contributeur

Xelians

2021-07-12 11:36 UTC, eric969 approved these changes

2021-07-20 07:35 UTC, bbenaissa requested changes

2021-07-20 07:35 UTC, bbenaissa commented on api/api-iam/iam-internal/src/main/resources/application-dev.yml
> +provisioning-client:
la configuration de la partie provisioning est intégrée dans cette PR

2021-08-10 11:32 UTC, CouzinieAtCines approved these changes

2021-08-17 09:04 UTC, pyXelians commented on api/api-iam/iam-internal/src/main/resources/application-dev.yml
> +provisioning-client:
Les configs existe déjà dans la branche develop mais git le marque comme étant new pour  je ne sais quel raison. Peut être a cause du renommage

2021-10-07 15:48 UTC, merged