Cea app referential pr1
ProgrammeVitam/vitam-ui pull request #36
Opened 2020-06-04 14:25 UTC by benemart

[Doc PR1.docx](https://github.com/ProgrammeVitam/vitam-ui/files/4730645/Doc.PR1.docx)

2020-06-17 08:34 UTC, nabilm2i approved these changes

2020-06-24 16:17 UTC, mamakh requested changes
Corriger les InternalServerException("", e) sur l'ensemble des services
referential-commons et les notes à revoir
Frontend : je n'ai pas compris le vitamui-library et la redéfinition des composants 
Frontend faire passer un run check et corriger les erreurs de lint

2020-06-24 16:17 UTC, mamakh commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/AccessionRegisterService.java
> +/**
Le commentaire vaut pour l'ensemble du package service.
Pourquoi avoir défini les services ici et pas dans referential-internal ou dans commons-vitam ? 
et certaines classes sont en doublons par rapport à commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/administration

2020-06-24 16:17 UTC, mamakh commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dto/AccessContractDto.java
> +/**
Le commentaire vaut pour l'ensemble du package dto.
Pourquoi avoir défini les services ici et pas dans commons-vitam ? 
et certaines classes sont en doublons par rapport à commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto
Il faudrait basculer les classes manquantes là dedans

2020-06-24 16:17 UTC, mamakh commented on api/api-referential/referential-internal-client/src/main/java/fr/gouv/vitamui/referential/internal/client/ReferentialInternalWebClientFactory.java
> +/**
classe non utilisée à supprimer

2020-06-24 16:17 UTC, mamakh commented on api/api-referential/referential-internal-client/src/main/java/fr/gouv/vitamui/referential/internal/client/IamStatusInternalRestClient.java
> +/**
classe non utilisée à supprimer

2020-06-24 16:17 UTC, mamakh commented on api/api-referential/referential-external-client/src/main/java/fr/gouv/vitamui/referential/external/client/ReferentialExternalWebClientFactory.java
> +/**
Classe non utilisée à supprimer

2020-06-24 16:17 UTC, mamakh commented on tools/swagger/docs/api-external/referential-external/swagger.json
> +{
Ne pas laissez le fichier brut.
Ajouter de la documentation, mettre des noms d'API plus parlantes à l'image d'iam

2020-06-24 16:17 UTC, mamakh commented on tools/swagger/docs/api-internal/referential-internal/swagger.json
> +{
Ne pas laissez le fichier brut.
Ajouter de la documentation, mettre des noms d'API plus parlantes à l'image d'iam

2020-06-24 16:17 UTC, mamakh commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractInternalService.java
> +            throw new InternalServerException("", e);
à corriger

2020-06-24 16:17 UTC, mamakh commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractInternalService.java
> +            throw new InternalServerException("", e);
à corriger

2020-06-24 16:17 UTC, mamakh commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractInternalService.java
> +            throw new InternalServerException("", e);
à corriger

2020-06-24 16:17 UTC, mamakh commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractInternalService.java
> +            throw new InternalServerException("", ioe);
à corriger

2020-06-24 16:17 UTC, mamakh commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/agency/AgencyInternalService.java
> +    public AgencyDto getOne(VitamContext vitamContext, String identifier) {
Les fonctions et leurs structures se répètent pas mal de fois.
Je pense qu'il faudrait une classe de base pour les différents services

2020-06-24 16:17 UTC, mamakh commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/agency/AgencyInternalService.java
> +            throw new InternalServerException("Unable to create agency");
Exception non renvoyée

2020-06-24 16:17 UTC, mamakh commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/agency/AgencyInternalService.java
> +            throw new InternalServerException("Unable to find history by id = {}", id);
Renvoyer l'exception

2020-06-24 16:17 UTC, mamakh commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/fileformat/FileFormatInternalService.java
> +            throw new InternalServerException("Unable to create fileFormat");
Renvoyer l'exception

2020-06-24 16:17 UTC, mamakh commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ontology/OntologyInternalService.java
> +            throw new InternalServerException("Unable to create ontology");
Renvoyer l'exception

2020-06-24 16:17 UTC, mamakh commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ontology/OntologyInternalService.java
> +            throw new InternalServerException("Unable to delete ontology");
Renvoyer l'exception

2020-06-24 16:17 UTC, mamakh commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ontology/OntologyInternalService.java
> +                    throw new InternalServerException("Unable to copy properties to DTO");
Renvoyer l'exception

2020-06-24 16:17 UTC, mamakh commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/probativevalue/ProbativeValueInternalService.java
> +		try (InputStream fopconfigfile = getClass().getClassLoader().getResourceAsStream("fop/fop-config.xml");
A mettre en constantes globales : fop/fop-config.xml, fop/probativevaluereport.xsl

2020-06-24 16:17 UTC, mamakh commented on api/api-iam/iam-commons/src/main/java/fr/gouv/vitamui/iam/common/dto/AccessContractDto.java
> +/**
classe non utilisée, à supprimer

2020-06-24 16:17 UTC, mamakh commented on api/api-iam/iam-internal/src/main/config/customer-init.yml
> +    - name: Security Profiles Profile
Nom du profil en français plutôt ?
Ajouter une description

2020-06-24 16:17 UTC, mamakh commented on api/api-iam/iam-commons/src/main/java/fr/gouv/vitamui/iam/common/dto/AccessContractCreationFormData.java
> +/**
classe non utilisée, à supprimer

2020-06-24 16:17 UTC, mamakh commented on api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/SwaggerJsonFileGenerationTest.java
> -package fr.gouv.vitamui.iam.internal.server;
Pourquoi cette classe a été supprimée ?

2020-06-24 16:17 UTC, mamakh commented on cas/cas-server/src/main/config/cas-server-application-dev.yml
>      key-password: jkspasswd
valeur à remettre

2020-06-24 16:17 UTC, mamakh commented on cas/cas-server/src/main/config/cas-server-application-dev.yml
> +  host: dev-cas.vitamui.com
pareil

2020-06-24 16:17 UTC, mamakh commented on cas/cas-server/src/main/config/cas-server-application-dev.yml
> +cas.server.prefix: https://dev-cas.vitamui.com:8080/cas
pareil

2020-06-24 16:17 UTC, mamakh commented on cas/cas-server/src/main/config/cas-server-application-dev.yml
> +vitamui.portal.url: https://dev-portal.vitamui.com:4200/
pareil

2020-06-24 16:17 UTC, mamakh commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
> +    public static final String SERVICE_AUDITS = "AUDITS";
Ajouter une séparation visuelle comme pour opérations

2020-06-24 16:17 UTC, mamakh commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
> +    public static final String SERVICE_PROBATIVE_VALUE = "PROBATIVE_VALUE";
pareil, ajouter une séparation visuelle

2020-06-24 16:17 UTC, mamakh commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractInternalService.java
> +        	LOGGER.warn(e.getMessage());
un peu problématique ça, pour quoi ?

2020-06-24 16:17 UTC, mamakh commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/administration/AccessContractService.java
> +            LOGGER.error("BAIS: {}", byteArrayInputStream.toString());
à supprimer

2020-06-24 16:17 UTC, mamakh commented on ui/ui-frontend/projects/vitamui-library/src/lib/components/application-select-content/application-select-content.component.html
> +<div class="app-container" [class.modal-container]="isModalMenu">
pourquoi avoir redéfini le composant ?

2020-06-24 16:17 UTC, mamakh commented on ui/ui-frontend/projects/vitamui-library/src/lib/components/vitamui-menu-tile/vitamui-menu-tile.component.html
> +<a [href]="url" *ngIf="!sameApp" (click)="appSelected()">
pourquoi avoir redéfini le composant ?

2020-06-24 16:28 UTC, gansheer commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/probativevalue/ProbativeValueInternalService.java
> +		try (InputStream fopconfigfile = getClass().getClassLoader().getResourceAsStream("fop/fop-config.xml");
Ce code est supprimé en prochaine PR, j'ai viré fop pour réutiliser le code des utils commons sur les PDF

2020-06-25 08:00 UTC, gansheer commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
> +    public static final String SERVICE_AUDITS = "AUDITS";
En fait ça fait partie des operations

2020-06-25 08:00 UTC, gansheer commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
> +    public static final String SERVICE_PROBATIVE_VALUE = "PROBATIVE_VALUE";
Idem fait ça fait partie des operations

2020-06-25 08:06 UTC, gansheer commented on api/api-referential/referential-internal-client/src/main/java/fr/gouv/vitamui/referential/internal/client/IamStatusInternalRestClient.java
> +/**
Done

2020-06-25 08:06 UTC, gansheer commented on api/api-referential/referential-external-client/src/main/java/fr/gouv/vitamui/referential/external/client/ReferentialExternalWebClientFactory.java
> +/**
Done

2020-06-25 08:07 UTC, gansheer commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/administration/AccessContractService.java
> +            LOGGER.error("BAIS: {}", byteArrayInputStream.toString());
Done

2020-06-25 08:07 UTC, gansheer commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractInternalService.java
> +            throw new InternalServerException("", e);
Done

2020-06-25 08:07 UTC, gansheer commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractInternalService.java
> +            throw new InternalServerException("", e);
Done

2020-06-25 08:07 UTC, gansheer commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractInternalService.java
> +            throw new InternalServerException("", e);
Done

2020-06-25 08:07 UTC, gansheer commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractInternalService.java
> +            throw new InternalServerException("", ioe);
Done

2020-06-25 08:08 UTC, gansheer commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/agency/AgencyInternalService.java
> +            throw new InternalServerException("Unable to create agency");
Done

2020-06-25 08:08 UTC, gansheer commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/fileformat/FileFormatInternalService.java
> +            throw new InternalServerException("Unable to create fileFormat");
Done

2020-06-25 08:08 UTC, gansheer commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ontology/OntologyInternalService.java
> +            throw new InternalServerException("Unable to create ontology");
Done

2020-06-25 08:08 UTC, gansheer commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ontology/OntologyInternalService.java
> +            throw new InternalServerException("Unable to delete ontology");
Done

2020-06-25 08:08 UTC, gansheer commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ontology/OntologyInternalService.java
> +                    throw new InternalServerException("Unable to copy properties to DTO");
Done

2020-06-25 08:09 UTC, gansheer commented on api/api-iam/iam-commons/src/main/java/fr/gouv/vitamui/iam/common/dto/AccessContractDto.java
> +/**
Done

2020-06-25 08:09 UTC, gansheer commented on api/api-iam/iam-commons/src/main/java/fr/gouv/vitamui/iam/common/dto/AccessContractCreationFormData.java
> +/**
Done

2020-06-25 08:09 UTC, gansheer commented on api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/SwaggerJsonFileGenerationTest.java
> -package fr.gouv.vitamui.iam.internal.server;
Boulette, c'est remis

2020-06-25 08:10 UTC, gansheer commented on api/api-referential/referential-internal-client/src/main/java/fr/gouv/vitamui/referential/internal/client/ReferentialInternalWebClientFactory.java
> +/**
Done

2020-06-25 08:10 UTC, gansheer commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/agency/AgencyInternalService.java
> +            throw new InternalServerException("Unable to find history by id = {}", id);
Done

2020-06-25 14:04 UTC, gansheer commented on cas/cas-server/src/main/config/cas-server-application-dev.yml
> +  host: dev-cas.vitamui.com
Done

2020-06-25 14:04 UTC, gansheer commented on cas/cas-server/src/main/config/cas-server-application-dev.yml
> +cas.server.prefix: https://dev-cas.vitamui.com:8080/cas
Done

2020-06-25 14:05 UTC, gansheer commented on tools/swagger/docs/api-external/referential-external/swagger.json
> +{
La doc d'API n'est pas finalisée, une autre PR sera faite pour celle-ci

2020-06-25 14:05 UTC, gansheer commented on tools/swagger/docs/api-internal/referential-internal/swagger.json
> +{
La doc d'API n'est pas finalisée, une autre PR sera faite pour celle-ci

2020-06-25 14:06 UTC, gansheer commented on cas/cas-server/src/main/config/cas-server-application-dev.yml
>      key-password: jkspasswd
De quelle valeur parles-tu ?

2020-06-25 14:10 UTC, mamakh commented on cas/cas-server/src/main/config/cas-server-application-dev.yml
>      key-password: jkspasswd
je ne le vois plus, une erreur sans doute, je pensais sûrement aux urls

2020-06-25 16:43 UTC, gansheer commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/agency/AgencyInternalService.java
> +    public AgencyDto getOne(VitamContext vitamContext, String identifier) {
A discuter avec la gestion des commons

2020-06-25 16:48 UTC, gansheer commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractInternalService.java
> +        	LOGGER.warn(e.getMessage());
Done

2020-06-25 16:52 UTC, gansheer commented on cas/cas-server/src/main/config/cas-server-application-dev.yml
> +vitamui.portal.url: https://dev-portal.vitamui.com:4200/
Done

2020-06-25 16:55 UTC, gansheer commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
> +    public static final String SERVICE_PROBATIVE_VALUE = "PROBATIVE_VALUE";
Done quand même

2020-06-25 16:56 UTC, gansheer commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
> +    public static final String SERVICE_AUDITS = "AUDITS";
Done

2020-06-25 17:35 UTC, gansheer commented on api/api-iam/iam-internal/src/main/config/customer-init.yml
> +    - name: Security Profiles Profile
Done

2020-06-30 15:43 UTC, gansheer commented
@mamakh 
Les fixes sont finis de mon côté :
> Corriger les InternalServerException("", e) sur l'ensemble des services
C'est fait
> referential-commons et les notes à revoir
> Frontend : je n'ai pas compris le vitamui-library et la redéfinition des composants
Une discussion est lancée en parallèle sur ces deux sujets
> Frontend faire passer un run check et corriger les erreurs de lint
c'est fait

Des PR sont prévues juste après merge avec :
* les TU
* la doc API à jour
* des bugfix
* le remplacement du PDF du résultat d'audit de valeurs probante

Dis-moi s'il reste des choses à voir.

2020-07-02 16:10 UTC, mamakh commented on api/api-iam/iam-internal/src/main/config/customer-init.yml
> +    - name: Profile pour la gestion des profiles de sécurité
Profil :)

2020-07-02 16:10 UTC, mamakh commented on api/api-iam/iam-internal/src/main/config/customer-init.yml
> +    - name: Profile pour la gestion des formats de fichiers
Pareil

2020-07-02 16:10 UTC, mamakh commented on api/api-iam/iam-internal/src/main/config/customer-init.yml
> +    - name: Profile pour la gestion des ontologies
Pareil

2020-07-02 16:10 UTC, mamakh commented on api/api-iam/iam-internal/src/main/config/customer-init.yml
> +    - name: Profile pour la gestion des contrats des contextes
Pareil

2020-07-02 16:10 UTC, mamakh commented on api/api-iam/iam-internal/src/main/config/customer-init.yml
> +    - name: Profile pour la gestion des contrats d'accès
Pareil

2020-07-02 16:10 UTC, mamakh commented on api/api-iam/iam-internal/src/main/config/customer-init.yml
> +    - name: Profile pour la gestion des contrats d'entrée
Pareil

2020-07-02 16:10 UTC, mamakh commented on api/api-iam/iam-internal/src/main/config/customer-init.yml
> +    - name: Profile pour les services agents
Pareil

2020-07-02 16:10 UTC, mamakh commented on tools/docker/mongo/database_scripts/iam/1.0.0/01_iam_ref.js.j2
> +db.tenants.insert({
je suis passé à côté de ça mais il faut déplacer les modifications sur de nouveaux scripts pour pouvoir gérer la montée de version

2020-07-02 16:10 UTC, mamakh commented on tools/docker/mongo/database_scripts/iam/1.0.0/01_iam_ref.js.j2
> +db.tenants.insert({
ça peut venir sur une 2e PR

2020-07-02 16:10 UTC, mamakh commented on tools/docker/mongo/database_scripts/iam/1.0.0/02_security_ref.js
> +        "ROLE_GET_ONTOLOGIES", "ROLE_CREATE_ONTOLOGIES", "ROLE_DELETE_ONTOLOGIES",
je ne vois pas pourquoi les rôles sont dans ui-identity

2020-07-02 16:10 UTC, mamakh commented on tools/docker/mongo/database_scripts/iam/1.0.0/02_security_ref.js
> +use security;
Le fichier existe déjà, à renommer avec referential dans le nom et ne mettre que l'ajout du context pour le referential

2020-07-02 16:10 UTC, mamakh commented on tools/docker/mongo/database_scripts/iam/1.0.0/03_application_ref.js.j2
> +// -------- VITAM ADMINISTRATION -----
à déplacer sur un nouveau script pour gérer la montée de version

2020-07-02 16:10 UTC, mamakh commented on tools/docker/mongo/database_scripts/iam/1.0.0/101_iam_system_demo.js
> +		"5c7927537884583d1ebb6e769fcbc58f86f148a3ba96a58759b4befcdadb171c",
à déplacer sur un nouveau script

2020-07-02 16:10 UTC, mamakh commented on tools/docker/mongo/database_scripts/iam/1.0.0/cas_services_ref.js.j2
> +db.services.insert({
pareil à déplacer sur un nouveau script

2020-07-02 16:10 UTC, mamakh commented on tools/docker/mongo/mongo_vars_dev.yml
> +    logoutUrl: "https://ddev.vitamui.com:9002/logout"
à corriger en 'https://dev.vitamui.com:9002/logout'

2020-07-02 16:10 UTC, mamakh commented on tools/docker/mongo/mongo_vars_dev.yml
> +    server_name: dev-portal.vitamui.com:4201
A remettre en dev.vitamui.com

2020-07-02 16:10 UTC, mamakh commented on tools/docker/mongo/mongo_vars_dev.yml
> +    server_name: dev-identity.vitamui.com:4201
pareil ici

2020-07-02 16:10 UTC, mamakh commented on tools/docker/mongo/mongo_vars_dev.yml
> +    server_name: dev-identity.vitamui.com:4201
pareil ici

2020-07-02 16:10 UTC, mamakh commented on tools/docker/mongo/mongo_vars_dev.yml
> +    server_name: dev-referential.vitamui.com:4202
pareil ici

2020-07-02 16:10 UTC, mamakh commented on ui/ui-portal/src/main/config/ui-portal-application-dev.yml
> +  host: dev-portal.vitamui.com
à remette en dev.vitamui.com

2020-07-02 16:10 UTC, mamakh commented on ui/ui-portal/src/main/config/ui-portal-application-dev.yml
> +    portal: "https://dev-portal.vitamui.com:4200"
à remette en dev.vitamui.com

2020-07-02 16:10 UTC, mamakh commented on ui/ui-portal/src/main/config/ui-portal-application-dev.yml
> +  url: "https://dev-portal.vitamui.com:4200"
à remette en dev.vitamui.com

2020-07-02 16:10 UTC, mamakh commented on ui/ui-portal/src/main/config/ui-portal-application-dev.yml
> +  internal-url: https://dev-cas.vitamui.com:8080/cas
à remette en dev.vitamui.com

2020-07-02 16:10 UTC, mamakh commented on ui/ui-identity/src/main/config/ui-identity-application-dev.yml
> +    portal: "https://dev-portal.vitamui.com:4200"
à remette en dev.vitamui.com

2020-07-02 16:10 UTC, mamakh commented on ui/ui-identity/src/main/config/ui-identity-application-dev.yml
> +  host: dev-identity.vitamui.com
à remette en dev.vitamui.com

2020-07-02 16:10 UTC, mamakh commented on ui/ui-identity/src/main/config/ui-identity-application-dev.yml
> +  url: "https://dev-identity.vitamui.com:4201"
à remette en dev.vitamui.com

2020-07-02 16:10 UTC, mamakh commented on ui/ui-identity/src/main/config/ui-identity-application-dev.yml
> +  internal-url: https://dev-cas.vitamui.com:8080/cas
à remette en dev.vitamui.com

2020-07-02 16:10 UTC, mamakh commented on ui/ui-referential/src/main/config/ui-referential-application-dev.yml
> +  internal-url: https://dev-cas.vitamui.com:8080/cas
mettre dev.vitamui.com

2020-07-02 16:34 UTC, Mocteezuma commented on tools/docker/mongo/database_scripts/iam/1.0.0/02_security_ref.js
> +        "ROLE_GET_ONTOLOGIES", "ROLE_CREATE_ONTOLOGIES", "ROLE_DELETE_ONTOLOGIES",
Salut,

C'est juste parce qu'on ne savait pas comment fonctionnait les rôles au début du projet.

Pour la partie deployment, les bon rôles sont associés aux bons "contextes" (APP referentiels pour ui-referentiel et rien changé pour ui-identity).

On poussera la correction (suppression de ces nouveaux roles identity) dans la prochaine PR CEA.

2020-07-02 16:34 UTC, mamakh approved these changes

2020-07-02 16:43 UTC, gansheer commented
Le sujet de la séparation dans des scripts mongos différents nous prenons en compte la demande pour une prochaines PR

2020-07-03 06:56 UTC, merged