Feature/devops/dlab 4154
ProgrammeVitam/vitam-ui pull request #38
Opened 2020-06-08 11:52 UTC by mathieuleguay

# VitamUI - Pull request details (Vitam) DLAB-4154
## Description

La pull request actuelle modifie plusieurs briques du déploiement VitamUI:
* Gestion de la PKI
  * Modification des scripts de PKI afin de pouvoir réaliser des surcharges sur certaines fonctions
  * Séparation entre librairies et les mains afin de faciliter les surcharges en fonction du besoin de la cible
  * Ajout de la PKI de dev
    * Exploitation des scripts de la PKI de déploiement
    * Centralisation des assets SSL
    * Mise à jour des assets SSL sur les modules du projet
* Mutualisation des scripts Mongo entre l'environnement de dev et le déploiment
  * Centralisation des scripts Mongo
  * Ordonnancement des scripts Mongo
  * Exploitation des scripts de déploiement existants pour alimenter l'environnement de dev (docker - local)
  * Modification des scripts de démarrage du docker Mongo de dev (local) afin d'autoriser la surcharge de certaines propriétés (ADDITIONNAL_VITAMUI_CONFIG_FILE)
* Ajout du versioning sur les scripts Mongo
  * Critère de sélection d'un script exécuté: nom du fichier
  * Alimentation de la collection changelog sur les différents commits exécutés sur la base de production
  * Possibilité d'activer/désactiver le versioning
  * Possibilité de mocker l'ajout de données afin de ne populer que le changelog (reprise de données sur existant)
  * Le versioning est activé par défaut. Pour modifier cette configuration, il faut se rendre dans le fichier `environments/group_vars/all/mongodb_vars.yml` et de modifier la clé `mongodb.versioning.enable` 
* Intégration de Mitogen au sein du déploiement (impacts significatifs sur l'init du mongo en local)

## Type de changement:
* Build
* PKI 
* Ansiblerie

## Documentation:
- Alimentation des README.md existant
TODO: A voir pour une documentation plus centralisée.

## Tests:
* Tests PKI:
  * Génération from scratch
  * Mise à jour de la PKI avec ajout de nouveaux certificats clients
* Tests d'installation de la solution from scratch avec différentes configurations :
  * 1 VM
  * 3 VMs

## Migration:
Si le versioning des scripts doit être activée sur une solution déjà opérationnelle, il convient d'exécuter le playbook *mongo.yml* avec le tag *mongo_init* et la variable *mock_insert_data* à `true`

Exemple:
> ansible-playbook mongo.yml --tags "mongo_init" -e "mock_insert_data=true"

Cela aura pour conséquence de ne populer que la collection `changelog` avec tous les scripts courants du projet.

## Checklist:
[X] Mon code suit le style de code de ce projet.
[X] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

2020-06-15 10:26 UTC, pimenta-cines approved these changes

2020-06-15 14:12 UTC, benemart requested changes

2020-06-15 14:12 UTC, benemart commented on cas/cas-server/src/main/config/cas-server-application-recette.yml
>      key-store: file:src/main/config/cas-server.jks
Ca ne devrait pas plutôt être src/main/config/keystore_cas-server.jks ?

2020-06-15 14:12 UTC, benemart commented on deployment/roles/mongo_init/tasks/execute_script.yml
> +    - fail: msg="The file '{{ mongo_file.finalname }}' is not exist"
msg="The file '{{ mongo_file.finalname }}' does not exist"

2020-06-15 14:12 UTC, benemart commented on deployment/roles/mongo_init/tasks/prepare_script.yml
> +- fail: msg="The file '{{ mongo_file.finalname }}' is not exist"
msg="The file '{{ mongo_file.finalname }}' does not exist"

2020-06-15 14:12 UTC, benemart commented on ui/ui-portal/src/main/config/ui-portal-application-recette.yml
>      key-store: src/main/config/ui-portal.jks
Ce ne serait pas plutôt src/main/config/keystore_ui-portal.jks ?

2020-06-15 15:23 UTC, CouzinieAtCines commented on deployment/roles/mongo_init/README.md
> +The role creates an ordered list of scripts will be executed on database.
```suggestion
The role creates an ordered list of scripts which will be executed on database.
```

2020-06-15 15:30 UTC, CouzinieAtCines commented on deployment/roles/mongo_init/tasks/main.yml
> +# We apply regex for included and excludes files in order to compute the eligible scripts.
```suggestion
# We apply regex for included and excluded files in order to compute the eligible scripts.
```

2020-06-15 15:54 UTC, CouzinieAtCines commented on tools/docker/mongo/README.md
> +  Lors du templatage, un premier tri par version est exécutée afin de trier ces dernières par ordre croissante.
```suggestion
  Lors du templatage, un premier tri par version est exécuté afin de trier ces dernières par ordre croissant.
```

2020-06-15 15:55 UTC, CouzinieAtCines commented on tools/docker/mongo/README.md
> +- si le script a déjà été exécutée, aucun action n'est effectuée
```suggestion
- si le script a déjà été exécuté, aucun action n'est effectuée
```

2020-06-15 15:58 UTC, CouzinieAtCines commented on tools/docker/mongo/README.md
> +Dans le cas d'une migration d'une version de VitamUI précédent le versioning, il suffit de définir la variable Ansible **mock_insert_data**. Dans le cas présent, l'ensemble des scripts seront joués m
```suggestion
Dans le cas d'une migration d'une version de VitamUI précédent le versioning, il suffit de définir la variable Ansible **mock_insert_data**. Dans le cas présent, l'ensemble des scripts sera joué
 mais non exécutés, seules les entrées dans la collection **changelog** seront ajoutées.
```

2020-06-15 15:59 UTC, CouzinieAtCines commented on tools/docker/mongo/README.md
>  fonctionnalité de
```suggestion
fonctionnalités de
```

2020-06-15 16:00 UTC, CouzinieAtCines commented on tools/docker/mongo/README.md
>  fonctionnalité de
fonctionnalités de ... ? =D

2020-07-03 12:47 UTC, benemart approved these changes

2020-07-09 15:50 UTC, gansheer commented
Bonjour à tous, peut-on vraiment ajouter le code de la lib mitogen dans le repository ?

2020-07-15 07:40 UTC, gansheer commented
Les scripts de données ont visiblement tous été déplacés dans tools/docker/mongo/database_scripts. Celà veut-il dire qu'un vitamui peut être déployé et utilisé sans toutes ces données dans l'application vitamui ?

2020-07-24 11:52 UTC, nabilm2i approved these changes

2020-07-24 13:15 UTC, merged