[VAS] Vas item 8067 archive units search by appraisal mgt rules and  8366 adapt saving criteria
ProgrammeVitam/vitam-ui pull request #385
Opened 2021-08-11 12:49 UTC by bbenaissa

archive units item 8067 search by appraisal mgt rules and  8366 adapt saving criteria

2021-08-13 11:54 UTC, depysk requested changes

2021-08-13 11:54 UTC, depysk commented on api/api-archive-search/archive-search-internal/pom.xml
> +                        -Xmx512m -Dvitam.config.folder=${basedir}/src/main/config/dev-vitam -Xdebug
Mode debug à désactiver

2021-08-13 11:54 UTC, depysk commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchAppraisalQueryBuilderService.java
> +            if (searchCriteria.getCriteria()
```
if (searchCriteria.getCriteria().equals(ArchiveSearchConst.AppraisalRuleOriginValues.APPRAISAL_RULE_ORIGIN_HAS_AT_LEAST_ONE.name()) && !CollectionUtils.isEmpty(searchCriteria.getValues())) {
    appraisalRuleOriginRuleCriteria.setHasAtLeastOneRule(ArchiveSearchConst.TRUE_CRITERIA_VALUE.equals(searchCriteria.getValues().get(0)));
}
```
Les conditions imbriquées ci-après peuvent être simplifier avec un "ET" logique (&&)

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/aparaisal-rule-search/apparaisal-rule-search.component.html
> +<div class="archive-search-section">
Attention au nommage des composants, on a 3 noms différents le même terme **AppraisalRule** :

**Appraisal** - **aparaisal** - **apparaisal**

ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/**aparaisal**-rule-search/**apparaisal**-rule-search.component.html

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/aparaisal-rule-search/apparaisal-rule-search.component.ts
> +  styleUrls: ['./apparaisal-rule-search.component.css'],
A supprimer si vide

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/aparaisal-rule-search/apparaisal-rule-search.component.ts
> +    this.appraisalAdditionalCriteria = new Map();
Une raison particulière de ne pas mettre ce bout de code dans ngOnInit()?

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/aparaisal-rule-search/apparaisal-rule-search.component.ts
> +    merge(this.appraisalRuleCriteriaForm.statusChanges, this.appraisalRuleCriteriaForm.valueChanges)
définir un attribut **Subscription** qui libérera l'espace mémoire de cette souscription lors de la fermeture de ce composant (ngOnDestroy)

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> +    this.archiveExchangeDataService.receiveRemoveFromChildSearchCriteriaSubject().subscribe((criteria) => {
définir un attribut Subscription qui libérera l'espace mémoire de cette souscription lors de la fermeture de ce composant (ngOnDestroy)

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> +    this.archiveExchangeDataService.receiveAppraisalSearchCriteriaSubject().subscribe((criteria) => {
définir un attribut Subscription qui libérera l'espace mémoire de cette souscription lors de la fermeture de ce composant (ngOnDestroy)

2021-08-13 11:54 UTC, depysk commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchAgenciesInternalService.java
> +                idCriteriaList.stream().forEach(criteria -> {
l'opérateur `stream()` est inutile ici
`idCriteriaList.stream().forEach()` --> `idCriteriaList.forEach()`

2021-08-13 11:54 UTC, depysk commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchRulesInternalService.java
> +    final private RuleService ruleService;
private avant final ;)

2021-08-13 11:54 UTC, depysk commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchRulesInternalService.java
> +                        searchQuery.setCriteriaList(appraisalMgtRulesCriteriaMap.values().stream().collect(
`searchQuery.setCriteriaList(appraisalMgtRulesCriteriaMap.values().stream().collect(Collectors.toList()));` peut être simplifier en `searchQuery.setCriteriaList(new ArrayList<>(appraisalMgtRulesCriteriaMap.values()));`

2021-08-13 11:54 UTC, depysk commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchRulesInternalService.java
> +    public ArchiveUnit fillOriginatingAgencyName(ResultsDto originResponse,
Cette méthode n'est utilisée nul part

2021-08-13 11:54 UTC, depysk commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchRulesInternalService.java
> +        String ruleType)
Cette méthode n'est utilisée nul part

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> +        var shortNameA = a.Label;
changer const en var?

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> +        this.removeCriteria('NODE', node.id, false);
Serait-il pas intéressant de créer une Enum pour les criteria NODE?

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> +        this.addCriteria('NODE', node.id, node.title, true, 'EQ', SearchCriteriaTypeEnum.NODES, false, 'STRING', false);
Serait-il pas intéressant de créer une Enum pour l' opérateur **EQ** ?

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> +          this.archiveExchangeDataService.sendAppraisalFromMainSearchCriteriaAction({ keyElt: keyElt, valueElt: valueElt, action: 'ADD' });
Serait-il pas intéressant de créer une Enum pour les actions **ADD**, **REMOVE**, ... ?

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> +          category: 'NODES',
Serait-il pas intéressant de créer une Enum pour les catégories **NODES**, **FIELDS**, ... ?

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> +        dataType: 'STRING',
Serait-il pas intéressant de créer une Enum pour les dataTypes **STRING** ?

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.ts
> +  styleUrls: ['./simple-criteria-search.component.css'],
A supprimer si vide

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/title-and-description-criteria-search/title-and-description-criteria-search.component.ts
> +  styleUrls: ['./title-and-description-criteria-search.component.css'],
A supprimer si vide

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/title-and-description-criteria-search/title-and-description-criteria-search.component.ts
> +    this.previousTitleDescriptionCriteriaValue = {
Contenu à déplacer vers ngOnInit() sauf si contrainte

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.ts
> +    this.archiveService.getOntologiesFromJson().subscribe((data: any) => {
définir un attribut Subscription qui libérera l'espace mémoire de cette souscription lors de la fermeture de ce composant (ngOnDestroy)

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.ts
> +    merge(this.simpleCriteriaForm.statusChanges, this.simpleCriteriaForm.valueChanges)
définir un attribut Subscription qui libérera l'espace mémoire de cette souscription lors de la fermeture de ce composant (ngOnDestroy)

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.ts
> +    this.simpleCriteriaForm.get('otherCriteria').valueChanges.subscribe((selectedcriteria) => {
définir un attribut Subscription qui libérera l'espace mémoire de cette souscription lors de la fermeture de ce composant (ngOnDestroy)

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/title-and-description-criteria-search/title-and-description-criteria-search.component.ts
> +    merge(this.quickSearchCriteriaForm.statusChanges, this.quickSearchCriteriaForm.valueChanges)
définir un attribut Subscription qui libérera l'espace mémoire de cette souscription lors de la fermeture de ce composant (ngOnDestroy)

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/title-and-description-criteria-search/title-and-description-criteria-search.component.ts
> +  ngOnChanges(): void {}
A supprimer

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/title-and-description-criteria-search/title-and-description-criteria-search.component.ts
> +  ngOnDestroy() {
Ajouter l'interface OnDestroy à la classe

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/criteria-search/criteria-search.component.ts
> +  ngOnInit(): void {}
A supprimer si non utiliser (avec l'interface OnInit)

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/title-and-description-criteria-search/title-and-description-criteria-search.component.ts
> +export class TitleAndDescriptionCriteriaSearchComponent implements OnInit {
Ajouter l'interface OnDestroy pour la méthode ngOndestroy() du cycle de vie d'Angular

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.ts
> +export class SimpleCriteriaSearchComponent implements OnInit {
Ajouter l'interface OnDestroy pour la méthode ngOndestroy() du cycle de vie d'Angular

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
>  export class ArchiveSearchComponent implements OnInit {
Ajouter les interfaces OnDestroy et OnChanges pour les méthodes ngOndestroy() ngOnChanges() du cycle de vie d'Angular

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
>    ngOnDestroy() {
Ajouter l'interface OnDestroy pour la méthode ngOndestroy() du cycle de vie d'Angular

2021-08-13 11:54 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/aparaisal-rule-search/apparaisal-rule-search.component.ts
> +export class ApparaisalRuleSearchComponent implements OnInit {
Ajouter l'interface OnDestroy pour la méthode ngOndestroy() du cycle de vie d'Angular

2021-08-18 07:58 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/aparaisal-rule-search/apparaisal-rule-search.component.html
> +<div class="archive-search-section">
Renomé

2021-08-18 07:58 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/aparaisal-rule-search/apparaisal-rule-search.component.ts
> +  styleUrls: ['./apparaisal-rule-search.component.css'],
Supprimés

2021-08-18 07:59 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/title-and-description-criteria-search/title-and-description-criteria-search.component.ts
> +export class TitleAndDescriptionCriteriaSearchComponent implements OnInit {
Ajouté

2021-08-18 07:59 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.ts
> +export class SimpleCriteriaSearchComponent implements OnInit {
Ajouté

2021-08-18 07:59 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
>  export class ArchiveSearchComponent implements OnInit {
Ajouté

2021-08-18 07:59 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/aparaisal-rule-search/apparaisal-rule-search.component.ts
> +export class ApparaisalRuleSearchComponent implements OnInit {
Ajouté

2021-08-18 15:20 UTC, nabilm2i requested changes

2021-08-18 15:39 UTC, oussamasic requested changes

2021-08-18 15:39 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchAppraisalQueryBuilderService.java
> +                if (!CollectionUtils.isEmpty(searchCriteria.getValues())) {
un && entre les deux conditions

2021-08-18 15:39 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchAppraisalQueryBuilderService.java
> +                if (!CollectionUtils.isEmpty(searchCriteria.getValues())) {
un && entre les deux conditions

2021-08-18 15:39 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchAppraisalQueryBuilderService.java
> +                if (!CollectionUtils.isEmpty(searchCriteria.getValues())) {
Meme chose

2021-08-18 15:39 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/appraisal-rule-search/appraisal-rule-search.component.ts
> +    // unsubscribe to ensure no memory leaks
Commentaire à supprimer

2021-08-18 15:39 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/appraisal-rule-search/appraisal-rule-search.component.ts
> +  ngOnDestroy() {
Il faut ajouter l'interface OnDestroy pour la méthode ngOndestroy() du cycle de vie d'Angular

2021-08-18 15:42 UTC, oussamasic commented
Il faut aussi squasher les commits

2021-08-19 10:10 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/aparaisal-rule-search/apparaisal-rule-search.component.ts
> +    this.appraisalAdditionalCriteria = new Map();
modifiée

2021-08-19 11:44 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/pom.xml
> +                        -Xmx512m -Dvitam.config.folder=${basedir}/src/main/config/dev-vitam -Xdebug
supprimé

2021-08-19 11:45 UTC, bbenaissa commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/common/AppraisalRuleOriginRuleCriteria.java
> +    private Boolean hasNoNoRule;
renomé

2021-08-19 11:45 UTC, bbenaissa commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/common/ArchiveSearchConst.java
> +public class ArchiveSearchConst {
modifié

2021-08-19 11:45 UTC, bbenaissa commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/common/ArchiveSearchConst.java
> +    public static final String EV_DATE_TIME = "\"evDateTime\"";
supprimé

2021-08-19 11:46 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchRulesInternalService.java
> +                JsonNode queryRules = select.getFinalSelect();
ajouté

2021-08-19 11:46 UTC, bbenaissa commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/common/AppraisalRuleOriginRuleCriteria.java
> +    private Boolean hasNoNoRule;
done

2021-08-19 11:46 UTC, bbenaissa commented on api/api-archive-search/archive-search-external-client/pom.xml
> -            <artifactId>junit-vintage-engine</artifactId>
non

2021-08-19 11:46 UTC, bbenaissa commented on api/api-archive-search/archive-search-external/pom.xml
> -        </dependency>
non

2021-08-19 11:47 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/appraisal-rule-search/appraisal-rule-search.component.html
> +            class="btn-valiate"
renomé

2021-08-19 11:49 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/appraisal-rule-search/appraisal-rule-search.component.ts
> +  ngOnDestroy() {
ajouté

2021-08-19 13:24 UTC, nabilm2i approved these changes

2021-08-19 13:55 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchAppraisalQueryBuilderService.java
> +            if (searchCriteria.getCriteria()
modifié

2021-08-19 14:06 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/appraisal-rule-search/appraisal-rule-search.component.spec.ts
> +});
supprimé

2021-08-19 14:06 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/criteria-search/criteria-search.component.spec.ts
> +});
supprimé

2021-08-19 14:06 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/title-and-description-criteria-search/title-and-description-criteria-search.component.spec.ts
> +});
supprimé

2021-08-19 14:06 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> +          category: 'NODES',
modifié

2021-08-19 16:36 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/appraisal-rule-search/appraisal-rule-search.component.ts
> +    // unsubscribe to ensure no memory leaks
removed

2021-08-19 16:36 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
> +      "GEL": "Gel"
traduites

2021-08-19 16:36 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
> +        }
traduites

2021-08-19 16:36 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
> +      "DUA_TITLE": "Durée d'utilité administrative",
traduites

2021-08-19 16:37 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.ts
> +/*
supprimé

2021-08-19 16:37 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.ts
> +    // unsubscribe to ensure no memory leaks
supprimé

2021-08-19 16:37 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.spec.ts
> +});
supprimé

2021-08-19 16:37 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/models/search.criteria.ts
> +}
Ok

2021-08-20 09:07 UTC, oussamasic approved these changes

2021-08-27 15:41 UTC, merged