Theme engine
ProgrammeVitam/vitam-ui pull request #40
Opened 2020-06-17 19:51 UTC by mamakh

2020-07-10 13:08 UTC, Mocteezuma requested changes
Code qui semble nécessité une modification avant validation de la PR:
- Ajout de code mort (dans du code mort)
- Des `TODO` qui restent dans le code (traiter le cas et supprimer le TODO !)
- Quelques modifications dans certains fichiers qui ne semble avoir aucun lien avec la PR moteur de theme (Attention !)
-- Configs spring, modifications de couleurs ou tailles d'éléments (hors variables de thèmes)

Quelques notes qui demandent plus une attention particulière que des modifications dans le code:
- Ajout de font / css / gstatic
- EXT_VITAMUI_AUTHENTICATION_USER semble avoir été retiré des config mais la clé ajouté autre part. Est-ce normal ?
- Montée de versions qui ne semble avoir aucun lien avec la PR de moteur de thèmes (Attention !)
-- Pourrait compliquer inutilement la validation de la PR (a moins que la montée de version soit nécessaire ici ?)
-- Aussi, montée de version des POM qui me semble non désirée
- Globalement, même si c'est très light, faire passer des modifications qui ne concernent pas la PR en question ralenti la phase de validation de la PR. Attention à bien proposer en PR que les commits qui concernent le PR.

Je fais un déploiement sur mon poste, j'ajouterais peut être des commentaires supplémentaire suite à ca.

2020-07-10 13:08 UTC, Mocteezuma commented on api/api-iam/iam-commons/pom.xml
> +        <version>1.0.2-SNAPSHOT</version>
On en est où dans les versions de Vitam-UI ?
Est-ce bien la 1.0.2 qui est cible ici (d'autant plus qu'on a une montée de 2 versions mineures) ?
Par exemple, la PR 41, qui est censé arriver après, est en version 1.0.0-SNAPSHOT.

2020-07-10 13:08 UTC, Mocteezuma commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/service/CustomerInternalService.java
> +                        LOGGER.error("Cannot instantiate themeColors value as a Map<String, String>. Ignore it");
Dans quel cas pourrait-on avoir ce cas d'erreur ?
Veut-on vriament l'ignorer ?

2020-07-10 13:08 UTC, Mocteezuma commented on cas/cas-server/src/main/config/sass/_login.scss
> +            background-color: var(--vitamui-secondary);
Il y a eu un changement de couleurs au passage ? C'est normal ?

2020-07-10 13:08 UTC, Mocteezuma commented on ui/ui-frontend-common/package.json
> +    "bufferutil": "^4.0.1",
Est-ce normal d'avoir une montée de version Angular (et autres libs) dans cette MR ?

2020-07-10 13:08 UTC, Mocteezuma commented on ui/ui-frontend-common/src/app/modules/components/customer-select-content/customer-select-content.component.ts
> +      this.customers.sort((c1, c2) => c1.label.localeCompare(c2.label));
Note: Eviter les modifications qui ne concernent pas la PR en question

2020-07-10 13:08 UTC, Mocteezuma commented on ui/ui-frontend-common/src/app/modules/components/download-snack-bar/download-snack-bar.component.spec.ts
> +// import { MatProgressBarModule } from '@angular/material/progress-bar';
Ajouts d'imports commentés ???
OK le TU est totalement commenté (ce qui n'est pas le sujet de la MR mais au passage c'est pas cool).
Mais du coup pourquoi ajouter des imports si de toute facon y a pas de test joué ?

2020-07-10 13:08 UTC, Mocteezuma commented on ui/ui-frontend-common/src/app/modules/components/vitamui-input/vitamui-input.component.ts
> +import {Component, ElementRef, forwardRef, HostBinding, HostListener, Input, OnInit, ViewChild} from '@angular/core';
Format ?

2020-07-10 13:08 UTC, Mocteezuma commented on ui/ui-frontend-common/src/app/modules/logbook/event-type-label/event-type-label.component.html
> +  EXT_VITAMUI_AUTHENTICATION_USER {Authentification de l'utilisateur}
EXT_VITAMUI_AUTHENTICATION_USER n'a pas été retiré dans les autres fichiers ?

2020-07-10 13:08 UTC, Mocteezuma commented on ui/ui-frontend-common/src/index.html
> +  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet">
Veut-on vraiment charger ces données ?
Ne peut-on pas avoir des éléments spécifiques en assets, sans avoir besoin de faire plusieurs requêtes google ?
Quel rapport avec le moteur de theme ?

2020-07-10 13:08 UTC, Mocteezuma commented on ui/ui-frontend-common/src/sass/_theme.scss
> +    src: local('Roboto'), url(https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap) format('woff2');
Ne peut on pas ajouter cette font aux sources plutôt que d'avoir un lien vers googleapis ?

2020-07-10 13:08 UTC, Mocteezuma commented on ui/ui-frontend/package.json
> +    "analyze-identity": "ng build identity --stats-json --prod --i18n-locale fr ; webpack-bundle-analyzer dist/identity/stats-es2015.json",
Que fait exactement ce script d'analyse ?
Doit t-on l'ajouter a tout les projets front (referential, ...) ?
Quel rapport avec le moteur de thèmes ?

2020-07-10 13:08 UTC, Mocteezuma commented on ui/ui-frontend/projects/demo/src/index.html
> +  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet">
Deux fois le même import ?

2020-07-10 13:08 UTC, Mocteezuma commented on ui/ui-frontend/projects/identity/src/app/app-routing.module.ts
> +  ],
Note: Pourquoi pas mais rapport avec Moteur de thèmes ?

2020-07-10 13:08 UTC, Mocteezuma commented on ui/ui-frontend/projects/identity/src/app/customer/customer-create/customer-colors-input/customer-colors-input.component.html
> +<!-- TODO: Add specific colors -->
TODO ?

2020-07-10 13:08 UTC, Mocteezuma commented on ui/ui-frontend/projects/identity/src/app/customer/customer-create/customer-colors-input/customer-colors-input.component.html
> +  -->
TODO ?

2020-07-10 13:08 UTC, Mocteezuma commented on ui/ui-frontend/projects/identity/src/app/customer/customer-create/customer-colors-input/customer-colors-input.component.html
> +<div class="dlab-input-errors">
dlab css ?

2020-07-10 13:08 UTC, Mocteezuma commented on ui/ui-frontend/projects/identity/src/app/customer/customer-create/customer-create.component.ts
> +import {ConfirmDialogService, Customer, OtpState, ThemeService} from 'ui-frontend-common';
Import Format

2020-07-10 13:08 UTC, Mocteezuma commented on ui/ui-frontend/projects/identity/src/app/group/group.service.spec.ts
> +    req.flush(result);
Pourquoi créer une constante juste pour l'assigner ?

2020-07-10 13:08 UTC, Mocteezuma commented on ui/ui-frontend/projects/identity/src/app/hierarchy/hierarchy.component.spec.ts
>  // import { HierarchyComponent } from './hierarchy.component';
Pourquoi ajouter des imports commentés (a un fichier de test totalement commenté) ?

2020-07-10 13:08 UTC, Mocteezuma commented on ui/ui-frontend/projects/identity/src/app/user/user-preview/user-preview.component.spec.ts
>  // import { of, Subject } from 'rxjs';
Imports commentés ?

2020-07-10 13:08 UTC, Mocteezuma commented on ui/ui-identity/src/main/config/ui-identity-application-recette.yml
> +    admin-identity: "https://dev.vitamui.com/:9001identity"
Mauvaise URL. Devrait être: `https://dev.vitamui.com:9001/identity`

2020-07-10 13:08 UTC, Mocteezuma commented on ui/ui-frontend-common/src/sass/material/_preview-tab.scss
> +        padding: 30px 85px 30px 40px;
Modification de taille de composant ? Est-ce normal ?

2020-07-10 13:08 UTC, Mocteezuma commented on cas/cas-server/src/main/config/cas-server-application-recette.yml
> +spring.mail.properties.mail.smtp.starttls.enable: false
C'est quoi toutes ces modifs de confs sur CAS (smtp, auth, modif de tenants/ports) ?
Ca correspond à quel besoin ?
Quel rapport avec les thèmes ?

2020-07-10 13:26 UTC, Mocteezuma commented on ui/ui-frontend-common/src/app/modules/logbook/event-type-label/event-type-label.component.html
> +  EXT_VITAMUI_AUTHENTICATION_USER {Authentification de l'utilisateur}
My bad sur ce sujet, c'est authentification qui est remplacé par authentication sur logbook.
Du coup la variable EXT_VITAMUI_AUTHENTIFICATION_USER est-elle toujours utile ici ?

2020-07-10 14:49 UTC, Mocteezuma commented
Une autre remarque aussi:
Y a une conf de dev pour mettre en place la variable de themes (  theme-colors: /  vitamui-primary / vitamui-secondary ) dans les *dev.yml
Mais y a pas de modification des ui-*/application.yml.j2 dans la partie deployment.

C'est normal ?
Ca marche bien sur un déploiement sur environnement dedié ?

2020-07-16 16:28 UTC, mamakh commented on ui/ui-identity/src/main/config/ui-identity-application-recette.yml
> +    admin-identity: "https://dev.vitamui.com/:9001identity"
done

2020-07-16 16:28 UTC, mamakh commented on ui/ui-frontend-common/src/sass/material/_preview-tab.scss
> +        padding: 30px 85px 30px 40px;
oui dans le cadre du moteur de thèmes, une passe graphique a été faite pour corriger les parties graphiques

2020-07-16 16:31 UTC, mamakh commented on cas/cas-server/src/main/config/cas-server-application-recette.yml
> +spring.mail.properties.mail.smtp.starttls.enable: false
Aucun rapport avec le moteur de thèmes. Modification faite au passage.
Sur ces valeurs de compte, il n'y avait pas de TSL. D'ailleurs ce compte ne fonctionne pas.
Il a été changé pour que ça fonctionne sur des postes de dev ici : https://github.com/ProgrammeVitam/vitam-ui/blob/7699c753a7a161a639d8d53ec3a25f1cf42473bb/cas/cas-server/src/main/config/cas-server-application-recette.yml

2020-07-16 16:33 UTC, mamakh commented on ui/ui-frontend/projects/identity/src/app/user/user-preview/user-preview.component.spec.ts
>  // import { of, Subject } from 'rxjs';
sur les corrections associées au moteur de thèmes, il y a eu un update sur les imports. Pour ne pas importer tous les composants material mais que ceux dont on a besoin.
Malgré le fait que ce test soit commenté, les modifications ont été apportés également sur ce fichier

2020-07-16 16:33 UTC, mamakh commented on ui/ui-frontend/projects/identity/src/app/hierarchy/hierarchy.component.spec.ts
>  // import { HierarchyComponent } from './hierarchy.component';
sur les corrections associées au moteur de thèmes, il y a eu un update sur les imports, pour ne pas importer tous les composants material mais que ceux dont on a besoin.
Malgré le fait que ce test soit commenté, les modifications ont été apportés également sur ce fichier

2020-07-16 16:35 UTC, mamakh commented on ui/ui-frontend/projects/identity/src/app/customer/customer-create/customer-colors-input/customer-colors-input.component.html
> +  -->
ça nous a échappé sur la review, on corrige

2020-07-16 16:36 UTC, mamakh commented on ui/ui-frontend/projects/identity/src/app/customer/customer-create/customer-colors-input/customer-colors-input.component.html
> +<div class="dlab-input-errors">
un oubli, on corrige en même temps que le TODO

2020-07-16 16:36 UTC, mamakh commented on ui/ui-frontend/projects/identity/src/app/customer/customer-create/customer-create.component.ts
> +import {ConfirmDialogService, Customer, OtpState, ThemeService} from 'ui-frontend-common';
done

2020-07-16 16:38 UTC, mamakh commented on ui/ui-frontend/projects/identity/src/app/app-routing.module.ts
> +  ],
Souci de performances remontés sur les tests du moteur de thèmes. On en a profité pour apporté ces améliorations

2020-07-16 16:38 UTC, mamakh commented on ui/ui-frontend/projects/demo/src/index.html
> +  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet">
bien vu

2020-07-16 16:39 UTC, mamakh commented on ui/ui-frontend/package.json
> +    "analyze-identity": "ng build identity --stats-json --prod --i18n-locale fr ; webpack-bundle-analyzer dist/identity/stats-es2015.json",
Souci de performances remontés sur les tests du moteur de thèmes. On en a profité pour apporté ces éléments d'analyse qui remontent les tailles des paquets.
C'est intéressant et à ajouter sur toutes les ui effectivement

2020-07-16 16:41 UTC, mamakh commented on ui/ui-frontend-common/src/sass/_theme.scss
> +    src: local('Roboto'), url(https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap) format('woff2');
A discuter, ça alourdit les packages front

2020-07-16 16:41 UTC, mamakh commented on ui/ui-frontend-common/src/index.html
> +  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet">
Souci de performances remontés sur les tests du moteur de thèmes. On en a profité pour apporté ces améliorations.
Ils étaient déjà chargés pour le coup, le fait de les ajouter à l'index améliore les perfs

2020-07-16 16:42 UTC, mamakh commented on ui/ui-frontend-common/src/app/modules/logbook/event-type-label/event-type-label.component.html
> +  EXT_VITAMUI_AUTHENTICATION_USER {Authentification de l'utilisateur}
EXT_VITAMUI_AUTHENTIFICATION_USER a été ajouté pour gérer les legacy. Comme les logbooks ne sont jamais supprimés

2020-07-16 16:44 UTC, mamakh commented on ui/ui-frontend-common/src/app/modules/components/vitamui-input/vitamui-input.component.ts
> +import {Component, ElementRef, forwardRef, HostBinding, HostListener, Input, OnInit, ViewChild} from '@angular/core';
done

2020-07-16 16:45 UTC, mamakh commented on ui/ui-frontend/projects/identity/src/app/group/group.service.spec.ts
> +    req.flush(result);
effectivement ça aurait pu être simplifié

2020-07-16 16:45 UTC, mamakh commented on ui/ui-frontend/projects/identity/src/app/customer/customer-create/customer-colors-input/customer-colors-input.component.html
> +<!-- TODO: Add specific colors -->
on corrige

2020-07-16 16:46 UTC, mamakh commented on ui/ui-frontend-common/src/app/modules/components/download-snack-bar/download-snack-bar.component.spec.ts
> +// import { MatProgressBarModule } from '@angular/material/progress-bar';
sur les corrections associées au moteur de thèmes, il y a eu un update sur les imports, pour ne pas importer tous les composants material mais que ceux dont on a besoin.
Malgré le fait que ce test soit commenté, les modifications ont été apportés également sur ce fichier

2020-07-16 16:47 UTC, mamakh commented on ui/ui-frontend-common/src/app/modules/components/customer-select-content/customer-select-content.component.ts
> +      this.customers.sort((c1, c2) => c1.label.localeCompare(c2.label));
La PR correspond au moteur de thèmes mes en fonction des retours de tests, d'autres corrections peuvent être apportés sur la partie front

2020-07-16 16:48 UTC, mamakh commented on ui/ui-frontend-common/package.json
> +    "bufferutil": "^4.0.1",
La PR correspond au moteur de thèmes mais en fonction des retours de tests, nous avons amélioré les perfs d'où les montées de version mineures

2020-07-16 16:49 UTC, mamakh commented on cas/cas-server/src/main/config/sass/_login.scss
> +            background-color: var(--vitamui-secondary);
Retour de tests sur le moteur de thèmes, nous avons effectué une adaptation des couleurs

2020-07-16 16:50 UTC, mamakh commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/service/CustomerInternalService.java
> +                        LOGGER.error("Cannot instantiate themeColors value as a Map<String, String>. Ignore it");
C'est au cas où il y a un souci de formats.
Exception à levée effectivement

2020-07-16 16:53 UTC, mamakh commented on api/api-iam/iam-commons/pom.xml
> +        <version>1.0.2-SNAPSHOT</version>
Nous avons fait des montées de version en interne.
C'était avant la clarification sur la gestion des versions.

2020-07-16 16:56 UTC, mamakh commented
@Mocteezuma pour la partie déploiement, nous l'avons traité à côté ici : https://github.com/ProgrammeVitam/vitam-ui/pull/42

2020-07-21 07:54 UTC, CouzinieAtCines commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/webflow/actions/CustomInitialFlowSetupAction.java
> +        }
`e.printStackTrace();`  c'est moche :
Il vaut mieux utiliser le logger qui fait déjà tout le boulot : 

`LOGGER.warn("Can't find vitam logo", e);`

2020-07-21 08:00 UTC, CouzinieAtCines commented on deployment/README.rst
> +Pou définir les couleurs de base du système visibles par défaut sur l'ensemble des interfaces utilisateurs, il faut surcharger cette structure  :
```suggestion
platform_name est utilisé pour définir / surcharger le nom de l'application qui sera récupéré sur les applications frontend et affiché par exemple dans le titre de la page.
Pour définir les couleurs de base du système visibles par défaut sur l'ensemble des interfaces utilisateurs, il faut surcharger cette structure  : 
```

2020-07-21 08:12 UTC, CouzinieAtCines commented on ui/ui-frontend-common/package.json
> +    "bufferutil": "^4.0.1",
Et le ui-frontend-common descend en version 0.0.13 ?

2020-07-21 08:34 UTC, mamakh commented on ui/ui-frontend-common/package.json
> +    "bufferutil": "^4.0.1",
euh étrange, on avait fait une ou plusieurs montée de version. je regarde ce point

2020-07-21 08:34 UTC, mamakh commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/webflow/actions/CustomInitialFlowSetupAction.java
> +        }
très moche en effet, je fixe

2020-07-21 08:57 UTC, CouzinieAtCines commented on ui/ui-frontend/projects/identity/src/locale/messages.xlf
> +      <x id="START_ITALIC_TEXT" ctype="x-i" equiv-text="&lt;i&gt;"/><x id="CLOSE_ITALIC_TEXT" ctype="x-i" equiv-text="&lt;/i&gt;"/> Le mode subrogation est activté pour <x id="INTERPOLATION" equiv-te
Typo

```suggestion
      <x id="START_ITALIC_TEXT" ctype="x-i" equiv-text="&lt;i&gt;"/><x id="CLOSE_ITALIC_TEXT" ctype="x-i" equiv-text="&lt;/i&gt;"/> Le mode subrogation est activé pour <x id="INTERPOLATION" equiv-text="{{data.duration}}"/> minutes, jusqu&apos;à
```

2020-07-21 09:11 UTC, CouzinieAtCines commented on ui/ui-frontend/projects/identity/src/locale/messages.xlf
> +              séparés par le caractères .)
```suggestion
              séparés par le caractère '.')
```

2020-07-21 09:12 UTC, CouzinieAtCines commented on ui/ui-frontend/projects/identity/src/locale/messages.xlf
> +        <source>Ce groupe possède des profiles</source>
Typo

```suggestion
        <source>Ce groupe possède des profils</source>
```

2020-07-23 09:11 UTC, CouzinieAtCines commented on ui/ui-frontend-common/src/sass/_badge.scss
> +        background-color: #dadada;
C'est devenu du light_grey maintenant ^^
On rajoute une entrée dans le fichier _ui/ui-frontend-common/src/sass/variables/_colors.scss _ ?

2020-07-23 09:13 UTC, mamakh commented on ui/ui-frontend-common/src/sass/_badge.scss
> +        background-color: #dadada;
oui effectivement, ça peut être géré par une entrée dans _colors.scss

2020-07-23 09:59 UTC, mamakh commented on ui/ui-frontend-common/src/sass/_badge.scss
> +        background-color: #dadada;
j'ai créé une JIrA pour faire une passe chez nous, il y a sûrement d'autres cas.
Nous ferons une PR corrective

2020-07-23 11:00 UTC, CouzinieAtCines commented on ui/ui-frontend-common/src/sass/_theme.scss
> +    src: local('Roboto'), url(https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap) format('woff2');
Personne ne veux apporter quelque chose sur ce point ? On resolve ?

2020-07-23 11:09 UTC, mamakh commented on ui/ui-frontend-common/src/sass/_theme.scss
> +    src: local('Roboto'), url(https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap) format('woff2');
c'est à discuter / traiter pour moi en adhoc. 
L'appel à cet URL y était, ça a été juste déplacé ici. Je voudrais en discuter au retour de Ludovic avec d'autres personnes potentiellement avant d'acter quelque chose

2020-07-23 11:11 UTC, CouzinieAtCines commented
>     * Ajout de code mort (dans du code mort)

Peut-on reporter ca pour une autre PR pour nettoyer ce genre de fichiers morts ?

2020-07-23 11:15 UTC, mamakh commented
> > ```
> > * Ajout de code mort (dans du code mort)
> > ```
> 
> Peut-on reporter ca pour une autre PR pour nettoyer ce genre de fichiers morts ?

ce sont des tests à réactiver pour moi @CouzinieAtCines . ça n'aurait jamais dû etre commenté.
C'est de la dette technique que  j'ai noté et qu'on va corriger

2020-07-24 14:07 UTC, CouzinieAtCines approved these changes

2020-07-27 09:35 UTC, TDevillechabrolle approved these changes

2020-07-27 15:03 UTC, merged