Vas item 8441 update dev spring config vitamui modules
ProgrammeVitam/vitam-ui pull request #400
Opened 2021-08-23 15:31 UTC by bbenaissa

## Description

Cette PR contient des modifications ayant pour but de faciliter les développements et l'intégration de spring avec les IDE des devs pour les modules Archive-Search et Ingest. 

Elle permet de pouvoir utiliser nativement les fonctionnalités de débbugage de l'IDE ainsi que le lancement des modules sur les postes des devs. 

Note : il faudra potentiellement mettre à jours les runner des postes des devs s'ils en ont. 
Note: Il faudra d’abord merger la PR 359 avant celle-ci. 

Aucun impact sur l'existant.

## Type de changement
-  Technique : Amélioration du développement

## Checklist

 [X ] Mon code suit le style de code de ce projet.
 [X] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.
 [X] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.
 [X] Les tests unitaires nouveaux et existants passent avec succès localement.
 [X] Toutes les dépendances ont été mergées en priorité

## Contributeur

Vitam Accessible en Service (VAS)

2021-09-09 16:40 UTC, depysk requested changes

2021-09-09 16:40 UTC, depysk commented on pom.xml
> +                            <exclude>application-*.yml</exclude>
On est sûr d'exclure les fichiers `<exclude>application-*.yml</exclude>` su répertoire `src/main/resources` ?

2021-10-07 18:26 UTC, bbenaissa commented on pom.xml
> +                            <exclude>application-*.yml</exclude>
Pour le profil prod, on ignore les autres profiles

2021-10-08 08:11 UTC, depysk approved these changes

2021-10-08 08:12 UTC, oussamasic approved these changes

2021-10-12 07:12 UTC, merged