add UA selection behaviour
ProgrammeVitam/vitam-ui pull request #409
Opened 2021-08-31 14:12 UTC by oussamasic

## Description
L'objectif de cette PR est de modifier le comportement de sélection des unités archivistiques après une recherche lancée par l'utilisateur.
Ce comportement de sélection sera utile dans les US qui concernent la partie téléchargement DIP et élimination des règles de gestion.

## Type de changement:
* Nouveau Code 
* Refactorisation de code

## Documentation:

## Tests:
- Des tests fonctionnels sont effectués pour vérifier le fonctionnement de cette évolution.

## Migration:
- Pas de modification au niveau de la DB, 
- pas de migration.

## Checklist:
[X] Mon code suit le style de code de ce projet.
[X] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.
[X] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.
[X] Les tests unitaires nouveaux et existants passent avec succès localement.

## Contributeur
Vitam Accessible en Service (VAS)

2021-09-08 10:09 UTC, depysk requested changes

2021-09-08 10:09 UTC, depysk commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
> +    private void test() {
Méthode vide --> A supprimer

2021-09-08 10:09 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> +    // this.checkUserHasRole('EliminationAnalysis', 'ROLE_EXPORT_DIP', +this.tenantIdentifier);
Code commenté à supprimer

2021-09-08 10:09 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> +    if (this.isAllchecked) {
Ce premier `if` peut être mutualisé avec la condition qui suit :

```
if (this.isAllchecked && !action) {
        this.listOfUACriteriaSearch = [];
        this.isIndeterminate = true;
        this.listOfUAIdToExclude.push({ value: id, id });
        this.listOfUAIdToInclude = [];
        if (this.itemSelected > 0) {
          this.itemSelected--;
          this.itemNotSelected++;
        }
} else {
        ...
}
```

2021-09-08 10:09 UTC, depysk commented on ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation.component.ts
> +        console.log(params);
Supprimer le console.log() ou le remplacer par l'utilisation du service Logger

2021-09-08 10:09 UTC, depysk commented on ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation.component.ts
>        console.error('LogbookOperationComponent Error: no list in the template');
Supprimer le console.error() ou le remplacer par l'utilisation du service Logger

2021-09-08 10:09 UTC, depysk commented on ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation.component.ts
> +        console.log(this.workflowGuidToSearch);
Supprimer le console.log() ou le remplacer par l'utilisation du service Logger

2021-09-08 14:09 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
> +    private void test() {
deleted

2021-09-08 14:09 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> +    // this.checkUserHasRole('EliminationAnalysis', 'ROLE_EXPORT_DIP', +this.tenantIdentifier);
deleted

2021-09-08 14:10 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation.component.ts
> +        console.log(params);
deleted

2021-09-08 14:10 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation.component.ts
>        console.error('LogbookOperationComponent Error: no list in the template');
deleted

2021-09-08 14:10 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation.component.ts
> +        console.log(this.workflowGuidToSearch);
deleted

2021-09-08 14:37 UTC, CouzinieAtCines commented on commons/commons-vitam/src/test/java/fr/gouv/vitamui/commons/vitam/api/access/ExportDipV2ServiceTest.java
> +    }
Un oubli ou c'est pour plus tard ?

2021-09-08 14:40 UTC, CouzinieAtCines commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/appraisal-rule-search/appraisal-rule-search.component.ts
> +    // console.log('actualCategory', actualCategory);
Le log a été commenté par erreur ?

2021-09-08 16:46 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/appraisal-rule-search/appraisal-rule-search.component.ts
> +    // console.log('actualCategory', actualCategory);
log supprimé

2021-09-08 16:46 UTC, oussamasic commented on commons/commons-vitam/src/test/java/fr/gouv/vitamui/commons/vitam/api/access/ExportDipV2ServiceTest.java
> +    }
un oubli ==> classe de test supprimé

2021-09-08 16:47 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> +    if (this.isAllchecked) {
Done

2021-09-09 07:31 UTC, CouzinieAtCines approved these changes

2021-09-09 07:39 UTC, bbenaissa approved these changes

2021-09-09 12:42 UTC, depysk approved these changes

2021-09-09 14:20 UTC, merged