Java11
ProgrammeVitam/vitam-ui pull request #41
Opened 2020-06-23 22:37 UTC by mamakh

## Description
Cette PR contient des mises à jour techniques ainsi que quelques correctifs liés aux versions, à l'authentification et fonctionnalités de CAS.
Mise à jour de CAS en version 6.1.6
Mise à jour de SpringBoot en version 2.2.6.RELEASE
Mise à jour Spring en version 5.2.5.RELEASE
Mise à jour de Serenity, Cucumber et des tests d'intégration
Mise à jour des plugins Maven

## Type de changement:
Code et/ou Configuration : Refactorisation
Build :
Ansiblerie

## Documentation:
[X] Quels sont les nouvelles documentations?
Modification des README et DAT VITAMUI

## Tests:
Tests de déploiement
Tests sur les différents interfaces

## Migration:

## Checklist:
[x] Mon code suit le style de code de ce projet.
[x] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.
[x] J'ai fait les changements correspondant dans la documentation Technique.
[x] Les tests unitaires nouveaux et existants passent avec succès localement.
[x] Toutes les dépendances ont été mergées en priorité

2020-07-08 14:01 UTC, Mocteezuma reviewed
Première passe rapide, je ferais une passe plus complète et plus en profondeur demain pour analyser le code et ses intéractions.

2020-07-08 14:01 UTC, Mocteezuma commented on api/api-iam/iam-external/pom.xml
> +        </dependency>
Pourquoi ne pas garder cette dépendances dans metrics ?
Et le mettre dans la partie spring des dépendances ?
#Comment1

Nb: Je n'ai pas retourné tout les cas de cette remarque pour éviter de surcharger la MR

2020-07-08 14:01 UTC, Mocteezuma commented on api/api-iam/iam-external/src/test/java/fr/gouv/vitamui/iam/external/server/service/ProfileExternalServiceTest.java
> +        if (roles != null && roles.size() > 0) {
Pourquoi ne plus utiliser la lib apache ?
Sinon `!roles.isEmpty()` n'est pas plus efficace et plus clair que `roles.size() > 0` ?
#Comment2

Nb: Je n'ai pas retourné tout les cas de cette remarque pour éviter de surcharger la MR

2020-07-08 14:01 UTC, Mocteezuma commented on api/api-iam/iam-external/src/test/java/fr/gouv/vitamui/iam/external/server/service/TenantExternalServiceTest.java
> +        if (roles != null && roles.size() > 0) {
Pareil #Comment2

2020-07-08 14:01 UTC, Mocteezuma commented on api/api-iam/iam-internal/pom.xml
> +        </dependency>
Pareil #Comment1

2020-07-08 14:01 UTC, Mocteezuma commented on api/api-iam/iam-external/src/test/java/fr/gouv/vitamui/iam/external/server/service/ApplicationExternalServiceTest.java
> +        if (roles != null && roles.size() > 0) {
Pareil #Comment2

2020-07-08 14:01 UTC, Mocteezuma commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/authentication/DelegatedSurrogateAuthenticationPostProcessor.java
> +        val credential = transaction.getPrimaryCredential().get();
Globalement, qu'apport lombook.val ?
Je vois ce qu'il fait, et a quoi il sert mais pour moi dans les cas d'utilisation ici il n'apporte ni lisibilité ni interet.
Je ne vais pas les remonter tous pour pas flooder de commentaires.

2020-07-08 14:01 UTC, Mocteezuma commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/webflow/actions/CustomVerifyPasswordResetRequestAction.java
> +                return error();
Pourquoi logger au niveau warn sur un cas d'erreur ?

2020-07-09 14:06 UTC, gansheer commented
Que sont devenus les script init_bdd ? Je ne les trouve plus null part dans la branche

2020-07-09 14:56 UTC, thermoweb requested changes
lombok.val: quel intérêt dans une pr java 11 ? peu lisible et peu d'intérêt.
api/api-iam/iam-external/src/main/config/truststore_server.jks.old --> .old ?
pourquoi tous ces changements de déploiement ?
certains fichiers du projet deploiment ont été supprimés, pourquoi ?
à quoi sert le dev-deploiment ?
pourquoi l'ajout de la dépendance common-private de vitam ? 
pourquoi intégrer la lib mitogen directement dans vitamui ??

Plus généralement il y a beaucoup de modifications qui n'ont pas de rapport avec la montée de version java 11.

2020-07-09 14:56 UTC, thermoweb commented on api/api-iam/iam-external/src/test/java/fr/gouv/vitamui/iam/external/server/service/ApplicationExternalServiceTest.java
> -        if (CollectionUtils.isNotEmpty(roles)) {
c'est pas bien `!CollectionUtils.isEmpty(roles)` ?

2020-07-09 14:56 UTC, thermoweb commented on api/api-iam/iam-internal/pom.xml
> +			<artifactId>common-private</artifactId>
c'est normal d'ajouter une dépendance de `common-private` ?

2020-07-09 14:56 UTC, thermoweb commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/idp/service/IdentityProviderInternalService.java
> +import java.util.*;
faut éviter les import *
c'est de la conf de l'IDE souvent qu'il faut modifier

2020-07-09 14:56 UTC, thermoweb commented on api/api-referential/referential-internal/pom.xml
> +            <artifactId>pac4j-saml-opensamlv3</artifactId>
le passage a samlv3 est imposé par le changement java 11 ?

2020-07-09 14:56 UTC, thermoweb commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/util/Utils.java
> +            if (mailSender == null || org.apache.commons.lang3.StringUtils.isBlank(text) || org.apache.commons.lang3.StringUtils.isBlank(from)
import ?

2020-07-09 14:56 UTC, thermoweb commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/webflow/actions/CustomVerifyPasswordResetRequestAction.java
> +        } catch (final InvalidTicketException e) {}
silent exception ?

2020-07-09 14:56 UTC, thermoweb commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/webflow/actions/DispatcherAction.java
> +        val provider = (SamlIdentityProviderDto) identityProviderHelper.findByUserIdentifier(providersService.getProviders(), dispatchedUser).orElse(null);
a quoi sert le cast avec le "val" ?

2020-07-09 14:56 UTC, thermoweb commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/webflow/actions/GeneralTerminateSessionAction.java
>  import java.util.*;
import *

2020-07-09 14:56 UTC, thermoweb commented on cas/cas-server/src/main/java/org/apereo/cas/CasEmbeddedContainerUtils.java
> +            return "   _______           _____  __      ___ _                  _    _ _______  \n" +
yolo

2020-07-09 14:56 UTC, thermoweb commented on commons/commons-api/src/test/java/fr/gouv/vitamui/commons/api/logger/VitamUILoggerImplWithoutConfigurationTest.java
> +//@RunWith(PowerMockRunner.class)
remove comments

2020-07-09 14:56 UTC, thermoweb commented on commons/commons-logbook/pom.xml
> +			<artifactId>common-private</artifactId>
common-private ???

2020-07-09 14:56 UTC, thermoweb commented on commons/commons-mongo/src/main/java/fr/gouv/vitamui/commons/mongo/config/MongoConfig.java
> + * contact@programmevitam.fr This software is a computer program whose purpose
petit souci de licence ?

2020-07-09 14:56 UTC, thermoweb commented on deployment/environments/vitamui_extra_vars.yml
> -vitamui_site_name: "changeme"
pourquoi le supprimer

2020-07-09 14:56 UTC, thermoweb commented on deployment/generate_stores_dev.sh
> +. $(dirname $0)/pki/scripts/lib/stores.sh
je préfère utiliser `source` au lieu de `. `

2020-07-09 14:56 UTC, thermoweb commented on deployment/lib/mitogen-0.2.9/LICENSE
> +Copyright 2019, David Wilson
Pourquoi avoir ajouté le code de la lib mitogen dans le code vitamui ???

2020-07-09 14:56 UTC, thermoweb commented on deployment/mongo.yml
> -        - init_bdd
pourquoi cette suppression ?

2020-07-09 14:56 UTC, thermoweb commented on deployment/pki/scripts/generate_ca.sh
functions.sh n'était pas compatible java11 ?

2020-07-09 14:56 UTC, thermoweb commented on deployment/roles/checks/tasks/check_java.yml
> +    state: absent
check_java qui désinstalle java8 ?

2020-07-09 14:56 UTC, thermoweb commented on deployment/roles/checks/tasks/main.yml
> +- name: check if java 11 is the version installed
ça check pas, ça désinstall et install java

2020-07-09 14:56 UTC, thermoweb commented on deployment/roles/mongo_configure/vars/main.yml
> -mongo_version: "4.2"
du coup c'est quelle version maintenant ?

2020-07-09 14:56 UTC, thermoweb commented on deployment/roles/mongo_init/vars/main.yml
> +mongo_version: "4.0"
downgrade from 4.2 to 4.0 ???

2020-07-09 14:56 UTC, thermoweb commented on tools/docker/mongo/database_scripts/1.0.0/02_security_ref.js.j2
> +db = db.getSiblingDB('security')
c'est pas plutot "mongodb.security.db" ?

2020-07-09 14:56 UTC, thermoweb commented on tools/docker/mongo/mongo_dev.yml
> -      - "$PWD/mongo-entrypoint/:/vitamui/scripts/mongo/data"
pour ce changement de répertoire ?

2020-07-09 15:04 UTC, mathieuleguay commented
@thermoweb 
> Plus généralement il y a beaucoup de modifications qui n'ont pas de rapport avec la montée de version java 11.

La PR est héritée de celle-ci: https://github.com/ProgrammeVitam/vitam-ui/pull/38. Les reliquats concernant l'ancienne version de la base de données viennent de l'ancienneté de la PR en effet.

@gansheer Même réponse qu'au dessus. Les scripts sont centralisés dans `tools/docker/mongo/database_scripts`. Le role exploité pour initialiser la base de données, en local ou pour un déploiement est le même, plus de duplication de scripts.

2020-07-16 17:00 UTC, mamakh commented on api/api-iam/iam-external/pom.xml
> +        </dependency>
La partie metrics est très fortement associé à la partie actuator. 
Du coup ça a été associé pour améliorer la lisibilité.
les deux sont fortement liés

2020-07-16 17:07 UTC, mamakh commented on api/api-iam/iam-external/src/test/java/fr/gouv/vitamui/iam/external/server/service/ProfileExternalServiceTest.java
> +        if (roles != null && roles.size() > 0) {
bien vu

2020-07-16 17:08 UTC, mamakh commented on api/api-iam/iam-external/src/test/java/fr/gouv/vitamui/iam/external/server/service/TenantExternalServiceTest.java
> +        if (roles != null && roles.size() > 0) {
okay

2020-07-16 17:08 UTC, mamakh commented on api/api-iam/iam-internal/pom.xml
> +        </dependency>
La partie metrics est très fortement associé à la partie actuator.
Du coup ça a été associé pour améliorer la lisibilité.
les deux sont fortement liés

2020-07-16 17:08 UTC, mamakh commented on api/api-iam/iam-external/src/test/java/fr/gouv/vitamui/iam/external/server/service/ApplicationExternalServiceTest.java
> +        if (roles != null && roles.size() > 0) {
vu

2020-07-16 17:10 UTC, mamakh commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/authentication/DelegatedSurrogateAuthenticationPostProcessor.java
> +        val credential = transaction.getPrimaryCredential().get();
Ceci est une surcharge de projet open source de cas, ils ont choisi d'utiliser val.
D'autres auraient fait différemment

2020-07-16 17:10 UTC, mamakh commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/webflow/actions/CustomVerifyPasswordResetRequestAction.java
> +                return error();
done

2020-07-16 17:12 UTC, mamakh commented
> Que sont devenus les script init_bdd ? Je ne les trouve plus null part dans la branche

les scripts sont dans tools/docker/mongo 
Pour aller vite Olivier avait dupliqué les scripts, ce qui n'est pas maintenable. ça a été regroupé sur la PR sur les scripts Mongo avec la gestion du versionning etc

2020-07-16 17:15 UTC, mamakh commented on api/api-iam/iam-external/src/test/java/fr/gouv/vitamui/iam/external/server/service/ApplicationExternalServiceTest.java
> -        if (CollectionUtils.isNotEmpty(roles)) {
Les deux écritures se valent pour moi

2020-07-16 17:17 UTC, mamakh commented on api/api-referential/referential-internal/pom.xml
> +            <artifactId>pac4j-saml-opensamlv3</artifactId>
Dans le passage en java11, il y a une montée de version de CAS qui implique celle de ces dépendances utilisées comme pac4j

2020-07-16 17:19 UTC, mamakh commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/util/Utils.java
> +            if (mailSender == null || org.apache.commons.lang3.StringUtils.isBlank(text) || org.apache.commons.lang3.StringUtils.isBlank(from)
nous avons ajouté la possibilité d'envoyer un email en html.
Une attention plus particulière pour dissocier les modifications sera apportée sur les prochaines PR

2020-07-16 17:28 UTC, mamakh commented on api/api-iam/iam-internal/pom.xml
> +			<artifactId>common-private</artifactId>
lombok.val c'est pour garder une homogénéité avec  la surcharge du projet opensource CAS.

Sur les déploiements, nos devops ont voulu améliorer cette partie pour mutualiser les cots par exemple avec VITAM ou la mise à jour des modules avec la gestion plus fine des modules, de leurs mise à jour (installation / désinstallation)
Une attention plus particulière pour dissocier les modifications sera apportée sur les prochaines PR
Les différentes modifications sont un peu arrivées en même  temps et Cette PR est devenue le réceptacle de toutes les modifications techniques autour de JAVA11.

Pour dissocier les certificats de déploiement et de dev et suite à des discussions sur le slack, le dev-deployment a été créé pour utiliser la pki pour générer les certificats de dev.

Mitogen permet grandement d'améliorer les déploiements. ça été mis sur tous nos projets.
Suite à des discussions avec thierry, nous feront uns autre PR pour la rendre optionnelle

2020-07-16 17:30 UTC, mamakh commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/webflow/actions/CustomVerifyPasswordResetRequestAction.java
> +        } catch (final InvalidTicketException e) {}
le point sur l'absence du ts est traité juste après

2020-07-16 17:30 UTC, mamakh commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/webflow/actions/DispatcherAction.java
> +        val provider = (SamlIdentityProviderDto) identityProviderHelper.findByUserIdentifier(providersService.getProviders(), dispatchedUser).orElse(null);
comportement du projet open source sur l'utilisation du 'val'

2020-07-16 17:31 UTC, mamakh commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/webflow/actions/GeneralTerminateSessionAction.java
>  import java.util.*;
d'autres import '.*' non liées seront traités sur une autre PR

2020-07-16 17:32 UTC, mamakh commented on cas/cas-server/src/main/java/org/apereo/cas/CasEmbeddedContainerUtils.java
> +            return "   _______           _____  __      ___ _                  _    _ _______  \n" +
Un affichage un peu plus sympa sur les logs !

2020-07-16 17:33 UTC, mamakh commented on commons/commons-mongo/src/main/java/fr/gouv/vitamui/commons/mongo/config/MongoConfig.java
> + * contact@programmevitam.fr This software is a computer program whose purpose
bien vu, merci !

2020-07-16 17:33 UTC, mamakh commented on deployment/environments/vitamui_extra_vars.yml
> -vitamui_site_name: "changeme"
trop de site_name qui correspondent à la même chose, celui là n'était pas utilisé

2020-07-16 17:34 UTC, mamakh commented on deployment/lib/mitogen-0.2.9/LICENSE
> +Copyright 2019, David Wilson
sera revue sur une autre PR pour l'utilisation de mitogen

2020-07-16 17:35 UTC, mamakh commented on deployment/mongo.yml
> -        - init_bdd
La mise à jour mongo et les montées de version ont été gérés sur la PR mongo.
L'init-bdd est géree différement

2020-07-16 17:35 UTC, mamakh commented on deployment/pki/scripts/generate_ca.sh
La mutualisation de la PKI faite

2020-07-16 17:37 UTC, mamakh commented on deployment/roles/mongo_configure/vars/main.yml
> -mongo_version: "4.2"
la version mongo correspond à celle de VITAM désormais avec la mutualisation des cots. Cette valeur n'est plus utilisé

2020-07-16 17:39 UTC, mamakh commented on tools/docker/mongo/mongo_dev.yml
> -      - "$PWD/mongo-entrypoint/:/vitamui/scripts/mongo/data"
L'exécution du docker a été changée, on ne monte plus le volume d'entrypoint avant de lancer les scripts

2020-07-17 07:14 UTC, thermoweb commented on api/api-iam/iam-external/src/test/java/fr/gouv/vitamui/iam/external/server/service/ApplicationExternalServiceTest.java
> -        if (CollectionUtils.isNotEmpty(roles)) {
si elles sont équivalentes, pourquoi avoir changé ?

2020-07-17 07:17 UTC, thermoweb commented on api/api-iam/iam-internal/pom.xml
> +			<artifactId>common-private</artifactId>
Ici je parle du module "common-private" de vitam qui n'est pas censé être utilisé en dehors de vitam.

Concernant lombok, j'ai surtout vu un usage dans le code de vitam-ui à base de "val variable = machin()". Ce qui pour moi réduis la lisibilité et la compréhension du code. Mais j'en parle dans mon commentaire global.

2020-07-17 07:19 UTC, thermoweb commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/util/Utils.java
> +            if (mailSender == null || org.apache.commons.lang3.StringUtils.isBlank(text) || org.apache.commons.lang3.StringUtils.isBlank(from)
pardon je n'ai pas été assez clair dans mon commentaire, je suggère ici d'importer la méthode `isBlank` plutot que d'y faire appel comme ici `org.apache.commons.lang3.StringUtils.isBlank`.

2020-07-21 07:54 UTC, gansheer commented
> > Que sont devenus les script init_bdd ? Je ne les trouve plus null part dans la branche
> 
> les scripts sont dans tools/docker/mongo
> Pour aller vite Olivier avait dupliqué les scripts, ce qui n'est pas maintenable. ça a été regroupé sur la PR sur les scripts Mongo avec la gestion du versionning etc

2020-07-21 07:57 UTC, gansheer commented on api/api-iam/iam-internal/pom.xml
> +			<artifactId>common-private</artifactId>
Sur le sujet mitogen, qu'on l'utilise soit, mais le code ne doit pas être copié dans le repo vitamui. De plus celà ajoute la licence mitogen dans le projet.
Il serait plus adapté de faire un script permettant de l'installer/télécharger.

Le module "common-private" de vitam ne devrait pas être importé dans le projet. Si vous avez besoin de certaines classes dedans n'hésitez pas à nous les indiquez nous verrons s'il est pertinent de la passer dans common-public.

2020-07-21 08:01 UTC, gansheer commented
> @thermoweb
> 
> > Plus généralement il y a beaucoup de modifications qui n'ont pas de rapport avec la montée de version java 11.
> 
> La PR est héritée de celle-ci: #38. Les reliquats concernant l'ancienne version de la base de données viennent de l'ancienneté de la PR en effet.
> Et le dev-deployment permet la centralisation de la PKI de dev utilisé pour les différents modules. C'était, il me semble l'une de tes demandes précédentes.
> 
> @gansheer Même réponse qu'au dessus. Les scripts sont centralisés dans `tools/docker/mongo/database_scripts`. Le role exploité pour initialiser la base de données, en local ou pour un déploiement est le même, plus de duplication de scripts.

Du coup je repose la question de la PR #38 :
Les scripts de données ont visiblement tous été déplacés dans tools/docker/mongo/database_scripts. Celà veut-il dire qu'un vitamui peut être déployé et utilisé sans toutes ces données dans l'application vitamui ?

2020-07-22 00:30 UTC, mamakh commented on api/api-iam/iam-external/src/test/java/fr/gouv/vitamui/iam/external/server/service/ApplicationExternalServiceTest.java
> -        if (CollectionUtils.isNotEmpty(roles)) {
Collectionutils remis

2020-07-22 00:32 UTC, mamakh commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/idp/service/IdentityProviderInternalService.java
> +import java.util.*;
done

2020-07-22 00:32 UTC, mamakh commented on cas/cas-server/src/main/java/fr/gouv/vitamui/cas/util/Utils.java
> +            if (mailSender == null || org.apache.commons.lang3.StringUtils.isBlank(text) || org.apache.commons.lang3.StringUtils.isBlank(from)
done

2020-07-22 00:33 UTC, mamakh commented on deployment/roles/mongo_init/vars/main.yml
> +mongo_version: "4.0"
la version mongo n'est pas utilisée dans les scripts

2020-07-22 00:37 UTC, mamakh commented on deployment/roles/checks/tasks/check_java.yml
> +    state: absent
à l'image de https://github.com/ProgrammeVitam/vitam/blob/e899f3ec417c5dc78b79d5783897c987acd13062/deployment/ansible-vitam/roles/checks/tasks/check_java.yml
désinstallation du java8 s'il était présent sur la machine

2020-07-22 00:41 UTC, mamakh commented
> > @thermoweb
> > > Plus généralement il y a beaucoup de modifications qui n'ont pas de rapport avec la montée de version java 11.
> > 
> > 
> > La PR est héritée de celle-ci: #38. Les reliquats concernant l'ancienne version de la base de données viennent de l'ancienneté de la PR en effet.
> > Et le dev-deployment permet la centralisation de la PKI de dev utilisé pour les différents modules. C'était, il me semble l'une de tes demandes précédentes.
> > @gansheer Même réponse qu'au dessus. Les scripts sont centralisés dans `tools/docker/mongo/database_scripts`. Le role exploité pour initialiser la base de données, en local ou pour un déploiement est le même, plus de duplication de scripts.
> 
> Du coup je repose la question de la PR #38 :
> Les scripts de données ont visiblement tous été déplacés dans tools/docker/mongo/database_scripts. Celà veut-il dire qu'un vitamui peut être déployé et utilisé sans toutes ces données dans l'application vitamui ?

Non les données sont bien initialisées lors du déploiement par le role d'initalisation du mongo en se basant sur la source unique des fichiers
Sujet traité dans la PR également  https://github.com/ProgrammeVitam/vitam-ui/pull/38

2020-07-22 00:53 UTC, mamakh commented on commons/commons-logbook/pom.xml
> +			<artifactId>common-private</artifactId>
C'est historique et lié au logbook externe. Pour générer les événements et les identifiants associés, nous utilisons dans vitam-ui les imports suivants :  import fr.gouv.vitam.common.guid.GUID; import fr.gouv.vitam.common.guid.GUIDFactory;
qui sont dans commons-private.
Le choix avait été fait d'importer ces classes pour se baser sur la même génération d'id que VITAM

2020-07-22 00:54 UTC, mamakh commented on api/api-iam/iam-internal/pom.xml
> +			<artifactId>common-private</artifactId>
C'est historique et lié au logbook externe. Pour générer les événements et les identifiants associés, nous utilisons dans vitam-ui les imports suivants :  import fr.gouv.vitam.common.guid.GUID; import fr.gouv.vitam.common.guid.GUIDFactory;
qui sont dans commons-private.
Le choix avait été fait avec Germain (Smile) il me semble en collaboration avec Julien(Xelians) d'importer ces classes pour se baser sur la même génération d'id que VITAM.
Effectivement ce serait intéressant de passer ça sur commons-public. Vous voulez procéder comment ?

2020-07-22 00:56 UTC, mamakh commented on tools/docker/mongo/database_scripts/1.0.0/02_security_ref.js.j2
> +db = db.getSiblingDB('security')
oui effectivement on aurait pu utiliser la variable ansible comme sur d'autres scripts liés à la PR38 https://github.com/ProgrammeVitam/vitam-ui/pull/38

2020-07-27 14:46 UTC, thermoweb approved these changes

2020-08-05 15:46 UTC, Mocteezuma approved these changes

2020-08-05 15:50 UTC, merged