[VAS] : Item 8343 create Dip Request
ProgrammeVitam/vitam-ui pull request #411
Opened 2021-09-06 17:19 UTC by oussamasic

## Description
L'objectif de cette PR est d'ajouter la nouvelle fonctionnalité qui permet de créer une demande d'exportation d'un DIP au niveau de VitamUI (application Recherche et consultation des archives).

## Type de changement:
* Nouveau Code 
* Refactorisation de code

## Documentation:

## Tests:
- Des tests fonctionnels sont effectués pour vérifier le fonctionnement de cette évolution.
- Des tests unitaires coté Angular sont ajoutés

## Migration:
- Pas de modification au niveau de la DB, 
- pas de migration.

## Checklist:
[X] Mon code suit le style de code de ce projet.
[X] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.
[X] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.
[X] Les tests unitaires nouveaux et existants passent avec succès localement.

## Contributeur
Vitam Accessible en Service (VAS)

2021-09-07 08:52 UTC, depysk requested changes

2021-09-07 08:52 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> +    dialogRef.afterClosed().subscribe((result) => {
Définir un attribut Subscription qui libérera l'espace mémoire de cette souscription lors de la fermeture de ce composant (ngOnDestroy)

2021-09-07 08:52 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> +    dialogRef.afterClosed().subscribe((result) => {
Ajouter l'interface OnDestroy à la classe

2021-09-07 08:52 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/dip-request-create/dip-request-create.component.ts
> +      lifeCycleLogs: this.exportDIPform.get('lifeCycleLogs').value === this.translate.instant('ARCHIVE_SEARCH.DIP.INCLUDE') ? true : false,
Peut être simplifier en :

```
lifeCycleLogs: this.exportDIPform.get('lifeCycleLogs').value === this.translate.instant('ARCHIVE_SEARCH.DIP.INCLUDE')
```

2021-09-07 08:52 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/dip-request-create/dip-request-create.component.ts
> +        console.error('Error message :', error);
Remplacer l'utilisation de la console par le service Logger 

```
private logger: Logger
```

2021-09-07 09:53 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> +    dialogRef.afterClosed().subscribe((result) => {
Done

2021-09-07 09:53 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/dip-request-create/dip-request-create.component.ts
> +      lifeCycleLogs: this.exportDIPform.get('lifeCycleLogs').value === this.translate.instant('ARCHIVE_SEARCH.DIP.INCLUDE') ? true : false,
Done

2021-09-07 09:55 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/dip-request-create/dip-request-create.component.ts
> +        console.error('Error message :', error);
Ajouté

2021-09-07 14:21 UTC, depysk approved these changes

2021-09-08 11:45 UTC, bbenaissa commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/ExportDipCriteriaDto.java
> +    private boolean lifeCycleLogs;
le type du champs et le nom ne sont pas adéquats

2021-09-08 11:45 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
> -    private void test() {
le nom de la méthode n'est pas adapté

2021-09-08 11:45 UTC, bbenaissa commented on commons/commons-vitam/src/test/java/fr/gouv/vitamui/commons/vitam/api/access/ExportDipV2ServiceTest.java
> +        // TODO implement
A enlever ou à implémenter

2021-09-08 11:45 UTC, merged