[CEA] Corrections d'anomalies sur les applications référentiel (lot1)
ProgrammeVitam/vitam-ui pull request #47
Opened 2020-08-25 07:02 UTC by gansheer

## Description

Cette PR contient les bugfixes du lot 1 du CEA et la refonte de la génération du PDF de valeur probante.

Les sujets traités sont les suivants :

**Opération de sécurisation :**

- 18984 - Ajout de l’onglet « vérification ».
- 19123 - Ajout du bouton coffre dans le bandeau de la page
- 18984 – erreur d'orthographe. Corriger le libellé de l'onglet "Véricifation" en "Vérification" dans le volet de droite
- 18982 - Erreur bloquante - erreur 500 quand on télécharge un opération de sécurisation au statut "Warning"
- 19718 - la recherche par identifiant ne renvoie pas le résultat attendu pour les opérations de sécurisation. Le résultat ne correspond pas à la recherche

**Contrat d’entrée :**

 - 19724 –Dans les contrats d'entrée, dans le volet de modification, dans l'onglet information, le libellé est "compte actif"  au lieu de "contrat actif"

**Relevé de valeur probante :**

 - 19715 –la pop up de lancement de relevé de valeur probante n'affiche pas d'erreur si un champ obligatoire n'est pas complété, ni ne grise le bouton de validation : grisage du bouton de validation tant que les champs requis ne sont pas complétés + suppression du bouton retour
- 19714 - Ajouter dans le bandeau « Le relevé de valeur probante a été lancé »

 **Format de fichier :**

 - 18988 - Suppression des formats ajoutés par l’utilisateur

**Profils de sécurité :**

- 18994 - Correction de la mise à jour des profils
- 19016 - Correction de fautes d’orthographe
- 18995 - Suppression des profils de sécurité

**Service agent :**

- 19009 - Correction de la suppression des services agents.
- 19014 - Pas de message de succès après le téléchargement du référentiel.
- 19095 - Ajout d’un message d’erreur, empêchant la création de plusieurs services agent avec le même identifiant.
- 19010 - Correction sur la mise à jour du nom du service agent

**Contrat d’accès**

 - 18999 - Correction de la mise à jour du contrat d’accès

**Contrat d’entrée :**

- 19074 - Correction d’une faute d’orthographe.
- 19120 - Ajout des infos bulle.
- 19001 - Correction de la mise à jour des contrats d’entrée
- 18974, 19000 - Correction sur le formulaire de création de contrats d’entrée

**Ontologie :**

- 19003  - Correction de la recherche
- 19004 - Affichage de la date de création
- 19006 - Suppression d’une ontologie

**Relevé de valeur probante :**

- 19716 - la recherche de relevé de valeur probante par identifiant de relevé, identifiant d'UA date de début ne fonctionne pas
- 18997 - Correction de champ requis.
- 19124 - Ajout du bouton coffre dans le bandeau de la page.
- 18996 - Téléchargement du RVP
- 18996 - Récupération de la valeur probante – téléchargement bloqué

**Contexte applicatif :**

- 18990 - Correction de la fonctionnalité d’ajout de contexte applicatif.
- 19022 - Correction des blocages dans le cadre de l’ajout de permissions.

**Audits :**

- 19103 - Ajout du bouton coffre dans le bandeau de la page.
- 18977 - Correction de libellés

**Autres :**

- 19052 - Réduire les rôles dans le contexte
- Refonte du PDF de relevé de la valeur probante :
  - suppression de la librairie apache FOP
  - utilisation de la fonctionnalité xdocreport de vitamui pour la génération du pdf avec upgrade de la version freemarker

## Type de changement:
Code et/ou Configuration : correction de fonctionnalités existantes
Code et/ou Configuration : Refactorisation de la génération des PDF de valeur probante

## Tests:
Tests de déploiement
Recette sur environnement smile des fixes

La doc swagger et les TU sont prévus dans les PR dédiées à venir

## Contributeur

Commissariat à l'énergie atomique et aux énergies alternatives (CEA)

2020-09-08 13:00 UTC, mamakh commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/export/probativevalue/dto/ProbativeOperationDto.java
> +	private String profil;
profile plutôt que profil

2020-09-08 15:13 UTC, mamakh requested changes
Globalement okay.
Quelques modifications à apporter, je n'ai pas compris le patch avec le dto complet, alors qu'un appel  update existe

2020-09-08 15:13 UTC, mamakh commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamAgencyService.java
> +        LOGGER.error("is ok ? {}", r.isOk());
supprimer le log

2020-09-08 15:13 UTC, mamakh commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/probativevalue/ProbativeValueInternalService.java
> +				LOGGER.error(e.getMessage());
Préciser le message renvoyé par les exceptions

2020-09-08 15:13 UTC, mamakh commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/probativevalue/ProbativeValueInternalService.java
> +			LOGGER.error(exc.getMessage());
Préciser le message renvoyé par l'exception

2020-09-08 15:13 UTC, mamakh commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/probativevalue/ProbativeValueInternalService.java
> +			LOGGER.error(e.getMessage());
Préciser le message renvoyé par l'exception

2020-09-08 15:13 UTC, mamakh commented on commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/BaseCrudRestClient.java
> +    public D patchWithDto(final C context, final D partialDto) {
pourquoi cette nouvelle méthode et pourquoi ne pas utiliser l'update ?

2020-09-08 15:13 UTC, mamakh commented on ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/service/AbstractCrudService.java
> +    public T patchWithDto(final ExternalHttpContext c, final T partialDto, final String id) {
même remarque, pourquoi ne pas utiliser l'update

2020-09-08 15:13 UTC, mamakh commented on ui/ui-frontend/projects/referential/src/app/context/context-preview/context-preview.component.ts
> +      console.log('ResetForm: ', this.tabs.selectedIndex);
enlevez le console.log

2020-09-14 09:01 UTC, gansheer commented on ui/ui-frontend/projects/referential/src/app/context/context-preview/context-preview.component.ts
> +      console.log('ResetForm: ', this.tabs.selectedIndex);
Done

2020-09-14 09:01 UTC, gansheer commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/probativevalue/ProbativeValueInternalService.java
> +			LOGGER.error(e.getMessage());
Done

2020-09-14 09:01 UTC, gansheer commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/probativevalue/ProbativeValueInternalService.java
> +			LOGGER.error(exc.getMessage());
Done

2020-09-14 09:01 UTC, gansheer commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/probativevalue/ProbativeValueInternalService.java
> +				LOGGER.error(e.getMessage());
Done

2020-09-14 09:02 UTC, gansheer commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamAgencyService.java
> +        LOGGER.error("is ok ? {}", r.isOk());
Done

2020-09-14 10:15 UTC, gansheer commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/export/probativevalue/dto/ProbativeOperationDto.java
> +	private String profil;
D'après la specification CEA et le modèle de données VITAM il s'agit bien de "Profil"

2020-09-14 10:16 UTC, gansheer commented on commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/BaseCrudRestClient.java
> +    public D patchWithDto(final C context, final D partialDto) {
Nous faisons bien un patch et non un update de remplacement.

2020-09-14 10:16 UTC, gansheer commented on ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/service/AbstractCrudService.java
> +    public T patchWithDto(final ExternalHttpContext c, final T partialDto, final String id) {
Nous faisons bien un patch et non un update de remplacement.

2020-09-14 15:07 UTC, gansheer commented on commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/BaseCrudRestClient.java
> +    public D patchWithDto(final C context, final D partialDto) {
Reponse de @Mocteezuma :

_Alors, effectivement, déjà il faut savoir que vu que l'on fait des mises à jour un peu spéciales. En effet nous n'avons pas d'update a proprement parler dans VITAM sur la plupart des référentiels, ca passe généralement par réimport.
Ensuite, pour le patchWithDto, c'est surtout que ce n'est pas un update (ce n'est un DTO complet qu'on enregistre en DB en surchargant tout les champs) mais bien un patch (on modifie seulement les champs qu'on fournis en paramètre).
Du coup, à la base, on était parti sur un patch.
Sauf que la map non typée de key/object faisait que certaines valeurs (les tableaux en particuliers) se retrouvaient "stringifiées", et donc serialisées en chaines de caractères, sans avoir la possibilité de savoir la valeure originale.
Du coup on a créé un patch plus spécifique, où au lieu d'envoyer une map, on envoie un DTO, mais qui peut contenir des valeurs nulles.
A noter aussi (même si c'est pas exactement le sujet) que l'on crée le json du DSL "à la main" avant la mise à jour vers VITAM, car le DslHelper a du mal a serialiser les tableaux d'objets en json, et a tendance a en faire un gros string._

2020-09-14 15:07 UTC, gansheer commented on ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/service/AbstractCrudService.java
> +    public T patchWithDto(final ExternalHttpContext c, final T partialDto, final String id) {
Même réponse qu'au dessus.

2020-09-15 07:51 UTC, mamakh approved these changes

2020-09-15 15:05 UTC, nabilm2i commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/ContextInternalController.java
> +    public ContextDto patch(final @PathVariable("id") String id, @RequestBody final ContextDto partialDto) {
je vois @Valid sur quelques Dto et pas sur d'autres ... 
est ce que c'est légitime de faire une validationdes DTOs de vitam si on veut dire, comme les DTO d'iam & co
-> Vitam fait ses controles de son côté bien sur.
-> la question est : est ce que laisser des objets qui viennent de l'ihm contenant des datas qu'on contrôle pas est bien ?
-> pas de sanitize pas de contrôle ?
-> je sais pas si c'est normal de laisse un flux foireux passer jusqu'au backend ? 
(je pense que c'est une question d'ordre général et qui peut ne pas concerner cette PR en particulier, mais bon)

2020-09-15 15:26 UTC, Mocteezuma commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/ContextInternalController.java
> +    public ContextDto patch(final @PathVariable("id") String id, @RequestBody final ContextDto partialDto) {
pas de sanitize pas de contrôle ?
- Effectivement, les sanitize ne seraient pas de trop, tout comme on en a ajouté sur vas globalement il y a peu, mais ca a pas été ajouté avec le dev CEA, et ca ne sera pas fait dans le context de cette PR.

je sais pas si c'est normal de laisse un flux foireux passer jusqu'au backend ?
- De toute facon, l'objet est largement retransformé au passage en DSL, et VITAM fait largement des vérifications de son côté en terme de sanitize et de vérification de l'objet. Donc pas de problème de ce côté là.

2020-09-15 15:28 UTC, nabilm2i commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/ContextInternalController.java
> +    public ContextDto patch(final @PathVariable("id") String id, @RequestBody final ContextDto partialDto) {
Okey

2020-09-15 15:28 UTC, nabilm2i approved these changes

2020-09-15 16:26 UTC, merged