[CEA] Suite des corrections d'anomalies sur les applications référentiel (lot1)
ProgrammeVitam/vitam-ui pull request #48
Opened 2020-09-16 09:35 UTC by gansheer

## Description

Cette PR contient la suite des bugfixes du lot 1 du CEA.

Les sujets traités sont les suivants :

**Opération de sécurisation :**

- 18984 - Securisation - Disable verification buttons for operations with 'WARNING' status
- 19715 - Probative value creation - Fix access contract form control
- 19716 - Probative value - Fix date search filters
- vitam context : add select all option + fix some bugs
- fix empty contracts in vitam context creation and modification

## Type de changement:
Code et/ou Configuration : correction de fonctionnalités existantes

## Tests:
Tests de déploiement
Recette sur environnement smile des fixes

La doc swagger et les TU sont prévus dans les PR dédiées à venir

## Contributeur

Commissariat à l'énergie atomique et aux énergies alternatives (CEA)

2020-09-22 07:48 UTC, mamakh approved these changes
Juste une petite interrogation sur un commentaire

2020-09-22 07:48 UTC, mamakh commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamContextService.java
> +        // FIXME ? The "accessContracts" and "ingestContracts" in the permissions must be rename to "AccessContracts" and "IngestContracts" to be saved in Vitam
faudrait enlever les FIXME et laisser que le commentaire ?

2020-09-23 08:13 UTC, gansheer commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamContextService.java
> +        // FIXME ? The "accessContracts" and "ingestContracts" in the permissions must be rename to "AccessContracts" and "IngestContracts" to be saved in Vitam
Fixed

2020-09-23 14:10 UTC, nabilm2i commented on ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-list/probative-value-list.component.ts
> +    console.log('Filters: ', filters);
delete this

2020-09-23 14:28 UTC, nabilm2i approved these changes

2020-09-23 16:18 UTC, gansheer commented on ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-list/probative-value-list.component.ts
> +    console.log('Filters: ', filters);
Done

2020-09-23 18:27 UTC, Mocteezuma requested changes

2020-09-23 18:27 UTC, Mocteezuma commented on publish_smile.sh
> +done
To be deleted

2020-09-23 19:29 UTC, gansheer commented on publish_smile.sh
> +done
Done

2020-09-24 08:26 UTC, Mocteezuma approved these changes

2020-09-24 09:09 UTC, merged