[DLAB-4240] Add documentation about PKI
ProgrammeVitam/vitam-ui pull request #49
Opened 2020-09-16 13:53 UTC by mathieuleguay

## Description

Cette PR contient l'ajout de la documentation pour la PKI de la solution VitamUI.

L'ajout du lien de la documentation existante de la PKI Vitam est nécessaire.

## Type de changement:
Ajout de documentation

## Contributeur

Xelians

2020-09-18 15:37 UTC, gansheer approved these changes

2020-09-18 15:39 UTC, GiooDev approved these changes

2020-09-23 13:44 UTC, benemart requested changes
Je trouve qu'il manque un paragraphe explicite sur comment gérer les certificats lorsqu'on utilise une PKI externe :
- dans la zone server : vu le nombre d'apps et donc le nombre de certificats nécessaire, perso, j'avais recommandé d'utiliser les certificats générés par le script  fourni. Cependant si on souhaite utiliser une PKI externe, il faut fournir les informations nécessaires à leur génération : 

• Key Usage : digitalSignature, keyEncipherment (j'imagine)
• Extended Key Usage : TLS Web Server Authentication (j'imagine)
• Subject Alternative Name : Nom DNS du service consul

- dans la zone client-vitam et client-external: en prod, il me semble important que ces certificats soient gérés par la PKI externe, du coup également définir les paramètres: 

• Key Usage : digitalSignature, keyEncipherment (j'imagine)
• Extended Key Usage : TLS Web Client Authentication (j'imagine)

2020-10-15 08:42 UTC, mathieuleguay commented
> Je trouve qu'il manque un paragraphe explicite sur comment gérer les certificats lorsqu'on utilise une PKI externe :
> 
> * dans la zone server : vu le nombre d'apps et donc le nombre de certificats nécessaire, perso, j'avais recommandé d'utiliser les certificats générés par le script  fourni. Cependant si on souhaite utiliser une PKI externe, il faut fournir les informations nécessaires à leur génération :
> 
> • Key Usage : digitalSignature, keyEncipherment (j'imagine)
> • Extended Key Usage : TLS Web Server Authentication (j'imagine)
> • Subject Alternative Name : Nom DNS du service consul
> 
> * dans la zone client-vitam et client-external: en prod, il me semble important que ces certificats soient gérés par la PKI externe, du coup également définir les paramètres:
> 
> • Key Usage : digitalSignature, keyEncipherment (j'imagine)
> • Extended Key Usage : TLS Web Client Authentication (j'imagine)

Bonjour,
Je suis d'accord. Toutefois, la PKI VitamUI s'applique sur la PKI Vitam. La documentation demandée porte sur le coeur de la PKI Vitam.
Dans la documentation présentée ici, j'ai juste rappelé certains concepts et les liens entre les différentes PKI des solutions.

@TDevillechabrolle: peut-on avoir un lien vers la documentation de la PKI Vitam, afin de completer cette documentation stp ?

2020-10-16 15:13 UTC, TDevillechabrolle commented
La documentation de la PKI, c'est essentiellement ça:
http://www.programmevitam.fr/ressources/DocCourante/html/installation/annexes/10-overview_certificats.html?highlight=pki

2020-11-30 13:04 UTC, benemart approved these changes

2020-12-01 15:08 UTC, merged