[VAS] Item 8585 Check rules for archive search
ProgrammeVitam/vitam-ui pull request #516
Opened 2021-10-20 15:50 UTC by nabilm2i

2021-10-20 16:54 UTC, bbenaissa requested changes

2021-10-20 16:54 UTC, bbenaissa commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/RuleExternalController.java
> +    @GetMapping("/rules")
attention, au pb de volumetrie, à supprimer ou à remplacer par une paginated

2021-10-20 16:54 UTC, bbenaissa commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/RuleExternalController.java
> +    public ResponseEntity<Void> check(@RequestBody RuleDto accessContractDto, @RequestHeader(value = CommonConstants.X_TENANT_ID_HEADER) Integer tenant) {
Elle sert à quoi cette méthode ?

2021-10-20 16:54 UTC, bbenaissa commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/service/RuleExternalService.java
> +    public List<RuleDto> getAll() {
Même remarque pour la pagination

2021-10-20 16:54 UTC, bbenaissa commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/RuleInternalController.java
> +        LOGGER.debug("get all rule identifier={}");
Meme remarque concernant la pagination

2021-10-20 16:54 UTC, bbenaissa commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/RuleInternalController.java
> +            if (ruleResponseDto.getResults().size() == 0) {
Eviter d'avoir plusieurs return dans la même méthode

2021-10-20 16:54 UTC, bbenaissa commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/RuleInternalController.java
> +            if (ruleResponseDto.getResults().size() == 0) {
risque de nul?, proposition: CollectionUtils(celle de spring).isEmpty(ruleResponseDto.getResults())

2021-10-20 16:54 UTC, bbenaissa commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/RuleInternalController.java
> +                RuleNodeResponseDto ruleNodeResponseDto = objectMapper
Même remarque de plusieurs return

2021-10-20 16:54 UTC, bbenaissa commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/RuleInternalController.java
> +                if(ruleNodeResponseDto.getResults().size() > 0 ) {
risque de nul?, proposition: CollectionUtils(celle de spring).isEmpty(ruleResponseDto.getResults())

2021-10-20 16:54 UTC, bbenaissa commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/details/AccessionRegisterDetailInternalService.java
> +            RequestResponse<AccessionRegisterDetailModel> accessionRegisterDetails = null; //adminExternalClient.findAccessionRegisterDetails(vitamContext, query);
pourquoi cette modif dans cette pr? si ça un sens,à enlever le comment

2021-10-20 16:54 UTC, bbenaissa commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/AccessionRegisterDetailInternalServiceTest.java
> +   /* @Test
Pourquoi commenter ces tests?

2021-10-20 16:54 UTC, bbenaissa commented on commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/rules/RuleInternalRestClient.java
> +    public List<RuleDto> getAll(final C context) {
Meme remarque concernant la pagination

2021-10-20 16:54 UTC, bbenaissa commented on commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/rules/RuleInternalRestClient.java
> +    public List<RuleDto> getOne(final C context) {
Je pense que le nom n'est pas bon

2021-10-26 08:56 UTC, nabilm2i commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/RuleExternalController.java
> +    @GetMapping("/rules")
done

2021-10-26 08:56 UTC, nabilm2i commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/RuleExternalController.java
> +    public ResponseEntity<Void> check(@RequestBody RuleDto accessContractDto, @RequestHeader(value = CommonConstants.X_TENANT_ID_HEADER) Integer tenant) {
le check de l'existence d'une rule ;)

2021-10-26 08:56 UTC, nabilm2i commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/service/RuleExternalService.java
> +    public List<RuleDto> getAll() {
done

2021-10-26 08:56 UTC, nabilm2i commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/RuleInternalController.java
> +        LOGGER.debug("get all rule identifier={}");
done

2021-10-26 08:57 UTC, nabilm2i commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/RuleInternalController.java
> +            if (ruleResponseDto.getResults().size() == 0) {
refactored

2021-10-26 08:59 UTC, nabilm2i commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/RuleInternalController.java
> +                if(ruleNodeResponseDto.getResults().size() > 0 ) {
done

2021-10-26 08:59 UTC, nabilm2i commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/details/AccessionRegisterDetailInternalService.java
> +            RequestResponse<AccessionRegisterDetailModel> accessionRegisterDetails = null; //adminExternalClient.findAccessionRegisterDetails(vitamContext, query);
my bad, corrigé

2021-10-26 09:04 UTC, nabilm2i commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/AccessionRegisterDetailInternalServiceTest.java
> +   /* @Test
corrigé

2021-10-26 09:04 UTC, nabilm2i commented on commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/rules/RuleInternalRestClient.java
> +    public List<RuleDto> getAll(final C context) {
done

2021-10-26 09:04 UTC, nabilm2i commented on commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/rules/RuleInternalRestClient.java
> +    public List<RuleDto> getOne(final C context) {
corrigé

2021-10-26 09:05 UTC, nabilm2i commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/RuleInternalController.java
> +            if (ruleResponseDto.getResults().size() == 0) {
corrigé

2021-10-26 09:05 UTC, nabilm2i commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/RuleInternalController.java
> +                if(ruleNodeResponseDto.getResults().size() > 0 ) {
corrigé

2021-10-26 09:05 UTC, nabilm2i commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/details/AccessionRegisterDetailInternalService.java
> +            RequestResponse<AccessionRegisterDetailModel> accessionRegisterDetails = null; //adminExternalClient.findAccessionRegisterDetails(vitamContext, query);
corrigé

2021-10-26 09:26 UTC, nabilm2i commented on commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/rules/RuleInternalRestClient.java
> +    public List<RuleDto> getOne(final C context) {
done

2021-10-26 09:26 UTC, nabilm2i commented on commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/rules/RuleInternalRestClient.java
> +    public List<RuleDto> getAll(final C context) {
done

2021-10-26 09:26 UTC, nabilm2i commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/AccessionRegisterDetailInternalServiceTest.java
> +   /* @Test
done

2021-10-26 09:26 UTC, nabilm2i commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/details/AccessionRegisterDetailInternalService.java
> +            RequestResponse<AccessionRegisterDetailModel> accessionRegisterDetails = null; //adminExternalClient.findAccessionRegisterDetails(vitamContext, query);
done

2021-10-26 09:26 UTC, nabilm2i commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/RuleInternalController.java
> +                if(ruleNodeResponseDto.getResults().size() > 0 ) {
done

2021-10-26 09:26 UTC, nabilm2i commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/RuleInternalController.java
> +                RuleNodeResponseDto ruleNodeResponseDto = objectMapper
done

2021-10-26 09:26 UTC, nabilm2i commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/RuleInternalController.java
> +            if (ruleResponseDto.getResults().size() == 0) {
done

2021-10-26 09:27 UTC, nabilm2i commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/RuleInternalController.java
> +            if (ruleResponseDto.getResults().size() == 0) {
done

2021-10-26 09:27 UTC, nabilm2i commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/RuleInternalController.java
> +        LOGGER.debug("get all rule identifier={}");
done

2021-10-26 09:27 UTC, nabilm2i commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/service/RuleExternalService.java
> +    public List<RuleDto> getAll() {
done

2021-10-26 09:27 UTC, nabilm2i commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/RuleExternalController.java
> +    public ResponseEntity<Void> check(@RequestBody RuleDto accessContractDto, @RequestHeader(value = CommonConstants.X_TENANT_ID_HEADER) Integer tenant) {
done

2021-10-26 09:27 UTC, nabilm2i commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/RuleExternalController.java
> +    @GetMapping("/rules")
done

2021-10-26 15:06 UTC, bbenaissa approved these changes

2021-10-27 12:27 UTC, oussamasic commented on ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/utils/enums/RuleRestApi.java
> +public abstract class RuleRestApi {
Classe inutile, à supprimer

2021-10-27 12:27 UTC, oussamasic commented on commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/util/RuleRestApi.java
> +public abstract class RuleRestApi {
Classe inutile, à supprimer

2021-10-27 12:27 UTC, oussamasic commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/RuleDto.java
> +public class RuleDto extends IdDto implements Serializable {
je vois que la classe RuleDto est dupliquée, je pense qu'on peut supprimer une et laisser juste la classe utilisée.
- commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/RuleDto.java (je pense que celle qu'on peut supprimer)
- commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/dto/RuleDto.java

2021-10-27 12:27 UTC, oussamasic commented on ui/ui-archive-search/pom.xml
> +                    <jvmArguments>-Xmx512m -Xdebug</jvmArguments>
à enlever le mode Debug

2021-10-27 12:27 UTC, oussamasic commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/administration/RuleService.java
> +    public RequestResponse<FileRulesModel> findRuleById(final VitamContext vitamContext, final String ruleId)
Je pense qu'on utilise pas cette méthode.

2021-10-28 10:13 UTC, nabilm2i commented on ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/utils/enums/RuleRestApi.java
> +public abstract class RuleRestApi {
done

2021-10-28 10:13 UTC, nabilm2i commented on commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/util/RuleRestApi.java
> +public abstract class RuleRestApi {
done

2021-10-28 10:13 UTC, nabilm2i commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/RuleDto.java
> +public class RuleDto extends IdDto implements Serializable {
deleted

2021-10-28 10:14 UTC, nabilm2i commented on ui/ui-archive-search/pom.xml
> +                    <jvmArguments>-Xmx512m -Xdebug</jvmArguments>
deleted

2021-10-28 10:15 UTC, nabilm2i commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/administration/RuleService.java
> +    public RequestResponse<FileRulesModel> findRuleById(final VitamContext vitamContext, final String ruleId)
cleaned

2021-10-28 12:36 UTC, oussamasic approved these changes

2021-10-29 10:42 UTC, merged