[Xelians]SONAR dependencies verification report publication
ProgrammeVitam/vitam-ui pull request #521
Opened 2021-10-27 13:21 UTC by youcefxelians

Cette PR permet de publier le rapport de sécurité des dépendances sur Sonar.

## Type de changement

-  Code et/ou Configuration : Nouvelle fonctionnalité

## Tests

Suite au build un rapport de test est généré avec les vulnérabilités. 

## Migration

 Quels sont les opérations supplémentaires à faire lors d’une migration de VITAM ? 
 De quel version à quel version s’appliquent ces modifications ?

## Checklist

 [ * ] Les tests unitaires nouveaux et existants passent avec succès localement.
 [ * ] Toutes les dépendances ont été mergées en priorité

## Contributeur

Xelians

2021-11-02 08:19 UTC, bbenaissa requested changes

2021-11-02 08:19 UTC, bbenaissa commented on pom.xml
> +                        <artifactId>dependency-check-maven</artifactId>
Bonjour, 

Nous avons déja le plugin utilisé, avec quelques modifications : dependency-check-maven

2022-02-02 14:17 UTC, bbenaissa approved these changes

2022-02-02 14:21 UTC, nabilm2i approved these changes

2022-02-02 14:22 UTC, merged