[Xelians] User preferencies gestion
ProgrammeVitam/vitam-ui pull request #523
Opened 2021-10-27 15:18 UTC by pyXelians

Cette PR permet de gérer les préférences utilisateurs. Une Api a été créée avec des informations partagés de l'utilisateurs comme la langue de préférence.

## Type de changement

-  Code et/ou Configuration : Nouvelle fonctionnalité

## Tests

Nous avons testé que les préférences de l'utilisateur étaient bien enregistré et qu'en se déconnectant/connectant les préférences étaient bien appliquées. 

## Migration

 Quels sont les opérations supplémentaires à faire lors d’une migration de VITAM ? 
 De quel version à quel version s’appliquent ces modifications ?

## Checklist

 [ * ] Les tests unitaires nouveaux et existants passent avec succès localement.
 [ * ] Toutes les dépendances ont été mergées en priorité

## Contributeur

Xelians

2021-11-08 20:20 UTC, nabilm2i requested changes

2021-11-08 20:20 UTC, nabilm2i commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/service/UserInfoInternalService.java
> +import fr.gouv.vitamui.commons.api.domain.GroupDto;
GroupDto not used

2021-11-08 20:20 UTC, nabilm2i commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/domain/UserInfo.java
> +@EqualsAndHashCode
add (callSuper = true) here

2021-11-08 20:20 UTC, nabilm2i commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/service/UserInfoInternalService.java
> +import fr.gouv.vitamui.iam.internal.server.user.converter.UserInfoConverter;
Fix Imports ! configure your IDE with vitamui code Style

2021-11-08 20:20 UTC, nabilm2i commented on api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/cas/service/CasServiceIntegrationTest.java
> +                Criteria.where("obId").is(user.getIdentifier()).and("obIdReq").is(MongoDbCollections.USERS).and("evType").is(EventType.EXT_VITAMUI_BLOCK_USER);
format typo here !

2021-11-08 20:20 UTC, nabilm2i commented on api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/user/service/UserInfoInternalServiceTest.java
> +    private CustomSequenceRepository sequenceRepository;
sequenceRepository not used !

2021-11-08 20:20 UTC, nabilm2i commented on api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/user/service/UserInfoInternalServiceTest.java
> +    private InternalHttpContext internalHttpContext;
internalHttpContext not used ! à supprimer

2021-11-08 20:20 UTC, nabilm2i commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/UserInfoExternalController.java
> +    public UserInfoDto getMe() {
Secure the endpoint ! @Secured(ServicesData....)

2021-11-08 20:20 UTC, nabilm2i commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/UserInfoExternalController.java
> +    public UserInfoDto patchMe(@RequestBody final Map<String, Object> partialDto) {
Idem, Secure the endpoint with @Secured(ServicesData....)

2021-11-08 20:20 UTC, nabilm2i commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/UserInfoExternalController.java
> +    public UserInfoDto patch(final @PathVariable("id") String id, final @RequestBody Map<String, Object> partialDto) {
dans quel use case on utilise patchMe() et l'autre patch() ?

2021-11-08 20:20 UTC, nabilm2i commented on ui/ui-frontend/projects/identity/src/app/profile/profile-create/profile-create.component.ts
> +      if (roleUpdateUsersIndex === -1) {
pour la lisibilité .. pourquoi pas utiliser if(profile.roles.includes(Role.ROLE_UPDATE_USERS)) ?

2021-11-08 20:20 UTC, nabilm2i commented on ui/ui-frontend/projects/identity/src/app/profile/profile-create/profile-create.component.ts
> +        profile.roles.splice(roleUpdateUsersInfoIndex, 1);
qu'est ce que ça corrige fonctionnellement ces ajouts / complétions de rôles ? une explication brève serait la bienvenue !

2021-11-08 20:20 UTC, nabilm2i commented on deployment/scripts/mongod/2.0.0/013_REC-385_fix_user_info_role_duplication_ref.js
> +db.profiles.find({ applicationName: "USERS_APP" }).forEach((profile) => {
d'où viennent les rôles dupiliqués à la base ? c'est lié à ce qui est fait dans profile-create.component.ts j'imagine dans les méthodes de completion des rôles ? j'aimerai bien savoir en profondeur à quoi ça répond ? et quel soucis résout ce truc !

2021-11-08 20:20 UTC, nabilm2i commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/service/UserEmailInternalService.java
> +                            userDto.getFirstname(), userDto.getLastname(), LanguageDto.valueOf(userInfoDto.getLanguage()).getLanguage());
Question lié à l'expiration des mots de passes des utilisateurs et la modification de ces derniers:
- Pourquoi les préférences de langue des utilisateurs ne sont gérés au niveau authentification / changement de password / différents templates CAS ?, l'utilisateur devrait voir ses préférences de langue appliquées au niveau des différentes templates CAS non ?
-

2021-11-08 20:20 UTC, nabilm2i commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/domain/UserInfo.java
> +    private String language;
pourquoi le choix d'ajouter une nouvelle collection ? j'ignore la complexité qui a drivé ce choix ! sacahant qu'on avait l'info de langue au niveau de la collection Users ? et le changement de langue fonctionnait bien ? c'est quoi la limite de l'ancien modèle ?

2021-11-08 20:24 UTC, nabilm2i commented
- Les package-lock des modules ui*frontend et ui*frontend-common et la suppression du tar ont été commité à tort ! à supprimer.
- La PR devrait etre rebasé! les conflicts également à résoudre.
- le build a pété maint fois à cause de ça sur nos CI/CD

2021-11-09 10:30 UTC, pyXelians commented
> * Les package-lock des modules ui_frontend et ui_frontend-common et la suppression du tar ont été commité à tort ! à supprimer.
**Ok**
> * La PR devrait etre rebasé! les conflicts également à résoudre.
**Elle était à jour et n'avait pas de conflit lorsqu'on a créé la PR il y a 13 jours. Tu te doutes bien qu'on ne peut pas la rebase systématiquement en attendant quel soit review ! C'est pour ça qu'on fait les rebase seulement une fois que vous êtes prêt a la merger.**
> * le build a pété maint fois à cause de ça sur nos CI/CD
**Même remarque, que plus haut, il y a 13 jours le build ne passait pas a cause de l'instabilité de votre CI/CD, (sur la notre ça passe). On préfère attendre que vous finissiez la review pour la faire fonctionner.**

2021-11-09 10:35 UTC, pyXelians commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/service/UserInfoInternalService.java
> +import fr.gouv.vitamui.commons.api.domain.GroupDto;
Ok

2021-11-09 10:35 UTC, pyXelians commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/service/UserInfoInternalService.java
> +import fr.gouv.vitamui.iam.internal.server.user.converter.UserInfoConverter;
ok

2021-11-09 10:36 UTC, pyXelians commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/domain/UserInfo.java
> +@EqualsAndHashCode
Ok

2021-11-09 15:58 UTC, pyXelians commented on api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/cas/service/CasServiceIntegrationTest.java
> +                Criteria.where("obId").is(user.getIdentifier()).and("obIdReq").is(MongoDbCollections.USERS).and("evType").is(EventType.EXT_VITAMUI_BLOCK_USER);
je n'ai pas compris ce qui ne va pas ?

2021-11-09 16:02 UTC, pyXelians commented on api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/user/service/UserInfoInternalServiceTest.java
> +    private CustomSequenceRepository sequenceRepository;
Il est utilisé dans le service UserInfoInternalService. Il a donc été mock pour évité tout effet de bord.

2021-11-10 09:43 UTC, pyXelians commented on ui/ui-frontend/projects/identity/src/app/profile/profile-create/profile-create.component.ts
> +        profile.roles.splice(roleUpdateUsersInfoIndex, 1);
Il y avait déjà une fonctionnalité qui avait pour but d'ajouter des rôles lorsqu'on clique sur un toggle. La méthode a été revu pour gérer également les rôles nécessaires a la gestion de UserInfo.

2021-11-10 09:45 UTC, pyXelians commented on deployment/scripts/mongod/2.0.0/013_REC-385_fix_user_info_role_duplication_ref.js
> +db.profiles.find({ applicationName: "USERS_APP" }).forEach((profile) => {
Oui en effet cela vient de cette modification qui dans un premier temps avait un bug. Nous avons ajouté ce script pour corriger les impacts de ce bug.

2021-11-10 10:04 UTC, pyXelians commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/service/UserEmailInternalService.java
> +                            userDto.getFirstname(), userDto.getLastname(), LanguageDto.valueOf(userInfoDto.getLanguage()).getLanguage());
ça n'a pas été vu comme ça par le fonctionnel.

2021-11-10 10:07 UTC, pyXelians commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/domain/UserInfo.java
> +    private String language;
On a voulu isolé ça dans une API a part, pour pouvoir répondre à d'autres besoins concernant les préférences utilisateurs. Aujourd'hui on parle de la langue, demain on pourra gérer d'autres types de préférences, sans "alourdir" le modèle existant.

2021-11-10 14:01 UTC, nabilm2i commented on deployment/scripts/mongod/2.0.0/013_REC-385_fix_user_info_role_duplication_ref.js
> +db.profiles.find({ applicationName: "USERS_APP" }).forEach((profile) => {
ok

2021-11-10 14:02 UTC, nabilm2i commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/service/UserEmailInternalService.java
> +                            userDto.getFirstname(), userDto.getLastname(), LanguageDto.valueOf(userInfoDto.getLanguage()).getLanguage());
ok

2021-11-10 14:05 UTC, nabilm2i commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/UserInfoExternalController.java
> +    public UserInfoDto patchMe(@RequestBody final Map<String, Object> partialDto) {
à part la sécurité des endpoints externes avec les roles adéquats, pour moi c'est bon ! une fois fixé vous rebasez la branche et la suite se fera de notre part

2021-11-10 15:58 UTC, nabilm2i commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/domain/UserInfo.java
> +    private String language;
ok

2021-11-12 09:25 UTC, pyXelians commented on ui/ui-frontend/projects/identity/src/app/profile/profile-create/profile-create.component.ts
> +      if (roleUpdateUsersIndex === -1) {
Sauf erreur de ma part, de ce que je vois la collection role dans le profil est une collection d'objet ayant pour propriété name (Cf ligne 140). Si nous utilisons la méthode includes, il ne va pas réussir a comparer un objet avec l'Enum. C'est pour ça qu'ils ont utilisés findIndex afin de pouvoir comparer la propriété name présent dans l'objet role.

2021-11-15 09:14 UTC, nabilm2i commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/UserInfoExternalController.java
> +    public UserInfoDto patchMe(@RequestBody final Map<String, Object> partialDto) {
bonjour, y a t-il une raison de ne pas sécuriser quelques endpoints dans ce controller ? sinon les autres remarques c'est bon pour moi :+1:

2021-11-15 10:18 UTC, nabilm2i commented on ui/ui-frontend/projects/identity/src/app/profile/profile-create/profile-create.component.ts
> +      if (roleUpdateUsersIndex === -1) {
Ok

2021-11-15 10:55 UTC, pyXelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/UserInfoExternalController.java
> +    public UserInfoDto patchMe(@RequestBody final Map<String, Object> partialDto) {
Ces endpoints ne donnent accès qu'aux informations de l'utilisateur connecté, aucun ID n'est passé en paramètre. Nous avons donc jugé qu'il n'était pas nécessaire d'ajouter un rôle a l'utilisateur lui même pour accéder à ses propres informations. De plus dans user-info il n'y a aucune information sensible.

2021-11-15 11:26 UTC, nabilm2i commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/UserInfoExternalController.java
> +    public UserInfoDto patchMe(@RequestBody final Map<String, Object> partialDto) {
ok, je vois l'idée! tant qu'il n'ya pas d'infos sensibles !

2021-11-15 11:27 UTC, nabilm2i approved these changes

2021-11-17 08:17 UTC, merged