[VAS] item 8331 accession register advanced search
ProgrammeVitam/vitam-ui pull request #547
Opened 2021-11-15 13:05 UTC by depysk

Accession register advanced search implementation

2021-12-17 14:36 UTC, oussamasic commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/AccessionRegisterExternalController.java
> +        return accessionRegisterDetailExternalService.getAccessionRegisterDetailStats(detailsSearchDto);
Tu peux ajouter un check de sanitizing sur **detailsSearchDto**

2021-12-17 14:36 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/summary/AccessionRegisterSummaryInternalService.java
> +            throw new InternalServerException("Unable to find accessionRegister Summaries", e);
on peut logger l'exception aussi

2021-12-17 14:36 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/AccessionRegisterInternalController.java
> +        return summaryInternalService.getAccessionRegisterDetailStats(vitamContext, detailsSearchDto);
des check sur **accessContractId** et **detailsSearchDto** à ajouter

2021-12-17 14:36 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/vitamui-common.module.ts
> +// import { LevelInputModule } from './components/editable-field/level-input/level-input.module';
commentaire à supprimer

2021-12-17 14:36 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/vitamui-common.module.ts
> +    // LevelInputModule,
à supprimer

2021-12-17 14:36 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/vitamui-common.module.ts
> +    // LevelInputModule,
idem

2021-12-17 14:36 UTC, oussamasic commented on ui/ui-frontend-common/src/sass/icons/vitamui-icons.css
> -
Il faut pas supprimer cette icone, c'est l'icone _corbeille_  qu'on utilise au niveau de certaines applications referentials

2021-12-17 14:36 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-list/accession-register-list.component.ts
> +  // Gestion de la recherche
à supprimer

2021-12-17 14:36 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-list/accession-register-list.component.ts
> +  // Gestion des filtres
les 2 commentaires à supprimer

2021-12-17 14:36 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register.component.ts
> +export class AccessionRegisterComponent extends SidenavPage<AccessionRegisterDetail> implements OnInit, OnDestroy {
pas besoin d'implémenter l'interface `OnDestroy` vu qu'on a pas de subscription.

2021-12-17 14:36 UTC, oussamasic commented on ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/AccessionRegisterController.java
> +        return detailsService.getAccessionRegisterDetailStats(buildUiHttpContext(), detailsSearchDto);
un controle de sanitizing sur `detailsSearchDto` à ajouter

2021-12-17 15:34 UTC, nabilm2i requested changes

2021-12-17 15:34 UTC, nabilm2i commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/summary/AccessionRegisterSummaryInternalService.java
> +            LOGGER.info("Error constructing vitam query");
LOGGER.debug?

2021-12-17 17:52 UTC, nabilm2i approved these changes

2021-12-20 09:55 UTC, depysk commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/summary/AccessionRegisterSummaryInternalService.java
> +            LOGGER.info("Error constructing vitam query");
Mis en error

2021-12-20 09:57 UTC, depysk commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register.component.ts
> +export class AccessionRegisterComponent extends SidenavPage<AccessionRegisterDetail> implements OnInit, OnDestroy {
Cette classe étends une autre classe qui effectue des souscriptions. Ondestroy appelle celui de la classe héritée

2021-12-20 09:58 UTC, depysk commented on ui/ui-frontend-common/src/sass/icons/vitamui-icons.css
> -
Merci ;)

2021-12-20 09:58 UTC, depysk commented on ui/ui-frontend-common/src/app/modules/vitamui-common.module.ts
> +    // LevelInputModule,
Code commenté supprimé

2021-12-20 09:58 UTC, depysk commented on ui/ui-frontend-common/src/app/modules/vitamui-common.module.ts
> +    // LevelInputModule,
Code commenté supprimé

2021-12-20 09:59 UTC, depysk commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/AccessionRegisterInternalController.java
> +        return summaryInternalService.getAccessionRegisterDetailStats(vitamContext, detailsSearchDto);
Merci CheckMarx. Sanitizer ajouté :)

2021-12-20 09:59 UTC, depysk commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/summary/AccessionRegisterSummaryInternalService.java
> +            throw new InternalServerException("Unable to find accessionRegister Summaries", e);
Logger ajouté

2021-12-20 09:59 UTC, depysk commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/AccessionRegisterExternalController.java
> +        return accessionRegisterDetailExternalService.getAccessionRegisterDetailStats(detailsSearchDto);
Merci CheckMarx. Sanitizer ajouté :)

2021-12-20 10:39 UTC, oussamasic approved these changes

2021-12-22 10:57 UTC, merged