Vas item 8638 ua update management rules
ProgrammeVitam/vitam-ui pull request #549
Opened 2021-11-19 14:57 UTC by oussamasic

2021-11-30 14:32 UTC, CouzinieAtCines approved these changes

2021-11-30 15:37 UTC, bbenaissa requested changes

2021-11-30 15:37 UTC, bbenaissa commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/VitamUiManagementMetadataAction.java
> +    String archiveUnitProfile;
private à ajouter

2021-11-30 15:37 UTC, bbenaissa commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/VitamUiRuleActions.java
> +    List<Map<String, VitamUiRuleCategoryAction>> add = new ArrayList<>();
private à ajouter

2021-11-30 15:37 UTC, bbenaissa commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/rest/RestApi.java
> +    public static final String MASSUPDATEUNITSRULES = "/units/rules";
mettre des _ dans le nom

2021-11-30 15:37 UTC, bbenaissa commented on api/api-archive-search/archive-search-external/src/test/java/fr/gouv/vitamui/archives/search/external/server/rest/ArchivesSearchExternalControllerTest.java
> +        String expectedResponse = new String();
ça sera mieux d'avoir une réponse comme 'expected_response'

2021-11-30 15:37 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rulesupdate/converter/RuleOperationsConverter.java
> +    public RuleOperationsConverter() {
Tu peux le remplacer par @noArgConstructor

2021-11-30 15:37 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rulesupdate/converter/RuleOperationsConverter.java
> +        if(vitamUiRuleActions != null && vitamUiRuleActions.getAddOrUpdateMetadata() != null) {
common if(vitamUiRuleActions != null)

2021-11-30 15:37 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
> +        LOGGER.info("Add Rules to UA final updateQuery : {}", updateQuery);
convert infor to debug

2021-12-01 13:24 UTC, bbenaissa approved these changes

2021-12-01 14:29 UTC, merged