[VAS] Initialize Ingest APP
ProgrammeVitam/vitam-ui pull request #56
Opened 2020-09-24 15:28 UTC by Mocteezuma

## Description

* Ajout du service Ingest ( api-ingest / ui-ingest / ... + Mise à jour de la conf de deploiement )
* Ajout de la fonctionnalité d'entrée de SIP
* Ajout de l'affichage des entrées récentes + Affichage des détails d'une entrée
* Changemnt du tenant de preuve de base ( Tenant 1 par défaut )
* Fix: Remplacement des logos Locarchives par des logos VITAM
* Fix suite à l'audit R12 (Ajout de Sanity Check, mise à jour de dépendances, ...)
* Fix d'un log affichant des information de session en base64
* Documentation sur l'initialisation de profils d'organisations.
* Documentation sur l'initialisation des catégories du portail

## Documentation:

Nouvelles Documentations:

Initialisation de profils d'organisations (customer-init.yml)
initialisation des catégories du portail
Connexion à une VM Vitam en mode dev

## Tests:

Des tests unitaires ont étés mis en place pour le nouveau code
Une recette manuelle à été effectuée sur l'application

## Migration:

Nouvelles applications et configurations liées dans mongo:
* Jouer les script mongo de 212_application_ref.js à 215_security.populate_certificates_ref.js

## Contributeur

VAS

2020-10-09 15:24 UTC, mamakh requested changes
Duplication classe logbook
Duplication API atr et manifest 

Ingest upload : synchrone de bout en bout ? ihm => api => vitam ? risque de timeout

Modification fichier application.properties de CAS

Pourquoi la présence de init_ingest_app_bdd ?
Aussi de https://github.com/ProgrammeVitam/vitam-ui/pull/56/files#diff-f34a18208fdf2ceeb67b74f24e9ccfc0

Pas de modififications de scripts réferentiels Mongo existants. Il faut en créer de nouveaux pour gérer la migration et le mongo init proprement
Supprimer les roles identity dans les nouveaux contextes de la base security

Pourquoi avoir regénéré tous les scripts dans dev-deployment ?
Nouveaux certificats dans tools/docker/mongo/pki/dev/certs à supprimer 
A supprimer https://github.com/ProgrammeVitam/vitam-ui/pull/56/files#diff-be400c45ff63a1197121ac4568001dde
https://github.com/ProgrammeVitam/vitam-ui/pull/56/files#diff-7fc4b681ed93c9d293520a77a0b00919
access-external-client.conf & ingest-external-client.conf utiliser des paths externes pour ne pas mettre des certificats liés à un partenaire ou un env de dev

UI-frontend : mini-logo-vitam à supprimer, ça casse le moteur de thèmes. Ce logo sera affiché sans possibilité de l'override comme la gestion du logo ?
à supprimer et à implémenter dans le cadre du moteur de thèmes
ingesta-pi.service.ts : /atr et /manifest déjà présent dans vitam-ui/ui/ui-frontend-common/src/app/modules/api/logbook-api.service.ts
Modification à remettre https://github.com/ProgrammeVitam/vitam-ui/pull/56/files#diff-f0a42480875d2549b6b578cc45c0063f

Modification A supprimer https://github.com/ProgrammeVitam/vitam-ui/pull/56/files#diff-d4322c3d2ba549ce9371e5b6649be02a

2020-10-09 15:24 UTC, mamakh commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/CasExternalController.java
> +        // FIXME 6880: Make another API point for superuser logout and keep an api point with "normal user" (authTokenOnly) logout
je n'ai pas compris la remarque. Tu peux m'en dire plus stp

2020-10-09 15:24 UTC, mamakh commented on api/api-iam/iam-internal/src/main/config/dev-vitam/access-external-client.conf
> +  - keyPath: keystore_ihm-demo.p12
ces fichiers de devs ne devraient pas être embarqué

2020-10-09 15:24 UTC, mamakh commented on api/api-iam/iam-internal/src/main/config/dev-vitam/access-external-client.conf
> +  - keyPath: keystore_ihm-demo.p12
Le commentaire vaut pour tous les fichiers dev-vitam

2020-10-09 15:24 UTC, mamakh commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/CasInternalController.java
> +        // FIXME 6880: Make another API point for superuser logout and keep an api point with "normal user" (authTokenOnly) logout
même question pour l'external

2020-10-09 15:24 UTC, mamakh commented on api/api-ingest/ingest-commons/src/main/java/fr/gouv/vitamui/ingest/common/dto/LogbookEventModel.java
> +public class LogbookEventModel {
à supprimer.
Déjà présent dans commons-vitam. LogbookEventDto

2020-10-09 15:24 UTC, mamakh commented on api/api-ingest/ingest-commons/src/main/java/fr/gouv/vitamui/ingest/common/dto/LogbookOperationDto.java
> +/**
à supprimer.
Déjà présent dans commons-vitam

2020-10-09 15:24 UTC, mamakh commented on api/api-ingest/ingest-commons/src/main/java/fr/gouv/vitamui/ingest/common/dto/LogbookOperationModel.java
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
Pourquoi ne pas utiliser une Dto pour les Log**Dto et Log*Model

2020-10-09 15:24 UTC, mamakh commented on api/api-ingest/ingest-commons/src/main/java/fr/gouv/vitamui/ingest/common/dto/LogbookOperationsResponseDto.java
> +
à supprimer.
Déjà présent dans commons-vitam

2020-10-09 15:24 UTC, mamakh commented on api/api-ingest/ingest-external-client/src/main/java/fr/gouv/vitamui/ingest/external/client/IngestExternalRestClient.java
> +    public ResponseEntity<Resource> downloadManifest(ExternalHttpContext context, String id) {
API existe déja avec LogbookExternalRestClient

2020-10-09 15:24 UTC, mamakh commented on api/api-ingest/ingest-external-client/src/main/java/fr/gouv/vitamui/ingest/external/client/IngestExternalRestClient.java
> +    public ResponseEntity<Resource> downloadATR(ExternalHttpContext context, String id) {
même remarque

2020-10-09 15:24 UTC, mamakh commented on api/api-ingest/ingest-external/pom.xml
> +        <!-- Hibernate -->
à supprimer

2020-10-09 15:24 UTC, mamakh commented on api/api-ingest/ingest-external/pom.xml
> +        <dependency>
copier coller ?

2020-10-09 15:24 UTC, mamakh commented on api/api-ingest/ingest-external/src/main/java/fr/gouv/vitamui/ingest/external/server/rest/IngestExternalController.java
> +    @GetMapping("/manifest" + CommonConstants.PATH_ID)
existe déjà avec LogbookExternalController dans iam-external

2020-10-09 15:24 UTC, mamakh commented on api/api-ingest/ingest-external/src/main/java/fr/gouv/vitamui/ingest/external/server/rest/IngestExternalController.java
> +    public ResponseEntity<Resource> downloadATR(final @PathVariable("id") String id) {
pareil

2020-10-09 15:24 UTC, mamakh commented on api/api-ingest/ingest-internal/pom.xml
> +        <!-- dependency>
à supprimer

2020-10-09 15:24 UTC, mamakh commented on api/api-ingest/ingest-internal/pom.xml
> +        <dependency>
à supprimer

2020-10-09 15:24 UTC, mamakh commented on api/api-ingest/ingest-internal/pom.xml
> +            <groupId>com.fasterxml.jackson.dataformat</groupId>
à supprimer

2020-10-09 15:24 UTC, mamakh commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/rest/IngestInternalController.java
> +    public ResponseEntity<Resource> exportManifest(
même remarque que sur l'external

2020-10-09 15:24 UTC, mamakh commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestInternalService.java
> +            LOGGER.info("The recieved stream size : " + path.getInputStream().available() + " is sent to Vitam");
on veut vraiment faire un envoi synchrone à vitam ?

2020-10-09 15:24 UTC, mamakh commented on cas/cas-server/run.sh
> +mvn clean package -DskipTests -P vitam
à enlever, ça risque de nous poser problème

2020-10-09 15:24 UTC, mamakh commented on cas/cas-server/src/main/resources/application.properties
> +cas.authn.accept.users=casuser::Mellon
pourquoi cette modification ?

2020-10-09 15:24 UTC, mamakh commented on deployment/roles/init_ingest_app_bdd/templates/ingest/01_ingest.js.j2
> +print("START 01_ingest.js");
Pourquoi ce script n'est pas dans la gestion des scripts actuels

2020-10-09 15:24 UTC, mamakh commented on deployment/roles/mongo_init/tasks/check_auth.yml
> +    # no_log: "{{ hide_passwords_during_deploy }}"
c'est fait exprès ?

2020-10-09 15:24 UTC, mamakh commented on deployment/scripts/mongod/1.0.0/01_iam_ref.js.j2
> +db.profiles.insert({
à déplacer dans un nouveau script

2020-10-09 15:24 UTC, mamakh commented on deployment/scripts/mongod/1.0.0/209_cas_services_ref.js.j2
> +	"_id" : NumberInt(4),
Pareil ici, un nouveau script

2020-10-09 15:24 UTC, mamakh commented on deployment/scripts/mongod/1.0.0/214_security_ref.js.j2
> +        "ROLE_GET_PROFILES", "ROLE_CREATE_PROFILES", "ROLE_UPDATE_PROFILES", "ROLE_DELETE_PROFILES",
copier coller, enlever les roles d'identity

2020-10-09 15:24 UTC, mamakh commented on ui/ui-frontend/projects/identity/src/app/customer/customer.component.html
> +          <img src="assets/mini-logo-vitam.png">Rechercher <strong>un Client, un Propriétaire</strong>
à supprimer et à réfléchir dans le cadre du moteur de thèmes

2020-10-09 15:24 UTC, mamakh commented on ui/ui-frontend/projects/ingest/src/app/core/api/ingest-api.service.ts
> +  downloadManifest(id: string): Observable<Blob> {
fonction déjà présent vitam-ui/ui/ui-frontend-common/src/app/modules/api/logbook-api.service.ts.
a supprimer

2020-10-09 15:24 UTC, mamakh commented on ui/ui-frontend/projects/ingest/src/app/core/api/ingest-api.service.ts
> +  downloadATR(id: string): Observable<Blob> {
fonction déjà présent vitam-ui/ui/ui-frontend-common/src/app/modules/api/logbook-api.service.ts.
a supprimer

2020-10-09 15:24 UTC, mamakh commented on ui/ui-frontend/projects/ingest/src/sass/login.scss
> +
pas utilisé à supprimer

2020-10-09 15:24 UTC, mamakh commented on ui/ui-frontend/tslint.json
> +    "ordered-imports": false,
à remettre

2020-10-09 15:24 UTC, mamakh commented on ui/ui-identity/${maven.multiModuleProjectDirectory}/ui/ui-frontend/package-lock.json
> +{
à supprimer

2020-10-09 15:24 UTC, mamakh commented on ui/ui-ingest/src/main/config/ui-ingest-application-recette.yml
> +    key-store: src/main/config/ui-ingest.jks
utiliser les certs de dev-deployment

2020-10-09 15:24 UTC, mamakh commented on ui/ui-ingest/src/main/java/fr/gouv/vitamui/ingest/rest/IngestController.java
> +    @ApiOperation(value = "download manifest for ingest operation")
A supprimer 
 cf vitam-ui/ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/rest/LogbookController.java

2020-10-09 15:24 UTC, mamakh commented on ui/ui-ingest/src/main/java/fr/gouv/vitamui/ingest/rest/IngestController.java
> +    public ResponseEntity<Resource> downloadATR(final @PathVariable("id") String id) {
A supprimer 
 cf vitam-ui/ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/rest/LogbookController.java

2020-10-09 15:24 UTC, mamakh commented on ui/ui-portal/${maven.multiModuleProjectDirectory}/ui/ui-frontend/package-lock.json
> +{
à supprimer

2020-10-23 11:57 UTC, Mocteezuma commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/CasExternalController.java
> +        // FIXME 6880: Make another API point for superuser logout and keep an api point with "normal user" (authTokenOnly) logout
Hello !
Je l'ai laissé comme ca pour le moment mais j'ai vu ce point d'API lorsque j'ai garé un bug sur du sanity check.

En l'occurence, on test que les variables en entrées ( ici authToken et superUser ) soient non nulles.

Le problème, c'est que le point d'api de logout qui à été fait sert dans deux cas différent et ne demandent pas les mêmes valeurs dans es deux cas:
* Dans un cas, le logout classique, il ne nécessite que le authToken de l'utilisateur à déconnecter.
* Dans le cas d'une subrofation, deux informations doivent être fournies: le authToken de l'utilisateur subrogé et du superUser à déconnecter.

J'ai pour le moment simplement laissé un FIXME en supprimant la vérification de la présence du superUser en paramètres, mais il serait certainement plus pérenne de faire deux points d'API différents en vérifiant dans un cas la présence de authToken seulement, et dans l'autre de superUser en plus.

2020-10-23 11:58 UTC, Mocteezuma commented on api/api-iam/iam-internal/src/main/config/dev-vitam/access-external-client.conf
> +  - keyPath: keystore_ihm-demo.p12
Effectivement, certainement un soucis lors des merge conflits, je modifie ca et j'ajoute de la documentation sur la génération de ces fichiers si c'est pas déjà fait.

2020-10-23 11:58 UTC, Mocteezuma commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/CasInternalController.java
> +        // FIXME 6880: Make another API point for superuser logout and keep an api point with "normal user" (authTokenOnly) logout
Même réponse du coup

2020-10-23 12:01 UTC, Mocteezuma commented on ui/ui-identity/${maven.multiModuleProjectDirectory}/ui/ui-frontend/package-lock.json
> +{
Effectivement, certainement un soucis lors des merge conflits

2020-10-23 12:01 UTC, Mocteezuma commented on ui/ui-portal/${maven.multiModuleProjectDirectory}/ui/ui-frontend/package-lock.json
> +{
Effectivement, certainement un soucis lors des merge conflits

2020-10-23 12:09 UTC, Mocteezuma commented on ui/ui-ingest/src/main/java/fr/gouv/vitamui/ingest/rest/IngestController.java
> +    @ApiOperation(value = "download manifest for ingest operation")
Je ne savais pas qu'ils existaient déjà, je peux effectivement les utiliser, mais ca ne me semble pas logique d'avoir des API de téléchargement d'ATR/Manifest (spécifique à l'ingest) dans la partie logbook.

Est-ce que ces points d'API sont utilisés actuellement par vitam-ui, en dehors des points d'API créés par cette PR ?

2020-10-23 12:10 UTC, Mocteezuma commented
@mamakh désolé j'étais en congés lorsque tu as répondu à la PR, du coup je ne te fais un retour que maintenant.

Je vais traiter les sujets que tu me remonte, mais j'ai tout de même laissé quelques questions et messages qui requiers un retour de ta part.

2020-10-23 12:16 UTC, Mocteezuma commented on ui/ui-ingest/src/main/config/ui-ingest-application-recette.yml
> +    key-store: src/main/config/ui-ingest.jks
Je vais voir ca ene ffet

2020-10-23 12:24 UTC, Mocteezuma commented on api/api-ingest/ingest-external/pom.xml
> +        <!-- Hibernate -->
En effet

2020-10-23 12:26 UTC, Mocteezuma commented on api/api-ingest/ingest-external/pom.xml
> +        <dependency>
Comment ca copier coller ?

2020-10-23 12:27 UTC, Mocteezuma commented on api/api-ingest/ingest-internal/pom.xml
> +        <dependency>
Certainement la récupération de ce qu'il y avait sur iam ou referential avant certaines grosses PR.

Peux tu me donner plus de contexte sur la suppression de cette partie ?
Ca a été remplacé par autre chose au passage à la java 11 ?

2020-10-23 12:31 UTC, Mocteezuma commented on deployment/roles/mongo_init/tasks/check_auth.yml
> +    # no_log: "{{ hide_passwords_during_deploy }}"
oups, non un test de debug, je le remet

2020-10-23 12:35 UTC, Mocteezuma commented on deployment/roles/init_ingest_app_bdd/templates/ingest/01_ingest.js.j2
> +print("START 01_ingest.js");
un mécompréenssion entre ce qui avait été fait avant le déplacement des script, ce qui à été décidé pour séparer les differents blocs dd'app (core vitam-ui / referential / ingest) et ce qui à été fait après le déplacement des scripts dans deployment/script/mongo.
Je regarde ca et je modifie ou je reviens vers toi au besoin

2020-10-23 12:37 UTC, Mocteezuma commented on deployment/scripts/mongod/1.0.0/209_cas_services_ref.js.j2
> +	"_id" : NumberInt(4),
Ceci est simplement un correctif sur le referential, car l'incrémantation (maxId + 1) provoquait des erreurs à l'initialisation.
Il n'y a aucune raison que ca soit un nouveau script.

2020-10-23 12:42 UTC, Mocteezuma commented on deployment/scripts/mongod/1.0.0/01_iam_ref.js.j2
> +db.profiles.insert({
De ce que j'ai pu voir tout les profils administrateur étaient initialisés dans ce fichier. Pourquoi le profil d'ingest serait à mettre dans un fichier séparé ?

Y a t-il de la doc pour expliquer ca et permettre d'éviter des mal comprendre le fonctionnement des scripts dans le futur ?

2020-10-23 12:43 UTC, Mocteezuma commented on deployment/scripts/mongod/1.0.0/214_security_ref.js.j2
> +        "ROLE_GET_PROFILES", "ROLE_CREATE_PROFILES", "ROLE_UPDATE_PROFILES", "ROLE_DELETE_PROFILES",
En effet, je corrige

2020-10-23 12:44 UTC, Mocteezuma commented on cas/cas-server/src/main/resources/application.properties
> +cas.authn.accept.users=casuser::Mellon
Je l'ai pas vu passer, je recoupe en interne

2020-11-03 12:24 UTC, mamakh commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/CasExternalController.java
> +        // FIXME 6880: Make another API point for superuser logout and keep an api point with "normal user" (authTokenOnly) logout
okay merci pour le retour

2020-11-03 12:25 UTC, mamakh commented on ui/ui-identity/${maven.multiModuleProjectDirectory}/ui/ui-frontend/package-lock.json
> +{
le package lock est important, à ne surtout pas mettre dans le gitignore

2020-11-03 12:26 UTC, mamakh commented on api/api-ingest/ingest-external/pom.xml
> +        <dependency>
les dépendances pac4j ne sont pas utilisés au niveau de votre external non ?
Je me trompe peut-être. DU coup je pensais que les dépendances avaient été ajoutés à la suite d'un copier/coller de pom.xml

2020-11-03 12:28 UTC, mamakh commented on api/api-ingest/ingest-internal/pom.xml
> +        <dependency>
La dépendance a du sens dans d'autres modules style iam ou on fait des traitements samlv2 mais pas ici

2020-11-03 12:33 UTC, mamakh commented on deployment/scripts/mongod/1.0.0/01_iam_ref.js.j2
> +db.profiles.insert({
Les scripts sont versionnés et numérotés. cf https://github.com/ProgrammeVitam/vitam-ui/blob/vas_init_ingest/tools/docker/mongo/README.md#templatage-des-scripts-de-db
Une moulinette a été mis en place pour 

Tout script déjà joué en prod, ne le sera pas même s'il a été modifié.
Logiquement s'il y a des modifications de bdd, ils doivent être sur des scripts distincts et ne doivent pas toucher aux scripts existants

2020-11-03 12:35 UTC, mamakh commented on deployment/scripts/mongod/1.0.0/209_cas_services_ref.js.j2
> +	"_id" : NumberInt(4),
Même remarque qu'en haut, aucun script existant ne doit être modifié, tout ajout ou modification sur la bdd doit être sur un nouveau script.
Et le max doit bien être traité pour que ça fonctionne sur des bases de données déjà initialisées.
Il ne faut pas oublier qu'il y a des entités avec de la prod derrière

2020-11-03 12:37 UTC, mamakh commented on ui/ui-ingest/src/main/java/fr/gouv/vitamui/ingest/rest/IngestController.java
> +    @ApiOperation(value = "download manifest for ingest operation")
oui ça peut se disctuer pour les API /atr et /manifest.
ces API sont utilisés chez Xelians

2020-11-03 12:37 UTC, mamakh commented on ui/ui-portal/${maven.multiModuleProjectDirectory}/ui/ui-frontend/package-lock.json
> +{
le package lock est important, à ne surtout pas mettre dans le gitignore

2020-11-03 12:38 UTC, mamakh commented
Retours effectués pour les commentaires

2020-11-03 12:47 UTC, Mocteezuma commented on ui/ui-portal/${maven.multiModuleProjectDirectory}/ui/ui-frontend/package-lock.json
> +{
Du coup j'ai pas compris ce que tu veux que je supprime ?

2020-11-03 12:54 UTC, Mocteezuma commented on deployment/scripts/mongod/1.0.0/01_iam_ref.js.j2
> +db.profiles.insert({
Bah oui mais on a pas encore de version releasé sur Vitam-ui a ce que j'en sais ? Je vais pas faire un script de migration vers la même version si ?
Pour moi on est toujours sur la stabilisation de la 1.0.0, mais il est vrai que la question de release / version de vitam-ui est un sujet encore en discussion sur le projet global.
En tout cas je prend note de ta remarque et je recoupe en interne.

2020-11-03 12:56 UTC, Mocteezuma commented on deployment/scripts/mongod/1.0.0/209_cas_services_ref.js.j2
> +	"_id" : NumberInt(4),
1) Déjà le maxId ne fonctionne pas bien, je peux t'en parler si besoin à l'oral pour plus de détails.Je vais pas laisser en place un script qui ne fonctionne pas même si c'est un vieux script... un bug fix c'est un bug fix....

2) Je l'ai déjà dit plus haut mais actuelement je n'ai pas souvenir qu'on ait releasé vitamui, pourquoi s'embeter a faire des versions differentes de script pour une version de vitamui qui est la même ? Et aussi comment ? Je suis sensé faire des 1.0.1-fix_56 ?

2020-11-30 15:13 UTC, Mocteezuma commented
Comme vu ensemble, les modifications ont étés apportés:

Suppression des point d'API /atr et /manifest de ingest pour utiliser les point d'API common.

Suppression de doublon sur LogbookDto et ses dérivés + adaptations du LogbookDto original (de common)

Suppression de certaines erreurs:
* Modification fichier application.properties de CAS
* Ajout d'un commentaire dans un fichier ansiblerie
* ajout de package-lock.json créés par maven

Suppression des fichiers de conf dev des differents projets ( revenus du a une mauvaise gestion de conflit suite a la création de dev-deployment ).

2020-12-02 10:54 UTC, mamakh approved these changes
Quelques petites modifications sinon okay dans l'ensemble.
Un point d'attention sur le formatter sur les classes JAVA.
Et un autre point d'attention sur les tailles de SIP. Combien de Mo ou de Go sont permis sur les SIP ? Et jusqu'à combien vous avez fait les tests ?

2020-12-02 10:54 UTC, mamakh commented on .gitignore
> +api/api-referential/referential-internal/src/main/config/dev-vitam/*
Ligne déjà présente voir L 235

2020-12-02 10:54 UTC, mamakh commented on .gitignore
> +api/api-referential/referential-internal/src/main/config/dev-vitam/*
à supprimer

2020-12-02 10:54 UTC, mamakh commented on api/api-iam/iam-internal/src/main/config/customer-init.yml
> +      description: Gestion des application de dépot et suivi des versements
à corriger mettre un 's' à application

2020-12-02 10:54 UTC, mamakh commented on api/api-iam/iam-internal/src/main/config/customer-init.yml
> +      description: Gestion des application de dépot et suivi des versements
dépôt

2020-12-02 10:54 UTC, mamakh commented on api/api-iam/iam-internal/src/main/config/customer-init.yml
> +      description: Gestion des application de dépot et suivi des versements
Fautes d'orthographe : **ajouter un 's' à application** et changer dépot en **dépôt**

2020-12-02 10:54 UTC, mamakh commented on api/api-ingest/ingest-external/src/main/java/fr/gouv/vitamui/ingest/external/server/rest/IngestExternalController.java
> +            LOGGER.debug("ERROR: InputStream error ", e);
Plutot un Logger.error non ?

2020-12-02 10:54 UTC, mamakh commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/rest/IngestInternalController.java
> +@Api(tags = "ingest", value = "Ingest an SIP", description = "Ingest an SIP")
Ingest a SIP

2020-12-02 10:54 UTC, mamakh commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestInternalService.java
> +            LOGGER.info("The recieved stream size : " + path.getInputStream().available() + " is sent to Vitam");
recieved => **received**

2020-12-02 10:54 UTC, mamakh commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestInternalService.java
> +            LOGGER.info("The recieved stream size : " + path.getInputStream().available() + " is sent to Vitam");
je pense que c'est mieux de le mettre en debug

2020-12-02 10:54 UTC, mamakh commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
> -import java.util.ArrayList;
attention au formatter, les static doivent être avant les imports classiques.
Un point d'attention sur vos prochains devs également

2020-12-02 10:54 UTC, mamakh commented on deployment/roles/vitamui/files/customer-init.yml
> +      description: Gestion des application de dépot et suivi des versements
```suggestion
      description: Gestion des applications de dépôt et suivi des versements
```

2020-12-02 10:54 UTC, mamakh commented on deployment/roles/vitamui/files/customer-init.yml
> +    - name: PROFIL_INGEST_TENANT
Ce nom apparaît au niveau de l'interface par exemple l'ajout de groupe de profils ou la modification, là ça fait un peu trop technique

2020-12-02 10:54 UTC, mamakh commented on deployment/scripts/mongod/1.0.0/01_iam_ref.js.j2
> +db.profiles.insert({
toujours d'actualité, fichier à déplacer

2020-12-02 10:54 UTC, mamakh commented on deployment/scripts/mongod/1.0.0/101_iam_system_demo.js
> +        "system_logbook_operation_profile",
à déplacer dans un nouveau script

2020-12-02 10:54 UTC, mamakh commented on api/api-iam/iam-internal/src/main/config/customer-init.yml
> +      description: Gestion des application de dépot et suivi des versements
```suggestion
      description: Gestion des applications de dépôt et suivi des versements
```

2020-12-02 10:54 UTC, mamakh commented on api/api-iam/iam-internal/src/main/config/customer-init.yml
> +    - name: Profil Ingest
Utiliser un nom plus fonctionnel et pas technique.
Ce nom sera visible lors de la création de groupe ou sa modification

2020-12-08 09:56 UTC, bbenaissa approved these changes

2020-12-10 09:35 UTC, mamakh requested changes
Petite correction sur le fichier d'init
Une autre correction sur les scripts.
Sinon tout le reste à l'air bon

1. Fichier d'init 

Il y a des différences entre les fichiers init de dev et de déploiement.
Je proposerai peut-être une PR pour utiliser un fichier unique pour éviter les décalages. 

/home/makhtar/code/locarchives/clone/vitam-ui/deployment/roles/vitamui/files/customer-init.yml
/home/makhtar/code/locarchives/clone/vitam-ui/api/api-iam/iam-internal/src/main/config/customer-init.yml

1e fichier : 
`   
      - name: Profil pour le dépôt et suivi des versements
      description: Gestion des applications de dépôt et suivi des versements
      app-name: INGEST_MANAGEMENT_APP
      level:
      roles:
        - ROLE_GET_INGEST
        - ROLE_CREATE_INGEST
        - ROLE_GET_ALL_INGEST
`

2e fichier : 
'
    - name: Profil pour le dépôt et suivi des versements
      description: Gestion des applications de dépôt et suivi des versements
      app-name: INGEST_APP
      level:
      roles:
        - ROLE_GET_INGEST
        - ROLE_CREATE_INGEST
        - ROLE_GET_ALL_INGEST
'
à corriger

2. Séparation entre script '_ref.js 'et script '_demo.js'

2020-12-10 09:39 UTC, mamakh commented on deployment/scripts/mongod/1.0.0/212_application_ref.js.j2
> +    {
Ceci est une donnée de démo. A déplacer dans un fichier '_demo.js'
Tous les fichiers '_ref.js' correspondent aux données installées sur tous les environnements

2020-12-10 15:26 UTC, mamakh approved these changes

2020-12-14 15:09 UTC, merged