[CEA] Mise en place des règles de gestion
ProgrammeVitam/vitam-ui pull request #60
Opened 2020-11-23 16:54 UTC by mamak-smile

## Description

Cette PR contient les développements permettant la mise en place des règles de gestion.

Les sujets traités sont les suivants :

**Règles de gestion :**

* 19789 - Accéder au référentiel des règles de gestion
* 19806 - Créer une règle de gestion
* 19807 - Rechercher une règle de gestion
* 19808 - Consulter et/ou mettre à jour une règle de gestion
* 19809 - Exporter le référentiel des règles de gestion
* 19813 - Supprimer une règle de gestion

**Le mécanisme d'import via fichier CSV (#19812) sera embarqué dans une future PR**

## Type de changement:
Code et/ou Configuration : Ajout de nouvelles fonctionnalités

## Tests:

Tests unitaires
Tests d'intégration
Recette sur environnement Smile

## Contributeur

Commissariat à l'énergie atomique et aux énergies alternatives (CEA)

2020-12-02 14:14 UTC, mamakh requested changes
Concernant cette PR, il y a quelques modifications à apporter.
L'utilisation du logo vitamui-logo-small.png doit être supprimée.
Ce logo ne fais pas parti du moteur de thèmes. Une entité Xelians, CEA ou autres ne peut pas surcharger cette image au déploiement.
cf : <img src="assets/vitamui-logo-small.png">

vitamui-library est bcp utilisée, cette librairie est en doublon avec ui-frontend-common et à vocation à disparaitre.
Toutes les icones copiées doivent restées dans ui-frontend-common, définies dans [Figma](figma.com/file/m5EfQ0suI0YGr8oqLih0NL/Design-System-Vitam-UI?node-id=93%3A1).
Si ces icones manquent dans ui-frontend-common, il faut les ajouter.
S'assurer également de leurs présences dans Figma. Une grosse refonte graphique ets en cours chez Xelians, les icones non présentes risque de disparaitre

2020-12-02 14:14 UTC, mamakh commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamRuleService.java
> +    /**
fondre cette classe dans celle là qui existe déjà https://github.com/ProgrammeVitam/vitam-ui/blob/8c308c15a124d26cf6ded83c46f92c69cf5c70aa/commons%2Fcommons-vitam%2Fsrc%2Fmain%2Fjava%2Ffr%2Fgouv%2Fvitamui%2Fcommons%2Fvitam%2Fapi%2Fadministration%2FRuleService.java

2020-12-02 14:14 UTC, mamakh commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/RuleExternalService.java
> +            result.getValues().stream().map(element -> converterToExternalDto(element)).collect(Collectors.toList()),
pourquoi les values sont retraités ? 
Quelles sont les informations qui ne sont pas remontées ?

2020-12-02 14:14 UTC, mamakh commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rule/RuleInternalService.java
> +                return null;
faudrait pas plutot renvoyer un NotFoundException ?

2020-12-02 14:14 UTC, mamakh commented on deployment/scripts/mongod/1.0.0/101_iam_system_demo.js
> +        "system_logbook_operation_profile"
à mettre dans un nouveau script

2020-12-02 14:14 UTC, mamakh commented on deployment/scripts/mongod/1.0.0/208_application_ref.js.j2
> -db.applications.insert({
ajouter un script de suppression de ce profil dans Mongo deleteOne dans un autre fichier

2020-12-02 14:14 UTC, mamakh commented on deployment/scripts/mongod/1.0.0/307_iam_ref.js.j2
> +db.profiles.insert({
Tenant auto est un tenant de test.
A supprimer

2020-12-02 14:14 UTC, mamakh commented on deployment/scripts/mongod/1.0.0/307_iam_ref.js.j2
> +            	"auto_system_rules"
meme commentaire qu'au dessus

2020-12-02 14:14 UTC, mamakh commented on integration-tests/README.md
> +Par exemple, l'exécution des tests d'intégration Flow back-end nécessite : Flow external, Flow internal, Flow referential, IAM external, IAM internal, CAS, et Security
```suggestion
Par exemple, l'exécution des tests d'intégration Referential back-end nécessite : Referential external, Referential internal, IAM external, IAM internal, CAS, et Security
```

2020-12-02 14:14 UTC, mamakh commented on ui/ui-frontend/projects/referential/src/app/access-contract/access-contract.component.html
> +          <img src="assets/vitamui-logo-small.png">Paramétrer mes <strong>Contrats d'accès</strong>
logo à supprimer. Ne fais pas parti du moteur de thèmes.
Une entité ne peut pas surcharger cette image au déploiement

2020-12-02 14:14 UTC, mamakh commented on ui/ui-frontend/projects/referential/src/app/admin-dsl/admin-dsl.component.html
> +          <img src="assets/vitamui-logo-small.png">Recherche par <strong>Requêtes DSL</strong>
logo à supprimer. Ne fais pas parti du moteur de thèmes.
Une entité ne peut pas surcharger cette image au déploiement

2020-12-02 14:14 UTC, mamakh commented on ui/ui-frontend/projects/referential/src/app/agency/agency.component.html
> +          <img src="assets/vitamui-logo-small.png">Paramétrer les <strong>Services Agents</strong>
logo à supprimer. Ne fais pas parti du moteur de thèmes.
Une entité ne peut pas surcharger cette image au déploiement

2020-12-02 14:14 UTC, mamakh commented on ui/ui-frontend/projects/referential/src/app/audit/audit.component.html
> +                    <img src="assets/vitamui-logo-small.png">Paramétrer mes <strong>Audits</strong>
logo à supprimer. Ne fais pas parti du moteur de thèmes.
Une entité ne peut pas surcharger cette image au déploiement

2020-12-02 14:14 UTC, mamakh commented on ui/ui-frontend/projects/referential/src/app/context/context.component.html
> +          <img src="assets/vitamui-logo-small.png">Paramétrer les <strong>Contextes Applicatifs</strong>
logo à supprimer. Ne fais pas parti du moteur de thèmes.
Une entité ne peut pas surcharger cette image au déploiement

2020-12-02 14:14 UTC, mamakh commented on ui/ui-frontend/projects/referential/src/app/file-format/file-format.component.html
> +          <img src="assets/vitamui-logo-small.png">Paramétrer les <strong>Formats de Fichiers</strong>
logo à supprimer. Ne fais pas parti du moteur de thèmes.
Une entité ne peut pas surcharger cette image au déploiement

2020-12-02 14:14 UTC, mamakh commented on ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract.component.html
> +                    <img src="assets/vitamui-logo-small.png">Paramétrer mes <strong>Contrats d’entrée</strong>
logo à supprimer. Ne fais pas parti du moteur de thèmes.
Une entité ne peut pas surcharger cette image au déploiement

2020-12-02 14:14 UTC, mamakh commented on ui/ui-frontend/projects/referential/src/app/ontology/ontology.component.html
> +          <img src="assets/vitamui-logo-small.png">Paramétrer les <strong>Ontologies</strong>
logo à supprimer. Ne fais pas parti du moteur de thèmes.
Une entité ne peut pas surcharger cette image au déploiement

2020-12-02 14:14 UTC, mamakh commented on ui/ui-frontend/projects/referential/src/app/probative-value/probative-value.component.html
> +                    <img src="assets/vitamui-logo-small.png">Rechercher mes <strong>Relevés de valeur probante</strong>
logo à supprimer. Ne fais pas parti du moteur de thèmes.
Une entité ne peut pas surcharger cette image au déploiement

2020-12-02 14:14 UTC, mamakh commented on ui/ui-frontend/projects/referential/src/app/rule/rule-create/rule-create.component.scss
> +        color: #a5a5a5;
pourquoi cette couleur en dure ?

2020-12-02 14:14 UTC, mamakh commented on ui/ui-frontend/projects/referential/src/app/rule/rule.component.html
> +                    <img src="assets/vitamui-logo-small.png">Paramétrer les <strong>Règles de gestion</strong>
logo à supprimer. Ne fais pas parti du moteur de thèmes.
Une entité ne peut pas surcharger cette image au déploiement

2020-12-02 14:14 UTC, mamakh commented on ui/ui-frontend/projects/referential/src/app/securisation/securisation.component.html
> +                    <img src="assets/vitamui-logo-small.png">Paramétrer mes <strong>Opérations de securisations</strong>
logo à supprimer. Ne fais pas parti du moteur de thèmes.
Une entité ne peut pas surcharger cette image au déploiement

2020-12-02 14:14 UTC, mamakh commented on ui/ui-frontend/projects/referential/src/app/security-profile/security-profile.component.html
> +          <img src="assets/vitamui-logo-small.png">Paramétrer les <strong>Profils de Sécurité</strong>
logo à supprimer. Ne fais pas parti du moteur de thèmes.
Une entité ne peut pas surcharger cette image au déploiement

2020-12-03 07:26 UTC, Mocteezuma commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamRuleService.java
> +        fr.gouv.vitamui.commons.vitam.api.dto.LogbookOperationsResponseDto lastImportOperation = VitamRestUtils.responseMapping(lastImportOperationResponse.toJsonNode(), LogbookOperationsResponseDto.
Pourquoi on a le package de la classe `LogbookOperationsResponseDto` ici ?

2020-12-03 07:26 UTC, Mocteezuma commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamRuleService.java
> +            final List<String> contextRuleIds = checkRules.stream().map(context -> context.getRuleId()).collect(Collectors.toList());
Je suis pas certain de pourquoi on a des variables `contextResponseDto`, `contextRuleIds` et `context` (dans le stream) ?
On est d'accord qu'on devrais plustôt avoir des  `rulesResponse`, `rule` (dans le stream) et `rulesIds` (la liste de string) ?

2020-12-03 07:26 UTC, Mocteezuma commented on deployment/scripts/mongod/1.0.0/208_application_ref.js.j2
> -
Pourquoi veut-on supprimer ce profil ?

2020-12-03 07:26 UTC, Mocteezuma commented on integration-tests/README.md
> +Par exemple, l'exécution des tests d'intégration Flow back-end nécessite : Flow external, Flow internal, Flow referential, IAM external, IAM internal, CAS, et Security
Flow est (si je ne me trompe pas) un des modules de DLab/XAM qui n'a pas été partagé à la communauté.
Je pense que ce bout de code restant est une erreur, un bout non retiré.
Cependant tu peut le remplacer par referential à la place.

2020-12-07 15:58 UTC, mamak-smile commented on deployment/scripts/mongod/1.0.0/208_application_ref.js.j2
> -
Petite erreur de notre part lorsque nous avons rejoué nos commits en cherry-pick après avoir mis à jour notre branche develop avec les derniers developpements de vitadmin.

Cette modification sera annulée lors de nos corrections.

2020-12-07 16:05 UTC, mamak-smile commented on deployment/scripts/mongod/1.0.0/101_iam_system_demo.js
> +        "system_logbook_operation_profile"
C'est une simple correction de typo (je viens de constater que Bénédicte a fait un [commit](https://github.com/ProgrammeVitam/vitam-ui/commit/d47d5504497e399262c1e208d7ed9860a0a61869) qui embarque la même correction sur la branche develop)

Cette ligne correspond à la gestion des journaux d'opération, et a été ajoutée à la base par @nabilm2i 
Faut-il réellement la déplacer dans un autre script ?

2020-12-11 11:50 UTC, pimenta-cines approved these changes

2020-12-15 14:54 UTC, mamak-smile commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamRuleService.java
> +    /**
Cette classe a besoin d'appeler le VitamQueryHelper dans le projet api-referential / referential-commons, il n'est donc pas possible de refondre toute la classe dans celle qui existe déjà dans commons-vitam.

Je constate que la plupart des applis referential ont deux services qui co-existent (AgencyService / VitamAgencyService, IngestContractService / IngestContractService, etc) dans api-referential et commons-vitam.

Nous allons laisser en l'état.

2020-12-15 14:56 UTC, mamak-smile commented on ui/ui-frontend/projects/referential/src/app/rule/rule-create/rule-create.component.scss
> +        color: #a5a5a5;
J'ai repris le même fichier css que pour l'application "file-format"

2020-12-15 15:36 UTC, mamak-smile commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rule/RuleInternalService.java
> +                return null;
J'ai repris le même fonctionnement que tous les autres InternalService du referential-internal

2020-12-15 15:48 UTC, mamak-smile commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamRuleService.java
> +            final List<String> contextRuleIds = checkRules.stream().map(context -> context.getRuleId()).collect(Collectors.toList());
Je n'ai pas bien compris ce commentaire.

- J'ai la liste de toutes les règles (RequestResponse<FileRulesModel> vitamRules) que je met dans un RuleNodeResponseDto pour pouvoir les manipuler facilement
- J'ai la liste des règles que je veux vérifier (final List<FileRulesModel> checkRules) dont j'extrais la liste des ids.

-  Dans mon stream je parcours la liste de toutes les règles existantes, et pour chaque règle existante je regarde si son id est dans la liste des règles à vérifier


Que faudrait-il modifier exactement ?

2020-12-31 10:52 UTC, youcefxelians commented on ui/ui-frontend/projects/referential/src/app/rule/rule-create/rule-create.component.scss
> +        color: #a5a5a5;
Il est préférable d'utiliser la palette de couleurs existante.
Le nouveau thème est PR. ça simplifiera grandement les choses.

2020-12-31 10:56 UTC, youcefxelians commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rule/RuleInternalService.java
> +                return null;
Il est préférable d'utiliser des exceptions afin de laisser les handlers opérer à mon avis.
ça permet aussi de supprimer le else.

2021-01-04 08:39 UTC, Mocteezuma commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamRuleService.java
> +            final List<String> contextRuleIds = checkRules.stream().map(context -> context.getRuleId()).collect(Collectors.toList());
Hello !

Je parle simplement du nom des variables qui ne me semblent pas approprié et donc peut ralentir la comprehension du code.

2021-01-04 08:40 UTC, Mocteezuma commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rule/RuleInternalService.java
> +                return null;
Dans ce cas, il faudra aussi adapter les autres services existants ( dans une PR séparée bien entendu ) pour que le code soit le plus homogène possible.

2021-01-04 08:42 UTC, Mocteezuma commented on ui/ui-frontend/projects/referential/src/app/rule/rule-create/rule-create.component.scss
> +        color: #a5a5a5;
Le nouveau moteur de thème n'étant pas encore présent pourquoi demander une modifications qui le concerne (si j'ai bien compris le soucis) ?
En revanche, effectivement ce gris doit déjà exister en variable dans le colors.css si je ne dis pas de bétises, il serait plus judicieux de le réutiliser, et ensuite de modifier tout les CSS utilisant la variable pour reprendre celle du nouveau moteur quand il sera mergé.

2021-01-04 13:17 UTC, youcefxelians commented on ui/ui-frontend/projects/referential/src/app/rule/rule-create/rule-create.component.scss
> +        color: #a5a5a5;
Ma demande concernait uniquement l'utilisation des couleurs existantes ou de garder le même fonctionnement si on souhaite ajouter des nouvelles :)
J'ai fait référence au nouveau thème juste à titre informationnel :). Bien entendu, les modifications concernant le nouveau thème ne sont pas l'objet de cette PR.

2021-01-12 14:22 UTC, mamak-smile commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamRuleService.java
> +            final List<String> contextRuleIds = checkRules.stream().map(context -> context.getRuleId()).collect(Collectors.toList());
J'ai fais un petit refactor des noms des variables, ça devrait être un peu plus clair maintenant !

2021-01-13 10:10 UTC, mamak-smile commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rule/RuleInternalService.java
> +                return null;
A voir dans une future PR donc

2021-01-13 10:59 UTC, mamak-smile commented on ui/ui-frontend/projects/referential/src/app/rule/rule-create/rule-create.component.scss
> +        color: #a5a5a5;
Cette couleur est actuellement définie unitairement pour chaque app, et n'est pas définie dans le colors.css.
Il me semble judicieux d'attendre la mise en place du nouveau thème pour effectuer ces modifications, lors d'une autre PR.

2021-01-13 11:30 UTC, Mocteezuma approved these changes

2021-01-14 14:02 UTC, merged