Ajout du modèle provider OIDC
ProgrammeVitam/vitam-ui pull request #608
Opened 2022-01-11 15:04 UTC by leleuj

Cette PR est une évolution du modèle de données `IdentityProvider` pour pouvoir ajouter des providers OIDC en plus des providers SAML et internes.

Cette PR est décorrélée de l'upgrade du serveur CAS en v6.4.

Deux points sont ajustables:
- pour la création d'un `IdentityProvider` OIDC, le logbook trace le `clientId` et la `discoveryUrl`
- au niveau logbook, seul le secret client parmi les informations OIDC est caché.

2022-01-15 20:05 UTC, bbenaissa requested changes

2022-01-15 20:05 UTC, bbenaissa commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/idp/converter/IdentityProviderConverter.java
>          provider.setSpMetadata(spMetadata);
Une affectation directe sans créer une nouvelle variable

2022-01-15 20:05 UTC, bbenaissa commented on api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/idp/converter/IdentityProviderConverterTest.java
> +        Map<String, String> customParams = new HashMap<>();
on peut créer une map avec des valeurs sans initialser une variable

2022-01-15 20:05 UTC, bbenaissa commented on api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/idp/converter/IdentityProviderConverterTest.java
> +        idp.setClientId("id");
Je sais que c'est une dette  précedente, mais c'est mieux de créer des consts

2022-01-15 20:05 UTC, bbenaissa commented on api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/idp/converter/IdentityProviderConverterTest.java
> +        customParams.put("prompt", "none");
Meme remarque pour la map

2022-01-17 08:24 UTC, leleuj commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/idp/converter/IdentityProviderConverter.java
>          provider.setSpMetadata(spMetadata);
Je ne comprends pas ta remarque

2022-01-17 08:25 UTC, leleuj commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/idp/converter/IdentityProviderConverter.java
>          provider.setSpMetadata(spMetadata);
Ah je pense que j'ai compris

2022-01-17 08:25 UTC, leleuj commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/idp/converter/IdentityProviderConverter.java
>          provider.setSpMetadata(spMetadata);
OK

2022-01-17 08:27 UTC, leleuj commented on api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/idp/converter/IdentityProviderConverterTest.java
> +        Map<String, String> customParams = new HashMap<>();
OK

2022-01-17 08:27 UTC, leleuj commented on api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/idp/converter/IdentityProviderConverterTest.java
> +        customParams.put("prompt", "none");
OK

2022-01-17 08:29 UTC, leleuj commented on api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/idp/converter/IdentityProviderConverterTest.java
> +        idp.setClientId("id");
OK

2022-01-17 09:23 UTC, leleuj commented
@bbenaissa la PR a été mise à jour par rapport à tes commentaires

2022-01-17 09:41 UTC, bbenaissa approved these changes

2022-01-18 14:27 UTC, jbricout007 commented
Tag "enhancement" retiré car fonction embarqué dans une autre PR

2022-01-18 14:37 UTC, closed without merging