[VAS] ITEM 8101 : add computed inherited rules function
ProgrammeVitam/vitam-ui pull request #624
Opened 2022-01-21 13:49 UTC by oussamasic

## Description
L'objectif de cette PR est  d'ajouter une nouvelle fonctionnalité au niveau de l'application "Recherche et consultation des archives", cette nouvelle fonctionnalité permet de demander immédiatement le calcul des règles héritées
[Ticket TuleUp](https://tuleap.dev.programmevitam.fr/plugins/tracker/?aid=8101)

## Type de changement:
* Nouveau Code 
* Re-factorisation de code

## Documentation:

## Tests:
- Des tests fonctionnels sont effectués pour vérifier le fonctionnement de cette évolution.
- Des test JAVA sont ajoutés.

## Migration:
- Ajout des modifications au niveau de la DB, 
- Pas de migration.

## Checklist:
[X] Mon code suit le style de code de ce projet.
[X] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.
[X] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.
[X] Les tests unitaires nouveaux et existants passent avec succès localement.

## Contributeur
Vitam Accessible en Service (VAS)

2022-02-01 11:20 UTC, bbenaissa requested changes

2022-02-01 11:20 UTC, bbenaissa commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/rest/RestApi.java
> +    public static final String COMPUTED_INHERITED_RULES = "/computed-inherited-rules";
"computed" signifie que les règles ont calculés, ça sera mieux de changer le end point : par exemple: launch-inheritance-rules ou compute-inheritance-rules

2022-02-01 11:20 UTC, bbenaissa commented on api/api-archive-search/archive-search-external-client/src/main/java/fr/gouv/vitamui/archives/search/external/client/ArchiveSearchExternalRestClient.java
> +    public ResponseEntity<String> computedInheritedRules(SearchCriteriaDto searchCriteriaDto,
même remarque que les noms de méthodes

2022-02-01 11:20 UTC, bbenaissa commented on api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/rest/ArchivesSearchExternalController.java
> +    @Secured(ServicesData.ROLE_COMPUTED_INHERITED_RULES)
Même remarque que le rôle

2022-02-01 11:20 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
> +            Lancer le calcul d'héritage
à traduire et remplacer par des clés

2022-02-02 08:42 UTC, nabilm2i commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/rest/RestApi.java
> +    public static final String COMPUTED_INHERITED_RULES = "/computed-inherited-rules";
le nom d'API côté vitam s'appelle `computedInheritedRules`

2022-02-02 11:11 UTC, nabilm2i approved these changes

2022-02-04 13:10 UTC, bbenaissa approved these changes

2022-02-04 13:28 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
> +            Lancer le calcul d'héritage
Done

2022-02-04 13:28 UTC, merged