[CINES][PASTIS] Archival profile edition
ProgrammeVitam/vitam-ui pull request #628
Opened 2022-01-21 17:24 UTC by naji-cines

### Description

Ajout de fonctionnalité d'édition de profil d'archivage et de profil d"unité archivistique.
 - affichage des PA et PUA de l'instance de VITAM
 - création / modification de la notice associé au profil d'archivage (JSON)
 - création / modification du profil d'archivage (RNG)
 - création / modification de profil d'unité archivistique (JSON)
 - édition des règles des PA et PUA

### Deux projets principaux
#### api-pastis
C'est le back-end de Pastis  composé de 4 projets :
 - pastis : back spring (Pastis controller, Sécurité)
 - pastis-commons (DTO, manipulation du RNG, manipulation du JSON)
 - pastis-client : interface de l'api pastis
 - pastis-standalone : projet utilisé pour construire la version standalone de pastis

#### Le front
Composé de  : 
 - ui-pastis le gateway
 - ui-frontend/project/pastis l'application Angular

### Des ajouts dans le projet api-referential
Essentiellement pour manipuler (CRUD) les notices, PA et PUA de VITAM.

### Des ajouts dans la procédure de déploiement (playbook). Pas complètement testés.
 - modification de playbook
 - ajout de templates
 - scripts Mongo pour ajouter Pastis
 - ajout des certificats de pastis dans Mongo

### Tests
Un certain nombre de tests unitaires réalisés mais sans couverture exhaustive.

2022-02-08 08:39 UTC, bbenaissa requested changes

2022-02-08 08:39 UTC, bbenaissa commented on api/api-pastis/pastis-client/pom.xml
> +            <version>5.0-SNAPSHOT</version>
Mettre la version dans le pom parent si c'est pas fait et l'enlever ici

2022-02-08 08:39 UTC, bbenaissa commented on api/api-pastis/pastis-commons/pom.xml
> +                <dependency>
enlever les parties commentées

2022-02-08 08:39 UTC, bbenaissa commented on api/api-pastis/pastis-commons/pom.xml
> +            <artifactId>jaxb-api</artifactId>
Dans le pom parent, on a déja :   <version>${jaxb.version}</version> ,

2022-02-08 08:39 UTC, bbenaissa commented on api/api-pastis/pastis-commons/pom.xml
> +            <version>0.6.2</version>
à mettre la version dans le pom parent

2022-02-08 08:39 UTC, bbenaissa commented on api/api-pastis/pastis-commons/pom.xml
> +            <version>20091111</version>
à mettre la version dans le pom parent

2022-02-08 08:39 UTC, bbenaissa commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/ElementProperties.java
> +    Object sedaData;
Plusieurs remarques et questions: 

- Pas d'accesseurs sur les champ sedaData , parent et puaData (un oubli ?)
- sur les champs sedaData , parent, on a déja les getter/setter à traver @Data

2022-02-08 08:39 UTC, bbenaissa commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/ElementRNG.java
> +    String name;
Même question concernant les accesseurs

2022-02-08 08:39 UTC, bbenaissa commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/factory/CardinalityTagFactory.java
> +        if (node.getCardinality().equals(RNGConstants.Cardinality.zeroOrMore.getLabel())) {
une bonne pratique est d'avoir une seule sortie d'une méthode

2022-02-08 08:39 UTC, bbenaissa commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/factory/CardinalityTagFactory.java
> +        if (cardinalityType.equals("ZeroOrMoreTag")) {
une bonne pratique est d'avoir une seule sortie d'une méthode

2022-02-08 08:39 UTC, bbenaissa commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/factory/PastisFactoryTagProvider.java
> +        if ("RngTag".equalsIgnoreCase(factoryType)) {
une bonne pratique est d'avoir une seule sortie d'une méthode

2022-02-08 08:39 UTC, bbenaissa commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/factory/RngTagFactory.java
> +            LOGGER.info("Parsing " + cardinalityTag.getTagName());
Un debug ?

2022-02-08 08:39 UTC, bbenaissa commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/factory/RngTagFactory.java
> +        if (currentTag instanceof GrammarTag) {
C'est une grosse méthode avec plus de 200 lignes, à découper pour plus de lisibilité

2022-02-08 08:39 UTC, bbenaissa commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/jaxb/BaliseXML.java
> +            if (currentXmlTag instanceof GrammarXML) {
Pareil , à découper la méthode

2022-02-11 09:45 UTC, pyXelians commented on api/api-pastis/pastis-client/pom.xml
> +
Toutes les dépendances liées aux tests semblent inutiles, puisque aucun test n'existent sur ce module. Il faudrait donc supprimer toutes les dépendances a partir de la ligne 59.

2022-02-11 14:46 UTC, pyXelians requested changes

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-client/pom.xml
> +        </dependency>
Je ne suis pas sûre que cette dépendance est utilisée dans ce module, il faudrait la supprimer.

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-client/pom.xml
> +        </dependency>
ça n'a pas l'air d'être utilisé dans le module

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-client/src/main/java/fr/gouv/vitamui/pastis/client/PastisTransformationRestClient.java
> +
Il y a pas mal de warning affichés par IntelliJ, et des sonarlint a corriger. Si vous ne l'avez pas installé, il faudrait le faire. Inline variable, exception useless, Explicit type argument etc

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-client/src/main/java/fr/gouv/vitamui/pastis/client/PastisTransformationRestClient.java
> +        LOGGER.debug("Transform profile");
Exception useless

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/ElementProperties.java
> +
sonarlint et warning intelliJ

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/ElementRNG.java
> +    // Build the a tree of properties given :
Erreurs sonarlint et warning intelliJ a corriger dans le fichier.

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/ElementRNG.java
> +
Cette méthode n'a pas l'air d'être utilisée

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/ElementRNG.java
> +        LOGGER.info("Generating JSON element {}", node.getName());
Complexité de la méthode trop élevé. Il faudrait factoriser

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/JsonFromRng.java
> +
Coquille dans le nom de la propriété

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/JsonFromRng.java
> +            this.cardinality = RNGConstants.CardinalityMap.get(cardinality);
remplacer par une équation ternaire ?

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/PuaData.java
> +    Boolean ExclusiveMinimum;
UpperCase sur les attributs ?  il y a pas moyen d'éviter ça ?

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/factory/CardinalityTagFactory.java
> +        if (cardinalityType.equals("OneOrMoreTag")) {
La méthode ne semble pas être utilsée

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/factory/RngTagFactory.java
> +
Beaucoup de warning et de sonarlint qui simplifierai  pas mal le code, condition always true, condition may be simplified, variable never used,  Merge this if statement with the enclosing one etc 

De plus je pense qu'il serait bien de factoriser cette méthode pour y voir plus clair

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/factory/RngTagFactory.java
> +
le package test n'existe pas, il faudrait le créer et surtout écrire des tests unitaires, avec la taille des méthodes et leurs compléxités il me parait essentiel d'avoir des tests pour assurer un minimum de maintenance

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/jaxb/BaliseXML.java
> +
Même remarque sur sonarlint et les warnings + tests unitaires + factorisation de la méthode

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/profiles/ProfileType.java
> +    }
private n'est pas nécessaire

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/pua/PuaMetadata.java
> +    }
ça n'a pas l'air d'être utilisé

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/seda/SedaNode.java
> +    private String Name;
pas moyen d'éviter les Uppercase ?

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/JsonFromPUA.java
> +     */
Même remarque des sonarlint et des warnings a corriger et une méthode a découper/refactoriser + tests unitaires manquants

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/PuaDefinitions.java
> +
coquille dans le nom de l'attribut, ça n'a pas l'air d'être utilisé non plus

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/PuaDefinitions.java
> +    @Value("${pua.definitions.file}")
Pourquoi ne pas initialiser la map ? ça permettrait d'éviter de se protéger contre le null dans le set

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/PuaDefinitions.java
> +public class PuaDefinitions {
Pourquoi est-ce un service ? La classe n'a pas l'air d'être utilisé ?

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/PuaFromJSON.java
> +
Warning et sonarlint

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/PuaPastisValidator.java
> +
warning + sonarlint + unit test + refactoring des méthodes trop longues

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/FileSystemResource.java
> +
Lombok ? sonarlint ?

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/NoticeUtils.java
> +        ObjectMapper mapper = new ObjectMapper();
sonarlint + méthode non utilisée

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/OrderedJSONObjectFactory.java
> +    private static final VitamUILogger LOGGER = VitamUILoggerFactory.getInstance(OrderedJSONObjectFactory.class);
Class non utilisée ?

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/PastisGetXmlJsonTree.java
> +    public String getJsonParsedTreeTest(ElementRNG elementRNGRoot) throws JAXBException, FileNotFoundException {
Faire le TODO

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/PastisGetXmlJsonTree.java
> +
Méthode pas utilisée

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/PastisGetXmlJsonTree.java
> +        this.jsonParsed = jsonParsed;
Méthode pas utilisée

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/PastisGetXmlJsonTree.java
> +            e1.printStackTrace();
catch mutualisable,  mauvaise pratique les printStackTrace

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/PastisGetXmlJsonTree.java
> +
sonarlint

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/PastisSAX2Handler.java
> +    }
Méthode vide ?

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/PastisSAX2Handler.java
> +
sonarlint

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/PropertiesUtils.java
> +
Cette classe n'est référencé que dans les tests, il serait bien de la déplacer dans un package test

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/PropertiesUtils.java
> +        File file;
Deux fois la même condition ?

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/PropertiesUtils.java
> +
Catch qui ne fait rien ?

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/RNGProfileValidator.java
> +    public static final String RNG_FACTORY = "com.thaiopensource.relaxng.jaxp.XMLSyntaxSchemaFactory";
même remarque utilisé que dans les tests

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/RNGProfileValidator.java
> +            return false;
Assignation de la variable error pas jamais utilisé

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/RNGProfileValidator.java
> +                    return true;
Assignation de la variable error pas jamais utilisé

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/controller/PastisController.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(PastisController.class);
Sonarlint

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/controller/PastisController.java
> +            return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
Renvoyé une erreur 500 qu'importe le soucis est une très mauvaise pratique. Les exceptions doivent être gérés au cas par cas, fonctionnelles ou techniques avec des codes erreurs les plus clairs possibles.

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/controller/PastisController.java
> +
Les requestMappings peuvent être remplacé par getMapping, PostMapping etc...

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-standalone/src/main/resources/standalone/angular.json
> +      "projectType": "library",
vitamui-library est deprecated et doit prochainement être supprimé, ce n'est par normal que cette librairie soit référencée ici.

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-standalone/src/main/resources/standalone/package.json
> +  "license": "MIT",
Si ce fichier ne doit être utilisé que pour la partie standalone, la partie scripts ne nécessite pas tout ces éléments

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-standalone/src/main/resources/standalone/startup.service.ts
> +
Ce fichier risque d'être très dure a maintenir si "l'original" change

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis-standalone/src/main/resources/standalone/theme.service.ts
> +}
Même remarque sur la maintenance

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis/pom.xml
> +
Il faudrait vérifier si les dépendances sont utilisées ou pas

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis/src/main/java/fr/gouv/vitamui/pastis/server/rest/PastisController.java
> +            return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
même remarque concernant les exceptions et les RequestMapping

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
> +
sonarlint a revoir

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
> +    private PuaPastisValidator puaPastisValidator;
Injection a faire par constructeur

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
> +            e1.printStackTrace();
Très mauvaise pratique il faut gérer l'exception

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
> +        }
C'est normal cet Id en dure ?

2022-02-11 14:46 UTC, pyXelians commented on api/api-pastis/pastis/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
> +        ProfileType profileType;
Utilisé une  Enum paramétrable serait plus simple et serait réutilisable

2022-02-11 14:54 UTC, pyXelians commented
Il y a beaucoup d'éléments facilement corrigeable avec l'utilisation de sonarlint comme plugin sur intelliJ. Il y a pas mal de code mort, pas assez de tests unitaires et des méthodes a factoriser. Je vous suggère d'installer le plugin (vérifier votre formatage au passage) et nous continuerons la review une fois les remarques déjà présentes prises en comptes.

2022-03-02 13:27 UTC, pyXelians requested changes

2022-03-02 13:27 UTC, pyXelians commented on api/api-pastis/pastis-client/pom.xml
> +        </dependency>
Avez-vous vérifier ce point ?

2022-03-02 13:27 UTC, pyXelians commented on api/api-pastis/pastis-client/pom.xml
> +        </dependency>
Avez-vous vérifier ce point ?

2022-03-02 13:27 UTC, pyXelians commented on api/api-pastis/pastis-client/pom.xml
> +
Avez-vous vérifier ce point ?

2022-03-02 13:27 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/ElementProperties.java
> +        }
Tu peux utiliser getOrDefault, ou bien utiliser une équation ternaire.

2022-03-02 13:27 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/ElementProperties.java
> +            this.groupOrChoice = groupOrChoice;
Tu peux utiliser getOrDefault, ou bien utiliser une équation ternaire.

2022-03-02 13:27 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/JsonFromRng.java
> +
la coquielle est toujours là => valu**L**eOrData

2022-03-02 13:27 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/PuaData.java
> +    List<String> Enum;
Nom d'attribut non conventionnel => pas d'uppercase, le nom fait référence a un mot clef java.

2022-03-02 13:27 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/factory/CardinalityTagFactory.java
> +        if (cardinalityType.equals("OneOrMoreTag")) {
Avez-vous vérifier ce point ?

2022-03-02 13:27 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/factory/RngTagFactory.java
> +
Je vois le package mais pas les tests unitaires associés ?

2022-03-02 13:27 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/factory/ValueTagFactory.java
> +public class ValueTagFactory implements AbstractTagFactory<Tag> {
Cette classe n'a pas l'air d'être utilisée ?

2022-03-02 13:27 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/pua/PuaMetadata.java
> +    }
Avez vous pu vérifier ce point ?

2022-03-02 13:27 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/exception/BusinessException.java
> +    }
Cela ne semble pas être utilisé

2022-03-02 13:27 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/exception/PastisException.java
> +
Il existe déjà une classe qui joue se rôle pour tout le projet => VitamUIException. Il faudrait la réutiliser et enrichir les exceptions gérées. De plus vos exceptions doivent être ensuite gérer au niveau du RestExceptionHandler

2022-03-02 13:27 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/exception/TechnicalException.java
> +    }
Même commentaire, bien que celle-ci soit utilisé, il faudrait qu'elle s'inscrive dans la même logique que le projet. Ou bien revoir la logique pour l'ensemble des exceptions

2022-03-02 13:27 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/rest/RestApi.java
> +
Les apis n'ont pas l'air de respecter les conventions Rest, il faut les changer => https://blog.nicolashachet.com/developpement-php/larchitecture-rest-expliquee-en-5-regles/

2022-03-02 13:27 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/JsonFromPUA.java
> +
Il faudrait ajouter des tests unitaires sur ce service qui détient pas mal de logique

2022-03-02 13:27 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/PuaDefinitions.java
> +public class PuaDefinitions {
Pouvez-vous vérifier ce point ?

2022-03-02 13:41 UTC, pyXelians commented on api/api-pastis/pastis/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
> +
Test unitaires manquants

2022-03-02 14:17 UTC, pyXelians commented on api/api-pastis/pastis/src/test/java/fr/gouv/vitamui/pastis/server/service/ImportPuaTest.java
> +        ElementProperties profile = jsonFromPUA.getProfileFromPUA(profileJson);
Si l'assertionError est remonté par le validator le code qui suit n'est pas utile

2022-03-02 14:17 UTC, pyXelians commented on api/api-pastis/pastis/src/test/java/fr/gouv/vitamui/pastis/server/service/ImportPuaTest.java
> +        ElementProperties profile = jsonFromPUA.getProfileFromPUA(profileJson);
Si l'assertionError est remonté par le validator le code qui suit n'est pas utile

2022-03-02 14:17 UTC, pyXelians commented on api/api-pastis/pastis/src/test/java/fr/gouv/vitamui/pastis/server/service/ImportPuaTest.java
> +        ElementProperties profile = jsonFromPUA.getProfileFromPUA(profileJson);
Si l'assertionError est remonté par le validator le code qui suit n'est pas utile

2022-03-02 14:17 UTC, pyXelians commented on api/api-pastis/pastis/src/test/java/fr/gouv/vitamui/pastis/server/service/ImportPuaTest.java
> +        puaPastisValidator.validatePUA(profileJson);
Si l'assertionError est remonté par le validator le code qui suit n'est pas utile

2022-03-02 14:17 UTC, pyXelians commented on api/api-pastis/pastis/src/test/java/fr/gouv/vitamui/pastis/server/service/ImportPuaTest.java
> +
Les deux services devraient être testés séparément

2022-03-02 15:39 UTC, GiooDev requested changes

2022-03-02 15:39 UTC, GiooDev commented on deployment/scripts/mongod/1.0.0/221_pastis_application_ref.js.j2
> +db.applications.update(
Pourquoi faire un update du même objet juste après le insert ?

2022-03-02 15:39 UTC, GiooDev commented on deployment/scripts/mongod/1.0.0/222_pastis_profile_ref.js.j2
> +db.profiles.insert({
Attention à ne pas oublier de prendre en compte les organisations déjà existantes ? (notamment dans le cas des montées de version).

2022-03-02 15:39 UTC, GiooDev commented on deployment/scripts/mongod/1.0.0/307_iam_ref.js.j2
> +            $each: [
Pas besoin du each pour 1 seule valeur.

2022-03-02 15:39 UTC, GiooDev commented on deployment/vitamui_pastis.yml
> +---
Déplacer ce script dans le répertoire `ansbile-vitamui/`

2022-03-02 15:39 UTC, GiooDev commented on deployment/scripts/mongod/1.0.0/307_iam_ref.js.j2
>      }
Attention, dans le cas d'une montée de version, ce script qui a déjà été livré (notamment en 5.rc) ne sera donc pas rejoué.

Il vaut mieux sortir la mise à jour de ce groups dans un nouveau script afin qu'il soit pris en compte.

2022-03-02 15:39 UTC, GiooDev commented on deployment/scripts/mongod/1.0.0/101_iam_system_demo.js
>          "system_dsl",
Attention, sur une infra déjà existante (cas d'une mise à jour) ce script ne sera pas rejoué.

Il s'agit d'un script _demo donc pas très grave pour des environnements type production.

2022-03-02 15:58 UTC, naji-cines commented on api/api-pastis/pastis-client/pom.xml
> +
oui, c'est bon

2022-03-02 15:58 UTC, naji-cines commented on api/api-pastis/pastis-client/pom.xml
> +        </dependency>
oui, c'est bon

2022-03-02 15:58 UTC, naji-cines commented on api/api-pastis/pastis-client/pom.xml
> +        </dependency>
oui, c'est bon

2022-03-02 16:04 UTC, naji-cines commented on api/api-pastis/pastis-standalone/src/main/resources/standalone/angular.json
> +      "projectType": "library",
Mais, elle existe sur le dans la structure des projets ui-frontend et on peux pas construire ui-frontend sans elle. Idem pour pastis standalone. Quand le projet ui-frontend ne dépendra plus d'elle on l'a supprimera

2022-03-02 16:08 UTC, naji-cines commented on api/api-pastis/pastis-standalone/src/main/resources/standalone/startup.service.ts
> +
Tout à fais d'accord, mais avez vous d'autres proposition ? le startupService est responsable de l'authentification et en me temps les couleurs de vitam-ui, donc on ai obligé de l'injecter pour avoir les couleur de vitam-ui mais en neutralisant l'authentification.

2022-03-02 18:00 UTC, naji-cines commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/factory/CardinalityTagFactory.java
> +        if (cardinalityType.equals("OneOrMoreTag")) {
Elle est utilisé ici common/dto/factory/RngTagFactory.java L310

2022-03-02 18:01 UTC, naji-cines commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/pua/PuaMetadata.java
> +    }
resolved

2022-03-03 08:26 UTC, GiooDev requested changes

2022-03-03 08:26 UTC, GiooDev commented on deployment/scripts/mongod/1.0.0/222_pastis_profile_ref.js.j2
> +db.profiles.insert({
Exemple de création de profils pour l'ensemble des tenants existants (fonctionne pour une installation from scratch & upgrade): https://github.com/ProgrammeVitam/vitam-ui/blob/develop/deployment/scripts/mongod/2.0.0/47_create_new_profiles_during_upgrade.js.j2

Pattern de nommage des profils à respecter: `PROFIL_<tenant.identifier>-<APP_NAME>-<SUFFIX>`
Si pas besoin de multi-profiles pour l'application, le <SUFFIX> = DEFAULT

2022-03-03 16:49 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/PuaPastisValidator.java
> +
Il faudrait des tests unitaires sur cette classe

2022-03-03 16:49 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/PastisGetXmlJsonTree.java
> +
Il reste des erreurs sonarlint

2022-03-03 16:49 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/PastisCustomCharacterEscapeHandler.java
> +
ça serait bien d'avoir des Tests unitaires

2022-03-03 16:49 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/PastisSAX2Handler.java
> +
Il reste des sonarlint et des warnings

2022-03-03 16:49 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/test/java/fr/gouv/vitamui/pastis/common/service/ImportPuaTest.java
> +        ElementProperties profile = jsonFromPUA.getProfileFromPUA(profileJson);
Si c'est le validator qui remonte l'erreur, le code plus bas peut être supprimé

2022-03-03 16:49 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/test/java/fr/gouv/vitamui/pastis/common/service/ImportPuaTest.java
> +        ElementProperties profile = jsonFromPUA.getProfileFromPUA(profileJson);
Si c'est le validator qui remonte l'erreur, le code plus bas peut être supprimé

2022-03-03 16:49 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/test/java/fr/gouv/vitamui/pastis/common/service/ImportPuaTest.java
> +        ElementProperties profile = jsonFromPUA.getProfileFromPUA(profileJson);
Si c'est le validator qui remonte l'erreur, le code plus bas peut être supprimé

2022-03-03 16:49 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/test/java/fr/gouv/vitamui/pastis/common/service/ImportPuaTest.java
> +        ElementProperties profile = jsonFromPUA.getProfileFromPUA(profileJson);
Si c'est le validator qui remonte l'erreur, le code plus bas peut être supprimé

2022-03-03 16:49 UTC, pyXelians commented on api/api-pastis/pastis-commons/src/test/java/fr/gouv/vitamui/pastis/common/service/ImportPuaTest.java
> +@TestPropertySource(locations = "/application-test.yml")
Pourquoi avoir utilisé springRunner et PropertySource ? ça n'a pas l'air d'être nécessaire dans les tests plus bas

2022-03-03 16:49 UTC, pyXelians commented on api/api-pastis/pastis-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/controller/PastisController.java
> +
Pouvez-vous prendre en compte ces remarques ?

2022-03-03 16:49 UTC, pyXelians commented on api/api-pastis/pastis-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/controller/PastisController.java
> +            return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
Pouvez-vous prendre en compte ces remarques

2022-03-03 16:49 UTC, pyXelians commented on api/api-pastis/pastis-standalone/src/main/resources/standalone/angular.json
> +      "projectType": "library",
Je n'ai pas vu d'endroit ou vous utilisé cette librairie en mode standalone ? si vous ne l'utilisé pas il n'y a pas de raison que vous ne puissiez pas la supprimer.

2022-03-03 16:49 UTC, pyXelians commented on api/api-pastis/pastis-standalone/src/main/resources/standalone/package.json
> +    "start:en": "ng serve --proxy-config proxy.conf.json  --configuration=en --disable-host-check --ssl --ssl-key $npm_package_pki_path/$npm_package_pki_asset.key --ssl-cert $npm_package_pki_path/$np
Je ne pense pas que le start:en soit nécessaire ?

2022-03-03 16:49 UTC, pyXelians commented on api/api-pastis/pastis-standalone/src/main/resources/standalone/package.json
> +    "test:vitamui-library": "ng test vitamui-library --watch=false",
Si vous n'utilisé pas vitamui-library, vous ne devriez pas non plus avoir besoin des scripts associés ici et plus bas

2022-03-03 16:49 UTC, pyXelians commented on api/api-pastis/pastis-standalone/src/main/resources/standalone/package.json
> +    "copy-scss:vitamui-library": "cp-cli ./projects/vitamui-library/src/sass ./dist/sass",
avec ngx-translate, vous ne devriez pas avoir besoin de extract-translations

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/angular.json
> +              "i18nFile": "projects/pastis/src/locale/messages.en.xlf",
cela ne devrait plus être nécessaire avec ngx-translate

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/angular.json
> +          "options": {
cela ne devrait plus être nécessaire avec ngx-translate

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/package.json
>      "analyze-portal": "ng build portal --stats-json --prod ; webpack-bundle-analyzer dist/portal/stats-es2015.json",
le --i18n-locale fr ne devrait plus être nécessaire avec ngx-translate

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/package.json
>      "check:demo": "npm run lint:demo && npm run build:demo",
cela ne devrait plus être nécessaire avec ngx-translate

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/api/api.service.spec.ts
> +    expect(service).toBeTruthy();
ça ne test pas grand chose; il faudrait soit compléter le test ou bien le supprimer (pour éviter qu'il consomme du temps de build pour très peu de valeur ajouté)

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/file.service.spec.ts
> +    const service: FileService = TestBed.get(FileService);
a supprimer ou compléter

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/notice.service.spec.ts
> +    expect(service).toBeTruthy();
a supprimer ou compléter

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/notice.service.ts
> +
Les models devraient être définis en dehors du service. De plus pour simplifier le mapping vous pouvez utiliser les affectations déstructurées : https://www.digitalocean.com/community/tutorials/understanding-destructuring-rest-parameters-and-spread-syntax-in-javascript-fr

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/popup.service.spec.ts
> +    expect(service).toBeTruthy();
A supprimer ou compléter

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.spec.ts
> +    expect(service).toBeTruthy();
A supprimer ou compléter

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
> +})
Supprimer le code mort et les console.log

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
> +
Les souscriptions ne doivent pas être géré manuellement, pour éviter cette gestion vous pouvez utiliser takeUnti et alléger le code, ou même créer une classe qui gère ça : https://dev.to/this-is-angular/dry-way-to-manage-subscriptions-in-angular-components-256j

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
> +    return allProfilesPA;
Tu peux inline et supprimer la déclaration de la variable

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
> +    return allProfilesPUA;
Tu peux inline et supprimer la déclaration de la variable

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
> +    const profiles: ProfileDescription[] = [];
De ce que je vois les appels sont fait séquentiellement, hors ça n'a pas l'air d'être nécessaire puisqu'il n'y a pas de lien entre les deux appels. Il faudrait donc les réaliser parallèlement.

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
> +          p.type = 'PUA';
Pourquoi ne pas utiliser l'opperator map qui semble clairement approprié à la problématique ?

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
> +    return allProfilesPA;
Tu peux inline

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
> +    return allProfilesPUA;
Tu peux inline

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
> +        data.forEach(p => tabVide.push(p));
Pourquoi parcourir deux fois la collection ?

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
> +
tabVide n'a pas l'air d'être utilisé, tu peux le supprimer et par la même occasion de ne pas la remplir si tu ne l'utilises pas après

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/seda.service.spec.ts
> +    expect(service).toBeTruthy();
A supprimer ou compléter

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/seda.service.ts
> +
tslint et indentation

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/seda.service.ts
> +            return result;
Avoir un seul return dans la méthode permettrai d'éviter ça

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/seda.service.ts
> +            return result;
Avoir un seul return dans la méthode permettrai d'éviter ça

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/seda.service.ts
> +        return nodeFound;
Avoir un seul return dans la méthode permettrai d'éviter ça

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/seda.service.ts
> +                                                      ||
la condition est trop complexe il faudrait la découper en predicate peut être ?

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/seda.service.ts
> +    if (sedaParent.Name == nomDuChamp) {
nomDuChamp => français ?

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/toggle-sidenav.service.spec.ts
> +    expect(service).toBeTruthy();
A supprimer ou compléter

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/core/services/toggle-sidenav.service.ts
> +        console.log('SideNav is opened');
supprimer les console.log

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/models/metadata-validator.ts
> +    const dateRegEx = new RegExp(/^\d{1,2}\.\d{1,2}\.\d{4}$/);
le type date ne suffit pas ?

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/pastis/pastis.module.ts
> +    MatTabsModule
Il faudrait plutôt utiliser PastisMaterialModule si j'ai bien compris la logique

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/create-profile/create-profile.component.spec.ts
> +    expect(component).toBeTruthy();
A supprimer ou compléter

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/edit-profile.component.spec.ts
> +    expect(component).toBeTruthy();
A supprimer ou compléter

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/attributes/attributes.service.spec.ts
> +  });
A supprimer ou compléter

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/attributes/attributes.service.ts
> +  constructor() { }
A supprimer

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/center-matmenu.directive.spec.ts
> +  });
A compléter ou supprimer

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.spec.ts
> +    expect(component).toBeTruthy();
A supprimer ou compléter

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.ts
> +}
Pourquoi ne pas avoir utiliser translate instant ? pour la pop up ça devrait suffire

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.ts
> +  private _fileServiceSubscription: Subscription;
Même remarque que plus haut pour gérer les subscriptions : https://dev.to/this-is-angular/dry-way-to-manage-subscriptions-in-angular-components-256j

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.ts
> +    if (newValue != null) {
supprimer le console.log

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.service.spec.ts
> +  });
A supprimer ou compléter

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.service.ts
> +            nomDuChamp: child.name,
On aurait pu créer un objet et un mapper pour gérer ça plutôt que de le dupliquer

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.service.ts
> +    return data;
Les console.log sont  à supprimer

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.service.ts
> +    let allowedCardinalityListResult: string[] = [];
il faudrait factoriser la méthode et diminuer le nombre de return

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree/file-tree.component.spec.ts
> +    expect(component).toBeTruthy();
A supprimer ou compléter

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree/file-tree.component.ts
> +      this.notificationRemoveSuccessTwo = 'avec succès';
Pourquoi ne pas utiliser aussi la traduction en mode standalone ?

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree/file-tree.component.ts
> +      },
Il y a un changement de langue spécifique pour SEDA ?

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree/file-tree.component.ts
> +    dataToSendToPopUp.component = UserActionAddMetadataComponent;
Translate.instant aurait très bien fait l'affaire ici, donc plus besoin de conserver tous ces attributs dans le component

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree/file-tree.component.ts
> +    const elementsToAddFromSeda: SedaData[] = [];
La méthode est beaucoup trop longue il faut la factoriser

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree/file-tree.component.ts
> +   if(insertItemDuplicate){
Code mort

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree/pipes/file-tree-filter.pipe.spec.ts
> +    expect(pipe).toBeTruthy();
A supprimer ou compléter

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree/pipes/file-tree-filter.pipe.ts
> +  }
pas sûre que ce soit utile ?

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/list-profile/list-profile.component.spec.ts
> +    expect(component).toBeTruthy();
A supprimer ou compléter

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/list-profile/list-profile.component.ts
> +      this.popupCreationCancelLabel = 'Annuler';
même remarque concernant la traduction

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/list-profile/list-profile.component.ts
> +
il faut supprimer tous les console.log

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/list-profile/list-profile.component.ts
> +    } else {
pourquoi on utilise un window.location ici ?

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/list-profile/list-profile.component.ts
> +    dataToSendToPopUp.cancelLabel = this.popupCreationCancelLabel;
translate instant devrait suffire ici, et donc pas besoin de déclarer autant de propriété

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/list-profile/list-profile.component.ts
> +  transform(listOfProfiles: ProfileDescription[], typeToFilter: string): ProfileDescription[] {
Il faut déclarer les pipe dans des fichiers a part

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-information-tab/profile-information-tab/profile-information-tab.component.spec.ts
> +    expect(component).toBeTruthy();
A compléter ou supprimer

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-information-tab/profile-information-tab/profile-information-tab.component.ts
> +
Supprimer les console.log

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-information-tab/profile-information-tab/profile-information-tab.component.ts
> +  }
Pourquoi l'avoir déclaré ?

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-information-tab/profile-information-tab/profile-information-tab.component.ts
> +      this.profileService.refreshListProfiles();
élément non traduit ?

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-information-tab/profile-information-tab/profile-information-tab.component.ts
> +    });
élément non traduit ?

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-preview.component.spec.ts
> +    expect(component).toBeTruthy();
A compléter ou supprimer

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/profile.component.spec.ts
> +    expect(component).toBeTruthy();
A compléter ou supprimer

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/profile.component.html
> +<p>profile works!</p>
pas sûre que ce component soit utile ?

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/profile/profile.component.ts
> +  constructor() { }
pas sûre que ce component soit utile ?

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/seda-visualizer/seda-visualizer.component.html
> +    <svg height=80 id="seda_legend" width=420></svg>
Pourquoi le style est mis en dure dans le html ?

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/seda-visualizer/seda-visualizer.component.spec.ts
> +    expect(component).toBeTruthy();
A compléter ou supprimer

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/seda-visualizer/seda-visualizer.component.ts
> +      this.sedaData = sedaRules;
Méthode trop longue

2022-03-03 16:49 UTC, pyXelians commented on ui/ui-frontend/projects/pastis/src/app/shared/data-generique-popup.service.spec.ts
> +    expect(service).toBeTruthy();
A compléter ou supprimer

2022-03-09 15:33 UTC, GiooDev requested changes

2022-03-09 15:33 UTC, GiooDev commented on deployment/scripts/mongod/2.0.0/48_create_new_profiles_pastis_during_upgrade.js.j2
> +                "name": "ROLE_DELETE_PASTIS"
Est-ce qu'il n'y a pas besoin de créer des profils sans le droit de DELETE pour certains usages ?
Tel que pour l'app ARCHIVESEARCH ?

2022-03-09 15:33 UTC, GiooDev commented on deployment/scripts/mongod/1.0.0/321_iam_groups_pastis_ref.js.j2
> +db.groups.updateOne( {
Pourquoi faire ça ici alors que dans le script `deployment/scripts/mongod/2.0.0/48_create_new_profiles_pastis_during_upgrade.js.j2` on fait l'association du profil à admin_group ?

Ce script me semble inutile.

2022-03-09 15:33 UTC, GiooDev commented on deployment/scripts/mongod/1.0.0/307_iam_ref.js.j2
> +
Annuler les modifs sur ce script pour éviter le suivi dans la PR.

2022-03-09 15:33 UTC, GiooDev commented on deployment/scripts/mongod/1.0.0/222_pastis_profile_ref.js.j2
> +db.profiles.insert({
Ce script ne semble plus nécessaire car le script : `deployment/scripts/mongod/2.0.0/48_create_new_profiles_pastis_during_upgrade.js.j2` semble faire l'ensemble des créations des profils pour chacun des tenants.

2022-03-09 15:33 UTC, GiooDev commented on deployment/scripts/mongod/1.0.0/221_pastis_application_ref.js.j2
> +db.applications.update({
Pourquoi faire un update juste après le insert précédent ?

Modifier le insert précédent pour tout faire en 1 fois.

2022-03-10 14:18 UTC, GiooDev commented
Est-ce qu'il ne manquerait pas le profil de pastis dans le fichier `roles/vitamui/files/customer-init.yml` pour la création de nouvelles organisations ?

2022-03-11 10:13 UTC, alexandregranier commented on api/api-pastis/pastis-client/pom.xml
> +            <version>5.0-SNAPSHOT</version>
FAIT - A VERIFIER

2022-03-11 10:15 UTC, alexandregranier commented on api/api-pastis/pastis-commons/pom.xml
> +                <dependency>
FAIT - A VERIFIER

2022-03-11 10:17 UTC, alexandregranier commented on api/api-pastis/pastis-commons/pom.xml
> +            <artifactId>jaxb-api</artifactId>
FAIT - A VERIFIER

2022-03-11 10:20 UTC, alexandregranier commented on api/api-pastis/pastis-commons/pom.xml
> +            <version>0.6.2</version>
FAIT - A VERIFIER -> mis en variable dans parent

2022-03-11 10:20 UTC, alexandregranier commented on api/api-pastis/pastis-commons/pom.xml
> +            <version>20091111</version>
FAIT - A VERIFIER -> mis en variable dans parent

2022-03-11 10:23 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/ElementProperties.java
> +    Object sedaData;
RIEN A FAIRE - A VERIFIER annotation @Data suffisante

2022-03-11 10:24 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/ElementRNG.java
> +    String name;
RIEN A FAIRE - A VERIFIER annotation @DaTa suffisante

2022-03-11 10:27 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/factory/CardinalityTagFactory.java
> +        if (node.getCardinality().equals(RNGConstants.Cardinality.zeroOrMore.getLabel())) {
FAIT - A VERIFIER

2022-03-11 10:31 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/factory/CardinalityTagFactory.java
> +        if (cardinalityType.equals("ZeroOrMoreTag")) {
METHODE SUPPRIMEE - A VERIFIER

2022-03-11 10:39 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/factory/PastisFactoryTagProvider.java
> +        if ("RngTag".equalsIgnoreCase(factoryType)) {
CLASSE SUPPRIMEE - A VERIFIER

2022-03-11 10:46 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/factory/RngTagFactory.java
> +            LOGGER.info("Parsing " + cardinalityTag.getTagName());
FAIT - A VERIFIER - MIS AU NIVEAU DEBUG

2022-03-11 10:48 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/jaxb/BaliseXML.java
> +            if (currentXmlTag instanceof GrammarXML) {
FAIT - A VERIFIER

2022-03-11 10:49 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/factory/RngTagFactory.java
> +        if (currentTag instanceof GrammarTag) {
FAIT - A VERIFIER -

2022-03-11 10:52 UTC, alexandregranier commented on api/api-pastis/pastis-client/pom.xml
> +        </dependency>
FAIT - A VERIFIER

2022-03-11 10:53 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/JsonFromRng.java
> +
FAIT - A VERIFIER

2022-03-11 13:19 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/JsonFromRng.java
> +            this.cardinality = RNGConstants.CardinalityMap.get(cardinality);
FAIT

2022-03-11 13:19 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/PuaData.java
> +    Boolean ExclusiveMinimum;
FAIT - A VERIFIER

2022-03-11 13:20 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/factory/CardinalityTagFactory.java
> +        if (cardinalityType.equals("OneOrMoreTag")) {
RIEN A FAIRE

2022-03-11 13:32 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/factory/RngTagFactory.java
> +
REFACTO FAIT -> TESTS UNITAIRES NON FAITS

2022-03-11 13:34 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/jaxb/BaliseXML.java
> +
WARNING ET REFACTO FAIT. TU REPOUSSES

2022-03-11 13:35 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/pua/PuaMetadata.java
> +    }
FAIT - A VERIFIER

2022-03-11 13:35 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/seda/SedaNode.java
> +    private String Name;
FAIT - A VERIFIER

2022-03-11 13:36 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/JsonFromPUA.java
> +     */
REFACTO FAIT - TU REPOUSSES

2022-03-11 13:36 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/PuaDefinitions.java
> +
CLASSE SUPPRIMEE

2022-03-11 13:37 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/PuaDefinitions.java
> +    @Value("${pua.definitions.file}")
CLASSE SUPPRIMEE

2022-03-11 13:37 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/PuaDefinitions.java
> +public class PuaDefinitions {
CLASSE SUPPRIMEE

2022-03-11 13:39 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/PuaPastisValidator.java
> +
FAIT - TU REPOUSSES

2022-03-11 13:40 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/FileSystemResource.java
> +
FAIT - A VERIFIER

2022-03-11 13:41 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/NoticeUtils.java
> +        ObjectMapper mapper = new ObjectMapper();
METHODE SUPPRIMEE

2022-03-11 13:41 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/OrderedJSONObjectFactory.java
> +    private static final VitamUILogger LOGGER = VitamUILoggerFactory.getInstance(OrderedJSONObjectFactory.class);
CLASSE SUPPRIMEE

2022-03-11 13:41 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/PastisGetXmlJsonTree.java
> +    public String getJsonParsedTreeTest(ElementRNG elementRNGRoot) throws JAXBException, FileNotFoundException {
FAIT - A VERIFIER

2022-03-11 13:42 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/PastisGetXmlJsonTree.java
> +
METHODE SUPPRIMEE

2022-03-11 13:42 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/PastisGetXmlJsonTree.java
> +        this.jsonParsed = jsonParsed;
METHODE SUPPRIMEE

2022-03-11 13:43 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/PastisGetXmlJsonTree.java
> +            e1.printStackTrace();
METHODE SUPPRIMEE

2022-03-11 14:06 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/PastisSAX2Handler.java
> +    }
FAIT - A VERIFIER

2022-03-11 14:15 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/PropertiesUtils.java
> +
FAIT

2022-03-11 14:17 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/PropertiesUtils.java
> +        File file;
CORRIGE

2022-03-11 14:18 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/PropertiesUtils.java
> +
CORRIGE

2022-03-11 14:19 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/RNGProfileValidator.java
> +    public static final String RNG_FACTORY = "com.thaiopensource.relaxng.jaxp.XMLSyntaxSchemaFactory";
CLASSE DEPLACEE

2022-03-11 14:19 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/RNGProfileValidator.java
> +            return false;
MIS EN LOG - A VERIFIER

2022-03-11 14:20 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/RNGProfileValidator.java
> +                    return true;
MIS EN LOG - A VERIFIER

2022-03-11 14:36 UTC, alexandregranier commented on api/api-pastis/pastis-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/controller/PastisController.java
> +            return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
Il s'agit d'erreur I/O ou de marshalling XML. Pas d'erreur métier associé. Difficile de faire mieux.

2022-03-11 14:38 UTC, alexandregranier commented on api/api-pastis/pastis-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/controller/PastisController.java
> +
FAIT - A VERIFIER

2022-03-11 14:40 UTC, alexandregranier commented on api/api-pastis/pastis-standalone/src/main/resources/standalone/angular.json
> +      "projectType": "library",
ON EST OBLIGE DE LA LAISSER SINON, CA NE COMPILE PLUS

2022-03-11 14:41 UTC, alexandregranier commented on api/api-pastis/pastis-standalone/src/main/resources/standalone/package.json
> +  "license": "MIT",
FAIT - A VERIFIER

2022-03-11 14:42 UTC, alexandregranier commented on api/api-pastis/pastis-standalone/src/main/resources/standalone/theme.service.ts
> +}
PAS POSSIBLE DE FAIRE MIEUX

2022-03-11 14:45 UTC, alexandregranier commented on api/api-pastis/pastis/pom.xml
> +
NON CRITIQUE - ON PEUT FAIRE CELA PLUS TARD

2022-03-11 14:45 UTC, alexandregranier commented on api/api-pastis/pastis/src/main/java/fr/gouv/vitamui/pastis/server/rest/PastisController.java
> +            return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
DEJA VU PLUS HAUT

2022-03-11 14:48 UTC, alexandregranier commented on api/api-pastis/pastis/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
> +
SONARLINT OK - TESTS REPOUSSES

2022-03-11 14:48 UTC, alexandregranier commented on api/api-pastis/pastis/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
> +    private PuaPastisValidator puaPastisValidator;
FAIT - A VERIFIER

2022-03-11 14:49 UTC, alexandregranier commented on api/api-pastis/pastis/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
> +            e1.printStackTrace();
FAIT - A VERIFIER

2022-03-11 14:50 UTC, alexandregranier commented on api/api-pastis/pastis/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
> +        }
FAIT - A VERIFIER

2022-03-11 14:50 UTC, alexandregranier commented on api/api-pastis/pastis/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
> +        ProfileType profileType;
FAIT - A VERIFIER

2022-03-11 14:53 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/ElementProperties.java
> +        }
FAIT A VERIFIER

2022-03-11 14:54 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/ElementProperties.java
> +            this.groupOrChoice = groupOrChoice;
FAIT

2022-03-11 15:09 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/factory/ValueTagFactory.java
> +public class ValueTagFactory implements AbstractTagFactory<Tag> {
CLASSE SUPPRIMEE

2022-03-11 15:10 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/exception/BusinessException.java
> +    }
EXCEPTION SUPPRIMEE

2022-03-11 15:36 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/JsonFromPUA.java
> +
FAIT - A VERIFIER

2022-03-11 15:43 UTC, alexandregranier commented on api/api-pastis/pastis/src/test/java/fr/gouv/vitamui/pastis/server/service/ImportPuaTest.java
> +        ElementProperties profile = jsonFromPUA.getProfileFromPUA(profileJson);
CLASSE SUPPRIMEE

2022-03-11 15:43 UTC, alexandregranier commented on api/api-pastis/pastis/src/test/java/fr/gouv/vitamui/pastis/server/service/ImportPuaTest.java
> +        ElementProperties profile = jsonFromPUA.getProfileFromPUA(profileJson);
CLASSE SUPPRIMEE

2022-03-11 15:43 UTC, alexandregranier commented on api/api-pastis/pastis/src/test/java/fr/gouv/vitamui/pastis/server/service/ImportPuaTest.java
> +        ElementProperties profile = jsonFromPUA.getProfileFromPUA(profileJson);
CLASSE SUPPRIMEE

2022-03-11 15:43 UTC, alexandregranier commented on api/api-pastis/pastis/src/test/java/fr/gouv/vitamui/pastis/server/service/ImportPuaTest.java
> +        puaPastisValidator.validatePUA(profileJson);
CLASSE SUPPRIMEE

2022-03-11 15:43 UTC, alexandregranier commented on api/api-pastis/pastis/src/test/java/fr/gouv/vitamui/pastis/server/service/ImportPuaTest.java
> +
CLASSE SUPPRIMEE

2022-03-11 17:19 UTC, bbenaissa requested changes

2022-03-11 17:19 UTC, bbenaissa commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/profiles/Notice.java
> +        String fileName = r.getFilename();
risque de NPE

2022-03-11 17:19 UTC, bbenaissa commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/profiles/Notice.java
> +            this.name = getFileBaseName(fileName);
Pour name et fileBaseName : 2 appels de la méthode  getFileBaseName

2022-03-11 17:19 UTC, bbenaissa commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/profiles/Notice.java
> +                JSONTokener tokener = new JSONTokener(new InputStreamReader(inputStream));
un check de fileExists?

2022-03-11 17:19 UTC, bbenaissa commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/exception/PastisException.java
> +
+1

2022-03-11 17:19 UTC, bbenaissa commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/exception/TechnicalException.java
> +    }
+1

2022-03-11 17:19 UTC, bbenaissa commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/JsonFromPUA.java
> +                    addPuaDataToElementIfNotPresent(childProfile);
les valeurs $ref, enum, pattern sont utilisés plusieurs fois, pourquoi pas une enum?

2022-03-11 17:19 UTC, bbenaissa commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/RNGConstants.java
> +        TypesMap.put("CodeListVersions", DataType.TOKEN);
Pourquoi pas externaliser ça ailleurs (un fichier de configuration) ?

2022-03-11 17:19 UTC, bbenaissa commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamProfileService.java
> +    /*
A supprimer

2022-03-11 17:19 UTC, bbenaissa commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamArchivalProfileUnitService.java
> +package fr.gouv.vitamui.referential.common.service;
A ajouter le texte de la licence dans l'ensemble des nouveaux fichiers

2022-03-11 17:19 UTC, bbenaissa commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ArchivalProfileUnitExternalController.java
> +    //@Secured(ServicesData.ROLE_GET_ARCHIVE_PROFILES_UNIT)
Pourquoi le controle des roles a été désactivé?

2022-03-11 17:19 UTC, bbenaissa commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ProfileExternalController.java
> +    //@Secured(ServicesData.ROLE_GET_ARCHIVE_PROFILES)
Pourquoi le controle des roles a été désactivé?

2022-03-11 17:19 UTC, bbenaissa commented on api/api-referential/referential-internal-client/src/main/java/fr/gouv/vitamui/referential/internal/client/ProfileInternalWebClient.java
> +    public String getPathUrl() {
pourquoi l'url est null?

2022-03-11 17:19 UTC, bbenaissa commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/profile/ProfileInternalService.java
> +/*    public Boolean check(VitamContext vitamContext, ProfileDto archivalProfileDto) {
A supprimer

2022-03-11 17:19 UTC, bbenaissa commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/ProfileInternalController.java
> +/*    @PostMapping(CommonConstants.PATH_CHECK)
A supprimer

2022-03-11 17:19 UTC, bbenaissa commented on ui/ui-frontend/projects/pastis/src/app/shared/pastis-generic-popup/pastis-popup-selection.service.spec.ts
> +    expect(service).toBeTruthy();
A completer ou supprimer

2022-03-11 17:19 UTC, bbenaissa commented on ui/ui-frontend/projects/pastis/src/app/shared/pastis-generic-popup/pastis-generic-popup.component.spec.ts
> +    expect(component).toBeTruthy();
A completer ou supprimer

2022-03-14 08:25 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/PastisCustomCharacterEscapeHandler.java
> +
TESTS REPOUSSES

2022-03-14 08:26 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/test/java/fr/gouv/vitamui/pastis/common/service/ImportPuaTest.java
> +        ElementProperties profile = jsonFromPUA.getProfileFromPUA(profileJson);
CLASSE SUPPRIMEE

2022-03-14 08:26 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/test/java/fr/gouv/vitamui/pastis/common/service/ImportPuaTest.java
> +        ElementProperties profile = jsonFromPUA.getProfileFromPUA(profileJson);
CLASSE SUPPRIMEE

2022-03-14 08:26 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/test/java/fr/gouv/vitamui/pastis/common/service/ImportPuaTest.java
> +        ElementProperties profile = jsonFromPUA.getProfileFromPUA(profileJson);
CLASSE SUPPRIMEE

2022-03-14 08:26 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/test/java/fr/gouv/vitamui/pastis/common/service/ImportPuaTest.java
> +        ElementProperties profile = jsonFromPUA.getProfileFromPUA(profileJson);
CLASSE SUPPRIMEE

2022-03-14 08:26 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/test/java/fr/gouv/vitamui/pastis/common/service/ImportPuaTest.java
> +@TestPropertySource(locations = "/application-test.yml")
CLASSE SUPPRIMEE

2022-03-14 09:54 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/profiles/Notice.java
> +        String fileName = r.getFilename();
FAIT - A VERIFIER

2022-03-14 09:54 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/profiles/Notice.java
> +            this.name = getFileBaseName(fileName);
FAIT - A VERIFIER

2022-03-14 09:54 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/profiles/Notice.java
> +                JSONTokener tokener = new JSONTokener(new InputStreamReader(inputStream));
FAIT - A VERIFIER

2022-03-14 13:28 UTC, alexandregranier commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamProfileService.java
> +    /*
FAIT - A VERIFIER

2022-03-14 13:28 UTC, alexandregranier commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ArchivalProfileUnitExternalController.java
> +    //@Secured(ServicesData.ROLE_GET_ARCHIVE_PROFILES_UNIT)
FAIT - A VERIFIER

2022-03-14 13:28 UTC, alexandregranier commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/profile/ProfileInternalService.java
> +/*    public Boolean check(VitamContext vitamContext, ProfileDto archivalProfileDto) {
FAIT - A VERIFIER

2022-03-14 13:28 UTC, alexandregranier commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/ProfileInternalController.java
> +/*    @PostMapping(CommonConstants.PATH_CHECK)
FAIT - A VERIFIER

2022-03-14 14:44 UTC, alexandregranier commented on api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/ElementProperties.java
> +            this.groupOrChoice = groupOrChoice;
REVENU EN ARRIERE : PAS PRATIQUE DANS CE CAS.

2022-03-14 17:00 UTC, naji-cines commented on ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree/file-tree.component.ts
> +      },
Oui, en langage SEDA et en francais

2022-03-21 11:18 UTC, GiooDev requested changes

2022-03-21 11:18 UTC, GiooDev commented on deployment/scripts/mongod/1.0.0/221_pastis_application_ref.js.j2
> +    {% if vitamui.pastis.base_url is defined %}
Pourquoi faire 2x le même if ? Est-ce qu'il ne serait pas possible de mettre dans la condition précédente les valeurs adéquates ?

2022-03-21 11:18 UTC, GiooDev commented on deployment/scripts/mongod/1.0.0/220_cas_services_pastis_ref.js.j2
> +{% if vitamui.pastis.base_url is defined %}
Pourquoi faire 2x le même if ? Est-ce qu'il ne serait pas possible de mettre dans la condition précédente les valeurs adéquates ?

2022-11-18 15:09 UTC, bbenaissa commented
Suite à la décision de l'admin, cette PR sera mergée et des corrections vont être ajoutés après pour améliorer la qualité et éventuellement corriger des anomlies

2022-11-21 10:17 UTC, bbenaissa approved these changes

2022-11-21 13:47 UTC, laedanrex approved these changes

2022-11-21 14:04 UTC, merged