WIP OIDC authn delegation
ProgrammeVitam/vitam-ui pull request #633
Opened 2022-01-25 08:56 UTC by leleuj

DO NOT merge

2022-02-03 15:03 UTC, bbenaissa commented on api/api-iam/iam-commons/src/main/java/fr/gouv/vitamui/iam/common/utils/Pac4jClientBuilder.java
> +                    if (useState != null) {
Une condition oidcConfiguration.setWithState(useState != null ? useState:true ) c'est plus lisible je pense ? une proposition

2022-02-03 15:04 UTC, bbenaissa commented on api/api-iam/iam-commons/src/main/java/fr/gouv/vitamui/iam/common/utils/Pac4jClientBuilder.java
> +                    if (useState != null) {
pareil pour les autres instructions ci-dessous (ça réduit un peu le code)

2022-02-03 15:06 UTC, bbenaissa requested changes

2022-02-03 15:06 UTC, bbenaissa commented on api/api-iam/iam-commons/src/main/java/fr/gouv/vitamui/iam/common/utils/Pac4jClientBuilder.java
> +            LOGGER.error("Cannot build pac4j client", e);
Je pense que cette instruction n'est pas accessible

2022-02-07 08:22 UTC, leleuj commented on api/api-iam/iam-commons/src/main/java/fr/gouv/vitamui/iam/common/utils/Pac4jClientBuilder.java
> +                    if (useState != null) {
OK, je vais changer.
Je ne suis pas fan de cet opérateur ternaire qui, pour moi, diminue la lisibilité, mais en effet ça sera plus concis.

2022-02-07 08:23 UTC, leleuj commented on api/api-iam/iam-commons/src/main/java/fr/gouv/vitamui/iam/common/utils/Pac4jClientBuilder.java
> +            LOGGER.error("Cannot build pac4j client", e);
Potentiellement oui. Les `if` ne couvrent que quelques cas suivant le message d'erreur.

2022-02-07 08:39 UTC, leleuj commented
@bbenaissa La PR a été mise à jour après tes retours.

2022-02-07 09:22 UTC, bbenaissa approved these changes

2022-02-07 17:52 UTC, merged