[VAS] Item 9102: Manage Filing and Holding scheme when exporting search results as CSV
ProgrammeVitam/vitam-ui pull request #650
Opened 2022-02-08 10:17 UTC by nabilm2i

## Description
L'objectif de cette PR est  de gérer le type d'archive (arbres, plans, archives avec objets ou sans objets) lors de l'export des résultats de recherche sous format CSV

## Type de changement:
* Nouveau Code 

## Tests:
- Des tests fonctionnels sont effectués pour vérifier le fonctionnement de cette évolution.
- Des tests ont été ajoutés.

## Migration:
- Pas de migration.

## Checklist:
[X] Mon code suit le style de code de ce projet.
[X] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.
[X] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.
[X] Les tests unitaires nouveaux et existants passent avec succès localement.

## Contributeur
Vitam Accessible en Service (VAS)

2022-02-08 14:43 UTC, oussamasic requested changes

2022-02-08 14:43 UTC, oussamasic commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/ArchiveUnitCsv.java
> +    private String descriptionLevelType;
descriptionLevel, c'est plutôt **unitType** je pense

2022-02-08 14:45 UTC, oussamasic approved these changes

2022-02-09 10:38 UTC, bbenaissa approved these changes

2022-02-09 16:23 UTC, merged