[Xelians] Add trace and histo user-info
ProgrammeVitam/vitam-ui pull request #670
Opened 2022-02-16 16:16 UTC by pyXelians

Comme discuté avec Joris, cette PR contient plusieurs modifications : 

- Gestion de l'historique pour l'user-info
- Ajout des traces pour l'user info
-  Correction de bug en tout genre

Cette PR est a mergé en même temps que celle sur la partie front : 

## Type de changement

-  Code et/ou Configuration : Correction, évolution

## Tests

Suite au build un rapport de test est généré avec les vulnérabilités. 

## Migration

 Quels sont les opérations supplémentaires à faire lors d’une migration de VITAM ? 
 De quel version à quel version s’appliquent ces modifications ?

## Checklist

 [ * ] Les tests unitaires nouveaux et existants passent avec succès localement.
 [ * ] Toutes les dépendances ont été mergées en priorité

## Contributeur

Xelians

2022-04-06 16:00 UTC, bbenaissa requested changes

2022-04-06 16:00 UTC, bbenaissa commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/UserInfoExternalController.java
> +    @GetMapping("/{id}/history")
à mettre le path comme constante dans RestApi ou dans CommonConstants

2022-04-12 09:14 UTC, pyXelians commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/UserInfoExternalController.java
> +    @GetMapping("/{id}/history")
C'est fait

2022-04-13 08:44 UTC, bbenaissa approved these changes

2022-04-13 08:44 UTC, bbenaissa commented on api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/UserInfoExternalController.java
> +    @GetMapping("/{id}/history")
à mettre le path comme constante dans RestApi ou dans CommonConstants

2022-04-13 09:03 UTC, bbenaissa requested changes
Il manque le texte de signature dans plusieurs fichiers créés.

2022-04-26 08:32 UTC, pyXelians commented
> Il manque le texte de signature dans plusieurs fichiers créés.

C'est fait

2022-05-02 13:30 UTC, pyXelians commented
l'ajout de la propriété max_street_length a bien été fait

2022-05-06 15:44 UTC, GiooDev requested changes

2022-05-06 15:44 UTC, GiooDev commented on deployment/environments/group_vars/all/vitamui_vars.yml
> +    max_street_length: 250
Pourquoi définir cette valeur pour 2 composants ?

Est-ce possible de la configurer à des valeurs différentes pour chacun des composants ? Quel est le fonctionnement attendu si c'est le cas ?

Si cette valeur doit être commune, la placer plutôt au niveau de `vitamui_platform_informations`.

2022-05-06 15:44 UTC, GiooDev commented on deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
> +  max-street-length: 250
Pourquoi en dur pour ce composant ?

Même question, quel est le comportement si on met des valeurs différentes pour chacun des composants ?

2022-05-06 15:44 UTC, GiooDev commented on deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
> +  message: "Profitez d'un portail unique pour rechercher dans les archives de vos coffres, pour déposer des éléments en toute sécurité et pour imprimer des étiquettes en quelques clics."
Pourquoi mettre en dur cette valeur ? il existe une variable `vitamui_platform_informations.portal_message` qui contient ce message.

2022-05-06 15:44 UTC, GiooDev commented on deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
> +  title: "Portail des applications de l'archivage"
Idem avec la variable `vitamui_platform_informations.portal_title`

2022-05-06 15:44 UTC, GiooDev commented on deployment/roles/vitamui/templates/iam-internal/application.yml.j2
> +  max-street-length: {{ vitamui.iam_internal.max_street_length }}
Prévoir une valeur par défaut.

2022-05-06 15:44 UTC, GiooDev commented on deployment/roles/vitamui/templates/ui-identity/application.yml.j2
> +  max-street-length: {{ vitamui.identity.max_street_length }}
Prévoir une valeur par défaut.

2022-05-06 15:44 UTC, GiooDev commented on deployment/roles/vitamui/templates/ui-identity/application.yml.j2
> +  max-street-length: 250
Idem, pourquoi en dur pour cette application ?

2022-05-06 15:44 UTC, GiooDev commented on deployment/roles/vitamui/templates/ui-identity/application.yml.j2
> +  message: "Profitez d'un portail unique pour rechercher dans les archives de vos coffres, pour déposer des éléments en toute sécurité et pour imprimer des étiquettes en quelques clics."
Idem que précédemment, on a des variables pour ces messages.

2022-05-06 15:44 UTC, GiooDev commented on deployment/roles/vitamui/templates/ui-portal/application.yml.j2
> +  message: "Profitez d'un portail unique pour rechercher dans les archives de vos coffres, pour déposer des éléments en toute sécurité et pour imprimer des étiquettes en quelques clics."
Again

2022-09-14 08:55 UTC, bbenaissa approved these changes

2022-09-14 08:55 UTC, bbenaissa commented on deployment/scripts/mongod/2.0.0/012_REC-385_update_user_info_role_ref.js
> +  { $addToSet: { roles: { $each: [{ name: "ROLE_GET_USER_INFOS" }] } } }
Est ce que ce role 'ROLE_GET_USER_INFOS' a été ajouté dans les contextes Ui

2022-09-14 08:55 UTC, bbenaissa commented on ui/ui-identity/src/main/java/fr/gouv/vitamui/identity/service/UiIdentityApplicationService.java
> +    @Value("${address.max-street-length}")
Il faudra ajouter ce parametre dans la partie template ansible

2022-09-14 08:55 UTC, bbenaissa commented on ui/ui-identity/src/main/java/fr/gouv/vitamui/identity/service/UiIdentityApplicationService.java
> +    @Value("${address.max-street-length}")
Il faudra ajouter ce parametre dans la partie template ansible

2022-09-14 08:57 UTC, merged