[VAS] Item 9419: Archival Unit Reclassification
ProgrammeVitam/vitam-ui pull request #685
Opened 2022-02-28 09:16 UTC by nabilm2i

## Description
Nouvelle fonctionnalité de reclassement d'une unité archivistique

## Type de changement:
* Configuration ansiblerie des droits
* ajout d'api /reclassification sur le module archive-search

## Checklist:
[X] Mon code suit le style de code de ce projet.
[X] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.
[X] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.
[X] Les tests unitaires nouveaux et existants passent avec succès localement.

## Contributeur
Vitam Accessible en Service (VAS)

2022-02-28 17:18 UTC, bbenaissa requested changes

2022-02-28 17:18 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal-client/src/main/java/fr/gouv/archive/internal/client/ArchiveInternalRestClient.java
> +            restTemplate.exchange(getUrl() + RestApi.CRECLASSIFICATION, HttpMethod.POST,
Je pense qu'il y a une petite faute dans l'url : **CRECLASSIFICATION**

2022-02-28 17:19 UTC, bbenaissa commented
Il faudra prévoir un script de migration des profils en incluant le role en question

2022-03-01 11:03 UTC, oussamasic requested changes
Remplace info par debug

2022-03-01 11:03 UTC, oussamasic commented on api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/rest/RestApi.java
> +    public static final String CRECLASSIFICATION = "/reclassification";
Nom à changer "reclassification"

2022-03-01 11:03 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> +  // Reclassification variables
commentaire à supprimer

2022-03-01 11:03 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/reclassification/reclassification.component.css
> +}
des commentaires à supprimer

2022-03-02 16:39 UTC, GiooDev requested changes

2022-03-02 16:39 UTC, GiooDev commented on deployment/scripts/mongod/2.0.0/47_update_archive_search_context_to_add_reclassification_role.js.j2
> +         $each:[
Pas besoin du $each pour une seule valeur.

2022-03-02 16:39 UTC, GiooDev commented on deployment/scripts/mongod/2.0.0/48_update_archive_administrator_profile_to_add_reclassification_role.js.j2
> +         $each:[
idem

2022-03-02 16:39 UTC, GiooDev commented on deployment/scripts/mongod/2.0.0/48_update_archive_administrator_profile_to_add_reclassification_role.js.j2
> +db.profiles.updateOne({
Quid des profils déjà existants ?

2022-03-02 17:02 UTC, GiooDev requested changes

2022-03-02 17:02 UTC, GiooDev commented on deployment/scripts/mongod/2.0.0/48_update_archive_administrator_profile_to_add_reclassification_role.js.j2
> +   "_id":"system_archive_search_profile_archiviste_administrator"
Attention, suite à la PR #676 ce profil ne s'appelle plus ainsi.

Le nom attendu sera `PROFIL_<tenant.identifier>-ARCHIVE_SEARCH_MANAGEMENT_APP-ADMIN`

2022-03-02 17:36 UTC, GiooDev requested changes

2022-03-02 17:36 UTC, GiooDev commented on deployment/scripts/mongod/2.0.0/47_update_archive_search_context_to_add_reclassification_role.js.j2
> +db = db.getSiblingDB('security')
Modifier le numéro du script pour être sûr qu'il passe après le script `scripts/mongod/2.0.0/47_create_new_profiles_during_upgrade.js.j2` qui va créer les nouveaux profiles pour tous les tenants.

2022-03-02 17:48 UTC, GiooDev requested changes

2022-03-02 17:48 UTC, GiooDev commented on deployment/scripts/mongod/2.0.0/48_update_archive_administrator_profile_to_add_reclassification_role.js.j2
> +         $each:[
```
db.profiles.updateMany({
   "name": "Archiviste administrateur"
},
{
   "$addToSet": {
      "roles":{
           $each: [
               "name": "ROLE_RECLASSIFICATION",
               "name": "ROLE_UPDATE_MANAGEMENT_RULES",
               "name": "ROLE_COMPUTED_INHERITED_RULES"
          ]
      }
   }
});
```

2022-03-03 09:17 UTC, GiooDev commented on deployment/scripts/mongod/2.0.0/48_update_archive_administrator_profile_to_add_reclassification_role.js.j2
> +         $each:[
Avec cette requête, ça devrait prendre en compte tous les cas de montée de version et d'install initiale pour même les profils existants.

2022-03-03 16:38 UTC, oussamasic approved these changes

2022-03-03 16:40 UTC, bbenaissa approved these changes

2022-03-03 16:48 UTC, GiooDev requested changes

2022-03-03 16:48 UTC, GiooDev commented on deployment/scripts/mongod/2.0.0/51_migration_roles_reclassifciation_updaterules_inheritesrules_script.js.j2
> +print("START 51_migration_roles_rclassifciation_updaterules_inheritesrules_script.js");
typo rclassification

2022-03-03 16:48 UTC, GiooDev commented on deployment/scripts/mongod/2.0.0/51_migration_roles_reclassifciation_updaterules_inheritesrules_script.js.j2
> +print("END 51_migration_roles_rclassifciation_updaterules_inheritesrules_script.js");
idem

2022-03-03 17:05 UTC, merged