[VAS] BUG 9567 : add get access contract to archive profiles
ProgrammeVitam/vitam-ui pull request #691
Opened 2022-03-02 16:04 UTC by oussamasic

L'objectif de cette PR est de corriger un bug au niveau des profils de l'application recherche et consultation des archives

2022-03-02 16:13 UTC, jbricout007 commented
Régression uniquement sur develop = tag retiré

2022-03-02 16:29 UTC, GiooDev requested changes

2022-03-02 16:29 UTC, GiooDev commented on deployment/scripts/mongod/2.0.0/50_add_get_access_contract_role_to_archive_profiles.js.j2
> +         $each:[
pas besoin du $each pour une valeur

2022-03-02 16:29 UTC, GiooDev commented on deployment/scripts/mongod/2.0.0/50_add_get_access_contract_role_to_archive_profiles.js.j2
> +   "$push": {
Attention au $push, si la valeur à rajouter existe déjà, il va la doublonner.

Mieux vaut privilégier un `$addToSet`

2022-03-03 08:11 UTC, bbenaissa approved these changes

2022-03-03 09:01 UTC, GiooDev approved these changes

2022-03-04 08:48 UTC, nabilm2i approved these changes

2022-03-04 09:09 UTC, merged