Feature/vas 8092 9429 facets and access rules
ProgrammeVitam/vitam-ui pull request #701
Opened 2022-03-03 21:38 UTC by bbenaissa

2022-03-04 15:34 UTC, nabilm2i requested changes

2022-03-04 15:34 UTC, nabilm2i commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchManagementRulesQueryBuilderService.java
> +        private void buildMgtRulesOriginCriteria(String ruleCategory, BooleanQuery query,
clean comments

2022-03-04 15:34 UTC, nabilm2i commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchManagementRulesQueryBuilderService.java
> +            if (searchCriteria.getCriteria().equals(
idem clean

2022-03-04 15:34 UTC, nabilm2i commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
> +            if (LOGGER.isDebugEnabled()) {
pas besoin de isDebugEnabled() c'est géré par le
 ```yml
logging:
    level:
        p.a.c.k.a.g.e.archives.search.internal.*:  LOG_LEVEL
```
ou pas ?

2022-03-04 16:00 UTC, oussamasic commented
coté Front :

pour les opérateurs tu peux utiliser l'enum CriteriaOperator
pour les types de donnée tu peux utiliser l'enum : CriteriaDataType et ActionOnCriteria pour les actions (add et remove)

2022-03-04 16:07 UTC, oussamasic requested changes

2022-03-04 16:07 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
> +                searchQuery.setCriteriaList(initalCriteriaList);
nom de la variable "initalCriteriaList", il manque un 'i'

2022-03-04 16:07 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
> +        List<SearchCriteriaEltDto> initalCriteriaList,
nom de la variable "initalCriteriaList", il manque un 'i'

2022-03-04 16:07 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
> +                if (direction.isPresent() && DirectionDto.DESC.equals(direction.get())) {
direction.isPresent() toujours à true, donc à enlever

2022-03-04 16:07 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchManagementRulesQueryBuilderService.java
> + */
ancien texte

2022-03-04 16:07 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
> +            if (LOGGER.isDebugEnabled()) {
pas besoin je pense, c'est toujours activé

2022-03-04 16:07 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchManagementRulesQueryBuilderService.java
> +    */
à supprimer

2022-03-04 16:07 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchManagementRulesQueryBuilderService.java
> +            */
à supprimer

2022-03-04 16:07 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/components/vitamui-facet/vitamui-facet-facet.component.spec.ts
> +});
je pense qu'on peut enlever ce fichier vu qu'il contient aucun test

2022-03-04 16:07 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/components/vitamui-facet/vitamui-facet.component.html
> +          <span class="status-text" [ngStyle]="{ color: facet.color }">{{ facet.title }}</span>
dans un fichier css c'est mieux

2022-03-04 16:07 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/components/vitamui-facet/vitamui-facet.component.ts
> +  // tslint:disable-next-line: component-selector
c'est mieux de supprimer ce commentaire, pour laisser la règle de tslint qui s'applique sur les selectors activée

2022-03-04 16:07 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/access-rule-search/access-rule-search.component.html
> +          [ngStyle]="{ 'background-color': 'green', width: '30', height: '30' }"
à ajouter dans un fichier css c'est mieux

2022-03-04 16:07 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/access-rule-search/access-rule-search.component.html
> +          [ngStyle]="{ 'background-color': 'green', width: '30', height: '30' }"
Idem

2022-03-04 16:07 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/archive-search-rules-facets.component.spec.ts
> +});
on peut le supprimer vu qu'il n'y a pas de tests

2022-03-04 16:07 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-appraisal-rules-facets/search-appraisal-rules-facets.component.spec.ts
> +});
Idem

2022-03-07 08:24 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchManagementRulesQueryBuilderService.java
> +            if (searchCriteria.getCriteria().equals(
Done

2022-03-07 08:24 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
> +            if (LOGGER.isDebugEnabled()) {
Done

2022-03-07 08:30 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
> +                searchQuery.setCriteriaList(initalCriteriaList);
done

2022-03-07 08:30 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
> +        List<SearchCriteriaEltDto> initalCriteriaList,
done

2022-03-07 08:34 UTC, nabilm2i approved these changes

2022-03-07 08:35 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
> +                if (direction.isPresent() && DirectionDto.DESC.equals(direction.get())) {
Il y a un test avant, elle n'est pas tjrs à true

2022-03-07 08:35 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
> +            if (LOGGER.isDebugEnabled()) {
Supprimé

2022-03-07 08:35 UTC, bbenaissa commented on ui/ui-frontend-common/src/app/modules/components/vitamui-facet/vitamui-facet.component.ts
> +  // tslint:disable-next-line: component-selector
Supprimé

2022-03-07 08:35 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/archive-search-rules-facets.component.spec.ts
> +});
Supprimé

2022-03-07 08:36 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-appraisal-rules-facets/search-appraisal-rules-facets.component.spec.ts
> +});
Supprimé

2022-03-07 08:43 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/access-rule-search/access-rule-search.component.html
> +          [ngStyle]="{ 'background-color': 'green', width: '30', height: '30' }"
Done

2022-03-07 08:43 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/access-rule-search/access-rule-search.component.html
> +          [ngStyle]="{ 'background-color': 'green', width: '30', height: '30' }"
Done

2022-03-07 08:43 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchManagementRulesQueryBuilderService.java
> + */
Changé

2022-03-07 09:03 UTC, oussamasic approved these changes

2022-03-07 09:28 UTC, merged