[VAS] Add Contributors
ProgrammeVitam/vitam-ui pull request #706
Opened 2022-03-04 15:57 UTC by nabilm2i

Ajout des contributeurs équipe VITAM

2022-03-04 16:00 UTC, gansheer approved these changes

2022-03-04 16:00 UTC, oussamasic approved these changes

2022-03-04 16:05 UTC, jbricout007 requested changes
Please add :
- Jérome LELEU
- Mehdi NAJAHI

2022-03-04 16:08 UTC, bbenaissa approved these changes

2022-03-04 16:10 UTC, jbricout007 approved these changes

2022-03-07 12:58 UTC, GiooDev approved these changes

2022-03-07 12:59 UTC, merged