[VAS] fix vault mongo_express variable and consul reload handler
ProgrammeVitam/vitam-ui pull request #728
Opened 2022-03-17 15:00 UTC by nabilm2i

2022-03-18 17:54 UTC, Ro3034 approved these changes

2022-03-19 14:30 UTC, GiooDev requested changes

2022-03-19 14:30 UTC, GiooDev commented on deployment/roles/mongo_configure/vars/main.yml
> +consul_service: "{{ consul.service_name }}"
Inutile car utilise nulle part

2022-03-19 14:30 UTC, GiooDev commented on deployment/roles/mongo_configure/tasks/main.yml
> +- name: "Reload consul"
Pourquoi faire une task pour le reload consul et non pas un handler ?

2022-03-19 14:30 UTC, GiooDev commented on deployment/environments/group_vars/all/vault-mongodb.yml
> +38616363643236383839353163356335666365643133666138386362326363393236343538386536
C'est quoi la modif qui a été faite ici ? Si c'est des changements impactant faut le montrer dans le example associé

2022-03-21 08:39 UTC, GiooDev commented on deployment/environments/group_vars/all/vault-mongodb.yml
> +38616363643236383839353163356335666365643133666138386362326363393236343538386536
ok vérifié, c'est le nom de la variable mongod_express au lieu de mongo_express qui n'était pas correct.
Dans le fichier example c'est déjà ok :)

2022-03-21 08:40 UTC, GiooDev commented on deployment/roles/mongo_configure/tasks/main.yml
> +- name: "Reload consul"
Car dans ce cas là, on va reload à chaque fois que l'on appliquera l'ansiblerie

2022-03-21 09:07 UTC, Ro3034 commented on deployment/roles/mongo_configure/vars/main.yml
> +consul_service: "{{ consul.service_name }}"
ligne supprimée

2022-03-21 09:23 UTC, nabilm2i commented on deployment/environments/group_vars/all/vault-mongodb.yml
> +38616363643236383839353163356335666365643133666138386362326363393236343538386536
yes

2022-03-21 09:27 UTC, GiooDev approved these changes

2022-03-21 09:28 UTC, GiooDev commented
Après test, il restera les CP à refaire à partir de ce commit pour R16 et V5RC.

2022-03-22 16:30 UTC, Ro3034 approved these changes

2022-03-22 16:30 UTC, merged