[VAS] Bug 9729 : Fix update unit metadata
ProgrammeVitam/vitam-ui pull request #740
Opened 2022-03-22 17:08 UTC by laedanrex

## Description
Problème de mise à jour des métadonnées descriptive des unités archivistique.

La PR contient aussi un fix du bug 9737: ça été ajouté en mode quick win sur cette branche pour accélérer les tests de l'ensemble

## Type de changement:
* Correction 
## Tests:
Tests manuels
## Checklist:
[x] Mon code suit le style de code de ce projet.
[x] Les tests unitaires nouveaux et existants passent avec succès localement.
## Contributeur
VAS

2022-03-22 17:53 UTC, oussamasic requested changes

2022-03-22 17:53 UTC, oussamasic commented on deployment/scripts/mongod/2.0.0/54_migration_role_update_desc_unit_metadata_script.js.j2
> +print("END 54_migration_role_update_desc_unit_metadata_script.js");
pas besoin de ce script, le script 53.... fait la même chose

2022-03-23 10:51 UTC, oussamasic approved these changes

2022-03-23 10:51 UTC, oussamasic approved these changes

2022-03-24 12:24 UTC, bbenaissa approved these changes

2022-03-24 13:58 UTC, merged