VAS item 8777 accessionregisterdetails export csv
ProgrammeVitam/vitam-ui pull request #767
Opened 2022-04-04 16:30 UTC by laedanrex

2022-04-05 12:37 UTC, oussamasic commented
Il y a pas de commentaires à supprimer,
Le code style Intellij n'est pas appliqué, voici le lien vers la conf du code style : [https://assistance.programmevitam.fr/plugins/document/projetvitam/folder/50](https://assistance.programmevitam.fr/plugins/document/projetvitam/folder/50)

2022-04-05 13:05 UTC, oussamasic requested changes

2022-04-05 13:05 UTC, oussamasic commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/AccessionRegisterExternalController.java
> +    //@Secured(ServicesData.ROLE_GET_ARCHIVE)
à ne pas commenter, il faut sécuriser l'API par un rôle qui concerne le profil de l'application registre des fonds, comme : ROLE_GET_ACCESSION_REGISTER_DETAIL, sinon un nouveau role pour l'export CSV

2022-04-05 13:05 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
> +        LOGGER.info("Calling exportToCsvAccessionRegister with query {} ", searchQuery);
debug ?

2022-04-05 13:05 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
> +            LOGGER.info("accessionRegisterDetailResponseDto found {} ", accessionRegisterDetailResponseDto.getResults().size());
debug ?

2022-04-05 13:05 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-list/accession-register-list.component.ts
> +    console.log('accessContract ', this.accessContract);
To delete

2022-04-05 13:05 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/core/api/accession-register-detail-api.service.ts
> +    console.log('API front: ', criteria);
To delete

2022-04-05 13:05 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterSummaryInternalService.java
> +	public AccessionRegisterStatsDto getAccessionRegisterDetailStats(VitamContext vitamContext, AccessionRegisterDetailsSearchStatsDto detailsSearchDto) {
fonction non utilisée, à supprimer

2022-04-06 13:32 UTC, bbenaissa requested changes

2022-04-06 13:32 UTC, bbenaissa commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/AccessionRegisterExternalController.java
> +    @PostMapping("/details/export-csv")
Est ce que tu peux mettre l'url comme une constante dans la classe : **RestApi**

2022-04-06 13:32 UTC, bbenaissa commented on api/api-referential/referential-internal-client/src/main/java/fr/gouv/vitamui/referential/internal/client/AccessionRegisterDetailInternalRestClient.java
> +            restTemplate.exchange(getUrl() + "/export-csv", HttpMethod.POST,
remplacer l'url par la constante de RestApi

2022-04-06 13:32 UTC, bbenaissa commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
> -            LOGGER.error("Error when getting Accession Register summaries : {} " , e);
Puisque tu throw l'exception, pas besoin de logger, ça sera logger plus loin

2022-04-06 13:32 UTC, bbenaissa commented on api/api-referential/referential-internal-client/src/main/java/fr/gouv/vitamui/referential/internal/client/AccessionRegisterDetailInternalRestClient.java
> +        LOGGER.info("Calling exportAccessionRegisterCsv with query {} ", query);
LOGGER.debug?

2022-04-06 13:32 UTC, bbenaissa commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
> +        // Agecies codes or name labels ?
Comment à supprimer

2022-04-06 13:32 UTC, bbenaissa commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
>              LOGGER.error("Can't create dsl query to get paginated accession registers : {}", ioe);
pareil pour le log

2022-04-06 13:32 UTC, bbenaissa commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
>              LOGGER.error("Can't fetch data from VITAM : {}", e);
pareil pour le log

2022-04-06 13:32 UTC, bbenaissa commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
>              LOGGER.error("Error parsing query : {}", e);
Idem

2022-04-06 13:32 UTC, bbenaissa commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterSummaryConverter.java
> +/**
A vérifier le CopyRight

2022-04-06 13:32 UTC, bbenaissa commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterSummaryInternalService.java
> +			LOGGER.error("Error when getting Accession Register summaries : {} " , e);
idem pour les logs

2022-04-06 13:32 UTC, bbenaissa commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/AccessionRegisterInternalController.java
> +    @PostMapping("/details/export-csv")
idem pour l'ur

2022-04-13 15:40 UTC, closed without merging