[VAS] Feature 9774 archive search service refactoring
ProgrammeVitam/vitam-ui pull request #774
Opened 2022-04-13 15:13 UTC by bbenaissa

2022-04-14 16:06 UTC, laedanrex approved these changes

2022-04-15 08:27 UTC, oussamasic requested changes

2022-04-15 08:27 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchEliminationInternalService.java
> + * This software is a computer program whose purpose is to implement a digital archiving back-office system managing
la signature n'est pas à jour, et il y a bcp de formatage au niveau du code

2022-04-15 08:27 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchFacetsInternalService.java
> +        LOGGER.info("Start finding facets for computed rules  ");
debug ?

2022-04-15 08:27 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchMgtRulesInternalService.java
> +        LOGGER.info("Add Rules to ArchiveUnits using query : {} and DSL actions : {}",
debug ?

2022-04-15 08:27 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchFacetsInternalService.java
> +import static fr.gouv.vitamui.archives.search.common.common.ArchiveSearchConsts.WAITING_RECALCULATE;
import static fr.gouv.vitamui.archives.search.common.common.ArchiveSearchConsts.*; ?

2022-04-15 08:28 UTC, oussamasic commented
dans l'ensemble des classes java crées, le texte du copyright n'est pas à jour

2022-04-15 13:15 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchMgtRulesInternalService.java
> +        LOGGER.info("Add Rules to ArchiveUnits using query : {} and DSL actions : {}",
done

2022-04-15 13:15 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchFacetsInternalService.java
> +        LOGGER.info("Start finding facets for computed rules  ");
done

2022-04-15 14:19 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchFacetsInternalService.java
> +import static fr.gouv.vitamui.archives.search.common.common.ArchiveSearchConsts.WAITING_RECALCULATE;
Done

2022-04-15 14:42 UTC, oussamasic approved these changes

2022-04-15 14:47 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchEliminationInternalService.java
> + * This software is a computer program whose purpose is to implement a digital archiving back-office system managing
Modifiée

2022-04-15 17:43 UTC, merged