Feature/vas 9760 manage access facets
ProgrammeVitam/vitam-ui pull request #779
Opened 2022-04-14 15:17 UTC by bbenaissa

2022-04-20 14:29 UTC, oussamasic requested changes

2022-04-20 14:29 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
> +        "CALCULATED": "Avec règle indexée"
il manque la traduction en anglais

2022-04-20 14:29 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-access-rules-facets/search-access-rules-facets.component.ts
> +import { FacetDetails } from 'ui-frontend-common/app/modules/models/operation/facet-details.interface';
Pour les couleurs, on peut créer une Enum et déclarer les couleurs en question.

2022-04-20 14:29 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/common-services/archive-facets.service.ts
> +        if (facet.name === 'COMPUTE_RULES_AU_NUMBER') {
on peut déclarer ces chaines de caractères dans des constantes

2022-04-21 11:53 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
> +        "CALCULATED": "Avec règle indexée"
Ajoutés

2022-04-21 11:54 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-access-rules-facets/search-access-rules-facets.component.ts
> +import { FacetDetails } from 'ui-frontend-common/app/modules/models/operation/facet-details.interface';
Modifiées

2022-04-21 11:54 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/common-services/archive-facets.service.ts
> +        if (facet.name === 'COMPUTE_RULES_AU_NUMBER') {
modifiée

2022-04-21 12:16 UTC, oussamasic approved these changes

2022-04-25 08:54 UTC, laedanrex approved these changes

2022-04-26 08:51 UTC, merged

2022-04-26 09:04 UTC, GiooDev commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchEliminationInternalService.java
> - * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2015-2022)
Pourquoi les dates ont été changées ?

2022-04-26 09:04 UTC, GiooDev commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchEliminationInternalService.java
> - * circulated by CEA, CNRS and INRIA at the following URL "https://cecill.info".
Et l'édition de cette URL ?