[VAS] 8904 : add accession register preview
ProgrammeVitam/vitam-ui pull request #785
Opened 2022-04-28 15:29 UTC by laedanrex

2022-04-29 14:54 UTC, nabilm2i requested changes

2022-04-29 14:54 UTC, nabilm2i commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
> +            LOGGER.error("Error when getting Accession Register summaries : {} ", e);
messages incohérents entre Logger et throw à corriger

2022-04-29 14:54 UTC, nabilm2i commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
> +                    String.valueOf(accessionRegisterCsv.getTotalObjects().getIngested()), //FR_OBJ_ELEC
FR_OBJ_ELEC commentaire à supprimer

2022-04-29 14:54 UTC, nabilm2i commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
> +                    String.valueOf(accessionRegisterCsv.getObjectSize().getIngested()), //FR_VOL_ELEC
//FR_VOL_ELEC idem

2022-04-29 14:54 UTC, nabilm2i commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-list/accession-register-list.component.html
> +            <div class="col-3">{{ accessionRegisterDetail.obIdIn }}</div>
message au lieu de GUID? voulu ?

2022-04-29 14:55 UTC, nabilm2i commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-list/accession-register-list.component.html
> +            <div class="col-3">{{ accessionRegisterDetail.obIdIn }}</div>
vu avec Alex ! c'est bon pour moi

2022-04-29 15:01 UTC, bbenaissa requested changes

2022-04-29 15:01 UTC, bbenaissa commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-detail/accession-register-detail.component.ts
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
Le copy right n'est pas bon

2022-04-29 15:01 UTC, bbenaissa commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-detail/accession-register-detail.component.ts
> +  ngOnDestroy() {
pas besoin de garder les méthodes non utilisées

2022-04-29 15:01 UTC, bbenaissa commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operation/accession-register-operation.component.ts
> +
idem

2022-04-29 15:03 UTC, bbenaissa commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
> +            LOGGER.error("Error when getting Accession Register summaries : {} ", e);
Pas besoin de garder d'ajouter le message, il sera logguée plus tard dans le handeler,

2022-04-29 15:36 UTC, oussamasic requested changes

2022-04-29 15:36 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
> +                    String.valueOf(accessionRegisterCsv.getObjectSize().getIngested()), //FR_VOL_ELEC
tu peux supprimer les 2 commentaires

2022-04-29 15:36 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/models/access-register/register-value-event-model.ts
> +  CreationDate: string //creationdate
Commentaires à supprimer

2022-04-29 15:36 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-detail/accession-register-detail.component.ts
> +
to delete,

2022-04-29 15:36 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operation/accession-register-operation.component.ts
> +@Component({
je pense qu'on peut fusionner ce composant avec le composant `AccessionRegisterOperationsListComponent`

2022-04-29 15:36 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operations-list.component.html
> +    </app-accession-register-operation>
on peut utiliser les tables existantes de VitamUI

2022-04-29 15:36 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operations-list.component.ts
> +  }
To delete

2022-04-29 15:36 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-preview.component.spec.ts
> +  });
Est-ce qu'on peut ajouter d'autres tests ?

2022-04-29 15:36 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operations-list.component.spec.ts
> +  });
Est-ce qu'on peut ajouter d'autres tests ?

2022-04-29 15:36 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-preview.component.ts
> +  }
To delete

2022-04-29 15:36 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-preview.component.spec.ts
> + *
Ancien texte de copyright, à mettre à jour

2022-04-29 15:36 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-preview.component.ts
> + *
Ancien texte de copyright, à mettre à jour par le nouveau texte

2022-04-29 15:36 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-detail/accession-register-detail.component.ts
> + * contact@programmevitam.fr
Ancien texte de copyright, à mettre à jour par le nouveau texte

2022-04-29 15:36 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operation/accession-register-operation.component.ts
> + * contact@programmevitam.fr
Ancien texte de copyright, à mettre à jour par le nouveau texte

2022-04-29 15:36 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operations-list.component.ts
> + * contact@programmevitam.fr
Ancien texte de copyright, à mettre à jour par le nouveau texte

2022-04-29 15:46 UTC, oussamasic requested changes

2022-04-29 15:46 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-detail/accession-register-detail.component.ts
> +    return this.accessionRegisterDetail.comment[0].substring(0, 200);
possibilité de NP au cas où le commentaire est non renseigné

2022-04-29 15:46 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/models/access-register/register-value-event-model.ts
> +  Opc: string; //operation
Pourquoi mettre les attributs en majuscule ?

2022-05-02 05:59 UTC, laedanrex commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operation/accession-register-operation.component.ts
> +@Component({
oui, mais je ne suis pas trop pour le faire: 
ca permet de bien separer le code

2022-05-02 06:01 UTC, laedanrex commented on ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operations-list.component.html
> +    </app-accession-register-operation>
tu penses auxquelles ?

2022-05-02 06:05 UTC, laedanrex commented on ui/ui-frontend-common/src/app/modules/models/access-register/register-value-event-model.ts
> +  Opc: string; //operation
c'est le model ^^
je m'adapte a ce qui est retourné par le back

2022-05-04 17:10 UTC, bbenaissa approved these changes

2022-05-05 09:42 UTC, oussamasic approved these changes

2022-05-05 14:52 UTC, merged