Vas 9848
ProgrammeVitam/vitam-ui pull request #787
Opened 2022-05-02 15:25 UTC by laedanrex

## Description

faire que la recherche et l'export csv coté registre de fond ai les meme criteres

## Type de changement:

* Build

* Nouveau Code

* Refactorisation de code

## Tests:

manuel

environnement

TU
## Checklist:

[x] Mon code suit le style de code de ce projet.

[x] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[x] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[x] Les tests unitaires nouveaux et existants passent avec succès localement.

## Contributeur
VAS (Vitam Accessible en Service)

2022-05-04 17:08 UTC, bbenaissa requested changes

2022-05-04 17:08 UTC, bbenaissa commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/AccessionRegisterExternalController.java
>          RestUtils.checkCriteria(criteria);
ça sera mieux de mettre le debug après le check pour une question de sécurité

2022-05-04 17:08 UTC, bbenaissa commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/AccessionRegisterExternalController.java
> +        LOGGER.info("WESH WESH WESH criteria={}", criteria);
WESH WESH WESH criteriaWESH WESH WESH criteria

2022-05-04 17:08 UTC, bbenaissa commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/AccessionRegisterExternalController.java
>          LOGGER.info("Calling export to csv search archive Units By Criteria {} ", query);
debug? et à inverser aussi

2022-05-04 17:08 UTC, bbenaissa commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/AccessionRegisterInternalController.java
> +        LOGGER.info("WESH WESH WESH criteria={}", criteria);
WESH WESH WESH criteria

2022-05-05 08:34 UTC, oussamasic requested changes

2022-05-05 08:34 UTC, oussamasic commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessRegisterVitamQueryHelperTest.java
> +    void createQueryDSL_test_with_criteria01()
ça sera mieux d'avoir des noms qui expliquent bien l'objectif du test en question, 
Meme remarque pour l'ensemble des tests ajoutés

2022-05-05 08:34 UTC, oussamasic commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessRegisterVitamQueryHelperTest.java
> +            getResourceAsCriteria("criteriabis01.json"),
C'est mieux aussi d'avoir des noms explicites pour l'ensemble des fichiers des tests.
Meme remarque pour l'ensemble des fichiers de tests (json/access-register).

2022-05-05 08:34 UTC, oussamasic commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessRegisterVitamQueryHelperTest.java
> +            getResourceAsCriteria("criteriabis01.json"),
C'est mieux aussi d'avoir des noms explicites pour l'ensemble des fichiers des tests.

2022-05-05 10:04 UTC, oussamasic approved these changes

2022-05-05 10:04 UTC, oussamasic commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessRegisterVitamQueryHelperTest.java
> +    void createQueryDSL_test_with_criteria01()
ça sera mieux d'avoir des noms qui expliquent bien l'objectif du test en question, 
Meme remarque pour l'ensemble des tests ajoutés

2022-05-05 16:29 UTC, bbenaissa approved these changes

2022-05-06 15:07 UTC, merged