[VAS] US 9697: Workflow de création d'un projet de versement
ProgrammeVitam/vitam-ui pull request #788
Opened 2022-05-04 12:16 UTC by depysk

## Description
[VAS] US 9697: Workflow de création d'un projet de versement
## Type de changement:
* Nouveau Code
## Tests:
Tests manuels, TU
## Migration:
Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire
## Checklist:
[x] Mon code suit le style de code de ce projet.
[x] J'ai commenté mon code, en particulier dans les classes et lesméthodes difficile à comprendre.
[x] Les tests unitaires nouveaux et existants passent avec succès localement.
[x] Toutes les dépendances ont été mergées en priorité
## Contributeur
VAS

2022-05-04 17:01 UTC, bbenaissa requested changes

2022-05-04 17:01 UTC, bbenaissa commented on .run/2 - Security-Internal.run.xml
> +    <extension name="net.ashald.envfile">
Pourquoi ces ajouts?

2022-05-04 17:01 UTC, bbenaissa commented on api/api-ingest/ingest-commons/src/main/java/fr/gouv/vitamui/ingest/common/dto/ProjectDto.java
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2015-2019)
A mettre à jour le template de copyRight

2022-05-04 17:01 UTC, bbenaissa commented on api/api-ingest/ingest-external-client/src/main/java/fr/gouv/vitamui/collect/external/client/CollectExternalRestClient.java
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
Idem

2022-05-04 17:01 UTC, bbenaissa commented on api/api-ingest/ingest-external-client/src/main/java/fr/gouv/vitamui/collect/external/client/CollectStreamingExternalRestClient.java
> +        LOGGER.info("The response is {}", response.toString());
.debug?

2022-05-04 17:01 UTC, bbenaissa commented on api/api-ingest/ingest-external/src/main/java/fr/gouv/vitamui/ingest/external/server/rest/CollectExternalController.java
> +        LOGGER.debug("[External] upload collect zip file : {}", originalFileName);
ça sera plus secure d'inverser l'ordre du debug avec les checks

2022-05-04 17:01 UTC, bbenaissa commented on api/api-ingest/ingest-external/src/main/java/fr/gouv/vitamui/ingest/external/server/service/CollectExternalService.java
> +@Getter
Est ce que tu as besoin des get et set ici?

2022-05-04 17:01 UTC, bbenaissa commented on api/api-ingest/ingest-internal-client/src/main/java/fr/gouv/vitamui/collect/internal/client/CollectStreamingInternalRestClient.java
> +        LOGGER.info("The response on collect upload is {} ", response.toString());
debug?

2022-05-04 17:01 UTC, bbenaissa commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/rest/CollectInternalController.java
> +@Getter
Besoin des get et set?

2022-05-04 17:01 UTC, bbenaissa commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/collect/CollectInternalService.java
> +        return ProjectDto.builder()
ce sont des données mockées?

2022-05-04 17:01 UTC, bbenaissa commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/collect/CollectInternalService.java
> +        LOGGER.info("contextId : {}", contextId);
debug?

2022-05-04 17:01 UTC, bbenaissa commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/collect/CollectInternalService.java
> +        File targetFile = new File("/home/passam/Bureau/" + originalFileName);
changer par un chemin relatif

2022-05-04 17:01 UTC, bbenaissa commented on deployment/scripts/mongod/2.0.0/56_application_ref.js.j2
> +db = db.getSiblingDB('iam')
modifier le nom du fichier avec un nom significatif

2022-05-04 17:01 UTC, bbenaissa commented on deployment/scripts/mongod/2.0.0/57_iam_ref.js.j2
> +
idem pour le nom

2022-05-04 17:01 UTC, bbenaissa commented on ui/ui-frontend/projects/ingest/src/app/collect/projects/create-project/create-project.component.ts
> +    'Versement',
Est ce qu'on ne peut pas mettre ces entrées dans la partie traduction ?

2022-05-04 17:01 UTC, bbenaissa commented on ui/ui-frontend/projects/ingest/src/app/collect/projects/create-project/create-project.component.ts
> +          "Aucun contrat d'accès n'est associé à l'utiisateur",
Il y a un exemple de traduction dans le module archive-search

2022-05-04 17:01 UTC, bbenaissa commented on ui/ui-frontend/projects/ingest/src/app/collect/projects/project-list/project-list.component.ts
> +    console.log(project);
A supprimer

2022-05-04 17:01 UTC, bbenaissa commented on ui/ui-frontend/projects/ingest/src/app/collect/projects/projects.component.ts
> +    console.log(event);
Idem

2022-05-04 17:01 UTC, bbenaissa commented on ui/ui-frontend/projects/ingest/src/app/collect/projects/projects.service.ts
> +    console.log(project);
idem

2022-05-05 09:36 UTC, oussamasic requested changes

2022-05-05 09:36 UTC, oussamasic commented on api/api-ingest/ingest-external/src/main/java/fr/gouv/vitamui/ingest/external/server/rest/CollectExternalController.java
> +        LOGGER.debug("getPaginateEntities page={}, size={}, criteria={}, orderBy={}, ascendant={}", page, size, orderBy,
un petit check à ajouter sur le paramètre criteria.

2022-05-05 09:36 UTC, oussamasic commented on api/api-ingest/ingest-external/src/main/java/fr/gouv/vitamui/ingest/external/server/rest/CollectExternalController.java
> +        LOGGER.debug("Project to create : {}", projectDto);
un check à ajouter sur projectDto

2022-05-05 09:36 UTC, oussamasic commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/rest/CollectInternalController.java
> +        LOGGER.debug("Project to create {}", projectDto);
un check sur projectDto à ajouter avant le logger

2022-05-05 09:36 UTC, oussamasic commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/rest/CollectInternalController.java
> +            .debug("getPaginateEntities page={}, size={}, criteria={}, orderBy={}, ascendant={}", page, size, criteria,
un check à ajouter sur criteria avant le logger

2022-05-05 09:36 UTC, oussamasic commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/rest/CollectInternalController.java
> +        LOGGER.debug("[Internal] upload collect zip file : {}", originalFileName);
pour des raisons de sécurité, c'est mieux de changer l'ordre check et du logger

2022-05-05 09:36 UTC, oussamasic commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/collect/CollectInternalService.java
> +        }
c'est mieux de thrower des exceptions personnalisées.

2022-05-05 09:36 UTC, oussamasic commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/CollectProjectUploadDto.java
> +public class CollectProjectUploadDto extends IdDto {
cette classe a une utilité ou non ?

2022-05-05 09:36 UTC, oussamasic commented on deployment/roles/vitamui/files/customer-init.yml
> +        - ROLE_GET_TRANSACTIONS
Il faut ajouter ces rôles : 
            "ROLE_GET_EXTERNAL_PARAMS",
            "ROLE_GET_FILLING_PLAN_ACCESS",
            "ROLE_GET_COLLECT_TRANSACTIONS",
            "ROLE_GET_COLLECT_PROJECTS"

ROLE_GET_TRANSACTIONS à supprimer

2022-05-05 09:36 UTC, oussamasic commented on deployment/scripts/mongod/2.0.0/57_iam_ref.js.j2
> +            "name": "ROLE_GET_COLLECT_TRANSACTIONS",
il faut ces 4 rôles : 
            "ROLE_GET_EXTERNAL_PARAMS",
            "ROLE_GET_FILLING_PLAN_ACCESS",
            "ROLE_GET_COLLECT_TRANSACTIONS",
            "ROLE_GET_COLLECT_PROJECTS"

2022-05-05 09:36 UTC, oussamasic commented on deployment/scripts/mongod/2.0.0/57_iam_ref.js.j2
> +            $each: [
pas besoin du $each pour une valeur

2022-05-05 09:36 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/src/app/collect/projects/create-project/create-project.component.ts
> +  ];
à mettre dans les fichiers de traductions, 
on peut utiliser le TranslateService

2022-05-05 09:36 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/src/app/collect/projects/create-project/create-project.component.ts
> +                console.error(error)
console à supprimer, 
on peux utiliser le loggerService de VitamUI

2022-05-05 09:36 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/src/app/collect/projects/create-project/create-project.component.ts
> +                  "Téléchargement des fichiers terminé!",
à traduire et à mettre dans les fichiers de traductions

2022-05-05 09:36 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/src/app/collect/projects/create-project/create-project.component.ts
> +            console.error(error);
console à supprimer,
on peux utiliser le loggerService de VitamUI

2022-05-05 09:36 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/src/app/collect/projects/create-project/create-project.component.ts
> +      this.dateErrorMessage = 'La date de début ne peut être supérieure à la date de fin !';
à traduire et à mettre dans les fichiers de traductions

2022-05-05 09:36 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/src/app/collect/projects/project-list/project-list.component.ts
> +  onSelectRow(project: Project) {
est-ce que cette fonction est utile ?

2022-05-05 09:36 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/src/app/collect/projects/project-list/project-list.component.html
> +          (click)="onSelectRow(project)"
ce click est utile ?

2022-05-05 09:36 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/src/app/collect/projects/projects.component.ts
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
texte de copyright à mettre à jour

2022-05-05 09:36 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/src/app/collect/projects/projects.component.ts
> +  onSearch(event: string) {
fonction utile ?

2022-05-05 09:36 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/src/app/collect/projects/projects.component.html
> +        (search)="onSearch($event)"
c'est utile de passer onSearch aussi comme entrée ?

2022-05-05 09:36 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/src/app/collect/projects/projects.component.ts
> +        // Update project list
à compléter  !!

2022-05-05 09:36 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/src/app/collect/projects/projects.service.ts
> +/*
texte de copyright à mettre à jour

2022-05-05 09:36 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/src/app/collect/projects/projects.service.ts
> +  public updateProject(project: any) {
fonction utile ?

2022-05-05 09:36 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/src/app/collect/projects/create-project/create-project.component.html
> +          <button type="button" class="btn primary" (click)="updateProject()" [disabled]="validateFourStep()">{{ 'COMMON.SUBMIT' | translate }}</button>
le click est utile ?

2022-05-05 09:36 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/src/app/collect/shared/collect-confirm-upload/collect-confirm-upload.component.ts
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
texte de copyright à mettre à jour

2022-05-05 09:36 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/src/app/collect/shared/collect-upload/collect-upload-file.ts
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
idem

2022-05-05 09:36 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/src/app/collect/shared/collect-upload/collect-upload.service.ts
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
idem

2022-05-05 09:36 UTC, oussamasic commented on ui/ui-ingest/src/main/java/fr/gouv/vitamui/ingest/rest/CollectController.java
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
idem

2022-05-05 09:36 UTC, oussamasic commented on ui/ui-ingest/src/main/java/fr/gouv/vitamui/ingest/rest/CollectController.java
> +        LOGGER.info("Start uploading file ...{} ", filename);
debug ?

2022-05-05 09:36 UTC, oussamasic commented on ui/ui-ingest/src/main/java/fr/gouv/vitamui/ingest/rest/CollectController.java
> +        return collectService.createProject(buildUiHttpContext(), projectDto);
un petit check sur projectDto à ajouter

2022-05-05 09:36 UTC, oussamasic commented on ui/ui-ingest/src/main/java/fr/gouv/vitamui/ingest/rest/CollectController.java
> +        LOGGER.debug("getAllProjectsPaginated page={}, size={}, criteria={}, orderBy={}, ascendant={}", page, size, criteria,
un check sur criteria avant le debug

2022-05-05 09:36 UTC, oussamasic commented on ui/ui-ingest/src/main/java/fr/gouv/vitamui/ingest/service/CollectService.java
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
idem

2022-05-05 13:05 UTC, depysk commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/collect/CollectInternalService.java
> +        return ProjectDto.builder()
Oui

2022-05-05 13:31 UTC, depysk commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/CollectProjectUploadDto.java
> +public class CollectProjectUploadDto extends IdDto {
Oui, elle permet de récupérer l'id du projet créer

2022-05-06 14:08 UTC, oussamasic requested changes

2022-05-06 14:08 UTC, oussamasic commented on api/api-iam/iam-internal/pom.xml
> +                        -Xmx512m -Dvitam.config.folder=${basedir}/src/main/resources/dev/vitam
à supprimer

2022-05-06 14:08 UTC, oussamasic commented on api/api-ingest/ingest-internal/pom.xml
> +                    <jvmArguments>-Xmx512m -Dvitam.config.folder=${basedir}/src/main/resources/dev/vitam</jvmArguments>
à supprimer, vu que la manière de lancement a été changée

2022-05-06 15:20 UTC, GiooDev requested changes

2022-05-06 15:20 UTC, GiooDev commented on deployment/roles/vitamui/files/customer-init.yml
> +        - ROLE_GET_EXTERNAL_PARAMS,
il y a une virgule, est-ce normal ?

2022-05-06 15:22 UTC, GiooDev requested changes

2022-05-06 15:22 UTC, GiooDev commented on deployment/scripts/mongod/2.0.0/56_application_collect_ref.js.j2
> +    {% if vitamui.ingest.base_url is defined %}
Pourquoi faire 2x le même if que précédemment ? regrouper en 1 seul et attention à l'indentation

2022-05-06 15:32 UTC, oussamasic approved these changes

2022-05-06 15:42 UTC, depysk commented on deployment/roles/vitamui/files/customer-init.yml
> +        - ROLE_GET_EXTERNAL_PARAMS,
Corrigé

2022-05-06 15:42 UTC, depysk commented on deployment/scripts/mongod/2.0.0/56_application_collect_ref.js.j2
> +    {% if vitamui.ingest.base_url is defined %}
Simplification faite. Merci ;)

2022-05-10 09:41 UTC, laedanrex commented on api/api-ingest/ingest-commons/src/main/java/fr/gouv/vitamui/ingest/common/rest/RestApi.java
> +    public RestApi() throws UnsupportedOperationException {
ca peut être mis private :) 

et si y a lombock y a l'annot @UtilityClass

2022-05-10 12:37 UTC, GiooDev approved these changes

2022-06-14 15:25 UTC, closed without merging