[VAS] ITEM 9438 : manage access rules category (add, delete and update)
ProgrammeVitam/vitam-ui pull request #789
Opened 2022-05-04 14:24 UTC by oussamasic

## Description
L'objectif de cette PR est d'ajouter une nouvelle fonctionnalité qui permet de gérer les règles des UAs de type Communicabilité (AccessRule).

## Type de changement:

*Indiquer le ou les types de changements*

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

Pas de migration et pas de modification au niveau de la base de données

## Checklist:

*Sélectionner les éléments de la checklist*

[ X ] Mon code suit le style de code de ce projet.

[ X ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ X ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ X ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ X ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

2022-05-04 17:19 UTC, bbenaissa requested changes

2022-05-04 17:19 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchManagementRulesQueryBuilderService.java
>                      LOGGER.error("Invalid creation operation exception {}", exception);
On ne gère pas l'exception.?

2022-05-04 17:19 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchManagementRulesQueryBuilderService.java
>                      LOGGER.error("Invalid create operation {}", exception);
Idem

2022-05-05 13:49 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchManagementRulesQueryBuilderService.java
>                      LOGGER.error("Invalid creation operation exception {}", exception);
exception ajoutée

2022-05-05 13:49 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchManagementRulesQueryBuilderService.java
>                      LOGGER.error("Invalid create operation {}", exception);
exception ajoutée

2022-05-05 15:22 UTC, bbenaissa approved these changes

2022-05-05 15:37 UTC, merged