[VAS 9790] Set ingest status for list and preview
ProgrammeVitam/vitam-ui pull request #791
Opened 2022-05-05 09:53 UTC by laedanrex

## Description
Resynchronisation du status de l'ingest dans la preview et dans la liste

## Type de changement:

* Build
* Nouveau Code
* Refactorisation de code

## Tests:

manuel

## Checklist:

*Sélectionner les éléments de la checklist*

[x] Mon code suit le style de code de ce projet.

[x] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

## Contributeur

VAS (Vitam Accessible en Service)

2022-05-05 17:52 UTC, nabilm2i approved these changes

2022-05-05 17:52 UTC, nabilm2i commented on ui/ui-frontend/projects/ingest/src/app/models/ingests.interface.ts
> +}
À vérifier l'attribut ArchivalProfile ici. Le reste est bon pour moi.

2022-05-13 10:52 UTC, oussamasic approved these changes

2022-05-17 15:04 UTC, oussamasic requested changes

2022-05-17 15:04 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/models/logbook/api-event.interface.ts
> +// rename to ApiLogbookOperation
ce petit commentaire à supprimer

2022-05-17 15:04 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/src/app/ingest/ingest-list/ingest-list.component.ts
> +    this.updatedData.subscribe(() => this.ingestService.logbookOperationsReloaded.next(this.dataSource));
On peut ajouter une subscription ici, et la détruire après utilisation pour libérer un peu la mémoire.

2022-05-17 15:04 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.ts
> +    this.ingestService.getIngestOperation(this.ingestFromParent.id)
idem

2022-05-19 11:34 UTC, oussamasic approved these changes

2022-05-19 12:08 UTC, merged