story #9029 - adjust time to client timezone
ProgrammeVitam/vitam-ui pull request #794
Opened 2022-05-10 14:44 UTC by mascoun

2022-05-10 15:38 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.html
> +          ><span (click)="pickerSatrDate.open()">{{ form.get('startDate').value | dateTime: 'dd/MM/yyyy' }} </span>
Je suppose qu'il s'agit de `pickerStartDate` au lieu de `pickerSatrDate`  ;)

2022-05-10 15:38 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/add-management-rules/add-management-rules.component.html
> +            ><span (click)="pickerSatrDate.open()">{{ ruleDetailsForm.get('startDate').value | dateTime: 'dd/MM/yyyy' }} </span>
Idem ici ;)

2022-05-11 08:32 UTC, bbenaissa commented
Est ce que tu peux changer la version du module vitamui-frontend-common et mettre à jour la version dans ui-frontend

2022-05-11 08:35 UTC, mascoun commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.html
> +          ><span (click)="pickerSatrDate.open()">{{ form.get('startDate').value | dateTime: 'dd/MM/yyyy' }} </span>
j'ai pas touché à ce nom de variable, s'il faudra la corriger il faut le faire dans une autre PR

2022-05-11 09:24 UTC, bbenaissa approved these changes

2022-05-13 09:49 UTC, oussamasic requested changes

2022-05-13 09:49 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/pipes/datetime.pipe.spec.ts
> +import { DatePipe } from '@angular/common';
texte du copyright à ajouter,
lien vers le Code style et aussi le texte du copyright : [ici](https://assistance.programmevitam.fr/plugins/document/projetvitam/folder/50)

2022-05-13 09:49 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/pipes/datetime.pipe.ts
> +import { Pipe, PipeTransform } from '@angular/core';
texte du copyright à ajouter

2022-05-13 09:49 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/src/app/ingest/ingest-list/ingest-list.component.html
> +              {{ ingest?.evDateTime | dateTime: 'HH:mm:ss':'-2000' }}
-2000 à enlever, vu que ça va changer le timezone.

2022-05-13 09:49 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/src/app/ingest/ingest-list/ingest-list.component.html
> +              {{ ingestEndDate(ingest) | dateTime: 'HH:mm:ss':'-2000' }}
idem

2022-05-13 09:49 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.html
> +          <span>{{ (event | lastEvent)?.dateTime | dateTime: 'HH:mm:ss':'-2000' }}</span>
idem

2022-05-16 07:32 UTC, bbenaissa commented on ui/ui-frontend/projects/ingest/src/app/ingest/ingest-list/ingest-list.component.html
> +              {{ ingest?.evDateTime | dateTime: 'HH:mm:ss':'-2000' }}
+1

2022-05-16 07:32 UTC, bbenaissa commented on ui/ui-frontend/projects/ingest/src/app/ingest/ingest-list/ingest-list.component.html
> +              {{ ingestEndDate(ingest) | dateTime: 'HH:mm:ss':'-2000' }}
+1

2022-05-16 07:32 UTC, bbenaissa commented on ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.html
> +          <span>{{ (event | lastEvent)?.dateTime | dateTime: 'HH:mm:ss':'-2000' }}</span>
+1

2022-05-16 07:32 UTC, bbenaissa commented on ui/ui-frontend-common/src/app/modules/pipes/datetime.pipe.spec.ts
> +import { DatePipe } from '@angular/common';
+1

2022-05-17 09:50 UTC, oussamasic approved these changes

2022-05-18 13:18 UTC, laedanrex approved these changes

2022-05-19 09:28 UTC, bbenaissa approved these changes

2022-05-23 13:23 UTC, merged