[VAS] ITEM 9754 : manage storage rule category, add new actions
ProgrammeVitam/vitam-ui pull request #800
Opened 2022-05-19 09:50 UTC by oussamasic

## Description
L'objectif de cette PR est d'ajouter une nouvelle fonctionnalité qui permet de gérer les règles des UAs de type DUC (StorageRule).

## Type de changement:

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Tests:

manuel

environnement

TU

## Migration:

Pas de migration et pas de modification au niveau de la base de données

## Checklist:

*Sélectionner les éléments de la checklist*

[ X ] Mon code suit le style de code de ce projet.

[ X ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ X ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ X ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ X ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

2022-05-23 06:21 UTC, bbenaissa requested changes

2022-05-23 06:21 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.ts
> +    // if (this.criteriaSearchListToSave.length === 0) {
To delete comments

2022-05-23 06:21 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.ts
> +      console.log('hello', data);
to delete console logs

2022-05-23 06:21 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.ts
> +        console.log('pour la partie back', ruleSearchCriteriaDto);
delete console/log

2022-05-23 13:55 UTC, laedanrex approved these changes

2022-05-24 09:04 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.ts
> +        console.log('pour la partie back', ruleSearchCriteriaDto);
Done

2022-05-24 09:05 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.ts
> +      console.log('hello', data);
Done

2022-05-24 09:05 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.ts
> +    // if (this.criteriaSearchListToSave.length === 0) {
Done

2022-05-24 15:36 UTC, bbenaissa approved these changes

2022-05-24 15:49 UTC, merged