[WIP] [vas] 9919 add collect module
ProgrammeVitam/vitam-ui pull request #807
Opened 2022-05-25 09:40 UTC by mascoun

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2022-05-30 15:49 UTC, bbenaissa requested changes

2022-05-30 15:49 UTC, bbenaissa commented on api/api-collect/collect-internal/src/main/resources/application-dev.yml
> +  data:
Je crois qu'il n'y a pas de BD collect

2022-05-30 15:49 UTC, bbenaissa commented on api/api-collect/collect-internal/pom.xml
> +            <artifactId>spring-boot-starter-data-mongodb</artifactId>
Pas besoin de dépendences mongo puiqu'il n'y a pas de BD

2022-05-30 15:49 UTC, bbenaissa commented on api/api-collect/collect-internal/pom.xml
> +            <groupId>fr.gouv.vitamui.commons</groupId>
Idem

2022-05-30 15:49 UTC, bbenaissa commented on api/api-collect/collect-internal/pom.xml
> +        <dependency>
Idem

2022-05-30 15:49 UTC, bbenaissa commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/config/ApiCollectInternalServerConfig.java
> +@Import({RestExceptionHandler.class, MongoConfig.class, SwaggerConfiguration.class, WebSecurityConfig.class,
Pas besoin d'inclure MongoConfig

2022-05-30 15:49 UTC, bbenaissa commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/config/ApiIngestInternalServerConfig.java
> +import fr.gouv.vitam.collect.external.client.CollectClient;
Pourquoi cet import

2022-05-30 15:49 UTC, bbenaissa commented on deployment/ansible-vitamui/app_collect.yml
> +# Collect external calls archive internal
collect au lieu d'archive ??

2022-05-30 15:49 UTC, bbenaissa commented on deployment/ansible-vitamui/app_collect.yml
> +# UI collect calls archive external
Collect au lieu d'archive

2022-05-30 15:49 UTC, bbenaissa commented on deployment/environments/group_vars/all/vault-mongodb.yml.example
> +    collect:
Je crois qu'il n'y a pas de BD Collect dans Vitamui

2022-05-30 15:49 UTC, bbenaissa commented on deployment/environments/group_vars/all/vault-mongodb.yml
> -38616363643236383839353163356335666365643133666138386362326363393236343538386536
Je crois qu'il n'y a pas de BD Collect dans Vitamui

2022-05-30 15:49 UTC, bbenaissa commented on deployment/scripts/mongod/0.0.0/14_init-collect-database.js.j2
> +
Pas besoin de db

2022-05-30 15:49 UTC, bbenaissa commented on deployment/scripts/mongod/0.0.0/15_users-collect.js.j2
> +// Switch to collect database
Pas besoin de db

2022-05-30 15:49 UTC, bbenaissa commented on tools/docker/mongo/mongo_vars_dev.yml
> +  collect:
Pas besoin de db

2022-05-30 15:49 UTC, bbenaissa commented on ui/ui-frontend/projects/collect/src/assets/i18n/en.json
> +  "ARCHIVE_SEARCH": {
A supprimer le contenu, c'est spécifique au module archive

2022-05-30 15:49 UTC, bbenaissa commented on ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
> +{
Idem

2022-05-30 15:49 UTC, bbenaissa commented on ui/ui-frontend/projects/collect/src/assets/ontologies/ontologies.json
> +[
A supprimer

2022-05-30 15:52 UTC, bbenaissa commented
Il y a aussi le texte du copyright qui change d'un fichier à un autre en raison de copier/coller de l'ancien module archive-search. On trouve les dates 2020 sur certains et 2022 sur d'autres

2022-05-30 17:01 UTC, depysk reviewed
Le projet ne build pas en local sur mon poste

2022-05-30 17:01 UTC, depysk commented on api/api-collect/collect-commons/src/main/java/fr/gouv/vitamui/collect/common/rest/RestApi.java
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2015-2022)
2 copyrights à la suite, supprimer un des deux.

2022-05-30 17:01 UTC, depysk commented on api/api-collect/collect-commons/src/main/java/fr/gouv/vitamui/collect/common/rest/RestApi.java
> +    public static final String COLLECT_PATH = "/collect";
Ajouter un constructeur privé pour éviter la création d'une instance de la classe, vu qu'il s'agit d'une classe utilitaire ou utiliser l'annotation @UtilityClass de Lombok qui fait la même chose

2022-05-30 17:01 UTC, depysk commented on api/api-collect/collect-external-client/src/test/java/fr/gouv/vitamui/AppTest.java
> +        assertTrue( true );
Classe de test à compléter ou à supprimer

2022-05-30 17:01 UTC, depysk commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/ApiCollectExternalServerApplication.java
> +import org.springframework.context.ConfigurableApplicationContext;
Import non utilisé à supprimer

2022-05-30 17:01 UTC, depysk commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectExternalController.java
> +@RequestMapping(RestApi.COLLECT_PATH)
Ne serait-il pas mieux d'avoir `RestApi.COLLECT_PROJECT_PATH` à la place de `RestApi.COLLECT_PATH` avec la valeur r `collect/projects`

2022-05-30 17:01 UTC, depysk commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectExternalController.java
> +    @Secured(ServicesData.ROLE_GET_ACCESS_CONTRACTS) // FIXME
A supprimer ou définir clairement le rôle approprié

2022-05-30 17:01 UTC, depysk commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/service/CollectExternalService.java
> +    @Autowired private final CollectInternalWebClient projectInternalWebClient;
L'annotation @Autowired est inutile ici vu que le champ est déjà injecter par constructeur

2022-05-30 17:01 UTC, depysk commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/service/CollectExternalService.java
> +    @Autowired private final CollectInternalRestClient collectInternalRestClient;
L'annotation @Autowired est inutile ici vu que le champ est déjà injecter par constructeur

2022-05-30 17:01 UTC, depysk commented on api/api-collect/collect-internal-client/src/test/java/fr/gouv/vitamui/collect/internal/client/CollectInternalRestClientTest.java
> +
Classe de tests à supprimer ou à compléter

2022-05-30 17:01 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/core/api/collect-api.service.ts
> +      .pipe(tap((result) => result.values.map((ev) => (ev.parsedData = ev.data != null ? JSON.parse(ev.data) : null))));
Pas besoin de faire un parse ici `JSON.parse(ev.data)`

Faire simplement : 
````
return super
      .getAllPaginated(pageRequest, embedded, headers);
````

2022-06-01 08:33 UTC, depysk requested changes

2022-06-01 08:33 UTC, depysk commented on api/api-collect/collect-external-client/src/main/java/fr/gouv/vitamui/collect/external/client/CollectExternalRestClientFactory.java
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
Changer l'entête de la license. Il semblerait que ce ne soit pas le bon.

2022-06-01 08:33 UTC, depysk commented on api/api-collect/collect-external-client/src/main/java/fr/gouv/vitamui/collect/external/client/CollectExternalWebClientFactory.java
> + * and the signatories of the "VITAM - Accord du Contributeur" agreement.
Changer l'entête de la license. Il semblerait que ce ne soit pas le bon.

2022-06-01 08:33 UTC, depysk commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/config/ApiCollectExternalApplicationProperties.java
> + * contact.vitam@culture.gouv.fr
Changer l'entête de la license. Il semblerait que ce ne soit pas le bon.

2022-06-01 08:33 UTC, depysk commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/config/ApiCollectExternalServerConfig.java
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2015-2020)
Changer l'entête de la license. Il semblerait que ce ne soit pas le bon.

2022-06-01 08:33 UTC, depysk commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/config/ApiCollectExternalServerConfig.java
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2015-2020)
Changer l'entête de la license. Il semblerait que ce ne soit pas le bon.

2022-06-01 08:33 UTC, depysk commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/security/WebSecurityConfig.java
> + * contact.vitam@culture.gouv.fr
Changer l'entête de la license. Il semblerait que ce ne soit pas le bon.

2022-06-01 08:33 UTC, depysk commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/service/CollectExternalService.java
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2015-2020)
Changer l'entête de la license. Il semblerait que ce ne soit pas le bon.

2022-06-01 08:33 UTC, depysk commented on api/api-collect/collect-internal-client/src/main/java/fr/gouv/vitamui/collect/internal/client/CollectInternalWebClientFactory.java
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2015-2020)
Changer l'entête de la license. Il semblerait que ce ne soit pas le bon.

2022-06-01 08:33 UTC, depysk commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/security/WebSecurityConfig.java
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
Changer l'entête de la license. Il semblerait que ce ne soit pas le bon.

2022-06-02 09:09 UTC, depysk approved these changes

2022-06-02 12:23 UTC, bbenaissa approved these changes

2022-06-02 13:05 UTC, merged