[VAS] Feature/vas 9816 manage search and facets for storage rules
ProgrammeVitam/vitam-ui pull request #809
Opened 2022-05-30 07:54 UTC by bbenaissa

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2022-06-01 14:15 UTC, laedanrex approved these changes

2022-06-03 13:32 UTC, oussamasic requested changes

2022-06-03 13:32 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
> +        "STORAGE_RULE_START_DATE": "Date de début règle DUC",
il manque la traduction en anglais pour l'ensemble des clés ajoutées

2022-06-03 13:32 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchFacetsInternalService.java
> +        LOGGER.debug("Dsl query for auWithRulesFacets {} ", dslQuery.toPrettyString());
pour des raisons de performance, c'est mieux de logger le json directement, sans le parser en string

2022-06-03 13:32 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-storage-rules-facets/search-storage-rules-facets.component.ts
> +import { DatePipe } from '@angular/common';
il manque le texte du copyright

2022-06-03 13:32 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-storage-rules-facets/search-storage-rules-facets.component.ts
> +      color: 'gray',
on peut utiliser l'enum Colors, il y a plusieurs constantes gray et orange à remplacer par l'enum

2022-06-03 13:32 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/storage-rule-search/storage-rule-search.component.html
> +          [ngStyle]="{ 'background-color': 'green', width: '30', height: '30' }"
à mettre dans un fichier css c'est plus propre je pense

2022-06-03 13:32 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/storage-rule-search/storage-rule-search.component.ts
> +import { Component, Input, OnDestroy, OnInit } from '@angular/core';
il manque le texte du copyright

2022-06-03 13:32 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/storage-rule-search/storage-rule-search.component.ts
> +          'STRING',
pour l'opérateur EQ et le type STRING, et aussi pour les autres opérateurs + types, on a des  enum pour ça, on peut les utiliser directement dans le fichier et remplacer les différentes constantes

2022-06-06 07:11 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-storage-rules-facets/search-storage-rules-facets.component.ts
> +import { DatePipe } from '@angular/common';
Done

2022-06-06 07:11 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchFacetsInternalService.java
> +        LOGGER.debug("Dsl query for auWithRulesFacets {} ", dslQuery.toPrettyString());
Done

2022-06-06 07:11 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
> +        "STORAGE_RULE_START_DATE": "Date de début règle DUC",
Done

2022-06-06 07:11 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/storage-rule-search/storage-rule-search.component.ts
> +import { Component, Input, OnDestroy, OnInit } from '@angular/core';
Done

2022-06-06 07:31 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-storage-rules-facets/search-storage-rules-facets.component.ts
> +      color: 'gray',
Updated

2022-06-06 08:12 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/storage-rule-search/storage-rule-search.component.ts
> +          'STRING',
Oui, effectivement

2022-06-10 08:26 UTC, oussamasic approved these changes

2022-06-10 12:41 UTC, merged