[VAS] Story 9872 - track import holding scheme and filling scheme
ProgrammeVitam/vitam-ui pull request #817
Opened 2022-06-03 08:42 UTC by mascoun

## Description

Suivi des opérations de versement d'arbre et de plan

## Type de changement:

*Indiquer le ou les types de changements*

* Nouveau Code

* Correction

* Refactorisation de code

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[X] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2022-06-08 16:03 UTC, depysk requested changes

2022-06-08 16:03 UTC, depysk commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestInternalService.java
> +                return null;
Ne faudrait-il pas plutôt lever une exception?

2022-06-08 16:03 UTC, depysk commented on ui/ui-frontend/projects/ingest/src/app/core/common/upload.component.spec.ts
> +      schemas: [NO_ERRORS_SCHEMA],
Eviter d'utiliser `NO_ERRORS_SCHEMA`. Voici un petir post sur le sujet : 
https://medium.com/@fivedicephoto/why-you-shouldnt-use-no-errors-schema-in-angular-unit-tests-cdd478c30782

2022-06-08 16:03 UTC, depysk commented on ui/ui-frontend/projects/ingest/src/app/core/common/upload.component.ts
> +        if (this.contextId == 'HOLDING_SCHEME' || this.contextId == 'FILING_SCHEME') {
Regrouper les valeurs `HOLDING_SCHEME` et `FILING_SCHEME` dans une enum (scheme-type.enum.ts) pour éviter de les trimballer un peu partout

2022-06-08 16:03 UTC, depysk commented on ui/ui-frontend/projects/ingest/src/app/shared/vitamui-snack-bar/vitamui-snack-bar.component.html
> +      <span style="padding-right: 10px;">
créer de préférence une classe pour ce style
```
.p-e-10 {
    padding-right: 10px;
}
```

2022-06-09 13:18 UTC, bbenaissa requested changes

2022-06-09 13:18 UTC, bbenaissa commented on ui/ui-frontend/projects/ingest/src/app/shared/vitamui-snack-bar/vitamui-snack-bar.component.html
> +      <span style="padding-right: 10px;">
+1

2022-06-09 13:18 UTC, bbenaissa commented on ui/ui-frontend/projects/ingest/src/app/core/common/upload.service.ts
> +              callback(data.headers.get('X-Operation-Id'));
Dans le cas où il y  a une erreur; X-Operation-Id  va etre null, quel est le comportement attendu?

2022-06-09 13:18 UTC, bbenaissa commented on api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestInternalService.java
> +                return null;
Tout dépend du comportement attendu, mais effectivement ici ça pose question

2022-06-10 08:34 UTC, oussamasic requested changes

2022-06-10 08:34 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/src/app/core/common/upload.component.ts
> +              console.log(operationId);
log à supprimer, tu peux utiliser le loggerService

2022-06-10 08:34 UTC, oussamasic commented on ui/ui-frontend/projects/ingest/src/app/core/common/upload.component.ts
> +          this.message = error.message;
idem : log à supprimer, tu peux utiliser le loggerService

2022-06-14 15:04 UTC, abdelmoez-guetat commented on ui/ui-frontend/projects/ingest/src/app/core/common/upload.service.ts
> +              callback(data.headers.get('X-Operation-Id'));
X-Operation-Id ne peut pas être null

2022-06-14 16:10 UTC, bbenaissa approved these changes

2022-06-14 16:22 UTC, oussamasic approved these changes

2022-06-15 08:21 UTC, depysk approved these changes

2022-06-16 14:05 UTC, merged