item#9817 Add profil for consulting agencies
ProgrammeVitam/vitam-ui pull request #827
Opened 2022-06-13 08:23 UTC by GhrabSaifEddine

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2022-06-13 09:11 UTC, bbenaissa requested changes

2022-06-13 09:11 UTC, bbenaissa commented on deployment/scripts/mongod/1.0.0/01_iam_ref.js.j2
> +db.profiles.insert({
Il faudra créer un nouveau script, et le placer dans le repertoire 6.0

2022-06-13 09:11 UTC, bbenaissa commented on deployment/scripts/mongod/1.0.0/01_iam_ref.js.j2
> +db.profiles.insert({
Il faudra créer un nouveau script, et le placer dans le repertoire 6.0, sinon ce script ne sera jamais executé

2022-06-13 10:03 UTC, GhrabSaifEddine commented on deployment/scripts/mongod/1.0.0/01_iam_ref.js.j2
> +db.profiles.insert({
- Pourquoi il ne sera jamais exécuté : lors d'une install, on ne lance pas les scripts du dossier 1.0.0 ?

-  Comment vous gérez la nomenclature des dossiers ( je vois des 1.0.0, 1.1.0, 2.0.0, 2_collect, 5.4.0 ) Il faudrait avoir une règle précise qui organise tout ça et à renseigner dans un README pour savoir quand et où mettre les nouveaux scripts à venir.

2022-06-13 10:24 UTC, oussamasic requested changes

2022-06-13 10:24 UTC, oussamasic commented on deployment/scripts/mongod/1.0.0/01_iam_ref.js.j2
> +db.profiles.insert({
- Pour une nouvelle installation le script sera exécuté mais  lors d'une migration non, vu que le script est déjà exécuté avant.
- Actuellement on a pas une règle précise pour la création de ces répertoires, on essaie de créer un répertoire pour chaque release

2022-06-13 10:29 UTC, bbenaissa commented on deployment/scripts/mongod/1.0.0/01_iam_ref.js.j2
> +db.profiles.insert({
- Pour la 1ere question: le pricnipe d'execution des scripts ressemble à celui de Luiquibase, ce que signifie que lorsque le script est executé une fois, il ne sera pas executé une nouvelle fois,  donc, toute modification dans un ancien script, ne sera pas executé sur une installation déja faite.
- Pour la doc, elle est dans le repo , je te l'envoie

2022-06-13 12:20 UTC, oussamasic requested changes

2022-06-13 12:20 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/agency/agency-list/agency-list.component.html
> +              appId: 'AGENCIES_APP',
si je me trompe pas (à tester), l'utilisation de la directive `vitamuiCommonHasRole` va masquer le bouton ou lieu de le désactiver.
si l'objectif est de le supprimer on peux laisser cette directive, sinon pour griser le bouton on utilise le service : la fonction `hasRole` dans (`SecurityService`)

2022-06-13 15:04 UTC, GhrabSaifEddine commented on ui/ui-frontend/projects/referential/src/app/agency/agency-list/agency-list.component.html
> +              appId: 'AGENCIES_APP',
Effectivement, ca devrait être caché juste pour le bouton delete mais pas pour les autres. Du coup, modification déja pris en compte.

2022-06-14 09:17 UTC, bbenaissa approved these changes

2022-06-14 09:27 UTC, GiooDev requested changes

2022-06-14 09:27 UTC, GiooDev commented on deployment/scripts/mongod/6.0.0/01_iam_referential.js.j2
> +print("START 01_iam_referential.js");
Le nom du fichier ainsi que le print est pas très représentatif.

2022-06-14 09:27 UTC, GiooDev commented on deployment/scripts/mongod/6.0.0/01_iam_referential.js.j2
> +
Pas besoin de créer ce nouveau profil pour les tenants déjà existants ? 

Car il fait partie du customer init, donc à l'initialisation d'un nouveau tenant il sera créé. Mais quid des tenants déjà existants ?

2022-06-14 09:31 UTC, bbenaissa commented on deployment/scripts/mongod/6.0.0/01_iam_referential.js.j2
> +
Non pas besoin, puisque les tenants existants auront tjrs le profil full, qui existe déjà

2022-06-14 09:46 UTC, oussamasic requested changes

2022-06-14 09:46 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/agency/agency.component.ts
> +  hasRole(role: string) {
fonction intitule je pense

2022-06-14 10:48 UTC, GiooDev commented on deployment/scripts/mongod/6.0.0/01_iam_referential.js.j2
> +
Donc quel intérêt de créer ce nouveau profil pour les nouvelles organisations ? Si c'est pas nécessaire, à retirer du customer-init non ?

2022-06-14 12:22 UTC, bbenaissa commented on deployment/scripts/mongod/6.0.0/01_iam_referential.js.j2
> +
le fait de le créer et l'ajouter dans customer-init c'est pour le rendre accessible pour les organisations,  qui ont de toute façon par défaut le profil full, mais peuvent pour par exemple limiter les accès à certains de leurs users, en créant un nouveau groupe et en choisissant ce profil de consultation au lieu du profil full.

2022-06-14 12:23 UTC, bbenaissa approved these changes

2022-06-14 12:53 UTC, oussamasic approved these changes

2022-06-14 13:49 UTC, GhrabSaifEddine commented
- Le nom du répo sous scripts/mongod fait référence à la version de la release.
- Une doctrine a été précisée pour la nomenclature des fichiers scripts en spécifiant ( brièvement )la fonctionnalité concernée.

2022-06-14 14:38 UTC, GiooDev commented on deployment/scripts/mongod/6.0.0/01_iam_referential.js.j2
> +
Oui donc pourquoi les organisations existantes ne voudraient pas la même possibilité ?

2022-06-14 14:43 UTC, oussamasic commented on deployment/scripts/mongod/6.0.0/01_iam_referential.js.j2
> +
point discuté avec les POs, on garde le profil qui a les droits full pour les utilisateurs existants, après c'est à l'administrateur de l’organisation de gérer les droits et les groupes de ces users.

2022-06-15 08:47 UTC, GiooDev requested changes

2022-06-15 08:47 UTC, GiooDev commented on deployment/scripts/mongod/6.rc.0/02_migrate_profils_for_existant_agencies.js.j2
> +db = db.getSiblingDB('iam');
C'est pas vraiment une migration de profiles, ce morceau de script pourrait être intégré au script précédent directement.

2022-06-15 10:52 UTC, GhrabSaifEddine commented on deployment/scripts/mongod/6.rc.0/02_migrate_profils_for_existant_agencies.js.j2
> +db = db.getSiblingDB('iam');
Fonctionnellement, c'est une migration vu qu'il s'agit de faire des MAJ par rapport aux données déjà existantes. D'ailleurs, ce script n'a pas vocation a être exécuté sur une install from scratch.

2022-06-15 12:05 UTC, GiooDev commented on deployment/scripts/mongod/6.rc.0/02_migrate_profils_for_existant_agencies.js.j2
> +db = db.getSiblingDB('iam');
Oui il n'a pas vocation à être joué sur une installation from scratch mais il le sera malgré tout.

Pour les précédents scripts ainsi, on mutualisait dans un seul et unique script les 2 parties car cela ajoute bien un nouveau profil. Bref comme vous voulez, mais y'a déjà beaucoup de scripts dans ce répertoire et mutualiser dans un seul simplifie la relecture je pense car tout est effectué au même endroit et on a pas besoin de regarder ailleurs ce qui sera rajouté.

2022-06-15 13:06 UTC, GhrabSaifEddine commented on deployment/scripts/mongod/6.rc.0/02_migrate_profils_for_existant_agencies.js.j2
> +db = db.getSiblingDB('iam');
Ok, je les merge ensemble..

2022-06-15 13:08 UTC, GiooDev approved these changes

2022-06-15 13:27 UTC, merged

2022-06-15 14:02 UTC, depysk commented on ui/ui-frontend/projects/referential/src/app/agency/agency.component.ts
> +    this.route.params.subscribe((params) => {
Subscrible sans unsubscribe dans ngDestroy() ==> memory leak
Faire de même pour ceux en dessous ;)

2022-06-15 14:02 UTC, depysk commented on ui/ui-frontend/projects/referential/src/app/agency/agency-preview/agency-information-tab/agency-information-tab.component.ts
> +    this.route.params.subscribe((params) => {
Subscrible sans unsubscribe dans ngDestroy() ==> memory leak
Faire de même pour ceux en dessous ;)

2022-06-17 09:50 UTC, GiooDev commented on ui/ui-frontend/projects/referential/src/app/agency/agency.component.ts
> +    this.route.params.subscribe((params) => {
Est-ce que tes remarques sont corrigées quelque part ? Car ça avait été déjà mergé ?

2022-06-17 09:53 UTC, bbenaissa commented on ui/ui-frontend/projects/referential/src/app/agency/agency.component.ts
> +    this.route.params.subscribe((params) => {
Saief etait en train de préparer une autre PR sur ce sujet

2022-06-17 10:02 UTC, GhrabSaifEddine commented on ui/ui-frontend/projects/referential/src/app/agency/agency.component.ts
> +    this.route.params.subscribe((params) => {
Je suis entrain de faire une passe sur la partie que jai rajouté vu qu'il y a un bug d'affichage : ( le subscribe est en retard par rapport à l'affichage du composant ). Dés que c'est fait, je soumettrai la MR. Par la suite une 2éme MR de clean code devrait MAJ tout les autes subscribe afin d'éviter de les construire sans les détruire enfin de constrution du composant.

2022-06-17 10:13 UTC, GiooDev commented on ui/ui-frontend/projects/referential/src/app/agency/agency.component.ts
> +    this.route.params.subscribe((params) => {
Ok parfait, c'était juste pour être sûr que ce soit bien pris en compte :)