[VAS] ITEM 8645 : Block and unlock a rule inheritance
ProgrammeVitam/vitam-ui pull request #828
Opened 2022-06-13 16:47 UTC by oussamasic

2022-06-14 15:17 UTC, bbenaissa requested changes

2022-06-14 15:17 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchManagementRulesQueryBuilderService.java
> +                    LOGGER.error("Invalid creation operation exception {}", exception);
S'il y a une erreur on fait que la logger?

2022-06-15 13:40 UTC, bbenaissa approved these changes

2022-06-15 13:50 UTC, laedanrex approved these changes

2022-06-15 14:04 UTC, merged