[VAS] Item 9920 : [SEDACCORD] Create and list projects
ProgrammeVitam/vitam-ui pull request #830
Opened 2022-06-14 12:19 UTC by depysk

## Description

* Add new collect's project
* List existing projects

## Type de changement:

* Ansiblerie

* Nouveau Code

## Tests:

* TU, manuel

## Checklist:

*Sélectionner les éléments de la checklist*

[x] Mon code suit le style de code de ce projet.

[x] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[x] Les tests unitaires nouveaux et existants passent avec succès localement.

## Contributeur

VAS (Vitam Accessible en Service)

2022-06-14 14:03 UTC, oussamasic requested changes

2022-06-14 14:03 UTC, oussamasic commented on api/api-collect/collect-commons/src/main/java/fr/gouv/vitamui/collect/common/dto/CollectListProjectDto.java
> +package fr.gouv.vitamui.collect.common.dto;
il manque le texte du copyright

2022-06-14 14:03 UTC, oussamasic commented on api/api-collect/collect-commons/src/main/java/fr/gouv/vitamui/collect/common/dto/CollectProjectDto.java
> +package fr.gouv.vitamui.collect.common.dto;
il manque le texte du copyright

2022-06-14 14:03 UTC, oussamasic commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectExternalController.java
> +        SanityChecker.isValidFileName(originalFileName);
un autre check sur `projectId` à ajouter

2022-06-14 14:03 UTC, oussamasic commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectExternalController.java
> +        SanityChecker.sanitizeCriteria(collectProjectDto);
un autre check sur `id` à ajouter, en utilisant le `checkSecuredParam`

2022-06-14 14:03 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/ProjectInternalController.java
> +        SanityChecker.isValidFileName(originalFileName);
un autre check de vérification à ajouter sur projectId

2022-06-14 14:03 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/ProjectInternalController.java
> +        SanityChecker.sanitizeCriteria(collectProjectDto);
idem sur id

2022-06-14 14:03 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/project/ProjectInternalService.java
> +        }
même exception envoyée, du coup à rassembler  les deux exceptions dans un seul catch

2022-06-14 14:03 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/project/ProjectInternalService.java
> +        }
idem

2022-06-14 14:03 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/project/ProjectInternalService.java
> +        } catch (VitamClientException e) {
on peux logger l’exception

2022-06-14 14:03 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/project/ProjectInternalService.java
> +    }
idem pour ces deux exceptions

2022-06-14 14:03 UTC, oussamasic commented on deployment/scripts/mongod/2_collect/application_ref.js.j2
> +    { "name": "ROLE_UPDATE_PROJECTS" },
créer un autre script pour faire l'update de ce profil

2022-06-14 14:03 UTC, oussamasic commented on deployment/scripts/mongod/2_collect/application_ref.js.j2
> +    { "name": "ROLE_UPDATE_PROJECTS" },
créer un autre script pour faire l'update de ce profil

2022-06-14 14:03 UTC, oussamasic commented on deployment/scripts/mongod/2_collect/security_ref.js.j2
> +      "ROLE_UPDATE_PROJECTS"
idem

2022-06-14 14:03 UTC, oussamasic commented on ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/ProjectController.java
> +            .checkParameter("The tenantId and projectId are mandatory parameters : ",
un autre check plus sécurisé sur `tenantId` et `projectId`

2022-06-14 14:03 UTC, oussamasic commented on ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/ProjectController.java
> +        ParameterChecker.checkParameter("The Identifier is a mandatory parameter: ", id);
idem sur id

2022-06-14 14:03 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/collect.component.ts
> -/*Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2022)
je pense qu'o c'est mieux de supprimer le composant entièrement avec ces fichiers (ts, html et css) au lieu de les laisser vides

2022-06-14 14:03 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
> +  }
to delete, fonction inutile

2022-06-14 14:03 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/projects/project-list/project-list.component.ts
> +      title: 'En cours',
les titres des facettes n'ont pas besoin de traduction ?

2022-06-14 14:23 UTC, depysk commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/project/ProjectInternalService.java
> +        }
Il s'agit de deux exceptions distinctes ;) . 
La première concerne une exception VITAM => impossible de créer le projet
La deuxième concerne VitamUi => le projet a été créer côté VITAM mais la réponse n'a pas été bien interpréter

2022-06-14 14:23 UTC, depysk commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/project/ProjectInternalService.java
> +        }
Il s'agit de deux exceptions distinctes ;) . 
La première concerne une exception VITAM => impossible de créer le projet
La deuxième concerne VitamUi => le projet a été créer côté VITAM mais la réponse n'a pas été bien interpréter

2022-06-14 14:23 UTC, depysk commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/project/ProjectInternalService.java
> +    }
Il s'agit de deux exceptions distinctes ;) . 
La première concerne une exception VITAM => impossible de créer le projet
La deuxième concerne VitamUi => le projet a été créer côté VITAM mais la réponse n'a pas été bien interpréter

2022-06-14 16:01 UTC, oussamasic approved these changes

2022-06-14 16:01 UTC, oussamasic commented on deployment/scripts/mongod/2_collect/update_collect_profile_ref.js.j2
> +        {"name": "ROLE_GET_EXTERNAL_PARAMS"},
à ajouter aussi dans le customer-init

2022-06-15 14:13 UTC, bbenaissa requested changes

2022-06-15 14:13 UTC, bbenaissa commented on api/api-iam/iam-internal/src/main/resources/dev/customer-init.yml
> +        - ROLE_GET_EXTERNAL_PARAMS
Pourquoi le role ROLE_GET_EXTERNAL_PARAMS ?

2022-06-15 14:13 UTC, bbenaissa commented on deployment/roles/vitamui/files/customer-init.yml
> +        - ROLE_GET_EXTERNAL_PARAMS
Idem pour ROLE_GET_EXTERNAL_PARAMS

2022-06-15 14:13 UTC, bbenaissa commented on deployment/scripts/mongod/2_collect/update_collect_profile_ref.js.j2
> +        {"name": "ROLE_GET_EXTERNAL_PARAMS"},
idem ROLE_GET_EXTERNAL_PARAMS

2022-06-15 14:13 UTC, bbenaissa commented on deployment/scripts/mongod/2_collect/update_collect_profile_ref.js.j2
> +
Est ce que tu peux déplacer ces scripts dans le dossier 6.0 ou 6-rc stp

2022-06-15 14:13 UTC, bbenaissa commented on deployment/scripts/mongod/2_collect/update_collect_security_ref.js.j2
> +        "ROLE_GET_EXTERNAL_PARAMS",
idem

2022-06-15 14:13 UTC, bbenaissa commented on deployment/scripts/mongod/2_collect/update_collect_profile_ref.js.j2
> +
Est ce que tu peux mettre un n0 devant oiyr déterminer un ordre stp

2022-06-16 09:04 UTC, laedanrex approved these changes

2022-06-16 09:07 UTC, bbenaissa approved these changes

2022-06-16 09:11 UTC, merged