[CINES] Feature/contrat gestion
ProgrammeVitam/vitam-ui pull request #845
Opened 2022-06-21 08:58 UTC by alexandregranier

## Description

Application du référentiel permettant de créer et modifier les contrats de gestion de VITAM.

### Fonctionnalités
 - Affichage de la liste des contrats de gestions.
 - Création / modification
 - Une revue fonctionnelle sera à prévoir notamment pour :
   -  la notion de "politique de conservation de fichiers" non implémenté.
   - la vérification que la stratégie de stockage choisie existe bien dans VITAM

## Type de changement:

* Ansiblerie
4 fichiers de scripts mongo
Ansiblerie à vérifier

* Nouveau Code
Une partie dans le back ui-referential, referential-external, referential-internal, referential-commons

Une partie dans le front
vitam-ui/ui/ui-frontend/projects/referential/src/app/management-contract/*

* Correction
L'url d'accès est "management-contract".
Quelques modifications dans les classes ManagementContract* qui existaient déjà mais qui étaient incomplètes.

* Refactorisation de code
Pas de refactorisation

## Documentation:

Pas de mise à jour de la documentation.

## Tests:

Tests unitaires sur les parties back.

## Migration:

Sur une installation existante, il faudra ajouter les entrées dans mongo, voir fichiers dans 
deployment/scripts/mongod/
07_create_profile_MANAGEMENT_CONTRACT_APP.js.j2
08_create_application_MANAGEMENT_CONTRACT_APP.js.j2
09_add_role_for_MANAGEMENT_CONTRACT_APP.js.j2
10_add_profile_id_for_MANAGEMENT_CONTRACT_APP.js.j2

## Checklist:

*Sélectionner les éléments de la checklist*

[x ] Mon code suit le style de code de ce projet.

[ x] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

Pas de points difficiles.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[x ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeurs

Julien Couzinié, Alexandre Granier
CINES

2022-06-21 11:56 UTC, GiooDev requested changes

2022-06-21 11:56 UTC, GiooDev commented on deployment/scripts/mongod/1.0.0/321_iam_ref.js.j2
> +db = db.getSiblingDB('iam')
Renommer ces scripts, l'intitulé _ref c'est pour signifier que ce sont les scripts de référence. Ils doivent ainsi être renommés en fonction de la partie touchée.

2022-06-21 11:56 UTC, GiooDev commented on deployment/scripts/mongod/1.0.0/322_application_ref.js.j2
> +{% endif %}
Pas besoin de `else` ici ?

cf. par exemple `scripts/mongod/6.rc.0/02_add_collect_module_application.js.j2`

2022-06-21 11:56 UTC, GiooDev commented on deployment/scripts/mongod/1.0.0/322_application_ref.js.j2
> +    "serviceId": "^https://dev.vitamui.com:4202/.*"
Adresse en dur... voir cf. pour un exemple d'implémentation `scripts/mongod/6.rc.0/02_add_collect_module_application.js.j2`

2022-06-21 11:56 UTC, GiooDev commented on deployment/scripts/mongod/1.0.0/322_application_ref.js.j2
> +db = db.getSiblingDB('iam')
Dans l'ordre d'exécution, ce script est joué après la création des profils.

Il n'y a pas de dépendances fortes entre les collections dans Mongo mais est-ce logique de créer l'application après les profils associés ?

2022-06-21 11:56 UTC, GiooDev commented on deployment/scripts/mongod/1.0.0/321_iam_ref.js.j2
> +db.profiles.insert({
Quid des tenants déjà existants ? Il n'y a pas besoin de créer ce nouveau profil pour les autres customers ?

cf. par exemple `scripts/mongod/6.rc.0/02_add_collect_module_application.js.j2`

2022-06-21 11:56 UTC, GiooDev commented on deployment/scripts/mongod/1.0.0/321_iam_ref.js.j2
> +db = db.getSiblingDB('iam')
De plus, si c'est des nouvelles features pour la v6.rc, déplacer ces scripts dans le répertoire associé à la version `6.rc.0`

2022-06-21 11:56 UTC, GiooDev commented on deployment/scripts/mongod/1.0.0/321_iam_ref.js.j2
> +db.profiles.insert({
Si oui, ne pas oublier non plus de le renseigner dans le fichier `roles/vitamui/files/customer-init.yml` pour qu'il soit créé avec les nouvelles organisations.

2022-07-18 10:40 UTC, oussamasic requested changes

2022-07-18 10:40 UTC, oussamasic commented on .run/2 - Security-Internal.run.xml
> -<component name="ProjectRunConfigurationManager">
à ne pas supprimer les fichiers du lancement des différents services.

2022-07-18 10:40 UTC, oussamasic commented on .run/3 - IAM-Internal.run.xml
> -<component name="ProjectRunConfigurationManager">
idem

2022-07-18 10:40 UTC, oussamasic commented on .run/7 - UI-Identity back.run.xml
> -<component name="ProjectRunConfigurationManager">
idem

2022-07-18 10:40 UTC, oussamasic commented on .run/6 - UI-Portal back.run.xml
> -<component name="ProjectRunConfigurationManager">
idem

2022-07-18 10:40 UTC, oussamasic commented on .run/4 - IAM-External.run.xml
> -<component name="ProjectRunConfigurationManager">
idem

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dto/ManagementContractVitamDto.java
> + * As a counterpart to the access to the source code and  rights to copy,
Ancien texte de copyright,
voici le lien vers le nouveau texte avec le nouveau codeStyle : [ici](https://assistance.programmevitam.fr/plugins/document/projetvitam/folder/50)

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamUIManagementContractService.java
> + *
Ancien texte de copyright,
voici le lien vers le nouveau texte avec le nouveau codeStyle : [ici](https://assistance.programmevitam.fr/plugins/document/projetvitam/folder/50)

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamUIManagementContractService.java
> +        LOGGER.info("Management Contract EvIdAppSession : {} " , vitamContext.getApplicationSessionId());
debug ? 
Message pas clair, dois-je enlever la ligne LOGGER.debug ?

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamUIManagementContractService.java
> +        LOGGER.debug("patch: {}, {}", id, jsonNode);
il faut ajouter un check de sanitizing sur l' id et le jsonNode avant le log

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/VitamUIManagementContractServiceTest.java
> +package fr.gouv.vitamui.referential.common.service;
il manque le texte du copyright

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ManagementContractExternalController.java
> +        LOGGER.debug("get managementcontract  identifier={}", identifier);
il faut sanitizer l'id avant le log (on a des méthodes dans SanityCheker)

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ManagementContractExternalController.java
> +        LOGGER.debug("check exist managementContract={}", managementContractDto);
il faut du sanitizing sur managementContractDto avant le log

 -> je ne sais pas comment

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ManagementContractExternalController.java
> +        LOGGER.debug("Create {}", managementContractDto);
idem : vérifier managementContractDto avant le log

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ManagementContractExternalController.java
> +        ParameterChecker.checkParameter("The Identifier is a mandatory parameter: ", id);
- Pour des raisons de sécurité : il faut logger après le sanitizing (faille du log4j)
- Il faut du sanitizing sur l'id et aussi sur partialDto (utiliser SanityChecker).

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ManagementContractExternalController.java
> +        ParameterChecker.checkParameter("Identifier is mandatory : " , id);
- Pour des raisons de sécurité : il faut logger après le sanitizing (faille du log4j)
- Il faut du sanitizing sur l'id (utiliser SanityChecker).

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/rest/ManagementContractExternalControllerTest.java
> +package fr.gouv.vitamui.referential.external.server.rest;
il manque le texte du copyright

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/service/ManagementContractExternalServiceTest.java
> +package fr.gouv.vitamui.referential.external.server.service;
idem, il manque le texte du copyright

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +            LOGGER.info("Management Contract EvIdAppSession : {} " , vitamContext.getApplicationSessionId());
debug ?

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +        } catch (VitamClientException | JsonProcessingException e) {
un petit log avant le throw

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +        LOGGER.info("All Management Contracts EvIdAppSession : {} " , vitamContext.getApplicationSessionId());
debug ?

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +            throw new InternalServerException("Can't parse criteria as Vitam query", e);
un petit log avant les throw

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +            LOGGER.info("All Management Contracts EvIdAppSession : {} " , vitamContext.getApplicationSessionId());
debug ?

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +            throw new InternalServerException("Unable to find Management Contracts", e);
un log avant le throw

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +            LOGGER.info("Management Contract Check EvIdAppSession : {} " , vitamContext.getApplicationSessionId());
debug

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +            return true;
on throw aucune exception ??

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +            LOGGER.info("Create Management Contract EvIdAppSession : {} " , vitamContext.getApplicationSessionId());
debug

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +            throw new InternalServerException("Can't create management contract", e);
un petit log avant le throw

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +                    case "objectStrategy": propertyName = "ObjectStrategy";break;
default case ??

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +            LOGGER.info("Patch Management Contract EvIdAppSession : {} " , vitamContext.getApplicationSessionId());
debug

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +            throw new InternalServerException("Can't patch management contract", e);
un petit log avant les deux throw

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +            LOGGER.info("Management Contract History EvIdAppSession : {} " , vitamContext.getApplicationSessionId());
debug ?

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +            throw new InternalServerException("Unable to fetch history", e);
idem, log avant le throw

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/ManagementContractInternalController.java
> +        LOGGER.debug("get managementContract identifier={} / {}", identifier, URLDecoder.decode(identifier, StandardCharsets.UTF_8.toString()));
il manque le sanitizing du 'identifier'

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/ManagementContractInternalController.java
> +        LOGGER.debug("check exist managementContract={}", managementContractDto);
il manque le sanitizing du managementContractDto avant le log

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/ManagementContractInternalController.java
> +        LOGGER.debug("create managementContract={}", managementContractDto);
un sanitize de managementContractDto avant le log

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/ManagementContractInternalController.java
> +        LOGGER.debug("Patch {} with {}", id, partialDto);
un sanitize du partialDto et id avant le log

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/ManagementContractInternalController.java
> +        LOGGER.debug("get logbook for managementContract with id :{}", id);
un sanitize de l'id avant le log

2022-07-18 10:40 UTC, oussamasic commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/ManagementContractInternalServiceTest.java
> +package fr.gouv.vitamui.referential.internal.server.service;
il manque le texte du copyright

2022-07-18 10:40 UTC, oussamasic commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ManagementContractDto.java
> +/**
texte du copyrigth à changer

2022-07-18 10:40 UTC, oussamasic commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ManagementContractModelDto.java
> +/**
texte du copyright à mettre à jour

2022-07-18 12:17 UTC, oussamasic requested changes

2022-07-18 12:17 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +        }
bloc qui fait rien, à supprimer ou à ajouter le traitement associé

2022-07-18 12:17 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +        if (id == null) {
un petit log avant le throw

2022-07-19 13:11 UTC, oussamasic requested changes

2022-07-19 13:11 UTC, oussamasic commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/StorageDetailDto.java
> + * This software is a computer program whose purpose is to implement
à mettre à jour

2022-07-19 13:11 UTC, oussamasic commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/VersionRetentionPolicyDto.java
> +package fr.gouv.vitamui.commons.api.domain;
texte du copyright à ajouter

2022-07-19 13:11 UTC, oussamasic commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/VersionUsageDto.java
> +import com.fasterxml.jackson.annotation.JsonProperty;
texte du copyright à ajouter

2022-07-19 13:11 UTC, oussamasic commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/VersionUsageDto.java
> +    }
à ajouter dans un autre fichier c'est plus propre

2022-07-19 13:11 UTC, oussamasic commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/administration/ManagementContractService.java
> + *
à mettre à jour

2022-07-19 13:11 UTC, oussamasic commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/administration/ManagementContractService.java
> +            model.setTenant(null);
est-ce qu'il y a une raison pour ne pas mettre l'id du tenant ?

2022-07-19 13:11 UTC, oussamasic commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/administration/ManagementContractService.java
> +    }
fileName non utilisé

2022-07-19 13:11 UTC, oussamasic commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/administration/ManagementContractService.java
> +    public RequestResponse<?> createManagementContracts(final VitamContext vitamContext, final InputStream managementContract)
Il est fortement recommandé de ne pas utiliser de types génériques comme types de retour.

2022-07-19 13:11 UTC, oussamasic commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/administration/ManagementContractService.java
> +    public RequestResponse<?> createManagementContract(final VitamContext vitamContext, final InputStream managementContract, String fileName)
Il est fortement recommandé de ne pas utiliser de types génériques comme types de retour.

2022-07-19 13:11 UTC, oussamasic commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamUIManagementContractService.java
> +    public RequestResponse<?> patchManagementContract(final VitamContext vitamContext, final String id, JsonNode jsonNode) throws InvalidParseOperationException, AccessExternalClientException {
Il est fortement recommandé de ne pas utiliser de types génériques comme types de retour.

2022-07-19 13:11 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +            RequestResponse<?> requestResponse = vitamUIManagementContractService.patchManagementContract(vitamContext, id, query);
Il est fortement recommandé de ne pas utiliser de types génériques comme types de retour.

2022-07-19 13:11 UTC, oussamasic commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/ManagementContractResponseDto.java
> + * contact@programmevitam.fr
à mettre à jour

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/core/api/management-contracts-api.service.ts
> + *
à mettre à jour

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.spec.ts
> +  });
à compléter ou à supprimer

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.ts
> + * contact@programmevitam.fr
à mettre à jour

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.ts
> +
```suggestion
      this.keyPressSubscription?.unsubscribe();
      this.statusControlValueChangesSubscribe?.unsubscribe();

```

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.ts
> +        console.error(error);
console à supprimer, on peux utiliser le logger

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.module.ts
> + *
à mettre à jour

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.ts
> +    this.managementContractService.create(managementContract).subscribe(
à définir dans une subscription pour éviter les problèmes de surcharge de la mémoire, après la détruire dans le ngOnDestroy

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.validators.spec.ts
> + * contact@programmevitam.fr
texte à mettre à jour

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.validators.ts
> + *
idem

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-list/management-contract-list.component.html
> +        <!-- TODO: Change labels for i18n -->
to delete

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-list/management-contract-list.component.html
> +    <!--tbody vitamuiCommonCollapseContainer-->
to delete

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-list/management-contract-list.component.html
> +          <!-- TODO: Add date pipe -->
to delete

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-list/management-contract-list.component.spec.ts
> + * contact@programmevitam.fr
copyright à mettre à jour

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-list/management-contract-list.component.spec.ts
> +});
à compléter ou à supprimer

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-list/management-contract-list.component.ts
> +
texte du copyright à ajouter

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-preview/management-contract-information-tab/management-contract-information-tab.component.spec.ts
> +import {NO_ERRORS_SCHEMA} from '@angular/core';
copyright à ajouter

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-preview/management-contract-information-tab/management-contract-information-tab.component.spec.ts
> +    // tslint:disable-next-line:variable-name
il faut pas désactiver les règles de tslint

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-preview/management-contract-information-tab/management-contract-information-tab.component.spec.ts
> +});
à compléter ou à supprimer

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-preview/management-contract-information-tab/management-contract-information-tab.component.ts
> +import {catchError,filter,map,switchMap} from 'rxjs/operators';
il manque le texte du copyright

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-preview/management-contract-information-tab/management-contract-information-tab.component.ts
> +  // tslint:disable-next-line:variable-name
règle à ne pas désactiver

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-preview/management-contract-preview.component.spec.ts
> +  });
à compléter ou à supprimer

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-preview/management-contract-preview.component.ts
> + *
à mettre à jour

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-preview/management-contract-preview.component.ts
> +  // tab indexes: info = 0; history = 2;
to delete

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-preview/management-contract-preview.module.ts
> + * This software is a computer program whose purpose is to implement
idem

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-preview/management-contract-storage-tab/management-contract-storage-tab.component.spec.ts
> +});
à compléter ou à supprimer

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-preview/management-contract-storage-tab/management-contract-storage-tab.component.ts
> +import {Component,EventEmitter,Input,OnInit,Output} from '@angular/core';
il manque le texte du copyright

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-preview/management-contract-storage-tab/management-contract-storage-tab.component.ts
> +  // tslint:disable-next-line:variable-name
règle à ne pas désactiver

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-routing.module.ts
> +(https://redirect.francearchives.fr/seda/).
un nouveau texte du copyright ??

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract.component.spec.ts
> +});
à compléter sinon à supprimer

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract.service.spec.ts
> +});
idem

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/vitamui-library/src/lib/models/management-contract.ts
> +import {Id} from 'ui-frontend-common';
texte du copyright à ajouter

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract.service.ts
> +    // TODO: Check add of tenantId
commentaire à supprimer

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/ManagementContractController.java
> +        LOGGER.debug("getById {} / {}", identifier, URLEncoder.encode(identifier, StandardCharsets.UTF_8.toString()));
un check de sanitizing à ajouter sur l'identifier

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/ManagementContractController.java
> +        LOGGER.debug("check ability to create managementContract={}", managementContractDto);
un check de sanitizing à ajouter sur managementContractDto avant les logs

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/ManagementContractController.java
> +        LOGGER.debug("Patch managementContract {} with {}", id, partialDto);
un check de sanitizing à ajouter sur partialDto et l'id  avant les logs

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-referential/src/test/java/fr/gouv/vitamui/referential/rest/ManagementContractControllerTest.java
> +package fr.gouv.vitamui.referential.rest;
copyright ?

2022-07-19 13:11 UTC, oussamasic commented on ui/ui-referential/src/test/java/fr/gouv/vitamui/referential/service/ManagementContractServiceTest.java
> +package fr.gouv.vitamui.referential.service;
copyright ?

2022-07-19 13:14 UTC, oussamasic commented
Remarques générales : 
- Sur les nouveaux fichier .java et .ts il faut mettre le nouveau texte du copyright et appliquer le nouveau codeStyle 
Ancien texte de copyright,
voici le lien vers le nouveau texte avec le nouveau codeStyle : [ici](https://assistance.programmevitam.fr/plugins/document/projetvitam/folder/50) 
- Au niveau des nouvelles ihm ajoutées, il manque la partie traduction (en i18n).

2022-07-19 13:32 UTC, oussamasic requested changes

2022-07-19 13:32 UTC, oussamasic commented on api/api-iam/iam-internal/src/main/resources/dev/customer-init.yml
> +
il faut ajouter ce bloc aussi dans le fichier : deployment/roles/vitamui/files/customer-init.yml

2022-07-19 13:32 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +            if (managementContractResponseDto.getResults().size() == 0) {
```suggestion
            if (managementContractResponseDto.getResults().isEmpty()) {
```

2022-07-19 13:32 UTC, oussamasic commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/administration/ManagementContractService.java
> +    public RequestResponse<?> createManagementContract(final VitamContext vitamContext, final InputStream managementContract, String fileName)
méthode non utilisée

2022-07-19 13:32 UTC, oussamasic commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/administration/ManagementContractService.java
> +    public RequestResponse<?> createManagementContracts(final VitamContext vitamContext, final InputStream managementContract)
méthode non utilisée

2022-07-19 13:32 UTC, oussamasic commented on deployment/scripts/mongod/6.rc.0/08_create_application_MANAGEMENT_CONTRACT_APP.js.j2
> +print("START 322_application_ref.js");
```suggestion
print("START_08_create_application_MANAGEMENT_CONTRACT_APP.js");
```

2022-07-19 13:32 UTC, oussamasic commented on deployment/scripts/mongod/6.rc.0/08_create_application_MANAGEMENT_CONTRACT_APP.js.j2
> +print("END 322_application_ref.js");
```suggestion
print("END_08_create_application_MANAGEMENT_CONTRACT_APP.js");
```

2022-07-19 13:32 UTC, oussamasic commented on deployment/scripts/mongod/6.rc.0/07_create_profile_MANAGEMENT_CONTRACT_APP.js.j2
> +print("START 321_iam_ref.js");
```suggestion
print("START_07_create_profile_MANAGEMENT_CONTRACT_APP.js");
```

2022-07-19 13:32 UTC, oussamasic commented on deployment/scripts/mongod/6.rc.0/07_create_profile_MANAGEMENT_CONTRACT_APP.js.j2
> +print("END 321_iam_ref.js");
```suggestion
print("END_07_create_profile_MANAGEMENT_CONTRACT_APP.js");
```

2022-07-19 13:32 UTC, oussamasic commented on deployment/scripts/mongod/6.rc.0/09_add_role_for_MANAGEMENT_CONTRACT_APP.js.j2
> +print("START 323_security_ref.js");
```suggestion
print("START_09_add_role_for_MANAGEMENT_CONTRACT_APP.js");
```

2022-07-19 13:32 UTC, oussamasic commented on deployment/scripts/mongod/6.rc.0/09_add_role_for_MANAGEMENT_CONTRACT_APP.js.j2
> +print("END 323_security_ref.js");
```suggestion
print("END_09_add_role_for_MANAGEMENT_CONTRACT_APP.js");
```

2022-07-19 13:32 UTC, oussamasic commented on deployment/scripts/mongod/6.rc.0/10_add_profile_id_for_MANAGEMENT_CONTRACT_APP.js.j2
> +print("START 324_groups.js");
```suggestion
print("START_10_add_profile_id_for_MANAGEMENT_CONTRACT_APP.js");
```

2022-07-19 13:32 UTC, oussamasic commented on deployment/scripts/mongod/6.rc.0/10_add_profile_id_for_MANAGEMENT_CONTRACT_APP.js.j2
> +print("END 324_groups.js");
```suggestion
print("END_10_add_profile_id_for_MANAGEMENT_CONTRACT_APP.js");
```

2022-07-20 11:44 UTC, laedanrex commented
Il faudra squasher tous les commits en un seul ret ebase sur develop

2022-07-20 12:22 UTC, oussamasic commented
Remarques générales : 
- Sur les nouveaux fichier .java et .ts il faut mettre le nouveau texte du copyright et appliquer le nouveau codeStyle 
Ancien texte de copyright,
voici le lien vers le nouveau texte avec le nouveau codeStyle : [ici](https://assistance.programmevitam.fr/plugins/document/projetvitam/folder/50) 
- Au niveau des nouvelles ihm ajoutées, il manque la partie traduction (en i18n).
- Il faut pas oublier le squash des commits

2022-07-20 12:54 UTC, laedanrex commented on ui/ui-frontend/projects/referential/src/app/core/api/management-contracts-api.service.ts
> +    return super.getHttp().post<any>(super.getApiUrl(), managementContract, {headers});
il faut essayer au maximum d'eviter le type any ici c'est ManagementContract en et en dessous void

2022-09-22 08:24 UTC, alexandregranier commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +            LOGGER.info("Management Contract EvIdAppSession : {} " , vitamContext.getApplicationSessionId());
C'est à dire ?

2022-09-22 08:36 UTC, alexandregranier commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +        } catch (VitamClientException | JsonProcessingException e) {
De quel niveau error, info ?

2022-09-22 08:37 UTC, alexandregranier commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +        LOGGER.info("All Management Contracts EvIdAppSession : {} " , vitamContext.getApplicationSessionId());
c'est à dire

2022-09-22 08:37 UTC, alexandregranier commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +            throw new InternalServerException("Can't parse criteria as Vitam query", e);
De quel niveau ?

2022-09-22 08:37 UTC, alexandregranier commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +            LOGGER.info("All Management Contracts EvIdAppSession : {} " , vitamContext.getApplicationSessionId());
C'est à dire ?

2022-09-22 08:38 UTC, alexandregranier commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +            throw new InternalServerException("Unable to find Management Contracts", e);
de quel niveau ?

2022-09-22 16:04 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +            LOGGER.info("Management Contract EvIdAppSession : {} " , vitamContext.getApplicationSessionId());
LOGGER.debug

2022-09-22 16:05 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +        } catch (VitamClientException | JsonProcessingException e) {
error

2022-09-22 16:05 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +        LOGGER.info("All Management Contracts EvIdAppSession : {} " , vitamContext.getApplicationSessionId());
LOGGER.debug au lieu de LOGGER.info

2022-09-22 16:06 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/managementcontract/ManagementContractInternalService.java
> +            throw new InternalServerException("Unable to find Management Contracts", e);
avant le throw (un logger.error)

2022-09-28 14:58 UTC, alexandregranier commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.ts
> +        console.error(error);
Je le laisse sinon ça ne compile plus.

2022-12-15 13:36 UTC, oussamasic requested changes

2022-12-15 13:36 UTC, oussamasic commented on api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamUIManagementContractService.java
> +        LOGGER.info("Management Contract EvIdAppSession : {} " , vitamContext.getApplicationSessionId());
non, juste remplacer info par debug (pour voir les logs que en mode debug)

2022-12-15 13:36 UTC, oussamasic commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ManagementContractExternalController.java
> +        LOGGER.debug("check exist managementContract={}", managementContractDto);
avec SanityChecker.sanitizeCriteria(managementContractDto);

2022-12-15 13:36 UTC, oussamasic commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ManagementContractExternalController.java
> +        LOGGER.debug("Patch {} with {}", id, partialDto);
un sanity check à ajouter sur l'id

2022-12-15 13:36 UTC, oussamasic commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/administration/ManagementContractService.java
> +                    throw new BadRequestException(msg);
```suggestion
                    LOGGER.error("All the management contracts must have the same tenant identifier");
                    throw new BadRequestException("All the management contracts must have the same tenant identifier");
```

2022-12-15 13:36 UTC, oussamasic commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/administration/ManagementContractService.java
> +                throw new BadRequestException(msg);
```suggestion
                LOGGER.error("The tenant identifier must be present in the request body");
                throw new BadRequestException("The tenant identifier must be present in the request body");
```

2022-12-15 13:36 UTC, oussamasic commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/administration/ManagementContractService.java
> +                    throw new PreconditionFailedException(msg);
```suggestion
                    LOGGER.error("Can't create management contracts for the tenant : " + tenantIdentifier + " not found in Vitam");
                    throw new NotFoundException("Can't create management contracts for the tenant : " + tenantIdentifier + " not found in Vitam");
```

2022-12-15 13:36 UTC, oussamasic commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/administration/ManagementContractService.java
> +                    throw new UnavailableServiceException(msg);
```suggestion
                    LOGGER.error("Can't create management contracts for this tenant, Vitam response code : " + response.getStatus());
                    throw new UnavailableServiceException("Can't create management contracts for this tenant, Vitam response code : " + response.getStatus());
```

2022-12-15 13:36 UTC, oussamasic commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/administration/ManagementContractService.java
> +                throw new UnavailableServiceException(msg);
```suggestion
                LOGGER.error("Can't create management contracts for this tenant, error while calling Vitam : " + e.getMessage());
                throw new UnavailableServiceException("Can't create management contracts for this tenant, error while calling Vitam : " + e.getMessage());
```

2022-12-15 13:36 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.ts
> +        console.error(error);
utilise le logger qu'on a dans ui-frontend-common à la place de console, pour éviter le problème de build

2022-12-15 13:36 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/app/management-contract/management-contract.component.ts
> +/*
texte à mettre à jour

2023-02-08 16:11 UTC, oussamasic commented
PR ajoutée dans une autre PR : https://github.com/ProgrammeVitam/vitam-ui/pull/1186

2023-02-08 16:11 UTC, closed without merging