[VAS] 8645 : fix some update mgt rules issues
ProgrammeVitam/vitam-ui pull request #872
Opened 2022-07-05 15:18 UTC by oussamasic

PR pour compléter l'US 8645.

2022-07-05 15:21 UTC, laedanrex approved these changes

2022-07-05 15:44 UTC, depysk requested changes

2022-07-05 15:44 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/archive-unit-rules.component.ts
> +        this.managementRules.length !== 0 &&
Extraire ces conditions dans une méthode privée et nomme la méthode de tel sorte qu'on comprenne ce qui est testé

2022-07-05 15:44 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/archive-unit-rules.component.ts
> +          this.managementRules.find(
Extraire la condition dans une méthode privée

2022-07-05 15:44 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/archive-unit-rules.component.ts
> +          this.managementRules.find(
Extraire la condition dans une méthode privée

2022-07-06 13:10 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/archive-unit-rules.component.ts
> +        this.managementRules.length !== 0 &&
Done

2022-07-06 13:12 UTC, depysk approved these changes

2022-07-07 07:26 UTC, merged