[VAS] Bug 10171: reclassement des ua bloqué à cause du sanitizer
ProgrammeVitam/vitam-ui pull request #877
Opened 2022-07-13 15:33 UTC by laedanrex

## Description
Bug sur le reclassement des UA bloqué par le samitizer qui n'aime pas les champs avec des $

## Type de changement:
Nouveau Code

## Tests:
environnement
TU

## Checklist:

*Sélectionner les éléments de la checklist*

[x] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[x] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur
VAS (Vitam Accessible en Service)

2022-07-25 12:17 UTC, bbenaissa requested changes

2022-07-25 12:17 UTC, bbenaissa commented on api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/UnitExternalController.java
> +        SanityChecker.sanitizeJson(dsl);
Instruction en double

2022-07-27 08:36 UTC, mohatizaoui approved these changes

2022-07-27 13:50 UTC, bbenaissa approved these changes

2022-07-27 15:13 UTC, merged