Item 10185 collect au details
ProgrammeVitam/vitam-ui pull request #889
Opened 2022-07-25 08:20 UTC by depysk

## Description

Consulter le détail d'une AU depuis un panneau latéral

## Type de changement:

* Nouveau Code

## Tests:

manuel, TU

## Checklist:

*Sélectionner les éléments de la checklist*

[x] Mon code suit le style de code de ce projet.

## Contributeur

VAS (Vitam Accessible en Service)

2022-07-26 13:53 UTC, mascoun requested changes

2022-07-26 13:53 UTC, abdelmoez-guetat commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/SearchCollectUnitInternalService.java
> +    public ArchiveUnitsDto searchArchiveUnitsByCriteria(String projectId, SearchCriteriaDto searchQuery, VitamContext vitamContext)
searchQuery not used !

2022-07-26 13:53 UTC, mascoun commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/SearchCollectUnitInternalService.java
> +    public ArchiveUnitsDto searchArchiveUnitsByCriteria(String projectId, SearchCriteriaDto searchQuery, VitamContext vitamContext)
il faut peut être merger celui là et faire les modifications necessaires [!9141](https://gitlab.dev.programmevitam.fr/vitam/vitam/merge_requests/9141)

2022-07-26 13:53 UTC, mascoun commented on deployment/scripts/mongod/6.rc.0/05_update_contexts_with_collect_roles.js.j2
> +        "ROLE_GET_ACCESS_CONTRACTS",
pourquoi des rôles sur les contrats d'acces ?

2022-07-26 13:53 UTC, mascoun commented on ui/ui-collect/pom.xml
> +        </dependency>
à supprimer l'un des deux

2022-07-26 15:26 UTC, laedanrex commented on api/api-collect/collect-commons/src/main/java/fr/gouv/vitamui/collect/common/rest/RestApi.java
> +    public static final String COLLECT_ARCHIVE_UNIT_PATH = COLLECT_PATH + ARCHIVE_UNIT_PATH;
pour la lisibilité je les aurait quand meme appelé 
ARCHIVES_SEARCH_PATH et COLLECT_ARCHIVES_SEARCH_PATH

2022-07-26 16:15 UTC, depysk commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/SearchCollectUnitInternalService.java
> +    public ArchiveUnitsDto searchArchiveUnitsByCriteria(String projectId, SearchCriteriaDto searchQuery, VitamContext vitamContext)
Point à prendre juste après cette PR

2022-07-26 16:17 UTC, depysk commented on deployment/scripts/mongod/6.rc.0/05_update_contexts_with_collect_roles.js.j2
> +        "ROLE_GET_ACCESS_CONTRACTS",
Pour la recherche des unités archivistique

2022-07-26 16:20 UTC, laedanrex commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/ProjectInternalService.java
> +        LOGGER.debug("Criteria: ", criteria.stream().findFirst().orElse(null));
orElse direct devrait marché

2022-07-27 08:07 UTC, bbenaissa requested changes

2022-07-27 08:07 UTC, bbenaissa commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ArchiveUnitExternalController.java
> + * Project External controller
Adapter le commentaire

2022-07-27 08:07 UTC, bbenaissa commented on api/api-iam/iam-internal/src/main/resources/dev/customer-init.yml
> +        - ROLE_GET_ACCESS_CONTRACTS
Pourquoi l'ajout des roles de creation/modification des contrats d'accès

2022-07-27 08:07 UTC, bbenaissa commented on deployment/roles/vitamui/files/customer-init.yml
> +        - ROLE_GET_ACCESS_CONTRACTS
Même remarque concernant les roles

2022-07-27 08:07 UTC, bbenaissa commented on ui/ui-collect/pom.xml
> +        <dependency>
un doublon d'import

2022-07-27 08:07 UTC, bbenaissa commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-collect.service.ts
> +    const applicationIdentifier = 'ARCHIVE_SEARCH_MANAGEMENT_APP';
Ce n'est pas le bon nom d' app

2022-07-27 08:07 UTC, bbenaissa commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-collect.service.ts
> +  startEliminationAnalysis(criteriaDto: SearchCriteriaDto, accessContract: string) {
Pas d'actions d'elimination, analyse elimination, DIP dans la nouvelle app collect

2022-07-27 08:07 UTC, bbenaissa commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-details-tab.component.ts
> +      // TODO : Gestion des règles d'héritage
To remove or update

2022-07-27 08:07 UTC, bbenaissa commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
> +      <!-- Todo : UNCOMMENT WHEN FETCHING TREES
To check or remove

2022-07-27 09:24 UTC, closed without merging

2022-07-27 10:09 UTC, mohatizaoui approved these changes

2022-07-27 13:24 UTC, laedanrex approved these changes