story:9852 download transfer DIP
ProgrammeVitam/vitam-ui pull request #894
Opened 2022-07-28 09:17 UTC by mohatizaoui

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2022-08-04 15:43 UTC, depysk requested changes

2022-08-04 15:43 UTC, depysk commented on ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.ts
> +  private getMessageForDownload(): string{
Peut être simplifier en :
 
````
private getMessageForDownload(): string {

    switch(this.event.typeProc){
        case 'EXPORT_DIP':{ 
          return 'Télécharger le DIP';
        }
        case 'ARCHIVE_TRANSFER': {
          return 'Télécharger le DIP de transfert';
        }
        default:{
          return 'Télécharger le rapport';
        } 
    }
  }
````

2022-08-04 15:43 UTC, depysk commented on ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.ts
> +  private getMessageForDownload(): string{
Peut être simplifier en :
 
````
private getMessageForDownload(): string {

    switch(this.event.typeProc){
        case 'EXPORT_DIP':{ 
          return 'Télécharger le DIP';
        }
        case 'ARCHIVE_TRANSFER': {
          return 'Télécharger le DIP de transfert';
        }
        default:{
          return 'Télécharger le rapport';
        } 
    }
  }
````

2022-08-04 15:43 UTC, depysk commented on ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.html
> +          <vitamui-common-event-type-label [key]="getMessageForOperation(event.type)"></vitamui-common-event-type-label>
Mieux de faire:
````
[key]="event.type + 'LABEL' | translate"
````

2022-08-05 12:41 UTC, laedanrex commented on ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.html
> +          <vitamui-common-event-type-label [key]="getMessageForOperation(event.type)"></vitamui-common-event-type-label>
yes avec les parenthese si ca marche pas du premier coups

2022-08-08 14:22 UTC, GhrabSaifEddine requested changes

2022-08-08 14:22 UTC, GhrabSaifEddine commented on ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.ts
> +        case 'EXPORT_DIP':{
merci d'utiliser plutôt des constantes pour les 3 cases!

2022-08-08 14:22 UTC, GhrabSaifEddine commented on ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.ts
> +  private getMessageForOperation(type:string){
le module ref front ne se lance pas suite à l'erreur :
"ERROR in projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.ts:146:11 - error TS6133: 'getMessageForOperation' is declared but its value is never read.
"
Si tu comptes garder la méthode, supprimes le "private" afin de garder une visibilité de la méthode uniquement par le html et le compiler TS la fait passer!

2022-08-08 14:22 UTC, GhrabSaifEddine commented on ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.html
> +          <vitamui-common-event-type-label [key]="getMessageForOperation(event.type)"></vitamui-common-event-type-label>
@depysk La proposition n'est pas bonne : la traduction est déjà faite par le composant "EventTypeLabelComponent" qui prend en compte un clé et construit systématiquement la valeur.
@mohatizaoui : Essais plutôt de mapper ce changement lors de l'init de la  dataSource dans onDataSourceReloaded() : ceci évitera l'aller-retour entre html-component lors de la construction du DOM, et enfin on garde le "event.type" en html.

2022-08-09 08:11 UTC, mohatizaoui commented on ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.html
> +          <vitamui-common-event-type-label [key]="getMessageForOperation(event.type)"></vitamui-common-event-type-label>
non il faut remplacer que Archive_TRANSFER par ARCHIVE_TRANSFERT_LABEL pas les autres 
et je l'ai sortie vers une fonction car souvent il y aura d'autre cas qu'il faut faire la même chose donc pour éviter d'écrire bcp de code en html je l'ai sortie vers une  fonction

et pas la peine de faire translate car c'est le composant vitamui-common-event-type-label qui fait le taf

2022-08-09 08:11 UTC, mohatizaoui commented on ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.ts
> +  private getMessageForDownload(): string{
C'est kif kif 

et pour la lisibilité c'est mieux d'avoir un seul return

2022-08-09 08:11 UTC, mohatizaoui commented on ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.ts
> +  private getMessageForDownload(): string{
En plus pour certain interpreteur il faut un seul sortie car le fonctionnement d'interpreteur il se base sur dijikstra pour lancer le programme comme le fonctionnemenet d'aassembleur 
En java on a pas ce problème car il y a le le compilateur java qui fait le taf  conversion vers .class
https://softwareengineering.stackexchange.com/questions/118703/where-did-the-notion-of-one-return-only-come-from

2022-08-09 13:07 UTC, laedanrex approved these changes

2022-08-11 08:59 UTC, GhrabSaifEddine approved these changes

2022-08-11 09:47 UTC, depysk approved these changes

2022-08-12 13:05 UTC, merged