[VAS] Story 10173: add naviguation arborescence ua
ProgrammeVitam/vitam-ui pull request #898
Opened 2022-08-01 07:55 UTC by laedanrex

## Description
L'objectif de cette US est de faire évoluer le panneau latéral de gauche de l'APP Recherche et consultation qui contient actuellement l'arborescence des arbres et des plans et qui doit être complété par un nouveau bloc d'arborescence permettant de visualiser les SIP d'archives standards (avec ou sans objet).

## Type de changement:
* Nouveau Code
* Refactorisation de code

## Tests:
manuel
environnement

## Checklist:
[x] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur
VAS (Vitam Accessible en Service)

2022-08-18 09:16 UTC, mohatizaoui commented on ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
> +    this.subscriptionFacets = this.archiveSharedDataService.getFacets()
Ajout unsubscribe stp dans ondestroy

2022-08-18 09:16 UTC, mohatizaoui commented on ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
> +      if (!found && node.children) {
remplacer les deux if  par else if(( node.children) )

2022-08-18 11:48 UTC, oussamasic requested changes

2022-08-18 11:48 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.scss
> +/* styles applied directly to the ap-root element only */
des commentaires dans le fichier à supprimer

2022-08-18 11:48 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
> +export class FilingHoldingSchemeComponent implements OnChanges {
implements aussi OnDestroy (avec l'ajout de quelques unsubscribers)

2022-08-18 11:48 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
> +      // return [node, ...childResult];
to delete

2022-08-23 11:36 UTC, laedanrex commented on ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
> +      if (!found && node.children) {
mmh, c'est pas la meme chose

2022-08-23 11:56 UTC, laedanrex commented on ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
> +      if (!found && node.children) {
j'en ai profité pour rename et ajouter une condition pour break

2022-08-23 14:38 UTC, laedanrex commented on ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
> +      if (!found && node.children) {
beh j'ai changé du coup

2022-08-24 07:49 UTC, mohatizaoui commented on ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.component.ts
> +    if (node.canLoadMoreChildren) {
il faut retrouner une valeur si aucune de ces conditions est atteint

2022-08-24 07:49 UTC, mohatizaoui commented on ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.component.ts
> +    if (!node.canLoadMoreChildren === undefined) {
cette condition est un else de node.canLoadMoreChildren === undefined

2022-08-24 14:03 UTC, laedanrex commented on ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.component.ts
> +    if (!node.canLoadMoreChildren === undefined) {
yes, le undefined n'a pas sa place

2022-08-24 14:14 UTC, oussamasic approved these changes

2022-08-24 14:23 UTC, mohatizaoui approved these changes

2022-08-24 14:47 UTC, merged