item#9879 Add profil for consulting rules
ProgrammeVitam/vitam-ui pull request #904
Opened 2022-08-09 08:04 UTC by mohatizaoui

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2022-08-09 12:53 UTC, bbenaissa approved these changes

2022-08-11 15:42 UTC, mascoun approved these changes

2022-08-12 13:05 UTC, GiooDev requested changes

2022-08-12 13:05 UTC, GiooDev commented on deployment/scripts/mongod/6.rc.0/07_add_consult_rules_profil.js.j2
> +print("END 01_add_consult_rules_profil.js");
Mauvais nom ici

2022-08-12 13:32 UTC, merged