[VAS]Feature-10145:Handle search by reuse and dissemination rules cri…
ProgrammeVitam/vitam-ui pull request #907
Opened 2022-08-11 14:30 UTC by bbenaissa

## Description

L'objectif de cette US est de pouvoir effectuer des recherches sur les règles de gestion de Type 'REUSE' ou 'DISSEMINATION' ainsi que le traitement des facettes associées.

## Type de changement:

* Nouveau Code

## Documentation:

## Tests:

manuel

TU

## Contributeur

VAS (Vitam Accessible en Service)

2022-08-16 10:07 UTC, mohatizaoui commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
>          if (!CollectionUtils.isEmpty(waitingToRecalculateCriteria) &&
Je pense il faut faire que ça:
if (!CollectionUtils.isEmpty(waitingToRecalculateCriteria))

car les autres conditions sont déjà testé après pour  searchQuery.setCriteriaList(initialCriteriaList); il pourra être géré par un boolean  

un boolean n'est pas couteux comme la vérification des empty

2022-08-16 13:59 UTC, oussamasic requested changes

2022-08-16 13:59 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchDisseminationMgtRulesQueryBuilderServiceTest.java
> +    }
tu peux utiliser la classe FileReader (src/test/java/fr/gouv/vitamui/archive/internal/server/utils/FileReader.java), pour éviter la déclaration des deux méthodes dans chaque classe test

2022-08-16 13:59 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchDisseminationMgtRulesQueryBuilderServiceTest.java
> +public class ArchivesSearchDisseminationMgtRulesQueryBuilderServiceTest {
pas besoin de créer cette classe de test, tu peux ajouter tes tests directement dans la classe : `ArchivesSearchDisseminationRuleQueryBuilderServiceTest`

2022-08-16 13:59 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchDisseminationMgtRulesQueryBuilderServiceTest.java
> +        //Given
to delete

2022-08-16 13:59 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchDisseminationMgtRulesQueryBuilderServiceTest.java
> +        //Given
to delete

2022-08-16 13:59 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchReuseMgtRulesQueryBuilderServiceTest.java
> +    }
tu peux utiliser la classe FileReader (src/test/java/fr/gouv/vitamui/archive/internal/server/utils/FileReader.java), pour éviter la déclaration des deux méthodes dans chaque classe test

2022-08-16 13:59 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchReuseMgtRulesQueryBuilderServiceTest.java
> +public class ArchivesSearchReuseMgtRulesQueryBuilderServiceTest {
pas besoin de créer cette classe de test, tu peux ajouter tes tests directement dans la classe : `ArchivesSearchReuseRuleQueryBuilderServiceTest`

2022-08-16 13:59 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/dissemination-rule-search/dissemination-rule-search.component.html
> +          [ngStyle]="{ 'background-color': 'green', width: '30', height: '30' }"
à ajouter dans un fichier css c'est plus propre

2022-08-16 13:59 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/reuse-rule-search/reuse-rule-search.component.html
> +          [ngStyle]="{ 'background-color': 'green', width: '30', height: '30' }"
idem, à ajouter dans un fichier css

2022-08-16 13:59 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/core/archive-shared-data.service.ts
> + * As a counterpart to the reusing to the source code and  rights to copy,
c'est access normalement

2022-08-19 09:40 UTC, mohatizaoui approved these changes

2022-08-19 10:03 UTC, oussamasic approved these changes

2022-08-19 14:27 UTC, merged