[CEA] Rechercher des audits par requête DSL
ProgrammeVitam/vitam-ui pull request #92
Opened 2020-12-16 18:41 UTC by mamak-smile

## Description

Cette PR contient les développements permettant la recherche des audits par requête DSL.

Les sujets traités sont les suivants :

* 19828 - Accéder à l’interface de requête DSL 
* 19829 - Lancer une requête DSL

## Type de changement:
Code et/ou Configuration : Ajout de nouvelles fonctionnalités

## Tests:

Tests unitaires
Tests d'intégration
Recette sur environnement Smile

## Contributeur

Commissariat à l'énergie atomique et aux énergies alternatives (CEA)

2021-01-14 08:42 UTC, pimenta-cines approved these changes

2021-02-08 11:26 UTC, bbenaissa approved these changes

2021-02-11 13:08 UTC, oussamasic requested changes
Avant de merger la PR il faut faire une modification parce que le fichier `customerinit.yml` n'a pas été mis à jour pour donner les droits à requêtes DSL dans les organisations.

2021-02-11 13:51 UTC, benemart commented
Le customer_init a été modifié.

2021-02-11 13:58 UTC, oussamasic approved these changes

2021-02-19 08:06 UTC, merged