Feature/vas 8314 modify profiles to include thresholds
ProgrammeVitam/vitam-ui pull request #927
Opened 2022-08-19 09:37 UTC by bbenaissa

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2022-08-22 15:29 UTC, depysk requested changes

2022-08-22 15:29 UTC, depysk commented on api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/service/ArchivesSearchExternalService.java
> +         * TODO handle thresholds
TODO ?

2022-08-22 15:29 UTC, depysk commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalparamprofile/service/ExternalParamProfileInternalService.java
>              if (partialDto.get(ACCESS_CONTRACT) != null) {
Remplacer 

````java
if (!externalParamProfileLogbooks.isEmpty() || partialDto.get(ACCESS_CONTRACT) != null) {
            if (partialDto.get(ACCESS_CONTRACT) != null) {
                 ...
            }
}
````

par 

````java
if (!externalParamProfileLogbooks.isEmpty() || partialDto.get(ACCESS_CONTRACT) != null && partialDto.get(ACCESS_CONTRACT) != null) {
                 ...
}
````

2022-08-22 15:29 UTC, depysk commented on api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalparamprofile/service/ExternalParamProfileInternalService.java
> +        if (partialDto.get(USE_PLATFORM_BULK_OPERATIONS_THRESHOLD) != null ||
Simplifier la syntaxe des `if`

2022-08-22 15:29 UTC, depysk commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ExternalParamProfileDto.java
> +    public void transformFields() {
Un Dto ne doit pas endosser ce genre de responsabilité, déléguer cette responsabilité à une autre classe

2022-08-22 15:29 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> +const DEFAULT_ELIMINATION_ANALYSIS_THRESHOLD = 100000;
On pourrait tout simplement définir des variables à l'intérieur du composant au lieu de créer des const, vu qu'ils ne sont pas exportés.

2022-08-22 15:29 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
>      await this.prepareToLaunchVitamAction();
Méthode avec plusieurs embranchements, déléguer ce traitement dans une classe Ts avec des méthodes statiques significatives ou déléguer celà à un service Angular

2022-08-22 15:29 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
>      await this.prepareToLaunchVitamAction();
Méthode avec plusieurs embranchements, déléguer ce traitement dans une classe Ts avec des méthodes statiques significatives ou déléguer celà à un service Angular

2022-08-22 15:29 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> +    this.selectedItemCount = this.selectedItemCountKnown();
Méthode avec plusieurs embranchements, déléguer ce traitement dans une classe Ts avec des méthodes statiques significatives ou déléguer celà à un service Angular

2022-08-22 15:29 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
>      await this.prepareToLaunchVitamAction();
Méthode avec plusieurs embranchements, déléguer ce traitement dans une classe Ts avec des méthodes statiques significatives ou déléguer celà à un service Angular

2022-08-22 15:29 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
> +    this.selectedItemCount = this.selectedItemCountKnown();
Méthode avec plusieurs embranchements, déléguer ce traitement dans une classe Ts avec des méthodes statiques significatives ou déléguer celà à un service Angular

2022-08-22 15:29 UTC, depysk commented on ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-detail/information-tab/information-tab.component.ts
> +    // this.initListenersOnFormsValuesChanges();
Code commenté à supprimer

2022-08-22 15:29 UTC, depysk commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.ts
> +      const thresholdParams: any = parameters.get(ExternalParameters.PARAM_BULK_OPERATIONS_THRESHOLD);
éviter le type any

2022-08-22 15:29 UTC, depysk commented on ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-detail/information-tab/information-tab.component.ts
> +      console.log(updated);
console.log() à supprimer ou à remplacer avec le Logger Vitam

2022-08-22 15:29 UTC, depysk commented on ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-detail/information-tab/information-tab.component.ts
> +      updated = extend(
Je ne vois pas l'interêt d'utiliser extend ici

2022-08-23 15:00 UTC, oussamasic requested changes

2022-08-23 15:00 UTC, oussamasic commented on api/api-iam/iam-internal/src/main/resources/access-external-client.conf
> +hostnameVerification: true
fichier à supprimer

2022-08-23 15:00 UTC, oussamasic commented on api/api-iam/iam-internal/src/main/resources/collect-external-client.conf
> +hostnameVerification: true
to delete

2022-08-23 15:00 UTC, oussamasic commented on api/api-iam/iam-internal/src/main/resources/ingest-external-client.conf
> +hostnameVerification: true
to delete

2022-08-23 15:00 UTC, oussamasic commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ParameterListDto.java
> + *
texte du copyright n'est pas bon

2022-08-23 15:00 UTC, oussamasic commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/config/VitamClientConfig.java
> -    }
Attention : il faut pas supprimer cette partie, sinon le module collect tombe en KO.

2022-08-24 12:02 UTC, oussamasic requested changes

2022-08-24 12:02 UTC, oussamasic commented on api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/service/ArchiveSearchThresholdService.java
> +                        parameterThreshold.getValue());
on throw pas l'exception ?

2022-09-14 07:54 UTC, bbenaissa commented on api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/service/ArchiveSearchThresholdService.java
> +                        parameterThreshold.getValue());
done

2022-09-15 13:47 UTC, oussamasic approved these changes

2022-09-15 15:21 UTC, depysk requested changes

2022-09-15 15:21 UTC, depysk commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/config/VitamCollectConfig.java
> -    @Bean
Code supprimé?

2022-09-15 15:21 UTC, depysk commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/config/VitamClientConfig.java
> -    }
Code supprimé?

2022-09-15 15:21 UTC, depysk commented on ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-detail/information-tab/information-tab.component.ts
> +      updated = extend(
On peut se passer de extend

2022-09-15 15:40 UTC, bbenaissa commented on commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/config/VitamCollectConfig.java
> -    @Bean
annulé

2022-09-15 15:54 UTC, depysk approved these changes

2022-09-16 07:43 UTC, oussamasic approved these changes

2022-09-16 08:31 UTC, merged