Story 10201 purge project transaction
ProgrammeVitam/vitam-ui pull request #935
Opened 2022-08-22 12:18 UTC by anasstsdi

## Description
ajouter la suppression de projet lors de l'annulation
*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2022-08-23 09:58 UTC, oussamasic requested changes

2022-08-23 09:58 UTC, oussamasic commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectExternalController.java
> +    @Secured(ServicesData.ROLE_UPDATE_PROJECTS)
avec un role de Delete c'est mieux je pense

2022-08-23 09:58 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/ProjectInternalController.java
> +        ParameterChecker.checkParameter("The Identifier is a mandatory parameter: ", id);
un petit sanitize avant le log, 
méthode checkSecureParameter dans SanityChecker

2022-08-23 09:58 UTC, oussamasic commented on ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/ProjectController.java
> +        LOGGER.info("Delete the Project with ID {}", id);
debug ?

2022-08-23 09:58 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/core/api/project-api.service.ts
> +  //private static COLLECT_PROJECT_URL = './collect-api/project';
to delete

2022-08-24 13:05 UTC, mohatizaoui approved these changes

2022-08-24 13:41 UTC, anasstsdi commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectExternalController.java
> +    @Secured(ServicesData.ROLE_UPDATE_PROJECTS)
les roles on va les gerer dans une Us a part

2022-08-24 15:00 UTC, oussamasic approved these changes

2022-09-01 09:00 UTC, merged