[VAS] Bug #9753: show total of elements in search
ProgrammeVitam/vitam-ui pull request #947
Opened 2022-08-31 15:57 UTC by laedanrex

## Description
BUG Production - erreur sur Le nbre d'entrées dans le registre des fonds 

## Type de changement:
* Correction
* Refactorisation de code

## Tests:
manuel
TU

## Checklist:

[x] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur
VAS (Vitam Accessible en Service)

2022-09-05 09:38 UTC, oussamasic requested changes

2022-09-05 09:38 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/vitamui-table/page-request.model.ts
> +export const DEFAULT_PAGE_SIZE = 4;
pourquoi 4 ?

2022-09-05 09:38 UTC, oussamasic commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
> +/*
pas besoin de changer le texte du copyright

2022-09-05 09:38 UTC, oussamasic commented on api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessRegisterVitamQueryHelperTest.java
>  /*
idem

2022-09-05 09:38 UTC, oussamasic commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/PaginatedValuesDto.java
> +/*
idem

2022-09-21 07:51 UTC, laedanrex commented on ui/ui-frontend-common/src/app/modules/vitamui-table/page-request.model.ts
> +export const DEFAULT_PAGE_SIZE = 4;
yes une erreur bien vu

2022-09-21 08:01 UTC, laedanrex commented on api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
> +/*
c'est pas un problème si ?

2022-09-21 09:48 UTC, oussamasic approved these changes

2022-09-21 12:59 UTC, merged