[VAS] Story #10230: add download ATR
ProgrammeVitam/vitam-ui pull request #951
Opened 2022-09-02 08:45 UTC by laedanrex

## Description
Fix sur le téléchargement de l'ATR lors d'un ingest à blanc

## Type de changement:
* Nouveau Code

## Tests:
manuel

## Contributeur
VAS (Vitam Accessible en Service)

2022-09-02 09:09 UTC, bbenaissa commented on ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.ts
> +  // refacto: mettre en commun avec logbook-event.interface.ts
à traiter un jour

2022-09-02 09:09 UTC, bbenaissa approved these changes

2022-09-05 08:39 UTC, oussamasic requested changes

2022-09-05 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/assets/i18n/en.json
> +  },
to delete

2022-09-05 08:39 UTC, oussamasic commented on ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
> +  },
to delete

2022-09-21 08:23 UTC, laedanrex commented on ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.ts
> +  // refacto: mettre en commun avec logbook-event.interface.ts
oui c'est dans mon pipe clean code

2022-09-21 13:00 UTC, merged