story#10195: Navigate through tree of standard archive units
ProgrammeVitam/vitam-ui pull request #963
Opened 2022-09-08 15:49 UTC by depysk

## Description

US 10195 : Navigate through tree of standard archive units

## Type de changement:

* Nouveau Code

* Refactorisation de code

## Tests:

Tests TU et manuels

## Checklist:

*Sélectionner les éléments de la checklist*

[x] Mon code suit le style de code de ce projet.

[x] Les tests unitaires nouveaux et existants passent avec succès localement.

## Contributeur

VAS (Vitam Accessible en Service)

2022-09-09 13:05 UTC, oussamasic requested changes

2022-09-09 13:05 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/components/vitamui-tree-node/vitamui-tree-node.component.spec.ts
> +/*
Ancien texte copyright, à modifier dans l'ensemble des fichiers .ts ajoutés

2022-09-09 13:05 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/components/vitamui-tree-node/vitamui-tree-node.component.spec.ts
> +
possible d'avoir plus de tests ?

2022-09-09 13:05 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/classification-tree/classification-tree.component.scss
> +    //hidde empty node
to delete

2022-09-09 13:05 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/classification-tree/classification-tree.component.scss
> +    // text-decoration: underline;
to delete

2022-09-09 13:05 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
> +        this.nestedDataSourceFull.data = data;
```suggestion
        this.nestedDataSourceFull.data = data;
```

2022-09-09 13:05 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
> +    this.archiveService.loadFilingHoldingSchemeTree(this.tenantIdentifier, this.accessContract).subscribe((nodes) => {
```suggestion
    this.subscriptions.add(this.archiveService.loadFilingHoldingSchemeTree(this.tenantIdentifier, this.accessContract).subscribe((nodes) => {
```

2022-09-09 13:05 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.handler.ts
> +        vitamId: unit['#id'],
pas besoin de cet attribut (vitamId), c'est le meme que 'id'

2022-09-09 13:05 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.handler.ts
> +        title: unit.Title,
parfois Title est absent, (je pense qu'on aura besoin de gérer ce cas pour récupérer soit Title_.fr ou Title_en)

2022-09-09 13:05 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/components/vitamui-tree-node/vitamui-tree-node.component.ts
> + *
Ancien texte copyright, à modifier dans l'ensemble des nouveaux fichiers .ts ajoutés

2022-09-12 08:33 UTC, bbenaissa requested changes

2022-09-12 08:33 UTC, bbenaissa commented on ui/ui-frontend-common/src/app/modules/components/vitamui-tree-node/vitamui-tree-node.component.spec.ts
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
à mettre à jour le texte de licence

2022-09-14 09:23 UTC, oussamasic approved these changes

2022-09-14 09:45 UTC, bbenaissa approved these changes

2022-09-15 09:08 UTC, merged