Story 10261 close and send transaction
ProgrammeVitam/vitam-ui pull request #968
Opened 2022-09-15 06:59 UTC by mohatizaoui

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2022-09-16 07:31 UTC, oussamasic commented
à ne pas oublier de squasher les commits

2022-09-16 08:35 UTC, oussamasic requested changes

2022-09-16 08:35 UTC, oussamasic commented on api/api-collect/collect-external-client/src/main/java/fr/gouv/vitamui/collect/external/client/CollectExternalRestClient.java
> +    String apiName;
variable non utilisée (à supprimer)

2022-09-16 08:35 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/ProjectInternalController.java
> +        ParameterChecker.checkParameter("The Identifier is a mandatory parameter: ", id);
un sanitycheck à ajouter sur l'id avant le log

2022-09-16 08:35 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/ProjectInternalService.java
> +            List<ProjectDto> projectDtos = objectMapper.readValue(((RequestResponseOK) requestResponse).getFirstResult().toString(), new TypeReference<>() {
question générale : est-ce que le codeStyle de Vitam est bien appliqué ? 
il y a beaucoup des changements de format du code

2022-09-16 08:35 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/TransactionInternalService.java
> +            throw new VitamClientException("Unable to delete project : ", e);
```suggestion
            throw new VitamClientException("Unable to close the transaction : ", e);
```

2022-09-16 08:35 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/TransactionInternalService.java
> +            throw new VitamClientException("Unable to delete project : ", e);
```suggestion
            throw new VitamClientException("Unable to send the transaction : ", e);
```

2022-09-16 08:35 UTC, oussamasic commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/CommonConstants.java
> + * <p>
problème de formatage ?

2022-09-16 08:35 UTC, oussamasic commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
> + * <p>
idem

2022-09-16 08:35 UTC, oussamasic commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
> +        ROLE_UPDATE_PROJECTS
il faut ajouter les deux roles : `ROLE_CLOSE_TRANSACTIONS` et `ROLE_SEND_TRANSACTIONS` dans les deux listes : **ADMIN_VITAMUI_ROLES** et **ROLE_NAMES**

2022-09-16 08:35 UTC, oussamasic commented on ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/ProjectController.java
> +       // System.out.println(request.getHeaderNames());
commentaire à supprimer

2022-09-16 08:35 UTC, oussamasic commented on ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/TransactionController.java
> +        LOGGER.debug("Send the Transaction with ID {}", transactionId);
```suggestion
        LOGGER.debug("Close the Transaction with ID {}", transactionId);
```

2022-09-16 08:35 UTC, oussamasic commented on ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/TransactionController.java
> +    @ApiOperation(value = "Create new collect project")
```suggestion
    @ApiOperation(value = "Close transaction operation")
```

2022-09-16 08:35 UTC, oussamasic commented on ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/TransactionController.java
> +    @ApiOperation(value = "Create new collect project")
```suggestion
    @ApiOperation(value = "Send transaction operation")
```

2022-09-16 08:35 UTC, oussamasic commented on ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/service/TransactionService.java
> + * UI Collect Project Service
UI Collect Transaction Service

2022-09-16 08:35 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/models/collect/Transaction.ts
> +/*
pourquoi c'est ajouté dans ui-frontend-common ?

2022-09-16 08:35 UTC, oussamasic commented on ui/ui-frontend-common/src/app/modules/models/collect/transaction-status.ts
> +/*
pourquoi c'est ajouté dans ui-frontend-common ?

2022-09-16 08:35 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
> +            i18n="More actions button label@@customerListMoreActionsButton">Autres actions</span>
à traduire

2022-09-16 08:35 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
> +                    [disabled]="isNotOpen$ | async">Valider
à traduire

2022-09-16 08:35 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
> +                    [disabled]="isNotReady$ | async">Verser
à traduire et ajouter les deux fichier i18n

2022-10-05 12:10 UTC, mohatizaoui commented on ui/ui-frontend-common/src/app/modules/models/collect/Transaction.ts
> +/*
C'est le même cas pour Project et project-status

2022-10-05 12:11 UTC, mohatizaoui commented on ui/ui-frontend-common/src/app/modules/models/collect/transaction-status.ts
> +/*
idem

2022-10-05 12:30 UTC, oussamasic approved these changes

2022-10-05 12:41 UTC, mascoun requested changes

2022-10-05 12:41 UTC, mascoun commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/ProjectInternalController.java
> +import org.springframework.web.bind.annotation.*;
VitamStyle !

2022-10-05 12:41 UTC, mascoun commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/ProjectInternalService.java
> +      /*  try {
??

2022-10-05 12:41 UTC, mascoun commented on ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/TransactionController.java
> +import static fr.gouv.vitamui.collect.common.rest.RestApi.*;
VitamStyle

2022-10-05 13:18 UTC, depysk requested changes

2022-10-05 13:18 UTC, depysk commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/TransactionExternalController.java
> + * Project External controller
Change class comment to `Transaction External controller`

2022-10-05 13:18 UTC, depysk commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/service/TransactionExternalService.java
> + * The service to create project.
Change comment

2022-10-05 13:18 UTC, depysk commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/ProjectInternalService.java
> +      /*  try {
Code commenté à supprimer

2022-10-05 13:18 UTC, depysk commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/ProjectInternalService.java
> +            .id("aeeaaaaaaghotx7taajrgamdrf6fipaaaaaq")
Données en dur?

2022-10-05 13:18 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
> +    this.transactionSubscription = this.route.params.pipe(mergeMap((params) => {
Faire un unsubscribe ;)

2022-10-05 13:18 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
> +    this.archiveUnitCollectService.validateTransaction(this.transaction.id).subscribe(() => {
Faire un unsubscribe ;)

2022-10-05 13:18 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
> +    return this.archiveUnitCollectService.sendTransaction(this.transaction.id).subscribe(() => {
Faire un unsubscribe ;). Pas besoin de faire un return

2022-10-05 13:21 UTC, mohatizaoui commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
> +    this.transactionSubscription = this.route.params.pipe(mergeMap((params) => {
déjà fait

2022-10-06 09:49 UTC, depysk approved these changes

2022-10-06 14:06 UTC, merged