item #10326 Search collect units by criteria
ProgrammeVitam/vitam-ui pull request #974
Opened 2022-09-16 11:59 UTC by GhrabSaifEddine

## Description

*Description des modifications*

## Type de changement:

*Indiquer le ou les types de changements*

* Build

* PKI

* Ansiblerie

* Nouveau Code

* Correction

* Refactorisation de code

* Autre

## Documentation:

*Indiquer la documentation mise à jour*

[ ] Quels sont les nouvelles documentations ?

[ ] Quels sont les modifications existantes ?

[ ] Quels sont les documentations ou sections de documentations supprimés ?

## Tests:

*Indiquer comment le code à été testé (manuel, environnement, TU, etc)*

manuel

environnement

TU

## Migration:

*Indiquer si les modifications apportées impliquent une migration sur l'existant et comment la faire*

## Checklist:

*Sélectionner les éléments de la checklist*

[ ] Mon code suit le style de code de ce projet.

[ ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ ] J'ai fait les changements correspondant dans la documentation Métier.

[ ] J'ai fait les changements correspondant dans la documentation Technique.

[ ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ ] Toutes les dépendances ont été mergées en priorité

## Contributeur

*Indiquer qui a développé cette fonctionnalité*

VAS (Vitam Accessible en Service)

CEA (Commissariat à l'énergie atomique et aux énergies alternatives)

2022-09-26 12:14 UTC, depysk requested changes

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/vitamui-snack-bar.module.ts
> +export class VitamUISnackBarModule { }
Ce module a tout ce qu'il faut pour être migrer dans ui-frontend-common

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/services/management-rules-shared-data.service.ts
> +    // const options = {
Code commenté à supprimer

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/services/management-rules-shared-data.service.ts
> +    // .subscribe((data) =>{
Code commenté à supprimer

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/models/ruleAction.interface.ts
> +/*
Par convention les fichiers `ts` sont nommés en kebab-case. Renommer le fichier `ruleAction.interface.ts` en `rule-action.interface.ts`

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/services/archive-facets.service.ts
> +  extractNodesFacetsResults(facetResults: ResultFacetList[]): ResultFacet[] {
Proposition de reécriture de cette fonctionnalité:
````
extractNodesFacetsResults(facetResults: ResultFacetList[]): ResultFacet[] {
  if (facetResults.length === 0) {
    return [];
  }
  return facetResults
    .filter((facet: ResultFacet) => facet.name === this.COUNT_BY_NODE)
    .flatMap((facet: ResultFacet) => facet.buckets)
    .map(bucket => ({ node: bucket.value, count: bucket.count }));
}
````

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
> +    this.archiveExchangeDataService.receiveRemoveFromChildSearchCriteriaSubject().subscribe((criteria) => {
Ne pas oublier de faire un `unsubscribe`. Si trop de variables `Subscription`, pensez à en utiliser qu'un seul avec la methode `add`

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
> +    this.archiveUnitCollectService.searchArchiveUnitsByCriteria(searchCriteria, this.projectId, this.accessContract).subscribe(
Ne pas oublier de faire un `unsubscribe`. Si trop de variables `Subscription`, pensez à en utiliser qu'un seul avec la methode `add`

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/storage-rule-search/storage-rule-search.component.ts
> +    merge(this.storageRuleCriteriaForm.statusChanges, this.storageRuleCriteriaForm.valueChanges)
Ne pas oublier de faire un `unsubscribe`. Si trop de variables `Subscription`, pensez à en utiliser qu'un seul avec la methode `add`

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/storage-rule-search/storage-rule-search.component.ts
> +    this.storageRuleCriteriaForm.get('storageRuleTitle').valueChanges.subscribe((value) => {
Ne pas oublier de faire un `unsubscribe`. Si trop de variables `Subscription`, pensez à en utiliser qu'un seul avec la methode `add`

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/simple-criteria-search/simple-criteria-search.component.ts
> +    this.archiveCollectService.getOntologiesFromJson().subscribe((data: any) => {
Ne pas oublier de faire un `unsubscribe`. Si trop de variables `Subscription`, pensez à en utiliser qu'un seul avec la methode `add`

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/simple-criteria-search/simple-criteria-search.component.ts
> +    merge(this.simpleCriteriaForm.statusChanges, this.simpleCriteriaForm.valueChanges)
Ne pas oublier de faire un `unsubscribe`. Si trop de variables `Subscription`, pensez à en utiliser qu'un seul avec la methode `add`

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/simple-criteria-search/simple-criteria-search.component.ts
> +    this.managementRulesSharedDataService.getCriteriaSearchListToSave().subscribe((data) => {
Ne pas oublier de faire un `unsubscribe`. Si trop de variables `Subscription`, pensez à en utiliser qu'un seul avec la methode `add`

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/simple-criteria-search/simple-criteria-search.component.ts
> +    this.simpleCriteriaForm.get('otherCriteria').valueChanges.subscribe((selectedcriteria) => {
Ne pas oublier de faire un `unsubscribe`. Si trop de variables `Subscription`, pensez à en utiliser qu'un seul avec la methode `add`

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/search-criteria-list/search-criteria-list.component.ts
> +    this.searchCriteriaSaverService.getSearchCriteriaHistory().subscribe((data) => {
Ne pas oublier de faire un `unsubscribe`. Si trop de variables `Subscription`, pensez à en utiliser qu'un seul avec la methode `add`

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/search-criteria-list/search-criteria-list.component.ts
> +    dialog
Ne pas oublier de faire un `unsubscribe`. Si trop de variables `Subscription`, pensez à en utiliser qu'un seul avec la methode `add`

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/search-criteria-list/confirm-action/confirm-action.component.ts
> +export class ConfirmActionComponent implements OnInit {
Interface `OnInit` non utilisée à supprimer

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/reuse-rule-search/reuse-rule-search.component.ts
> +    merge(this.reuseRuleCriteriaForm.statusChanges, this.reuseRuleCriteriaForm.valueChanges)
Ne pas oublier de faire un `unsubscribe`. Si trop de variables `Subscription`, pensez à en utiliser qu'un seul avec la methode `add`

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/reuse-rule-search/reuse-rule-search.component.ts
> +    this.reuseRuleCriteriaForm.get('reuseRuleTitle').valueChanges.subscribe((value) => {
Ne pas oublier de faire un `unsubscribe`. Si trop de variables `Subscription`, pensez à en utiliser qu'un seul avec la methode `add`

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/reuse-rule-search/reuse-rule-search.component.ts
> +    this.subscriptionReuseFromMainSearchCriteria = this.archiveExchangeDataService.reuseFromMainSearchCriteriaObservable.subscribe(
Ne pas oublier de faire un `unsubscribe`. Si trop de variables `Subscription`, pensez à en utiliser qu'un seul avec la methode `add`

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/dissemination-rule-search/dissemination-rule-search.component.ts
> +    merge(this.disseminationRuleCriteriaForm.statusChanges, this.disseminationRuleCriteriaForm.valueChanges)
Ne pas oublier de faire un `unsubscribe`. Si trop de variables `Subscription`, pensez à en utiliser qu'un seul avec la methode `add`

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/dissemination-rule-search/dissemination-rule-search.component.ts
> +    this.disseminationRuleCriteriaForm.get('disseminationRuleTitle').valueChanges.subscribe((value) => {
Ne pas oublier de faire un `unsubscribe`. Si trop de variables `Subscription`, pensez à en utiliser qu'un seul avec la methode `add`

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/criteria-search/criteria-search.component.ts
> +export class CriteriaSearchComponent implements OnInit {
Interface `OnInit` non utilisée à supprimer

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/appraisal-rule-search/appraisal-rule-search.component.ts
> +    merge(this.appraisalRuleCriteriaForm.statusChanges, this.appraisalRuleCriteriaForm.valueChanges)
Ne pas oublier de faire un `unsubscribe`. Si trop de variables `Subscription`, pensez à en utiliser qu'un seul avec la methode `add`

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/appraisal-rule-search/appraisal-rule-search.component.ts
> +    this.appraisalRuleCriteriaForm.get('appraisalRuleTitle').valueChanges.subscribe((value) => {
Ne pas oublier de faire un `unsubscribe`. Si trop de variables `Subscription`, pensez à en utiliser qu'un seul avec la methode `add`

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/access-rule-search/access-rule-search.component.ts
> +    merge(this.accessRuleCriteriaForm.statusChanges, this.accessRuleCriteriaForm.valueChanges)
Ne pas oublier de faire un `unsubscribe`. Si trop de variables `Subscription`, pensez à en utiliser qu'un seul avec la methode `add`

2022-09-26 12:14 UTC, depysk commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/access-rule-search/access-rule-search.component.ts
> +    this.accessRuleCriteriaForm.get('accessRuleTitle').valueChanges.subscribe((value) => {
Ne pas oublier de faire un `unsubscribe`. Si trop de variables `Subscription`, pensez à en utiliser qu'un seul avec la methode `add`

2022-09-26 12:14 UTC, depysk commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/SearchCriteriaHistoryInternalService.java
> +        Assert.isTrue(list != null && list.size() < 10, "L’enregistrement n'est pas possible car vous avez atteint le nombre limite de recherches enregistrées. Veuillez supprimer au moins une de vos
Logger cette assertion

2022-09-26 12:14 UTC, depysk commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/ProjectArchiveUnitInternalService.java
> +    public static String getArchiveUnitTitle(ArchiveUnit archiveUnit) {
Proposition de code avec import static
````
import static org.apache.commons.lang3.StringUtils.isBlank;
import static org.apache.commons.lang3.StringUtils.isEmpty;

...

public static String getArchiveUnitTitle2(ArchiveUnit archiveUnit) {
        if (archiveUnit == null) {
            return null;
        }
        if ((isEmpty(archiveUnit.getTitle()) || isBlank(archiveUnit.getTitle())) && archiveUnit.getTitle_() != null) {
            boolean titleFrIsSpecified = !isEmpty(archiveUnit.getTitle_().getFr()) && !isBlank(archiveUnit.getTitle_().getFr());
            return titleFrIsSpecified? archiveUnit.getTitle_().getFr() : archiveUnit.getTitle_().getEn();
        }
        return archiveUnit.getTitle();
    }
````

2022-09-26 12:14 UTC, depysk commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/ProjectArchiveUnitInternalService.java
> +        if (endDateCriteria.isPresent() &&
Proposition de code, block `if`

````
 if (endDateCriteria.isPresent() &&
            !CollectionUtils.isEmpty(endDateCriteria.get().getValues())) {

            String beginDtStr = endDateCriteria.get().getValues().get(0).getBeginInterval();
            String endDtStr = endDateCriteria.get().getValues().get(0).getEndInterval();
            LocalDateTime beginDt = null;
            if (!StringUtils.isEmpty(beginDtStr)) {
                beginDt = LocalDateTime.parse(beginDtStr, ISO_FRENCH_FORMATER);
            }
            LocalDateTime endDt = null;
            if (!StringUtils.isEmpty(endDtStr)) {
                endDt = LocalDateTime.parse(endDtStr, ISO_FRENCH_FORMATER);
            }
            
            if (beginDt != null && endDt != null) {
                strDateExpirationCriteria = endDt.isAfter(beginDt) ? ONLY_DATE_FRENCH_FORMATTER_WITH_SLASH.format(endDt)
                                                                    : ONLY_DATE_FRENCH_FORMATTER_WITH_SLASH.format(beginDt);
            } else if (beginDt != null) {
                strDateExpirationCriteria = ONLY_DATE_FRENCH_FORMATTER_WITH_SLASH.format(beginDt);
            } else {
                strDateExpirationCriteria = ONLY_DATE_FRENCH_FORMATTER_WITH_SLASH.format(
                    Objects.requireNonNullElseGet(endDt, LocalDateTime::now));
            }
        }
````

2022-09-26 12:23 UTC, GhrabSaifEddine commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/vitamui-snack-bar.module.ts
> +export class VitamUISnackBarModule { }
Pas les clés, qui sont spécifiques au module. Essais de voir le html

2022-09-26 12:52 UTC, bbenaissa commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/vitamui-snack-bar.module.ts
> +export class VitamUISnackBarModule { }
on peut utiliser le service snackBarService, et supprimer completement ce module: exemple :

  create(externalParamProfile: ExternalParamProfile) {
    return this.externalParamProfileApi.create(externalParamProfile).pipe(
      tap(
        (response: ExternalParamProfile) => {
          this.snackBarService.open({
            message: 'EXTERNAL_PARAM_PROFILE.NOTIF_EXTERNAL_PARAM_PROFILE_CREATED',
            icon: 'vitamui-icon-admin-key',
            translateParams: { name: response.name },
          });
        },
        (error) => this.snackBarService.open({ message: error.error.message, translate: false })
      )
    );
  }

2022-09-26 12:53 UTC, bbenaissa commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/vitamui-snack-bar.module.ts
> +export class VitamUISnackBarModule { }
c'est le nouveau service commonisé de la PR de Xelians :)

2022-09-27 08:10 UTC, mohatizaoui commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/dsl/VitamQueryHelper.java
> +        String searchKey, final List<String> searchValues) throws InvalidCreateOperationException {
comme déjà discuté en réunion penser à faire une abstraction au lieu des méthodes static 
pas bloaquant

2022-09-27 08:11 UTC, mohatizaoui approved these changes

2022-09-27 08:17 UTC, oussamasic requested changes

2022-09-27 08:17 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchFacetsInternalService.java
> +import static fr.gouv.vitamui.commons.api.utils.ArchiveSearchConsts.CriteriaCategory.ACCESS_RULE;
un problème de formatage ?

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/vitamui-snack-bar.service.ts
> +/*
ancien texte du copyright, à mettre à jour

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/vitamui-snack-bar.module.ts
> + * modify and/ or redistribute the software under the terms of the CeCILL-C
ancien texte du copyright, à mettre à jour

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/vitamui-snack-bar.service.ts
> +  // tslint:disable-next-line:variable-name
règle à ne pas désactiver

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/vitamui-snack-bar.service.ts
> +    // tslint:disable-next-line:variable-name
Attention, il faut pas désactiver les règles tslint

2022-09-27 08:17 UTC, oussamasic commented on api/api-collect/collect-external-client/src/main/java/fr/gouv/vitamui/collect/external/client/SearchCriteriaHistoryExternalRestClient.java
> + *
Ancien texte du copyright, à modifier

2022-09-27 08:17 UTC, oussamasic commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/SearchCriteriaHistoryExternalController.java
> + * contact@programmevitam.fr
Ancien texte du copyright, à modifier

2022-09-27 08:17 UTC, oussamasic commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/service/SearchCriteriaHistoryExternalService.java
> + *
Ancien texte du copyright, à modifier

2022-09-27 08:17 UTC, oussamasic commented on api/api-collect/collect-internal-client/src/main/java/fr/gouv/vitamui/collect/internal/client/SearchCriteriaHistoryInternalRestClient.java
> + *
Ancien texte du copyright, à modifier

2022-09-27 08:17 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/config/ConverterConfig.java
> + * contact@programmevitam.fr
ancien texte, à mettre à jour

2022-09-27 08:17 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/config/MongoDbConfig.java
> + * This software is a computer program whose purpose is to implement
idem

2022-09-27 08:17 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/dao/SearchCriteriaHistoryRepository.java
> + * This software is a computer program whose purpose is to implement
idem

2022-09-27 08:17 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/domain/SearchCriteriaHistoryCollect.java
> + *
idem

2022-09-27 08:17 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/SearchCriteriaHistoryInternalController.java
> + * This software is a computer program whose purpose is to implement
idem

2022-09-27 08:17 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/SearchCriteriaHistoryInternalController.java
> +        SanityChecker.sanitizeCriteria(dto);
les deux check à inverser, possible d'avoir un NullPointerException si dto est null

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/simple-criteria-search/simple-criteria-search.component.html
> +                style="font-size: 14px; font-weight: 700; color: var(--vitamui-primary)"
style à mettre dans un fichier css, c'est plus propre

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/simple-criteria-search/simple-criteria-search.component.html
> +                <mat-option value="" style="font-size: 14px; font-weight: 700; color: var(--vitamui-primary)">
style à mettre dans un fichier css, c'est plus propre

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/simple-criteria-search/simple-criteria-search.component.html
> +                  <mat-option style="font-size: 14px; font-weight: 700; color: var(--vitamui-primary)"
idem

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/simple-criteria-search/simple-criteria-search.component.html
> +          <div class="col-6 form-control" [ngStyle]="{ 'margin-top': '10px' }">
dans un fichier css c'est plus propre

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/simple-criteria-search/simple-criteria-search.component.ts
> + *
texte to update

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/storage-rule-search/storage-rule-search.component.ts
> + *
à modifier

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/vitamui-snack-bar.service.ts
> +      } as any);
il faut éviter les types any

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/vitamui-snack-bar.service.ts
> +    // just to add the line below
plusieurs commentaires dans le fichier, il faut laisser juste les commentaires nécessaires, les autres à supprimer

2022-09-27 08:17 UTC, oussamasic commented on api/api-security/security-internal/pom.xml
> -            </exclusions>
pourquoi cette suppression ?

2022-09-27 08:17 UTC, oussamasic commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/dsl/VitamQueryHelper.java
> +        projection.put("Name", 1);
pourquoi on ajoute des projections sur Identifier et Name ?

2022-09-27 08:17 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/ProjectArchiveUnitInternalService.java
> +        LOGGER.info("Calling exportToCsvSearchArchiveUnitsByCriteria with query {} ", searchQuery);
debug ?

2022-09-27 08:17 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/ProjectArchiveUnitInternalService.java
> +            LOGGER.info("Calling exporting  export ArchiveUnits to CSV with criteria {}", searchQuery);
debug ?

2022-09-27 08:17 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/SearchCriteriaHistoryInternalService.java
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
to update

2022-09-27 08:17 UTC, oussamasic commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/converters/SearchCriteriaHistoryConverter.java
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
idem

2022-09-27 08:17 UTC, oussamasic commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/dsl/VitamQueryHelper.java
> + * contact.vitam@culture.gouv.fr
idem

2022-09-27 08:17 UTC, oussamasic commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/MetadataSearchCriteriaUtils.java
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
idem

2022-09-27 08:17 UTC, oussamasic commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/dsl/VitamQueryHelper.java
> +    public static JsonNode createQueryDSL(Map<String, Object> searchCriteriaMap,
je pense que cette méthode est utilisée juste quand on souhaite récupérer les services producteurs avec leurs names (on peux la renommer pour plus de signification)

2022-09-27 08:17 UTC, oussamasic commented on commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/MetadataSearchCriteriaUtils.java
> +            LOGGER.debug("Final query: {}", selectMultiQuery.getFinalSelect().toPrettyString());
à mettre dans une constante

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/ProjectArchiveUnitController.java
> +        SanityChecker.sanitizeCriteria(searchQuery);
un check sanitize à ajouter sur projectId aussi

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/service/SearchCriteriaHistoryService.java
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
to update

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-collect.service.ts
> +          console.log('Please update filter to reduce size of response' + errors.message);
console à supprimer, tu peux utiliser le loggerService

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
> +  // Manage lateral panels
des commentaires dans le fichier à supprimer

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
> +  exportArchiveUnitsToCsvFile() {
si l’utilisateur sélectionne plus de 10000 résultats, on affiche pas une pop-up d'avertissement un truc de ce genre ?

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/access-rule-search/access-rule-search.component.ts
> +import { Component, Input, OnDestroy, OnInit } from '@angular/core';
ajoute le texte du copyright

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/appraisal-rule-search/appraisal-rule-search.component.ts
> +import { Component, Input, OnDestroy, OnInit } from '@angular/core';
idem

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/criteria-search/criteria-search.component.scss
> +      //border-radius: 0px 0px 0px 0px;
to delete

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/criteria-search/criteria-search.component.scss
> +      //border-radius: 0px 5px 5px 0px;
to delete

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/criteria-search/criteria-search.component.ts
> +import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
ajoute le texte du copyright

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/search-criteria-list/confirm-action/confirm-action.component.ts
> +export class ConfirmActionComponent implements OnInit {
il sert à quoi ce composant ?

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/search-criteria-list/confirm-action/confirm-action.module.ts
> +export class ConfirmActionModule {
idem, c'est quoi l'utilité de ce module ?

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/search-criteria-list/search-criteria-list.component.spec.ts
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
to update

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/search-criteria-list/search-criteria-list.component.ts
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
idem

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/search-criteria-saver/search-criteria-saver.component.spec.ts
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
idem

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/search-criteria-saver/search-criteria-saver.component.ts
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
idem

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/simple-criteria-search/simple-criteria-search.component.html
> +          <div class="col-6 form-control" [ngStyle]="{ 'margin-right': '50%' }">
à mettre dans le fichier css

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/models/ruleAction.interface.ts
> +import { SearchCriteriaDto } from './search.criteria';
fichier à supprimer, il n'est pas utilisé

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/services/archive-shared-data.service.ts
> +          // tslint:disable-next-line:no-angle-bracket-type-assertion
à ne pas désactiver

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/services/archive-shared-data.service.ts
> +          // tslint:disable-next-line:no-angle-bracket-type-assertion
à ne pas désactiver

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/services/rule.validator.ts
> +/*
to update

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/services/management-rules-shared-data.service.ts
> +/*
to update

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/services/search-criteria-saver.service.ts
> +/*
idem

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/index.ts
> +/*
idem

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/vitamui-snack-bar.component.html
> +      <i class="vitamui-icon vitamui-icon-archive-ingest"></i> Un ou plusieurs versement(s) sont en cours
à traduire

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/vitamui-snack-bar.component.html
> +      <span> (Merci de ne pas éteindre votre navigateur pendant le processus)</span>
à traduire

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/vitamui-snack-bar.component.spec.ts
> +/*
to update

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/vitamui-snack-bar.component.spec.ts
> +  it('should create', () => {
à compléter avec d'autres tests ou à supprimer

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/vitamui-snack-bar.component.ts
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
to update

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/vitamui-snack-bar.component.ts
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
to update

2022-09-27 08:17 UTC, oussamasic commented on api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/service/SearchCriteriaHistoryExternalService.java
> +        LOGGER.debug("service external = Update SearchCriteriaHistory with id :{}", dto.getId());
si dto est null ? NPE dans le logger

2022-09-27 08:17 UTC, oussamasic commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/vitamui-snack-bar.module.ts
> +export class VitamUISnackBarModule { }
je vois pas l’intérêt de créer ce module sachant qu'on a la même chose dans ui-frontend-common (une duplication du code). Pour avoir le même comportement sur l'ensemble des applications VitamUI, il faut utiliser l'existant

2022-09-27 08:59 UTC, GhrabSaifEddine commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/vitamui-snack-bar.module.ts
> +export class VitamUISnackBarModule { }
Avec l'existant, ce n'est pas possible d'appliquer ce service. On attend ce genre de comportement :

```
 {{ 'COLLECT.SEARCH_CRITERIA_SAVER.DELETED_WITH_SUCCESS_1' | translate }} "<strong>{{ data?.name }}</strong> "
      {{ 'COLLECT.SEARCH_CRITERIA_SAVER.DELETED_WITH_SUCCESS_2' | translate }}
```
Avec le service de Xelians, on attend d'avoir un message directe ( ou to translate ) mais on ne peut plus gérer le style html "<strong>"

Je propose de garder l'existant et échanger par rapport une potentielle évolution avec les PO.

2022-09-27 08:59 UTC, GhrabSaifEddine commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/vitamui-snack-bar.module.ts
> +export class VitamUISnackBarModule { }
Avec l'existant, ce n'est pas possible d'appliquer ce service. On attend ce genre de comportement :

```
 {{ 'COLLECT.SEARCH_CRITERIA_SAVER.DELETED_WITH_SUCCESS_1' | translate }} "<strong>{{ data?.name }}</strong> "
      {{ 'COLLECT.SEARCH_CRITERIA_SAVER.DELETED_WITH_SUCCESS_2' | translate }}
```
Avec le service de Xelians, on attend d'avoir un message directe ( ou to translate ) mais on ne peut plus gérer le style html "<strong>"

Je propose de garder l'existant et échanger par rapport une potentielle évolution avec les PO.

2022-09-27 08:59 UTC, GhrabSaifEddine commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/vitamui-snack-bar.module.ts
> +export class VitamUISnackBarModule { }
Avec l'existant, ce n'est pas possible d'appliquer ce service. On attend ce genre de comportement :

```
 {{ 'COLLECT.SEARCH_CRITERIA_SAVER.DELETED_WITH_SUCCESS_1' | translate }} "<strong>{{ data?.name }}</strong> "
      {{ 'COLLECT.SEARCH_CRITERIA_SAVER.DELETED_WITH_SUCCESS_2' | translate }}
```
Avec le service de Xelians, on attend d'avoir un message directe ( ou to translate ) mais on ne peut plus gérer le style html "<strong>"

Je propose de garder l'existant et échanger par rapport une potentielle évolution avec les PO.

2022-09-27 09:49 UTC, GhrabSaifEddine commented on ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/services/archive-facets.service.ts
> +  extractNodesFacetsResults(facetResults: ResultFacetList[]): ResultFacet[] {
ton code ne compile pas

2022-09-27 11:57 UTC, GhrabSaifEddine commented on api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/ProjectArchiveUnitInternalService.java
> +    public static String getArchiveUnitTitle(ArchiveUnit archiveUnit) {
J'ai mis plutôt :

```
if (archiveUnit == null) {
            return null;
        }
        if (isNotBlank(archiveUnit.getTitle())) {
            return archiveUnit.getTitle();
        }
        if (archiveUnit.getTitle_() != null) {
            return isNotBlank(archiveUnit.getTitle_().getFr()) && isNotBlank(archiveUnit.getTitle_().getFr()) ?
                archiveUnit.getTitle_().getFr() :
                archiveUnit.getTitle_().getEn();
        }
        LOGGER.debug("Archive unit Title and Title_ are empty!");
        return null;
```

2022-09-27 12:12 UTC, GhrabSaifEddine commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/vitamui-snack-bar.component.spec.ts
> +  it('should create', () => {
On teste la création du component, c'est un test basic, ni + ni - à rajouter et je ne pense pas qu'on doit le supprimer..

2022-09-27 13:20 UTC, GhrabSaifEddine commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/vitamui-snack-bar.module.ts
> +export class VitamUISnackBarModule { }
j'ai déjà répondu à @depysk et @bbenaissa dans un commentaire en haut. Je t'invites à lire la discussion

2022-09-27 13:20 UTC, GhrabSaifEddine commented on ui/ui-frontend/projects/collect/src/app/collect/shared/vitamui-snack-bar/vitamui-snack-bar.module.ts
> +export class VitamUISnackBarModule { }
j'ai déjà répondu à @depysk et @bbenaissa dans un commentaire sur le même sujet en haut. Je t'invites à lire la discussion

2022-09-28 09:08 UTC, depysk approved these changes

2022-09-29 13:42 UTC, oussamasic approved these changes

2022-09-29 15:44 UTC, merged