[VAS][WIP] 10151 : add acknowledgment transfer operation to VitamUI
ProgrammeVitam/vitam-ui pull request #985
Opened 2022-09-23 15:02 UTC by oussamasic

## Description
L'objectif de cette PR est de traiter l'US 10151.
L'US concerne la fonctionnalité d'acquittement du transfert.

## Type de changement:

*Indiquer le ou les types de changements*

* Ansiblerie
* Nouveau Code
* Correction
* Refactorisation de code

## Tests:

manuel
environnement
TU

## Checklist:

[ X ]  Mon code suit le style de code de ce projet.

[ X ] J'ai commenté mon code, en particulier dans les classes et les méthodes difficile à comprendre.

[ ] J'ai fait les changements correspondant dans la documentation RAML.

[ X ]  J'ai fait les changements correspondant dans la documentation Métier.

[ X ]  J'ai fait les changements correspondant dans la documentation Technique.

[ X ] J'ai rajouté les tests unitaires vérifiant mes fonctionnalités.

[ ] J'ai rajouté les tests de non régression vérifiant mes fonctionnalités.

[ X ] Les tests unitaires nouveaux et existants passent avec succès localement.

[ X ] Toutes les dépendances ont été mergées en priorité

## Contributeur

VAS (Vitam Accessible en Service)

2022-09-26 14:01 UTC, bbenaissa requested changes

2022-09-26 14:01 UTC, bbenaissa commented on api/api-archive-search/archive-search-external/src/test/java/fr/gouv/vitamui/archives/search/external/server/rest/ArchivesSearchExternalControllerTest.java
> +            .when(archivesSearchExternalService.transferAcknowledgment(null, fileName))
Le mieux est de changer le null par un any(InputStream.class)

2022-09-26 14:01 UTC, bbenaissa commented on api/api-archive-search/archive-search-external/src/test/java/fr/gouv/vitamui/archives/search/external/server/rest/ArchivesSearchExternalControllerTest.java
> +            .when(archivesSearchExternalService.transferAcknowledgment(null, fileName))
le null normalement est censé générer une erreur?

2022-09-26 14:01 UTC, bbenaissa commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/TransferAcknowledgmentInternalService.java
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2015-2022)
Je ne vois d'interet à créer un nouveau service, on a déjà un service 'Transfert' et qui ne contient pas grande chose

2022-09-26 14:01 UTC, bbenaissa commented on ui/ui-frontend/package.json
> +    "@types/xml2js": "0.4.3",
le choix de la version fixe pour une raison ?

2022-09-26 14:01 UTC, bbenaissa commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
> +    <div class="coll-1 form-control">
col-1 au lieu de coll-1

2022-09-30 09:17 UTC, oussamasic commented on api/api-archive-search/archive-search-external/src/test/java/fr/gouv/vitamui/archives/search/external/server/rest/ArchivesSearchExternalControllerTest.java
> +            .when(archivesSearchExternalService.transferAcknowledgment(null, fileName))
Corrigé.
le null ne pose pas problème (Vitam envoie après une erreur sur ça)

2022-09-30 09:18 UTC, oussamasic commented on api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/TransferAcknowledgmentInternalService.java
> + * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2015-2022)
Done, les deux services sont fusionnés (transfer reply et transferRequest)

2022-09-30 09:18 UTC, oussamasic commented on ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
> +    <div class="coll-1 form-control">
Corrigé

2022-09-30 09:18 UTC, oussamasic commented on ui/ui-frontend/package.json
> +    "@types/xml2js": "0.4.3",
modifié pour prendre toujours la dernière version

2022-09-30 15:15 UTC, bbenaissa approved these changes

2022-09-30 15:54 UTC, laedanrex approved these changes

2022-09-30 17:04 UTC, merged