Feature/VAS-10004: stop using tenant 2 as a vitamui tenant for auto r…
ProgrammeVitam/vitam-ui pull request #987
Opened 2022-09-28 14:11 UTC by bbenaissa

L'objectif de cette PR est de supprimer la réservation du tenant 2, et documenter la procédure pour les anciennes versions 

## Contributeur

VAS (Vitam Accessible en Service)

2022-09-28 15:01 UTC, GiooDev requested changes

2022-09-28 15:01 UTC, GiooDev commented on docs/Exploitation.md
> +dans `deployment/environnement/group_vars/all/vitamui_vars.yml`.
Pourquoi il y a des sauts de ligne ajoutées ici ?

2022-09-28 15:01 UTC, GiooDev commented on docs/Exploitation.md
> +  base mongo.
idem, saut de ligne à retirer

2022-09-28 15:01 UTC, GiooDev commented on docs/Exploitation.md
> +chemin: `/vitamui/conf/ui-xxx/application.yml`
etc

2022-09-28 15:49 UTC, GiooDev commented
Je pense qu'il est plus pertinent de conserver le script de nettoyage de ce tenant 2 car il y a peu de chance que l'utilisateur ait créé un tenant en l'appelant auto_tenant.

2022-09-29 09:21 UTC, bbenaissa commented
Effectivement, comme discuté, les controles ajoutés sur la suppression du tenant 2 et son profil sont suffisants. et au niveau du paramètre first_customer_tenant:2 , la collection sequences contient pour la valeur tenants cette valeur (2), qui correspond au dernier tenant existant, le prochain tenant sera le 3.

Suite à tous ces élements, cette PR pourra être cloturée.

2022-09-29 13:12 UTC, closed without merging